### ISSUE TITLE
Routing rules containing geoip are ignored if AsIs or IPIfNoMatch is used as Domain resolution strategy

### ISSUE THREAD

**Issue by molink36** [v2fly/v2ray-core#1008]
### 1. What version of V2Ray are you using?
I am using V2Ray v4.38.3 installed on OpenWRT v19.07.7.
### 2. What's your scenario of using V2Ray?
I am using V2Ray as a client.
### 3. What problems have you encountered?
Routing rules containing `geoip` are ignored if I use `AsIs` or `IPIfNoMatch` as Domain resolution strategy. However, rules containing `geoip` work if `IPOnDemand` is selected as Domain resolution strategy.
### 4. What's your expectation?
I expected routing rules containing `geoip` to work and get applied like rules containing `IP/CIDR` or `geosite`.
### 5. Please attach your configuration here:

```
{
	"routing": {
		"domainStrategy": "IPIfNoMatch",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:us",
					"10.0.0.0/8"
				],
				"network": "tcp,udp",
				"outboundTag": "Direct"
			}
		]
	},
	"inbounds": [
		{
			"port": 1080,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp,udp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "redirect"
				}
			},
			"tag": "Redirect",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "AsIs"
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "Direct"
		},
		{
			"protocol": "blackhole",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"tag": "Block"
		}
	]
}
```

**Comment by Loyalsoldier** [comment]
IPIfNonMatch

**Comment by molink36** [comment]
I am sorry I had typed IPIfNonMatch here wrong. Actually neither IPIfNonMatch nor AsIs works with geoip for me. I still have the same problem.

**Comment by Loyalsoldier** [comment]
I can't reproduce this. You can try to remove line `"network": "tcp,udp",` from the rule.

**Comment by molink36** [comment]
@Loyalsoldier I deleted "network": `"tcp,udp",` from the routing rules, but the problem still persists. Something is wrong with v2ray on my OpenWRT router.
Anyway, thank you.
