### ISSUE TITLE
quic配置访问不通，在本地用go编译后运行,服务器和server都在本地,用localhost访问。

### ISSUE THREAD

**Issue by bipo123** [v2fly/v2ray-core#1024]
## 你正在使用哪个版本的 V2Ray？

V2Ray 4.39.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 darwin/amd64)
## 你看到的异常现象是什么？
访问不通
## 你期待看到的正常表现是怎样的？
无
## 请附上你的配置

**服务端配置：**
	{
			"port": 21634,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "9e736602-ff90-41e3-8dff-ce7a678ab341",
						"level": 1,
						"alterId": 0
					}
				]
			},
			"streamSettings": {
				"network": "quic",
				"security": "tls",
				"quicSettings": {
					"security": "none",
					"key": "",
					"header": {
						"type": "none"
					}
				},
				"tlsSettings": {
					"certificates": [
					  {
						"certificateFile": "./cert.der",
						"keyFile": "./key.der"
					  }
					]
				  }
			}
		}

**客户端配置：**
// 在这里附上客户端配置
 "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "localhost",
            "port": 21634,
            "users": [
              {
                "id": "9e736602-ff90-41e3-8dff-ce7a678ab341",
                "alterId": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "quic",
        "security": "tls"
      }
    }
  ]

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**
2021/05/21 09:14:45 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
```javascript
// 在这里附上服务器端日志

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

2021/05/21 09:14:57 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [Timeout: No recent network activity] > common/retry: all retry attempts failed

## 请附上访问日志

<!-- 在 Linux 中，访问日志通常在 `/var/log/v2ray/access.log` 文件中 -->

```javascript
// 在这里附上服务器端日志

```

**Comment by AkinoKaede** [comment]
```
sysctl -w net.core.rmem_max=2500000
```

**Comment by bipo123** [comment]
> ```
> sysctl -w net.core.rmem_max=2500000
> ```
> 
> 那不是写的很清楚嘛…不过 MacOS 能不能这么做我就不知道了
我在macos 上或者linux 上都试过了都不行，centos 比2500000 值都大，还是报同样的错误。
然后我又把 v2ray 降级到 4.29.0，没报这个错误了，但是还是访问不同。

**Comment by kingwilliam** [comment]
我是用 ubuntu 20.04, 最近也在测试 quic 但也是出现

connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. 
See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

已跟指示设定 但还是不行
sysctl -w net.core.rmem_max=2500000

请问还有什麽可以设定?

**Comment by wangshengxin1998** [comment]
QUIC目前已经标准化完成 RFC9000 希望v2ray能尽快跟进

**Comment by AkinoKaede** [comment]
> QUIC目前已经标准化完成 RFC9000 希望v2ray能尽快跟进

V2Ray 所依赖的 quic-go 已实现 rfc9000。

**Comment by wangshengxin1998** [comment]
> V2Ray 所依赖的 quic-go 已实现 rfc9000。

```
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "----",
            "level": 1,
            "flow": "xtls-rprx-direct"
          }
        ],
      "decryption": "none",
      "fallbacks": [
        {
          "dest": 17395
        }
      ]
      },
      "streamSettings": {
        "network": "quic",
        "security": "tls",
        "tlssettings": {
          "certificates": [
            {
              "ocspStapling": 3600,
              "certificate": [
                "-----BEGIN CERTIFICATE-----",
                "-----END CERTIFICATE-----"
              ],
              "key": [
                "-----BEGIN PRIVATE KEY-----",
                "-----END PRIVATE KEY-----"
              ]
            }
          ]
        }
      }
    }
```
配置完测试连不上,服务端输出如下:
```
9月 30 05:56:43 kr-vps systemd[1]: Started Xray Service.
9月 30 05:56:43 kr-vps xray[75248]: Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)
9月 30 05:56:43 kr-vps xray[75248]: A unified platform for anti-censorship.
9月 30 05:56:43 kr-vps xray[75248]: 2021/09/30 05:56:43 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
9月 30 05:56:43 kr-vps xray[75248]: 2021/09/30 05:56:43 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
9月 30 05:56:43 kr-vps xray[75248]: 2021/09/30 05:56:43 [Warning] core: Xray 1.4.5 started
```

**Comment by AkinoKaede** [comment]
> > V2Ray 所依赖的 quic-go 已实现 rfc9000。
> 
> ```
>     {
>       "port": 443,
>       "protocol": "vless",
>       "settings": {
>         "clients": [
>           {
>             "id": "----",
>             "level": 1,
>             "flow": "xtls-rprx-direct"
>           }
>         ],
>       "decryption": "none",
>       "fallbacks": [
>         {
>           "dest": 17395
>         }
>       ]
>       },
>       "streamSettings": {
>         "network": "quic",
>         "security": "tls",
>         "tlssettings": {
>           "certificates": [
>             {
>               "ocspStapling": 3600,
>               "certificate": [
>                 "-----BEGIN CERTIFICATE-----",
>                 "-----END CERTIFICATE-----"
>               ],
>               "key": [
>                 "-----BEGIN PRIVATE KEY-----",
>                 "-----END PRIVATE KEY-----"
>               ]
>             }
>           ]
>         }
>       }
>     }
> ```
> 
> 以上是相关配置文件的片段,配置完测试连不上,服务端输出如下:
> 
> ```
> 9月 30 05:56:43 kr-vps systemd[1]: Started Xray Service.
> 9月 30 05:56:43 kr-vps xray[75248]: Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)
> 9月 30 05:56:43 kr-vps xray[75248]: A unified platform for anti-censorship.
> 9月 30 05:56:43 kr-vps xray[75248]: 2021/09/30 05:56:43 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
> 9月 30 05:56:43 kr-vps xray[75248]: 2021/09/30 05:56:43 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
> 9月 30 05:56:43 kr-vps xray[75248]: 2021/09/30 05:56:43 [Warning] core: Xray 1.4.5 started
> ```

非 V2Ray 问题请不要在此讨论…

**Comment by wangshengxin1998** [comment]
> 非 V2Ray 问题请不要在此讨论…
V2Ray的原作者很早就打算[支持QUIC传输](https://twitter.com/projectv2ray/status/1081466539994431488?s=20),如今QUIC已经标准化;希望能尽快更新相关的说明文档

**Comment by Kylejustknows** [comment]
9月 30 05:56:43 kr-vps xray[75248]: 2021/09/30 05:56:43 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

这是一个quic-go升级BUG，最近在所有使用quic-go的项目上都出现很多报错。
sysctl -w net.core.rmem_max=2500000 也只是一个临时抢救方案，也只有一部分系统能用。

正确的解决方法quic-go报错已经写得非常明确了  ： 使用  net.UDPConn （而不是 net.PacketConn等），这样quic-go就能正确探测操作系统支持的缓存大小。

**Comment by AkinoKaede** [comment]
@Kylejustknows Thanks very much, I will try to solve it.

**Comment by yaott2020-666** [comment]
所以有解吗

**Comment by AkinoKaede** [comment]
顺带一提，因为 Linux 默认的 Buffer 实在是太小了，所以仍然需要[修改 Buffer 大小](https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size)。

```
sysctl -w net.core.rmem_max=2500000
```

**Comment by Peterbini** [comment]
sysctl -w net.core.rmem_max=2500000  这个没有用！This is useless！

**Comment by Peterbini** [comment]
debian11 sysctl -w net.core.rmem_max=2500000 这个也不起作用

**Comment by PanHsin** [comment]
sysctl -w net.core.rmem_max=2500000 这个命令对当前终端有效，重启实例后失效了，又恢复到之前的状态。
所以尝试通过修改sysctl.conf来解决这个问题：

echo "net.core.rmem_max=2500000" >> /etc/sysctl.conf
sysctl -p

检查修改效果：
sysctl -a | grep rmem_max

reboot后 再次检查仍保持。

**Comment by Peterbini** [comment]
> sysctl -w net.core.rmem_max=2500000 这个命令对当前终端有效，重启实例后失效了，又恢复到之前的状态。 所以尝试通过修改sysctl.conf来解决这个问题：
> 
> echo "net.core.rmem_max=2500000" >> /etc/sysctl.conf sysctl -p
> 
> 检查修改效果： sysctl -a | grep rmem_max
> 
> reboot后 再次检查，仍保持。

Thank you! debian11已解决！

**Comment by Peterbini** [comment]
manjaro 这个设置不起作用 sysctl -w net.core.rmem_max=2500000

**Comment by Scarecrow928** [comment]
4.44.0还没应用这个更新啊，只能等5了吗😢
```
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
2022/04/29 10:04:56 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
2022/04/29 10:04:57 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
```
