### ISSUE TITLE
[bug] grpc 不接受来自 X-Real-IP 的 ip 作为客户端 ip

### ISSUE THREAD

**Issue by rhjdvsgsgks** [v2fly/v2ray-core#1026]
## 你正在使用哪个版本的 V2Ray？

4.38.3

## 你的使用场景是什么？

使用 nginx 反代 v2ray 提供的 grpc ，使用 X-Real-IP 传入真实客户端地址

## 你看到的异常现象是什么？

v2ray log 中客户端地址显示为 127.0.0.1

## 你期待看到的正常表现是怎样的？

像 websocket 一样将 X-Real-IP 提供的地址作为客户端 ip

## 请附上你的配置

**服务端配置：**

```javascript
{
  "sniffing": {
    "enabled": true,
    "destOverride": [
      "http",
      "tls"
    ]
  },
  "listen": "127.0.0.1",
  "port": 123,
  "protocol": "vmess",
  "settings": {
    "clients": [
      {}
    ],
    "disableInsecureEncryption": true
  },
  "streamSettings": {
    "network": "grpc",
    "grpcSettings": {
      "serviceName": "aaa"
    },
    "sockopt": {
      "tcpFastOpen": true
    }
  },
  "tag": "grpc"
}

```

**客户端配置：**

```javascript
{
  "protocol": "vmess",
  "settings": {
    "vnext": [
      {
        "address": "x.x.x.x",
        "port": 443,
        "users": [
          {}
        ]
      }
    ]
  },
  "streamSettings": {
    "grpcSettings": {
      "serviceName": "aaa"
    },
    "network": "grpc",
    "security": "tls",
    "tlsSettings": {
      "serverName": "aaa.bb"
    }
  },
  "tag": "proxy"
}

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

无

**客户端错误日志：**

无

## 请附上访问日志

```
127.0.0.1:xxxxx accepted tcp:www.google.com:80 email:xxx
```

## 其它相关的配置文件（如 Nginx）和相关日志

nginx.site.conf
```nginx
location /aaa {
        grpc_pass grpc://127.0.0.1:123;
        grpc_set_header Host $http_host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

https://github.com/grpc/grpc-go/issues/3121

**Comment by AkinoKaede** [comment]
目前是不支持，我试着改一下，不过 WebSocket 用的是 `X-Forwarded-For`

**Comment by IRN-Kawakaze** [comment]
> 
> 
> 目前是不支持的，目前应该可以用 `Proxy Protocol`。BTW， WebSocket 用的是 `X-Forwarded-For`
> 稍微改了下，没试过，有兴趣帮忙测试下吗
> 
> https://github.com/AkinoKaede/v2ray-core/tree/feat-grpc-x-real-ip

试了一下，有用，配合nginx可以在日志里显示X-Real-IP了。

**Comment by AkinoKaede** [comment]
> > 目前是不支持的，目前应该可以用 `Proxy Protocol`。BTW， WebSocket 用的是 `X-Forwarded-For`
> > 稍微改了下，没试过，有兴趣帮忙测试下吗
> > https://github.com/AkinoKaede/v2ray-core/tree/feat-grpc-x-real-ip
> 
> 试了一下，有用，配合nginx可以在日志里显示X-Real-IP了。

感谢测试，不过我现在在纠结是使用 `X-Real-IP` 还是 改成 `X-Forwared-For`，或者可能不需要这个特性…
@xiaokangwang 我需要一些意见。

**Comment by xiaokangwang** [comment]
我之前的截图里面没这个，我也不太清楚，但是我觉得X-Forwarded-For更通用一点。这个可能需要额外的测试。

**Comment by rhjdvsgsgks** [comment]
> > > 目前是不支持的，目前应该可以用 `Proxy Protocol`。BTW， WebSocket 用的是 `X-Forwarded-For`
> > > 稍微改了下，没试过，有兴趣帮忙测试下吗
> > > https://github.com/AkinoKaede/v2ray-core/tree/feat-grpc-x-real-ip
> > 
> > 
> > 试了一下，有用，配合nginx可以在日志里显示X-Real-IP了。
> 
> 感谢测试，不过我现在在纠结是使用 `X-Real-IP` 还是改成 `X-Forwarded-For`，或者可能不需要这个特性…

用 X-Forwarded-For 吧，一是 websocket 也用的这个，二是有相应的标准而 x-real-ip 没有，我之前说 x-real-ip 也只是因为碰巧搜到了相关的 issue

**Comment by AkinoKaede** [comment]
> > > > 目前是不支持的，目前应该可以用 `Proxy Protocol`。BTW， WebSocket 用的是 `X-Forwarded-For`
> > > > 稍微改了下，没试过，有兴趣帮忙测试下吗
> > > > https://github.com/AkinoKaede/v2ray-core/tree/feat-grpc-x-real-ip
> > > 
> > > 
> > > 试了一下，有用，配合nginx可以在日志里显示X-Real-IP了。
> > 
> > 
> > 感谢测试，不过我现在在纠结是使用 `X-Real-IP` 还是改成 `X-Forwarded-For`，或者可能不需要这个特性…
> 
> 用 X-Forwarded-For 吧，一是 websocket 也用的这个，二是有相应的标准而 x-real-ip 没有，我之前说 x-real-ip 也只是因为碰巧搜到了相关的 issue

OK

**Comment by AkinoKaede** [comment]
@rhjdvsgsgks 改成了 `X-Forwarded-For` 了，能帮忙再测试下吗
https://github.com/AkinoKaede/v2ray-core/tree/feat-grpc-x-forwarded-for

**Comment by IRN-Kawakaze** [comment]
> 
> 
> @IRN-Kawakaze 改成了 `X-Forwarded-For` 了，方便帮忙再测试下吗
> https://github.com/AkinoKaede/v2ray-core/tree/feat-grpc-x-forwarded-for

有用，日志里可以显示 X-Forwarded-For 提供的IP。

**Comment by rhjdvsgsgks** [comment]
> @IRN-Kawakaze 改成了 `X-Forwarded-For` 了，方便帮忙再测试下吗
> https://github.com/AkinoKaede/v2ray-core/tree/feat-grpc-x-forwarded-for

如果我没理解错这是取的 x-forwarded-for 的第一个 ip ，而如果想取得发起连接者的ip（nginx 处理客户端伪造的 xff 头时会将其放在真实 ip 之前）应该取最后一个ip，可以参考
https://imququ.com/post/x-forwarded-for-header-in-http.html

**Comment by rhjdvsgsgks** [comment]
> 如果我没理解错这是取的 x-forwarded-for 的第一个 ip ，而如果想取得发起连接者的ip（nginx 处理客户端伪造的 xff 头时会将其放在真实 ip 之前）应该取最后一个ip，可以参考
> https://imququ.com/post/x-forwarded-for-header-in-http.html

https://github.com/v2fly/v2ray-core/blob/c66a1678daeae4cc1cc83b9b91c705ba386fb48a/transport/internet/http/hub.go#L100
https://github.com/v2fly/v2ray-core/blob/6f8979d017c67f72734efebaa8685229d40d7540/transport/internet/websocket/hub.go#L76

突然发现现有的方案也是选择 xff 中的第一个 ip ，也就是说可以伪装客户端 ip ？我测试下

**Comment by rhjdvsgsgks** [comment]
> > 如果我没理解错这是取的 x-forwarded-for 的第一个 ip ，而如果想取得发起连接者的ip（nginx 处理客户端伪造的 xff 头时会将其放在真实 ip 之前）应该取最后一个ip，可以参考
> > https://imququ.com/post/x-forwarded-for-header-in-http.html
> 
> https://github.com/v2fly/v2ray-core/blob/c66a1678daeae4cc1cc83b9b91c705ba386fb48a/transport/internet/http/hub.go#L100
> 
> https://github.com/v2fly/v2ray-core/blob/6f8979d017c67f72734efebaa8685229d40d7540/transport/internet/websocket/hub.go#L76
> 
> 突然发现现有的方案也是选择 xff 中的第一个 ip ，也就是说可以伪装客户端 ip ？我测试下

成功了，我在客户端用 nginx 反代 websocket 同时加了 header xff 为 1.2.3.4 ，在服务端的 v2ray log 中显示
```
1.2.3.4:0 accepted tcp:x.x.x.x:443 email:xx
```

**Comment by Loyalsoldier** [comment]
印象中 `X-Forwarded-For` 列表中最后一个 IP 才是真实 IP 地址。

**Comment by AkinoKaede** [comment]
> > > 如果我没理解错这是取的 x-forwarded-for 的第一个 ip ，而如果想取得发起连接者的ip（nginx 处理客户端伪造的 xff 头时会将其放在真实 ip 之前）应该取最后一个ip，可以参考
> > > https://imququ.com/post/x-forwarded-for-header-in-http.html
> > 
> > 
> > https://github.com/v2fly/v2ray-core/blob/c66a1678daeae4cc1cc83b9b91c705ba386fb48a/transport/internet/http/hub.go#L100
> > 
> > https://github.com/v2fly/v2ray-core/blob/6f8979d017c67f72734efebaa8685229d40d7540/transport/internet/websocket/hub.go#L76
> > 
> > 突然发现现有的方案也是选择 xff 中的第一个 ip ，也就是说可以伪装客户端 ip ？我测试下
> 
> 成功了，我在客户端用 nginx 反代 websocket 同时加了 header xff 为 1.2.3.4 ，在服务端的 v2ray log 中显示
> 
> ```
> 1.2.3.4:0 accepted tcp:x.x.x.x:443 email:xx
> ```

感谢

**Comment by AkinoKaede** [comment]
@Loyalsoldier @rhjdvsgsgks 
改成最后一个可能也会引起一些问题，比如如果经过了多个可信的 (反向) 代理都加了 `X-Forwarded-For`。

还有一些问题，比如不经过代理，直接伪造 `X-Forwarded-For`，也会让入站的 V2Ray 错误地判断 IP 地址。

我觉得这个功能可能需要一些改动，至少应该加个开关…

**Comment by AkinoKaede** [comment]
鉴于有点跑题了，开了个新的 Issues #1037

**Comment by Loyalsoldier** [comment]
`X-Forwarded-For` 就是可以伪造的。
我上面的意思是说，在不伪造 `X-Forwarded-For` 的情况下，我印象中最后一个 IP 才是真实 IP 地址。

**Comment by database64128** [comment]
To balance security and simplicity, I recommend we follow `X-Real-IP -> X-Forwarded-For -> Connecting IP` when obtaining the client real IP. Because it's usually easier to make sure `X-Real-IP` is the actual client IP, while preserving `X-Forwarded-For` as-is for later use.

In a typical setup where we have V2Ray behind a reverse proxy like NGINX:

1. To prevent IP spoofing, it's easy to configure the `ngx_http_realip_module` to collect the client real IP from trusted sources and then set it as `X-Real-IP`. The original `X-Forwarded-For` chain can be preserved and passed to V2Ray. The module is optional, but popular distributions including Arch, Fedora, Debian, all have this module enabled in their packaged version of nginx.
2. If client IP spoofing is not a concern, just leave it as is and everything will still work.
3. Cloudflare strips `X-Real-IP`, sets `CF-Connecting-IP` and appends `X-Forwarded-For`. Some other CDN providers set `X-Real-IP` and appends `X-Forwarded-For`.

My projects also follow this strategy. Some configuration examples: https://github.com/database64128/shadowsocks-uri-generator/blob/master/docs/reverse-proxy-guide.md, https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-, https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs

**Comment by onlyJinx** [comment]
不好意思，请问这个issue有进展吗？我现在使用vless-grpc仍然无法再v2ray日志里查看访问ip，全都是127.0.0.1. 有什么临时解决方案吗？

**Comment by chika0801** [comment]
> 不好意思，请问这个问题有进展吗？我现在可以使用vless-grpc 还可以再v2ray 日志里查看访问ip，都是127.0.0.1。有什么临时解决方案吗？

https://github.com/v2fly/v2ray-core/pull/1032

我认为没有合并，这个PR还在，只是通过了？

**Comment by rhjdvsgsgks** [comment]
隔壁 xray 有了，这边不考虑合一下吗？
https://github.com/XTLS/Xray-core/pull/769

> @Loyalsoldier @rhjdvsgsgks 改成最后一个可能也会引起一些问题，比如如果经过了多个可信的 (反向) 代理都加了 `X-Forwarded-For`。当然这个问题应该没有伪造 XFF 严重。
> 
> 还有一些问题，就算改成最后一个，比如不经过代理，直接伪造 `X-Forwarded-For`，也会让入站的 V2Ray 错误地判断 IP 地址。
> 
> 我觉得这个功能可能需要一些改动，至少应该加个开关…

确实，现在我也认为 X-Real-IP 是更好的方案，且其格式与 X-Forwarded-For 相比，和 cloudflare 推荐的 CF-Connecting-IP 一样
https://developers.cloudflare.com/fundamentals/get-started/http-request-headers

**Comment by Loyalsoldier** [comment]
您好，邮件已收到。
