### ISSUE TITLE
Outbound block bittorrent does not work. Torrents are still able to download.

### ISSUE THREAD

**Issue by Heclalava** [v2fly/v2ray-core#1042]
## 你的使用场景是什么？

Using Qbittorent to download torrents while connected to v2ray. Would expect the torrent to not be downloadable, yet it downloads no problem. 

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```
{
  "inbounds": [{
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
    "port": 8388,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "e371bdbd-f3b9-4f8c-acf8-4639cb4c0df1",
          "level": 1,
          "alterId": 0,
          "security": "auto"
        }
      ]
    },
    "streamSettings": {
	      "network": "ws",
	      "wsSettings": {
	        "path": "/websocket/"
	       	            }
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "block",
          "protocol": ["bittorrent"]
      }
    ]
  }
}

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```
No such file exists
**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

File is empty

```javascript
// 在这里附上服务器端日志

```

## 其它相关的配置文件（如 Nginx）和相关日志

Websocket runs through a reverse proxy on Nginx, but no issues there, connection through v2ray is normal and as expected. 

## 如果 V2Ray 服务运行异常，请附上 journal 日志

If v2ray is unable to block bittorrent, and I have tried various other methods such as host file blocking of trackers, IPTables rules with L7 filtering, and none of this works. How does one effectively block torrents on the VPS?

**Comment by kingwilliam** [comment]
try to modify
```
{
    "type": "field",
    // "ip": ["geoip:private"],     <-- remark this line
    "outboundTag": "block",
    "protocol": ["bittorrent"]
}
```

**Comment by Heclalava** [comment]
@kingwilliam Thanks. I tried this but torrents are still able to get through. I decided to go with a decent script which I found here on GitHub that uses a combination of L7 IPTables filtering and hosts file blocking. This has stopped torrents on the servers that I don't wan't clients to use BT on.

**Comment by OxygenLiu** [comment]
@Heclalava Would you please share the script? Thank you in advance!

**Comment by Heclalava** [comment]
You can check it in my repository.

**Comment by rr923** [comment]
This issue is still there in ver 5.20.0, seems the following rule doesn't work at all. Is it possible to fix is ? Or do we have any workaround for it?

`      {
        "type": "field",
        "outboundTag": "block",
        "protocol": ["bittorrent"]
      }`
