### ISSUE TITLE
socks5 outbound not working if socks5 authorization is enabled

### ISSUE THREAD

**Issue by kyze8439690** [v2fly/v2ray-core#1048]
## What version of V2Ray are you using?

4.93.2

## What's your scenario of using V2Ray?

Use v2ray to redirect my traffic to local lan socks5 server with authorization on

## What problems have you encountered?

Socks5 outbound not working if socks5 authorization is enabled
If I disable socks5 authorization on both side(client and server), everything works as expected.

## What's your expectation?

Support socks5+auth according to https://datatracker.ietf.org/doc/html/rfc1928 and https://datatracker.ietf.org/doc/html/rfc1929

## Please attach your configuration here

**Server configuration:**

```javascript
// Please attach your server configuration here.
gost -D -L username:password@:1234
```

**Client configuration:**

```javascript
// Please attach your client configuration here.
    "outbounds": [
        {
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "192.168.1.8",
                        "port": 1234,
                        "users": [
                            {
                                "user": "username",
                                "pass": "password"
                            }
                        ]
                    }
                ]
            }
        }
    ]
```

** Wireshark traffic info
![image](https://user-images.githubusercontent.com/1637169/120357915-87459000-c338-11eb-97a3-ea6043b1364e.png)

Look into the traffic detail, it seems that v2ray combines **socks hello packet** and **socks auth packet**, which is `050102` and `0108username08password`. According to RFC document I list above, we should send these two packet separately.

**Comment by kyze8439690** [comment]
https://github.com/v2fly/v2ray-core/commit/664b840812b810e8d7ffef0f117ab45d9933693d

**Comment by kyze8439690** [comment]
Sharing patch below to make socks-auth working, I don't whether it cause any breaking change, use at your own risk

```diff
diff --git a/proxy/socks/protocol.go b/proxy/socks/protocol.go
index 66d10d16..72328bfb 100644
--- a/proxy/socks/protocol.go
+++ b/proxy/socks/protocol.go
@@ -415,15 +415,6 @@ func ClientHandshake(request *protocol.RequestHeader, reader io.Reader, writer i
 	defer b.Release()
 
 	common.Must2(b.Write([]byte{socks5Version, 0x01, authByte}))
-	if authByte == authPassword {
-		account := request.User.Account.(*Account)
-
-		common.Must(b.WriteByte(0x01))
-		common.Must(b.WriteByte(byte(len(account.Username))))
-		common.Must2(b.WriteString(account.Username))
-		common.Must(b.WriteByte(byte(len(account.Password))))
-		common.Must2(b.WriteString(account.Password))
-	}
 
 	if err := buf.WriteAllBytes(writer, b.Bytes()); err != nil {
 		return nil, err
@@ -441,6 +432,21 @@ func ClientHandshake(request *protocol.RequestHeader, reader io.Reader, writer i
 		return nil, newError("auth method not supported.").AtWarning()
 	}
 
+	if authByte == authPassword {
+		account := request.User.Account.(*Account)
+
+        b.Clear()
+		common.Must(b.WriteByte(0x01))
+		common.Must(b.WriteByte(byte(len(account.Username))))
+		common.Must2(b.WriteString(account.Username))
+		common.Must(b.WriteByte(byte(len(account.Password))))
+		common.Must2(b.WriteString(account.Password))
+	}
+
+	if err := buf.WriteAllBytes(writer, b.Bytes()); err != nil {
+        return nil, err
+    }
+
 	if authByte == authPassword {
 		b.Clear()
 		if _, err := b.ReadFullFrom(reader, 2); err != nil {

```

**Comment by klzgrad** [comment]
The RFC didn't specify this separate behavior as far as I can see, and TCP does not operate at packet level.

**Comment by xiaokangwang** [comment]
I think this probably an issue with a misbehaving server. TCP does not preserve the border of traffics, so the receiver MUST be able to process the traffic regardless of how the data is segmented.

**Comment by kyze8439690** [comment]
It is a communication process. Server/client may reply different response depend of what they received. Of couse you can presume the server will react as you designed and send the following data in advanced. Some server implementation just can not be compatible with that. They just follow the simple "read-write-read-write" design.

**Comment by kyze8439690** [comment]
I will provide a code diff which can make it compatible with gost socks5 server for people who need it. This issue will be closed after.

**Comment by xiaokangwang** [comment]
> It is a communication process. Server/client may reply different response depend of what they received. Of couse you can presume the server will react as you designed and send the following data in advanced. Some server implementation just can not be compatible with that. They just follow the simple "read-write-read-write" design.

That being said, this is a common design issue with TCP based service. Programs like SSR will reject connection if it did not receive all header information in a single read.

In general, TCP based service must not assume the boundary of  message is preserved. I believe you need to contact them to fix their implementation of socks5 protocol. If you share the name of their software, I can contact them on your behalf.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, please include this workaround(send message separately) as an opt-in option in V2Ray. To increase support of socks server authentication.

**Comment by kyze8439690** [comment]
> I think this probably an issue with a misbehaving server. TCP does not preserve the border of traffics, so the receiver MUST be able to process the traffic regardless of how the data is segmented.

I agree with what you said above, but this patch does improve compatibility with different servers

**Comment by chenjiwork** [comment]
According to the description of rfc1928. The process of v2ray processing socks5 is wrong. After sending the verification header, it is necessary to receive the feedback from the server first, and then send the user's account password if the server accepts the account password method. But v2ray did not do this. After sending the verification header, v2ray directly sent the user account and password.

**Comment by starplanet** [comment]
socks5 compatibility problem should be solved. v2ray is not compatible with many socks services on the market
