### ISSUE TITLE
trojan+grpc 断流

### ISSUE THREAD

**Issue by architecturers** [v2fly/v2ray-core#1058]
客户端和服务器都是trojan+grpc
可以正常运行。
当正在运行中时候，服务器 运行命令 systemctl restart v2ray.service 后，断流。而且是永久性断流，即使服务器重启都不行。客户端重启也不行。
服务器是 x86 linux版本
客户端是 armv7a 版本

**Comment by architecturers** [comment]
root@FQDN:/var/log/v2ray# cat access.log
root@FQDN:/var/log/v2ray#
root@FQDN:/var/log/v2ray#
root@FQDN:/var/log/v2ray#
root@FQDN:/var/log/v2ray# cat error.log
2021/06/08 08:46:30 [Warning] V2Ray 4.39.2 started
2021/06/08 08:47:45 [Warning] V2Ray 4.39.2 started
2021/06/08 08:50:22 [Debug] app/log: Logger started
2021/06/08 08:50:22 [Info] app/dns: DNS: created Local DOH client for https://dns10.quad9.net/dns-query
2021/06/08 08:50:22 [Info] app/dns: DNS: created Local DOH client for https://dns-unfiltered.adguard.com/dns-query
2021/06/08 08:50:22 [Info] app/dns: DNS: created localhost client
2021/06/08 08:50:22 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
2021/06/08 08:50:23 [Warning] V2Ray 4.39.2 started
root@FQDN:/var/log/v2ray#

**Comment by kslr** [comment]
没有流量被导入

**Comment by architecturers** [comment]
只要 一运行 systemctl restart v2ray.service 就断流
而且永久断流
重启也没用 ， 只能更换其他的协议

**Comment by 33lyl** [comment]
我这grpc也会断，重启才恢复

**Comment by xiaokangwang** [comment]
看一下有没有被 https://github.com/v2fly/v2ray-core/commit/861d6be19a16136178245af30a6f41199593b0d2 修复

**Comment by onlyJinx** [comment]
老哥可以发一下trojan-grpc的客户端配置文件格式吗？我服务端写好之后发现客户端不会写，尴尬

**Comment by zhenpingfeng** [comment]
https://github.com/v2fly/v2ray-core/commit/0cbb6d75f3e5344da0ab8e0749fca458c1bb5962 经过几个小时测试。这个版本能延长断流的时间间隔，但是断流还是会发生，必须重启客户端才能再次使用。
