### ISSUE TITLE
最近几版的默认规则把tiktok归为直连网站是不是搞错了。

### ISSUE THREAD

**Issue by mdlenoir** [v2fly/v2ray-core#1075]
我的意思是最近几版geosite:cn按照一般国内网站直链规则的话，tiktok就是直链不走代理，网站就没法打开。必须在routing的geosite:cn规则前添加tiktok相关网站走代理规则才能正常打开网站。

###################################################################
rt。。。
2021/06/15 04:33:09 tcp:127.0.0.1:61993 accepted tcp:www.tiktok.com:443 [direct]

database64128 commented 2 days ago Contributor
There's no such thing as "default rules". Routing rules are configured by you in config.

**Comment by kslr** [comment]
看起来是因为 bytedance 被加入到 cn 里

**Comment by database64128** [comment]
https://github.com/v2fly/domain-list-community
