### ISSUE TITLE
近期出现了2次被识别端口封锁问题

### ISSUE THREAD

**Issue by shouziws** [v2fly/v2ray-core#1080]
使用用本4.23，一直使用的caddy + ws + tls + vmess 近期出现443被禁止的问题，我应该怎么办，如何避免被gfw

**Comment by ilpl** [comment]
可以尝试服务端 nginx+grpc+tls+vmess ,客户的使用tls chrome指纹

**Comment by shouziws** [comment]
> 可以尝试服务端 nginx+grpc+tls+vmess ,客户的使用tls chrome指纹

你好 请问有参考的配置吗

**Comment by inoblue** [comment]
You'd better discuss about it in `Discussions` area instead of here :)

**Comment by ArcCal** [comment]
同求
