### ISSUE TITLE
没搞过安卓, 请教几个代码问题

### ISSUE THREAD

**Issue by jymr92** [v2fly/v2ray-core#1086]
下载了master分支的代码, 随便看看了发现几个问题, 请指教
1 Unresolved reference: BuildConfig
<img width="562" alt="image" src="https://user-images.githubusercontent.com/44893500/122889375-5247be80-d375-11eb-8ac6-44c8d31381b8.png">

2 我随便搜了搜关键字,比如 “测试全部配置真连接”, 但是代码里搜不到?

以上原因是因为我下载代码有问题吗?

**Comment by kslr** [comment]
请到 v2rayNG 询问
