### ISSUE TITLE
mux有问题：出现大量的连接失败

### ISSUE THREAD

**Issue by MateorChan** [v2fly/v2ray-core#1088]
## 你正在使用哪个版本的 V2Ray？
4.39.2

## 你的使用场景是什么？
旁路由，24小时不间断走流量（或多或少的流量一直在线）

## 你看到的异常现象是什么？
出现大量的app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp xxx.xxx.xxx.xxx:port: operation was canceled] > common/retry: all retry attempts failed

## 请附上你的配置
我认为与配置文件无关，后文详细描述问题出现情况及我的猜测

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
服务端无错误
```

**客户端错误日志：**

```javascript
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp xxx.xxx.xxx.xxx:port: operation was canceled] > common/retry: all retry attempts failed

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志
与其无关
```

## 其它相关的配置文件（如 Nginx）和相关日志
与其无关

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出
可以启动，与其无关

## 如果 V2Ray 服务运行异常，请附上 journal 日志
可以启动，与其无关

## 我遇到的实际问题
服务端、客户端分别启动后，可以正常使用，但是error.log出现大量的上述Warning，影响网速

## 我尝试过的配置
vmess的tcp、vless的tcp

## 我的验证
使用两台虚拟机进行测试，将其中一台作为客户机，另一台作为服务机，将客户机的外网权限全部关闭，仅允许访问内网，作为模拟环境，连接到服务机。
观察到：客户机可以上网，出现大量的上述Warning，实际跑出来的带宽只有本地带宽的1/3-1/2（我本地是电信千兆）。
经过多次测试，发现只要mux不打开，就会出现上述问题，只要打开mux，哪怕concurrency为1，也不会出现。

**Comment by biabiubiu** [comment]
这个问题有解决吗？issue还没关，感觉…😂

**Comment by MateorChan** [comment]
> 这个问题有解决吗？issue还没关，感觉…😂

是这样的，这个Warning，只要一打开mux就消失，一关闭mux就出现，所以我才提个issue看下是不是代码里面有问题，如果你出现同样问题，可以试下跟我一样打开mux😁

**Comment by biabiubiu** [comment]
在哪打开mux的？

**Comment by MateorChan** [comment]
> 在哪打开mux的？


            "mux": {
                "enabled": true,
                "concurrency": 1
            }

**Comment by LearZhou** [comment]
分析可能是由於客戶端發起的網絡請求，撞到了所在的 Windows 操作系統的 最大半開連接數 限制這堵牆。正常的瀏覽器請求，隨著連接的建立，自動就緩解了；但是使用 v2ray，無論是 http 入站還是 socks5 入站，發起的併發連接沒有隊列處理機制，導致撞到最大半開連接數這個牆的個別 outbound 連接無法與服務器建立聯繫。

大家覺得這個分析是否在理，如果成立的話，在 v2ray 方面可有甚麼好的解決辦法？有可能在 http 或者 socks5 入站考慮最大半開連接，超出限制的進入等待隊列，這麼處理可以嗎？

**Comment by LearZhou** [comment]
抱歉，剛才關於半開連接數限制的猜想不正確。

但我發現，在不開 mux 的情況下，如果啟用 early data 連接 websocket，那麼在客戶端也不會有類似的 warning 產生。

所以這個問題應該出在不開啟 early data 的情況下，建立 websocket 連接的第二步驟的管理上出現了問題，建立了 websocket tunnel 之後，沒有發出跟進的握手數據。

**Comment by MateorChan** [comment]
> 抱歉，剛才關於半開連接數限制的猜想不正確。
> 
> 
> 
> 但我發現，在不開 mux 的情況下，如果啟用 early data 連接 websocket，那麼在客戶端也不會有類似的 warning 產生。
> 
> 
> 
> 所以這個問題應該出在不開啟 early data 的情況下，建立 websocket 連接的第二步驟的管理上出現了問題，建立了 websocket tunnel 之後，沒有發出跟進的握手數據。

但我这边的问题是出在最简单的tcp上面🤦‍♂️

**Comment by LearZhou** [comment]
那就可能是 socket 調度，在不經過 mux 的時候有 bug，這應該也算是一個很老的 bug 了。
