### ISSUE TITLE
Interface Naming Style

### ISSUE THREAD

**Issue by namingPolice** [v2fly/v2ray-core#1094]
`loglevel` of `{"log":{"loglevel":"none"}}` should be renamed to `level`, cuz its parent key `log` already contained key word `log`.

**Comment by kallydev** [comment]
I have the same idea, but the [config format of v5](https://gist.github.com/xiaokangwang/053b29d8fabb3873fe017963f3631f2f) doesn't seem to have any intention of modifying it.

It is suggested that v5 change the name of this key-value pair, cc @xiaokangwang.

**Comment by xiaokangwang** [comment]
This can be changed if need. @kslr What is your opinion on this?

**Comment by kslr** [comment]
we can add an alias

**Comment by database64128** [comment]
I think we should avoid unnecessary and potentially breaking changes to reduce confusion.

**Comment by database64128** [comment]
https://github.com/XTLS/Xray-core/issues/526
https://github.com/crystal-lang/crystal/issues/10840

This is borderline spam. I think the issue should be closed.

@namingPolice Please stop wasting open source maintainers' time on these pointless changes.

**Comment by xiaokangwang** [comment]
Thanks for your advice. From now on, the naming of new configs will be more careful to reduce this kind of issues. However, existing configs won't be changed, since it would create unnecessary frictions.

**Comment by namingPolice** [comment]
> we can add an alias

Agree. That's actually what I mean. Alias doesn't cause frictions and it also makes complete renaming in the future harmless.
