### ISSUE TITLE
一些不需要代理的网站使用了代理

### ISSUE THREAD

**Issue by playgithub** [v2fly/v2ray-core#1105]
如:
* microsoft.com
* windowsupdate.com

通过`Advanced Route Settings`可以设置为`Direct`，存在的问题，以microsoft.com为例，设为`Direct`以后本身没问题，但是访问时有**很多**附带的域名还是会通过代理，如：
* mem.gfx.ms
* img-prod-cms-rt-microsoft-com.akamaized.net
* dpm.demdex.net
* img-prod-cms-rt-microsoft-com.akamaized.net
* web.vortex.data.microsoft.com
* ...
(一共30个左右）

手动设置太麻烦了，有办法吗？

**Comment by database64128** [comment]
`geosite:geolocation-!cn@cn`

**Comment by playgithub** [comment]
> `geosite:geolocation-!cn@cn`

能不能通俗一点？

**Comment by playgithub** [comment]
> `geosite:geolocation-!cn@cn`

看了[预定义域名列表](https://www.v2fly.org/config/routing.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E5%9F%9F%E5%90%8D%E5%88%97%E8%A1%A8)，结尾`@cn`是什么意思？

**Comment by playgithub** [comment]
这样设置，访问microsoft.com时没有用到任何代理
* Domain / Direct
geosite:microsoft
geosite:microsoft-dev
* Domain / Block
geosite:category-ads-all

**Comment by database64128** [comment]
> 能不能通俗一点？

No one is obligated to answer your questions, especially when you also posted it in the wrong place.

**Comment by database64128** [comment]
> 看了[预定义域名列表](https://www.v2fly.org/config/routing.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E5%9F%9F%E5%90%8D%E5%88%97%E8%A1%A8)，结尾`@cn`是什么意思？

Domains that have access points like CDNs in mainland China are annotated with the `cn` tag.
