### ISSUE TITLE
freedom AsIs会对域名进行解析

### ISSUE THREAD

**Issue by hijxdd** [v2fly/v2ray-core#1117]
## 你正在使用哪个版本的 V2Ray？
4.40.1
## 你看到的异常现象是什么？
freedom使用"AsIs"模式并且配置”sendThrough“时，会对域名进行dns解析
## 你期待看到的正常表现是怎样的？
不进行dns解析
## 请附上你的配置
{
	"inbounds": [{
			"port": 10000,
			"protocol": "vmess",
			"settings": {"clients": [{"id": "xxx","alterId": 1,"email": "xxx"},]},
			"streamSettings": {"network": "tcp"}
		}
	],
	"outbounds": [{"tag":"out1","protocol":"freedom","domainStrategy":"AsIs","sendThrough":"10.100.0.1"}],
	"routing": {"rules": [{"type": "field","user":["xxx"], "outboundTag": "out1"}]}
}

**Comment by hijxdd** [comment]
我是想让接入端转换为ip，然后可以进路由流控，现在freedom出站指定源ip后，v2ray会对域名进行解析，若后续流控选择不同的线路出站，由于域名的ip在从v2ray出站时已经确定，会出现非最优dns

**Comment by database64128** [comment]
I don't understand what you're trying to do. How's the freedom outbound supposed to dial a domain name target without resolving it to an IP address? And please format your JSON. It's totally unreadable like this.
