### ISSUE TITLE
安装报错 

### ISSUE THREAD

**Issue by ToTdate** [v2fly/v2ray-core#1125]
## 你正在使用哪个版本的 V2Ray？

Debian 10     V2Ray 4.40.1

## 你的使用场景是什么？

上网

## 你看到的异常现象是什么？

安装报错
以下是我认为的异常

install: cannot create regular file '/usr/local/bin/v2ray': No such file or dire                                                                                                 ctory
install: cannot create regular file '/usr/local/bin/v2ctl': No such file or dire                                                                                                 ctory
rm: cannot remove '/etc/systemd/system/v2ray.service.d/10-donot_touch_multi_conf                                                                                                 .conf': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray@.service.d/10-donot_touch_multi_con                                                                                                 f.conf': No such file or directory

以下是完整安装过程

Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-                                                                                                 core/releases/download/v4.40.1/v2ray-linux-64.zip.dgst
info: Extract the V2Ray package to /tmp/tmp.Vtbnyl8H7A and prepare it for instal                                                                                                 lation.
install: cannot create regular file '/usr/local/bin/v2ray': No such file or dire                                                                                                 ctory
install: cannot create regular file '/usr/local/bin/v2ctl': No such file or dire                                                                                                 ctory
rm: cannot remove '/etc/systemd/system/v2ray.service.d/10-donot_touch_multi_conf                                                                                                 .conf': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray@.service.d/10-donot_touch_multi_con                                                                                                 f.conf': No such file or directory
info: Systemd service files have been installed successfully!
warning: The following are the actual parameters for the v2ray service startup.
warning: Please make sure the configuration file path is correctly set.
# /etc/systemd/system/v2ray.service
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
# In case you have a good reason to do so, duplicate this file in the same direc                                                                                                 tory and make your customizes there.
# Or all changes you made will be lost!  # Refer: https://www.freedesktop.org/so                                                                                               ftware/systemd/man/systemd.unit.html
[Service]
ExecStart=
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

installed: /usr/local/bin/v2ray
installed: /usr/local/bin/v2ctl
installed: /usr/local/share/v2ray/geoip.dat
installed: /usr/local/share/v2ray/geosite.dat
installed: /etc/systemd/system/v2ray.service
installed: /etc/systemd/system/v2ray@.service
removed: /tmp/tmp.Vtbnyl8H7A
info: V2Ray v4.40.1 is installed.
You may need to execute a command to remove dependent software: apt purge curl uzip                                                                                               
Please execute the command: systemctl enable v2ray; systemctl start v2ray
root@hw:~# systemctl enable v2ray
root@hw:~# service v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: exit-code) since Mon 2021-07-05 18:01:56 CST; 1h 28min ago
     Docs: https://www.v2fly.org/
 Main PID: 15178 (code=exited, status=203/EXEC)

Jul 05 18:01:56 hw systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 05 18:01:56 hw systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Jul 05 18:01:56 hw systemd[1]: Stopped V2Ray Service.
Jul 05 18:01:56 hw systemd[1]: v2ray.service: Start request repeated too quickly.
Jul 05 18:01:56 hw systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 05 18:01:56 hw systemd[1]: Failed to start V2Ray Service.

## 你期待看到的正常表现是怎样的？

安装成功

## 请附上你的配置

无，进程启动失败

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件


**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

无
我使用了 
ls /var/log/v2ray/ 
文件下并无error.log 文件

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出

无，提示
v2ray --test
-bash: v2ray: command not found

**Comment by ToTdate** [comment]
你好，请问这个问题如何解决？我尝试着google 好像没有答案！
如果可以的话，能说说出现这个问题的原因吗？
打扰了，谢谢！

**Comment by 15921483570** [comment]
同问, 如果有人解决了请戳我, 谢谢
