### ISSUE TITLE
Prevent Server ip as dns resolver

### ISSUE THREAD

**Issue by fsheidaiee** [v2fly/v2ray-core#1128]
Hi
When testing dns leak, i see the server ip as dns resolver beside my custom dns resolver.(Even if i leave dns section in config blank) 
Is there anyway to prevent server ip to be as the dns resolver? For example i only want to see cloudflare as dns resolver and nothing else
Like clash core.
Thanks

**Comment by kslr** [comment]
try custom DNS

**Comment by Loyalsoldier** [comment]
Some DNS leakage testings(e.g. https://www.astrill.com/vpn-leak-test ) try to resolve non-existed domains that will lead to resolving SOA record of that domain, which will leak your server IP or local IP.

In this case, a FakeDNS or a full-featured DNS will be your solutions.
