### ISSUE TITLE
建议增加routing对ipset的支持

### ISSUE THREAD

**Issue by 1887656** [v2fly/v2ray-core#1134]
## 你的使用场景是什么？
在软路由上安装v2ray，将访问请求根据不同的目的转发到不同的代理服务器（一般请求转到A代理，netflix请求转到B代理），由于在软路由上已经进行了域名解析，因此v2ray上收到的访问都是IP地址形式，而非域名形式，导致基于域名配置netflix分流策略失效。

## 你看到的异常现象是什么？
由于v2ray收到的访问请求都是ip地址，而非域名，导致在配置的基于域名的分流策略失效。

## 你期待看到的正常表现是怎样的？
期望v2ray增加基于ipset的分流策略支持，这样利用dnsmasq进行域名解析时可将netflix域名解析出来的ip地址增加到特定ipset中，v2ray针对此ipset种的ip地址分流到netflix代理。

**Comment by database64128** [comment]
You can use sniffing or FakeDNS to get the target domain name. Or just convert your IPSets to V2Ray's GeoIP file.

**Comment by 1887656** [comment]
现在在用的方案是利用dnsmasq解析nf相关域名后，将解析的ip地址加入到ipset里，iptables里订制策略将在nf ipset的访问转发到nf代理。也尝试过geosite:netflix，geoip:netflix，但发现没效果，我估计应该是geoip:netflix地址覆盖不全，所以直接在v2ray里配routing策略不起作用。将ipset转成geoip，这个方法在无法穷举nf ip地址的情况下不可行。所以认为v2ray能够支持根据ipset来配置路由策略可以较好的解决这个问题。

**Comment by Loyalsoldier** [comment]
不必先解析域名。开启 V2Ray 的 sniffing 或 FakeDNS，前提是先把流量导入 V2Ray。
