### ISSUE TITLE
Please add a top-level folder to your release archives

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [v2fly/v2ray-core#1135]
## What version of V2Ray are you using?

4.40.1

## What's your scenario of using V2Ray?

Just try it out

## What problems have you encountered?

I extracted it in my Downloads folder, now all the extracted files are scattered in it(instead of a single folder)

## What's your expectation?

I expect a top-level folder to exist in the release archive, which can be extracted cleanly without concerning about v2rays files scattering around other things

## Please attach your configuration here

N/A

**Client configuration:**

N/A

## Please attach error logs here

N/A

**Server error log:**

N/A

**Client error log:**

N/A

## Please attach access log here

N/A

## Other configurations (such as Nginx) and logs here

N/A

## If V2Ray cannot start up, please attach output from `--test` command

N/A

## If V2Ray service is abnormal, please attach journal log here

N/A

**Comment by database64128** [comment]
Is it really that difficult to specify a directory to extract to? Have you thought about the potential impacts of such a change? This would certainly break a lot of people's scripts.

**Comment by Lin-Buo-Ren** [comment]
> Is it really that difficult to specify a directory to extract to?

It's relatively more difficult to clean up the mess after wrongly assumed that a top-level directory will be created.
Breaking scripts is unfortunately a price to take to fix this issue, though.

**Comment by database64128** [comment]
Why would you assume the existence of a top-level directory in the release archive? Besides, almost all extract tools can list content in a compressed archive. You can always check before extracting.

**Comment by Lin-Buo-Ren** [comment]
> Why would you assume the existence of a top-level directory in the release archive?

Because most release archives do, in order to not making a mess in the extract destination.

> You can always check before extracting.

can != will

**Comment by database64128** [comment]
> Because most release archives do, in order to not making a mess in the extract destination.

I don't think so.
