### ISSUE TITLE
警报！新版Window版本被挂马

### ISSUE THREAD

**Issue by xmurobi** [v2fly/v2ray-core#1173]
## 你正在使用哪个版本的 V2Ray？

4.40.1

## 你的使用场景是什么？

Window

## 你看到的异常现象是什么？

1. Chrome警报
2. https://www.virustotal.com 检测被挂马

**Comment by kslr** [comment]
正常操作

**Comment by xmurobi** [comment]
@kslr 那自己编译呢？会带料吗？
