### ISSUE TITLE
运行V2ray出现started错误

### ISSUE THREAD

**Issue by zjpanda** [v2fly/v2ray-core#1175]
V2Ray 4.36.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 windows/386)
A unified platform for anti-censorship.
2021/07/30 12:10:30 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: C:\Program Files (x86)\v2rayN-Core\config.json
2021/07/30 12:10:31 [Warning] github.com/v2fly/v2ray-core/v4: V2Ray 4.36.2 started这个更新版本后也无法使用？请问怎么解决？

**Comment by Loyalsoldier** [comment]
启动成功了。
