### ISSUE TITLE
followRedirect 启用时 dokodemo-door 的 port 参数失效

### ISSUE THREAD

**Issue by rhjdvsgsgks** [v2fly/v2ray-core#1180]
## 你正在使用哪个版本的 V2Ray？

4.41.1

## 你的使用场景是什么？

使用反向代理访问国内网站
```shell
curl -Iv https://domain:233 --resolve domain:233:127.0.0.1
```
ps: 手动设置 dokodemo-door 的 InboundConfigurationObject 中 address 和 port 为正确值时可以正确获取到内容

## 你看到的异常现象是什么？

followRedirect 启用时 dokodemo-door 的 port 参数失效。根据文档的描述 followRedirect 启用时仅会“转发到相应的目标地址”，但实际上端口也被 followRedirect 所获取的端口覆盖了，所以流量被发到了 `domain的ip:233` 而不是 `domain的ip:443`
https://github.com/v2fly/v2ray-core/blob/327cbdc5cd10ee1aec6ef4dce1af027b3e277f33/proxy/dokodemo/dokodemo.go#L92
从这里也可以看出来，`outbound.Target` 的值直接给了 `dest` ，而 `dest` 里面是有 `Port` (也就是 `config.Port`) 的，所以配置里的端口被覆盖了

## 你期待看到的正常表现是怎样的？

followRedirect 获取的目标 ip/port 仅在未设置 address/port 时生效，后两者存在于配置中时覆盖前者获取的地址

## 请附上你的配置

**服务端配置：**

应该是客户端的问题

**客户端配置：**

```javascript
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 233,
      "protocol": "dokodemo-door",
      "settings": {
	      "port": 443,
	      "followRedirect": true
      },
      "tag": "in"
    }
  ],
```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

无错误

**客户端错误日志：**

无错误

## 请附上访问日志

客户端访问日志
```javascript
proxy/vmess/outbound: tunneling request to tcp:127.0.0.1:233 via xx
```

## 其它相关的配置文件（如 Nginx）和相关日志

无

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出

可以启动

## 如果 V2Ray 服务运行异常，请附上 journal 日志

服务启动正常

**Comment by AkinoKaede** [comment]
我认为这里的`目标地址`包含端口。

**Comment by rhjdvsgsgks** [comment]
> 我认为这里的`目标地址`包含端口。

那根据现有方案，“获取目标地址中的 ip 并使用配置文件中指定的端口进行连接“是否可以实现？

**Comment by rhjdvsgsgks** [comment]
如果我改成“希望实现获取目标地址中的 ip 并使用配置文件中指定的端口进行连接“是不是要再开个 issue ？
