### ISSUE TITLE
[Feature Request] Support tun to remove the dependency on tun2socks.

### ISSUE THREAD

**Issue by FH0** [v2fly/v2ray-core#1189]
I wrote a tun library. https://github.com/FH0/tunat

![image](https://user-images.githubusercontent.com/32861476/128626808-af163655-aabd-4918-9e3e-86fd0f5671b7.png)

**Comment by FH0** [comment]
More details https://github.com/shadowsocks/shadowsocks-rust/issues/581.

As a newbie to golang, I tried to read the source code of this project, but I didn't have a clue.

**Comment by rurirei** [comment]
thanks for the suggestion here, i'd interested in tun2socks as well.

**Comment by chromer030** [comment]
+1 for this feature.
Please add support.

**Comment by chromer030** [comment]
Or Comment.

**Comment by AkinoKaede** [comment]
#2541
