### ISSUE TITLE
ProbeInterval in config.json not working

### ISSUE THREAD

**Issue by manors** [v2fly/v2ray-core#1197]
## 你正在使用哪个版本的 V2Ray？
4.40.1 

## 你看到的异常现象是什么？
observatory中的ProbeInterval参数不起作用，始终是10秒的间隔。

## 请附上你的配置

    "observatory": {
        "subjectSelector": [
            "proxy"
        ],
        "probeURL": "api.v2fly.org",
        "ProbeInterval": 20000000000
    }

**Comment by manors** [comment]
还有我注意到ProbeInterval这个JSON配置的大小写风格与其他设置不一致。p或许应该小写？哈哈强迫症患者

**Comment by digglife** [comment]
@manors 

Golang 的 json 库在 `Unmarshal` 的时候也会忽略大小写来匹配，所以其实你在 JSON 文件里用 `probeInterval` 也一样有效。

当然，你也可以提一个 PR 改一下 `infra/conf/observatory.go` 和上面提到的文档。 😄

**Comment by tang88888888** [comment]
> ## 你正在使用哪个版本的 V2Ray？
> 4.40.1
> 
> ## 你看到的异常现象是什么？
> observatory中的ProbeInterval参数不起作用，始终是10秒的间隔。
> 
> ## 请附上你的配置
> ```
> "observatory": {
>     "subjectSelector": [
>         "proxy"
>     ],
>     "probeURL": "api.v2fly.org",
>     "ProbeInterval": 20000000000
> }
> ```

**Comment by tang88888888** [comment]
observatory": {
    "subjectSelector": [
        "proxy"
    ],
    "probeURL": "api.v2fly.org",
    "ProbeInterval": 20000000000
}
