### ISSUE TITLE
observatory": {

### ISSUE THREAD

**Issue by tang88888888** [v2fly/v2ray-core#1202]
observatory": {
    "subjectSelector": [
        "proxy"
    ],
    "probeURL": "api.v2fly.org",
    "ProbeInterval": 20000000000
}

_Originally posted by @tang88888888 in https://github.com/v2fly/v2ray-core/issues/1197#issuecomment-898795978_

**Comment by yomnxkcs** [comment]
ProbeInterval调用的函数是time.ParseDuration()。它接受的参数字符串不是数字。
例如："1ms", "2s", "3m"
更详细的请看[https://vimsky.com/zh-tw/examples/usage/time-parseduration-function-in-golang-with-examples.html](https://vimsky.com/zh-tw/examples/usage/time-parseduration-function-in-golang-with-examples.html)
