### ISSUE TITLE
内建DNS对A+AAAA结果的处理逻辑存在问题，其中一个失败不会返回错误

### ISSUE THREAD

**Issue by Mukou-Aoi** [v2fly/v2ray-core#1209]
以请求 UDP 服务器的代码为例，其他类型（DoH 等）亦存在此问题：
https://github.com/v2fly/v2ray-core/blob/73470e8dd8d020f3f19d77545cce00a9dbb96c2e/app/dns/nameserver_udp.go#L225-L246

当配置为同时请求 A 和 AAAA 记录（即默认）的情况下，若 ```record.A.getIPs()``` 或 ```record.AAAA.getIPs()``` 中有且仅有一个请求失败，合并了两者结果的 ```ips``` 数组就会存在成功的 IP，这些成功的 IP 会在 235 行返回，错误 ( ```err4``` / ```err6``` ) 被掩盖了。这一行为导致同时有 A+AAAA 记录的域名因为某种原因其中一种请求失败时，后续逻辑会错误的把该域名当成一个仅有 A/AAAA 记录的域名来处理。

发现此问题的契机是遇到偶尔无法访问 google 而其它网站正常的情况，排查发现服务器端 v2ray 的 dns 缓存中对 google.com 的结果只剩下了 IPv6 的地址。显然的，如果配置文件的 ```"dns"``` 段设置了 ```"queryStrategy": "UseIPv4"``` 或 ```"queryStrategy": "UseIPv6"``` 不会遇到此问题。

（未验证）是否可以将 ```err4``` 和 ``` err6``` 的判定移动到对应的 ```getIPs()``` 后，即获取结果后立即判断是否有错误，有即返回。虽然这种修改方式会改变 v2ray 目前的行为，但个人认为目前的行为应该看作 bug 直接进行修正。

**Comment by Loyalsoldier** [comment]
你的意思是，建议默认情况下（UseIP）DNS 解析必须同时返回有效的 IPv4 和 IPv6 地址才算解析成功？

如果是这样的话，那解析失败的概率应该会很高。建议直接设置为 UseIPv4 或 UseIPv6。

**Comment by Mukou-Aoi** [comment]
> 你的意思是，建议默认情况下（UseIP）DNS 解析必须同时返回有效的 IPv4 和 IPv6 地址才算解析成功？

当一个域名没有 A/AAAA 记录的时候成功的解析会返回 NXDOMAIN，和解析失败是不同的。

目前的行为是如果 A/AAAA 请求因为错误（比如超时）而没能返回结果就会当成没有这个记录处理，这显然是不对的。

> 如果是这样的话，那解析失败的概率应该会很高。建议直接设置为 UseIPv4 或 UseIPv6。

这不是个好主意：

> WARNING
> 
> 如果本选项设置为 UseIPv4，而 freedom 协议 outbound 中的 domainStrategy 选项设置为 UseIPv6，会导致从 freedom 协议 outbound 发出的连接的 DNS 查询被 Go 运行时接管，进而导致 DNS 泄漏；反之同理。
> 
> https://www.v2fly.org/config/dns.html#dnsobject

**Comment by CalmLong** [comment]
如果两个类型都查询了，那么只返回 IPv6 也是没问题的

> 即把「失败的请求」当作「成功的请求（空结果）」这显然是不对的。

这样是不对，但是对于 V2 或者能配置多个 DNS 的 DNS 客户端来说，这是没错的
配置文件是一个 DNS 列表，失败的请求与空结果都是一样的答案，那就是没有返回 IP。
没有IP就得继续使用下一个 DNS 来查询，直到获取 IP
当有多个 DNS 返回空结果/错误时是不可能对每个错误来处理的，因为总是要使用下一个 DNS 查询

**Comment by CalmLong** [comment]
万一有的用户要使用 IPv4 分流，但用 IPv6 联网呢 ~~/手动滑稽~~

**Comment by Mukou-Aoi** [comment]
> 配置文件是一个 DNS 列表，失败的请求与空结果都是一样的答案，那就是没有返回 IP。

并不是，空结果是请求成功但该域名没有对应的记录（NXDOMAIN），而失败的请求可能有各种原因（比如超时）

当得到 NXDOMAIN 的情况下会直接返回空结果，而不是回退到下一个服务器进行查询。

> 没有IP就得继续使用下一个 DNS 来查询，直到获取 IP

明确一下用语，以下所说的「失败」不包括查询成功但结果为空（即 NXDOMAIN）

目前的问题是：当同时请求 A+AAAA 记录、有且仅有一种请求失败时，会直接返回成功的结果并且进入缓存，**不会触发回退**。这一行为直接导致了后续处理把该域名当成了仅有 A/AAAA 记录的域名处理，会导致 IPv6/IPv4 的路由规则无效。

我能想到最简单的两种处理方式是：

- A. 其中一种失败就假定该 DNS 服务器出了问题，抛弃成功的结果返回错误，回退到下一个 DNS 服务器重新查询 A+AAAA。
- B. 修改逻辑，分开请求 A 和 AAAA 以确保两种请求都能正常回退。

**Comment by CalmLong** [comment]
> 当得到 NXDOMAIN 的情况下会直接返回空结果，而不是回退到下一个服务器进行查询。

也不能排除第一个 DNS 返回 NXDOMAIN 而第二个 DNS 却有结果的可能性

> 明确一下用语，以下所说的「失败」不包括查询成功但结果为空（即 NXDOMAIN）

我还是觉得过程对于V2来说是不重要的

你的意思就是如果我想要 A+AAAA 那么就必须返回 A+AAAA 这个没问题，只是 V2 还不支持，但是现有的做法也并不是个 Bug 吧，毕竟使用 `UseIP` 就得代表 IPv4 和 IPv6 都得可用

**Comment by Mukou-Aoi** [comment]
> 也不能排除第一个 DNS 返回 NXDOMAIN 而第二个 DNS 却有结果的可能性

那说明第一个 DNS 服务器有问题，V2Ray 不应该去尝试兼容这种非标准行为。正常的 DNS 服务器只应该对不存在的域名回复 NXDOMAIN。

> 你的意思就是如果我想要 A+AAAA 那么就必须返回 A+AAAA 这个没问题，只是 V2 还不支持，但是现有的做法也并不是个 Bug 吧，毕竟使用 UseIP 就得代表 IPv4 和 IPv6 都得可用

问题就在于，目前的行为导致了 IPv4/IPv6 其中一个会变得不可用，而且因为缓存的存在会导致长时间（目前的缓存时间是 300 秒，期间内所有的请求都回被返回错误的结果）阻断相应的访问。

> 默认值为 UseIP，即 DNS 同时查询域名的 A 和 AAAA 记录。
> https://www.v2fly.org/config/dns.html#dnsobject

同时查询域名的 A 和 AAAA 记录就应该返回两个成功（可以为空）的结果，而不是一个成功一个失败的结果也囫囵返回。

**Comment by CalmLong** [comment]
或许将单个DNS更改为只查IPV4可以解决

**Comment by database64128** [comment]
> 并不是，空结果是请求成功但该域名没有对应的记录（NXDOMAIN），而失败的请求可能有各种原因（比如超时）

This is incorrect. DNS returns NXDOMAIN when the domain name doesn't exist at all. If the domain only has AAAA records, querying for A records returns successfully (NOERROR) with an empty response.

**Comment by database64128** [comment]
@Mukou-Aoi Can you check if [this branch](https://github.com/v2fly/v2ray-core/tree/dns-query-strategy-use-ip-failfast) resolves the issue? You need to opt-in to the new behavior by setting `queryStrategy` to `UseIPFailFast`.

**Comment by Mukou-Aoi** [comment]
> @Mukou-Aoi Can you check if [this branch](https://github.com/v2fly/v2ray-core/tree/dns-query-strategy-use-ip-failfast) resolves the issue? You need to opt-in to the new behavior by setting `queryStrategy` to `UseIPFailFast`.

I've tried to use ```"queryStrategy": "UseIPFailFast"``` and dns still works for ipv4 only / ipv6 only / and dual stack sites:

```
2021/08/21 18:16:41 [Info] app/dns: DOH//cloudflare-dns.com got answer: ipv6.google.com. TypeAAAA -> [[2404:6800:4004:822::200e]] 852.0488ms
2021/08/21 18:16:41 [Info] app/dns: DOH//cloudflare-dns.com got answer: ipv6.google.com. TypeA -> [] 854.0489ms
2021/08/21 18:16:42 [Debug] app/dns: domain ipv6.google.com will use DNS in order: [DOH//cloudflare-dns.com DOH//dns.google]
2021/08/21 18:16:42 [Debug] app/dns: DOH//cloudflare-dns.com cache HIT ipv6.google.com -> [2404:6800:4004:822::200e]

2021/08/21 18:16:48 [Info] app/dns: DOH//cloudflare-dns.com got answer: www.google.com. TypeAAAA -> [[2404:6800:4004:80e::2004]] 2.1911253s
2021/08/21 18:16:48 [Info] app/dns: DOH//cloudflare-dns.com got answer: www.google.com. TypeA -> [172.217.175.4] 2.1911253s
2021/08/21 18:16:49 [Debug] app/dns: domain www.google.com will use DNS in order: [DOH//cloudflare-dns.com DOH//dns.google]
2021/08/21 18:16:49 [Debug] app/dns: DOH//cloudflare-dns.com cache HIT www.google.com -> [172.217.175.4 2404:6800:4004:80e::2004]

2021/08/21 18:17:12 [Info] app/dns: DOH//cloudflare-dns.com got answer: www.reddit.com. TypeAAAA -> [] 1.4300818s
2021/08/21 18:17:12 [Info] app/dns: DOH//cloudflare-dns.com got answer: www.reddit.com. TypeA -> [151.101.65.140 151.101.129.140 151.101.1.140 151.101.193.140] 1.4300818s
2021/08/21 18:17:13 [Debug] app/dns: domain www.reddit.com will use DNS in order: [DOH//cloudflare-dns.com DOH//dns.google]
2021/08/21 18:17:13 [Debug] app/dns: DOH//cloudflare-dns.com cache HIT www.reddit.com -> [151.101.65.140 151.101.129.140 151.101.1.140 151.101.193.140]
```

I didn't test what would happen when one of the request fails mainly because I don't know how (run a dns server?), all I can say is that it doesn't break things.

**Comment by database64128** [comment]
It's possible to use firewall to block a certain kind of query (e.g. drop `A www.google.com` but allow `AAAA www.google.com`). Or just deploy to production and check the logs afterwards.

**Comment by Mukou-Aoi** [comment]
> It's possible to use firewall to block a certain kind of query (e.g. drop `A www.google.com` but allow `AAAA www.google.com` and anything else). Or just deploy to production and check the logs afterwards.

I believe it's working properly:
```
[Debug] app/dns: domain www.qq.com will use DNS in order: [UDP:192.168.1.254:53 UDP:223.5.5.5:53]
[Debug] app/dns: UDP:192.168.1.254:53 querying DNS for: www.qq.com.
[Info] app/dns: UDP:192.168.1.254:53 got answer: www.qq.com. TypeA -> [221.198.70.47] 46.0026ms
[Debug] app/dns: UDP:192.168.1.254:53 updating IP records for domain:www.qq.com.
[Info] app/dns: failed to lookup ip for domain www.qq.com at server UDP:192.168.1.254:53 > context deadline exceeded
[Debug] app/dns: UDP:223.5.5.5:53 querying DNS for: www.qq.com.
[Info] app/dns: UDP:223.5.5.5:53 got answer: www.qq.com. TypeA -> [221.198.70.47] 20.0011ms
[Debug] app/dns: UDP:223.5.5.5:53 updating IP records for domain:www.qq.com.
[Info] app/dns: UDP:223.5.5.5:53 got answer: www.qq.com. TypeAAAA -> [[2402:4e00:1900:1400:0:9227:71e8:2ccc] [2402:4e00:1900:1400:0:9227:71ef:f0b1]] 21.0012ms
```

(192.168.1.254 is a vm which I have iptables in the vm os blocking all outgoing AAAA on udp 53)

**Comment by Mukou-Aoi** [comment]
> It's possible to use firewall to block a certain kind of query (e.g. drop `A www.google.com` but allow `AAAA www.google.com` and anything else). Or just deploy to production and check the logs afterwards.

I believe it's working properly:
```
[Debug] app/dns: domain www.qq.com will use DNS in order: [UDP:192.168.1.254:53 UDP:223.5.5.5:53]
[Debug] app/dns: UDP:192.168.1.254:53 querying DNS for: www.qq.com.
[Info] app/dns: UDP:192.168.1.254:53 got answer: www.qq.com. TypeA -> [0.0.0.0] 46.0026ms
[Debug] app/dns: UDP:192.168.1.254:53 updating IP records for domain:www.qq.com.
[Info] app/dns: failed to lookup ip for domain www.qq.com at server UDP:192.168.1.254:53 > context deadline exceeded
[Debug] app/dns: UDP:223.5.5.5:53 querying DNS for: www.qq.com.
[Info] app/dns: UDP:223.5.5.5:53 got answer: www.qq.com. TypeA -> [0.0.0.0] 20.0011ms
[Debug] app/dns: UDP:223.5.5.5:53 updating IP records for domain:www.qq.com.
[Info] app/dns: UDP:223.5.5.5:53 got answer: www.qq.com. TypeAAAA -> [[::] [::]] 21.0012ms
```

(192.168.1.254 is a linux vm which I have iptables configured to drop all incoming AAAA query on udp 53)

**Comment by database64128** [comment]
Can you also check if `UseIP` still behaves the same as before?

**Comment by Mukou-Aoi** [comment]
> Can you also check if `UseIP` still behaves the same as before?

`"queryStrategy": "UseIP"`
```
[Debug] app/dns: domain www.qq.com will use DNS in order: [UDP:192.168.1.254:53 UDP:223.5.5.5:53]
[Debug] app/dns: UDP:192.168.1.254:53 cache HIT www.qq.com -> [0.0.0.0]
```
Incorrect result cached, no fallback

---
`"queryStrategy": "UseIPFailFast"`
```
[Debug] app/dns: domain www.qq.com will use DNS in order: [UDP:192.168.1.254:53 UDP:223.5.5.5:53]
[Debug] app/dns: UDP:192.168.1.254:53 querying DNS for: www.qq.com.
[Debug] transport/internet/udp: dispatch request to: udp:192.168.1.254:53
[Debug] transport/internet/udp: dispatch request to: udp:192.168.1.254:53
[Info] app/dns: UDP:192.168.1.254:53 got answer: www.qq.com. TypeA -> [0.0.0.0] 11.0006ms
[Info] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
[Info] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
[Info] app/dns: failed to lookup ip for domain www.qq.com at server UDP:192.168.1.254:53 > context deadline exceeded
[Debug] app/dns: UDP:223.5.5.5:53 cache HIT www.qq.com -> [0.0.0.0 :: ::]
```
The incorrect result (ipv4 only) is not cached

**Comment by database64128** [comment]
Thank you for your thorough testing! I guess it's time for a new PR.

**Comment by Loyalsoldier** [comment]
看着上面的 log 感觉不太对劲，是不是应该重构一下处理逻辑 😂

**Comment by database64128** [comment]
@Loyalsoldier Feel free to assign yourself. Rewriting this mess is not an easy task. 🤣

**Comment by database64128** [comment]
@Loyalsoldier BTW, the log looks fine to me. Apparently @Mukou-Aoi only blocked AAAA queries to `192.168.1.254`, while allowing this type of query to `223.5.5.5`. The log snippets show the second time V2Ray looks up `www.qq.com`, because we need to know whether the partially failed (A succeeded, AAAA failed) lookup result is cached.

**Comment by database64128** [comment]
My fix does not directly prevent the successful query response from being cached when the other one failed. Instead, it adds a check in `findIPsForDomain`. The function `findIPsForDomain` is called to retrieve the cached DNS record for the domain. My added check makes sure that the cached record is used **only when** it contains both A and AAAA query response. Because the absence of either type of query response indicates that one of the queries failed. Note that empty A or AAAA records are still valid query responses.

@Loyalsoldier Do you plan to change the lookup logic to wait until both queries return and then decide whether to cache? I'm not sure if this change is really worth it though.

**Comment by Mukou-Aoi** [comment]
> Apparently @Mukou-Aoi only blocked AAAA queries to `192.168.1.254`, while allowing this type of query to `223.5.5.5`.

I'm using iptables in the vm (192.168.1.254) os to drop all incoming AAAA queries, no blocking is setup outside the vm.
---

It seems that V2Ray's dns cache works in a per-server fashion instead of a universal one, thus causing the resolve to 192.168.1.254 in second log from [my previous comment](https://github.com/v2fly/v2ray-core/issues/1209#issuecomment-903113943). What's the reason behind this design?

**Comment by Loyalsoldier** [comment]
> It seems that V2Ray's dns cache works in a per-server fashion instead of a universal one, thus causing the queries to 192.168.1.254 in second log from [my previous comment](https://github.com/v2fly/v2ray-core/issues/1209#issuecomment-903113943). What's the reason behind this design?

Not sure. Better refactor is welcome.

**Comment by xiaokangwang** [comment]
> > Apparently @Mukou-Aoi only blocked AAAA queries to `192.168.1.254`, while allowing this type of query to `223.5.5.5`.
> 
> I'm using iptables in the vm (192.168.1.254) os to drop all incoming AAAA queries, no blocking is setup outside the vm.
> 
> It seems that V2Ray's dns cache works in a per-server fashion instead of a universal one, thus causing the queries to 192.168.1.254 in second log from [my previous comment](https://github.com/v2fly/v2ray-core/issues/1209#issuecomment-903113943). What's the reason behind this design?

The reason behind this design is that an authoritative DNS can return a different result to the DNS recursive server based on the location of that recursive server(This is also the reason why some domestic websites will become very slow if you resolve their domain name on a foreign DNS server.). We should expect different DNS recursive servers in different locations to return a different set of responses. 

CC: @Loyalsoldier

**Comment by database64128** [comment]
The fix has landed in https://github.com/Shadowsocks-NET/v2ray-go.

**Comment by Mukou-Aoi** [comment]
> > > Apparently @Mukou-Aoi only blocked AAAA queries to `192.168.1.254`, while allowing this type of query to `223.5.5.5`.
> > 
> > 
> > I'm using iptables in the vm (192.168.1.254) os to drop all incoming AAAA queries, no blocking is setup outside the vm.
> > It seems that V2Ray's dns cache works in a per-server fashion instead of a universal one, thus causing the queries to 192.168.1.254 in second log from [my previous comment](https://github.com/v2fly/v2ray-core/issues/1209#issuecomment-903113943). What's the reason behind this design?
> 
> The reason behind this design is that an authoritative DNS can return a different result to the DNS recursive server based on the location of that recursive server(This is also the reason why some domestic websites will become very slow if you resolve their domain name on a foreign DNS server.). We should expect different DNS recursive servers in different locations to return a different set of responses.
> 
> CC: @Loyalsoldier

Doesn't the current design ensure that for a given domain it will always use the first (working) matching server? So one domain's result would be and only be stored in the first server's cache.

Here's my understanding of how the current DNS cache works, please correct me if I'm wrong. The following two scenarios assume that the first matching server is not returning a "valid" result, and a valid result is stored in the second server's cache:

1. When the first matching server is down, V2Ray would still send a request to the first server anyway, and only after the request fails (times out?) it would try the second server and get the cached result.

2. When the first matching server returns a result that doesn't match `expectIPs`, in most cases this server will always return the same non-matching result, yet V2Ray would still send a request to the first server every time, got a result that doesn't match, then proceed to request the second server and get the cached result.

This sounds very inefficient to me.

**Comment by xiaokangwang** [comment]
> > > > Apparently @Mukou-Aoi only blocked AAAA queries to `192.168.1.254`, while allowing this type of query to `223.5.5.5`.
> > > 
> > > 
> > > I'm using iptables in the vm (192.168.1.254) os to drop all incoming AAAA queries, no blocking is setup outside the vm.
> > > It seems that V2Ray's dns cache works in a per-server fashion instead of a universal one, thus causing the queries to 192.168.1.254 in second log from [my previous comment](https://github.com/v2fly/v2ray-core/issues/1209#issuecomment-903113943). What's the reason behind this design?
> > 
> > 
> > The reason behind this design is that an authoritative DNS can return a different result to the DNS recursive server based on the location of that recursive server(This is also the reason why some domestic websites will become very slow if you resolve their domain name on a foreign DNS server.). We should expect different DNS recursive servers in different locations to return a different set of responses.
> > CC: @Loyalsoldier
> 
> Doesn't the current design ensure that for a given domain it will always use the first (working) matching server? So one domain's result would be and only be stored in the first server's cache.
> 
> Here's my understanding of how the current DNS cache works, please correct me if I'm wrong. The following two scenarios assume that the first matching server is not returning a "valid" result, and a valid result is stored in the second server's cache:
> 
> 1. When the first matching server is down, V2Ray would still send a request to the first server anyway, and only after the request fails (times out?) it would try the second server and get the cached result.
> 2. When the first matching server returns a result that doesn't match `expectIPs`, in most cases this server will always return the same non-matching result, yet V2Ray would still send a request to the first server every time, got a result that doesn't match, then proceed to request the second server and get the cached result.
> 
> This sounds very inefficient to me.

I recognize this would be inefficient. I will examine this issue and try to find a way to improve for this.
