### ISSUE TITLE
文档里面dns章节 缺少DNS over QUIC 非 local 模式 

### ISSUE THREAD

**Issue by architecturers** [v2fly/v2ray-core#1225]
如题

**Comment by Loyalsoldier** [comment]
目前并无此模式。

**Comment by architecturers** [comment]
quic的dns 只能使用local模式？
以前的文档我记得有非local模式啊

**Comment by architecturers** [comment]
quic://dns-unfiltered.adguard.com

**Comment by database64128** [comment]
Feel free to implement it yourself :) Contributions are always welcome.
