### ISSUE TITLE
连上代理之后才可通过内建dns进行解析？

### ISSUE THREAD

**Issue by fredericky123** [v2fly/v2ray-core#1237]
## 你正在使用哪个版本的 V2Ray？
4.41.1

## 你的使用场景是什么？
通过Vmess 代理访问搜索

## 你看到的异常现象是什么？
局域网内dns被污染，导致我的代理服务器域名无法被解析，从而连不上服务器，在本地自建了个dns解析，如果在系统设置里将网络的dns改为127.0.0.1后，则可以进行代理服务器的域名解析，连上服务器；于是想在qv2ray里实现此目的，结果选中“dns拦截“和"直连使用v2ray dns"，将qv2ray的dns设置为127后，依然无法解析代理服务器的域名，没有实现通过内置dns解析代理服务器域名。经测试发现，如果将代理服务器的域名改为ip，则可连上服务器，而接下来通过浏览器发起的请求都会被通过内置dns进行解析。难道解析代理服务器域名这一步不能通过内置dns完成吗？

## 你期待看到的正常表现是怎样的？
连上代理服务器这一步也是通过内置dns进行域名解析，这样代理服务器的域名就不会被ISP劫持

**Comment by Loyalsoldier** [comment]
这是一个蛋和鸡的耦合问题。

**Comment by fredericky123** [comment]
> 这是一个蛋和鸡的耦合问题。

所以是无解么，系统的dns改为127不就是可以正常解析第一步代理域名的么，v2ray无法做到？

**Comment by happier233** [comment]
@Loyalsoldier 我提一个我的想法，尽可能让这个鸡和蛋分开一下。
1. 如果因为某些原因要发起outbound的链接所以要解析dns（如果有多线程加载，那么这里要对outbound做互斥锁）
2. dns解析要回到该outbound
3. 因为该outbound没有ready且拿不到这个outbound的锁，所以放弃该outbound，视为这个dns解析失败了，然后fallback跳到下一个dns
欢迎进行交流，这也只是我的一点想法
