### ISSUE TITLE
Test failure on go1.17

### ISSUE THREAD

**Issue by maxice8** [v2fly/v2ray-core#1265]
## What version of V2Ray are you using?

4.41.1

## What's your scenario of using V2Ray?

Running testsuite while building

## What problems have you encountered?

```
--- FAIL: TestLongRequestHeader (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 36 [running]:
testing.tRunner.func1.2({0xcab080, 0xe89578})
	/usr/lib/go/src/testing/testing.go:1209 +0x290
testing.tRunner.func1(0x318c690)
	/usr/lib/go/src/testing/testing.go:1212 +0x27c
panic({0xcab080, 0xe89578})
	/usr/lib/go/src/runtime/panic.go:1038 +0x258
strings.HasPrefix(...)
	/usr/lib/go/src/strings/strings.go:445
github.com/v2fly/v2ray-core/v4/transport/internet/headers/http_test.TestLongRequestHeader(0x318c690)
	/home/buildozer/aports/testing/v2ray/src/v2ray-core-4.41.1/transport/internet/headers/http/http_test.go:70 +0x1d4
testing.tRunner(0x318c690, 0xce2ce8)
	/usr/lib/go/src/testing/testing.go:1259 +0x104
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1306 +0x39c
FAIL	github.com/v2fly/v2ray-core/v4/transport/internet/headers/http	0.019s
```

## What's your expectation?
Testsuite passes like in go1.16.x

**Comment by xiaokangwang** [comment]
Hi, thanks for your feedback. Before we begin investigating, I would like to confirm the version of the code you are building. 

Are you using the latest commit of V2Ray or the tagged release?  You can provide me with this information by running `git rev-parse HEAD` in the source code folder, and post the result here.

Are you using the 1.17 version of the Go toolchain or 1.17.1 version of the go toolchain?  You can provide me with this information by running `go version` in the source code folder, and post the result here.

**Comment by maxice8** [comment]
Using the following sources:

```
https://github.com/v2fly/v2ray-core/archive/v4.41.0.tar.
```

Using go `1.17`, we (Alpine Linux) did not upgrade `go` to `1.17.1` yet because of an unrelated build failure on `ppc64le` architecture

**Comment by maxice8** [comment]
4.42.1 builds and passes tests in my local machine

**Comment by maxice8** [comment]
Fails on CI with the same error, https://gitlab.alpinelinux.org/alpine/aports/-/jobs/486851

**Comment by kslr** [comment]
> loadinternal: cannot find runtime/cgo
try add CGO_ENABLED=0

**Comment by maxice8** [comment]
The APKBUILD already has `export CGO_ENABLED=0` so all commands will have that in its environment, from the `go build` to `go test`

**Comment by Loyalsoldier** [comment]
@maxice8 

Could you please update `geoip.dat` and `geosite.dat`, and include `geoip-only-cn-private.dat`(https://github.com/v2fly/geoip/releases/download/202109102251/geoip-only-cn-private.dat) to the package?

And LDFLAGS should be changed to:

```
-X github.com/v2fly/v2ray-core/v4.codename=${CODENAME}
-X github.com/v2fly/v2ray-core/v4.version=${VERSIONTAG}
-X github.com/v2fly/v2ray-core/v4.build=${BUILDNAME}
-s -w -buildid=
```

**Comment by maxice8** [comment]
passes on x86_64 but fails on all other arches

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/25327

**Comment by nibon7** [comment]
I use go1.17.3 and  bisect from v4.23.3 to v4.23.4 with `env CGO_ENABLED=0 GOARCH=386 go test v2ray.com/core/transport/internet/headers/http`, it seems that 087a62ef3dd1234318a3c9c9e6fa7e7137e5ae9e was the first bad commit.

```
git bisect start
# good: [09295f7ef6a210a48b17e0c93ec9dcedaf6f6e90] fix bazel not set home
git bisect good 09295f7ef6a210a48b17e0c93ec9dcedaf6f6e90
# bad: [b610fc0a70b5e444abd3afe513bfff6ca6c85efb] make error less sensitive
git bisect bad b610fc0a70b5e444abd3afe513bfff6ca6c85efb
# good: [220b783caa667817a77c0b9dd5ed8375b17f8f02] Align Timeout Value
git bisect good 220b783caa667817a77c0b9dd5ed8375b17f8f02
# good: [5d616dcc753bbd536f38519f680c057371333b86] Merge pull request #9 from v2fly/revert-8-kslr-patch-1
git bisect good 5d616dcc753bbd536f38519f680c057371333b86
# bad: [221a13e658148d0516818db9249b3c17e396cbb9] Early detection of non http traffic to match web server behavior
git bisect bad 221a13e658148d0516818db9249b3c17e396cbb9
# bad: [087a62ef3dd1234318a3c9c9e6fa7e7137e5ae9e] Fixed HTTP response not adjusted based on request
git bisect bad 087a62ef3dd1234318a3c9c9e6fa7e7137e5ae9e
# good: [38e89bd2c740d660225ba6a5782a730860343bb4] VMess will Drain Connection On Auth failure
git bisect good 38e89bd2c740d660225ba6a5782a730860343bb4
# first bad commit: [087a62ef3dd1234318a3c9c9e6fa7e7137e5ae9e] Fixed HTTP response not adjusted based on request
```

**Comment by digglife** [comment]
我调查了一下， V2Ray [导入了 `readRequest` 这个私有函数](https://github.com/v2fly/v2ray-core/blob/c25e33c4232e9a2c1dc4d49c37d1b240dce82bb0/transport/internet/headers/http/linkedreadRequest.go#L12
) ，但是这个函数的签名[从 1.17 开始变了](https://github.com/golang/go/commit/acb189ea59d7f47e5db075e502dcce5eac6571dc#diff-58d1202218e4b5db623ceb4abddb3c166adc4c34a327c1c9df106191edc370d2R1022)，所以会导致 Runtime Error，我将签名更新后就正常了。

Go 的相关commit: https://github.com/golang/go/commit/acb189ea59d7f47e5db075e502dcce5eac6571dc#diff-58d1202218e4b5db623ceb4abddb3c166adc4c34a327c1c9df106191edc370d2R1022

```diff
-func readRequest(b *bufio.Reader, deleteHostHeader bool) (req *Request, err error) {
+func readRequest(b *bufio.Reader) (req *Request, err error) {
```

之前特地导入 `readRequest` 的目的应该是因为公有函数 `ReadRequest` 默认会删除 Host Header，使用 `readRequest` 可以传一个 `false` 规避这一点。

现在 `readRequest` 虽然没了`deleteHostHeader`参数， 但是默认不删除 Host Header，和我们的需求一致。
