### ISSUE TITLE
协议为socks 传输层用ws 当ws开启"maxEarlyData": 1024, 的时候断流

### ISSUE THREAD

**Issue by architecturers** [v2fly/v2ray-core#1268]
如题
只要把客户端的"maxEarlyData": 1024 关了就正常了，服务器端的开不开启不影响
客户端 服务器都是41.1版本

**Comment by kingwilliam** [comment]
在服务器v2前有没有 nginx/caddy/haproxy 之类?

**Comment by architecturers** [comment]
没有 直接连的

**Comment by kingwilliam** [comment]
要看看你客户那边ws如何设置

**Comment by architecturers** [comment]
`{
    "protocol": "socks",
    "settings": {
        "servers": [
            {
                "address": "",
                "port": 123
            }
        ]
    },
    
    "streamSettings": {
        "network": "ws",
        "wsSettings": {
            "path": "/123",
            //"maxEarlyData": 1024,
            "earlyDataHeaderName":"123"
        },
        
        "security": "tls",
        "tlsSettings": {
            "serverName": ""
        }
    }
}`

**Comment by architecturers** [comment]
> 

`{
    "protocol": "socks",
    "settings": {
        "servers": [
            {
                "address": "",
                "port": 123
            }
        ]
    },
    
    "streamSettings": {
        "network": "ws",
        "wsSettings": {
            "path": "/123",
            //"maxEarlyData": 1024,
            "earlyDataHeaderName":"123"
        },
        
        "security": "tls",
        "tlsSettings": {
            "serverName": ""
        }
    }
}`

**Comment by architecturers** [comment]
{
    "protocol": "socks",
    "settings": {
        "servers": [
            {
                "address": "",
                "port": 123
            }
        ]
    },
    
    "streamSettings": {
        "network": "ws",
        "wsSettings": {
            "path": "/123",
            //"maxEarlyData": 1024,
            "earlyDataHeaderName":"123"
        },
        
        "security": "tls",
        "tlsSettings": {
            "serverName": ""
        }
    }
}

**Comment by kingwilliam** [comment]
有没有 客户和伺服器 debug log
