### ISSUE TITLE
Latest Debian package uninstallable on stable

### ISSUE THREAD

**Issue by patrickli** [v2fly/v2ray-core#1278]
The Debian package is built on unstable/sid (https://github.com/v2fly/v2ray-core/pull/1277/checks#step:6:73), not stable/bullseye. As such it depends on libc6 >= 2.32, which is unavailable on stable (2.31-13). This makes the Debian package impossible to install in normal conditions.

Please update deb workflow to use debian stable (https://github.com/v2fly/v2ray-core/blob/master/.github/workflows/deb.yml#L24).

**Comment by Loyalsoldier** [comment]
There is no Go v1.17 package in Debian Stable now.

I'm not familiar with Debian. Can we just change

```
$ echo "deb [arch=amd64] https://apt.v2fly.org/ stable main" | sudo tee /etc/apt/sources.list.d/v2ray.list
```

to

```
$ echo "deb [arch=amd64] https://apt.v2fly.org/ unstable main" | sudo tee /etc/apt/sources.list.d/v2ray.list
```

**Comment by patrickli** [comment]
No it doesn't work like that. Debian repositories have 2 parts,

* Package index, which is the list of all available packages for your current version (stable) of distribution (Debian). You download/update this with `apt-get update`. This includes package metadata such as dependencies, recommends, etc. These sit under the `dists/` directory and each version has its own directory, for example, `dists/stable`, `dists/bullseye/`.
* The actual packages, they live under `pool/`.

In this case, `apt.v2fly.org` does not have a `dists/unstable/` directory. So changing apt list to `unstable` will cause and 404 when apt tries to download the metadata. The metadata for `stable` depends on `libc6 >= 2.32` but this is not available for `stable`.

You have 2 options.
1. `bullseye-backports`  has go 1.17 https://packages.debian.org/bullseye-backports/golang-1.17. You can add the backports repo in your build.
2. Just use the official go docker image. eg, replace https://github.com/v2fly/v2ray-core/blob/master/.github/workflows/deb.yml#L24 with `golang:1.17-bullseye`. If you use this option you no longer need to install `golang-1.17` or adjust `$PATH`.

I personally prefer option 2 as you can't guarantee backports will always have the next version of go available.

**Comment by Loyalsoldier** [comment]
Fixed. Could you try the latest build?

**Comment by patrickli** [comment]
Yep works perfectly. Thanks.
