### ISSUE TITLE
trojan Fallback 中"alpn"无效，此bug是否有计划修复？

### ISSUE THREAD

**Issue by lxhao61** [v2fly/v2ray-core#1282]
trojan Fallback 中"alpn"无效，此bug一直存在，一直没有解决，不知道是否有计划修复？
此bug虽然只影响使用类似nginx做回落服务（nginx 的 h2c 服务不能同时兼容 http/1.1，需要写两行 listen，分别用于http/1.1和 h2c），但因为使用nginx做回落服务的不少，还是建议能修复。
若无计划修复，建议更正[官方配置文档](https://www.v2fly.org/config/protocols/trojan.html#inboundconfigurationobject)，明确告知trojan Fallback 中"alpn"无效，即trojan Fallback中回落h2与http/1.1不能分开。若使用类似nginx做回落服务，tlsSettings中"alpn"不能使用默认值 ["h2", "http/1.1"]，要h2或http/1.1二选一（不能共存）；以便trojan Fallback仅回落h2或http/1.1。
此bug造成的问题见如下：
(https://github.com/XTLS/Xray-core/issues/708)
(https://github.com/XTLS/Xray-core/issues/573)

**Comment by kslr** [comment]
我认为可以简化此处逻辑只保留 fallback Address and port
@xiaokangwang 你怎么看

**Comment by gcphym** [comment]
请问这个bug有计划要修复吗 我也觉得应该要在文档里注明一下...

**Comment by kslr** [comment]
> 请问这个bug有计划要修复吗 我也觉得应该要在文档里注明一下...

已修复
