### ISSUE TITLE
V2RAY_LOCATION_ASSET environment variable seems like has no effect

### ISSUE THREAD

**Issue by chenmin1992** [v2fly/v2ray-core#135]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.27.0

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Update from 4.23.1 to 4.27.0 using https://github.com/v2fly/fhs-install-v2ray/blob/master/install-release.sh and restart the service

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

And V2ray service will not start.

4) What's your expectation?
V2ray service start properly.

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/local/bin/geoip.dat: no such file or directory > exit status 255
```

Client error log:

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.
Systemd unit file:
```bash
# cat /etc/systemd/system/v2ray.service
[Unit]
Description=V2Ray Service
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
Environment=V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.
```bash
 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json -test
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
A unified platform for anti-censorship.
2020/08/27 17:32:46 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Configuration OK.
```

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by kslr** [comment]
what do you want to say

**Comment by chenmin1992** [comment]
> what do you want to say
v2ray读取不到geoip.dat

**Comment by chenmin1992** [comment]
> what do you want to say

看不懂吗?? v2ray读取不到geoip.dat, 路径不对

**Comment by kslr** [comment]
终端运行要加环境变量
