### ISSUE TITLE
TProxy下udp connection无法释放

### ISSUE THREAD

**Issue by ganli** [v2fly/v2ray-core#1355]
## 你正在使用哪个版本的 V2Ray？

4.42.2 4.43.0 还有这个commit 7b0699e 都试过

## 你的使用场景是什么？

Asus 路由器，TProxy转发所有traffic到dokodemo-door.

## 你看到的异常现象是什么？

UDP connection （主要是dns） 不释放，很快有上千个。内存占用大 (700M - 1.5G) ，偶尔无法上网。
admin@RT-AC86U-F698:/tmp/home/root# netstat -anp|grep v2ray|grep udp|wc -l
3535

A lot of udp connections like below:
udp 0 0 :::40956 :::* 2275/v2ray
udp 0 0 :::49148 :::* 2275/v2ray
udp 0 0 :::54780 :::* 2275/v2ray
udp 0 0 :::33276 :::* 2275/v2ray
udp 0 0 :::40700 :::* 2275/v2ray
udp 0 0 180.168.255.118:53 10.0.0.88:41068 ESTABLISHED 2275/v2ray
udp 0 0 192.168.50.1:53 192.168.50.35:51115 ESTABLISHED 2275/v2ray
udp 0 0 180.168.255.118:53 10.0.0.88:51530 ESTABLISHED 2275/v2ray
udp 0 0 192.168.50.1:53 192.168.50.35:55965 ESTABLISHED 2275/v2ray
udp 0 0 180.168.255.118:53 10.0.0.88:28519 ESTABLISHED 2275/v2ray
udp 0 0 192.168.50.1:53 192.168.50.35:59954 ESTABLISHED 2275/v2ray

上面udp connection仅在router里看到，在局域网内其他电脑已看不到

## 你期待看到的正常表现是怎样的？
UDP connection 和 tcp connection，使用完后销毁

## 请附上你的配置

**服务端配置：**

```javascript
// 无服务端配置，freedom就可以重现

```

**客户端配置：**

```javascript
{
  "log": {
    "access": "/opt/etc/v2ray/access.log",
    "error": "/opt/etc/v2ray/error.log",
    "loglevel": "warning"
  },
  "dns": {},
  "inbounds": [
    {
      "tag": "IN_TPROXY",
      "listen": "127.0.0.1",
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy",
          "mark": 255
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "OUT_DIRECT",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    }
  ],
  "routing": {}
}

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
2021/10/26 21:32:07 [Info] [2132901519] proxy/dokodemo: received request for 192.168.50.88:56879
2021/10/26 21:32:07 [Info] [2132901519] app/dispatcher: default route for udp:192.168.50.1:53
2021/10/26 21:32:07 [Info] [2132901519] proxy/freedom: opening connection to udp:192.168.50.1:53
2021/10/26 21:32:07 [Info] [4111644856] proxy/dokodemo: received request for 10.0.0.88:55116
2021/10/26 21:32:07 [Info] [3934058719] proxy/dokodemo: received request for 10.0.0.88:50895
2021/10/26 21:32:07 [Info] [4111644856] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] [4111644856] proxy/freedom: opening connection to udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] [3934058719] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] [3934058719] proxy/freedom: opening connection to udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] [2193914193] proxy/dokodemo: received request for 192.168.50.88:48187
2021/10/26 21:32:07 [Info] [2193914193] app/dispatcher: sniffed domain: www.wd2go.com
2021/10/26 21:32:07 [Info] [2193914193] app/dispatcher: default route for tcp:www.wd2go.com:443
2021/10/26 21:32:07 [Info] [2193914193] proxy/freedom: opening connection to tcp:www.wd2go.com:443
2021/10/26 21:32:07 [Info] [2433480062] proxy/dokodemo: received request for 10.0.0.88:49978
2021/10/26 21:32:07 [Info] [552045611] proxy/dokodemo: received request for 10.0.0.88:56079
2021/10/26 21:32:07 [Info] [2433480062] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] [2433480062] proxy/freedom: opening connection to udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] [552045611] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] [552045611] proxy/freedom: opening connection to udp:180.168.255.118:53
2021/10/26 21:32:07 [Info] app/dns: Localhost got answer: www.wd2go.com -> [54.186.1.46 52.36.158.70 54.190.240.60 44.236.215.173 35.161.13.32 52.25.134.145]
2021/10/26 21:32:07 [Info] [2193914193] proxy/freedom: dialing to tcp:52.36.158.70:443
2021/10/26 21:32:07 [Info] [2193914193] transport/internet/tcp: dialing TCP to tcp:52.36.158.70:443
2021/10/26 21:32:08 [Info] [1194203116] proxy/dokodemo: received request for 192.168.50.88:33627
2021/10/26 21:32:08 [Info] [1194203116] app/dispatcher: default route for udp:192.168.50.1:53
2021/10/26 21:32:08 [Info] [1194203116] proxy/freedom: opening connection to udp:192.168.50.1:53
2021/10/26 21:32:08 [Info] [4047438940] proxy/dokodemo: received request for 10.0.0.88:44760
2021/10/26 21:32:08 [Info] [4047438940] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:08 [Info] [4047438940] proxy/freedom: opening connection to udp:180.168.255.118:53
2021/10/26 21:32:08 [Info] [2587754303] proxy/dokodemo: received request for 192.168.50.88:44470
2021/10/26 21:32:08 [Info] [2587754303] app/dispatcher: default route for udp:47.111.65.114:14171
2021/10/26 21:32:08 [Info] [2587754303] proxy/freedom: opening connection to udp:47.111.65.114:14171
2021/10/26 21:32:09 [Info] [2647388755] proxy/dokodemo: received request for 192.168.50.77:64987
2021/10/26 21:32:09 [Info] [2647388755] app/dispatcher: default route for udp:192.168.50.1:53
2021/10/26 21:32:09 [Info] [2647388755] proxy/freedom: opening connection to udp:192.168.50.1:53
2021/10/26 21:32:09 [Info] [3638081727] proxy/dokodemo: received request for 192.168.50.77:52444
2021/10/26 21:32:09 [Info] [2069351946] proxy/dokodemo: received request for 10.0.0.88:50752
2021/10/26 21:32:09 [Info] [3638081727] app/dispatcher: default route for udp:192.168.50.1:53
2021/10/26 21:32:09 [Info] [3638081727] proxy/freedom: opening connection to udp:192.168.50.1:53
2021/10/26 21:32:09 [Info] [2069351946] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:09 [Info] [2069351946] proxy/freedom: opening connection to udp:180.168.255.118:53
2021/10/26 21:32:09 [Info] [3473252751] proxy/dokodemo: received request for 192.168.50.77:56700
2021/10/26 21:32:09 [Info] [3473252751] app/dispatcher: sniffed domain: courier.push.apple.com
2021/10/26 21:32:09 [Info] [3473252751] app/dispatcher: default route for tcp:courier.push.apple.com:5223
2021/10/26 21:32:09 [Info] [3473252751] proxy/freedom: opening connection to tcp:courier.push.apple.com:5223
2021/10/26 21:32:09 [Info] [841585560] proxy/dokodemo: received request for 10.0.0.88:58908
2021/10/26 21:32:09 [Info] [841585560] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:09 [Info] [841585560] proxy/freedom: opening connection to udp:180.168.255.118:53
2021/10/26 21:32:09 [Info] app/dns: failed to lookup ip for domain courier.push.apple.com at server localhost > lookup courier.push.apple.com on 180.168.255.118:53: no such host
2021/10/26 21:32:09 [Info] [3473252751] proxy/freedom: failed to get IP address for domain courier.push.apple.com > lookup courier.push.apple.com on 180.168.255.118:53: no such host
2021/10/26 21:32:09 [Info] [3473252751] transport/internet/tcp: dialing TCP to tcp:courier.push.apple.com:5223
2021/10/26 21:32:09 [Info] [1693799760] proxy/dokodemo: received request for 10.0.0.88:33366
2021/10/26 21:32:09 [Info] [1779199579] proxy/dokodemo: received request for 10.0.0.88:34345
2021/10/26 21:32:09 [Info] [1693799760] app/dispatcher: default route for udp:180.168.255.118:53
2021/10/26 21:32:09 [Info] [1693799760] proxy/freedom: opening connection to udp:180.168.255.118:53


```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

## 其它相关的配置文件（如 Nginx）和相关日志
和guide给的参考配置差不多

    ip rule add fwmark 1 table 101
    ip route add local 0.0.0.0/0 dev lo table 101

admin@RT-AC86U-F698:/tmp/mnt/samsung128/entware/etc/v2ray# iptables -t mangle -nL
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DIVERT     tcp  --  0.0.0.0/0            0.0.0.0/0            socket
V2RAY      all  --  0.0.0.0/0            0.0.0.0/0

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
V2RAY_MASK  all  --  0.0.0.0/0            0.0.0.0/0

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination

Chain DIVERT (1 references)
target     prot opt source               destination
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK set 0x1
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain V2RAY (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/8
RETURN     all  --  0.0.0.0/0            127.0.0.0/8
RETURN     all  --  0.0.0.0/0            169.254.0.0/16
RETURN     all  --  0.0.0.0/0            172.16.0.0/12
RETURN     all  --  0.0.0.0/0            224.0.0.0/4
RETURN     all  --  0.0.0.0/0            255.255.255.255
RETURN     tcp  --  0.0.0.0/0            10.0.0.0/8
RETURN     udp  --  0.0.0.0/0            10.0.0.0/8           udp dpt:!53
RETURN     tcp  --  0.0.0.0/0            192.168.0.0/16
RETURN     udp  --  0.0.0.0/0            192.168.0.0/16       udp dpt:!53
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            MAC 80:38:96:A2:19:35
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            mark match 0xff
TPROXY     udp  --  0.0.0.0/0            0.0.0.0/0            TPROXY redirect 127.0.0.1:12345 mark 0x1/0xffffffff
TPROXY     tcp  --  0.0.0.0/0            0.0.0.0/0            TPROXY redirect 127.0.0.1:12345 mark 0x1/0xffffffff

Chain V2RAY_MASK (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/8
RETURN     all  --  0.0.0.0/0            127.0.0.0/8
RETURN     all  --  0.0.0.0/0            169.254.0.0/16
RETURN     all  --  0.0.0.0/0            172.16.0.0/12
RETURN     all  --  0.0.0.0/0            224.0.0.0/4
RETURN     all  --  0.0.0.0/0            255.255.255.255
RETURN     tcp  --  0.0.0.0/0            10.0.0.0/8
RETURN     udp  --  0.0.0.0/0            10.0.0.0/8           udp dpt:!53
RETURN     tcp  --  0.0.0.0/0            192.168.0.0/16
RETURN     udp  --  0.0.0.0/0            192.168.0.0/16       udp dpt:!53
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            mark match 0xff
MARK       udp  --  0.0.0.0/0            0.0.0.0/0            MARK set 0x1
MARK       tcp  --  0.0.0.0/0            0.0.0.0/0            MARK set 0x1

**Comment by cattyhouse** [comment]
1. 你的 V2RAY_MASK 有一条规则:
```
RETURN udp -- 0.0.0.0/0 10.0.0.0/8 udp dpt:!53
```
2. 什么意思呢, 就是从华硕本机到 10.0.0.0/8 网络段除了目标端口为 53 之外的所有 **UDP** 包, 然后都会打上 MARK 0x1, 然后触发 reroute-check, 然后送到 PREROUTING, 接着送到 V2RAY链

3. 你的 V2RAY链, 也有一条
```
RETURN udp -- 0.0.0.0/0 10.0.0.0/8 udp dpt:!53
```

4. 那么这个 UDP 包会继续往下走, 送到这里
```
TPROXY udp -- 0.0.0.0/0 0.0.0.0/0 TPROXY redirect 127.0.0.1:12345 mark 0x1/0xffffffff
```

5. 也就是送到了 v2ray 的代理服务器上了. 

6. 也就是你的 华硕路由器与 10.0.0.0/8 这个网络段的 UDP 包, 除了 dst 53 之外的, 都会送到 v2ray, 然后送到 你的 VPS 去处理... 

7. 这条也是一样的问题

```
RETURN udp -- 0.0.0.0/0 192.168.0.0/16 udp dpt:!53
```

**你觉得科学么? 删掉这2条规则.**

附上下面的输出.

```
iptables -t mangle -nvL --line-numbers
iptables -t nat -nvL --line-numbers
```

**Comment by zhylmzr** [comment]
1. 楼主配置并无任何服务器，仅用xray作为流量中转
2. xray出来的流量被mark 0xff, 直接在v2ray表中return，并不会导致流量循环

**Comment by ganli** [comment]
@zhylmzr 是的，这样配是为了排除服务器的问题。原来的配置有服务器，发现udp连接太多后，就简化配置来排查哪儿有问题。
@cattyhouse 我晚上回去打印下。

**Comment by cattyhouse** [comment]
还有
```
ip rule show
ip route show table all
```

假设你手机 iOS 连接 华硕 的 53. 手机ip为  10.0.0.100 , 华硕 ip 为 10.0.0.88, 那么按照你的规则:
1. 10.0.0.100 访问任何域名
2. 向10.0.0.88:53 发起查询
3. 10.0.0.100:任意端口 => 10.0.0.88:53
4. 进入 PREROUTING
5. 由于是udp,且是新连接, 忽略 DIVERT
6. 进入 V2RAY 链
7. 符合 `RETURN udp -- 0.0.0.0/0 10.0.0.0/8 udp dpt:!53`
8. 符合 `TPROXY udp -- 0.0.0.0/0 0.0.0.0/0 TPROXY redirect 127.0.0.1:12345 mark 0x1/0xffffffff`
9. 进入 v2ray 的代理端口, 并打上 MARK 1
10. 由v2ray代替iOS发起 OUTPUT 目标地址 10.0.0.88:53, 源地址变为华硕的地址 10.0.0.88, 也就是华硕自己访问自己. 同时 v2ray 改变其 MARK 为 255
11. 触发 [reroute-check](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/ipv4/netfilter/iptable_mangle.c?h=v5.15.13#n54
)
12. 重新检查 ip rule 表, MARK为255 不符合 `ip rule add fwmark 1 table 101`, 不会再进入 PREROUTING
13. 继续进入 V2RAY_MASK
14. 符合 `RETURN udp -- 0.0.0.0/0 10.0.0.0/8 udp dpt:!53`
15. 符合 `RETURN all -- 0.0.0.0/0 0.0.0.0/0 mark match 0xff`
16. 回到 OUTPUT
17. 由于接下来 OUTPUT 没有任何规则
18. 从 mangle 表进入 nat 表
19. 接下来看你的 nat 表有什么规则了, 如果没有规则
20. 由于你的v2ray的outbounds是 freedom , 华硕本机帮你查询 域名的 ip
21. 转发至华硕本机的 DNS 服务器
22. 转发上游 dns 服务器, 直连
23. 返回ip给iOS
24. 大概率是污染ip, 打不开网页

**Comment by cattyhouse** [comment]
再来看 华硕自己访问一个域名
1. 华硕从 OUTPUT 发起 dns 查询, 目标为 /etc/resolv.conf 里面设置的地址
2. 如果这个地址为 127.0.0.1, 那么问题不大. 
3. 如果这个地址为 10.0.0.88, 那么OUTPUT => 10.0.0.88:53
4. 进入 V2RAY_MASK
5. 符合 RETURN udp -- 0.0.0.0/0 10.0.0.0/8 udp dpt:!53
6. 符合 MARK udp -- 0.0.0.0/0 0.0.0.0/0 MARK set 0x1
7. 打上 mark 1, 触发 reroute-check, 进入 table 101, 进入 lo
8. 进入 PREROUTING
9. 进入 V2RAY 链
10. 符合 RETURN udp -- 0.0.0.0/0 192.168.0.0/16 udp dpt:!53
11. 进入 TPROXY udp -- 0.0.0.0/0 0.0.0.0/0 TPROXY redirect 127.0.0.1:12345 mark 0x1/0xffffffff
12. 进入 v2ray 程序, 由 v2ray 代替你访问 10.0.0.88:53, 走 OUTPUT
13. 改变 mark 为 255
14. 触发 reroute-check
15. 不符合 mark 1, 不会进入table 101, 不会进入 lo. 不会进入 PREROUTING
16. 进入 V2RAY_MASK
17. 死循环...

**Comment by zhylmzr** [comment]
这种情况只会出现在本机DNS服务器设置上游为本机IP，在这种情况下DNS服务本身就失效了，不会出现偶发性的无法上网
