### ISSUE TITLE
【inbounds】中【port】参数能否增加个监听多个不同端口的功能??

### ISSUE THREAD

**Issue by wutongskype** [v2fly/v2ray-core#1379]
![image](https://user-images.githubusercontent.com/40192806/141250302-49375515-0a03-4f4c-979a-047b28c0105d.png)

如图
虽然按文档可以监听一个端口范围，达到同时监听多个端口的效果，但是实际使用起来还是有些局限。
比如v2服务器使用443，但转发面板提供商封了443，就需要另外监听个44443给转发面板用。
想同时监听443和44443这样两个端口，就需要写两个inbounds，使用起来很麻烦。

**Comment by kslr** [comment]
不可以

**Comment by IRN-Kawakaze** [comment]
可以尝试使用 iptables 将 tcp 4443 端口转发到 tcp 443 端口。

例子：
```
iptables -t nat -A PREROUTING -p tcp --dport 4443 -j REDIRECT --to-port 443
```

**Comment by wutongskype** [comment]
> 可以尝试使用 iptables 将 tcp 44443 端口转发到 tcp 443 端口。
> 
> 例子：
> 
> ```
> iptables -t nat -A PREROUTING -p tcp --dport 44443 -j REDIRECT --to-port 443
> ```

我后来也想到这个思路了，折中办法，写了个任意门，把44433转到443上哈

**Comment by zozero** [comment]
你可以直接并列，例如
{
port:1233
},{
port:1234
}
