### ISSUE TITLE
4.27的dns服务器返回空解析

### ISSUE THREAD

**Issue by zenyanbo** [v2fly/v2ray-core#141]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.27.0
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
正常
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
在4.27.0版本，在dns服务器设置中，走直连的dns解析一些域名随机返回空解析（相同域名不一定每次出现这个问题），致使访问出错。目前仅出现于透明代理和手机上的v2rayng（注意要开本地dns模式，用v2ray的dns object做dns服务器），相同配置文件在电脑上用socks5没有问题；不使用本地dns模式也没问题。所以怀疑是流量进入core的第一次解析为空，导致连接中止。
提供一个检测的域名列表：
zeptovm.com
vultr.com
olvps.com
gullo.me
halocloud.net
idc.wiki
linode.com
xiuluohost.com
以及一些个人博客（海外，最好是hk jp us tw的IP）
随便找的一些idc（非广告），一般是ip符合代理规则，域名不包含在域名代理列表。他们出这个的问题的概率更大。

根据观察，dns服务器解析出错的与具体的dns object有关。
  "dns": {
    "hosts": {
      "geosite:category-ads-all": "127.0.0.1",
      "geosite:qihoo360": "127.0.0.1"
    },
    "servers": [
      "223.5.5.5",
      "223.6.6.6",
      {
        "address": "1.1.1.1",
        "domains": [
          "geolocation-!cn"
        ],
        "port": 53
      },
     "1.0.0.1"
    ]
  },
上述是存在该问题的配置，若更改为下述配置则无此问题（也可能概率太小
  "dns": {
    "hosts": {
      "geosite:category-ads-all": "127.0.0.1",
      "geosite:qihoo360": "127.0.0.1"
    },
    "servers": [
      "1.1.1.1",
      “1.0.0.1”，
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn"
        ],
        "port": 53
      },
     "223.6.6.6"
    ]
  },

根据
4) What's your expectation?
修复此问题
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    [config-server.txt](https://github.com/v2fly/v2ray-core/files/5141913/config-server.txt)
```

Client configuration:

```javascript
   [config.txt](https://github.com/v2fly/v2ray-core/files/5141890/config.txt)
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

无（已确定是客户端故障）

Client error log:
08-28 14:31:52.530 I/GoLog   ( 5839): [Debug] v2ray.com/core/app/dns: UDP:119.29.29.29:53 querying DNS for: olvps.com.
08-28 14:31:52.533 I/GoLog   ( 5839): [Debug] v2ray.com/core/app/dns: UDP:119.29.29.29:53 querying DNS for: olvps.com.
08-28 14:31:52.548 I/GoLog   ( 5839): [Info] v2ray.com/core/app/dns: UDP:119.29.29.29:53 got answere: olvps.com. TypeA -> [] 14.61323ms
08-28 14:31:52.548 I/GoLog   ( 5839): [Debug] v2ray.com/core/app/dns: UDP:119.29.29.29:53 updating IP records for domain:olvps.com.
08-28 14:31:52.548 I/GoLog   ( 5839): [Info] v2ray.com/core/app/dns: failed to lookup ip for domain olvps.com at server 
08-28 14:31:52.585 I/GoLog   ( 5839): [Info] v2ray.com/core/app/dns: UDP:119.29.29.29:53 got answere: olvps.com. TypeAAAA -> [] 54.463333ms
08-28 14:31:52.585 I/GoLog   ( 5839): [Debug] v2ray.com/core/app/dns: UDP:119.29.29.29:53 updating IP records for domain:olvps.com.
08-28 14:31:52.586 I/GoLog   ( 5839): [Info] v2ray.com/core/app/dns: failed to lookup ip for domain olvps.com at server 
08-28 14:31:52.590 I/GoLog   ( 5839): [Info] v2ray.com/core/app/dns: UDP:119.29.29.29:53 cache HIT olvps.com -> [] > empty response

之后的记录全是命中119的空缓存，也不查询其他dns了

**Comment by Robot-DaneelOlivaw** [comment]
https://github.com/v2fly/domain-list-community/pull/158#issuecomment-675394655 中有提及类似的表现。

**Comment by zenyanbo** [comment]
> [v2fly / domain-list-community＃158（评论）](https://github.com/v2fly/domain-list-community/pull/158#issuecomment-675394655)中也有引用类似的表现。

还是不一样，他是因为在geosite:cn中的域名无法解析出包含在geoip:cn中的结果，所以返回空解析。而我这个情况，是单独的"223.5.5.5"/"119.29.29.29"没有额外配置，都返回空解析。

**Comment by Loyalsoldier** [comment]
@zenyanbo 试试刚发布的最新版 v4.27.2

**Comment by zenyanbo** [comment]
> @zenyanbo 试试刚发布的最新版 [v4.27.4](https://github.com/v2fly/v2ray-core/releases/tag/v4.27.4)

多谢。软路由最近不在身边不方便测试，等ng发布新版本我试试

**Comment by zenyanbo** [comment]
> @zenyanbo 试试刚发布的最新版 [v4.27.4](https://github.com/v2fly/v2ray-core/releases/tag/v4.27.4)

出错概率大大降低了，但是仍然存在。

**Comment by zenyanbo** [comment]
实测https+local此问题完全消失

**Comment by qqqaadd** [comment]
是否应该删除错误响应的缓存
```
//原log
2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 querying DNS for: xiuluhost.com.
2020/09/01 18:16:41 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:192.168.50.1:53
2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: xiuluhost.com. TypeA -> [] 373.803582ms
2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 updating IP records for domain:xiuluhost.com.
2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
2020/09/01 18:16:41 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > rcode: 3
2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 cache HIT xiuluhost.com -> [] > rcode: 3
2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
2020/09/01 18:16:41 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > rcode: 3
2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 cache HIT xiuluhost.com -> [] > rcode: 3
2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
2020/09/01 18:16:41 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > rcode: 3
```
比如做了如下修改
```
// app/dns/udpns.go
func (s *ClassicNameServer) HandleResponse(ctx context.Context, packet *udp_proto.Packet) {

	ipRec, err := parseResponse(packet.Payload.Bytes())
	if err != nil {
		newError(s.name, " fail to parse responded DNS udp").AtError().WriteToLog()
		return
	}

+	if dns_feature.RCodeFromError(lastErr) > 0 {
+		newError(s.name, " fail. DNS response status code: ", lastErr).AtError().WriteToLog()
+		delete(s.ips, domain)
+	}
...

// app/dns/dohdns.go
func (s *DoHNameServer) sendQuery(ctx context.Context, domain string, option IPOption) {
...
-	if option.IPv6Enable && record.AAAA != nil && record.AAAA.RCode == dnsmessage.RCodeSuccess {
+	if option.IPv6Enable && record.AAAA != nil {
		aaaa, err := record.AAAA.getIPs()
		if err != nil {
			lastErr = err
		}
		ips = append(ips, aaaa...)
	}

-	if option.IPv4Enable && record.A != nil && record.A.RCode == dnsmessage.RCodeSuccess {
+	if option.IPv4Enable && record.A != nil {
		a, err := record.A.getIPs()
		if err != nil {
			lastErr = err
		}
		ips = append(ips, a...)
	}

	if len(ips) > 0 {
		return toNetIP(ips), nil
	}

+	if dns_feature.RCodeFromError(lastErr) > 0 {
+		newError(s.name, " fail. DNS response status code: ", lastErr).AtError().WriteToLog()
+		delete(s.ips, domain)
+	}

// app/dns/server.go
func (s *Server) lookupIPInternal(domain string, option IPOption) ([]net.IP, error) {
...
-		if err != context.Canceled && err != context.DeadlineExceeded && err != errExpectedIPNonMatch {
+		if err != context.Canceled && err != context.DeadlineExceeded && err != errExpectedIPNonMatch && dns.RCodeFromError(err) == 0 {
			return nil, err
		}
	}

	return nil, newError("returning nil for domain ", domain).Base(lastErr)
}

```
```
//修改后log
2020/09/01 21:24:28 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:192.168.50.1:53
2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: xiuluhost.com. TypeA -> [] 20.326809ms
2020/09/01 21:24:28 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 updating IP records for domain:xiuluhost.com.
2020/09/01 21:24:28 [Error] v2ray.com/core/app/dns: UDP:192.168.50.1:53 fail. DNS response status code: rcode: 3
2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: DOHL//dns.alidns.com querying: xiuluhost.com.
2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: DOHL//dns.alidns.com got answer: xiuluhost.com. TypeA -> [] 74.270142ms
2020/09/01 21:24:28 [Error] v2ray.com/core/app/dns: DOHL//dns.alidns.com fail. DNS response status code: rcode: 3
2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server DOHL//dns.alidns.com > rcode: 3
2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: DOH//cloudflare-dns.com querying: xiuluhost.com.
2020/09/01 21:24:29 [Info] v2ray.com/core/app/dns: DOH//cloudflare-dns.com got answer: xiuluhost.com. TypeA -> [] 163.114436ms
2020/09/01 21:24:29 [Error] v2ray.com/core/app/dns: DOH//cloudflare-dns.com fail. DNS response status code: rcode: 3
2020/09/01 21:24:29 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server DOH//cloudflare-dns.com > rcode: 3
2020/09/01 21:24:29 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server localhost > lookup xiuluhost.com on 192.168.50.1:53: no such host
2020/09/01 21:24:29 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > lookup xiuluhost.com on 192.168.50.1:53: no such host

```

**Comment by zenyanbo** [comment]
> 是否应该删除错误响应的缓存
> 
> ```
> //原log
> 2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 querying DNS for: xiuluhost.com.
> 2020/09/01 18:16:41 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:192.168.50.1:53
> 2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: xiuluhost.com. TypeA -> [] 373.803582ms
> 2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 updating IP records for domain:xiuluhost.com.
> 2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
> 2020/09/01 18:16:41 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > rcode: 3
> 2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 cache HIT xiuluhost.com -> [] > rcode: 3
> 2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
> 2020/09/01 18:16:41 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > rcode: 3
> 2020/09/01 18:16:41 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 cache HIT xiuluhost.com -> [] > rcode: 3
> 2020/09/01 18:16:41 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
> 2020/09/01 18:16:41 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > rcode: 3
> ```
> 
> 比如做了如下修改
> 
> ```
> // app/dns/udpns.go
> func (s *ClassicNameServer) findIPsForDomain(domain string, option IPOption) ([]net.IP, error) {
> ...
> +	if dns_feature.RCodeFromError(lastErr) > 0 {
> +		newError(s.name, " fail. DNS response status code: ", lastErr).AtError().WriteToLog()
> +		delete(s.ips, domain)
> +	}
> 
> 	if lastErr != nil {
> 		return nil, lastErr
> 	}
> 
> 	return nil, dns_feature.ErrEmptyResponse
> }
> 
> // app/dns/dohdns.go
> func (s *DoHNameServer) findIPsForDomain(domain string, option IPOption) ([]net.IP, error) {
> ...
> -	if option.IPv6Enable && record.AAAA != nil && record.AAAA.RCode == dnsmessage.RCodeSuccess {
> +	if option.IPv6Enable && record.AAAA != nil {
> 		aaaa, err := record.AAAA.getIPs()
> 		if err != nil {
> 			lastErr = err
> 		}
> 		ips = append(ips, aaaa...)
> 	}
> 
> -	if option.IPv4Enable && record.A != nil && record.A.RCode == dnsmessage.RCodeSuccess {
> +	if option.IPv4Enable && record.A != nil {
> 		a, err := record.A.getIPs()
> 		if err != nil {
> 			lastErr = err
> 		}
> 		ips = append(ips, a...)
> 	}
> 
> 	if len(ips) > 0 {
> 		return toNetIP(ips), nil
> 	}
> 
> +	if dns_feature.RCodeFromError(lastErr) > 0 {
> +		newError(s.name, " fail. DNS response status code: ", lastErr).AtError().WriteToLog()
> +		delete(s.ips, domain)
> +	}
> ...
> 
> // app/dns/server.go
> func (s *Server) lookupIPInternal(domain string, option IPOption) ([]net.IP, error) {
> ...
> -		if err != context.Canceled && err != context.DeadlineExceeded && err != errExpectedIPNonMatch {
> +		if err != context.Canceled && err != context.DeadlineExceeded && err != errExpectedIPNonMatch && dns.RCodeFromError(err) == 0 {
> 			return nil, err
> 		}
> 	}
> 
> 	return nil, newError("returning nil for domain ", domain).Base(lastErr)
> }
> ```
> 
> ```
> //修改后log
> 2020/09/01 21:24:28 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:192.168.50.1:53
> 2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: xiuluhost.com. TypeA -> [] 20.326809ms
> 2020/09/01 21:24:28 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 updating IP records for domain:xiuluhost.com.
> 2020/09/01 21:24:28 [Error] v2ray.com/core/app/dns: UDP:192.168.50.1:53 fail. DNS response status code: rcode: 3
> 2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server UDP:192.168.50.1:53 > rcode: 3
> 2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: DOHL//dns.alidns.com querying: xiuluhost.com.
> 2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: DOHL//dns.alidns.com got answer: xiuluhost.com. TypeA -> [] 74.270142ms
> 2020/09/01 21:24:28 [Error] v2ray.com/core/app/dns: DOHL//dns.alidns.com fail. DNS response status code: rcode: 3
> 2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server DOHL//dns.alidns.com > rcode: 3
> 2020/09/01 21:24:28 [Info] v2ray.com/core/app/dns: DOH//cloudflare-dns.com querying: xiuluhost.com.
> 2020/09/01 21:24:29 [Info] v2ray.com/core/app/dns: DOH//cloudflare-dns.com got answer: xiuluhost.com. TypeA -> [] 163.114436ms
> 2020/09/01 21:24:29 [Error] v2ray.com/core/app/dns: DOH//cloudflare-dns.com fail. DNS response status code: rcode: 3
> 2020/09/01 21:24:29 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server DOH//cloudflare-dns.com > rcode: 3
> 2020/09/01 21:24:29 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain xiuluhost.com at server localhost > lookup xiuluhost.com on 192.168.50.1:53: no such host
> 2020/09/01 21:24:29 [Info] v2ray.com/core/app/router: resolve ip for xiuluhost.com > lookup xiuluhost.com on 192.168.50.1:53: no such host
> ```

不知道。。。

**Comment by qqqaadd** [comment]
或许保留缓存好一点，去掉。。。
```
// app/dns/udpns.go
func (s *ClassicNameServer) findIPsForDomain(domain string, option IPOption) ([]net.IP, error) {
...
-	if dns_feature.RCodeFromError(lastErr) > 0 {
-		newError(s.name, " fail. DNS response status code: ", lastErr).AtError().WriteToLog()
-		delete(s.ips, domain)
-	}
...

// app/dns/dohdns.go
func (s *DoHNameServer) findIPsForDomain(domain string, option IPOption) ([]net.IP, error) {
...
-	if dns_feature.RCodeFromError(lastErr) > 0 {
-		newError(s.name, " fail. DNS response status code: ", lastErr).AtError().WriteToLog()
-		delete(s.ips, domain)
-	}
...
```
```
log
//第1轮
2020/09/02 09:18:13 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 querying DNS for: asdfgerw.sa.
2020/09/02 09:18:13 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:192.168.50.1:53
2020/09/02 09:18:13 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:192.168.50.1:53
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dispatcher: taking detour [drOut] for [udp:192.168.50.1:53]
2020/09/02 09:18:13 [Info] v2ray.com/core/proxy/freedom: opening connection to udp:192.168.50.1:53
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answer: asdfgerw.sa. TypeA -> [] 129.114334ms
2020/09/02 09:18:13 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 updating IP records for domain:asdfgerw.sa.
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server UDP:192.168.50.1:53 > rcode: 3
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dns: DOHL//dns.alidns.com querying: asdfgerw.sa.
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dns: DOHL//dns.alidns.com got answer: asdfgerw.sa. TypeA -> [] 585.420352ms
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server DOHL//dns.alidns.com > rcode: 3
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dns: DOH//cloudflare-dns.com querying: asdfgerw.sa.
2020/09/02 09:18:13 [Info] v2ray.com/core/app/dispatcher: taking detour [dns] for [tcp:cloudflare-dns.com:443]
2020/09/02 09:18:13 [Info] v2ray.com/core/common/mux: dispatching request to tcp:cloudflare-dns.com:443
2020/09/02 09:18:13 [Info] v2ray.com/core/proxy/freedom: opening connection to tcp:v1.mux.cool:9527
2020/09/02 09:18:13 [Debug] v2ray.com/core/app/proxyman/outbound: proxying to giaOut for dest tcp:v1.mux.cool:9527
2020/09/02 09:18:13 [Info] v2ray.com/core/transport/internet/websocket: creating connection to tcp:×:443
2020/09/02 09:18:14 [Info] v2ray.com/core/proxy/vless/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:×:443
2020/09/02 09:18:15 [Info] v2ray.com/core/app/dns: DOH//cloudflare-dns.com got answer: asdfgerw.sa. TypeA -> [] 1.58556036s
2020/09/02 09:18:15 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server DOH//cloudflare-dns.com > rcode: 3
2020/09/02 09:18:15 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server localhost > lookup asdfgerw.sa on 192.168.50.1:53: no such host
2020/09/02 09:18:15 [Info] v2ray.com/core/app/router: resolve ip for asdfgerw.sa > lookup asdfgerw.sa on 192.168.50.1:53: no such host

//第2轮，用上缓存
2020/09/02 09:18:15 [Debug] v2ray.com/core/app/dns: UDP:192.168.50.1:53 cache HIT asdfgerw.sa -> [] > rcode: 3
2020/09/02 09:18:15 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server UDP:192.168.50.1:53 > rcode: 3
2020/09/02 09:18:15 [Debug] v2ray.com/core/app/dns: DOHL//dns.alidns.com cache HIT asdfgerw.sa -> [] > rcode: 3
2020/09/02 09:18:15 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server DOHL//dns.alidns.com > rcode: 3
2020/09/02 09:18:15 [Debug] v2ray.com/core/app/dns: DOH//cloudflare-dns.com cache HIT asdfgerw.sa -> [] > rcode: 3
2020/09/02 09:18:15 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server DOH//cloudflare-dns.com > rcode: 3
2020/09/02 09:18:15 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain asdfgerw.sa at server localhost > lookup asdfgerw.sa on 192.168.50.1:53: no such host
2020/09/02 09:18:15 [Info] v2ray.com/core/app/router: resolve ip for asdfgerw.sa > lookup asdfgerw.sa on 192.168.50.1:53: no such host
//第3轮。。。

//反正一会缓存就过期了
2020/09/02 09:28:13 [Debug] v2ray.com/core/app/dns: DOHL//dns.alidns.com cleanup asdfgerw.sa.
2020/09/02 09:28:15 [Debug] v2ray.com/core/app/dns: DOH//cloudflare-dns.com cleanup asdfgerw.sa.
```

**Comment by zenyanbo** [comment]
算了，懒得折腾这问题了，没看见别人有的，可能个例。我去用clash算了

**Comment by arm64v8a** [comment]
挖坟

2020年至今，代码经过重构，仍有类似问题。

问题导致 SagerNet 系列软件连接某些域名时出现严重的断流。（条件：A记录TTL极短，AAAA记录为空且TTL长）

```
I/v2ray-core: app/dns: DOHL//doh.pub cache HIT gz-cm-kl.klee.store -> [] > empty response
I/v2ray-core: app/dns: failed to lookup ip for domain gz-cm-kl.klee.store at server DOHL//doh.pub > empty response
```

参考修复 
https://github.com/MatsuriDayo/v2ray-core/commit/187782b1d70d6c69fde1bba9b1a20e20849dbf3e
