### ISSUE TITLE
当节点用多文件配置在一个文件夹时，probeInterval 为单个节点的间隔

### ISSUE THREAD

**Issue by yanwh0311** [v2fly/v2ray-core#1445]
比如，在文件夹 outbounds/ 下有N个文件，outbound1.json
outbound2.json
.......
分别都是一个节点

执行
v2ray -c base.json -confdir outbounds/
probeInterval 的值却是每个节点的探测时间
这样，如果节点少，探测间隔小，会导致探测过于频繁，但如果探测间隔大，比如30分钟，那探测完一个后要等30分钟才能探测第二个，如果第一个节点是坏的，那就有30分钟连不上。
如果节点多，比如30个节点，间隔设置为1m，那也要30分钟才能探测完。

需求： probeInterval应该为所有节点循环一次的时间间隔

**Comment by digglife** [comment]
这个问题曾经有过一个 Issue #1227，我提过一个 PR #1241 增加了并发 Probe 的功能，可以保证 `probeInterval` 为所有节点循环一次的间隔，不过没有被合并。
