### ISSUE TITLE
在纯IPv6的环境下，安装出错

### ISSUE THREAD

**Issue by Smilence-Maverick** [v2fly/v2ray-core#147]
bash <(curl -L -s https://install.direct/go.sh)
ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this

OS： CentOS7.6-64bit-minimal
Platform: euserv.com
IP Address: IPv6 Only

**Comment by Loyalsoldier** [comment]
Please read the error message and instruction and follow the lead.

**Comment by Smilence-Maverick** [comment]
raw.githubusercontent.com
Does NOT support IPv6 now....What's wrong?

**Comment by kslr** [comment]
I suggest you read the error message

**Comment by Smilence-Maverick** [comment]
raw.githubusercontent.com是不错，但不支持IPv6
能另外找个可下载的地方吗？

**Comment by kslr** [comment]
这是你的问题，而不是 ipv6 的问题

**Comment by Loyalsoldier** [comment]
> raw.githubusercontent.com是不错，但不支持IPv6
> 能另外找个可下载的地方吗？

Please use IPv4 network then. Or install manually.
