### ISSUE TITLE
Connections through HTTPS proxies with h2 alpn frequently stall 

### ISSUE THREAD

**Issue by ValdikSS** [v2fly/v2ray-core#1477]
## What version of V2Ray are you using?

V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)

## What's your scenario of using V2Ray?

HTTPS (Secure Web Proxy / HTTP with TLS) proxy configured as outbound, with `"security": "tls"` `streamSettings`.  
The proxy has TLS h2 apln support.

## What problems have you encountered?

The connections via this proxy frequently stall. It's very unstable, 1/3 connection attempts either stall or fail.

When this proxy switched in http/1.1-only mode by adding `"alpn": ["http/1.1"]` to `"tlsSettings"`, everything works fine without stalls.

There is somewhat similar but not exactly the same bug in curl, listed as KNOWN_BUG: https://github.com/curl/curl/issues/6936  
This has nothing to do with v2ray, but it may give some hints.

## How to reproduce

1. You'll need a HTTP(S) proxy with h2 support. h2 support could be provided by `nghttpx`.
2. Configure outbound with `"protocol": "http"`, `"streamSettings": {"security": "tls"}`
3. Execute multiple requests over inbound in a row. It doesn't matter whether the requests go to HTTP or HTTPS website (unlike curl's bug), also h2 support for the destination does not matter.

## What's your expectation?

v2ray correctly works with h2 tls http proxy servers.

## Please attach your configuration here

**Client configuration:**

```javascript
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [{
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    },
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    }
  }],
  "outbounds": [
  {
    "protocol": "http",
    "settings": {
      "servers": [{
        "address": "proxy-server.com",
        "port": 443,
        "users": [
          {
            "user": "xxxxxxxxxx",
            "pass": "xxxxxxxxxx"
          }
        ]
      }]
    },
    "streamSettings": {
      "security": "tls",
      "tlsSettings": {
        //"alpn": ["http/1.1"],
        "allowInsecure": true
      }
    }
  }
  ]
}
```

## Please attach error logs here

**Client error log:**

```javascript
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
2021/12/21 21:44:54 [Info] main/jsonem: Reading config: ./test.json
2021/12/21 21:44:54 [Debug] app/log: Logger started
2021/12/21 21:44:54 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1080
2021/12/21 21:44:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
2021/12/21 21:44:54 [Warning] V2Ray 4.44.0 started
2021/12/21 21:44:55 [Info] [3480259294] proxy/socks: TCP Connect request to tcp:ifconfig.co:80
2021/12/21 21:44:55 [Info] [3480259294] app/dispatcher: sniffed domain: ifconfig.co
2021/12/21 21:44:55 [Info] [3480259294] app/dispatcher: default route for tcp:ifconfig.co:80
2021/12/21 21:44:55 tcp:127.0.0.1:51676 accepted tcp:ifconfig.co:80
2021/12/21 21:44:55 [Info] [3480259294] transport/internet/tcp: dialing TCP to tcp:proxy-server.com:443
2021/12/21 21:45:20 [Info] [3480259294] app/proxyman/outbound: failed to process outbound traffic > proxy/http: connection ends > context canceled
2021/12/21 21:45:20 [Info] [3480259294] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
```

```
$ curl --proxy socks5h://127.0.0.1:1080 http://ifconfig.co
curl: (52) Empty reply from server
```

Note the timings. The proxy server is 100% stable and working (this is a commercial proxy, not v2ray, I don't know exact software), there's no issues when using `http/1.1` alpn or empty `"alpn": []`. This is not due to traffic filtering/censorship.

**Comment by ValdikSS** [comment]
Please reopen.

**Comment by liudongmiao** [comment]
@ValdikSS For most of implementation, there is no websocket over http2.
Even Chrome says it ships websocket over http2, it doesn't at all.
(You can use wireshark to check, websocket in chrome only send http/1.1 with alpn.)

**Comment by ValdikSS** [comment]
@liudongmiao, this is not a websocket, this is a HTTP(S) proxy.
