### ISSUE TITLE
Bittorrent 嗅探只能识别 BT Handshake 数据包

### ISSUE THREAD

**Issue by digglife** [v2fly/v2ray-core#1499]
我因为本月使用 BT 比较多导致 VPS 进出流量剧增，几乎突破每月上限，所以注意到了，不确定是 Bug 还是预期行为。

## 你正在使用哪个版本的 V2Ray？

V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/arm64)
A unified platform for anti-censorship.

## 你的使用场景是什么？

直连 BT，其他流量按正常路由规则。

## 你看到的异常现象是什么？

BT 下载上传流量依然被转发到代理 VPS。

[关于 Bittorrent Sniff 的代码](https://github.com/v2fly/v2ray-core/blob/master/common/protocol/bittorrent/bittorrent.go#L25-L35)只能识别出 BT 的 handshake 流量，而所有 Message 流量，包括上传下载 Piece 都无法通过 Sniff 来识别出 Protocol，于是多数 BT 流量都在 V2Ray 控制之外。如果我的路由规则是代理黑名单模式（默认走代理），那这些流量都会转发到 VPS。

https://github.com/v2fly/v2ray-core/blob/ef58fde0ba5ffd63477bb7c6df634cc296479ae8/common/protocol/bittorrent/bittorrent.go#L25-L35

只有 Handshake 数据包会有 Protocol Name：

![image](https://user-images.githubusercontent.com/1468378/147629373-c103dda6-053b-419d-8c54-0dda9576e92c.png)

其他 Message 如 Piece 上传下载则没有：

![image](https://user-images.githubusercontent.com/1468378/147629437-c5e3599d-0bba-4059-8680-00f3b5c8f8b9.png)

## 你期待看到的正常表现是怎样的？

所有 BT 流量直连

## 请附上你的配置

**服务端配置：**

本问题和服务端无关

**客户端配置：**

已隐去多数无关配置。

```javascript
{
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "inbounds": [
    {
      "port": 1081,
      "protocol": "dokodemo-door",
      "settings": {
        "followRedirect": true,
        "network": "tcp"
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "redirect"
        }
      },
      "tag": "transparent",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "metadataOnly": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "vps_ip",
            "port": 8888,
            "users": [
              {
                "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "alterId": 64,
                "security": "auto",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "tag": "direct"
    }
  ]
}
```

**Comment by digglife** [comment]
因为 BT Message 流量没有十分明确的特征，估计无法仅仅通过分析 Payload 来准确判断。

但如果仅仅是嗅探 Handshake 流量，那感觉这个功能的必要性就不太大了，而且[白话文指南中也提到了 BT 直连](https://guide.v2fly.org/routing/bittorrent.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE)，实际是做不到的。

**Comment by kslr** [comment]
加密的数据也识别不到，的确比较鸡肋

**Comment by Machtergreifung** [comment]
v2ray对bittorrent的handshake识别好像仅基于peer_id

**Comment by Xyncgas** [comment]
这些事情本来就应该由代理软件来作 (例如proxifier)
