### ISSUE TITLE
vless不回落而直接reject connection

### ISSUE THREAD

**Issue by Alex-coffen** [v2fly/v2ray-core#150]
Server v2ray version: v4.27.4

Server config:
```
{
    "log": {
	     "access": "/var/log/alex.log",
             "error": "/var/log/alex.log",
             "loglevel": "debug"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "50332244-16a4-4728-a1c2-da5b81ddc28c",
                        "level": 0,
                        "email": "buddy@gmail.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    }
		]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/ssl/cc.crt",
                            "keyFile": "/ssl/cc.key"
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        }
    ]
}
```

nginx config:
```
    server {
        listen 0.0.0.0:80;

        charset utf-8;

        access_log /var/log/nginx/access.log main;

        location / {
            root /usr/share/nginx/html;
        }

        error_page  404              /404.html;

        error_page 500 502 503 504 /50x.html;
    }
```

Serve Debug log:
2020/08/31 15:35:26 [Info] [4167277421] v2ray.com/core/proxy/vless/inbound: firstLen = 527
2020/08/31 15:35:26 129.226.189.243:24651 rejected  v2ray.com/core/proxy/vless/encoding: invalid request version
2020/08/31 15:35:26 [Warning] [4167277421] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from 129.226.189.243:24651 > v2ray.com/core/proxy/vless/encoding: invalid request version
2020/08/31 15:35:27 129.226.189.243:33422 rejected  v2ray.com/core/proxy/vless/encoding: invalid request version
2020/08/31 15:35:27 [Info] [1022286226] v2ray.com/core/proxy/vless/inbound: firstLen = 539
2020/08/31 15:35:27 [Warning] [1022286226] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from 129.226.189.243:33422 > v2ray.com/core/proxy/vless/encoding: invalid request version
2020/08/31 15:35:32 129.226.189.243:12138 rejected  v2ray.com/core/proxy/vless/encoding: invalid request version
2020/08/31 15:35:32 [Info] [1627545069] v2ray.com/core/proxy/vless/inbound: firstLen = 539
2020/08/31 15:35:32 [Warning] [1627545069] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from 129.226.189.243:12138 > v2ray.com/core/proxy/vless/encoding: invalid request version

直接web访问服务器80端口可以访问index.html, 通过服务器443端口https访问不了index.html
请问哪里没配对导致不回落呢？

**Comment by dna1982** [comment]
我刚折腾好，80可以访问index.html，443也可以访问index.html(https)。
我看了下V2RAY配置文件，和你的没有什么区别。

**Comment by Alex-coffen** [comment]
"fallbacks": [
                    {
                        "dest": "127.0.0.1:80"
                    }
		]
我nginx和v2ray都是用docker跑的， 我发现不能直接用端口， 需要加127.0.0.1

**Comment by dna1982** [comment]
> ```
>             "fallbacks": [
>                 {
>                     "dest": "127.0.0.1:80"
>                 }
> 	]
> ```
> 
> 我nginx和v2ray都是用docker跑的， 我发现不能直接用端口， 需要加127.0.0.1

vless 的文档上不是写了会自动加127.0.0.1么。

**Comment by Alex-coffen** [comment]
我试过了。nginx docker不动，在宿主机而不在docker启动v2ray, 只用80可以回落。但是如果启动v2ray的docker, 只用80就是连不上，需要加127.0.0.1. 原因不懂

**Comment by rprx** [comment]
> 
> 
> 我试过了。nginx docker不动，在宿主机而不在docker启动v2ray, 只用80可以回落。但是如果启动v2ray的docker, 只用80就是连不上，需要加127.0.0.1. 原因不懂

应该不会出现这种区别，填 `80` 会先被转换成 `"127.0.0.1:80"` 再使用

**Comment by Alex-coffen** [comment]
加了127.0.0.1也不行， 不知道为什么， 用docker的v2ray就是没办法回落成功。但是在宿主机直接装就可以。
想不通

**Comment by Alex-coffen** [comment]
而且我在宿主机用install_release.sh 安装之后还执行不成功：
```
root@instance-2:~# systemctl status v2ray
● v2ray.service - V2Ray Service
     Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-08-31 20:12:27 CST; 10s ago
    Process: 187649 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=23)
   Main PID: 187649 (code=exited, status=23)

Aug 31 20:12:26 instance-2 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Aug 31 20:12:27 instance-2 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Aug 31 20:12:27 instance-2 systemd[1]: Stopped V2Ray Service.
Aug 31 20:12:27 instance-2 systemd[1]: v2ray.service: Start request repeated too quickly.
Aug 31 20:12:27 instance-2 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Aug 31 20:12:27 instance-2 systemd[1]: Failed to start V2Ray Service.
```
但是我单独执行/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json， 可以启动v2ray， 而且回落正常。

**Comment by rprx** [comment]
> 
> 
> 之前搞错了，应该是有一段时间的缓存，所以即使加了127.0.0.1也不行， 不知道为什么， 用docker的v2ray就是没办法回落成功。但是在宿主机直接装就可以。
> 想不通

我记得 docker 容器内 127.0.0.1 只代表本容器，如果你的 v2ray 和 nginx 不在同一个容器内，当然不能 127.0.0.1。

**Comment by Alex-coffen** [comment]
我用的host模式，理论上127.0.0.1是可以的。我也试过桥接bridge模式，不用127.0.0.1，而是用nginx docker的局域网ip地址，还是不行。我再研究研究

**Comment by Alex-coffen** [comment]
close this ticket.
至少宿主机上直接安装v2ray没有回落的问题。 
为什么docker容器里不行，我试过很多方法，使用docker0的IP， 或者直接使用host模式，或者bridge模式，都回落不成功。有时候不知道怎么搞好像可以成功一次，但是我刷新浏览器又不行。

**Comment by rprx** [comment]
（或许是 docker 的 BUG 或者配置错误
