### ISSUE TITLE
出现VMessAEAD怎么解决

### ISSUE THREAD

**Issue by AbelTu96** [v2fly/v2ray-core#1509]
rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.

**Comment by Fall-Rain** [comment]
I also encountered the same problem very headache

**Comment by kslr** [comment]
alter use 0 or set env

**Comment by Fall-Rain** [comment]
How to go about setting it, I don't know how to change the environment variables

**Comment by AbelTu96** [comment]
I used someone else’s one-click script, I don’t know how to change the environment variable

**Comment by kslr** [comment]
```
export V2RAY_VMESS_AEAD_FORCED=false
```

**Comment by Fall-Rain** [comment]
Oh thanks, my problem is solved, docker needs to change docker-compose.yml
![1641016888(1)](https://user-images.githubusercontent.com/36319339/147844930-933252ae-07a3-428a-bf79-518eb1711cae.jpg)

**Comment by database64128** [comment]
> I used someone else’s one-click script, I don’t know how to change the environment variable

If you prefer third-party scripts, then you should ask the script author for support.

**Comment by laggage** [comment]
> ```
> export V2RAY_VMESS_AEAD_FORCED=false
> ```

v2ray.service文件中配置环境变量可以解决

![image](https://user-images.githubusercontent.com/38829279/147897404-28d1f122-38d4-4200-9fb5-6c33f72e3eb9.png)

```config
Environment='V2RAY_VMESS_AEAD_FORCED=false'
```

**Comment by Gaylone** [comment]
> > ```
> > export V2RAY_VMESS_AEAD_FORCED=false
> > ```
> 
> v2ray.service文件中配置环境变量可以解决
> 
> ![image](https://user-images.githubusercontent.com/38829279/147897404-28d1f122-38d4-4200-9fb5-6c33f72e3eb9.png)
> 
> ```
> Environment='V2RAY_VMESS_AEAD_FORCED=false'
> ```

Windows环境下怎么配置呢？

**Comment by Gaylone** [comment]
Windows环境下怎么配置呢

**Comment by wuxianggujun** [comment]
脚本内置这个，但是还是会出现问题

**Comment by TomCaat** [comment]
> alter use 0 or set env

it should be the root reason there. After i have reset alterId value of my client side to 0, all works well. 
There are not that kind of error any more on my server side.

I have further found the root cause there: https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E6%B7%98%E6%B1%B0%E6%9C%BA%E5%88%B6

The MD5 is retired for vmess protocol so that the server side will reject requests with this.
And it seems that alertid value will use MD5 to generate the extra UUID.
