### ISSUE TITLE
DNS请求流程

### ISSUE THREAD

**Issue by timeday1102** [v2fly/v2ray-core#1521]
这种dns配置下，加入我想访问google.com ，它是通过哪个dns地址查询google.com的ip呢？

1. 访问google.com -> routing理由规则中查询不到 -> dns查询获取ip -> 通过 “https://223.5.5.5/dns-query”地址查询ip -> 被 “dns-out”出站代理拦截？ 换成“8.8.8.8” 查询？
2. 还有，通过任意门6450端口进来的dns查询，是直接去“1.0.0.1” 查询， 还是被 “dns-out”出站代理拦截？ 换成“8.8.8.8” 查询？

![image](https://user-images.githubusercontent.com/57295339/148053245-3e74a93d-9c95-48af-90e9-47ea8abd6223.png)

**Comment by capxax** [comment]
应该是“https://223.5.5.5
netstat-an 里无论客户端还是服务端都没有1.0.01和8888的连接

**Comment by timeday1102** [comment]
> 应该是“https://223.5.5.5 netstat-an 里无论客户端还是服务端都没有1.0.01和8888的连接

好的，谢谢回答
