### ISSUE TITLE
feedback errors

### ISSUE THREAD

**Issue by jkle112** [v2fly/v2ray-core#1524]
V2ray in linux system x64,will from v4.44 upgrade to v5.0.2 Developer Preview ,but show me some errors.
![Screenshot from 2022-01-07 04-26-11](https://user-images.githubusercontent.com/17021524/148523916-1878422e-c9d5-49db-850e-d1fb67f9cf26.png)
![Screenshot from 2022-01-07 04-26-27](https://user-images.githubusercontent.com/17021524/148523924-c45383f5-dd21-4160-9c9e-37d9575298dd.png)

**Comment by database64128** [comment]
Please wait until Qv2ray adds support for v2ray v5.
