### ISSUE TITLE
ILLEGAL INSTRUCTION on mipsel device with no hardware floating point support

### ISSUE THREAD

**Issue by cyber9723470** [v2fly/v2ray-core#1530]
## What version of V2Ray are you using?
v5.0.2 Developer Preview

## What's your scenario of using V2Ray?

Using V2Ray on routers.

## What problems have you encountered?

ILLEGAL INSTRUCTION on mipsel device with no hardware floating point support

https://github.com/v2fly/v2ray-core/pull/468

## What's your expectation?

add MIPS SoftFloat support

**Comment by AkinoKaede** [comment]
In the past, the binaries with softfloat support were added to the release of V2Ray.  But then it was removed. Currently, you could build V2Ray with softfloat support by yourself.

**Comment by AkinoKaede** [comment]
BTW, the performance of  the CPUs without float instructions support usually is too low to run V2Ray smoothly.

**Comment by cyber9723470** [comment]
> build V2Ray with softfloat support by yourself.

How to enable softfloat in the build script?

**Comment by AkinoKaede** [comment]
> > build V2Ray with softfloat support by yourself.
> 
> How to enable softfloat in the build script?

set the `GOMIPS` environment variable to `softfloat`. For exmaple:

```bash
GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -v -o v2ray -trimpath -ldflags "-s -w -buildid=" ./main
```
