### ISSUE TITLE
V2ray Android 的 Binary 执行程序无法正确获得设备的时区

### ISSUE THREAD

**Issue by AAPING** [v2fly/v2ray-core#1550]
## 你正在使用哪个版本的 V2Ray？
客户端：V2ray-core Version 4.44.0 Android - https://github.com/v2fly/v2ray-core/releases/download/v4.44.0/v2ray-android-arm64-v8a.zip
服务端：JustMySocks 机场 （事实上这个问题与服务端无关，即使运行客户端的设备断网也可以复现） 

## 你的使用场景是什么？
Youtube + Google etc.

## 你看到的异常现象是什么？
在Android端直接运行 V2ray 的 二进制程序（比如通过ADB命令行或者Termux），程序 log 中显示的时间使用的是格林威治时区，而非系统设置的时区。

## 你期待看到的正常表现是怎样的？
在Android端直接运行 V2ray 的 二进制程序，程序 log 中显示的时间使用的是系统设置的时区。

## 请附上你的配置

**服务端配置：** 
Not applied

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置
硬件： Samsung Tab S6 (骁龙855 CPU) 美版
OS: Android11, 三星原装 OneUI，美版系统 （自带谷歌全家桶，并非后安装，无刷机无Root）
运行 ADB 的 OS： Windows 10 19043.1415
ADB ver: r31.03 (事实上我认为这个问题和ADB无关，因为即使我在Termux里面依然可以复现一摸一样的问题)
```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**
第一次提（potential）bug, 如果还需要别的信息或者格式不正确，请告诉我，我会补充/改正。

二进制文件同dir的展示：

![Capture_ls-la](https://user-images.githubusercontent.com/97717321/149450614-b25f0dcd-775e-49aa-9dfb-07b6feeee346.PNG)

启动V2ray 二进制 （./v2ray 与 ./v2ray run 复现出的结果是一样的，截图是用的 ./v2ray 命令的输出结果）
![image](https://user-images.githubusercontent.com/97717321/149451589-eec5e003-0821-4bf2-874c-87d5cb5b386f.png)
（截图里的的命令和输出：）
gts6lwifi:/data/local/tmp $
gts6lwifi:/data/local/tmp $ ./v2ray
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 android/arm64)
A unified platform for anti-censorship.
2022/01/14 03:51:53 Using default config:  /data/local/tmp/config.json
2022/01/14 03:51:53 [Info] main/jsonem: Reading config: /data/local/tmp/config.json
2022/01/14 03:51:54 [Warning] V2Ray 4.44.0 started

v2ray 输出的时间是 03:51:xx, 但是我系统设置的时区是东八区，对应的时间是 11:51:xx， 我知道这两个时间是等效的，但是但是我希望V2ray使用的是系统的时区而非格林威治时间

显示系统时区(来证明我并没有设置错时区)：
![image](https://user-images.githubusercontent.com/97717321/149451690-f3f17a88-b996-4e25-aa62-5f3eaa616447.png)
（截图里的的命令和输出：）
gts6lwifi:/data/local/tmp $ getprop persist.sys.timezone
Asia/Shanghai

```javascript
```

## 请附上访问日志
断网的情况下也可以复现，应该与访问日志无关。

```javascript
// 在这里附上服务器端日志

```

**Comment by AAPING** [comment]
请稍等再处理，我需要解决一下截图上传失败的问题

**Comment by AAPING** [comment]
作为对比，我下载运行了 x86 版本的 v2ray 的可执行文件，命令行输出的日志的时区就跟我电脑的时区的设置是一致的。（比如，现在北京时间 1pm， 那么 v2ray-x86 的 log info 就能正确输出 1pm 的 timestamp， 不会像 android 的二进制 输出 tmestamp 为 5am 的 log info）

**Comment by dyhkwong** [comment]
golang issue https://github.com/golang/go/issues/20455

**Comment by AAPING** [comment]
> golang issue [golang/go#20455](https://github.com/golang/go/issues/20455)

Thanks! Now I know why..... It still impresses me that this specific Golang "bug" dates back to 2018 .... I'm okay to close this issue but if the development team or anyone else still wants to hold it open for improvement and/or discussion, please feel free to take over.
