### ISSUE TITLE
http伪装，在接受任意请求(?)后会崩溃

### ISSUE THREAD

**Issue by kda2000** [v2fly/v2ray-core#1569]
{
  "inbounds": [
    {
      "port": 80,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "***"          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "response": {
              "version": "1.1",
              "status": "200",
              "reason": "OK",
              "headers": {
                "Content-Type": [
                  "application/octet-stream",
                  "application/x-msdownload",
                  "text/html",
                  "application/x-shockwave-flash"
                ],
                "Transfer-Encoding": [
                  "chunked"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache"
              }
            }
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}

V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/arm64)
A unified platform for anti-censorship.
2022/01/24 12:23:11 Using default config:  /root/vv/config.json
2022/01/24 12:23:11 [Info] main/jsonem: Reading config: /root/vv/config.json
2022/01/24 12:23:11 [Warning] V2Ray 4.44.0 started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x713288]

goroutine 50 [running]:
github.com/v2fly/v2ray-core/v4/transport/internet/headers/http.(*HeaderReader).Read(0x40000962d0, {0xb1a6e0, 0x400000e020})
        github.com/v2fly/v2ray-core/v4/transport/internet/headers/http/http.go:120 +0x818
github.com/v2fly/v2ray-core/v4/transport/internet/headers/http.(*Conn).Read(0x40004d1e80, {0x4000029800, 0x800, 0x800})
        github.com/v2fly/v2ray-core/v4/transport/internet/headers/http/http.go:185 +0x70
github.com/v2fly/v2ray-core/v4/common/buf.(*Buffer).ReadFrom(...)
        github.com/v2fly/v2ray-core/v4/common/buf/buffer.go:192
github.com/v2fly/v2ray-core/v4/common/buf.ReadBuffer({0xfffdb883feb0, 0x40004d1e80})
        github.com/v2fly/v2ray-core/v4/common/buf/reader.go:30 +0xf0
github.com/v2fly/v2ray-core/v4/common/buf.(*SingleReader).ReadMultiBuffer(0x40000962f0)
        github.com/v2fly/v2ray-core/v4/common/buf/reader.go:158 +0x34
github.com/v2fly/v2ray-core/v4/common/buf.(*BufferedReader).Read(0x40004d61b0, {0x4000029000, 0x10, 0x800})
        github.com/v2fly/v2ray-core/v4/common/buf/reader.go:76 +0x78
io.ReadAtLeast({0xb17ec0, 0x40004d61b0}, {0x4000029000, 0x10, 0x800}, 0x10)
        io/io.go:328 +0xa8
io.ReadFull(...)
        io/io.go:347
github.com/v2fly/v2ray-core/v4/common/buf.(*Buffer).ReadFullFrom(0x40000420a0, {0xb17ec0, 0x40004d61b0}, 0x10)
        github.com/v2fly/v2ray-core/v4/common/buf/buffer.go:204 +0x90
github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding.(*ServerSession).DecodeRequestHeader(0x4000330070, {0xb17ec0, 0x40004d61b0})
        github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding/server.go:157 +0x2b4
github.com/v2fly/v2ray-core/v4/proxy/vmess/inbound.(*Handler).Process(0x40004d3270, {0xb2f5c0, 0x40004d6180}, 0x2, {0xfffdb883fe58, 0x40004d1e80}, {0xb2fc50, 0x40004e0370})
        github.com/v2fly/v2ray-core/v4/proxy/vmess/inbound/inbound.go:232 +0x2dc
github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*tcpWorker).callback(0x40001a7ae0, {0xfffdb883fe58, 0x40004d1e80})
        github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/worker.go:100 +0x6e0
created by github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*tcpWorker).Start.func1
        github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/worker.go:116 +0x4c

测试环境：
Oracle Linux 8.5 x64
Oracle Linux 8.5 aarch64

同配置在x64版本中不会崩溃。但是aarch64版使用此配置，在接受任意请求(?)后会崩溃，错误日志见前文。

**Comment by dyhkwong** [comment]
I can reproduce this on an aarch64 Android phone with v4.44.0 (linux/android binary) but cannot reproduce with v5.0.3 (linux/android binary, jsonv4). Try if v5.0.3 works.
