### ISSUE TITLE
为加密dns指定sni

### ISSUE THREAD

**Issue by Fhokud** [v2fly/v2ray-core#1581]
- 目的：解决当配置的所有dns中都为带有域名的加密dns时无法查询dns的问题

- 问题：dnsservers配置为以下模板时查询dns失败（我配置了本地dns）
 
          {
                "address": "quic://dns.com",
                "concurrency": true
            },
            {
                "address": "quic://cn.dns.com",
                "domains": [
                    "full:dns.com",
                    "geosite:cn"
                ],
                "concurrency": true,
                "skipFallback": true
            }
注：dns.com 和 cn.dns.com 没有IP级TLS证书

期望用法:

          {
              "address": "(tls/https/quic/tls+local/http+local/quic+local)://(ip地址):(端口)",
              "sni": "dns.com"
          }

- 还有个想法

指定一个非加密dns专门用来解析加密dns的域名？

比如

          {
              "address": "(tcp/udp/tcp+local/udp+local)://(ip地址):(端口)",
              "onlyEncryptedDNSParsing": true
          }

感谢大佬们的开发，这只是个小小的建议，也许有会更好的解决方案呢。

**Comment by AkinoKaede** [comment]
It's supported. Document: <https://www.v2fly.org/config/dns.html>
