### ISSUE TITLE
rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found

### ISSUE THREAD

**Issue by zhang-ray** [v2fly/v2ray-core#1605]
## 你正在使用哪个版本的 V2Ray？
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)

## 你的使用场景是什么？
翻阅内部防火墙

## 你看到的异常现象是什么？
服务端出现`rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found` , 并且客户端无法连接网络

## 你期待看到的正常表现是怎样的？
不出现错误日志，并且客户端可以正常使用网络

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
        "port": 16823, // 服务器监听端口
        "protocol": "vmess",    // 主传入协议
        "settings": {
          "clients": [
            {
              "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  // 用户 ID，客户端与服务器必须相同
              "alterId": 0
            }
          ]
        }
      }
  ],
  "outbounds": [
     {
      "protocol": "freedom",  // 主传出协议
      "settings": {}
      }
    ],

"dns": {
"servers": [
"114.114.114.114",
"localhost"
]
 }

}
```

**客户端配置：**

```javascript
// 在这里附上客户端配置
{
    "log": {
        "loglevel": "debug",
        "access": "/var/log/v2ray/access.log", // ~Y~X Linux ~Z~D路~D
        "error": "/var/log/v2ray/error.log"
    },
    "inbounds": [
        {
            "tag": "transparent",
            "port": 12345,
            "protocol": "dokodemo-door",
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy", // ~@~O~X~N代~P~F使~T TPROXY ~V~O
                    "mark": 255
                }
            }
        }
    ],
"outbounds": [
        {
            "protocol": "vmess", // 出口协议
            "settings": {
                "vnext": [
                    {
                        "address": "192.168.51.131", // 服务器地址，请修改为你自己的服务器 IP 或域名
                        "port": 16823, // 服务器端口
                        "users": [
                            {
                                "id": "b831381d-6324-4d53-ad4f-8cda48b30811", // 用户 ID，必须与服务器端配置相同
                                "alterId": 0 // 此处的值也应当与服务器相同
                            }
                        ]
                    }
                ]
            }
        }
    ],
    "dns": {
        "servers": [
            {
                "address": "192.168.1.1", //中国大陆域名使用 114 的 DNS (备用)
                "port": 53,
                "domains": [
                    "geosite:cn",
                    "ntp.org", // NTP 服务器
                    "$myserver.address" // 此处改为你 VPS 的域名
                ]
            },
{
                "address": "8.8.8.8", //非中国大陆域名使用 Google 的 DNS
                "port": 53,
                "domains": [
                    "geosite:geolocation-!cn"
                ]
            },
            {
                "address": "1.1.1.1", //非中国大陆域名使用 Cloudflare 的 DNS
                "port": 53,
                "domains": [
                    "geosite:geolocation-!cn"
                ]
            }
        ]
    }
}
```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志
2022/02/14 18:05:53 172.20.122.189:35832 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 [Info] [2337968776] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 172.20.122.189:35832 > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 172.20.122.189:35830 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 [Info] [1121610257] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 172.20.122.189:35830 > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 172.20.122.189:35840 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 [Info] [449892505] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 172.20.122.189:35840 > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 172.20.122.189:35838 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 [Info] [117733608] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 172.20.122.189:35838 > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 172.20.122.189:35846 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2022/02/14 18:05:53 [Info] [4227250692] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 172.20.122.189:35846 > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
^C2022/02/14 18:05:56 [Debug] app/log: Logger closing
```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by zhang-ray** [comment]
这个问题是偶发出现的。 客户端和服务端的 v2ray 重启后，不一定会复现

**Comment by AkinoKaede** [comment]
You don't have to worry about this, it may be the replay attacks from GFW.

**Comment by AkinoKaede** [comment]
> > You don't have to worry about this, it may be the replay attacks from GFW.
> 
> 关键这不涉及到 GFW, VMESS协议只跨越一个局域网

Sorry, I didn't read it carefully.

Generally, this is caused by inaccurate system time.

**Comment by zhang-ray** [comment]
> > > You don't have to worry about this, it may be the replay attacks from GFW.
> > 
> > 
> > 关键这不涉及到 GFW, VMESS协议只跨越一个局域网
> 
> Sorry, I didn't read it carefully.
> 
> Generally, this is caused by inaccurate system time.

我试过了，把client和server的时区和时钟都校准了，还是会出现。

**Comment by AkinoKaede** [comment]
Hmm, by design, this doesn't happen when the ID is correct and the time is accurate.

**Comment by kotori2** [comment]
Can reproduce this issue with NTP on. Also tried to move mu clock 60 seconds forward but it won't help.

**Comment by hujesse83** [comment]
我也遇到了同样的问题, ip id port 全都对应上了

**Comment by ziqizh** [comment]
4.43也遇到了同样的问题。uuid和时间检查了没问题，也能看到connection established，但就是无法连接。

**Comment by huangjiahua** [comment]
4.44遇到这个问题，一直回退到4.39还是有同样问题

**Comment by ivwumupy** [comment]
I have encountered the same problem too. There is something wrong with the 16 byte request header. It should be a hash value, but it is actually `GET /my-path` on my server.

**Comment by bruce2233** [comment]
同样的问题+1, 客户端没法翻墙

**Comment by xinxin8816** [comment]
服务端客户端协议不匹配也会出现这个报错

**Comment by zhweiGuo** [comment]
There are errors in `access.log`:

> rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false. You will not be able to enable legacy header workaround in the future.

When entering `v2ray log`:

> rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found

And I can't browse google. 

This problem was solved when I switched the protocol from **QUIC** to **TCP** both in server and client config.

**Comment by Feng1440** [comment]
如果您使用的linux发行版为debian

不妨执行如下命令:

apt-get install -y ntp && /lib/systemd/systemd-sysv-install enable ntp

当我执行这串命令，再次重启程序，服务端可以进行连接，希望能够帮到你！

**Comment by ynhj123** [comment]
遇到同样的问题，分析日志感觉大部分ip是正常的，只有个别比如112.79开头的ip就报错，比如：112.79.141.168:39219 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found

**Comment by tacy** [comment]
关闭VMessAEAD。。。v2ray.vmess.aead.forced = false

**Comment by GOUKOU007** [comment]
遇到同样的问题，发现是服务器时钟快了2分钟。。。

**Comment by vinqin** [comment]
As same as me. I fix it after adjust my client time.

**Comment by adwinwhite** [comment]
可能是客户端与服务器 alterId 不匹配， 不知道服务器设置的话把客户端的设为0就好了

**Comment by ArtoriaZhang** [comment]
I faced this issue too.
Windows client works fine, but android client shows 'pipe closed', and server logs shows 'vmess user not found'.

Fix: Just syn date. (e.g: $/timedatectl set-ntp true)

**Comment by HelloLingC** [comment]
My server time already synced
this error happened when using ws protocol with dynamic ports
but once changed the protocol type into tcp, this error was gone

**Comment by adminKKi** [comment]
> `access.log`中存在错误：
> 
> > 拒绝的公共/排水：公共/排水：无法排水连接> EOF > proxy/vmess/encoding：无效用户：强制执行VMessAEAD并接收非VMessAEAD连接。您仍然可以使用环境变量v2ray.vmess.aead.forced = false禁用此安全功能。未来您将无法启用遗留标题变通办法。
> 
> 输入`v2ray log`时：
> 
> > 拒绝的普通/排水：普通/排水：无法排水连接> EOF>代理/vmess/编码：无效用户>代理/vmess：未找到
> 
> 而且我无法浏览谷歌。
> 
> 当我在服务器和客户端配置中将协议从**QUIC**切换到**TCP**时，这个问题得到了解决。



> There are errors in `access.log`:
> 
> > rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false. You will not be able to enable legacy header workaround in the future.
> 
> When entering `v2ray log`:
> 
> > rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
> 
> And I can't browse google.
> 
> This problem was solved when I switched the protocol from **QUIC** to **TCP** both in server and client config.

更换协议为tcp也解决了这个问题 感谢！

**Comment by marioplus** [comment]
客户端时间不准会出现该问题
