### ISSUE TITLE
使用Google 搜索时底部位置信息显示并非v2ray服务器所在地

### ISSUE THREAD

**Issue by zozero** [v2fly/v2ray-core#1622]
以前使用v2ray时定位都是在v2ray服务器的地址，现在所有地址都指向的真实地址

请问各位大佬，这是我服务器配置的问题，还是Google的问题，又或者v2ray程序修改的问题？

**Comment by zozero** [comment]
还有一点就是因为这个原因我的Google play无法正常下载其他地区的游戏。。。。。。

**Comment by AkinoKaede** [comment]
Google 的 IP 地址库不准确

**Comment by Cwek** [comment]
除了IP库不准确，也可能是你搜索的内容所属地和浏览器其他容易泄露位置的机制有关
