### ISSUE TITLE
请问如何装json格式的配置写成 []*InboundHandlerConfig 形式？

### ISSUE THREAD

**Issue by gitv2ray** [v2fly/v2ray-core#1644]
如图
![20220304084938](https://user-images.githubusercontent.com/71534870/156679176-0e2d5bce-1d2a-4601-84cf-5ca260bc1549.png)

**Comment by WordsWorthLess** [comment]
这个是配置文件吗？看上去是脚本里面的一个函数，从用户输入或者文件读取参数，然后生成配置文件，再测试配置文件是否正确或者服务器是否可用之类的

**Comment by AkinoKaede** [comment]
Sorry, I can't understand your question. `github.com/v2fly/v2ray-core/v5/infra/conf/v4` is the package used to parse the `JSONv4` configuration.

**Comment by gitv2ray** [comment]
@AkinoKaede thank you reply
my question please see image
![20220305092114](https://user-images.githubusercontent.com/71534870/156862157-d75a293b-2d56-41eb-83b8-3a2da07c5ec5.png)

**Comment by AkinoKaede** [comment]
> @AkinoKaede thank you reply my question please see image ![20220305092114](https://user-images.githubusercontent.com/71534870/156862157-d75a293b-2d56-41eb-83b8-3a2da07c5ec5.png)


```go
proxyman.ReceiverConfig{
    Listen: net.NewIPOrDomain("/dev/shm/domainsocket"),
}
```

https://github.com/v2fly/v2ray-core/blob/3ef7feaeaf737d05c5a624c580633b7ce0f0f1be/infra/conf/v4/v2ray.go#L122-L140

**Comment by gitv2ray** [comment]
@AkinoKaede thank you!
write this can run.

` {
				ReceiverSettings: serial.ToTypedMessage(&proxyman.ReceiverConfig{
					Listen: net.NewIPOrDomain(net.ParseAddress("/etc/caddy/vmess")),
					StreamSettings: &internet.StreamConfig{
						ProtocolName: "websocket",
						TransportSettings: []*internet.TransportConfig{
							{
								ProtocolName: "websocket",
								Settings: serial.ToTypedMessage(&websocket.Config{
									Path: "/ccc",
								}),
							},
						},
					},
				}),
				ProxySettings: serial.ToTypedMessage(&inbound.Config{
					User: []*protocol.User{
						{
							Level: 0,
							Email: "",
							Account: serial.ToTypedMessage(&vmess.Account{
								Id:      "d45a79b4-6094-41cf-923d-42731e7ecf3e",
								AlterId: 0,
							}),
						},
					},
					SecureEncryptionOnly: false,
				}),
			},`
