### ISSUE TITLE
v5.0.3 配置 DNS 后 panic

### ISSUE THREAD

**Issue by kirakon** [v2fly/v2ray-core#1662]
## 你正在使用哪个版本的 V2Ray？
v5.0.3, linux arm64

## 你的使用场景是什么？
本地测试

## 你看到的异常现象是什么？
添加了 DNS 配置项时 V2Ray 无法启动，删除 DNS 配置后正常

## 你期待看到的正常表现是怎样的？
正常使用 DNS 功能

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置
{
  "inbounds": [
    {
      "tag": "socks_in",
      "port": 10086,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "settings": null,
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy_tcp",
      "protocol": "vmess",
      "settings": {
        "address": "127.0.0.1",
        "port": 10000,
        "uuid": "4d8ba710-e4f2-3520-8eaf-4420ed86aca7"
      }
    }
  ],
  "dns": {
    "nameServer": [
      {
        "address": {
          "network": "UDP",
          "address": "1.1.1.1",
          "port": 53
        },
        "prioritizedDomain": [
          {
            "type": "Subdomain",
            "domain": "google.com"
          }
        ]
      }
    ]
  }
}

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

## 如果 V2Ray 服务运行异常，请附上 journal 日志
V2Ray 5.0.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.6 linux/arm64)
A unified platform for anti-censorship.
panic: V is not in context.

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v5.MustFromContext({0xcc2aa0, 0x400010ae10})
        github.com/v2fly/v2ray-core/v5/context.go:24 +0x94
github.com/v2fly/v2ray-core/v5.RequireFeatures({0xcc2aa0, 0x400010ae10}, {0x9be0a0, 0x40004f3f40})
        github.com/v2fly/v2ray-core/v5/v2ray.go:152 +0x30
github.com/v2fly/v2ray-core/v5/app/dns.NewClient({0xcc2aa0, 0x400010ae10}, 0x400012f360, {0x0, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, 0x4000197428, ...)
        github.com/v2fly/v2ray-core/v5/app/dns/nameserver.go:74 +0x188
github.com/v2fly/v2ray-core/v5/app/dns.New({0xcc2aa0, 0x400010ae10}, 0x400057c370)
        github.com/v2fly/v2ray-core/v5/app/dns/dns.go:129 +0x780
github.com/v2fly/v2ray-core/v5/app/dns.init.1.func1({0xcc2aa0, 0x400010ae10}, {0xaf71e0, 0x400057c370})
        github.com/v2fly/v2ray-core/v5/app/dns/dns.go:315 +0x4c
github.com/v2fly/v2ray-core/v5/common.CreateObject({0xcc2aa0, 0x400010ae10}, {0xaf71e0, 0x400057c370})
        github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1ec
github.com/v2fly/v2ray-core/v5/app/dns.init.1.func2({0xcc2aa0, 0x400010ade0}, {0xaeebe0, 0x400057ae10})
        github.com/v2fly/v2ray-core/v5/app/dns/dns.go:380 +0x6e0
github.com/v2fly/v2ray-core/v5/common.CreateObject({0xcc2aa0, 0x400010ade0}, {0xaeebe0, 0x400057ae10})
        github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1ec
github.com/v2fly/v2ray-core/v5.CreateObject(0x40004f3e50, {0xaeebe0, 0x400057ae10})
        github.com/v2fly/v2ray-core/v5/functions.go:19 +0x6c
github.com/v2fly/v2ray-core/v5.initInstanceWithConfig(0x4000289290, 0x40004f3e50)
        github.com/v2fly/v2ray-core/v5/v2ray.go:194 +0x14c
github.com/v2fly/v2ray-core/v5.New(0x4000289290)
        github.com/v2fly/v2ray-core/v5/v2ray.go:162 +0x88
github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
        github.com/v2fly/v2ray-core/v5/main/commands/run.go:205 +0x324
github.com/v2fly/v2ray-core/v5/main/commands.executeRun(0x13bc6c0, {0x4000182140, 0x4, 0x4})
        github.com/v2fly/v2ray-core/v5/main/commands/run.go:82 +0xbc
github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
        github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x6d4
main.main()
        github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x300

**Comment by WordsWorthLess** [comment]
prioritizedDomain的Type开头是小写的，subdomain, full, regex, keyword,不知道有没有影响
