### ISSUE TITLE
請問v5版的配置文件， PriorityDomain還支持geosite域名集嗎？

### ISSUE THREAD

**Issue by WordsWorthLess** [v2fly/v2ray-core#1664]
### Discussed in https://github.com/v2fly/v2ray-core/discussions/1653

<div type='discussions-op-text'>

<sup>Originally posted by **WordsWorthLess** March  5, 2022</sup>
看配置文檔介紹
https://www.v2fly.org/v5/config/dns.html#prioritydomainobject
PriorityDomain貌似只有4種匹配方式
完整域名匹配，關鍵字匹配，(子)域名匹配，正則表達式匹配，
而且示例配置也沒有提及geosite域名集的相關配置（geosite.dat路徑，域名集填寫方法等）
是網站的説明漏了提及還是v2ray v5 dns不再支持geosite合集了?如果是後者的話就太令人費解了
而且我覺得原來V4的DNS 服務器列表配置方式就很清爽直觀，在V4的基礎上添加inverseMatch就很好了，V5搞得太繁瑣太臃腫了。
</div>

**Comment by sgon00** [comment]
I am having the same issue. Please re-open this bug. Thanks a lot.
