### ISSUE TITLE
V2ray运行正常，但无法进行代理

### ISSUE THREAD

**Issue by huangwb8** [v2fly/v2ray-core#1688]
## 你正在使用哪个版本的 V2Ray？
客户端：4.22.1
服务端：机场

## 你的使用场景是什么？
通过shell客户端ping通google；通过127.0.0.1:10808为emby等软件代理。

## 你看到的异常现象是什么？

访问超时：

```
$ ping www.google.com
PING www.google.com (199.59.149.232) 56(84) bytes of data.
--- www.google.com ping statistics ---
185 packets transmitted, 0 received, 100% packet loss, time 188311ms
```

## 你期待看到的正常表现是怎样的？

可以ping通google，实现外网

## 请附上你的配置

**服务端配置：**

来源于机场

**客户端配置：**

此config.json文件在windows10的电脑上的v2rayN客户端下copy过来的，在win10中是可以成功运行的。
已对关键字段做掩饰。
https://github.com/huangwb8/test_file/blob/master/config_demo.json

BT面板也已经开通10808端口，显示状态为正常。

查看与v2ray有关的端口：

```
netstat -anp|grep v2ray
tcp        0      0 127.0.0.1:10808         0.0.0.0:*               LISTEN      22282/v2ray         
udp       0      0 127.0.0.1:10808         0.0.0.0:*                           22282/v2ray         
unix  3   [ ]     STREAM     CONNECTED     863284   22282/v2ray
```

## 请附上出错时软件输出的错误日志

显示为active状态，无明显报错：

```
systemctl status v2ray                                                                          :( 1 22-03-22 - 21:00:10
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-03-22 20:54:49 CST; 6min ago
 Main PID: 22282 (v2ray)
    Tasks: 20 (limit: 7372)
   CGroup: /system.slice/v2ray.service
           └─22282 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Mar 22 20:54:49 lucky systemd[1]: Started V2Ray Service.
Mar 22 20:54:49 lucky v2ray[22282]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64
Mar 22 20:54:49 lucky v2ray[22282]: A unified platform for anti-censorship.
Mar 22 20:54:49 lucky v2ray[22282]: 2022/03/22 20:54:49 [Warning] v2ray.com/core: V2Ray 4.22.1 started
```

## 请附上访问日志

有`/var/log/v2ray`文件夹，但内部无任何文件。

## 其它相关的配置文件（如 Nginx）和相关日志

暂无。

## 如果 V2Ray 服务运行异常，请附上 journal 日志

journalctl -u v2ray
-- Logs begin at Mon 2022-03-07 16:27:02 CST, end at Tue 2022-03-22 21:02:05 CST. --
Mar 21 11:26:14 lucky systemd[1]: Started V2Ray Service.
Mar 21 11:26:15 lucky v2ray[2405]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
Mar 21 11:26:15 lucky v2ray[2405]: A unified platform for anti-censorship.
Mar 21 11:26:15 lucky v2ray[2405]: 2022/03/21 11:26:15 [Warning] v2ray.com/core: V2Ray 4.22.1 started
Mar 22 20:11:43 lucky v2ray[2405]: 2022/03/22 20:11:43 tcp:127.0.0.1:41052 rejected  v2ray.com/core/proxy/socks: insufficie
Mar 22 20:11:52 lucky v2ray[2405]: 2022/03/22 20:11:52 tcp:127.0.0.1:41074 rejected  v2ray.com/core/proxy/socks: insufficie
Mar 22 20:21:49 lucky systemd[1]: Stopping V2Ray Service...
Mar 22 20:21:49 lucky systemd[1]: Stopped V2Ray Service.
Mar 22 20:45:17 lucky systemd[1]: Started V2Ray Service.
Mar 22 20:45:17 lucky v2ray[10529]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64
Mar 22 20:45:17 lucky v2ray[10529]: A unified platform for anti-censorship.
Mar 22 20:45:17 lucky v2ray[10529]: 2022/03/22 20:45:17 [Warning] v2ray.com/core: V2Ray 4.22.1 started
Mar 22 20:54:37 lucky systemd[1]: Stopping V2Ray Service...
Mar 22 20:54:37 lucky systemd[1]: Stopped V2Ray Service.
Mar 22 20:54:49 lucky systemd[1]: Started V2Ray Service.
Mar 22 20:54:49 lucky v2ray[22282]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64
Mar 22 20:54:49 lucky v2ray[22282]: A unified platform for anti-censorship.
Mar 22 20:54:49 lucky v2ray[22282]: 2022/03/22 20:54:49 [Warning] v2ray.com/core: V2Ray 4.22.1 started

**Comment by huangwb8** [comment]
其实我很久以前就在Ubuntu上面安装v2ray，但一直未能成功运行。

**Comment by AkinoKaede** [comment]
- You can not redirect any ICMP requests to V2Ray, they can not be sent by V2Ray.
- You shoud change the proxy settings of desktop environments and applications.
