### ISSUE TITLE
[Warning] failed to handler mux client connection > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

### ISSUE THREAD

**Issue by BBBob** [v2fly/v2ray-core#1696]
## What version of V2Ray are you using?
经测试服务端v2ray版本使用 4.22.0到4.34.0均能正常连接，4.35.1到4.44.0无法正常使用，报错：
···
[Warning] failed to handler mux client connection > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
···
客户端版本为4.43.0

## What's your scenario of using V2Ray?
ws+tls+wmess

## What problems have you encountered?

···
[Warning] failed to handler mux client connection > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
···

## Please attach your configuration here

**Server configuration:**

```javascript
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
    "port": 11234,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xxxx1",
          "level": 1,
          "alterId": 64,
	  "email": "xxx1@xxxx.com"
        },
        {
          "id": "xxxx2",
          "level": 1,
          "alterId": 64,
	  "email": "xxx2@xxx.com"
        }

      ]
    },
     "streamSettings": {
      "network": "ws",
      "wsSettings": {
     	 "path": "/xxxx"
    	}
     }
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "outboundTag": "block",
        "protocol": [
          "bittorrent"
        ]
      }
    ]
  }
}
```

**Client configuration:**

```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inboundDetour": [
    {
      "protocol": "dokodemo-door",
      "port": 1081,
      "domainOverride": ["tls","http"],
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "tag":"forwardingport"
    }
  ],
  "inbounds": [
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxx.xxx",
            "port": 443,
            "users": [
              {
                "id": "xxxx1",
                "alterId": 64,
                "email": "xxxx1@xxxx.com",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "xxxx",
          "headers": null
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
        {
            "domain": [
              "jd.com",
              "youku.com",
              "baidu.com",
        "domain:education.github.com"
            ],
            "type": "field",
            "outboundTag": "direct"
        },
        {
            "ip": [
              "geoip:private"
            ],
            "outboundTag": "direct",
            "type": "field"
        },
        {
              "ip": [
                "geoip:cn"
              ],
              "outboundTag": "direct",
              "type": "field"
        },
        {
              "domain": [
                "geosite:cn"
              ],
              "outboundTag": "direct",
              "type": "field"
        },
        {
            "type": "field",
            "inboundTag": ["forwardingport"],
            "outboundTag": "proxy"
        }

    ]
  }
}
```

**Comment by IIIlllIIllIIIll** [comment]
https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E6%B7%98%E6%B1%B0%E6%9C%BA%E5%88%B6

**Comment by 8x8-64** [comment]
专门登录来批评作者自以为是的修改。禁用某个功能应该是用版本来区分，不应该程序内部按时间自行决定功能可不可用。服务器一直运行没问题，昨天维护需要重启一次，v2就连不上了，查了几个小时才了解到有这个坑人的修改，想关闭还要修改系统变量，不能在配置文件里设置。一个程序要么安装时能用，要么不能用，都是脚本维护的，时间久了谁还记得。出错提示没任何帮助，完全不知道真正原因。作者加了启动时判断在20220101之后就改协议的功能，怎么就不加判断在20221231之前还用了旧协议的出错提示，友好的提示升级，连浏览器控制台里都懂得提示旧协议不兼容。这个功能是个大雷，程序在启动时按时间判断的，如果服务器从2021年开始一直稳定运行，经过很长时间后重启出了问题，网上可能根本搜不到这个原因。

建议服务器和程序都用低版本，新版本越优化越费电，作者理论说的很美，就是不用手机开代理实测耗电。如果不小心用了高版本，把客户端AlterID改成0

**Comment by os9sur** [comment]
同样的问题,请问你最后是怎么解决的? 能否把答案贴过来看一下...
我目前由于 v2ray 不能工作,导致  https://www.v2fly.org 打不开

**Comment by Kannnnng** [comment]
我也是真的服了，为什么在新版本没有任何一点提示信息？昨晚上升级了一下内核，这就发现连不上去了，怎么折腾都没用，控制台或者日志里面没有任何一点提示信息，反复核对客户端和服务器端的时间同步问题，白白浪费了一个晚上加一个上午的时间，就只是因为这一个问题，实在是……
作者的本意我觉得是好的，毕竟现在 MD5 确实已经不安全了，我也支持后续的版本逐步放弃对 MD5 的支持。
但是在版本切换以后没有任何一点提示信息，这就实在是有点太不应该了，不知道的人可能就会像我一样排查个一天两天但就是死活排查不出来问题出在哪里，这么做对用户实在是太不友好了

**Comment by digglife** [comment]
「自以为是」

「真是服了」

「白白浪费」

「太不应该」。

恕我直言，作为 V2Ray-Core 的用户，包括我在内，是没有资格针对开发者说这些话的。

更新版本之后问题出现，回退版本之后问题消失，最自然的反应难道不是花几分钟去看版本更新日志？

这个变动，从 [4.35.1](https://github.com/v2fly/v2ray-core/releases/tag/v4.35.1) 加上开始，一直到 [4.41.1](https://github.com/v2fly/v2ray-core/releases/tag/4.41.1)，**一共 21 个版本**，每个版本的 Changelog 里都单独提过这个更改，直到 2022年 1 月 1 日才正式生效，近 **9 个月**的缓冲，我看不到开发者在这个问题上有什么「自以为是」「太不应该」，反而我觉得有些过分谨慎，「白白浪费」自己的时间修复问题、更新提示，「真是服了」。

**Comment by Kannnnng** [comment]
> 「自以为是」
> 
> 「真是服了」
> 
> 「白白浪费」
> 
> 「太不应该」。
> 
> 恕我直言，作为 V2Ray-Core 的用户，包括我在内，是没有资格针对开发者说这些话的。
> 
> 更新版本之后问题出现，回退版本之后问题消失，最自然的反应难道不是花几分钟去看版本更新日志？
> 
> 这个变动，从 [4.35.1](https://github.com/v2fly/v2ray-core/releases/tag/v4.35.1) 加上开始，一直到 [4.41.1](https://github.com/v2fly/v2ray-core/releases/tag/4.41.1)，**一共 21 个版本**，每个版本的 Changelog 里都单独提过这个更改，直到 2022年 1 月 1 日才正式生效，近 **9 个月**的缓冲，我看不到开发者在这个问题上有什么「自以为是」「太不应该」，反而我觉得有些过分谨慎，「白白浪费」自己的时间修复问题、更新提示，「真是服了」。

前面是我情绪有些激动了，有了一些言辞有些激烈的词语。
本身我对于开发者做出这样一款产品确实非常感激，因为我自己通过使用v2ray也受益颇多，因为遇到一个问题就这样说话确实不对，抱歉了。
另一方面，也是单纯提一个建议，在越靠近用户的地方提示用户，用户接受信息的机会也越大，手册里面固然要写清楚，只是手册本身内容庞杂，对这个错误没有头绪的人很难从中快速找到跟自己现在遇到的问题相关的有用的信息，甚至像我一样根本不知道问题出在哪里，看控制台没有提示任何信息，日志里面也没有，这就导致解决问题都有些无从下手，如果能够在用户都能快速看到反馈的控制台或者运行日志里面写清楚，那问题就迎刃而解了。
我再次对我说过的话说声抱歉。
