### ISSUE TITLE
v2ray-core内核支持ios吗

### ISSUE THREAD

**Issue by dxyadc** [v2fly/v2ray-core#1702]
请问开发ios 代理工具，可以用v2ray-core内核吗？

**Comment by KouYiGuo** [comment]
you could use [gomobile](https://github.com/golang/mobile) to compile v2ray-core to a xcframework

**Comment by AkinoKaede** [comment]
As @KouYiGuo said, you can use gomobile to compile V2Ray for iOS. However, V2Ray may exceed iOS RAM limit.

**Comment by ghostwolf90** [comment]
打包 Xray-core 指令
把專案下載下來，在專案目錄下執行終端機，接下來使用以下方法

gomobile init
go mod tidy -v
gomobile bind -v -target=ios -o v2Ray.xcframework -ldflags='-s -w' ./

**Comment by zhangmxxx** [comment]
(按照步骤执行失败后的疑问:)Xray-core指令构成了一个完整的程序(以main.go作为入口). 如果将Xray-core编译为xcframework的话, 我并不能够调用main(), 也就不能在swift项目中使用Xray-core的功能. 

我是否需要对项目的结构进行调整, 将原本在main()中定义的响应过程, 重写为某个module中的一系列methods?

按照上述步骤执行后, 得到的结果是: 
```bash
no exported names in the package "."
```

**Comment by zhangmxxx** [comment]
我在照做的过程中遇到的问题和初步的'解决'方法:
1. `no exported names in the package "."`(项目目录下不存在外界可引用的接口): 在项目目录下新增了`entry.go`, 其中定义了`func RunMain()`直接调用原本的`main()`函数.
2. `import is a program, not an importable package.`(package main的名称导致被判定为program?): 将main更名为entry.

随后正常编译xcframework.

由于是初次接触golang, 对报错的理解肯定会有不当之处, 正确性无法保证(
