### ISSUE TITLE
[Feature request] Add support for shadowsocks-2022 ciphers

### ISSUE THREAD

**Issue by Shikopat** [v2fly/v2ray-core#1731]
Please Add support for shadowsocks-2022 ciphers:

2022-BLAKE3-AES-128-GCM
2022-BLAKE3-AES-256-GCM
2022-BLAKE3-CHACHA20-IETF-POLY1305

Regards

**Comment by database64128** [comment]
The method names should be written in lowercase letters. There's no "ietf" between ChaCha20 and Poly1305.
