### ISSUE TITLE
VLESS的inbound可能存在内存泄漏

### ISSUE THREAD

**Issue by maskedeken** [v2fly/v2ray-core#176]
在Process方法中用到的Buffer都没有考虑Release，这样不知道会不会有问题

**Comment by rprx** [comment]
“都没有考虑”这个说法是不对的（实际上考虑过），当时写的时候不确定会不会被 GC，且两个都是小 buffer，所以想试验一下

**Comment by rprx** [comment]
（不过无论大小，始终会先申请 2K 的内存

**Comment by badO1a5A90** [comment]
> “都没有考虑”这个说法是不对的（实际上考虑过），当时写的时候不确定会不会被 GC，且两个都是小 buffer，所以想试验一下

使用pprof简单测试观察，应无内存泄漏问题

测试方式如下，增加代码开启v2ray的pprof编译进行测试。
启动v2ray，正常使用一会后静置5min开始测试。

抓取goroutine和heap数据的时间点
1. 初始状态--->抓取样本base
2. 随意使用v2ray浏览网页，播放视频，DNS查询等正常操作--->抓取样本testing
3. 停止使用，在1min，5min，10min（不是特别精确）后--->抓取样本

### goroutine
此处数据直接看 http://localhost:6060/debug/pprof/goroutine?debug=1

base:         goroutine profile: total 65
testing:      goroutine profile: total 297
after 1min:   goroutine profile: total 67
after 5min:   goroutine profile: total 65
after 10min:  goroutine profile: total 65

- 可以确定无goroutine泄漏问题

## heap
各时间点抓取heap数据
```
go tool pprof http://localhost:6060/debug/pprof/heap
```

以base样本为基准进行对比。
```
go tool pprof -base base样本 对比样本
```

testing:      Showing nodes accounting for 5940.84kB, 100% of 5940.84kB total
after 1min:   Showing nodes accounting for 3882.27kB, 100% of 3882.27kB total
after 5min:   Showing nodes accounting for 1323.97kB, 100% of 1323.97kB total
after 10min:  与base一致

- 可基本推断无其他问题导致的内存泄漏问题

## 补充
在testing的样本的对比中（即使用v2ray过程中)可以看到vless的使用内存增长
```
0     0%   100%   513.31kB  8.64%  v2ray.com/core/common/buf.(*Buffer).ReadFullFrom
         0     0%   100%      513kB  8.64%  v2ray.com/core/common/buf.(*SingleReader).ReadMultiBuffer
         0     0%   100%      513kB  8.64%  v2ray.com/core/common/buf.Copy
         0     0%   100%      513kB  8.64%  v2ray.com/core/common/buf.New (inline)
         0     0%   100%      513kB  8.64%  v2ray.com/core/common/buf.ReadBuffer
         0     0%   100%      513kB  8.64%  v2ray.com/core/common/buf.copyInternal
         0     0%   100%  1026.31kB 17.28%  v2ray.com/core/common/task.OnSuccess.func1
         0     0%   100%  1026.31kB 17.28%  v2ray.com/core/common/task.Run.func1
         0     0%   100%   513.31kB  8.64%  v2ray.com/core/proxy/vless/encoding.DecodeResponseHeader
         0     0%   100%  1026.31kB 17.28%  v2ray.com/core/proxy/vless/outbound.(*Handler).Process.func3
```

在after 1min中的样本对比base已无此增长，此时应该已正常释放

**Comment by rprx** [comment]
研究了一下，即使没有内存泄露，release 应该也有助于提升效率，加了 defer：https://github.com/v2fly/v2ray-core/commit/8c2e8e9db9d9461f5a1ef86d5d3db9b80eda6c3c
