### ISSUE TITLE
x509: certificate has expired or is not yet valid 同样一份配置文件，有的机器可以有的不行

### ISSUE THREAD

**Issue by Vargnatt** [v2fly/v2ray-core#1767]
我自己购买域名配置基于h2+nginx配置了，在windows电脑上稳定使用3年。
目前将客户端配置复制到mac上以后，使用V2RayU（core版本3.2）报错，具体为：
`2022/05/03 18:35:36 [Info] [4057736577] proxy/socks: TCP Connect request to tcp:www.google.com:443
2022/05/03 18:35:36 [Info] [4057736577] app/dispatcher: default route for tcp:www.google.com:443
2022/05/03 18:35:36 [Info] [4057736577] common/mux: dispatching request to tcp:www.google.com:443
2022/05/03 18:35:36 tcp:127.0.0.1:50596 accepted tcp:www.google.com:443 [proxy]
2022/05/03 18:35:37 [Error] transport/internet/http: failed to dial to myserver.online:443 > x509: certificate has expired or is not yet valid: current time 2022-05-03T18:35:37+08:00 is after 2020-12-27T03:40:14Z
2022/05/03 18:35:37 [Error] transport/internet/http: failed to dial to myserver.online:443 > x509: certificate has expired or is not yet valid: current time 2022-05-03T18:35:37+08:00 is after 2020-12-27T03:40:14Z
2022/05/03 18:35:38 [Error] transport/internet/http: failed to dial to myserver.online:443 > x509: certificate has expired or is not yet valid: current time 2022-05-03T18:35:38+08:00 is after 2020-12-27T03:40:14Z
2022/05/03 18:35:39 [Warning] failed to handler mux client connection > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/http: failed to dial to tcp:myserveronline:443 > Put "https://myserver.online:443/ray": x509: certificate has expired or is not yet valid: current time 2022-05-03T18:35:36+08:00 is after 2020-12-27T03:40:14Z transport/internet/http: failed to dial to tcp:myserver.online:443 > Put "https://myserver.online:443/ray": x509: certificate has expired or is not yet valid: current time 2022-05-03T18:35:37+08:00 is after 2020-12-27T03:40:14Z transport/internet/http: failed to dial to tcp:myserver.online:443 > Put "https://myserver.online:443/ray": x509: certificate has expired or is not yet valid: current time 2022-05-03T18:35:38+08:00 is after 2020-12-27T03:40:14Z] > common/retry: all retry attempts failed
2022/05/03 18:35:39 [Info] common/mux: failed to read metadata > io: read/write on closed pipe
2022/05/03 18:35:40 [Info] [2216922927] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
`
我的服务器端配置文件为：

`{
    "port": 443,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
           "id": "xxxxxxxx",
           "alterId": 64
         }
      ]
    },
    "streamSettings": {
      "network": "h2",
      "httpSettings": {
        "path": "/ray"
      },
      "security": "tls",
      "tlsSettings": {
        "certificates": [
          {
            "certificateFile": "/etc/v2ray/v2ray.crt",
            "keyFile": "/etc/v2ray/v2ray.key"
          }
        ]
      }
    }
  }`

我的mac客户端的配置文件为：

`outbounds": [
    {
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "httpSettings": {
          "path": "/ray",
          "host": [
            ""
          ]
        },
        "network": "h2"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "myserver.online",
            "users": [
              {
                "id": "xxxxxxxx",
                "alterId": 64,
                "level": 0,
                "security": "auto"
              }
            ],
            "port": 443
          }
        ]
      }
    },`

**Comment by kingwilliam** [comment]
是自签证书吗?

**Comment by Vargnatt** [comment]
是的

kingwilliam ***@***.***> 于2022年5月5日周四 07:15写道：

**Comment by kingwilliam** [comment]
```
{
  "outbounds": [
    {
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "httpSettings": {
          "path": "/ray",
          "host": [
            ""
          ]
        },
        "network": "h2"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "myserver.online",
            "users": [
              {
                "id": "xxxxxxxx",
                "alterId": 64,
                "level": 0,
                "security": "auto"
              }
            ],
            "port": 443
          }
        ]
      }
    }
  ]
}
```

1. 試試: 在 "httpSettings" 的 "host" 加入您的fqdn 如:"host": ["myserver.online"]
2. 建議1: h2本身已包含mux功能, 所以 "mux"可以刪除
3. 建議2: outbounds已有TLS, 為何不轉用vless
