### ISSUE TITLE
unknown config id: vliteu

### ISSUE THREAD

**Issue by arinc9** [v2fly/v2ray-core#1775]
## What version of V2Ray are you using?

5.0.6

## What problems have you encountered?
v2ray exits with error when trying to use the vlite protocol.

## Please attach your configuration here

**Server configuration:**

```json
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 19232,
      "protocol": "vliteu",
      "settings": {
        "password": "pw"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}
```

## Please attach error logs here

**Server error log:**

```
$ v2ray run -c test.json
V2Ray 5.0.6 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.1 linux/amd64)
A unified platform for anti-censorship.
Failed to start: main/commands: failed to load config: [test.json] > infra/conf/v4: failed to load inbound detour config. > infra/conf/cfgcommon/loader: unknown config id: vliteu
```

## If V2Ray cannot start up, please attach output from `--test` command
```
$ v2ray test -c test.json
V2Ray 5.0.6 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.1 linux/amd64)
A unified platform for anti-censorship.
Test failed: main/commands: failed to load config: [test.json] > infra/conf/v4: failed to load inbound detour config. > infra/conf/cfgcommon/loader: unknown config id: vliteu
```

**Comment by arinc9** [comment]
@xiaokangwang the v2ray binary is taken from the releases section for linux amd64.

**Comment by AkinoKaede** [comment]
Set `format` argument to `jsonv5`.

```bash
v2ray run --config /path/to/config --format jsonv5
```

**Comment by arinc9** [comment]
@AkinoKaede that fixed it, thanks. Shouldn't systemd service for v5 releases execute v2ray with this option by default?

**Comment by arinc9** [comment]
Closing the issue as it's resolved.

**Comment by freebat** [comment]
how o fix

**Comment by freebat** [comment]
> Closing the issue as it's resolved.

how to fix

**Comment by freebat** [comment]
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json  --format jsonv5
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target
it's correct

**Comment by freebat** [comment]
Test failed: main/commands: failed to load config: [test.json] > infra/conf/v4: failed to load inbound detour config. > infra/conf/cfgcommon/loader: unknown config id: vliteu  not fixed
