### ISSUE TITLE
WS+TLS+CloudFlareCDN 从墙外能正常翻，但从昨天起从墙内突然只有极少数时候可以正常翻，从墙内通过CDN能稳定裸连VPS上的网站

### ISSUE THREAD

**Issue by slusludy** [v2fly/v2ray-core#1785]
## 你正在使用哪个版本的 V2Ray？

4.44.0, Go1.17.3, Linux AMD64

## 你的使用场景是什么？

前天还用得非常好，即使在墙内晚上，在 [speedtest.net](https://www.speedtest.net) 选用墙外 Linux VPS 所在城市的测速服务器，也能测得超过 6 MiB/s 的下载速度和大约 250 ms 的延迟。

- 墙外 CentOS 7 VPS 使用 [V2Ray 4.44.0, Go 1.17.3, AMD64](https://github.com/v2fly/v2ray-core/releases/tag/v4.44.0) 作为服务器
- 墙内 Windows 使用 [Clash for Windows 0.19.7 AMD64](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.19.17) 作为客户端，在本地充当本地浏览器的 HTTP 代理服务器
- 墙内 Android 使用 [Clash for Android 2.5.8 ARM64v8A Premium](https://github.com/Kr328/ClashForAndroid/releases/tag/v2.5.8) 作为客户端，开启 VPN 供 Android 上网
- 墙内设备通过 CloudFlare CDN 下载速度最快（使用 [CloudFlare 的测速链接](https://speed.cloudflare.com/__down?bytes=104857600) 测得的下载速度超过 7 MiB/s ）的几个节点连接墙外 Linux VPS，墙外 CentOS 7 VPS 使用官方软件仓库里的 Nginx 1.20.2 作为 Web 服务器
- 自成功部署好以后从未更换过墙内外设备上的任何软件的版本
- 自成功部署好以后至出现故障前从未更改过墙外 VPS 上的配置文件

## 你看到的异常现象是什么？

从昨天开始 Clash 里的服务器列表就突然全都超时了。准确地说是绝大多数时候全都超时，极少数时候有一两个服务器的延迟与以前正常时的延迟相当，但立即重新测速就大概率全都超时了。极少数时候可以正常翻墙几到几十秒钟。

- 墙外和墙内设备的时区都是 Asia/Shanghai 且相互之间的时间差都不超过 5 秒
- 无论是否绕开 CloudFlare CDN 都能正常访问墙外 VPS 上的 HTTPS 网站，证书正常，确认不是 CloudFlare CDN 返回的缓存，浏览器也没有提供缓存
- 无论是否绕开 CloudFlare CDN，墙外 VPS 的 Nginx 和 V2Ray 的日志都显示 V2Ray 确实能收到墙内设备上的 Clash 通过 CloudFlare CDN 发来的请求
- 已在 CloudFlare 控制面板讲网站设为处于开发模式（意思就是 CloudFlare 绝对不会返回缓存内容，而是每次都从源站拉取）。在 CloudFlare 只开了自动把用户由 HTTP 链接重定向到 HTTPS 链接，没开其它任何规则
- 通过其它翻墙可以手段 SSH 连接到墙外 VPS，VPS 能用 `curl` 等命令正常访问墙外网站

Clash 没问题，换用其它免费机场的订阅源后，可以正常从墙内用 Clash 翻墙。

**有个难以置信的现象：** 先用其它翻墙方法让我的电脑翻墙（假设翻到新加坡），再在我的电脑上用 Clash 翻墙，则 Clash 可以成功连接到我的墙外 VPS，测 IP 地址的网站显示我的 IP 地址确实是我的墙外 VPS 的 IP 地址而非新加坡的 IP 地址；仅关掉电脑上的 Clash 则测 IP 地址的网站显示 IP 地址在新加坡。

## 你期待看到的正常表现是怎样的？

从墙内可以用 Clash 裸连 CloudFlare CDN 再用 VPS 翻墙。

## 请附上你的配置

**服务端配置：**

```javascript
{
    "log": {
      "access": "路径1",
      "error": "路径2",
      "loglevel": "debug"
    },
    "inbound": {
      "port": "端口",
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "ID",
            "alterId": 0
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/由25个左右的字母和数字组成的字符串"
        }
      }
    },
    "outbound": {
      "protocol": "freedom",
      "settings": {}
    }
}
```

**客户端配置：**

这是 Clash 的配置，不是 V2Ray 作为客户端的配置！！！已将下面的 Clash 的配置改写为非常易懂的形式。

Clash for Windows 和 Clash for Android 使用相同的配置文件。

```javascript
本地代理服务器信息，比如充当 HTTP 代理服务器时监听本地哪个端口
DNS 服务器信息，比如使用哪
一些规则
  比如访问以 youtube.com 结尾的域名则选用服务器组 A 里选定的服务器
    如果服务器组 A 选定的是墙外服务器，那就翻墙
  访问以 bilibili.com 结尾的域名则选用服务器组 B 里选定的服务器
    如果服务器组 B 选定的服务器是直连，那就直连

翻墙服务器信息，每个条目只有 name 和 server 字段各异，其它字段完全相同
proxies:
  - {
      name: "CloudFlare 的某个 IP 地址",
      server: CloudFlare 的 某个 IP 地址,
      port: 443,
      type: vmess,
      uuid: 与墙外 VPS 上的 V2Ray 配置文件里的 inbound.settings.clients[0].id 一致,
      alterId: 0,
      cipher: auto,
      tls: true,
      skip-cert-verify: false,
      network: ws,
      udp: true,
      ws-opts: {
        path: 与墙外 VPS 上的 V2Ray 配置文件里的 inbound.streamSettings.wsSettings.path 一致,
        headers: {
          Host: 域名
        }
      }
    }

服务器组
proxy-groups:
  - name: 这是一个服务器组，它会自动选出测速延迟最低的服务器。用户无法手动在这个组里选定服务器
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 每隔多少秒重新测这个服务器组下的所有服务器的延迟
    disable-udp: false
    proxies: # 这个服务器组下的一些服务器
      - 与 Clash 配置文件里的 proxies[n].name 一致
  - name: 服务器组 A。允许用户手动在这个组里选定一个服务器
    type: select
    proxies:
      - 上面 type 为 url-test 的组选出的延迟最低的服务器
      - 墙内直连
      - 丢弃数据包
      - 与 Clash 配置文件里的 proxies[n].name 一致
  - name: 服务器组 B。允许用户手动在这个组里选定一个服务器
    type: select
    proxies:
      - 上面 type 为 url-test 的组选出的延迟最低的服务器
      - 墙内直连
      - 丢弃数据包
      - 与 Clash 配置文件里的 proxies[n].name 一致

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```
时间戳A [Info] [一串数字] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 我的墙内IP:0 > proxy/vmess/encoding: failed to read request header > read tcp 127.0.0.1:V2Ray监听的端口号->127.0.0.1:40964: i/o timeout
时间戳A [Info] [另一串数字] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 我的墙内IP:0 > proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
```

**客户端错误日志：**

Clash 的日志

```
时间戳B level=debug msg="[Process] 墙外域名 from process 浏览器路径"
时间戳B level=debug msg="[DNS] 墙外域名 --> 墙外域名对应的IP地址"
时间戳C level=warning msg="[TCP] dial 服务器组名 (match DomainSuffix/墙外域名的后缀) to 墙外域名:443 error: CloudFlare CDN IP地址:443 connect error: dial tcp4 CloudFlare CDN IP地址:443: i/o timeout"
```

## 请附上访问日志

```javascript
时间戳A 我的墙内IP地址:0 rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
```

## 其它相关的配置文件（如 Nginx）和相关日志

Nginx 配置

```nginx
user  root;
worker_processes  auto;
pid        /var/run/nginx.pid;
events {
    worker_connections  1024;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    sendfile        on;
    keepalive_timeout  65;
    include /etc/nginx/conf.d/*.conf;
    server {
        listen                  443 ssl;
        ssl_certificate         证书路径;
        ssl_certificate_key     密钥路径;
        ssl_protocols           TLSv1.2 TLSv1.3;
        server_name             域名;
        charset                 utf-8;
        access_log              访问日志路径;
        error_log               错误日志路径;
        location /与墙外 VPS 上的 V2Ray 配置文件里的 inbound.streamSettings.wsSettings.path 一致 {
            proxy_redirect      off;
            proxy_pass          http://127.0.0.1:V2ray监听的端口;
            proxy_http_version  1.1;
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection "upgrade";
            proxy_set_header    Host $http_host;
        }
    }
}
```

**Comment by akw5454521** [comment]
worker.dev被关照了

**Comment by slusludy** [comment]
> worker.dev被关照了

不是 `worker.dev` 域名

**Comment by chika0801** [comment]
你找台vps重装个系统，去ping.pe 看下端口，IP都正常，重装搭，不套CDN，测试下通不通。协议组合你自己选。

**Comment by slusludy** [comment]
今天突然恢复正常了，不知道到底发生了什么

**Comment by ChainZeaxion** [comment]
> 今天突然恢复正常了，不知道到底发生了什么

只要加tls，无论你干啥，放心，忙时都会被淦的
只是被淦的力度不一样而已
比如我这用的毛子线路，忙时最狠的时候tcp丢包60%，udp丢包50%，延迟从150拉到430，带宽从200Mbps限死2Mbps

**Comment by slusludy** [comment]
> > 今天突然恢复正常了，不知道到底发生了什么
> 
> 只要加tls，无论你干啥，放心，忙时都会被淦的 只是被淦的力度不一样而已 比如我这用的毛子线路，忙时最狠的时候tcp丢包60%，udp丢包50%，延迟从150拉到430，带宽从200Mbps限死2Mbps

最近了解到了 TLS 指纹，感觉更像是 Clash 的 TLS 指纹被识别出并被针对了，毕竟可以正常打开网页，Nginx 日志也显示收到了 Clash 发去的请求。不过在那次以后再也没有遇到过这种问题。
