### ISSUE TITLE
vmess协议，用着好好的，突然这两天就连接不上了！

### ISSUE THREAD

**Issue by ft0907** [v2fly/v2ray-core#1810]
服务端：
版本：v2ray-core v4.45.0
配置：`{
   "inbounds": [
     {
       "port": 18576,
       "protocol": "vmess",
       "settings": {
        "clients": [
           {
             "id": "xxxx", // 已生成唯一标识
             "alterId": 64
           }
         ]
       }
     }
   ],
   "outbounds": [
     {
       "protocol": "freedom",
       "settings": {}
     }
   ]
 }`

客户端
版本：ClashX 191.1
配置：`# VMess
- name: "v2ray"
  type: vmess
  server: 域名
  port: 18576
  uuid: xxx
  alterId: 64
  cipher: auto`

这是大概的配置，可以正常访问前和访问后的配置是一样的，区别是在于我升级客户端版本号后，然后重启了服务器的服务，就无法访问，
日志一致提示404，但是我把协议换成Shadowsocks后，是可以正常访问的。

想问下，是客户端问题，还是服务器端配置修改了什么我不知道的嘛？

**Comment by sososdk** [comment]
@love1st 为什么现在只能是0啊? 是哪个版本修改的?

**Comment by puzzle9** [comment]
> @love1st 为什么现在只能是0啊? 是哪个版本修改的?

https://www.v2fly.org/config/protocols/vmess.html#vmess
