### ISSUE TITLE
服务端 TLS 指纹

### ISSUE THREAD

**Issue by arm64v8a** [v2fly/v2ray-core#1823]
## TL;DR

v2ray TLS **服务器** 存在独特的指纹。

解决方案：请考虑应用前置（套个 Nginx HAProxy Caddy 什么的）

抱歉，有点像“弄个大新闻”，实际影响多大还需项目组人士评估。

## 起因

最近网络上流传[一份 IP 列表](https://hostloc.com/thread-1029502-4-1.html)，很多是 v2ray TLS，也有部分误报。

TLS 协议实现复杂，参数多， 考虑到 v2ray 之前在 **客户端** 方面出现了独特的指纹，服务器出现这种问题也不奇怪。但是 issue 搜了一圈，居然没人提到。

过去的讨论： https://github.com/v2ray/discussion/issues/704 https://github.com/v2ray/v2ray-core/issues/2098 https://github.com/v2ray/v2ray-core/issues/2542

## 复现

网络资产搜索引擎常用 [jarm](https://github.com/salesforce/jarm) 表示一个 TLS 服务的指纹。

影响 jarm 的因素有 证书类型（如RSA/ECDSA）、 Go 版本、[代码中的 TLS 设置](https://github.com/v2fly/v2ray-core/blob/4e247840821f3dd326722d4db02ee3c237074fc2/transport/internet/tls/config.go#L219)等。

jarm 需要连接服务器进行测试，应该属于主动探测。

简单测试得到一些结果

```
golang http.ListenAndServeTLS (go 1.18)

(ECDSA)
40d1db40d0000001dc43d1db1db43de
0a012c76cf078b8d06f4620c2286f5e

(RSA)
3fd21b20d00000021c43d21b21b43de
0a012c76cf078b8d06f4620c2286f5e 

v2ray 4.44.0-5.0.6 (go 1.17-1.18)

(ECDSA)
40d1db40d0000001dc43d1db1db43d2
f70423af611c314ea6b67982756f7de

(RSA)
3fd21b20d00000021c43d21b21b43d2
f70423af611c314ea6b67982756f7de

v2ray 4.41 (go 1.16)

1dd1eb40d00040d1dc42d1eb1db41d7
8dd8236626f2926d4bf2ca9ae325b54

caddy (go 1.18)

40d40d40d00000000043d40d40d43da
936ab0256fab25eca082941d14e3ece
```

如何判断这个指纹 “普遍都是v2ray” 呢？

前往某资产搜索网站搜索 jarm

![image](https://user-images.githubusercontent.com/48624112/172876591-ff51efbc-f2bf-4707-976a-c4a5249c613a.png)

这是 `40d40d40d00000000043d40d40d43da936ab0256fab25eca082941d14e3ece` caddy 的分布

![image](https://user-images.githubusercontent.com/48624112/172877176-9ffac879-a812-4fcc-b094-0b3ec976dec5.png)

这是 `40d1db40d0000001dc43d1db1db43d2f70423af611c314ea6b67982756f7de` v2ray 的分布

从机房分布大概可以看出这是什么人在用。

https://beta.shodan.io/search/facet?query=http&facet=ssl.jarm

也可以知道这个指纹是比较小众的。

## 题外话

如果我是 hostloc 该帖楼主，我可以下载很多一键脚本，包括带nginx前置的，然后收集指纹拿去搜索，看上去分布比较像的都可以拉清单。或许这个 IP 列表就是这样来的。

复现的过程中还搜到了 gost 和 x-ui 的指纹（小声）

**Comment by arm64v8a** [comment]
update:

该帖楼主似乎已把扫描方法贴出。 

**抱歉，本帖要求阅读权限高于 50 才能浏览**

[检测 Xray \ v2ray tls 直连包，欢迎拿包测试](https://hostloc.com/thread-1029753-1-1.html)

**Comment by bash99** [comment]
如果caddy指纹也有问题，那么套一个caddy怎么解决呢？

**Comment by bash99** [comment]
> 已经有现成的应用前置方案。不过按照上面的方法统计，直接用 ws tls / trojan tls 的人还有很多。

直接用v2ray解tls的好处是支持回落，否则用nginx卸载ssl，后端传输层基本上就只能走ws/grpc协议了，而grpc协议在网络差的情况下偶发卡死现象较多。

就原理理解sni模式实际暴露的指纹应该也是后端的v2ray等。

**Comment by bash99** [comment]
看了下某个网站的结果
caddy指纹大概是 255,278 条匹配结果 （ 59,576 条独立IP） 
v2ray指纹大概是  46,366 条匹配结果 （ 23,697 条独立IP）

不考虑独立ip，caddy大概还算安全；v2ray不知道是否混有其它go语言服务器端的结果。

单纯从服务端指纹看，极端安全的还是 nginx 后套ws/grpc（但是最好别用一键脚本的ssl配置，自己用nginx缺省配置或者[CF公开的配置](https://github.com/cloudflare/sslconfig) 此处感谢 [klzgrad](https://github.com/klzgrad)）；
其次可能是 haproxy + naiveproxy 模式，
下面这个组合不知道能否走通： haproxy（卸载ssl） -> grpc 或者haproxy（卸载ssl）-> caddy -> grpc/ws

**Comment by klzgrad** [comment]
我不理解“回落”这个功能的意义在哪里，如果是伪装，按照上面的描述，回落也起不到伪装的作用

**Comment by bash99** [comment]
> 我不理解“回落”这个功能的意义在哪里，如果是伪装，按照上面的描述，回落也起不到伪装的作用

应该就是方便单域名下支持多个协议（或者更简单的单个软件支持多个协议）

**Comment by Yebolin** [comment]
这个应该普遍性不强吧。
我的是这个 JARM: 29d3fd00029d29d00042d43d0000008aec5bb03750a1d7eddfa29fb2d1deea
我感觉应该相同也反映不出什么，有人相同不？

**Comment by bash99** [comment]
> 这个应该普遍性不强吧。 我的是这个 JARM: 29d3fd00029d29d00042d43d0000008aec5bb03750a1d7eddfa29fb2d1deea 我感觉应该相同也反映不出什么，有人相同不？

你这个是nginx解ssl的？如果是ws/grpc应该没啥漏洞，如果是sni分流，应该拿分流的域名测试。
