### ISSUE TITLE
使用自签名证书的问题

### ISSUE THREAD

**Issue by mengniu8** [v2fly/v2ray-core#1826]
今天突然想使用自签名证书来配置v2ray，但是发现客户端必须安装了这个证书才能使用。请问有没有办法不在系统内安装这个自签名证书就可以使用？

**Comment by azzvx** [comment]
客户端设置允许不安全的证书
```
"tlsSettings": {
    "allowInsecure": true
},
```

**Comment by jose-C2OaWi** [comment]
Use only specified certificates in v2ray without installing them into system root CA.
See the [official document](https://www.v2fly.org/en_US/config/transport.html#tlsobject).

```
"tlsSettings": {
    "allowInsecure": false,
    "disableSystemRoot": true
    "certificates": [
        {
            "certificateFile": "/path/to/ca.crt",
            "usage": "verify"
        }
    ]
}
```
