### ISSUE TITLE
Incorrect UDP timeout in v4/v5 server side with socks/shadowsocks

### ISSUE THREAD

**Issue by ValdikSS** [v2fly/v2ray-core#1827]
## What version of V2Ray are you using?

v4.45.0, v5.0.6 git master

## What's your scenario of using V2Ray?

**Server side**: shadowsocks tcp,udp inbound or socks tcp,udp inbound; freedom outbound
**Client side**: dokodemo-door udp inbound, shadowsocks or socks outbound to the server side

## What problems have you encountered?

The UDP timeout on the **server** side for UDP-UDP tunnel (socks, shadowsocks) is always 4 seconds, regardless of configured policy timeouts.
It doesn't matter whether the UDP connection seen packets from the both sides ("established" connection) or only the client sent the packets, the connection will be "forgotten" by v2fly server in 4 seconds.
Subsequent UDP packets from the client are threated as a new connection which new source port on the server socket, which usually completely breaks the application which uses such connection.

No issues with UDP-in-TCP tunnels (vmess). Also no issues without tunnels at all (client with dokodemo-door inbound and freedom outbound).

## What's your expectation?

UDP connection follow timeouts and does not close after 4 seconds of data inactivity.

## How to reproduce

1. Run `nc -u -l -p 2223 -vvv -n` on a remote server
2. Replace `your-server-ip-here-to-which-send-udp-traffic` with this server IP address in the client configuration file below
3. Start client and server
4. `ncat -u 127.0.0.1 5990` on a client
5. Send a single byte in ncat session

**Actual result**: After 4 seconds, the connection is completely forgotten by v2fly server-side, even if the server replied.
**Expected result**: The connection should follow configured timeout values.

## Please attach your configuration here

Configuration assumes both client and server are on the same machine (localhost).

**Server configuration:**

```javascript
{
  "log": {
    "loglevel": "debug"
  },

  "policy": {
    "levels": {
        "0": {
            "handshake": 40,
            "connIdle": 300,
            "uplinkOnly": 20,
            "downlinkOnly": 50,
            "statsUserUplink": false,
            "statsUserDownlink": false,
            "bufferSize": 10
        }
    },
    "system": {
        "statsInboundUplink": false,
        "statsInboundDownlink": false,
        "statsOutboundUplink": false,
        "statsOutboundDownlink": false
    }
  },

  "inbounds": [{
    "listen": "127.0.0.1",
    "port": 5995,
    "settings": {
      "method": "aes-128-gcm",
      "password": "12345",
      "network": "tcp,udp"
    },
    "protocol": "shadowsocks"
  }],

  "outbounds": [{
    "protocol": "freedom"
  }]
}

```

**Client configuration:**

```javascript
{
  "log": {
    "loglevel": "debug"
  },

  "inbounds": [{
    "port": 5990,
    "listen": "127.0.0.1",
    "protocol": "dokodemo-door",
    "settings": {
      "address": "your-server-ip-here-to-which-send-udp-traffic",
      "port": 2223,
      "network": "tcp,udp"
    }
  }],

  "outbounds": [{
    "settings": {
      "servers": [{
        "address": "127.0.0.1",
        "port": 5995,
        "method": "aes-128-gcm",
        "password": "12345",
        "network": "tcp,udp"
      }]
    },
    "protocol": "shadowsocks"
  }]
}

```

## Please attach error logs here

**Server error log:**

Server-side log of a single UDP packet from the client to the remote server. Note the seconds:

```javascript
2022/06/12 14:27:02 [Info] [224451425] proxy/socks: client UDP connection from udp:127.0.0.1:57367
2022/06/12 14:27:02 [Debug] [224451425] proxy/socks: send packet to udp:1.2.3.4:2223 with 2 bytes
2022/06/12 14:27:02 [Debug] [224451425] transport/internet/udp: dispatch request to: udp:1.2.3.4:2223
2022/06/12 14:27:02 [Info] transport/internet/udp: establishing new connection for udp:1.2.3.4:2223
2022/06/12 14:27:02 [Warning] [224451425] app/dispatcher: default route for udp:1.2.3.4:2223
2022/06/12 14:27:02 udp:127.0.0.1:57367 accepted udp:1.2.3.4:2223
2022/06/12 14:27:02 [Info] [224451425] proxy/freedom: opening connection to udp:1.2.3.4:2223
2022/06/12 14:27:06 [Info] [224451425] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2022/06/12 14:27:06 [Info] [224451425] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
```

**Client error log:**

No errors on the client side.

**Comment by AkinoKaede** [comment]
May be related.

https://github.com/v2fly/v2ray-core/blob/4e247840821f3dd326722d4db02ee3c237074fc2/app/proxyman/inbound/worker.go#L354-L362

**Comment by ValdikSS** [comment]
Nope, just commented it, did not help.

**Comment by AkinoKaede** [comment]
https://github.com/v2fly/v2ray-core/blob/6ff1cfa25372271f30c422c19fe6407526a1d842/transport/internet/udp/dispatcher_split.go#L72

**Comment by ValdikSS** [comment]
Yes, this is it!

**Comment by AkinoKaede** [comment]
@xiaokangwang I think it's too early to close the connection after 4 seconds. How do you think?

**Comment by ValdikSS** [comment]
This is the reply handler.
https://github.com/v2fly/v2ray-core/blob/6ff1cfa25372271f30c422c19fe6407526a1d842/transport/internet/udp/dispatcher_split.go#L117
After the time update there should be `timer.SetTimeout(policy.connidle)` after the first server reply.
And 4 seconds for UDP handshake is still too small as a default. In VoIP, for example, it could be tens of seconds before using the socket for STUN and then reusing the same socket for the real connection. With this small timeout, the real connection will use another source port on the server and the connection most probably won't succeed.

**Comment by xiaokangwang** [comment]
> @xiaokangwang I think it's too early to close the connection after 4 seconds. How do you think?

Yes, we can increase this timeout to let's say 300. 

@ValdikSS I think there is no Full Cone support unless you enable it with packet encoding options. You will need it to get WebRTC working.

**Comment by ValdikSS** [comment]
> I think there is no Full Cone support unless you enable it with packet encoding options. You will need it to get WebRTC working.

WebRTC works for me via TURN, but only with proper timeouts. With tiny timeouts, even TURN connection gets teared down.

**Comment by 1715173329** [comment]
@xiaokangwang Well, does dokodemo-door inbound has fullcone support? Seems like it ain't work. (With latest v5 HEAD)

**Comment by AkinoKaede** [comment]
> does dokodemo-door inbound has fullcone support? Seems like it ain't work

No.

**Comment by 1715173329** [comment]
> No.

Okay thanks. Hope it is available someday ;)
