### ISSUE TITLE
observatory如果探测到某一个Outbound失效，会在balancer中自动暂时不使用这个Outbound吗

### ISSUE THREAD

**Issue by wanzhiyu** [v2fly/v2ray-core#1841]
...
"observatory": {
        "subjectSelector": [
            "OUT_1",
            "OUT_2",
            "OUT_3"
        ],
        "probeInterval": "2s"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "domainMatcher": "mph",
        "balancers": [
            {
                "tag": "zz",
                "selector": [
                    "OUT_1",
                    "OUT_2",
                    "OUT_3"
                ],
                "strategy": {
                    "type": "random"
                }
            }
        ],
...
如上配置，会每2s发起一次探测，检测3个OUT的状态，随后，随机random从这3个OUT中挑选一个发起连接。
那么，假设此时OUT_1对应的远程服务器宕机了、失效了，那么使用random时会自动不使用这一个OUT_1吗？
如果没有这一功能，希望可以添加。

**Comment by simplerick-simplefun** [comment]
从我的实际使用观感来看目前不会。
你的某一个outbound失效有可能是服务端彻底挂了，也可能是碰到问题、修复一下就好了，也可能是服务器维护重启，过了2、3分钟自己就好了，也可能是网络传输中丢包了、过几秒钟重连就好了。那么v2应该暂停这个outbounds多长时间合适呢？

**Comment by wanzhiyu** [comment]
> 从我的实际使用观感来看目前不会。 你的某一个outbound失效有可能是服务端彻底挂了，也可能是碰到问题、修复一下就好了，也可能是服务器维护重启，过了2、3分钟自己就好了，也可能是网络传输中丢包了、过几秒钟重连就好了。那么v2应该暂停这个outbounds多长时间合适呢？

连接观测observatory里面的probeInterval设定了探测间隔时间，例如我上面设置为2s探测一次，那么如果outbound坏了，那么就暂时停用它，继续每2s探测一次，过了一段时间之后outbound恢复了，那么就再使用这个outbound

**Comment by wind315** [comment]
> 连接观测observatory里面的probeInterval设定了探测间隔时间，例如我上面设置为2s探测一次，那么如果outbound坏了，那么就暂时停用它，继续每2s探测一次，过了一段时间之后outbound恢复了，那么就再使用这个outbound
我没作过这个测试，也不知道怎么测试，不过我觉得应该就是这样工作的吧？比如已经probe没问题，那肯定会使用它，如果probe发现它不可用了，应该不会向它发送信息了吧？

**Comment by wind315** [comment]
> > 从我的实际使用观感来看目前不会。 你的某一个outbound失效有可能是服务端彻底挂了，也可能是碰到问题、修复一下就好了，也可能是服务器维护重启，过了2、3分钟自己就好了，也可能是网络传输中丢包了、过几秒钟重连就好了。那么v2应该暂停这个outbounds多长时间合适呢？
> 
> 连接观测observatory里面的probeInterval设定了探测间隔时间，例如我上面设置为2s探测一次，那么如果outbound坏了，那么就暂时停用它，继续每2s探测一次，过了一段时间之后outbound恢复了，那么就再使用这个outbound

我没作过这个测试，也不知道怎么测试，不过我觉得应该就是这样工作的吧？比如已经probe没问题，那肯定会使用它，如果probe发现它不可用了，应该不会向它发送信息了吧？
