### ISSUE TITLE
更新到 4.28.0 後, 客方error.log出现...GODEBUG=x509ignoreCN=0...(已解决)

### ISSUE THREAD

**Issue by kingwilliam** [v2fly/v2ray-core#185]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
`4.28.0`

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
```
golang 1.14.8 
- 用lets encrypt正常
- 用self sign certificate正常

golang 1.15.2
- 用lets encrypt正常
- 用self sign certificate v2client 出现 GODEBUG=x509 ignoreCN=0 error
```

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
```
haproxy SSL handshake failure
[12/Sep/2020:07:15:43.898] in-tcp01/1: SSL handshake failure
```

4) What's your expectation?
运作正常

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
        {
            "tag": "in-v2",
            "protocol": "vmess",
            "port": 44304,
            "settings": {
                "clients": [{
                        "id": "UUID",
                        "alterId": 0,
                        "level": 5
                    }
                ]
            },
            "streamsettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "{paht}"
                }
            }
        },
```

Client configuration:

```javascript
        {
            "tag": "out-v2",
            "protocol": "vmess",
            "settings": {
                "vnext": [{
                        "address": "{FQDN}",
                        "port": 443,
                        "users": [{
                                "id": "UUID",
                                "alterId": 0,
                                "security": "aes-128-gcm"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                },
                "network": "ws",
                "wsSettings": {
                    "path": "/{path}/"
                },
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": false,
                    "certificates": [{
                            "certificateFile": "user_crt.pem",
                            "keyFile": "user_key.pem"
                        }, {
                            "usage": "verify",
                            "certificateFile": "CA_crt.pem"
                        }
                    ]
                }
            }
        },
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
2020/09/12 07:17:04 [Warning] [27003027]   v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://{FQDN}/{path}/):  > x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0] > v2ray.com/core/common/retry: all retry attempts failed
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.
`流程: v2client -(tls+ws)-> [internet] -(tls+ws)-> haproxy -(ws)-> v2server`

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by kingwilliam** [comment]
可能我是用 self sign certificate 有关, 但用lets encrypt就正常, 我先看看CA和cert, 暂先关闭.

**Comment by kingwilliam** [comment]
已重新加入CN和SAN, 但还是 ERROR. 

![image](https://user-images.githubusercontent.com/3607762/92987630-e0de0400-f4f6-11ea-999c-9f2bbced62b0.png)

**Comment by kingwilliam** [comment]
这应该不是v2问题 应该是golang 1.15处理电子证书的问题。但还没找到解决方法。

**Comment by kslr** [comment]
https://stackoverflow.com/questions/25970714/invalid-common-name-when-using-a-san-certificate

**Comment by kingwilliam** [comment]
方向会是 

Go 1.15 Release Notes
X.509 CommonName deprecation

The deprecated, legacy behavior of treating the CommonName field on X.509 certificates as a host name when no Subject Alternative Names are present is now disabled by default. It can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable.

Note that if the CommonName is an invalid host name, it's always ignored, regardless of GODEBUG settings. Invalid names include those with any characters other than letters, digits, hyphens and underscores, and those with empty labels or trailing dots.

https://golang.org/doc/go1.15#commonname

**Comment by kingwilliam** [comment]
> 应该是 v2ctl 里的生成太旧了

我是用windows 2019 CA server. create ecdsa384 p256. 应该可以支援

**Comment by kslr** [comment]
> > 应该是 v2ctl 里的生成太旧了
> 
> 我是用windows 2019 CA server. create ecdsa384 p256. 应该可以支援

- 用self sign certificate v2client 出现 GODEBUG=x509 ignoreCN=0 error

我看错以为是指 ctl，这应该是一个合理的行为

**Comment by lxhao61** [comment]
> 请以足够的信息回答所有问题。不遵循此模板的所有问题将立即关闭。
> 如果不确定您的问题是否确实是V2Ray中的错误，请首先[在此处进行](https://github.com/v2fly/discussion/issues)讨论。
> 
> 1. 您正在使用哪个版本的V2Ray（如果您在服务器和客户端上部署了不同版本，请明确指出）？
>    `4.28.0`
> 2. 您使用V2Ray的情况如何？例如，通过Socks / VMess代理在Chrome中观看YouTube视频。
> 
> ```
> golang 1.14.8 
> - 用lets encrypt正常
> - 用self sign certificate正常
> 
> golang 1.15.2
> - 用lets encrypt正常
> - 用self sign certificate v2client 出现 GODEBUG=x509 ignoreCN=0 error
> ```
> 
> 1. 你看见什么了？（请详细描述，例如超时，伪造的TLS证书等）
> 
> ```
> haproxy SSL handshake failure
> [12/Sep/2020:07:15:43.898] in-tcp01/1: SSL handshake failure
> ```
> 
> 1. 有什么期待？
>    运作正常
> 2. 请附加您的配置文件（**提交此问题之前，**请**屏蔽IP地址**）。
> 
> 服务器配置：
> 
> ```js
>         { 
>             “ tag”：“ in-v2” ，
>             “ protocol”：“ vmess” ，
>             “ port”：44304 ，
>             “ settings”：{ 
>                 “ clients”：[ { 
>                         “ id”：“ UUID” ，
>                         “ alterId”：0 ，
>                         “ level”：5 
>                     } 
>                 ] 
>             } ，
>             “ streamsettings”：{ 
>                 “ network”：“ ws” ，
>                 “ wsSettings”：{ 
>                     “path“ ：” {paht}“ 
>                 } 
>             } 
>         }，
> ```
> 
> 客户端配置：
> 
> ```js
>         { 
>             “ tag”：“ out-v2” ，
>             “ protocol”：“ vmess” ，
>             “ settings”：{ 
>                 “ vnext”：[ { 
>                         “ address”：“ {FQDN}” ，
>                         “ port”：443 ，
>                         “ users”：[ { 
>                                 “ id”：“ UUID” ，
>                                 “ alterId”：0 ，
>                                 “ security”：“ aes-128-gcm” 
>                             } 
>                         ] 
>                     } 
>                 ] 
>             } ，
>             “streamSettings“ ：{ 
>                 ”“ sockopt”：{
>                     “ mark”：255 
>                 } ，
>                 “ network”：“ ws” ，
>                 “ wsSettings”：{ 
>                     “ path”：“ / {path} /” 
>                 } ，
>                 “ security”：“ tls” ，
>                 “ tlsSettings”：{ 
>                     “ allowInsecure”：false ，
>                     “ certificates”：[ { 
>                             “ certificateFile”：“ user_crt.pem” ，
>                             “ keyFile”：“ user_key.pem” 
>                         } ， { 
>                             “用法” ：“验证” ，
>                             “ certificateFile”：“ CA_crt.pem” 
>                         } 
>                     ] 
>                 } 
>             } 
>         } ，
> ```
> 
> 1. 请附加错误日志，尤其是如果文件很大的话，请附加在最底行。错误日志文件通常在`/var/log/v2ray/error.log`Linux上。
> 
> 服务器错误日志：
> 
> ```js
>     //请在此处附加服务器错误日志。
> ```
> 
> 客户端错误日志：
> 
> ```js
> 2020 / 09 / 12  07：17：04  [ 警告]  [ 27003027 ]    v2ray 。COM / 核心 / 应用 / proxyman / 出站：没 到 加工 出站 流量 >  v2ray 。COM / 核心 / 代理 / vmess / 出站：失败 来 找到 一个 可用的 目的地 >  v2ray 。com / core / common / retry：[ v2ray 。COM / 核心 / 运输 / 互联网 / WebSocket的：没 给 拨 的WebSocket  >  v2ray 。COM / 核心 / 运输 / 互联网 / WebSocket的：没 给 拨 至 （WSS：// {FQDN} / {path} /）：> x509：证书依赖于旧的Common Name字段，使用SAN或使用GODEBUG = x509ignoreCN = 0]临时启用Common Name匹配> v2ray.com/core/common/retry：全部重试尝试失败
> ```
> 
> 1. 请附上访问日志。访问日志通常在Linux上位于“ /var/log/v2ray/access.log”。
> 
> ```js
>     //请在此处附加服务器访问日志。
> ```
> 
> 1. 其他配置（例如Nginx）和日志。
>    `流程: v2client -(tls+ws)-> [internet] -(tls+ws)-> haproxy -(ws)-> v2server`
> 2. 如果V2Ray没有运行，请附加来自的输出`--test`。
> 
> 该命令通常为`/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`，但根据您的情况可能有所不同。
> 
> 1. 如果V2Ray服务未运行，请附加日志日志。
> 
> 通常的命令是`journalctl -u v2ray`。
> 
> 提交前，请先审核您的问题。

配置文件错误！见下： 
 ”“ sockopt”：{
多了 ”

**Comment by kingwilliam** [comment]
抱歉 不要错重点

**Comment by kingwilliam** [comment]
> 自己配置文件错误！见下：
> ”“ sockopt”：{
> 多了 ”

抱歉 不要错重点

**Comment by kingwilliam** [comment]
问题终於解决 "x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0" 原於 golang 1.15开始已不支援 CN即Common Name存放FQDN. 所以如有用自签证书的, 大多数都会在客户端error.log内看见这错误信息。如不在CN内放FQDN,那麽FQDN应放那? SAN内的DNS是也. openSSL本人不太会用, 如用windows CA就在下图显示

![image](https://user-images.githubusercontent.com/3607762/92999448-832bd500-f553-11ea-879a-f9f59b429de0.png)
