### ISSUE TITLE
vless-ws是否安全

### ISSUE THREAD

**Issue by ahasid** [v2fly/v2ray-core#1857]
不知道vless-ws是否安全，见帮助里面写到vless本身没有加密，所以需要tls加密，不知道tls加密的是什么呢？
按理说443端口不是就已经属于流量加密了吗？对这方面不理解，能不能帮忙解答一下。

**Comment by Johnshall** [comment]
安全的。简单的说，TLS工作在传输层，为工作在应用层的websocket进行可靠的加密。


详细资料：
[傳輸層安全性協定](https://zh.m.wikipedia.org/zh-cn/傳輸層安全性協定)

**Comment by AkinoKaede** [comment]
No, the stream will not been encrypted.

**Comment by ahasid** [comment]
Got it, thanks for the reply!

**Comment by gudong1012** [comment]
> No, the stream will not been encrypted.否，流不会被加密。

If I use vmess+ws to log in to an https website, will my account number and password be leaked?
