### ISSUE TITLE
How can I add traffic limit in GB?

### ISSUE THREAD

**Issue by josefredohd** [v2fly/v2ray-core#1858]
I need help I need to add this to my server

**Comment by simplerick-simplefun** [comment]
https://www.v2fly.org/en_US/config/api.html
unfortunately it's not well documented

https://github.com/v2fly/v2ray-core/blob/fc6ae4d4e7f5158d7222a42c749d2bf7ca913632/app/stats/command/command_grpc.pb.go#L158
https://www.v2fly.org/config/stats.html

https://github.com/v2fly/v2ray-core/blob/fc6ae4d4e7f5158d7222a42c749d2bf7ca913632/app/proxyman/command/command_grpc.pb.go#L251

https://guide.v2fly.org/en_US/advanced/traffic.html#processing-of-traffic-stats

**Comment by josefredohd** [comment]
I'm not very good at this, could you give me an example please. For example if I wanted to limit it to 50GB

**Comment by simplerick-simplefun** [comment]
> I'm not very good at this, could you give me an example please. For example if I wanted to limit it to 50GB

https://www.mebi.me/1684.html

https://www.google.com/search?q=v2ray+api+%E6%B5%81%E9%87%8F+%E9%99%90%E5%88%B6&oq=v2ray+api+%E6%B5%81%E9%87%8F+%E9%99%90%E5%88%B6&aqs=chrome..69i57j33i160.9559j0j4&sourceid=chrome&ie=UTF-8

**Comment by josefredohd** [comment]
Help me please

**Comment by database64128** [comment]
Open source is "Here's the code. Help yourself.", not "help me please".
