### ISSUE TITLE
unknown config id: mtproto

### ISSUE THREAD

**Issue by benyamin218118** [v2fly/v2ray-core#1875]
v2ray version on server :
V2Ray v5.0.7 (user) 20220716-185236 (go1.18.4 linux/amd64)

server config : 
```
{
  "inbounds": [{
    "tag":"tag-in",
    "port": 4040,
    "protocol": "mtproto",
    "settings": {
	"users": [{"secret": "b0cbcef5a486d9636472ac27f8e11a9d"}]
    }
  }],
  "outbounds": [{
    "tag":"tag-out",
    "protocol": "mtproto",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": ["tg-in"],
        "outboundTag": "tg-out"
      },
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}
```

result of test with command `v2ray test -config ./mtprotoConf.json` is : 

`Test failed: main/commands: failed to load config: [./mtprotoConf.json] > infra/conf/v4: failed to load inbound detour config. > infra/conf/cfgcommon/loader: unknown config id: mtproto`

im already running a vmess one and everything works fine. but with mtproto its not.

whats wrong?

**Comment by AkinoKaede** [comment]
`MTProto` was removed in v5.
