### ISSUE TITLE
火狐===建立安全连接失败

### ISSUE THREAD

**Issue by lijin-tao** [v2fly/v2ray-core#1889]
## 火狐浏览器显示的信息是这样的
建立安全连接失败

连接到 youtube.com 时发生错误。PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

使用的版本是 V2Ray 4.45.2

**Comment by kslr** [comment]
Closed, issue Template not used.
