### ISSUE TITLE
对路由字段 ip, port, source, sourcePort 使用更加合理的命名

### ISSUE THREAD

**Issue by kslr** [v2fly/v2ray-core#190]
目前建议有:

- targetIP, sourceIP, targetPort, sourcePort
- targetAddress, sourceAddress, targetPort, sourcePort
- srcAddr, dstAddr, srcPort, dstPort

ref: https://www.v2fly.org/config/routing.html#ruleobject

**Comment by rprx** [comment]
srcIP, srcPort
dstIP, dstPort

**Comment by rprx** [comment]
因为这里只指 IP，不含域名，所以直接写 IP 更直观

src 一般对应 dst

**Comment by Vigilans** [comment]
Ref https://github.com/v2fly/v2ray-core/pull/87#issuecomment-691650010：

> 现在的"ip”是一个使用率极高的字段，"port”的使用率也不低，想让用户迁移过来应该是相当难的。此外，"domain"其实也是"target domain"，所以让"ip", "port", "domain"三者都隐式表示"target"感觉还是比较合理的。相对来说让"source"变成"sourceIP", "srcIP"或"sourceIp"比较合理，"source"这个名取得实在不太好。

> targetAddress, sourceAddress, targetPort, sourcePort

源码里Address类表示一个IP或一个域名，这里用Address应该会有点混淆……

**Comment by kslr** [comment]
> Ref [https://github.com/v2fly/v2ray-core/pull/87#issuecomment-691650010：](https://github.com/v2fly/v2ray-core/pull/87#issuecomment-691650010%EF%BC%9A)
> 
> > 现在的"ip”是一个使用率极高的字段，"port”的使用率也不低，想让用户迁移过来应该是相当难的。此外，"domain"其实也是"target domain"，所以让"ip", "port", "domain"三者都隐式表示"target"感觉还是比较合理的。相对来说让"source"变成"sourceIP", "srcIP"或"sourceIp"比较合理，"source"这个名取得实在不太好。
> 
> > targetAddress, sourceAddress, targetPort, sourcePort
> 
> 源码里Address类表示一个IP或一个域名，这里用Address应该会有点混淆……

如果只表示IP的话就不适用。可以确定的是，目前可以改掉 source

**Comment by zenyanbo** [comment]
算了吧。不过是个名称。改来改去还让不让人用了。。。

**Comment by rex5652** [comment]
srcAddr, dstAddr, srctPort, dstPort

**Comment by d4rkblue** [comment]
辛苦作出贡献的各位。
4.28.0以后，需要客户端和服务器端版本统一才能使用，已经有用户觉得不便了。如果修改字段，会不会再次需要修改json文件，这种情况希望尽可能的少出现。修改这些字段的必要性可以在此讨论，如果必须，可否在软件升级大版本的时候进行？

**Comment by xiebruce** [comment]
@d4rkblue 如果确实要改，建议暂时做兼容处理(也就是json中原字段名也允许使用，但提倡用新名)，然后在后续的版本中不断警告，让各大平台的客户端作者以及服务器端搭建者有时间了解并修改，到某个大版本时彻底去掉兼容，直接采用新名称。

**Comment by rprx** [comment]
@xiebruce 

如果要改的话，肯定是这样的形式，配置加载一般都会尽量兼容旧版。（我之前发现单个 inbound outbound 都还支持）

**Comment by xiebruce** [comment]
@rprx 嗯嗯，确实一般都会用这样的形式

**Comment by oemaix** [comment]
srcIP, srcPort
dstIP, dstPort

**Comment by chinsyo** [comment]
> 目前建议有:
> 
> * targetIP, sourceIP, targetPort, sourcePort
> * targetAddress, sourceAddress, targetPort, sourcePort
> * srcAddr, dstAddr, srctPort, dstPort
> 
> ref: https://www.v2fly.org/config/routing.html#ruleobject

I'm guessing the `srctPort` here is a typo, should it be `srcPort`?
