### ISSUE TITLE
Darwin's TFO impl was not support now.

### ISSUE THREAD

**Issue by fly3366** [v2fly/v2ray-core#1908]
TCP Fastopen impl for darwin is not support syscall with TCP_FASTOPEN_CLIENT.

Need to instead with CONNECTX.

**Comment by fly3366** [comment]
if anyone need it, i may submit PR for this.

**Comment by database64128** [comment]
Instead of trying to fix this mess, maybe consider switching to a modern alternative instead:

- https://github.com/database64128/shadowsocks-go
- https://github.com/SagerNet/sing-box

Both of these use my https://github.com/database64128/tfo-go for TFO support on Linux, Windows, macOS and FreeBSD.
