### ISSUE TITLE
希望增加对SS加密rc4支持

### ISSUE THREAD

**Issue by shenchihua** [v2fly/v2ray-core#191]
配置成功
Shadowsocks-SS(47***110:476)
启动服务(2020/9/13 20:19:15)...
2020/09/13 20:19:15 Using default config:  D:\Software\Proxy\v2rayN-Core\config.json

V2Ray 4.28.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 windows/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [D:\Software\Proxy\v2rayN-Core\config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  D:\Software\Proxy\v2rayN-Core\config.json
v2ray.com/core/infra/conf: **unknown cipher method: rc4-md5** > exit status 4294967295

**Comment by kslr** [comment]
没有该计划

**Comment by maskedeken** [comment]
正好我也有这样的需求，因为配合tls使用时，ss的加密越简单越好，所以我做了个分支，支持rc4-md5和rc4-md5-6
[](https://github.com/maskedeken/v2ray-core/tree/ss-enhance)

**Comment by shenchihua** [comment]
> [，[tls]，s]，[，]，[rc4-md5]rc4-md5-6https://github.com/maskedeken/v2ray-core/tree/ss-enhance

我用的V2rayN客户端,你的这个在windows我不知道怎么用
