### ISSUE TITLE
老BUG了，HTTP Range 206 Partial Content范围响应播放的mp4视频，或者speedtest测速等链接，暂停播放或者浏览器关闭后还持续异常跑流量，开启或关闭mux均可必定复现此问题

### ISSUE THREAD

**Issue by 1265578519** [v2fly/v2ray-core#1912]
老BUG了，HTTP Range 206 Partial Content范围响应播放的mp4视频，或者speedtest测速等链接，暂停播放或者浏览器关闭后还持续异常跑流量，开启或关闭mux均可必定复现此问题

这个问题什么时候修？别说你们没遇到这个问题！前几年我就就反馈过了。

**Comment by 1265578519** [comment]
@AkinoKaede 看到你标记completed已解决完成，请问具体是哪个pulls？我检查了下列表没看到相关的修复。

**Comment by AkinoKaede** [comment]
Currently only reproducing this issue when I turn on Mux.Cool.

**Comment by zjx20** [comment]
It seems to be solved in https://github.com/XTLS/Xray-core/pull/1417 , hopefully the patch will be ported here too.
