### ISSUE TITLE
linux 下启动客户端报错x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by o-water-o** [v2fly/v2ray-core#192]
log:
```v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > x509: certificate signed by unknown authority```

server config:
`  
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxx", // 填写你的 UUID
                        "level": 0,
                        "email": "xxx"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/home/tom/.acme.sh/xxx.cer", // 换成你的证书，绝对路径
                            "keyFile": "/home/tom/.acme.sh/xxp.key" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}`

client config:

`{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 1081,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "xxxx", // 换成你的域名
                        "port": 443,
                        "users": [
                            {
                                "id": "xxxx", // 填写你的 UUID
                                "encryption": "none",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls"
            }
        }
    ]
}`

同样的配置在windows下是可以的，但是在linux下无法连接服务器v2ray

**Comment by kslr** [comment]
你不是都看到错误了

**Comment by o-water-o** [comment]
是看到错误了，谷歌了一顿操作后还是解决不了。
---原始邮件---
发件人:&quot;Kslr&quot;<notifications@github.com&gt;
发送时间:2020年9月13日 星期日 下午9:52
收件人:&quot;v2fly/v2ray-core&quot;<v2ray-core@noreply.github.com&gt;
抄送:&quot;AKWoWo&quot;<457331510@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;
主题:Re: [v2fly/v2ray-core] linux 下启动客户端报错x509: certificate signed by unknown authority (#192)



你不是都看到错误了

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by kslr** [comment]
你的是什么证书？ 证书链完整吗？

**Comment by o-water-o** [comment]
> 你的是什么证书？ 证书链完整吗？

使用fullchain 的xxx.crt就好了，谢谢指导
