### ISSUE TITLE
V5版本，VMESS GRPC协议，监听 unix socket 启动报错 grpc unix istener not registered.

### ISSUE THREAD

**Issue by gamesofts** [v2fly/v2ray-core#1925]
## What version of V2Ray are you using?

**5.0.8**

## What problems have you encountered?

**启动失败，报错：grpc unix istener not registered.**

## Please attach your configuration here

``` json
{
  "inbounds": [
    {
      "listen": "/tmp/v2ray.socket",
      "protocol": "vmess",
      "settings": {
        "users": [
          "xxxx-xxxx-xxxx-xxxx"
        ]
      },
      "streamSettings": {
        "security": "none",
        "transport": "grpc",
        "transportSettings": {
          "serviceName": "myService"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}
```

## Please attach error logs here

V2Ray 5.0.8 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
Failed to start: app/proxyman/inbound: failed to listen Unix Domain Socket on /tmp/v2ray.socket > transport/internet: grpc unix istener not registered.

**Comment by hedsbj** [comment]
类似问题，xray上同样的配置（正常使用），在最新v2ray上启动没有错误，但不能正常使用

**Comment by fjn308** [comment]
请参阅v2ray文档（不论v4v5）inbounds的listen部分：
> 填写 Unix domain socket 时，port 将被忽略，协议暂时可选 VLESS、VMess、Trojan，传输方式可选 TCP、WebSocket、HTTP/2。

注意上面不包含 grpc。但是，在 xray 的文档中此处包含了 grpc，似乎是额外特性。

**Comment by AkinoKaede** [comment]
It's a bug, I will fix it. A workaround is set `protocol` to `gun`.
