### ISSUE TITLE
[websocket mode] alpn in client-hello make it's v2ray

### ISSUE THREAD

**Issue by liudongmiao** [v2fly/v2ray-core#1926]
| type | alpn |
| --- | --- |
| go-https (net/http) | h2, http/1.1 |
| v2ray-core | http/1.1 |
| go-websocket (github.com/gorilla/websocket) | N/A |

Referer: https://github.com/v2fly/v2ray-core/commit/8e791e92bc1898e11904bf54462635aed864cd04#diff-98874970fe9e833c1469702de67b4a0d1c731059ad04a00a349093f52f141f31R48

And for web browsers:
| scheme | alpn |
| --- | --- |
| https | h2, http/1.1 |
| wss | http/1.1 |

Please note, websocket over http2 is not supported.
IMO, v2ray-core should send `h2, http/1.1` like go-https (net/http), however, this requires server (like nginx) turn off http2.

**Comment by liudongmiao** [comment]
JA3 fingerprint: https://engineering.salesforce.com/tls-fingerprinting-with-ja3-and-ja3s-247362855967

**Comment by klzgrad** [comment]
FYI: WebSocket over H2 is supported after Chrome 91. https://chromestatus.com/feature/6251293127475200

**Comment by liudongmiao** [comment]
> FYI: WebSocket over H2 is supported after Chrome 91. https://chromestatus.com/feature/6251293127475200

@klzgrad I have chedked it before, however there is no way to turn on. And from my case, browser always send http/1.1 for wss.

**Comment by klzgrad** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=801564#c48

It's always enabled

**Comment by liudongmiao** [comment]
@klzgrad Just use chrome with a wss://.... then use wireshark to dump the packets.
