### ISSUE TITLE
建议：启动v2ray时，对配置中使用了geo文件中不再存在的分类，希望能跳过这条规则继续

### ISSUE THREAD

**Issue by rendaa** [v2fly/v2ray-core#1928]
一部分使用Loyalsoldier加强版geo文件的人们，一般会配合在v2ray的配置文件中使用相应的分类（category，如 geoip:cn、geosite:gfw 等）来指定更详细的DNS或路由规则，但如果geo文件的更新版本中突然取消了原有的分类，在v2ray重新启动时则会报错并停止运行。

这在一些将几乎所有发往外网的流量完全交由v2ray、以处理复杂些的路由规则的透明代理应用情景中，会因v2ray没有启动而导致无法访问外网。

可否考虑能调整 v2ray，使其在分析配置文件时对此类不存在的分类名字仅简单地忽略、以便能继续启动程序，而不是报错、退出？

烦请考虑此建议，谢谢！

**Comment by AkinoKaede** [comment]
I don't think it's wise to do so. These files are not part of the software.

**Comment by rendaa** [comment]
> I don't think it's wise to do so. These files are not part of the software.

这些文件本身确实不是本软件的部分，但本软件使用了这些第三方数据，用户希望软件能更“明智”些地处理好第三方数据可能造成的问题。希望你能明白，这里讨论的还是本软件本身的行为设计（并且这个调整其实并不难实现），并不应该就此关闭讨论。

当然，既然是member，你可以决定是否关闭讨论；我作为用户，也可以决定自己选用什么产品和向别人推荐什么。

**Comment by AkinoKaede** [comment]
Ignoring errors is likely to lead to leak problems.

**Comment by rendaa** [comment]
如果代码逻辑良好，忽略不存在的名字应该不那么likely地造成渗漏问题。从使用角度出发，遇到这种可忽略的错误而继续保证网络的功能，肯定比简单地停止运行、让外层的脚本或系统监控程序处理代价要小很多。不知道其他的使用者会希望怎样。

**Comment by universonic** [comment]
两位说的都不错。我建议对于这种情况可以在日志中输出warning，而不是强制退出。
