### ISSUE TITLE
升级4.28.1内核后部分线路无法联网

### ISSUE THREAD

**Issue by chafer516** [v2fly/v2ray-core#195]
PC端v2rayN 3.23版本  内核4.28.1出现部分线路无法联网的情况
线路为非443端口，tcp传输协议。无法联网
但是，此线路在手机端正常联网。
443端口和ws协议的线路可正常上网。
把内核降为4.27.5后，线路可正常联网。

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/93230436-3ee64200-f7aa-11ea-8448-22e99ea43bf9.png)
![image](https://user-images.githubusercontent.com/6442439/93230450-41489c00-f7aa-11ea-91b5-f37a9d6746de.png)
额外ID为0则强制启用aead加密
启用加密的情况必须要相同版本
为0的情况，一定需要相同版本
可以考虑升级服务端、、
客户端也升级到最新版，以最新版为标准

想要兼容旧版本客户端，那么得怎么兼容旧版本了
额外ID不为0即可。。

**Comment by twzchi** [comment]
> ![image](https://user-images.githubusercontent.com/6442439/93230436-3ee64200-f7aa-11ea-8448-22e99ea43bf9.png)
> ![image](https://user-images.githubusercontent.com/6442439/93230450-41489c00-f7aa-11ea-91b5-f37a9d6746de.png)
> 额外ID为0则强制启用aead加密
> 启用加密的情况必须要相同版本
> 为0的情况，一定需要相同版本
> 可以考虑升级服务端、、
> 客户端也升级到最新版，以最新版为标准
> 
> 想要兼容旧版本客户端，那么得怎么兼容旧版本了
> 额外ID不为0即可。。


 开启VMess AEAD 之后，配合TCP+TLS 这种组合，效果会如何？

**Comment by 1265578519** [comment]
AEAD 加密可以保证你的服务器不会被主动探测被墙封禁ip

**Comment by kslr** [comment]
以后aead会成为默认，不过如果你只用tls 可以试试专门设计在tls下工作的vless

**Comment by 1265578519** [comment]
嗯。以后vmess额外ID这个配置项可以废掉了，直接默认强制启用AEAD
和vless一样，完全不需要额外ID这个东东
