### ISSUE TITLE
5.1.0新核心无法上网，更新服务器端后上网失效

### ISSUE THREAD

**Issue by jackson-lx** [v2fly/v2ray-core#1950]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

This issue will be closed immediately.

**Comment by wxhsh** [comment]
我也是，服务端升级后就不能用了，现在只能换到xray-core。

**Comment by qonmnop** [comment]
> 我也是，服务端升级后就不能用了，现在只能换到xray-core。

清理掉无用的systemd配置

**Comment by lychichem** [comment]
你们的客户端是不是用的v2rayn，v2rayn用户要用这个5.1.0版core的话需要暂时把core类型选成sagernet

**Comment by ecrasy** [comment]
新版本的v2ray的命令行格式变了
直接替换二进制程序会失败

**Comment by azgh** [comment]
> 

同样情况，更新到5.1.0，无法上网了

**Comment by lhzw** [comment]
Cannot work, revert to old version v2ray-linux-64-v4.45.2.zip:
```
~# v2ray -h
Usage of v2ray:
# v2ray --help
Usage of v2ray:
# ls
```

**Comment by edimetia3d** [comment]
I dont get it, why a MEANINGLESS BREAKING change is introduced in a pretty stable software ?

FYI

Modify these file may help

/etc/systemd/system/v2ray.service 
/etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf

**Comment by wenge110110** [comment]
一样的问题

**Comment by wenge110110** [comment]
好像rm -rf /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
再systemctl restart v2ray
就好了

**Comment by wenge110110** [comment]
处理方式1：
rm -rf /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
systemctl daemon-reload
systemctl restart v2ray
处理方式2：
vi /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
把ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
改为ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json
systemctl daemon-reload
systemctl restart v2ray
处理方式3：
切回老版本：
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --version v4.45.2 就好啦

**Comment by jackson-lx** [comment]
处理方式1与2，路径不对，/etc/systemd/system/下没有v2ray.server.d/这个目录

wenge110110 ***@***.***> 于2022年9月8日周四 11:40写道：

**Comment by wenge110110** [comment]
sed -i "s/v2ray -config/v2ray run -config/g" /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
systemctl daemon-reload
systemctl restart v2ray

**Comment by jackson-lx** [comment]
已解决，谢谢

wenge110110 ***@***.***>于2022年9月8日 周四13:42写道：

**Comment by CangMang1** [comment]
## V2Ray 版本: v  /  V2Ray 状态: 未在运行 ##
一直是这个 和你们说的问题是一回事吗。。。

**Comment by CangMang1** [comment]
退货版本的代码运行后 显示还是5.1 ## V2Ray 版本: v5.1.0  /  V2Ray 状态: 未在运行 ##

**Comment by cyqco7612** [comment]
更新以后连不上了，希望尽快修正。显示状态 未在运行

**Comment by tannx** [comment]
> AcidShen

Thanks, it's work !

**Comment by liu731** [comment]
Docker Images v2fly/v2fly-core have the same problem

**Comment by AI2Hub** [comment]
Same problem, try install --version v4.45.2  it's work !  

bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --version v4.45.2

**Comment by xiasummer** [comment]
当前 V2Ray 版本: v5.1.0  /  当前 V2Ray 管理脚本版本: v3.67 
遇到了同样的问题，无法启动起来，一直都是 “未在运行”

**Comment by ZCDW-HTHY** [comment]
> 处理方式1： rm -rf /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf systemctl daemon-reload systemctl restart v2ray 处理方式2： vi /etc/systemd/system/v2ray.service.d/ 10-donot_touch_single_conf.conf 把ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json 改为ExecStart=/usr/local/bin/v2ray run -config /usr/local/ etc/v2ray/config.json systemctl daemon-reload systemctl restart v2ray 处理方式3：切换 老版本： bash <(curl -L [https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install -release.sh](https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) ) --version v4.45.2 就好啦

你这个得Centos8 x64才有效，我一台centos7的就无效。

**Comment by Geker** [comment]
this is the newest one of many times v2ray work broken by just update execute binary

**Comment by dongshimou** [comment]
2023 年了... 5.x 的`run` 的改动还没更新到 docker 版本.

**Comment by ZCDW-HTHY** [comment]
散了吧，作者进去了，内核故意改成不能使用的
