### ISSUE TITLE
处理方式1：

### ISSUE THREAD

**Issue by CangMang1** [v2fly/v2ray-core#1960]
处理方式1：
rm -rf /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
systemctl daemon-reload
systemctl restart v2ray
处理方式2：
vi /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
把ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
改为ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json
systemctl daemon-reload
systemctl restart v2ray
处理方式3：
切回老版本：
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --version v4.45.2 就好啦

_Originally posted by @wenge110110 in https://github.com/v2fly/v2ray-core/discussions/1953#discussioncomment-3590733_

降回V4.45.2还是无法启动。。。。

**Comment by wenge110110** [comment]
附上错误信息或者到我主页找我的联系方式

**Comment by didila** [comment]
我的处理方式是切回老版本
将已更新5.1.0的版本全数砍掉，重新安装下载4.45.2。
如果只是降版本是没用的

**Comment by wenge110110** [comment]
> 我的处理方式是切回老版本 将已更新5.1.0的版本全数砍掉，重新安装下载4.45.2。 如果只是降版本是没用的

https://github.com/v2fly/v2ray-core/issues/1950#issuecomment-1240245811
