### ISSUE TITLE
在v5配置文件中加入路由配置后报错

### ISSUE THREAD

**Issue by 9Canon** [v2fly/v2ray-core#1965]
## 你正在使用哪个版本的 V2Ray？
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)

## 你的使用场景是什么？
配置vlite出站

## 你看到的异常现象是什么？
服务端正常
客户端vlite报错无法运行

## 你期待看到的正常表现是怎样的？
vlite正常运行

## 请附上你的配置

**客户端配置：**

```javascript
{
  "log": {
    "error": {
      "level": "Debug",
      "type": "Console"
    },
    "access": {
      "type": "None"
    }
  },
  "outbounds": [
    {
      "protocol": "freedom"
    },
    {
      "protocol": "vliteu",
      "settings": {
        "address": "xxxxx",
        "port": 8811,
        "password": "pw",
        "enableFec": true,
        "enableStabilization": true,
        "enableRenegotiation": true
      },
      "tag": "vlite"
    }
  ],
  "inbounds": [
    {
      "protocol": "socks",
      "settings": {
        "udpEnabled": true,
        "address": "127.0.0.1",
        "packetEncoding": "Packet"
      },
      "port": 10808
    }
  ],
  "router": {
    "domainStrategy": "AsIs",
    "rule": [
      {
        "tag": "vlite",
        "domain": [
          {
            "type":"RootDomain",
            "value": "packet-addr.v2fly.arpa"
          }
        ]
      }
    ]
  }
}
```

## 请附上出错时软件输出的错误日志

**客户端错误日志：**

```javascript
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
2022/09/09 20:08:55 [Debug] app/log: Logger started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xae2d92]

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v5/app/router.init.1.func2({0x12307a0, 0xc0001b1470}, {0xfe1280?, 0xc0001779e0})
	github.com/v2fly/v2ray-core/v5/app/router/router.go:242 +0x692
github.com/v2fly/v2ray-core/v5/common.CreateObject({0x12307a0, 0xc0001b1470}, {0xfe1280, 0xc0001779e0})
	github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
github.com/v2fly/v2ray-core/v5.CreateObjectWithEnvironment(0xc0004a4cc0?, {0xfe1280, 0xc0001779e0}, {0x1016e20?, 0xc0004a4de0?})
	github.com/v2fly/v2ray-core/v5/functions.go:25 +0x8c
github.com/v2fly/v2ray-core/v5.initInstanceWithConfig(0xc0001dcfc0, 0xc0001778c0)
	github.com/v2fly/v2ray-core/v5/v2ray.go:203 +0x2e5
github.com/v2fly/v2ray-core/v5.New(0x7ffd78f5d291?)
	github.com/v2fly/v2ray-core/v5/v2ray.go:167 +0x77
github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
	github.com/v2fly/v2ray-core/v5/main/commands/run.go:205 +0x275
github.com/v2fly/v2ray-core/v5/main/commands.executeRun(0x196e0c0, {0xc00003e200, 0x4, 0x4})
	github.com/v2fly/v2ray-core/v5/main/commands/run.go:82 +0xca
github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
	github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x636
main.main()
	github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x285

```

## 请附上访问日志

无输出

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出
```
➜  v2ray v2ray test -config 2.json -format jsonv5                                                   
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
2022/09/09 20:10:50 [Debug] app/log: Logger started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xae2d92]

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v5/app/router.init.1.func2({0x12307a0, 0xc0001ed440}, {0xfe1280?, 0xc0001b3920})
	github.com/v2fly/v2ray-core/v5/app/router/router.go:242 +0x692
github.com/v2fly/v2ray-core/v5/common.CreateObject({0x12307a0, 0xc0001ed440}, {0xfe1280, 0xc0001b3920})
	github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
github.com/v2fly/v2ray-core/v5.CreateObjectWithEnvironment(0xc0004a0c80?, {0xfe1280, 0xc0001b3920}, {0x1016e20?, 0xc0004a0da0?})
	github.com/v2fly/v2ray-core/v5/functions.go:25 +0x8c
github.com/v2fly/v2ray-core/v5.initInstanceWithConfig(0xc0004eb170, 0xc0001b3800)
	github.com/v2fly/v2ray-core/v5/v2ray.go:203 +0x2e5
github.com/v2fly/v2ray-core/v5.New(0x7ffc26e89291?)
	github.com/v2fly/v2ray-core/v5/v2ray.go:167 +0x77
github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
	github.com/v2fly/v2ray-core/v5/main/commands/run.go:205 +0x275
github.com/v2fly/v2ray-core/v5/main/commands.executeTest(0x196e180, {0xc0000ae140, 0x4, 0x4})
	github.com/v2fly/v2ray-core/v5/main/commands/test.go:54 +0x8b
github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
	github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x636
main.main()
	github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x285

```

## 如果 V2Ray 服务运行异常，请附上 journal 日志
```
× v2ray.service - V2Ray Service
     Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/v2ray.service.d
             └─10-donot_touch_single_conf.conf
     Active: failed (Result: exit-code) since Fri 2022-09-09 19:52:30 CST; 20min ago
       Docs: https://www.v2fly.org/
    Process: 5157 ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json -format jsonv5 (code=exited, status=203/EXEC)
   Main PID: 5157 (code=exited, status=203/EXEC)
        CPU: 2ms

9月 09 19:52:30 systemd[1]: Started V2Ray Service.
9月 09 19:52:30 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
9月 09 19:52:30 systemd[1]: v2ray.service: Failed with result 'exit-code'.
9月 09 19:52:30 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
9月 09 19:52:30 systemd[1]: Stopped V2Ray Service.
9月 09 19:52:30 systemd[1]: v2ray.service: Start request repeated too quickly.
9月 09 19:52:30 systemd[1]: v2ray.service: Failed with result 'exit-code'.
9月 09 19:52:30 systemd[1]: Failed to start V2Ray Service.

```

**Comment by 9Canon** [comment]
> ## 你正在使用哪个版本的 V2Ray？
> 
> V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
> ## 你的使用场景是什么？
> 
> 配置vlite出站
> ## 你看到的异常现象是什么？
> 
> 服务端正常 客户端vlite报错无法运行
> ## 你期待看到的正常表现是怎样的？
> 
> vlite正常运行
> ## 请附上你的配置
> 
> **客户端配置：**
> 
> ```js
> {
>   "log": {
>     "error": {
>       "level": "Debug",
>       "type": "Console"
>     },
>     "access": {
>       "type": "None"
>     }
>   },
>   "outbounds": [
>     {
>       "protocol": "freedom"
>     },
>     {
>       "protocol": "vliteu",
>       "settings": {
>         "address": "xxxxx",
>         "port": 8811,
>         "password": "pw",
>         "enableFec": true,
>         "enableStabilization": true,
>         "enableRenegotiation": true
>       },
>       "tag": "vlite"
>     }
>   ],
>   "inbounds": [
>     {
>       "protocol": "socks",
>       "settings": {
>         "udpEnabled": true,
>         "address": "127.0.0.1",
>         "packetEncoding": "Packet"
>       },
>       "port": 10808
>     }
>   ],
>   "router": {
>     "domainStrategy": "AsIs",
>     "rule": [
>       {
>         "tag": "vlite",
>         "domain": [
>           {
>             "type":"RootDomain",
>             "value": "packet-addr.v2fly.arpa"
>           }
>         ]
>       }
>     ]
>   }
> }
> ```
> 
> ## 请附上出错时软件输出的错误日志
> 
> **客户端错误日志：**
> 
> ```js
> V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
> A unified platform for anti-censorship.
> 2022/09/09 20:08:55 [Debug] app/log: Logger started
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xae2d92]
> 
> goroutine 1 [running]:
> github.com/v2fly/v2ray-core/v5/app/router.init.1.func2({0x12307a0, 0xc0001b1470}, {0xfe1280?, 0xc0001779e0})
> 	github.com/v2fly/v2ray-core/v5/app/router/router.go:242 +0x692
> github.com/v2fly/v2ray-core/v5/common.CreateObject({0x12307a0, 0xc0001b1470}, {0xfe1280, 0xc0001779e0})
> 	github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
> github.com/v2fly/v2ray-core/v5.CreateObjectWithEnvironment(0xc0004a4cc0?, {0xfe1280, 0xc0001779e0}, {0x1016e20?, 0xc0004a4de0?})
> 	github.com/v2fly/v2ray-core/v5/functions.go:25 +0x8c
> github.com/v2fly/v2ray-core/v5.initInstanceWithConfig(0xc0001dcfc0, 0xc0001778c0)
> 	github.com/v2fly/v2ray-core/v5/v2ray.go:203 +0x2e5
> github.com/v2fly/v2ray-core/v5.New(0x7ffd78f5d291?)
> 	github.com/v2fly/v2ray-core/v5/v2ray.go:167 +0x77
> github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
> 	github.com/v2fly/v2ray-core/v5/main/commands/run.go:205 +0x275
> github.com/v2fly/v2ray-core/v5/main/commands.executeRun(0x196e0c0, {0xc00003e200, 0x4, 0x4})
> 	github.com/v2fly/v2ray-core/v5/main/commands/run.go:82 +0xca
> github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
> 	github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x636
> main.main()
> 	github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x285
> ```
> 
> ## 请附上访问日志
> 
> 无输出
> ## 其它相关的配置文件（如 Nginx）和相关日志
> ## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出
> 
> ```
> ➜  v2ray v2ray test -config 2.json -format jsonv5                                                   
> V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
> A unified platform for anti-censorship.
> 2022/09/09 20:10:50 [Debug] app/log: Logger started
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xae2d92]
> 
> goroutine 1 [running]:
> github.com/v2fly/v2ray-core/v5/app/router.init.1.func2({0x12307a0, 0xc0001ed440}, {0xfe1280?, 0xc0001b3920})
> 	github.com/v2fly/v2ray-core/v5/app/router/router.go:242 +0x692
> github.com/v2fly/v2ray-core/v5/common.CreateObject({0x12307a0, 0xc0001ed440}, {0xfe1280, 0xc0001b3920})
> 	github.com/v2fly/v2ray-core/v5/common/type.go:34 +0x1b2
> github.com/v2fly/v2ray-core/v5.CreateObjectWithEnvironment(0xc0004a0c80?, {0xfe1280, 0xc0001b3920}, {0x1016e20?, 0xc0004a0da0?})
> 	github.com/v2fly/v2ray-core/v5/functions.go:25 +0x8c
> github.com/v2fly/v2ray-core/v5.initInstanceWithConfig(0xc0004eb170, 0xc0001b3800)
> 	github.com/v2fly/v2ray-core/v5/v2ray.go:203 +0x2e5
> github.com/v2fly/v2ray-core/v5.New(0x7ffc26e89291?)
> 	github.com/v2fly/v2ray-core/v5/v2ray.go:167 +0x77
> github.com/v2fly/v2ray-core/v5/main/commands.startV2Ray()
> 	github.com/v2fly/v2ray-core/v5/main/commands/run.go:205 +0x275
> github.com/v2fly/v2ray-core/v5/main/commands.executeTest(0x196e180, {0xc0000ae140, 0x4, 0x4})
> 	github.com/v2fly/v2ray-core/v5/main/commands/test.go:54 +0x8b
> github.com/v2fly/v2ray-core/v5/main/commands/base.Execute()
> 	github.com/v2fly/v2ray-core/v5/main/commands/base/execute.go:64 +0x636
> main.main()
> 	github.com/v2fly/v2ray-core/v5/main/main.go:16 +0x285
> ```
> 
> ## 如果 V2Ray 服务运行异常，请附上 journal 日志
> 
> ```
> × v2ray.service - V2Ray Service
>      Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
>     Drop-In: /etc/systemd/system/v2ray.service.d
>              └─10-donot_touch_single_conf.conf
>      Active: failed (Result: exit-code) since Fri 2022-09-09 19:52:30 CST; 20min ago
>        Docs: https://www.v2fly.org/
>     Process: 5157 ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json -format jsonv5 (code=exited, status=203/EXEC)
>    Main PID: 5157 (code=exited, status=203/EXEC)
>         CPU: 2ms
> 
> 9月 09 19:52:30 systemd[1]: Started V2Ray Service.
> 9月 09 19:52:30 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
> 9月 09 19:52:30 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> 9月 09 19:52:30 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
> 9月 09 19:52:30 systemd[1]: Stopped V2Ray Service.
> 9月 09 19:52:30 systemd[1]: v2ray.service: Start request repeated too quickly.
> 9月 09 19:52:30 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> 9月 09 19:52:30 systemd[1]: Failed to start V2Ray Service.
> ```

补充：应该是路由问题
删除配置中router部分后可以正常启动

**Comment by 9Canon** [comment]
```
{
    "$schema": "https://cdn.jsdelivr.net/gh/EHfive/v2ray-jsonschema/v5-config.schema.json",
    "inbounds": [
        {
            "tag": "socks",
            "listen": "127.0.0.1",
            "port": 1090,
            "protocol":"socks",
            "settings": {
                "udpEnabled": true
            }
        }
    ],
    "outbounds": [
        {
            "tag":"direct",
            "protocol":"freedom"
        }
    ],
    "router": {
        "domainStrategy": "AsIs",
        "rule":[
        ]
    }
}
```
如果使用这个配置，就可以正常运行
```
v2ray run -config v2raycopy.json -format jsonv5
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
2022/09/09 20:34:47 [Warning] V2Ray 5.1.0 started
```
但当我加入router配置时，就会报错
```
{
    "$schema": "https://cdn.jsdelivr.net/gh/EHfive/v2ray-jsonschema/v5-config.schema.json",
    "inbounds": [
        {
            "tag": "socks",
            "listen": "127.0.0.1",
            "port": 1090,
            "protocol":"socks",
            "settings": {
                "udpEnabled": true
            }
        }
    ],
    "outbounds": [
        {
            "tag":"direct",
            "protocol":"freedom"
        }
    ],
    "router": {
        "domainStrategy": "AsIs",
        "rule":[
            {
                "tag": "direct"
            }
        ]
    }
}
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xae2d92]
```

**Comment by 9Canon** [comment]
已解决，把router改成routing就行了

**Comment by EHfive** [comment]
勘误一下：

首先"router"是正确的，"routing"是文档错了。如果你用的是v2ray-jsonschema的补全那反而会是准确的，因为它是从v2ray代码生成的，而文档是手工维护的所以会有人类错误。。

已经提交 https://github.com/v2fly/v2fly-github-io/pull/339 修复此文档问题

> github.com/v2fly/v2ray-core/v5/app/router/router.go:242

你上面的错误其实是 https://github.com/v2fly/v2ray-core/blob/adb7871f82895c091c3d7f4c530cddf11aa5ebb9/app/router/router.go#L242 这行对 `v.Networks` 的空指针引用，已经被 https://github.com/v2fly/v2ray-core/commit/ddc6312c5d58cc1b232dcd167efbeedc7e0e89cc 修复了。

> 已解决，把router改成routing就行了

如上，这其实是因为"routing"是无效的所以没有触发错误。
