### ISSUE TITLE
使用v2ray无法上网，提示安全问题

### ISSUE THREAD

**Issue by stone-syy** [v2fly/v2ray-core#1980]
## 你正在使用哪个版本的 V2Ray？
5.1.0

客户端4.2.0V2rayN

## 你的使用场景是什么？
使用谷歌

## 你看到的异常现象是什么？
无法上网。连接被拒绝

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```
{
  "log": {
  "loglevel": "info",
  "access": "/var/log/v2ray/access.log",
  "error": "/var/log/v2ray/error.log"
  },

  "inbounds": [
    {
      "port": 10086, // 服务器监听端口
      "protocol": "vmess",    // 主传入协议
      "settings": {
        "clients": [
          {
            "id": "25ed076c-1ffc-dd85-8388-cc5461ab460b",  // 用户 ID，客户端与服务器必须相同
            "alterId": 64
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",  // 主传出协议
      "settings": {}
    }
  ]
}

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**
error.log日志：2022/09/13 11:35:34 [Info] [1396291505] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 116.169.1.190:20464 > common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.

```javascript
// 在这里附上服务器端日志

```
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 3.22.117.59:10086: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```
2022/09/13 11:34:28 116.169.1.190:25472 rejected  common/drain: common/drain: drained connection > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.
## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出
root@ip-172-31-29-54:/usr/local/bin# ./v2ray test /usr/local/etc/v2ray/config.json
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
2022/09/13 11:46:04 Using config from STDIN

**Comment by stone-syy** [comment]
> 同有问题。客户端及服务端修改alterID为0后，客户端及服务端查看日志均无报错。但客户端无法正常访问。

我是之前可以，这几天突然不行的，不知道怎么回事？你把alterID改为64试试呢

**Comment by lychichem** [comment]
v2rayn直到5.35才正式支持5.1.0内核，你该升级客户端了

**Comment by stone-syy** [comment]
> v2rayn直到5.35才正式支持5.1.0内核，你该升级客户端了
我之前是正常使用，不行以后我升级了服务端，现在我升级客户端试试，thanks

**Comment by stone-syy** [comment]
我将客户端升级为5.35依然提示：app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 116.169.1.190:48291 > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.
这是哪里的问题呢

**Comment by lychichem** [comment]
> 我将客户端升级为5.35依然提示：app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 116.169.1.190:48291 > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.
> 这是哪里的问题呢

服务端alterid的问题，不使用aead的方法（也就是alterid不为0）已经过时了，你可以搜一下，需要你更改服务器和客户端配置

**Comment by stone-syy** [comment]
问题已解决：使用env v2ray.vmess.aead.forced=false /usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json &命令启动即可

**Comment by 46EULER** [comment]
已解决。猜测是服务器端错误地配置了参数”level”：1。删除该参数，并同时添加“security”：“tls”后恢复正常。（客户端喝服务器端君将alterid显式设置为0）
