### ISSUE TITLE
5.10的安装脚本install-release.sh似乎有问题

### ISSUE THREAD

**Issue by 33lyl** [v2fly/v2ray-core#1981]
安装脚本似乎有问题
修改了10-donot_touch_single_conf.conf文件后
如果再次执行install-release.sh安装
10-donot_touch_single_conf.conf中的v2ray  run -config会被改回去成v2ray    -config

**Comment by digglife** [comment]
Ref: https://github.com/v2fly/fhs-install-v2ray/issues/243

**Comment by 33lyl** [comment]
> Ref: [v2fly/fhs-install-v2ray#243](https://github.com/v2fly/fhs-install-v2ray/issues/243)

目前我自己写了一个service来调用，不用原来的自带的，自更新会替换掉

**Comment by digglife** [comment]
> 目前我自己写了一个service来调用，不用原来的自带的，自更新会替换掉

是啊，你说的这个问题就是 https://github.com/v2fly/fhs-install-v2ray/issues/243 里讨论的，是个已知的问题，而且已经有人提交了 PR 修复，只是没合并。

**Comment by 33lyl** [comment]
> > 目前我自己写了一个service来调用，不用原来的自带的，自更新会替换掉
> 
> 是啊，你说的这个问题就是 [v2fly/fhs-install-v2ray#243](https://github.com/v2fly/fhs-install-v2ray/issues/243) 里讨论的，是个已知的问题，而且已经有人提交了 PR 修复，只是没合并。

谢谢，目前新版本估计还有一些bug
