### ISSUE TITLE
Help content missing in Windows binary

### ISSUE THREAD

**Issue by Maxwellads** [v2fly/v2ray-core#1985]
## What version of V2Ray are you using?
5.1.0 Preview

## What problems have you encountered?

Usage/Help content is missing in Windows binary.

## Please attach error logs here

```
C:\Users\C\Desktop\V2>v2ray.exe -c config.json
flag provided but not defined: -c
Usage of v2ray.exe:

C:\Users\C\Desktop\V2>v2ray.exe --help
Usage of v2ray.exe:

```

UPDATE: It seems that all flags are somehow not defined, which makes the binary unoperationable.

**Comment by skozharinov** [comment]
Version 5 has a new CLI interface, check `v2ray.exe help` (without dashes).
Don't know why devs have left --help flag and haven't added help content there.

**Comment by Maxwellads** [comment]
> Version 5 has a new CLI interface, check `v2ray.exe help` (without dashes). Don't know why devs have left --help flag and haven't added help content there.

Thanks, I get how it works now.
(Who the heck will know that I should type "help" install of "--help" in a linux program ahhhhhhh)
