### ISSUE TITLE
v2ray 4.27.5 - 5.1.0 crashes on windows 10 arm 32

### ISSUE THREAD

**Issue by hamed7ir** [v2fly/v2ray-core#2005]
## What version of V2Ray are you using?

5.1.0

## What's your scenario of using V2Ray?

Hi 

thank you for your great work .
i just using v2ray to bypass censorship on my surface 2 tablet running windows 10 arm32

## What problems have you encountered?

all v2ray version up to 4.27.5 crashes on my tablet
the last and stable version is 4.27.4 that works perfect on my tablet

## What's your expectation?

as you compile this amazing app for arm 32 , its really good that the latest and most secure version of v2ray works.
i just wanted to share my experience with you and inform about this problem however 4.27.4 is fine for me

## Please attach your configuration here
 **config file is ok cause it works on my pc with last version of v2ray and also works fine with 4.27.4 version** 

**Client error log:**

```javascript
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 windows/arm)
A unified platform for anti-censorship.
2022/09/22 11:50:24 Using config from env:  C:\Users\hamed\.config\v2raya\config.json
fatal error: fault
[signal 0xc000001d code=0x0 addr=0x0 pc=0x12fb2fd]

goroutine 1 [running]:
runtime.throw({0x1d1d34f, 0x5})
        runtime/panic.go:1047 +0x4c fp=0x13947498 sp=0x13947484 pc=0x1170584
runtime.sigpanic()
        runtime/signal_windows.go:273 +0x1bc fp=0x139474bc sp=0x13947498 pc=0x1188400
google.golang.org/protobuf/internal/impl.(*listReflect).protoUnwrap(0x2c)
        google.golang.org/protobuf@v1.28.1/internal/impl/convert_list.go:140 +0x49 fp=0x139474dc sp=0x139474c0 pc=0x12fb2fd
runtime: g 1: unexpected return pc for google.golang.org/protobuf/internal/impl.consumeMessageSliceInfo called from 0x0
stack: frame={sp:0x139474dc, fp:0x13947534} stack=[0x13938000,0x13948000)
0x1394745c:  0x00000000  0xc000001d  0x01170868 <runtime.fatalthrow+0x00000064>  0x01170584 <runtime.throw+0x0000004c>
0x1394746c:  0x13947474  0x13048000  0x01170880 <runtime.fatalthrow.func1+0x00000000>  0x13048000
0x1394747c:  0x01170584 <runtime.throw+0x0000004c>  0x13947484  0x01188400 <runtime.sigpanic+0x000001bc>  0x00000002
0x1394748c:  0x01170590 <runtime.throw.func1+0x00000000>  0x01d1d34f  0x00000005  0x012fb2fd <google.golang.org/protobuf/internal/impl.(*listReflect).protoUnwrap+0x00000049>
0x1394749c:  0x01d1d34f  0x00000005  0x00000000  0x00000000
```

**Comment by AkinoKaede** [comment]
Sorry, I do not have any devices to test it. However, I think it may be a bug of upstream.

**Comment by hamed7ir** [comment]
> Sorry, I do not have any devices to test it. However, I think it may be a bug of upstream.
yeah these days nobody use surface rt :D you can run w10 arm 32 on qemu but i dont think worth your time.
sometimes if i insist to run newer versions rapidly by double clicking on that, it will actually run and works but then start browsing and routes get more and more it crashes just like before.
