### ISSUE TITLE
unix domain socket 监听，运行一段时间监听sock文件消失

### ISSUE THREAD

**Issue by Remonli** [v2fly/v2ray-core#2007]
uds监听在/run/shm/v2ray.sock,启动正常启动，log如下,同时生成两个文件/run/shm/v2ray.sock , /run/shm/v2ray.sock.lock
```
2022/09/25 00:25:42 [Debug] app/log: Logger started
2022/09/25 00:25:42 [Debug] app/proxyman/inbound: creating unix domain socket worker on /run/shm/v2ray.sock
```
运行一段时间(几十分钟或几个小时)后，/run/shm/目录下的两个文件消失，且没有留下任何log。

文件消失后，大部分时间代理工作正常，有几率断开无法联网。

以上测试了5.1.0 preview 和 4.45.2 , 结果相同。

**Comment by unknowndevQwQ** [comment]
> uds监听在/run/shm/v2ray.sock,启动正常启动，log如下,同时生成两个文件/run/shm/v2ray.sock , /run/shm/v2ray.sock.lock
> 
> ```
> 2022/09/25 00:25:42 [Debug] app/log: Logger started
> 2022/09/25 00:25:42 [Debug] app/proxyman/inbound: creating unix domain socket worker on /run/shm/v2ray.sock
> ```
> 
> 运行一段时间(几十分钟或几个小时)后，/run/shm/目录下的两个文件消失，且没有留下任何log。
> 
> 文件消失后，大部分时间代理工作正常，有几率断开无法联网。
> 
> 以上测试了5.1.0 preview 和 4.45.2 , 结果相同。

我建议使用 inotify-tools 和/或 audit 子系统监控 v2ray 的 socket 文件
额外一问：你在容器中运行 v2ray 吗？

**Comment by Remonli** [comment]
不是在容器中运行的，是debian testing，我怀疑是debian testing的问题，因为我换了xray测试一下，也是一样的问题，不过现在手头没有机器跑debian stable 或者Ubuntu，不然可以确定是不是debian testing的问题。

**Comment by unknowndevQwQ** [comment]
> 不是在容器中运行的，是debian testing，我怀疑是debian testing的问题，因为我换了xray测试一下，也是一样的问题，不过现在手头没有机器跑debian stable 或者Ubuntu，不然可以确定是不是debian testing的问题。

给下 `ls -ahl /run` 的输出
监控，然后慢慢看

**Comment by Remonli** [comment]
试了一下 inotify-tools 监控，但是只有创建文件的时候有记录
```
CREATE-/run/shm/v2ray.sock.lock-22/10/06-14:36
CREATE-/run/shm/v2ray.sock-22/10/06-14:36
```
进程启动的时候:
```
user@server[2:45:51]:~$ll /run/shm/
total 0
srwxr-xr-x 1 user user 0 Oct  6 14:26 v2ray.sock
-rw-r--r-- 1 user user 0 Oct  6 14:26 v2ray.sock.lock
```
文件丢失后:
```
user@server[2:47:04]:~$ll /run/shm/
total 0
```
但是之前汇报bug时是所有的机器都这样，但今天测，就只有一台机器有问题，所以我怀疑还是跟我机器环境有关系。
另外/run 目录如下:
```
user@server[2:47:07]:~$ll /run
total 16K
-rw-------  1 root root    0 Oct  6 18:56 agetty.reload
drwxr-xr-x  2 root root   80 Oct  6 18:56 console-setup
drwxr-xr-x  3 root root   60 Oct  6 18:56 credentials
-rw-r--r--  1 root root    4 Oct  6 18:56 crond.pid
----------  1 root root    0 Oct  6 18:56 crond.reboot
drwxr-xr-x  3 root root   80 Oct  6 18:56 dbus
prw-------  1 root root    0 Oct  6 18:56 initctl
drwx------  2 root root   80 Oct  6 18:56 initramfs
drwxrwxrwt  3 root root   60 Oct  6 18:56 lock
drwxr-xr-x  3 root root   60 Oct  6 18:56 log
-rw-r--r--  1 root root   91 Oct  6 22:44 motd.dynamic
drwxr-xr-x  2 root root   40 Oct  6 18:56 mount
drwxr-xr-x  2 root root  120 Oct  6 18:56 network
drwxrwxrwt  2 root utmp   40 Oct  6 18:56 screen
drwxr-xr-x  2 root root   40 Oct  6 18:56 sendsigs.omit.d
lrwxrwxrwx  1 root root    8 Oct  6 18:56 shm -> /dev/shm
drwxr-xr-x  2 root root   40 Oct  6 18:56 sshd
-rw-r--r--  1 root root    4 Oct  6 18:56 sshd.pid
drwx--x--x  2 root root   40 Oct  6 18:56 sudo
drwxr-xr-x 21 root root  500 Oct  6 18:56 systemd
drwxr-xr-x  2 root root   60 Oct  6 18:56 tmpfiles.d
drwxr-xr-x  6 root root  140 Oct  6 18:56 udev
drwxr-xr-x  3 root root   60 Oct  6 22:44 user
-rw-rw-r--  1 root utmp 1.9K Oct  6 22:44 utmp
```

**Comment by unknowndevQwQ** [comment]
> 试了一下 inotify-tools 监控，但是只有创建文件的时候有记录
> 
> ```
> CREATE-/run/shm/v2ray.sock.lock-22/10/06-14:36
> CREATE-/run/shm/v2ray.sock-22/10/06-14:36
> ```
> 
> 进程启动的时候:
> 
> ```
> user@server[2:45:51]:~$ll /run/shm/
> total 0
> srwxr-xr-x 1 user user 0 Oct  6 14:26 v2ray.sock
> -rw-r--r-- 1 user user 0 Oct  6 14:26 v2ray.sock.lock
> ```
> 
> 文件丢失后:
> 
> ```
> user@server[2:47:04]:~$ll /run/shm/
> total 0
> ```
> 
> 但是之前汇报bug时是所有的机器都这样，但今天测，就只有一台机器有问题，所以我怀疑还是跟我机器环境有关系。 另外/run 目录如下:
> 
> ```
> user@server[2:47:07]:~$ll /run
> total 16K
> -rw-------  1 root root    0 Oct  6 18:56 agetty.reload
> drwxr-xr-x  2 root root   80 Oct  6 18:56 console-setup
> drwxr-xr-x  3 root root   60 Oct  6 18:56 credentials
> -rw-r--r--  1 root root    4 Oct  6 18:56 crond.pid
> ----------  1 root root    0 Oct  6 18:56 crond.reboot
> drwxr-xr-x  3 root root   80 Oct  6 18:56 dbus
> prw-------  1 root root    0 Oct  6 18:56 initctl
> drwx------  2 root root   80 Oct  6 18:56 initramfs
> drwxrwxrwt  3 root root   60 Oct  6 18:56 lock
> drwxr-xr-x  3 root root   60 Oct  6 18:56 log
> -rw-r--r--  1 root root   91 Oct  6 22:44 motd.dynamic
> drwxr-xr-x  2 root root   40 Oct  6 18:56 mount
> drwxr-xr-x  2 root root  120 Oct  6 18:56 network
> drwxrwxrwt  2 root utmp   40 Oct  6 18:56 screen
> drwxr-xr-x  2 root root   40 Oct  6 18:56 sendsigs.omit.d
> lrwxrwxrwx  1 root root    8 Oct  6 18:56 shm -> /dev/shm
> drwxr-xr-x  2 root root   40 Oct  6 18:56 sshd
> -rw-r--r--  1 root root    4 Oct  6 18:56 sshd.pid
> drwx--x--x  2 root root   40 Oct  6 18:56 sudo
> drwxr-xr-x 21 root root  500 Oct  6 18:56 systemd
> drwxr-xr-x  2 root root   60 Oct  6 18:56 tmpfiles.d
> drwxr-xr-x  6 root root  140 Oct  6 18:56 udev
> drwxr-xr-x  3 root root   60 Oct  6 22:44 user
> -rw-rw-r--  1 root utmp 1.9K Oct  6 22:44 utmp
> ```

使用 audit 子系统或 systemtap/sysdig 监听 socket 文件操作

**Comment by Remonli** [comment]
audit 监控了半天，socks文件老老实实没有消失，算了不管他了，我换回ip端口监听了。

```
user@server[10:03:33]:~#ll /run/shm/
total 0
srwxr-xr-x 1 liz liz 0 Oct  7 15:17 v2ray.sock
-rw-r--r-- 1 liz liz 0 Oct  7 15:17 v2ray.sock.lock
```
```
time->Fri Oct  7 5:17:26 2022
type=PROCTITLE msg=audit(1665127046.671:125): proctitle=2F686F6D652F6C697A2F76327261792F76327261790072756E002D636F6E666967002F686F6D652F6C697A2F76327261792F636F6E6669672E6A736F6E
type=PATH msg=audit(1665127046.671:125): item=1 name="/run/shm/v2ray.sock" inode=5 dev=00:18 mode=0140755 ouid=1000 ogid=1000 rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1665127046.671:125): item=0 name="/run/shm/" inode=1 dev=00:18 mode=041777 ouid=0 ogid=0 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1665127046.671:125): cwd="/"
type=SOCKADDR msg=audit(1665127046.671:125): saddr=01002F72756E2F73686D2F76327261792E736F636B00
type=SYSCALL msg=audit(1665127046.671:125): arch=c000003e syscall=49 success=yes exit=0 a0=8 a1=c006cfb990 a2=16 a3=0 items=2 ppid=1 pid=607 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="v2ray" exe="/home/user/v2ray/v2ray" subj=unconfined key="v2ray"
```

**Comment by unknowndevQwQ** [comment]
> audit 监控了半天，socks文件老老实实没有消失，算了不管他了，我换回ip端口监听了。
> 
> ```
> user@server[10:03:33]:~#ll /run/shm/
> total 0
> srwxr-xr-x 1 liz liz 0 Oct  7 15:17 v2ray.sock
> -rw-r--r-- 1 liz liz 0 Oct  7 15:17 v2ray.sock.lock
> ```
> 
> ```
> time->Fri Oct  7 5:17:26 2022
> type=PROCTITLE msg=audit(1665127046.671:125): proctitle=2F686F6D652F6C697A2F76327261792F76327261790072756E002D636F6E666967002F686F6D652F6C697A2F76327261792F636F6E6669672E6A736F6E
> type=PATH msg=audit(1665127046.671:125): item=1 name="/run/shm/v2ray.sock" inode=5 dev=00:18 mode=0140755 ouid=1000 ogid=1000 rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
> type=PATH msg=audit(1665127046.671:125): item=0 name="/run/shm/" inode=1 dev=00:18 mode=041777 ouid=0 ogid=0 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
> type=CWD msg=audit(1665127046.671:125): cwd="/"
> type=SOCKADDR msg=audit(1665127046.671:125): saddr=01002F72756E2F73686D2F76327261792E736F636B00
> type=SYSCALL msg=audit(1665127046.671:125): arch=c000003e syscall=49 success=yes exit=0 a0=8 a1=c006cfb990 a2=16 a3=0 items=2 ppid=1 pid=607 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="v2ray" exe="/home/user/v2ray/v2ray" subj=unconfined key="v2ray"
> ```

最好的解决办法是不要用 /{dev,run}/shm，那玩意不是拿来放 socket 文件的

**Comment by Remonli** [comment]
没办法才放在那里的，放在/tmp 的话，caddy 转发过来有权限问题,找不到socket文件(即使两个运行在一个用户下)，又不想放在v2ray目录里面，不好看。

**Comment by unknowndevQwQ** [comment]
> 没办法才放在那里的，放在/tmp 的话，caddy 转发过来有权限问题,找不到socket文件(即使两个运行在一个用户下)，又不想放在v2ray目录里面，不好看。

建议使用 tmpfiles.d 去设置 v2ray 目录

**Comment by Remonli** [comment]
@unknowndevQwQ 确实有效，用tmpfiles.d 设置了放在/run/v2ray , 跑了十多个小时，没有再出问题。所以看起来就是/dev/shm 这个目录的策略，大概他会定期清理shm目录下面的文件。

另外你知道为什么放在/tmp下面会有权限问题么, Caddy为啥找不到/tmp/v2ray.sock ？ 我明明记得以前mysql 和php-fpm 是可以用
socket文件通信，并且socket文件就放在/tmp下面的。

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ 确实有效，用tmpfiles.d 设置了放在/run/v2ray , 跑了十多个小时，没有再出问题。所以看起来就是/dev/shm 这个目录的策略，大概他会定期清理shm目录下面的文件。
> 
> 另外你知道为什么放在/tmp下面会有权限问题么, Caddy为啥找不到/tmp/v2ray.sock ？ 我明明记得以前mysql 和php-fpm 是可以用 socket文件通信，并且socket文件就放在/tmp下面的。

如果 caddy 是直接通过 systemd 启动的，请检查对应的 .service 文件配置

**Comment by Remonli** [comment]
我看了一下，是下面这个设置的问题，service 文件是从官方抄回来的，被官方坑了。
感谢，感谢！
```
PrivateTmp=true
```
```
https://github.com/caddyserver/dist/blob/master/init/caddy.service
```

**Comment by Remonli** [comment]
事实上，/etc/systemd/logind.conf 中，有一个选项叫做 RemoveIPC。如果它被设置为 yes（在部分发行版的默认配置中就是 yes），那么当一个普通用户（UID >= 1000）的所有登录会话都结束并完全注销时，系统会自动销毁该用户拥有的所有 IPC（进程间通信）对象。

所以要么把这个选项改为no，要么不要放在/dev/shm里。
