### ISSUE TITLE
客户端文件不适合当前设备。

### ISSUE THREAD

**Issue by Paullaw102** [v2fly/v2ray-core#2019]
PVE虚拟计openwrt使用Passwall的科学上网，进行组件更新的时候，V2Ray的版本4.45.2升级到5.1.0的时候，提示客户端文件不适合当前设备，一直没发解决该问题。

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by ZiXia1** [comment]
请尝试将Passwall更新到最新版
