### ISSUE TITLE
v2ray与kvm存在网络冲突？

### ISSUE THREAD

**Issue by RuiBaiXYZ** [v2fly/v2ray-core#2021]
v2ray与kvm存在网络冲突

# uname -r
5.14.0-70.26.1.el9_0.x86_64

# v2ray --version
V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
A unified platform for anti-censorship.

KVM
qemu-kvm.x86_64 17:6.2.0-11.el9_0.5

故障现象：
v2ray启动后，KVM无法连接网络；
v2ray关闭后，KVM可以正常连接网络。

请确认是否存在冲突或者配置信息上需要有特别的注意点。

谢谢～

**Comment by AkinoKaede** [comment]
V2Ray just is a proxy software on Layer 7.

**Comment by RuiBaiXYZ** [comment]
en ... This is a little strange .
Does v2ray use some kernel functions or some ports conflict with the default KVM.

**Comment by RuiBaiXYZ** [comment]
> V2Ray just is a proxy software on Layer 7.

I'm so sorry.
After checking logs, this is something wrong with V2RayA  (v2raya-1.5.9.1698.1-1.x86_64).
Thanks for your reply
