### ISSUE TITLE
v2ray 获取帮助信息的参数不统一

### ISSUE THREAD

**Issue by unknowndevQwQ** [v2fly/v2ray-core#2029]
## 你正在使用哪个版本的 V2Ray？
v2ray 5.1.0

## 你的使用场景是什么？

包括但不限于 `v2ray -h`、`v2ray --help`、`v2ray --version`、`v2ray verify help`、`v2ray verify --help`、`v2ray convert help`、`v2ray convert --help`

## 你看到的异常现象是什么？
`v2ray --help` 或 `v2ray -h` 输出 `Usage of v2ray:\n`

`v2ray --version` 或 `v2ray -v` 输出：
```
flag provided but not defined: -v
Usage of v2ray:
```

`v2ray verify help` 输出 `empty signature path.`
`v2ray verify --help` 输出：
```
usage: v2ray verify [--sig=sig-file] file
Run 'v2ray help verify' for details.
```

`v2ray convert help`输出：`failed to merge: infra/conf/mergers: tried all mergers but failed for: help`
`v2ray convert --help`输出：
```
usage: v2ray convert [c1.json] [<url>.json] [dir1] ...
Run 'v2ray help convert' for details.
```

## 你期待看到的正常表现是怎样的？
-h/--help 行为与 help 一致
-v/--version 行为与 version 一致

在其他子命令的参数中含有 -h/--help/help 建议输出比较简短的帮助信息

**Comment by AkinoKaede** [comment]
You should use `v2ray help <subcommand>` to get help details.

**Comment by unknowndevQwQ** [comment]
> You should use `v2ray help <subcommand>` to get help details.

如果只想看简略信息的话？

**Comment by heimoshuiyu** [comment]
I hope v2ray can print the basic help message like

```A unified platform for anti-censorship.

Usage:

        v2ray <command> [arguments]

The commands are:

        run           run V2Ray with config
        api           call V2Ray API
        convert       convert config files
        test          test config files
        tls           TLS tools
        uuid          generate new UUID
        verify        verify if a binary is officially signed
        version       print V2Ray version

Use "v2ray help <command>" for more information about a command.

Additional help topics:

        config-merge  config merge logic
        format-loader config formats and loading

Use "v2ray help <topic>" for more information about that topic.
```

when I type something wrong such as `-h` or `-v` or `-version` or what ever starts with `-`

instead of an empty usage message

```
flag provided but not defined: -v
Usage of v2ray:
```

**Comment by heimoshuiyu** [comment]
push :)

**Comment by unknowndevQwQ** [comment]
@AkinoKaede 5.7.0 也没有修，这个问题不应该在现在被关闭

**Comment by unknowndevQwQ** [comment]
5.10.1 仍未修复

**Comment by heimoshuiyu** [comment]
才注意到 PR 被关闭了... 重新开了一个

**Comment by unknowndevQwQ** [comment]
fixed in #2761, close
