### ISSUE TITLE
v5 config的Trojan无法配置`fallbacks`

### ISSUE THREAD

**Issue by CXwudi** [v2fly/v2ray-core#2033]
## 你正在使用哪个版本的 V2Ray？

`v5.1.0`

## 你看到的异常现象是什么？

v5版配置无法给Trojan设置Fallback

## 你期待看到的正常表现是怎样的？

v5版配置可以给Trojan设置Fallback,  
如果可以的话, vless也可以支持

## 其他

创建此issue只是为了把telegram里一段发现的[配置bug](https://t.me/v2fly_chat/304583)移到GitHub issue上, 仅此而已

**Comment by xfoxfu** [comment]
实际上只是文档没有写出。经过测试以下的配置是可用的。

```json
    {
      "port": 443,
      "protocol": "trojan",
      "settings": {
        "clients": [ ... ],
        "fallbacks": [
          {
            "dest": "example.com"
          }
        ]
      },
      "streamSettings": { ... }
    }
```

**Comment by CXwudi** [comment]
可以, 有时间我也试一试, 同时希望这个配置可以写进文档

**Comment by pengyao** [comment]
@xfoxfu v5的用户使用的是[`users`](https://github.com/v2fly/v2ray-core/blob/master/proxy/trojan/simplified/config.go#L16)，和v4的`clients`不同，且目前v5当前配置并不支持`fallbacks`
