### ISSUE TITLE
基本是因为深度包检测，发现TLS over TLS，导致的近期的大规模封禁。未来能否解决DPI侦测

### ISSUE THREAD

**Issue by tez65** [v2fly/v2ray-core#2035]
几个月前被短期派到大型机关办公区，自己笔记本，用v2ray、trojan等协议都试过，均在几秒钟后就被识别、断网。
然后跟他们网管聊了一下，用的奇安信 网神防火墙，所有协议后台均显示为C&C隐蔽流量。估计是通过流量分析、深度包检测，就可以快速发现所有TLS over TLS流量。
当然主干网比办公区流量大的多，但gfw可以通过抓取部分流量进行分析，长时间点多次发现TLS over TLS，就会封ip，所以近期用非443端口的也被封了。之前境内中转机大规模被封也一样。
希望v2ray未来能有更好的流量混淆方法

**Comment by ChainZeaxion** [comment]
> 几个月前被短期派到大型机关办公区，自己笔记本，用v2ray、trojan等协议都试过，均在几秒钟后就被识别、断网。 然后跟他们网管聊了一下，用的奇安信 网神防火墙 ( [www.qianxin.com](http://www.qianxin.com) ) ，所有协议后台均显示为C&C隐蔽流量。估计是通过流量分析、深度包检测，就可以快速发现所有TLS over TLS流量。 当然主干网比办公区流量大的多，但gfw可以通过抓取部分流量进行分析，长时间点多次发现TLS over TLS，就会封ip，所以近期用非443端口的也被封了。之前境内中转机大规模被封也一样。 希望v2ray未来能有更好的流量混淆方法

首先，你不能老是拿着非标端口跑数据，而且这数据还是加密的
其次，即使非标端口跑加密数据也不是不可以，用来临时调测是肯定允许的
但是，你的使用习惯上面，注定了这流量就不正常，而且对外看起来又是加密，更不合规

所以，你的流量，从外面看起来，首先要是个正常流量，比如某种正常对外的服务
然后，你这种服务，它得有相对应的特征，而且不能是单一特征，最好是多种特征用以支撑你这种流量看起来是正常服务的正常使用习惯产生的流量
最后才是，你这个流量的使用习惯上，肯定不能长时间持续不断的大流量，也不能长时间不断的小流量
不能长时间单链接跑，也不能长时间固定多连接在跑

举个栗子，比如伪装成提供某种文件下载的服务，例如提供一个centos的iso镜像供人下载
那么从内几个或者十数个，数十个，肯定不能是几百上千，在比如一天内都去连你这个跑流量
那么仅你自己几个设备在连，流量有高有低，连接数有多有少，对外抽样拆包，这流量有那么几处能支撑你这是在拉文件
即使列入二查，进行主动探测，也会得到一个正常的提供服务的站点该反馈的信息
包括对你这个特定链接，比如 xxx.com/download/centos7-minimual.iso文件，也会发起侦测，会得到下载回馈
那么你这个提供的服务，就会被认可是正常流量，然后短时间内就不会红线

如果，你对外提供是tls加密过的数据，所有内容解包难度增加，可能会无论你是干啥的数据，包括主动探测即使得到正常回馈
只要你这流量异常，还是会被鈤，毕竟大厂的加密流量，都是一段一段起起伏伏的
能提供长时间大流量的，都有可以不加密进行获取的（毕竟大多数大流量除了视频，就是拉文件）

所以，你只要选择一种服务进行伪装，然后伪装后的流量，和你的使用行为习惯高度匹配，就不太会被针对
这类型伪装有、对外认可的文件下载服务、对外认可的网速测试、对外认可的大厂cdn、对外认可的媒体发布服务、对外认可的网页内容服务

如果能将所有流量截取，再拆解包，以甄别你是否红线，那么如此巨量的工程，所需的巨量算力，用来干如此鸡毛蒜皮的事
可行是可行，但就目前而言理论上还并没有，所以更多的还是从流量特征，以及最小拆包解包匹配流量特征特性的角度，在分析流量内的数据 毕竟，别人口中的10，在你眼里可能是1，而能用的100，又有可能仅仅指代1
