### ISSUE TITLE
如何调整tcp socket上行发送缓存大小，目前版本在350ms高延迟情况下上传速度很慢

### ISSUE THREAD

**Issue by 1265578519** [v2fly/v2ray-core#2044]
如何调整tcp socket上行发送缓存大小，目前版本在350ms高延迟情况下上传速度很慢

文档中找不到相关的配置文件进行调整tcp socket
![ZVC}TB ENX@TIO4O)NCPJ45](https://user-images.githubusercontent.com/6442439/194334479-34df9966-943b-4aed-adf0-47189be43084.png)

其它软件例子
http://www.xlightftpd.com/cn/faq.htm
![image](https://user-images.githubusercontent.com/6442439/194335609-0cac0eb4-dbd7-4563-ba56-48dc7654f459.png)

同一服务器搭建ftp，改动socket缓存大小
默认值64K 实测300KB/s
修改32768K 实测12MB/s

同一服务器v2
实测700KB/s

**Comment by AkinoKaede** [comment]
<https://www.v2fly.org/v5/config/service/policy.html>

**Comment by 1265578519** [comment]
```
{
  "policy": {
      "levels": {
      "bufferSize": 32768
    }
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
```
我使用的gui客户端重启服务后会被替换成默认的config.json，，，我试试cmd命令方式启动去测试
![image](https://user-images.githubusercontent.com/6442439/194699944-2c58545c-c0c2-4d41-beab-1ee10511a273.png)
