### ISSUE TITLE
最近想从trojan转v2ray来但是trojan的特性没有完全实现

### ISSUE THREAD

**Issue by hudingwen** [v2fly/v2ray-core#2045]
由于长期使用数据库管理trojan用户，导致无法从gfw-trojan迁移到v2ray-trojan中来，希望能完善此特性。

**Comment by CXwudi** [comment]
同样还有#2033 这个问题

**Comment by puzzle9** [comment]
我想了想 v2本身没设计这个在数据库中管理用户的功能啊
不过他支持api手动处理这部分数据

**Comment by hudingwen** [comment]
> 

主要是多台服务器的时候不知道v2ray中是如何统一管理一个用户id能在所有服务器上进行识别?
当我在trojan-gfw中使用数据库管理时,我不需要考虑我的后端是java,go,C#,php语言时,
只要往数据库中标记用户或者添加用户id即可即在所有trojan服务上进行应用,以至于在迁移时我只需要迁移数据库和备份数据等操作
