### ISSUE TITLE
5.1.0版本需要正式版

### ISSUE THREAD

**Issue by jkle112** [v2fly/v2ray-core#2105]
Linux 系統，用的4.45.2版本的v2ray，但是實際升級5.1.0版本後，因缺少一個執行文件，應用顯示不支持，希望早日出正式版本。

**Comment by qiangliu8183** [comment]
继续坚守4

**Comment by kulongwangzhi85** [comment]
5.19.7-2-pve 
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
从发布到现在，正常运行。

**Comment by jkle112** [comment]
看到5.1.0版本有不少安全更新，很期待。
用的LINUX管理應用界面不支持測試版，正式版沒有問題，所以希望更新，然後安裝的方法不是用命令方式，而是全手動複製粘貼，運行時是系統的管理應用調用文件運行，測試版直接報錯。
