### ISSUE TITLE
v2ray vless 协议443端口共用问题

### ISSUE THREAD

**Issue by linxuankent** [v2fly/v2ray-core#211]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.28.2
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 通过 Socks/VMess 代理观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
在服务器上安装adguard home 并开启https ，无法与v2ray vless协议同时使用。 现在还是使用vmess +tls 的方式使用inbounds port 没有指定443。
4) 你期待看到的正确表现是怎样的？
使用vless协议 443端口能够公用
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    },
                    {
                        "path": "/linxuan", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/etc/v2ray/v2ray.crt", // 换成你的证书，绝对路径
                            "keyFile": "/usr/local/etc/v2ray/v2ray.key" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
        },
        {
            "port": 15462,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
                    "path": "/linxuan" // 必须换成自定义的 PATH，需要和上面的一致
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by rprx** [comment]
fallbacks 第二个子元素的 dest 应改为 15462

（我不了解 adguard）

**Comment by linxuankent** [comment]
> fallbacks第二个子元素的dest应替换15462
> 
> （我不了解adguard）
我的vmess配置
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "localhost"
        ],
        "tag": "dns_inbound"
    },
    "stats": {},
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [{
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "inboundTag": [
                    "tg-in"
                ],
                "outboundTag": "tg-out"
            }
        ]
    },
    "policy": {},
    "reverse": {

    },
    "inbounds": [{
            "port": 15315,
            "protocol": "vmess",
            "settings": {
                "clients": [{
                    "id": "",
                    "alterId": 64
                }],
                "detour": {
                    "to": "dynamicPort"
                }

            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "certificates": [{
                        "certificateFile": "/usr/local/etc/v2ray/v2ray.crt",
                        "keyFile": "/usr/local/etc/v2ray/v2ray.key"
                    }]
                }
            }

        },
        {
            "protocol": "vmess",
            "port": "3000-5000",
            "tag": "dynamicPort",
            "settings": {
                "default": {
                    "alterId": 64
                }
            },
            "allocate": {
                "strategy": "random",
                "concurrency": 10,
                "refresh": 3
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "certificates": [{
                        "certificateFile": "/usr/local/etc/v2ray/v2ray.crt",
                        "keyFile": "/usr/local/etc/v2ray/v2ray.key"
                    }]
                }
            }
        },

        {
            "port": 35152,
            "protocol": "mtproto",
            "settings": {
                "users": [{
                    "email": "love@v2ray.com",
                    "level": 0,
                    "secret": "4514dd37619afb6ff89123216d679065"
                }]
            },
            "tag": "tg-in",
            "streamSettings": {},
            "listen": "0.0.0.0"
        }

    ],
    "outbounds": [{
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "tag": "direct"
        },
        {
            "tag": "blocked",
            "protocol": "blackhole",
            "settings": {}
        },
        {
            "tag": "tg-out",
            "protocol": "mtproto",
            "settings": {}
        }

    ],

    "transport": {}
}
用netstat -tlnp|grep 443命令查询就不会出现443端口占用的情况，vless由于inbounds指定了443，查询就是443已经被占用，是不是应该考虑用nginx来解决。

**Comment by rprx** [comment]
没有明白你想实现什么。。。以及意义

**Comment by ruisiji** [comment]
我的理解是这样的：

他有三个域名： proxy.com, webserver1.com, webserver2.com

proxy.com 用来做代理的服务端连接地址，另外两个是 web 服务器。

按我目前理解的情况是 VLESS 里填写的是 proxy.com 的证书，这样他的两个 web server 就不知道怎么访问了。

当这三个域名的TLS证书并非同一个的时候，怎么使用 HTTPS 来访问这三个域名呢？

另外关于这个配置里的fallbacks我有个疑问： https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-XTLS-WHATEVER/config_server.json#L19-L38

```
                "fallbacks": [
                    {
                        "dest": 80 // 也可以回落到其它防探测的代理
                    },
                    {
                        "path": "/websocket", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    },
                    {
                        "path": "/vmesstcp", // 必须换成自定义的 PATH
                        "dest": 2345,
                        "xver": 1
                    },
                    {
                        "path": "/vmessws", // 必须换成自定义的 PATH
                        "dest": 3456,
                        "xver": 1
                    }
                ]
```

关于 vmess over tls 很好理解，前面放一个 nginx，当 host:port/path 是 vmess over tls时直接转发给 v2ray，否则转发给其他东西。因为Nginx可以为不同域名配置不同证书，所以很容易做到。

而 VLESS 的情况下，TLS证书是在 VLESS 里配置的，那么当流量是非 VLESS 流量时，怎样根据域名来向后转流量呢？

**Comment by rprx** [comment]
@ruisiji 

目前还不支持 SNI 分流，如果有这个需求，建议用 Nginx stream 来做。

**Comment by linxuankent** [comment]
> 我的理解是这样的：
> 
> 他有三个域名：proxy.com，webserver1.com，webserver2.com
> 
> proxy.com用于做代理的服务端连接地址，另外两个是web服务器。
> 
> 按我目前理解的情况是VLESS里填写的是proxy.com的证书，这样他的两个网络服务器就不知道怎么访问了。
> 
> 当这三个域名的TLS证书并非同一个的时候，怎么使用HTTPS来访问这三个域名呢？
> 
> 另外关于这个配置里的fallbacks我有个疑问：[https](https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-XTLS-WHATEVER/config_server.json#L19-L38) : [//github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-XTLS-WHATEVER/config_server.json#L19-L38](https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-XTLS-WHATEVER/config_server.json#L19-L38)
> 
> ```
>                 "fallbacks": [
>                     {
>                         "dest": 80 // 也可以回落到其它防探测的代理
>                     },
>                     {
>                         "path": "/websocket", // 必须换成自定义的 PATH
>                         "dest": 1234,
>                         "xver": 1
>                     },
>                     {
>                         "path": "/vmesstcp", // 必须换成自定义的 PATH
>                         "dest": 2345,
>                         "xver": 1
>                     },
>                     {
>                         "path": "/vmessws", // 必须换成自定义的 PATH
>                         "dest": 3456,
>                         "xver": 1
>                     }
>                 ]
> ```
> 
> 关于vmess over tls很好理解，前面放一个nginx，当host：port / path是vmess over tls时直接转发给v2ray，否则转发给其他东西。因为Nginx可以为不同域名配置不同证书，所以很容易做到。
> 
> 而 VLESS 的情况下，TLS证书是在 VLESS 里配置的，那么当流量是非 VLESS 流量时，怎样根据域名来向后转流量呢？

对是这样的

**Comment by wcg928** [comment]
https://www.youtube.com/watch?v=t4RvS8lBtJI&t=33s 这里有共享教程

**Comment by garypang13** [comment]
https://lhy.life/20200816-vless/
