### ISSUE TITLE
There is No V2ctl after installation

### ISSUE THREAD

**Issue by emobin** [v2fly/v2ray-core#2120]
## What version of V2Ray are you using?

5.1.0

## What problems have you encountered?

there is no `/usr/local/bin/v2ctl ` after innstallation

**Server configuration:**

Debian 10.5

**Comment by AkinoKaede** [comment]
It was removed in `V5` and you can use the same features in `v2ray`.

**Comment by emobin** [comment]
@AkinoKaede
 Would you please help me with this, where can I find the updated documentation ? or what is the equivalent command for this ?

`/usr/local/bin/v2ctl api --server=127.0.0.1:62789 StatsService.QueryStats ''`

**Comment by emobin** [comment]
for futures 

you can use this command 
`v2ray api stats --server=127.0.0.1:62789`

and these commands for getting more help

`v2ray help
v2ray help api
v2ray help api stats`

**Comment by whystopped** [comment]
@emobin Would you please help me with this, how to get specific stats like `StatsService.GetStats` ?

`v2ctl api --server=127.0.0.1:10085 StatsService.GetStats 'name: "inbound>>>statin>>>traffic>>>downlink" reset: false'`

**Comment by whystopped** [comment]
> @emobin Would you please help me with this, how to get specific stats like `StatsService.GetStats`?
> 
> `v2ctl api --server=127.0.0.1:10085 StatsService.GetStats 'name: "inbound>>>statin>>>traffic>>>downlink" reset: false'`

ok i figured it out, just `v2ray api stats --server=127.0.0.1:10085 StatsService.GetStats name: "inbound>>>statin>>>traffic>>>downlink"`
