### ISSUE TITLE
Maybe we could add `EnvironmentFile` at service?

### ISSUE THREAD

**Issue by FavorMylikes** [v2fly/v2ray-core#2125]
https://github.com/v2fly/v2ray-core/blob/9936afaa49b515fd5ecd9c8968f7c792bd67ae05/release/config/systemd/system/v2ray.service#L6-L13

```service
EnvironmentFile=PATH_TO_DEFAULT_FILE_PATH
```

And make those `env-variables` work through this file?

```service
V2RAY_VMESS_AEAD_FORCED=false
```

----

After checking the official code, I'm not sure there is any other file I need to change except [`install-release.sh`, `v2ray.service`m, `v2ray@.service`].

Maybe you could notice that?

**Comment by AkinoKaede** [comment]
I recommend everyone to use VMess AEAD.
