### ISSUE TITLE
vmess vless trojan trojan-go kcptun udp2raw ss sr 使用情况汇总，包含bug和各优势

### ISSUE THREAD

**Issue by ChainZeaxion** [v2fly/v2ray-core#2127]
第一，各主要底层协议，带宽效果
ss>=sr>trojan/trojan-go>=vless-websocket>vmess-websocket>vless-grpc>vmess-grpc
由于vless少了一层加密，某些运营商线路下，实际效果不如vmess，可能造成的原因是协议识别优先级降级
比如毛子线路到cn电信，vmess-grpc就比vless-grpc带宽跑的高

第二，各主要底层协议，延时效果
vless-grpc>=vmess-grpc>=trojan-mux/trojan-go-mux>vless-websocket-mux>=vmess-websocket-mux>ss/sr>vless-websocket>vmess-websocket
某些线路实际上，同样vless或者vmess，grpc虽然下载带宽跑不过websocket，但是上传带宽有效性比websocket好
grpc由于协议上的优势，默认自带mux，且这个mux效果特别好，不会存在其他协议开mux跑测速断流的情况
所以grpc在时延上有巨大的优势

第三，近期cn电信似乎开始对udp封端口
kcp跑udp数据，无论数据大小，似乎都会封端口
kcp外套udp2raw伪装tcp，也会导致udp2raw的伪装tcp握手失败，实际上数据双方是能收发，但是无法短时间建立握手
这个应该是墙对tcp的强制判定，识别不到tcp优先级，看不到tcp内的数据（你都把底层转给kcp做了几层加密还转成了udp也加密）

第四，经过对多处线路的测试，择优就trojan/trojan-go和grpc这俩
trojan/trojan-go这货，似乎在外面识别到的就是正常web流量，所以带宽跑的非常高，就是时延受协议影响，即便是加mux也斗不过grpc，尤其是开mux跑测速断流
grpc这货，经测试似乎本机发包性能上，还是不如trojan/trojan-go，所以影响带宽的有本机对grpc的优化和外部线路对grpc的优先级

最后，建议还是流量在外看起来就是web流量，这样跑大流量，似乎才不容易被鈤
毛子线路trojan/trojan-go跑满200M，vmess/vless-websocket跑180M，vmess-grpc跑130-160M，vless-grpc跑30-60M（绝对异常）
美西辣姬非cn2线路trojan/trojan-go跑300-500M，vmess/vless-websocket跑200-400M，vmess-grpc跑160-230M，vless-grpc跑60-110M（也是绝对异常）
按理说vless少了一层加密，实际使用效果应该比vmess更好，这绝对异常还是比较尴尬，感觉还是本机发包上有点问题，发包就弱
但实际上本机发包已经优化过，否则其他协议不可能跑那么快（并没有达到机器性能瓶颈，一半性能占用都没到，带宽依然上不去）

**Comment by vinograd-cyber** [comment]
总结的很到位，udp2raw从某大召开期间就不能正常过墙了，墙对加密tcp的过滤明显增强许多，必须要udp包且端口几分钟自动变一个才可以过墙，ipip grep隧道也不能正常作为下层的基础建设了，这次由于会议议题敏感度提升不少，墙的策略开的很严。
