### ISSUE TITLE
trojan的一个独有特征，可能被利用识别

### ISSUE THREAD

**Issue by Xpsia** [v2fly/v2ray-core#2128]
配置：略  
无论何种配置方案都 存在，我测试了trojan+tcp+nginx 、trojan+ws+nginx 、trojan+grpc+nginx等
希望大佬们提供解决方法或修正问题！！感恩！！

**当type为trojan时，我们只需在客户端配置IP、端口及域名后，密码有意输错，就会提示如下信息：**
如果不是tcp时(如：ws、grpc)，只需在客户端将其协议调成tcp也会出现一样的提示。

此网站无法提供安全连接www.google.com 发送的响应无效。
[尝试运行 Windows 网络诊断](javascript:diagnoseErrors())。
ERR_SSL_PROTOCOL_ERROR

**而默认情况下的提示应该如下：**

无法访问此网站www.google.com 的响应时间过长。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
[运行 Windows 网络诊断](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT

vmess系列没有此问题。

**Comment by Xpsia** [comment]
希望大佬们能解惑！授渔！！如果错误提示信息的确存在自定义，能帮助修复或回归自然，虽然现象过于表面，但还是过于容易被利用。感恩你的付出！！！

**Comment by thank243** [comment]
you configured fallback. But not correctly

**Comment by Xpsia** [comment]
> you configured fallback. But not correctly
只有tcp配置有回落，ws/grpc等时是没有的，但在客户端将协议调成tcp时（实际上应该是ws/grpc），在有意输错密码时还是会出现同样的提示。之前找了找代码，可惜本人实力有限，没有找到具体代码区，或许大神们看看能找出原因所在。

**Comment by thank243** [comment]
tested on vmess+tls?

**Comment by Xpsia** [comment]
vmess+tls不存在此问题，目前只发现trojan系列配置中只要客户端是tcp协议就会出现不同于平时正常访问的提示，这或许是因为开发者在回落及tcp配置时自定义了错误信息。
