### ISSUE TITLE
docker v2ray最新版容器无法启动切换老版本可以

### ISSUE THREAD

**Issue by onlineyh** [v2fly/v2ray-core#2147]
## 你正在使用哪个版本的 V2Ray？
docker 版本

v2fly/v2fly-core                                                   latest           2703c17dd5cf   2 days ago      41.4MB
teddysun/xray                                                      latest           e497037151f9   3 days ago      40.8MB
v2fly/v2fly-core                                                   <none>           0e75a60ce4c9   4 weeks ago     41.5MB

## 你的使用场景是什么？
使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频

## 你看到的异常现象是什么？

vim docker-compose.yml 
v2ray:
  image: v2fly/v2fly-core
  container_name: v2ray
  ports:
    - "23118:23118"
  volumes:
    - /data/yy23118:/etc/v2ray
  environment:
    - TZ=Asia/Shanghai
  restart: always
  #command: v2ray -config /etc/v2ray/config.json

docker-compose up -d
报错如下 我切换到老版本正常
v2fly/v2fly-core                                                   <none>           0e75a60ce4c9   4 weeks ago     41.5MB

v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command
Run 'v2ray help' for usage.
v2ray v2ray: unknown command

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by kslr** [comment]
调整了结构 https://github.com/v2fly/docker/blob/master/Dockerfile
```
command: v2ray run -c  /etc/v2ray/config.json
```

**Comment by smilence86** [comment]
官网上的文档可以更新了，还是这样：
```
sudo docker run -d --name v2ray -v /etc/v2ray:/etc/v2ray -p 8888:8888 v2fly/v2fly-core  v2ray -config=/etc/v2ray/config.json
```

应该是：
```
sudo docker run -d --name v2ray -v /etc/v2ray:/etc/v2ray -p 8888:8888 v2fly/v2fly-core  run -c /etc/v2ray/config.json
```

**Comment by kslr** [comment]
> 官网上的文档可以更新了，还是这样：
> 
> ```
> sudo docker run -d --name v2ray -v /etc/v2ray:/etc/v2ray -p 8888:8888 v2fly/v2fly-core  v2ray -config=/etc/v2ray/config.json
> ```
> 
> 应该是：
> 
> ```
> sudo docker run -d --name v2ray -v /etc/v2ray:/etc/v2ray -p 8888:8888 v2fly/v2fly-core  run -c /etc/v2ray/config.json
> ```

这个文档在哪里

**Comment by smilence86** [comment]
@kslr https://guide.v2fly.org/app/docker-deploy-v2ray.html
