### ISSUE TITLE
monitoring clients traffic but missing v2ctl

### ISSUE THREAD

**Issue by axone13** [v2fly/v2ray-core#2153]
Hi, I wanted to monitor clients traffic and noticed that this option is available in v2ctl API. But the problem is the v2ray won't install v2ctl and it seems missing. How should I fix the problem?

**Comment by kslr** [comment]
try ```v2ray api stats [--server=127.0.0.1:8080] [pattern]```

**Comment by axone13** [comment]
Thanks @kslr <3
Is there any documentation about it? Or just use the old v2ctl documentation?
