### ISSUE TITLE
Log can't disable.

### ISSUE THREAD

**Issue by Handsome1080P** [v2fly/v2ray-core#2163]
My config:

>  "log":{
        "loglevel":"none",
        "access":"/var/log/v2ray/access.log",
        "error":"/var/log/v2ray/error.log"
    }

Already set none to disable log.But in my log folder there is a access.log file logging all connections.
![123.png](https://s2.loli.net/2022/11/23/hob4DELjmRTNqxH.png)

**Comment by isold23** [comment]
把log配置删掉

**Comment by digglife** [comment]
`"access":"/dev/null"`

**Comment by Handsome1080P** [comment]
> `"access":"/dev/null"`

thx,I found a solution in issues.change"access":"path" to "access":"none".

**Comment by Handsome1080P** [comment]
>"log":{
        "loglevel":"none",
        "access":"none",
        "error":"none"
    },
