### ISSUE TITLE
Can't run in standard user (without admin right)

### ISSUE THREAD

**Issue by AliM1988** [v2fly/v2ray-core#2167]
I tested v2ray-core client on windows x64 as a standard user (without admin right). It didn't work. It stays on line "A unified platform for anti-censorship."

**Comment by cross-hello** [comment]
All right. Did you specify the listening port in Windows global proxy 
settings?

----------------------------------------

*From: *AliM1988 ***@***.***>
*To: *v2fly/v2ray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 24, 2022 13:00:17
*Subject: *[v2fly/v2ray-core] Can't run in standard user (without admin 
right) (Issue #2167)

**Comment by AliM1988** [comment]
Yes, I set http=127.0.0.1:10809 and socks=127.0.0.1:10808
