### ISSUE TITLE
vmess ID only for one user 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [v2fly/v2ray-core#2177]
Hello team, 

There are several problems in v2ray that i will say  : 

1: There is no clear documentation. 
2: we can not count the Client connected to Server.
3: we can not limit account only for one user for example i have created vmess on v2ray that provide id for every user but v2ray
does not have an option  to limit the account to connect to server, an ID per user.

Please help to solve this problems.

**Comment by luogeshibu** [comment]
I need to this!

**Comment by acheong08** [comment]
I also want to note that the `Config Reference` doesn't match with the JSON values. It would be nice for it to contain both the Go type name (and capitalized) and the matching JSON value.

Example:
In https://www.v2fly.org/en_US/v5/config/proxy/vmess.html#vmess-inbound, "users" should be `Users []json.RawMessage   'json:"clients"'`
