### ISSUE TITLE
Unknown warning 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [v2fly/v2ray-core#2193]
Hello again, 

 Unknown warning  : 

:36 [Warning] [2249323408] app/dispatcher: default route for tcp:clients4.google.com:443
:39 [Warning] [2021466783] app/dispatcher: default route for tcp:ssl.gstatic.com:443
:39 [Warning] [2642297211] app/dispatcher: default route for tcp:www.gstatic.com:443
:41 [Warning] [2382197771] app/dispatcher: default route for tcp:amp-api.sandbox.apple.com:443
:43 [Warning] [4140102433] app/dispatcher: default route for tcp:in.appcenter.ms:443
:45 [Warning] [2532665721] app/dispatcher: default route for tcp:ocsp2.apple.com:443
:06 [Warning] [2769168596] app/dispatcher: default route for udp:1.1.1.1:53
:07 [Warning] [744833179] app/dispatcher: default route for tcp:gsp-ssl.ls.apple.com:443
:10 [Warning] [2456778540] app/dispatcher: default route for tcp:www.googleapis.com:443
:10 [Warning] [1085146939] app/dispatcher: default route for tcp:www.googleapis.com:443

Another problem in this v2ray-core is CPU and RAM high usage on ubuntu server 20.4.

**Comment by AkinoKaede** [comment]
This is just to remind you that V2Ray uses the default route.

**Comment by Kein** [comment]
@AkinoKaede 
> This is just to remind you that V2Ray uses the default route.

Is there a way to disable it? it pollutes the log with useless info

**Comment by AkinoKaede** [comment]
> @AkinoKaede
> 
> > This is just to remind you that V2Ray uses the default route.
> 
> Is there a way to disable it? it pollutes the log with useless info

You can add a routing rule at the last of routing rules list to route all connections to default outbound.

**Comment by Kein** [comment]
> You can add a routing rule at the last of routing rules list to route all connections to default outbound.

You have an example? I dont have any routing rules, my client and server config literally just `inbounds` and `outbound`

**Comment by hldh214** [comment]
> > You can add a routing rule at the last of routing rules list to route all connections to default outbound.
> 
> You have an example? I dont have any routing rules, my client and server config literally just `inbounds` and `outbound`

```json
{
    "inbounds": [
        {
            "tag": "main-inbound",
            "port": 8964,
            "protocol": "vmess",
            "settings": {}
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "domainMatcher": "mph",
        "rules": [
            {
                "type": "field",
                "outboundTag": "direct",
                "inboundTag": [
                    "main-inbound"
                ]
            }
        ]
    }
}
```

I used the `inboundTag` here because a rule requires at least one effective field. If you prefer not to use the tag method, you can refer to the documentation for alternative methods, such as using `attrs` to always return true.
