### ISSUE TITLE
systemd由nobody更改为DynamicUser

### ISSUE THREAD

**Issue by uselibrary** [v2fly/v2ray-core#2197]
## 你正在使用哪个版本的 V2Ray？

v5.1.0

## 你的使用场景是什么？

Linux服务器后端

## 你看到的异常现象是什么？

Special user nobody configured, this is not safe!

## 你期待看到的正常表现是怎样的？

Systemd的配置文件中，将`User=nobody` 更改为 `DynamicUser=yes `，以提高安全性。新版本的systemd ([systemd 235](https://lists.freedesktop.org/archives/systemd-devel/2017-October/039589.html)) 中引入了更加严格的安全限制，不再建议使用 User=nodoby，因此系统将弹出警告` Special user nobody configured, this is not safe!`。

**Comment by cross-hello** [comment]
Why you specify a "new" systemd which  located at 2017...

----------------------------------------

*From: *PACI ***@***.***>
*To: *v2fly/v2ray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Dec 5, 2022 04:17:21
*Subject: *[v2fly/v2ray-core] systemd由nobody更改为DynamicUser (Issue #2197)

**Comment by iopq** [comment]
Note that I packaged it like this for Nix already, so if you download it from nixpkgs it should work like this out of the box

**Comment by BeautyyuYanli** [comment]
related to #2287
