### ISSUE TITLE
路由功能偶尔失效

### ISSUE THREAD

**Issue by seers** [v2fly/v2ray-core#220]
V2Ray 4.28.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/arm)

![QQ截图20200924090448](https://user-images.githubusercontent.com/3963213/94091569-28e01d80-fe4b-11ea-8cef-22fe57165ffa.png)
![QQ截图20200924090543](https://user-images.githubusercontent.com/3963213/94091576-2da4d180-fe4b-11ea-9c7e-2801e2ed6d36.png)

**Comment by seers** [comment]
```
"routing":{
      "domainStrategy":"IPOnDemand",
      "rules":[
         {
            "type":"field",
            "outboundTag":"direct",
            "domain":[
               "geosite:cn"
            ]
         },
         {
            "type":"field",
            "outboundTag":"direct",
            "ip":[
               "geoip:cn",
               "geoip:private"
            ]
         },
         {
            "type":"field",
            "outboundTag":"adblock",
            "domain":[
               "geosite:category-ads-all"
            ]
         }
      ]
   }
```

**Comment by kingwilliam** [comment]
要看您完整的client config, 因有可能是DNS 设定上的问题。

**Comment by seers** [comment]
> 要看您完整的client config, 因有可能是DNS 设定上的问题。

您的意思是可能DNS污染导致geoip:cn命中国内IP吧，我config没设置DNS方面选项
geosite:cn里面没有命中direct，但是geoip:cn命中了，说明ip优先级更高？

**Comment by kingwilliam** [comment]
如您v2内没设定dns 情况已经明朗了。

1. 因您routing用了"domainStrategy":"IPOnDemand" 如遇到要用ip做决策时v2会问DNS取ip值("IPOnDemand"：当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配)(可参考https://www.v2fly.org/config/routing.html#routingobject)

2. Routing 是没分 优先，只有 次序 即由上到下

**Comment by kingwilliam** [comment]
路由功能已正常？

**Comment by seers** [comment]
```
"routing":{
      "domainStrategy":"IPIfNonMatch",
      "rules":[
         {
            "type":"field",
            "outboundTag":"adblock",
            "domain":[
               "geosite:category-ads-all"
            ]
         },
         {
            "type":"field",
            "outboundTag":"direct",
            "domain":[
               "geosite:cn"
            ]
         },
         {
            "type":"field",
            "outboundTag":"direct",
            "ip":[
               "geoip:cn",
               "geoip:private"
            ]
         }
      ]
   }
```
将路由策略改为IPIfNonMatch，同时能匹配域名和ip，目前运行正常

> 路由功能已正常？

**Comment by seers** [comment]
> 路由功能已正常？

路由策略改为IPIfNonMatch，测试中，准备添加geosite:google强制tag proxy，不知道有没有白名单实现方法
