### ISSUE TITLE
Hide "using proxy" from server

### ISSUE THREAD

**Issue by mohali4** [v2fly/v2ray-core#2209]
It looks like v2ray notice server that we are using a proxy service. I have a private server with special IP but I can't connect some sites 

![20221213_082308.jpg](https://user-images.githubusercontent.com/59795638/207229797-b776b4f7-1979-4dea-989c-3ca0ffa34c28.jpg)

It's 👇 using tor network 😐

![20221213_082849.jpg](https://user-images.githubusercontent.com/59795638/207230516-ebf10b19-8425-4d2a-9626-19cfdbef74e1.jpg)

**Comment by cross-hello** [comment]
Spotify will try to detect whether you use proxy, if the answer is yes, 
your traffic will be rejected.

----------------------------------------

*From: *mohali ***@***.***>
*To: *v2fly/v2ray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Dec 13, 2022 05:00:34
*Subject: *[v2fly/v2ray-core] Hide "using proxy" from server (Issue 
#2209)

**Comment by cross-hello** [comment]
So you must not use ip range which has located in Spotify database.

----------------------------------------

*From: *mohali ***@***.***>
*To: *v2fly/v2ray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Dec 13, 2022 05:00:34
*Subject: *[v2fly/v2ray-core] Hide "using proxy" from server (Issue 
#2209)

**Comment by mohali4** [comment]
Thanks
I changed my VPS IP and problem was solved
