### ISSUE TITLE
v2ray limit each client connection count

### ISSUE THREAD

**Issue by amirshabanics** [v2fly/v2ray-core#2210]
Hi,
I tried to run v2fly VPN on my server on vmess protocol. but unfortunately, I can't find the connection on one UUID and my server becomes overloaded because clients send config for each other.

is there any way to block new clients that want to connect to a specific UUID if they reach the limit connection?

**Comment by Johnsavadkuhi** [comment]
Hey man, 
v2ray can't do anything well.

**Comment by Johnsavadkuhi** [comment]
اگه ایران هستی ایا ایرانسل هم میتونه وصل بشه به سرور v2ray یا تنظیمات خاصی میخواد ؟‌ پروتوکل vmess

**Comment by Johnsavadkuhi** [comment]
اینا خودشونم نمیدونن چی ساختن از بس کپی میکنن از اینور اونور حتی نمیتونن به دو تا سوال جواب بدن

**Comment by amirshabanics** [comment]
> Hey man, v2ray can't do anything well.

I see some others that use access.log and the email of the clients to find the client that reach the limit and ban it. May be we can do something same in here.

**Comment by amirshabanics** [comment]
> 



> اگه ایران هستی ایا ایرانسل هم میتونه وصل بشه به سرور v2ray یا تنظیمات خاصی میخواد ؟‌ پروتوکل vmess

نه کار خاصی نکردم و همین الان چک کردم اوکی بود و کار میکرد. فقط تنها مشکلی که وجود داره این هست که droprate بالایی داره و پینگ حداقل ۳۰۰۰ هستش. با این وضع الان این بهترین پینگی هست که میتونم بگیرم چون کهخ پهنای باند به نت خارجی رو خیلی کم کردن.

**Comment by amirshabanics** [comment]
> اینا خودشونم نمیدونن چی ساختن از بس کپی میکنن از اینور اونور حتی نمیتونن به دو تا سوال جواب بدن

بابا مشکل اصلی اینه همه جا چینی مینویسن:/ خب چطوری بفهمیم چی میگید؟ ی جا درست و درمون توضیح نمیدن

**Comment by Johnsavadkuhi** [comment]
سلام تنظیمات سمت سرور v2ray شما برای وصل شدن ایرانسل چیه میشه به اشتراک بذارید ببینم کانفیگ اصلیتون رو   از tls استفاده میکنید؟

**Comment by amirshabanics** [comment]
> سلام تنظیمات سمت سرور v2ray شما برای وصل شدن ایرانسل چیه میشه به اشتراک بذارید ببینم کانفیگ اصلیتون رو از tls استفاده میکنید؟

ببین من چک کردم جواب میده ولی با پینگ حدودا ۴ برابر (۱۸۰۰ ایناس). ولی با همراه اول خیلییی بهتر جواب میده پینگم ۳۰۰ عه.

```
{
  "log": {
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 80,
      "protocol": "vmess",
      "allocate": {
        "strategy": "always"
      },
      "settings": {
        "clients": [
          {
            "id": <uuid>,
            "level": 1,
            "alterId": 0,
            "email": "client@example.com"
          }
        ],
        "disableInsecureEncryption": true
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "connectionReuse": true,
          "path": "/path"
        },
        "security": "none",
        "tcpSettings": {
          "header": {
            "type": "http",
            "response": {
              "version": "1.1",
              "status": "200",
              "reason": "OK",
              "headers": {
                "Content-Type": [
                  "application/octet-stream",
                  "application/x-msdownload",
                  "text/html",
                  "application/x-shockwave-flash"
                ],
                "Transfer-Encoding": ["chunked"],
                "Connection": ["keep-alive"],
                "Pragma": "no-cache"
              }
            }
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

**Comment by Johnsavadkuhi** [comment]
سلام ممنونم منم چنین کانفیگی دارم ولی ایرانسلا وصل نمیشن. 
حالا این مشکل به کنار 
خود v2ray مشکل زیادی داره مثلا من هنوز نمیدونم چطور از این طریق بفهمم چن نفر به هر پورت وصل شدن. چنین چیزی براش تعریف نکردن و باید با برنامه های دیگه این کارو بکنیم یا کلا امارگیری نداره یا ضعیفه خیلی مشکل داره چیزی که چینیا ساختن

**Comment by whoami-idk** [comment]
من هنوز نفهمیدم چی به چیه اصلا
چجوری بالا بیارم و بعد چجوری از این نمونه ها 
https://github.com/v2fly/v2ray-examples
استفاده کنم!
مستندات نداره اصلا!

**Comment by amirshabanics** [comment]
> من هنوز نفهمیدم چی به چیه اصلا چجوری بالا بیارم و بعد چجوری از این نمونه ها https://github.com/v2fly/v2ray-examples استفاده کنم! مستندات نداره اصلا!

در لحظه تو شرایطی هستیم که همه باید به هم کمک کنیم. من این لینک رو از همه بیشتر میپسندم به عنوان یک نمونه. کاملا خوب کانفیگ ها و داکر رو ستاپ کرده. امیدوارم کمکت کنه. [لینک](https://github.com/hossinasaadi/v2ray-config-examples)

فقط اینکه من در لحظه به طرز عجیبی فقط میتونم رو ایرانسل و رایتل با پینگ متغیر و دراپ ریت بالا بگیرم. روی همراه اول هم تا مدتی کار نمیکرد ولی الان مثل اینکه داره کار میکنه. روی اینترنت های داخلی مثل شاتل خیلی بهتر جواب میده ولی به طور کلی با توجه به پینگ و دراپ ریت ها گزینه خوب همیشگی نیست. اگر به پینگ خوب رسیدی که رو همه اوپراتور ها جواب داد خوشحال میشم بگی از کدوم دیتاسنتر سرور گرفتی .

**Comment by dev-kamran2001** [comment]
> > سلام تنظیمات سمت سرور v2ray شما برای وصل شدن ایرانسل چیه میشه به اشتراک بذارید ببینم کانفیگ اصلیتون رو از tls استفاده میکنید؟
> 
> ببین من چک کردم جواب میده ولی با پینگ حدودا ۴ برابر (۱۸۰۰ ایناس). ولی با همراه اول خیلییی بهتر جواب میده پینگم ۳۰۰ عه.
> 
> ```
> {
>   "log": {
>     "loglevel": "info"
>   },
>   "inbounds": [
>     {
>       "port": 80,
>       "protocol": "vmess",
>       "allocate": {
>         "strategy": "always"
>       },
>       "settings": {
>         "clients": [
>           {
>             "id": <uuid>,
>             "level": 1,
>             "alterId": 0,
>             "email": "client@example.com"
>           }
>         ],
>         "disableInsecureEncryption": true
>       },
>       "streamSettings": {
>         "network": "ws",
>         "wsSettings": {
>           "connectionReuse": true,
>           "path": "/path"
>         },
>         "security": "none",
>         "tcpSettings": {
>           "header": {
>             "type": "http",
>             "response": {
>               "version": "1.1",
>               "status": "200",
>               "reason": "OK",
>               "headers": {
>                 "Content-Type": [
>                   "application/octet-stream",
>                   "application/x-msdownload",
>                   "text/html",
>                   "application/x-shockwave-flash"
>                 ],
>                 "Transfer-Encoding": ["chunked"],
>                 "Connection": ["keep-alive"],
>                 "Pragma": "no-cache"
>               }
>             }
>           }
>         }
>       }
>     }
>   ],
>   "outbounds": [
>     {
>       "protocol": "freedom",
>       "settings": {}
>     }
>   ]
> }
> ```

داداش شما باید پروتکل vmess روی پورت 443 با HTTP Header اجرا کنی غیر از این نتیجه مطلوب و قابل قبولی نداره چون پورت 80 روی دیتای رمزنگاری شده اختلال میندازن به همین خاطر تعداد TCP Retransmission خیلی زیاد میشه و پینگ هم نجومی میره بالا.

**Comment by amirshabanics** [comment]
> > > سلام تنظیمات سمت سرور v2ray شما برای وصل شدن ایرانسل چیه میشه به اشتراک بذارید ببینم کانفیگ اصلیتون رو از tls استفاده میکنید؟
> > 
> > 
> > ببین من چک کردم جواب میده ولی با پینگ حدودا ۴ برابر (۱۸۰۰ ایناس). ولی با همراه اول خیلییی بهتر جواب میده پینگم ۳۰۰ عه.
> > ```
> > {
> >   "log": {
> >     "loglevel": "info"
> >   },
> >   "inbounds": [
> >     {
> >       "port": 80,
> >       "protocol": "vmess",
> >       "allocate": {
> >         "strategy": "always"
> >       },
> >       "settings": {
> >         "clients": [
> >           {
> >             "id": <uuid>,
> >             "level": 1,
> >             "alterId": 0,
> >             "email": "client@example.com"
> >           }
> >         ],
> >         "disableInsecureEncryption": true
> >       },
> >       "streamSettings": {
> >         "network": "ws",
> >         "wsSettings": {
> >           "connectionReuse": true,
> >           "path": "/path"
> >         },
> >         "security": "none",
> >         "tcpSettings": {
> >           "header": {
> >             "type": "http",
> >             "response": {
> >               "version": "1.1",
> >               "status": "200",
> >               "reason": "OK",
> >               "headers": {
> >                 "Content-Type": [
> >                   "application/octet-stream",
> >                   "application/x-msdownload",
> >                   "text/html",
> >                   "application/x-shockwave-flash"
> >                 ],
> >                 "Transfer-Encoding": ["chunked"],
> >                 "Connection": ["keep-alive"],
> >                 "Pragma": "no-cache"
> >               }
> >             }
> >           }
> >         }
> >       }
> >     }
> >   ],
> >   "outbounds": [
> >     {
> >       "protocol": "freedom",
> >       "settings": {}
> >     }
> >   ]
> > }
> > ```
> 
> داداش شما باید پروتکل vmess روی پورت 443 با HTTP Header اجرا کنی غیر از این نتیجه مطلوب و قابل قبولی نداره چون پورت 80 روی دیتای رمزنگاری شده اختلال میندازن به همین خاطر تعداد TCP Retransmission خیلی زیاد میشه و پینگ هم نجومی میره بالا.

سلام امکانش هست یک http header مناسب برای این کانفیگ مثال بزنید یا اگر کانفیگ خوبی داری بفرستید؟ راجب پورت هم این روی داکر هست برای همین صرفا پورتش رو زمان اکسپورت کردن تغییر میدم

**Comment by Mikaeil-t** [comment]
> > سلام تنظیمات سمت سرور v2ray شما برای وصل شدن ایرانسل چیه میشه به اشتراک بذارید ببینم کانفیگ اصلیتون رو از tls استفاده میکنید؟
> 
> ببین من چک کردم جواب میده ولی با پینگ حدودا ۴ برابر (۱۸۰۰ ایناس). ولی با همراه اول خیلییی بهتر جواب میده پینگم ۳۰۰ عه.
> 
> ```
> {
>   "log": {
>     "loglevel": "info"
>   },
>   "inbounds": [
>     {
>       "port": 80,
>       "protocol": "vmess",
>       "allocate": {
>         "strategy": "always"
>       },
>       "settings": {
>         "clients": [
>           {
>             "id": <uuid>,
>             "level": 1,
>             "alterId": 0,
>             "email": "client@example.com"
>           }
>         ],
>         "disableInsecureEncryption": true
>       },
>       "streamSettings": {
>         "network": "ws",
>         "wsSettings": {
>           "connectionReuse": true,
>           "path": "/path"
>         },
>         "security": "none",
>         "tcpSettings": {
>           "header": {
>             "type": "http",
>             "response": {
>               "version": "1.1",
>               "status": "200",
>               "reason": "OK",
>               "headers": {
>                 "Content-Type": [
>                   "application/octet-stream",
>                   "application/x-msdownload",
>                   "text/html",
>                   "application/x-shockwave-flash"
>                 ],
>                 "Transfer-Encoding": ["chunked"],
>                 "Connection": ["keep-alive"],
>                 "Pragma": "no-cache"
>               }
>             }
>           }
>         }
>       }
>     }
>   ],
>   "outbounds": [
>     {
>       "protocol": "freedom",
>       "settings": {}
>     }
>   ]
> }
> ```

سلام داداش يه توضيح كوچيك در رابطه با كانفيگ ايرانسلت ميدي كلا ممنون ميشم ❤️
