### ISSUE TITLE
[Discuss] 在之后的新版本发布流程中，编译时传递 `-PIE` 选项。

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/v2ray-core#223]
Related PR and previous discussion: #221.

**Comment by kslr** [comment]
https://golang.org/doc/go1.15#linker

**Comment by Loyalsoldier** [comment]
Maybe add into OS specific Bazel configuration?

**Comment by IceCodeNew** [comment]
> Maybe add into OS specific Bazel configuration?

Good idea, I will give it a shot later.
