### ISSUE TITLE
gRPC API 文件没有找到

### ISSUE THREAD

**Issue by Birddle** [v2fly/v2ray-core#2235]
### Discussed in https://github.com/v2fly/v2ray-core/discussions/2234

<div type='discussions-op-text'>

<sup>Originally posted by **Birddle** December 24, 2022</sup>
当我尝试使用gRPC转换V2RAY-CORE 代码到JAVA语言时,没有找到一个一劳永逸的方法，只能进入到每个文件夹中重复操作，但是当转换某些文件时，得到文件没有找到这样的报错。例如proxyman
我是用的是WINDOWS系统
![image](https://user-images.githubusercontent.com/86408260/209425276-d36bcb3e-f7d8-492d-b30a-98fbfd3f66c2.png)

请问这是哪里出现问题了？
</div>

**Comment by AkinoKaede** [comment]
You should use `-IPATH` or `--proto_path=PATH` to specify the directory in which to search for imports. You can read find the docment in protoc.

**Comment by Birddle** [comment]
> You should use `-IPATH` or `--proto_path=PATH` to specify the directory in which to search for imports. You can read find the docment in `protoc`.

OMG, It's working..... Thank you  buddy, love you.
