### ISSUE TITLE
How to config uTLS with JsonV4

### ISSUE THREAD

**Issue by Handsome1080P** [v2fly/v2ray-core#2239]
I did't find the document about how to configure the uTLS with JsonV4 and there is a way convert my original JsonV4 config file to JsonV5?

**Comment by lhbdhr** [comment]
you mean v2fly v4? JSON is a file format. so, there is no JSONv4.
And uTLS is only supported on v2fly v5.20. you can't use it on v2fly v4.

you need to update your server v2fly to v5.20.
you can find the most configurable option on the v2fly official website.
https://www.v2fly.org/en_US/v5/config/overview.html

**Comment by Handsome1080P** [comment]
> 

I mean Json V4 config not V2RAY version 4.0.I alreay updated v2ray to latest one.

**Comment by lhbdhr** [comment]
Oh, I misunderstood what you said. I have no idea the answer to your question.
you can use this command to try. I'm not sure it will work.
v2ray run -c config.json -format jsonv5

**Comment by xiaokangwang** [comment]
uTLS and other new features added after the release of V2Ray V5 is inaccessible with jsonv4 format(as it is in maintenance mode now). 
There is no automated way to convert an V4 config to V5, but you will be able to rewrite the config in V5 manually.

**Comment by Handsome1080P** [comment]
> uTLS and other new features added after the release of V2Ray V5 is inaccessible with jsonv4 format(as it is in maintenance mode now). There is no automated way to convert an V4 config to V5, but you will be able to rewrite the config in V5 manually.

thx.

**Comment by mydogshitgold** [comment]
@Handsome1080P
uTLS is inaccessible with V4 config, but that doesn't prevent you from using it by monkey patching,


>**utls_v4_config.patch**:

```diff
diff --git a/infra/conf/v4/transport_internet.go b/infra/conf/v4/transport_internet.go
index 1a18a45d..1231bd14 100644
--- a/infra/conf/v4/transport_internet.go
+++ b/infra/conf/v4/transport_internet.go
@@ -19,6 +19,8 @@ import (
 	"github.com/v2fly/v2ray-core/v5/transport/internet/kcp"
 	"github.com/v2fly/v2ray-core/v5/transport/internet/quic"
 	"github.com/v2fly/v2ray-core/v5/transport/internet/tcp"
+	"github.com/v2fly/v2ray-core/v5/transport/internet/tls"
+	"github.com/v2fly/v2ray-core/v5/transport/internet/tls/utls"
 	"github.com/v2fly/v2ray-core/v5/transport/internet/websocket"
 )
 
@@ -324,6 +326,25 @@ func (c *StreamConfig) Build() (*internet.StreamConfig, error) {
 		config.SecuritySettings = append(config.SecuritySettings, tm)
 		config.SecurityType = serial.V2Type(tm)
 	}
+	if strings.EqualFold(c.Security, "utls") {
+		tlsSettings := c.TLSSettings
+		if tlsSettings == nil {
+			tlsSettings = &tlscfg.TLSConfig{}
+		}
+		ts, err := tlsSettings.Build()
+		if err != nil {
+			return nil, newError("Failed to build TLS config.").Base(err)
+		}
+		utlsConfig := &utls.Config{
+			TlsConfig: new(tls.Config),
+			Imitate:   "chrome_auto",
+			NoSNI:     false,
+		}
+		proto.Merge(utlsConfig.TlsConfig, ts)
+		tm := serial.ToTypedMessage(utlsConfig)
+		config.SecuritySettings = append(config.SecuritySettings, tm)
+		config.SecurityType = serial.V2Type(tm)
+	}
 	if c.TCPSettings != nil {
 		ts, err := c.TCPSettings.Build()
 		if err != nil {
```
**NOTE:**: you can change value of `utlsConfig.mitate` to one defined in [nameMapper.go](https://github.com/v2fly/v2ray-core/tree/master/transport/internet/tls/utls/nameMapper.go)
```bash
git clone --depth 1 https://github.com/v2fly/v2ray-core
cd v2ray-core
curl -sLO https://gist.githubusercontent.com/mydogshitgold/e14c2f840ac2537e09fd0c32db608340/raw/19215bddac1c883f1f156c9cf9aef47d2837e37c/utls_v4_config.patch
patch -Np1 -i utls_v4_config.patch
CGO_ENABLED=0 go build -o v2ray -trimpath -ldflags "-s -w -buildid=" ./main
sudo install -Dm 755 vray /bin/v2ray
```
Then change `streamSettings.security` of your config.json to `"utls"`.

**Comment by Handsome1080P** [comment]
> 

Nice,thx.
