### ISSUE TITLE
客户端升级 v5.2.0 User Preview后，VLESS+TCP+TLS 无法使用，VLESS+GRPC 正常使用。

### ISSUE THREAD

**Issue by Zeezorn** [v2fly/v2ray-core#2243]
## 你正在使用哪个版本的 V2Ray？
服务器端 v5.1.0 User Preview
客户端 v5.2.0 User Preview

## 你的使用场景是什么？
OpenWrt 22.03.2 Stable Release

## 你看到的异常现象是什么？
STEP 1：
服务器端 v5.1.0 
客户端 v5.2.0 通过OP官方稳定源升级：https://downloads.openwrt.org/releases/22.03.2/packages/x86_64/packages/v2ray-core_5.2.0-1_x86_64.ipk
VLESS+TCP+TLS 无法使用
VLESS+GRPC 正常使用
STEP 2：
服务器端 [保持] v5.1.0 
客户端 [手动降级] v5.2.0 --> v5.1.0 
VLESS+TCP+TLS 正常使用
VLESS+GRPC 正常使用

## 错误日志
客户端未显示错误日志

**Comment by abc950309** [comment]
same problem, here is my log
```2023/01/05 16:10:37 [Info] app/observatory: the outbound ** is dead: > app/observatory: GET request failed:app/observatory: outbound failed to relay connection > Get "https://www.google.com/gen_204": io: read/write on closed pipe > app/observatory: with outbound handler report > app/observatory: underlying connection failed > app/observatory: underlying connection error > app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config```
