### ISSUE TITLE
v2ray does not read config.json from a custom path and not from a symlink either

### ISSUE THREAD

**Issue by a-pav** [v2fly/v2ray-core#2244]
## What version of V2Ray are you using?

5.1.0

## What's your scenario of using V2Ray?

I've installed `v2ray` by using the [fhs script](https://github.com/v2fly/fhs-install-v2ray/). Initially I tried to create a symlink to `/custom/path/to/config.json` from `/usr/local/etc/v2ray/config.json`, but that didn't work.
Then I've created a `override.conf` inside the `v2ray.service.d` directory with below content:
```
[Service]
User=v2ray_user
ExecStart=
ExecStart=/usr/local/bin/v2ray run -config /custom/path/to/config.json
```
At first, tried without `User=v2ray_user` directive but didn't work. So I created a new linux user, ran `chown v2ray_user:v2ray_user config.json`. But still I get `permission denied`:
```
Failed to start: main/commands: failed to load config: [/custom/path/to/config.json] > fail to load /custom/path/to/config.json: open /custom/path/to/config.json: permission denied
```
Had the same error with symlinks too. But interestingly, it works if I run `v2ray run -config /custom/path/to/config.json` in terminal  or when I use `User=my_own_username` directive inside the `override.conf`

## What problems have you encountered?
See above.

## What's your expectation?
I expect to be able to change to a custom path to config.json using symlinks or a `.conf` drop-in file.

How can one customize the  path for config.json file?

## Please attach your configuration here
{ can provide if absolutely needed }

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

**Comment by cross-hello** [comment]
Do you want to try xray? With latest code, xray should be able to read configuration from symbolic link file. But in fact, we don't have a test formally. Do you want to help to have a test?

**Comment by cross-hello** [comment]
It is confused. We test **os.Open** of golang builtin function could open symbolic link file. How could it don't read configuration?

**Comment by lhbdhr** [comment]
It is not necessary to change this file.
If your purpose is convenient to change the config file.
you can use the soft link.
ln -s `/usr/local/etc/v2ray/config.json` `yourhomepath/v2fly-config.json`  
then, you will not enter that long path to modify the config file.

**Comment by cross-hello** [comment]
The problem is caused by file permission. Change your original file to 777, then the problem maybe could be solved. (golang os.Open build-in function has supported link file)

Dec 31, 2022 05:56:19 a-pav ***@***.***>:

**Comment by lhbdhr** [comment]
> 
I mean,
you can use `vi soft link path` to change the config file.
Don't change `ExecStart` to your custom path.
then you will start v2ray successfully.

btw, Linux file permission can't just change its permission, 
also needs to change the permission of the directory where the file is located to 755.

**Comment by cross-hello** [comment]
You must create a new problem.
May you should write a golang program to have a test?

Jan 11, 2023 19:48:02 a-pav ***@***.***>:

**Comment by lhbdhr** [comment]
Have you tried this?
>you can use vi soft link path to change the config file.
Don't change ExecStart to your custom path.
then you will start v2ray successfully.

**Comment by suienzan** [comment]
Works fine here. You might have wrong permission for your config file.

```console
~/test ❯ l 
~/test ❯ l /etc/v2ray/config.json                                                                                                                                                                                                  19:54:18
Permissions Size User Date Modified    Name
.rw-r--r--  3.4k root 2022-11-16 20:02 /etc/v2ray/config.json
~/test ❯ ln -s /etc/v2ray/config.json                                                                                                                                                                                              19:54:25
~/test ❯ v2ray run -config config.json                                                                                                                                                                                             19:54:35
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
2023/01/12 19:54:42 [Warning] V2Ray 5.1.0 started
```

**Comment by suienzan** [comment]
> > Works fine here. You might have wrong permission for your config file.
> > ```
> > ~/test ❯ l 
> > ~/test ❯ l /etc/v2ray/config.json                                                                                                                                                                                                  19:54:18
> > Permissions Size User Date Modified    Name
> > .rw-r--r--  3.4k root 2022-11-16 20:02 /etc/v2ray/config.json
> > ~/test ❯ ln -s /etc/v2ray/config.json                                                                                                                                                                                              19:54:25
> > ~/test ❯ v2ray run -config config.json                                                                                                                                                                                             19:54:35
> > V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
> > A unified platform for anti-censorship.
> > 2023/01/12 19:54:42 [Warning] V2Ray 5.1.0 started
> > ```
> 
> Seems people around here just don't bother with reading the OP anymore...

What I'm talking about is V2ray support both custom path and symlink. The problem you are facing is a permission issue. It's not caused by V2ray.

If you need help with configuration, it's better asking help in discussions.

**Comment by lhbdhr** [comment]
> What... is `vi soft link path`?! I used `ln`.
> Like this: `ln -sf /my/path/2/config.json /usr/local/etc/v2ray/config.json;`

You can use vi /my/path/2/config.json to edit config file. 
I put soft link in my linux account home directory.

**Comment by KouYiGuo** [comment]
The log is very clear. 
```
open /custom/path/to/config.json: permission denied
```
It means that the user "v2ray_user" in the systemd service file has no permission to read the "config.json".

Try to change **config.json** permission to "666" and make it readable by **other user**.

**Comment by mydogshitgold** [comment]
It is not wise to make the file world-writable. 644 should be enough.

**Comment by KouYiGuo** [comment]
> It is not wise to make the file world-writable. **644** should be enough.

Yes, you're right.

**Comment by mydogshitgold** [comment]
File permissions are **NOT** file ownership. If a file doesn't have the read permission bit set, you won't be able to read it, even if you own the file.

To set read permission bit
```bash
chmod +r config.json
```

To check file permission
```bash
stat config.json
```

**Comment by mydogshitgold** [comment]
All parent directories of `config.json` **must** also have their execute bit set.

**Comment by mydogshitgold** [comment]
If you don't want to compromise the permissions of your home directory, you can use file ACL. No workaround is needed.

```bash
setfacl -m u:v2ray_user:rx <path/to/directory>
```

Apply this command to all parent directory of `config.json`. It is safe and does not affect permisson of other users.

**Comment by mydogshitgold** [comment]
Use file ACL if you only want one path.

Whatever works best for you is the one true way.
