### ISSUE TITLE
i cant find some folder 

### ISSUE THREAD

**Issue by fereidoonsavadkoohi** [v2fly/v2ray-core#2245]
hi, where is github.com/v2fly/v2ray-core/v5/ ??

**Comment by kslr** [comment]
master  branch

**Comment by database64128** [comment]
`v5` is part of the Go module path, not an actual folder. See https://go.dev/doc/modules/major-version to learn about the convention of major version updates.

**Comment by fereidoonsavadkoohi** [comment]
hi @database64128  can you help me release the v2ray-core to .aar for android? i download this repo in my computer and install go and go mobile , but i cant release .aar file :|

**Comment by cross-hello** [comment]
Look here: https://github.com/2dust/AndroidLibV2rayLite
Then *make*

Jan 6, 2023 00:24:00 fereidoon Savadkoohi ***@***.***>:
