### ISSUE TITLE
VLESS和中转服务器的问题

### ISSUE THREAD

**Issue by kingzleshe** [v2fly/v2ray-core#226]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.29.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 通过 Socks/VMess 代理观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
4.29.0发布后，测试了下，发现如下问题
之前使用的场景：
client SS-->VPS1--VMESS-->VPS2 （正常访问）
client VMESS-->VPS1--VMESS-->VPS2 （正常访问）
测试场景：
client SS-->VPS1--VLESS-->VPS2 （不能正常）
client VMESS-->VPS1--VLESS-->VPS2 （不能正常）
4) 你期待看到的正确表现是怎样的？
使用VLESS+中转服务器的时候，是否能支持客户端用SS协议或者VMESS协议连接中转服务器的inbond？
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by rprx** [comment]
请问这是 v4.29.0 的新问题吗？

**Comment by kingzleshe** [comment]
是的呀,中转无法使用,也不知道为啥。。

**Comment by kingzleshe** [comment]
我是4.29发布后才测试的,之前的版本我也没试过VLESS

**Comment by charley008** [comment]
配置都不发,全靠猜吗

**Comment by kingzleshe** [comment]
> 配置都不发,全靠猜吗

server端用的自动脚本部署的，client的配置不是自动的么，然后我就多加了inbond的端口和协议，作为中转服务器的配置。

**Comment by Cwek** [comment]
这……使用自动脚本的小白，这样很难让老大们协助的？
或者你需要打开自动配置的脚本，看一下里面将配置文件写入到哪里，然后再去到配置文件打开来看知道？

**Comment by kingzleshe** [comment]
> 这……使用自动脚本的小白，这样很难让老大们协助的？
> 或者你需要打开自动配置的脚本，看一下里面将配置文件写入到哪里，然后再去到配置文件打开来看知道？

跟你有半毛钱的关系？你才是喜欢发配置的小白把

**Comment by charley008** [comment]
中转不只一种方式吧？ 我知道的至少两种，1. 代理转发，"proxySettings" ，这种方法只在客户端配置。2，在服务端的outbounds 里配置vmess 直接通到 另一台vps，而不是freedom。

**Comment by kingzleshe** [comment]
> 中转不只一种方式吧？ 我知道的至少两种，
> 1. 代理转发，"proxySettings" ，这种方法只在客户端配置。
> 2，在服务端的outbounds 里配置vmess 直接通到 另一台vps，而不是freedom。
> 如果你用的是ProxySettings出站代理转发的话，要注意
> 使用了代理转发 streamSettings 会失效，即只能是非 TLS、无 HTTP 伪装的 TCP 传输协议。
> vless是有tls的，所以你什么都没说一下，你让别人怎么判断你哪里出错？

无语,我画的示意图已经充分说明了,而且这年头没TLS还能翻墙？

**Comment by kingzleshe** [comment]
如果继续追问配置问题的哥们还是省省吧，别问了。

之前强调了VLESS的client的配置是server端自动生成的，client的配置直连server是没问题的。

然后我就把client配置加了SS协议和VMESS协议 inbond端口，作为中转服务器的配置。其他没任何调整。
当我用PC连接中转服务器的inbond后，无法正常访问出去。
