### ISSUE TITLE
New version cannot be installed

### ISSUE THREAD

**Issue by fasthorse** [v2fly/v2ray-core#2266]
When using the online script to upgrade v2fly to v5.2.1, the following errors occured.
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-64.zip.dgst
error: Check failed! Please check your network or try again.

Please help.

**Comment by martin-songzy** [comment]
same problem，+1

**Comment by 138398wpf** [comment]
same problem, it may be caused by the instability of the github website server.

**Comment by laga-bu** [comment]
same problem too~

**Comment by Balnea** [comment]
<img width="775" alt="Screenshot 2023-01-16 185509" src="https://user-images.githubusercontent.com/11453121/212675194-bf6e4997-5b13-4bf5-b539-634b4832a250.png">

**Comment by coosar** [comment]
some problem +1 
waiting for fixing

**Comment by Balnea** [comment]
script has been updated.
