### ISSUE TITLE
Big (Maybe) log file causes machine crash

### ISSUE THREAD

**Issue by shejialuo** [v2fly/v2ray-core#2269]
## What version of V2Ray are you using?

V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)

## What problems have you encountered?

I have run the v2ray service for a long time about 3 months. There are some many logs. Today, I have found that my VPS suddenly crashed. This has happened before, so I though about this problem was caused by the VPS provider. However, when I reboot the VPS, and starts the v2ray service again. I use my browser for google. The VPS would crash.

At that time, I had understood that the log file may be the problem. So I have checked the size of the `access.log` and `error.log`. The both size of them is about 80M. (There are a lot of warnings in the `error.log`).

So I delete all the logs, the things had been all done.

## What's your expectation?

My vps's performance is not good. Below is the information:

+ CPU: Intel Xeon E5-2650 v2 @ 2.6GHz
+ RAM: 976Mib
+ Disk: 5.1G / 25G (22%)

But I don't think reading or writing a 80M log would cause the VPS crash.

## Please attach your configuration here

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

**Comment by oldflag2333333** [comment]
看上去像服务器的问题，建议给vps的供应商提工单想办法拿到crash的日志，这个issue建议关了，如果能够确定是v2ray导致的再另外提一个附有具体原因的issue吧，现在这个issue很难给你啥有效的帮助。另外如果只是单纯解决日志文件比较大的问题可以用 logrotate自动切片删除。
