### ISSUE TITLE
Unable to Read Header Len > EOF

### ISSUE THREAD

**Issue by esmaeilifardi** [v2fly/v2ray-core#2272]
in ubuntu 22.10 & xubuntu & kali:
with core "v2ray-linux-64.zip" v4.31.0  in qv2ray

2023/01/21 23:46:32 [Info] [7605383] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Unable to Read Header Len > EOF

with same vmess key mobile phone and windows11 with same setting connected.

**Comment by 09141618025** [comment]
> in ubuntu 22.10 & xubuntu & kali: with core "v2ray-linux-64.zip" v4.31.0 in qv2ray
> 
> 2023/01/21 23:46:32 [Info] [7605383] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Unable to Read Header Len > EOF
> 
> with same vmess key mobile phone and windows11 with same setting connected.

https://p.free-gate.site/api/v1/client/subscribe?token=77faabd6a550d35e971387bfa0bcd51f

**Comment by DogeWatch** [comment]
I have the same problem, the error log is
```
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: Unable to Read Header Len > EOF
```
I use the vmess with kcp + dtls header

**Comment by JoeZing** [comment]
I hava the same problem

**Comment by Aaron199** [comment]
I hava the same problem

**Comment by 09141618025** [comment]
in ubuntu 22.10 & xubuntu & kali:
with core "v2ray-linux-64.zip" v4.31.0  in qv2ray

2023/01/21 23:46:32 [Info] [7605383] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Unable to Read Header Len > EOF

with same vmess key mobile phone and windows11 with same setting connected.

_Originally posted by @esmaeilifardi in https://github.com/v2fly/v2ray-core/issues/2272_
