### ISSUE TITLE
关于log

### ISSUE THREAD

**Issue by yyiu** [v2fly/v2ray-core#2273]
> 
    "log": {
        "access": "access.log",
        "error": "error.log",
        "loglevel": "none" // loglevel: "debug" | "info" | "warning" | "error" | "none"
    },

v5 5.2.1
log分开设置时，等级设置成 none 时，仍然会与入 access.log ，log是正常的无写入

**Comment by AkinoKaede** [comment]
`loglevel` in JsonV4 format is the level of error log.
