### ISSUE TITLE
使用v5配置文件，路由添加geoip后，cannot unmarshal object into Go value of type []json.RawMessage

### ISSUE THREAD

**Issue by ybh1998** [v2fly/v2ray-core#2289]
使用v2ray v5.2.1，启动命令`v2ray run -format jsonv5`，配置文件如下：
```
{
  "inbounds": [{
    "protocol": "vmess",
    "settings": {
      "users": ["eed678ef-bbfc-4820-b71c-000000000000"]
    },
    "port": 9086,
    "listen": "127.0.0.1"
  }],
  "outbounds": [{
    "protocol": "blackhole"
  }, {
    "tag": "freedom",
    "protocol": "freedom"
  }],
  "router": {
    "rule": [{
      "tag": "freedom",
      "geoip": {
        "cidr": [{
          "ipAddr": "127.0.0.1",
          "prefix": 32
        }]
      },
      "portList": "9655"
    }]
  }
}
```
使用该配置文件报错如下：
```
Failed to start: main/commands: failed to load config > infra/conf/v5cfg: unable to build config > common/registry: unable to parse json content > json: cannot unmarshal object into Go value of type []json.RawMessage
```
在配置文件中删除router -> rule -> geoip后可以正常启动，geoip块尝试一下几种，报错相同：
```
"geoip": {
  "code": "CN"
},
```
```
"geoip": {
},
```
配置文件写法参考了[https://www.v2fly.org/v5/config/router.html#ruleobject](https://www.v2fly.org/v5/config/router.html#ruleobject)和[https://www.v2fly.org/v5/config/geo.html](https://www.v2fly.org/v5/config/geo.html)，不知道是配置文件写法不对，还是v2ray没能正确Parse `GeoIP`

**Comment by mydogshitgold** [comment]
Your configuration is invalid.

`router.rule.geoip` is supposed to be an array of [GeoIP](https://www.v2fly.org/v5/config/geo.html#GeoIP) objects, not a single GeoIP object.

```json
        "geoip": [
          {
            "cidr": [
              {
                "ipAddr": "127.0.0.1",
                "prefix": 32
              }
            ]
          }
        ]
```

The v5 configuration schema listed on [official website](https://www.v2fly.org/v5/config/router.html#ruleobject) seems to be a bit outdated. You probably want to refer to protobuf files (`config.proto`) in the source tree when in doubt.

[EHfive/v2ray-jsonschema](https://github.com/EHfive/v2ray-jsonschema)  provides [JSON schema](https://json-schema.org) generated through Go type reflection, which could be more up to date. You can use that to validate your configuration.

**Comment by ybh1998** [comment]
Thanks!
