### ISSUE TITLE
Problem with configuring uTLS

### ISSUE THREAD

**Issue by arashammm** [v2fly/v2ray-core#2298]
In latest version there is a new security mode which is uTLS. I have a working v2ray v5.2.1 client program with this json file:

> {
>   "log": {
>     "loglevel": "warning"
>   },
>   "inbounds": [ 
> {
>           "listen": "127.0.0.1",
>       "protocol": "socks",
>       "settings": {
>         "udp": true,
>         "auth": "noauth"
>       },
>       "port": "1082"
> 
> }
>   ],
>   "outbounds": [
>     {
>   "protocol": "vmess",
>       "streamSettings": {
>         "wsSettings": {
>           "path": "/",
>           "headers": {
>             "host": ""
>           }
>         },
>         "tlsSettings": {
>           "allowInsecure": false
>         },
>            "security": "tls",
>         "network": "ws"
>       },
>       "tag": "proxy",
>       "settings": {
>         "vnext": [
>           {
>             "address": "my domain",
>             "users": [
>               {
>                 "id": "my uuid",
>                 "alterId": 0,
>                 "level": 0,
>                 "security": "aes-128-gcm"
>               }
>             ],
>             "port": 443
>           }
>         ]
>       }
>     }
>   ]
> }
> 

But when I try to implement the uTLS like discussed [here](https://github.com/v2fly/v2ray-core/pull/2219) I can't connect to the vmess server.

this is how I try to implement the uTLS :

> {
>   "log": {
>     "loglevel": "warning"
>   },
>   "inbounds": [ 
> {
>           "listen": "127.0.0.1",
>       "protocol": "socks",
>       "settings": {
>         "udp": true,
>         "auth": "noauth"
>       },
>       "port": "1082"
> 
> }
>   ],
>   "outbounds": [
>     {
>   "protocol": "vmess",
>       "streamSettings": {
>         "wsSettings": {
>           "path": "/ray",
>           "headers": {
>             "host": ""
>           }
>         },
>          "security": "utls",
>          "securitySettings": {
>         "imitate": "android_11_okhttp",
>         "tlsConfig": {
>         }
>         "network": "ws"
>       },
>       "tag": "proxy",
>       "settings": {
>         "vnext": [
>           {
>             "address": "my domain",
>             "users": [
>               {
>                 "id": "my uuid",
>                 "alterId": 0,
>                 "level": 0,
>                 "security": "aes-128-gcm"
>               }
>             ],
>             "port": 443
>           }
>         ]
>       }
>     }
>   ]
> }
> 
> 

Can anyone tell me what I do wrong?

Is the v2ray version on server has to be 5.2.1 also for this to work?

**Comment by mydogshitgold** [comment]
See #2239 

You are using [v4](https://www.v2fly.org/en_US/config/overview.html) configuration format, [which does not have access to new features such has uTLS](https://github.com/v2fly/v2ray-core/issues/2239#issuecomment-1383164095).

You should either rewrite your configuration file in [v5 format](https://www.v2fly.org/en_US/v5/config/overview.html), or [patch v2ray](https://github.com/v2fly/v2ray-core/issues/2239#issuecomment-1399535453).
