### ISSUE TITLE
Check version

### ISSUE THREAD

**Issue by mahmoodn** [v2fly/v2ray-core#2301]
I have installed v2ray on a VM with this command `bash <(curl -s -L https://git.io/v2ray.sh)`. How can I find the installed version? Also, how can I get latest update? What are the instructions?

**Comment by mydogshitgold** [comment]
Run `v2ray version` to find the installed version.

link https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip will always point to latest V2Ray binary release for Linux on amd64.

The script you are using seems to be unmaintained (original repo  was deleted).
Why not try to [understand how to configure](https://www.v2fly.org/en_US/v5/config/overview.htmll) V2Ray manually and then [automate it yourself](https://tldp.org/LDP/Bash-Beginners-Guide/html/)?

There's also a [guide](https://guide.v2fly.org/en_US/) on configuring V2Ray as well.

**Comment by mahmoodn** [comment]
The guide you mentioned points to downloading a script named `go.sh` which says `This script has been DISCARDED`. I am a bit confused. The `v2ray-linux-64.zip` contains binary and config files which I think are used for manual installation. Am I right?

**Comment by mydogshitgold** [comment]
The guide is only a reference, something would surely be out of date. You don't have to copy every step.

Like most Go applications, V2Ray is mostly self-contained. Just unpack the archive and you are done.

If you are on a bleeding edge distro like Fedora, Arch, openSUSE, then installing V2Ray via the package manager might actually be easier.

My personal advice is that don't jump to scripts and try to figure out how to use V2Ray manually, the knowledge you gain from this process will be very helpful in building a robust proxy.

**Comment by mahmoodn** [comment]
OK Thanks. I will create the next issue in the next topic.
