### ISSUE TITLE
搭建好的 VLESS ，如下，使用没问题，但是每天 过了 凌晨12点以后，必封端口。

### ISSUE THREAD

**Issue by GinJouii** [v2fly/v2ray-core#2303]
搭建好的 VLESS ，如下，使用没问题，但是每天 过了 凌晨12点以后，必封端口。
天天如此，求解决办法。有偿求

V2ray运行状态：已安装 V2ray正在运行
V2ray配置文件： /etc/v2ray/config.json
V2ray配置信息： 协议： VLESS
IP（地址）： 45.32.x.xxx 端口（
端口）：14635
id（uuid）：xxxxxx-20c6-4397-91bb-ae51a54xxxxxx 流控（flow）：xtls-rprx-direct
加密（encryption）： none 传输协议（network）： TCP 伪装类型（type）：none

伪装域名/主机名（host）/SNI/peer名称：
www.xxxxx.click

底层安全传输（tls）：XTLS

**Comment by Neverends4** [comment]
Isn't this an xray issue? should post it on
[https://github.com/XTLS/Xray-core/issues](url)

**Comment by dllcnx** [comment]
好像xtls目前协议目前有一个漏洞，tls1.3携带tls1.2的特点，会被精准识别，目前解决办法就是要不别用xtls或者使用新版本的流控xtls-rprx-vioson，但是支持新模式流控的ios，mac应用好像特别少。

**Comment by AAlieZZ** [comment]
流控换xtls-rprx-vision
底层安全传输换TLS

**Comment by sndnnlfhvk** [comment]
XTLS很容易被识别，不建议再使用了。

**Comment by sysalong** [comment]
最近两会，等两会过了就好了。

**Comment by adgnaf** [comment]
> XTLS很容易被识别，不建议再使用了。

不使用XTLS的话，建议使用什么协议呢？

**Comment by xuwanjin** [comment]
> XTLS很容易被识别，不建议再使用了。

有相关的资料吗？我想了解一下
