### ISSUE TITLE
geosite:tor 识别tor为国家报错

### ISSUE THREAD

**Issue by mixool** [v2fly/v2ray-core#231]
V2Ray 4.29.0

server routing rules:
```javascript
   {"type": "field","outboundTag": "tortag","domain": ["geosite:tor"]}
```

err log；
```javascript
V2Ray 4.29.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: geosite:tor > v2ray.com/core/infra/conf: failed to load geosite: TOR > v2ray.com/core/infra/conf: country not found: TOR > exit status 255
```
4.28.0版本时可以正常使用
domain-list-community： https://github.com/v2fly/domain-list-community/blob/master/data/tor

**Comment by Loyalsoldier** [comment]
不是把 tor 识别为了国家，只是错误提示没有改过来而已。另外，验证一下 JSON 配置是不是格式不对。

接着下载最新的 `dlc.dat` https://github.com/v2fly/domain-list-community/releases
然后重命名为 `geosite.dat`
最后重新试一试。另外，也试试别的，诸如 `geosite:apple`

**Comment by mixool** [comment]
@Loyalsoldier 
使用最新的bash install-dat-release.sh更新了geosite.dat

复现：

服务器上使用geosite:cn时候v2ray能正常运行，说明JSON配置正确:
{"type": "field","outboundTag": "blocked","domain": ["geosite:private","geosite:cn","geosite:category-ads-all"]}

服务端只需改动上面的geosite:cn为geosite:tor,再运行就会报错

又测试了客户端端，改路由中的geosite:cn为geosite:tor，运行正常

**Comment by kslr** [comment]
手动尝试，不要用工具，确定更新了

**Comment by mixool** [comment]
算了放弃治疗
