### ISSUE TITLE
Any Plan for Code Audit

### ISSUE THREAD

**Issue by sr093906** [v2fly/v2ray-core#2310]
As a key project helping people bypass network restriction, do you have any plan to conduct professional code audit to ensure security of user and project itself?

Maybe cure53?

https://cure53.de/

For audit fee, you can raise money from users and  even proxy services relying on v2ray-core. It is a win-win in my opinion,

**Comment by cross-hello** [comment]
([frightened] Begger don't dare to say anything. )

Feb 8, 2023 20:01:37 sr093906 ***@***.***>:

**Comment by AkinoKaede** [comment]
It's a great idea, but it's hard to raise the money needed to audit the code. As an open source project, V2Ray relies on unpaid audits by developers and researchers.

**Comment by xiaokangwang** [comment]
Based on information from https://www.coreinfrastructure.org/programs/audit-program/, a cost review cost anywhere from 15K ~ 38K for a code base at V2Ray's scale, and the cost would be significantly harder if dependency of V2Ray are included in the review.

We don't currently have any plan for a fundraising at that scale(the corejs author claim to receive as little as $400 a month in the readme, after extensive funding effort). So, to answer your question, we won't be able to afford it even with fundraising. (And it is not like any of the author can just absorb this cost like other minor expense V2Ray have.)

That being said, we are more than happy if there is someone run a code audit of V2Ray, at their own cost, and share their finding with us. 

If anyone are still determined to get V2Ray a code audit, there is a [Red Team Lab](https://www.opentech.fund/labs/red-team-lab/) from [USAGM's OTF](https://www.usagm.gov/networks/otf/) that claim to provide code audit at their own cost.  If someone is willing to contact them and negotiate a code audit, at their own cost, please comment in the thread.

**Comment by xiaokangwang** [comment]
We have received an security audit, see here:
https://github.com/v2fly/v2ray-core/discussions/3096
