### ISSUE TITLE
how to set udp timeout for tproxy

### ISSUE THREAD

**Issue by ion-engine** [v2fly/v2ray-core#2339]
根据 https://toutyrater.github.io/app/tproxy.html 配置透明代理，确认工作正常，但是如果用nslookup 或者dig 查询某些ofline 状态的dns server （不会响应），发现v2ray不会释放关闭udp, 造成 open file的大量堆积，重现过程
## 192.168.2.2 doesn't exist!, just used to reproduce
dig bing.com @192.168.2.2

netstat -an |grep :53 可以看到udp established, 等待了5-10分钟，也没有释放 （lsof 或者netstat -an），重启v2ray后会释放

note: 虽然udp是无状态的，但是netstat 仍然显示established
https://stackoverflow.com/questions/10841678/netstat-na-udp-and-state-established

如果 dns 正常相应的话，netstat udp port 53 established 一会儿就没了

**Comment by mydogshitgold** [comment]
You con configure connection idle timeout with [LevelPolicyObject](http://localhost:8000/config/policy.html#levelpolicyobject).

For example, you can create a new user level `4` and set it's `connIdle` to 5, which means connections will be closed If no data is transmitted in 5 seconds. To apply this policy, set the `settings.userLevel` in your transparent proxy inbound.

NOTE: most of proctols used by V2Ray support user levels

**Comment by ion-engine** [comment]
thank you,  tested below and it works
```
  "policy": {
      "levels": {
          "4": {
              "connIdle" : 180
           }
      }
  },
  "inbounds": [
    {
      "tag":"transparent",
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true,
        "userLevel" : 4
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy" 
        }
      }
    },
```
