### ISSUE TITLE
leastLoad是什么意思？可以给一个配置示例吗？

### ISSUE THREAD

**Issue by draftman9** [v2fly/v2ray-core#2350]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

This issue will be closed immediately.

**Comment by mydogshitgold** [comment]
Please ask questions at [discussions](https://github.com/v2fly/v2ray-core/discussions). The "Issues" is mostly used for reporting bugs or requesting features.

https://github.com/v2fly/v2ray-core/blob/e9943b5a7295ca76341c996a4937f7e03a5015f9/app/router/strategy_leastload.go#L83-L98

**Comment by mkmark** [comment]
https://github.com/v2fly/v2ray-core/pull/589
