### ISSUE TITLE
日志的type和level设置失效

### ISSUE THREAD

**Issue by tecsar9000** [v2fly/v2ray-core#2352]
按照教程设置设置了无日志，但用docker logs仍然看得到访问记录
 "log": {
    "type": "None",
    "level": "None"
  },

**Comment by mydogshitgold** [comment]
Hello,

The toplevel `log` object is composed of two LogSpecObjects, which are `access` and `error`.

To suppress the access log, use
```json
{
  "log": {
    "access": {
      "type": "None"
    }
}
```

To suppress both access and error logs, use
```json
{
  "log": {
    "access": {
      "type": "None"
    },
    "error": {
      "type": "None"
    }
  }
}
```

The log severity level `"None"` does not exist. There are five log severity levels - `"Unknown"`, `"Debug"`, `"Info"`, `"Warning"`, `"Error"`.

At the time of this writing, parts of the [documentation](https://www.v2fly.org/en_US/v5/config/overview.html#logobject) are outdated. When in doubt, it is preferable to refer to protobuf files (.proto), source code, or possibly generated schemas from [this repository](https://github.com/EHfive/v2ray-jsonschema) (note, however, that the generated schema may not be as up-to-date as the source code).

**Comment by tecsar9000** [comment]
Failed to start: main/commands: failed to load config: [/etc/v2ray/config.json] > infra/conf/serial: failed to read config file at line 1 char 208 > json: cannot unmarshal object into Go struct field LogConfig.log.access of type string

**Comment by mydogshitgold** [comment]
The configurations listed here are for the new V5 format. Please run with `v2ray run -format=jsonv5 /etc/v2ray/config.json` to use them, or you will be see this error.

**Comment by KouYiGuo** [comment]
If you use v5 format, you should use number but not string to config log.
Like this.
```
"log": {
    "access": {
      "level": 2,
      "type": 1
    },
    "error": {
      "type": 1,
      "level": 2
    }
  }
```
Level 2 means **Warning**, and type 1 means **Console**. I'm not sure if it'll be changed in the future release.

**Comment by mydogshitgold** [comment]
> you should use number but not string to config log

I don't think that's true, protoc-gen-go also supports string enums.

**Comment by KouYiGuo** [comment]
> > you should use number but not string to config log
> 
> I don't think that's true, protoc-gen-go also supports string enum map.

Yes, you're right.

**Comment by y0umu** [comment]
> If you use v5 format, you should use number but not string to config log. Like this.
> 
> ```
> "log": {
>     "access": {
>       "level": 2,
>       "type": 1
>     },
>     "error": {
>       "type": 1,
>       "level": 2
>     }
>   }
> ```
> 
> Level 2 means **Warning**, and type 1 means **Console**. I'm not sure if it'll be changed in the future release.

That is terrible. There is no mention of such caveats in the v5 doc. And one cannot figure this out until he reads the [source](https://github.com/v2fly/v2ray-core/blob/master/app/log/config.pb.go).
