### ISSUE TITLE
路由器匹配规则问题

### ISSUE THREAD

**Issue by Just-dot** [v2fly/v2ray-core#2365]
1、在直连规则下，使用文档介绍的方式。但依然存在大陆IP地址走代理。
![image](https://user-images.githubusercontent.com/117957988/222093988-9dc7d99f-7fb8-49c1-9f02-491478527c6a.png)
![image](https://user-images.githubusercontent.com/117957988/222094132-7fd1e9c7-2327-4620-8067-3bcd20950f5f.png)

2、通过DOMAIN方式把google已经加入到走代理的方式，但有时候存在依然走直连的情况（这种情况下，偶尔重启服务可以解决，但偶尔重启服务也没有效果）
![image](https://user-images.githubusercontent.com/117957988/222094657-29755b0a-0062-4301-a8db-5cb88ef52722.png)
![image](https://user-images.githubusercontent.com/117957988/222094469-e590bc16-ad82-4576-b4df-fdbd7cbe8e12.png)

**Comment by mydogshitgold** [comment]
Please ask questions at [discussions](https://github.com/v2fly/v2ray-core/discussions). The "Issues" is mostly used for reporting bugs or requesting features.

You are using a custom frontend that potentially have a different configuration. You may be able to get information from their discussion board.

**Comment by Just-dot** [comment]
好。但是配置了代理却没有被代理，并且还是偶发现象。这不应该也是一种错误吗？下面是全部配置的截图：
![image](https://user-images.githubusercontent.com/117957988/222320014-c97bd7d8-0204-47ff-a2d8-dd6c96c511a5.png)
![image](https://user-images.githubusercontent.com/117957988/222320034-0eab659b-bf79-432d-96e2-7ab7b19db197.png)
![image](https://user-images.githubusercontent.com/117957988/222320073-69771007-fe29-4284-b429-704b1030ad68.png)
![image](https://user-images.githubusercontent.com/117957988/222320101-82fac2fc-e810-4bc7-912b-ccb791ec0737.png)

**Comment by mydogshitgold** [comment]
Look, you are using V2RayN, which is a third party v2ray frontend which is not developed here. If you are having troubles with it, you should ask [there](https://github.com/2dust/v2rayN/discussions/categories/q-a).

**Comment by Just-dot** [comment]
抱歉，我在应用程序点击的反馈。我以为你们是一家。
