### ISSUE TITLE
[Feature Request] Launch core with errors in routing rules

### ISSUE THREAD

**Issue by Robot-DaneelOlivaw** [v2fly/v2ray-core#237]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
Client: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 darwin/amd64)

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Filtering advertisements, providing encrypted DNS.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
Currently when users specify a non-existent GeoSite or GeoIP list, core won't launch. Lists with non-existent attributes are correctly dismissed, yet if they're specified alone in a field, core won't launch. (Core doesn't output error message either when a list with non-existent attributes is configured along with other existent lists.) This makes domain lists maintenance a bit harder, since any deletion and rename of lists and attributes result in launch failure in core.

4) What's your expectation?
Core is able to launch even when there're errors in routing rules. Errors are dismissed with correct error message output.

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

- Client configuration with non-existent GeoSite lists:

```javascript
{
        "type": "field",
        "domain": [
          "geosite:appl",
          "geosite:microsoft"
        ],
        "outboundTag": "direct"
}
```

- Client configuration with non-existent GeoIP lists:

```javascript
{
        "type": "field",
        "ip": [
          "geoip:cnn"
        ],
        "outboundTag": "direct"
}
```

- Client configuration with non-existent attributes:

```javascript
{
        "type": "field",
        "domain": [
          "geosite:apple@banana"
        ],
        "outboundTag": "direct"
}
```

- Client configuration with non-existent attributes along with existent lists:

```javascript
{
        "type": "field",
        "domain": [
          "geosite:apple@banana",
          "geosite:microsoft"
        ],
        "outboundTag": "direct"
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

- Client error log with non-existent GeoSite lists:

```
main: failed to read config files: [/Applications/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /Applications/v2ray/config.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: geosite:appl > v2ray.com/core/infra/conf: failed to load geosite: APPL > v2ray.com/core/infra/conf: country not found: APPL > exit status 255
```

- Client error log with non-existent GeoIP lists:

```
main: failed to read config files: [/Applications/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /Applications/v2ray/config.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: cnn > v2ray.com/core/infra/conf: country not found: CNN > exit status 255
```

- Client error log with non-existent attributes:

```
main: failed to create server > v2ray.com/core/app/router: this rule has no effective fields
```

- Client error log with non-existent attributes along with existent lists:

```
[Debug] v2ray.com/core/app/log: Logger started
[Info] v2ray.com/core/app/dns: DNS: created Remote DOH client for https://dns.google/dns-query
[Info] v2ray.com/core/app/dns: DNS: created Local DOH client for https://doh.pub/dns-query
[Info] v2ray.com/core/app/dns: DNS: created localhost client
[Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1080
[Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1081
[Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
[Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:1080
[Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1081
[Warning] v2ray.com/core: V2Ray 4.28.2 started
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by Loyalsoldier** [comment]
Closed due to https://github.com/v2fly/v2ray-core/pull/516
