### ISSUE TITLE
如果使用java代码调用 v2ray

### ISSUE THREAD

**Issue by ABC15859888** [v2fly/v2ray-core#2392]
java 项目种需要使用v2ray 代理接口请求  想请问这种需求 v2ray 可以完成吗

**Comment by mydogshitgold** [comment]
Your question is not about bugs in V2Ray. Please discuss it [here](https://github.com/v2fly/v2ray-core/discussions), and close this issue.

**Comment by ABC15859888** [comment]
> Your question is not about bugs in V2Ray. Please discuss it [here](https://github.com/v2fly/v2ray-core/discussions), and close this issue.

ok
