### ISSUE TITLE
服务无法启动

### ISSUE THREAD

**Issue by xuelongjiang** [v2fly/v2ray-core#2409]
## 你正在使用哪个版本的 V2Ray？

docker  版 mzz2017 / v2rayA   

## 你的使用场景是什么？

做全局代理

## 你看到的异常现象是什么？
访问  http://ip:2017/ 管理页面 点左上角的 “就绪/启动”,返回：
failed to start v2ray-core: timeout: check the log for more information

## 请附上出错时软件输出的错误日志
docker里没有 /var/log/v2ray/error.log文件

## 请附上访问日志
docker里没有 /var/log/v2ray/access.log文件

**Comment by mydogshitgold** [comment]
> docker version mzz2017 / v2rayA

This is repository of [v2fly/v2ray-core](https://github.com/v2fly/v2ray-core), **NOT** [v2rayA/v2rayA](https://github.com/v2rayA/v2rayA), please report bugs [there](https://github.com/v2rayA/v2rayA/issues) and **close** this issue.
