### ISSUE TITLE
where is the download page!!!!!??????

### ISSUE THREAD

**Issue by Denis-666** [v2fly/v2ray-core#2423]
i been search  from 2days ! haven't find V2ray mac os download!

**Comment by mydogshitgold** [comment]
It is on [GitHub release page](https://github.com/v2fly/v2ray-core/releases/download/v5.3.0/v2ray-macos-64.zip)

In the future, please ask questions like this on [discussions](https://github.com/v2fly/v2ray-core/discussions/categories/q-a).

**Comment by Denis-666** [comment]
thx

**Comment by mydogshitgold** [comment]
Please close this issue.
