### ISSUE TITLE
Reset Settings

### ISSUE THREAD

**Issue by amir385276** [v2fly/v2ray-core#2458]
Hi Support Team

I set some settings in the v2rayNG 
but there is a problem 
how to reset settings in the app

thanks

**Comment by mydogshitgold** [comment]
We are no support team and here isn't the [v2rayNG repo](https://github.com/2dust/v2rayNG). it's v2ray-core. To reset all data, use your android settings interface.

**Comment by amir385276** [comment]
Hi mydogshitgold

OK thanks

**Comment by amir385276** [comment]
Solved
