### ISSUE TITLE
Swift & Android or Flutter Package

### ISSUE THREAD

**Issue by Borzalic** [v2fly/v2ray-core#2464]
Hello,

I am interested in using the v2ray project for my mobile applications. I wanted to know if there are any existing Swift and Android or Flutter packages available for the v2ray project? If not, do you have any plans to develop such packages in the near future, or can you recommend any alternative solutions for mobile development? I would appreciate any guidance on this topic.

Thank you in advance for your help.

**Comment by AkinoKaede** [comment]
Sorry, we don't have this.
