### ISSUE TITLE
problem with apache contnet-length

### ISSUE THREAD

**Issue by seezaara** [v2fly/v2ray-core#2469]
hi
i want use nodejs hosts as vpn server and use the http headers on tcp transmit and vmess protocol (for lower price and more vpn for iranian peoples ❤)

but 

the problem is all hosts use apache server and i had to use apache proxy .
and the real problem is apache don't accept request without contnet-length and it don't let more incoming data then contnet-length value

and the alternative solution for `contnet-length` is `Transfer-Encoding: chunked` 

example:
```

HTTP/1.1 200 OK
Content-Type: text/plain
Transfer-Encoding: chunked

7\r\n
Mozilla\r\n
11\r\n
Developer Network\r\n
0\r\n
\r\n
```

> for more info :  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

 **i really need you to add `contnet-length` or `Transfer-Encoding: chunked` in http headers option for encode data in client (and for better in server)**

and for sure this feature is more reliable in filtered network 💯

**Comment by mydogshitgold** [comment]
Your post is quite confusing. If you are using Apache as a reverse proxy WebSocket or HTTP2 transport, you can set arbitrary HTTP headers using the `"headers"` key under the `"streamSettings"` category.

**Comment by seezaara** [comment]
> Your post is quite confusing. If you are using Apache as a reverse proxy WebSocket or HTTP2 transport, you can set arbitrary HTTP headers using the `"headers"` key under the `"streamSettings"` category.

those protocols are corrupted in Iran but http is stable

**Comment by mydogshitgold** [comment]
The [TCP HTTP header](https://www.v2fly.org/config/transport/tcp.html#httpheaderobject) can also be customized. Please read the documentation.

**Comment by seezaara** [comment]
yes you are right but `content-length` is variable by every packet . is there a way to do that?

**Comment by seezaara** [comment]
> The [TCP HTTP header](https://www.v2fly.org/config/transport/tcp.html#httpheaderobject) can also be customized. Please read the documentation.

yes you are right but content-length is variable by every packet . is there a way to do that?

**Comment by mydogshitgold** [comment]
I think you said that already:
> and the alternative solution for contnet-length is Transfer-Encoding: chunked

**Comment by seezaara** [comment]
> I think you said that already:
> 
> > and the alternative solution for contnet-length is Transfer-Encoding: chunked

yes and for that i wrote example of  packet structure ...  it should be a hex number of the length of the content at the beginning of each chunk

**Comment by mydogshitgold** [comment]
This still does not make a lot of sense to me.

Would you mind telling me what exactly you are using as the transport and proxy protocol for v2ray? What do you mean by `nodejs hosts as vpn server` and `use the http headers on tcp transmit`? What are you trying to achieve?

**Comment by AkinoKaede** [comment]
It's seems a problem from upstream.

**Comment by AkinoKaede** [comment]
The HTTP transport layer of V2Ray does not follow RFC, and Content-Length cannot be set.

**Comment by AkinoKaede** [comment]
The behavior of V2Ray also does not meet the standard of `Transfer-Encoding: chunked`
