### ISSUE TITLE
能否默认不依赖v2ctl，让v2ray独立运行？

### ISSUE THREAD

**Issue by forever8938** [v2fly/v2ray-core#247]
目前想让v2ray独立运行，只能修改main/distro/all/all.go，手动编译。目的是减小体积，以便路由器使用。

**Comment by forever8938** [comment]
https://github.com/v2fly/v2ray-core/blob/2fc5f96a1de4faa41b82f9394a5b2427aee002b1/main/distro/all/all.go#L64

**Comment by CalmLong** [comment]
https://steemit.com/cn/@v2ray/meemg-v2ray

**Comment by forever8938** [comment]
> https://steemit.com/cn/@v2ray/meemg-v2ray

@CalmLong 我是要注释掉楼上的62行 ，解除64行的注释。如果调用v2ctl只是为了解析json文件，没有理由不这么做。

**Comment by lp123sun** [comment]
可以用pb格式的配置文件，不调用v2ctl解析json配置文件。

**Comment by qjebbs** [comment]
我也不是很明白强行需要v2ctl加载的意义，这里涉及到的是两个导入包的选择，`json` 和 `jsonem`：

```go
// The following line loads JSON from v2ctl
_ "v2ray.com/core/main/json"
// The following line loads JSON internally
// _ "v2ray.com/core/main/jsonem"
```

根据我的编译试验（做法见 [V2Ray 的模块化](https://steemit.com/cn/@v2ray/meemg-v2ray)）:

- 编译命令是 `GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" .`
- 不作任何裁剪，编译大小为 17M，作为对照数据
- 注释掉尽可能多的包，只剩下：必选包、路由、blackhole、dokodemo、freedom、vmess

选用不同的json包，结果如下：

1. `json` 和 `jsonem`，无论保留哪一个，编译大小还是 17M。即只要保留任一项，裁剪就无效
1. `json` 和 `jsonem` 均注释掉，编译大小9.8M

我的疑惑是：

1. 根据上述结果1，无论选哪一个都裁剪无效，为什么默认不选择对日常使用更方便的那个？
1. 我觉得选择`jsonem`并不会有生态上的问题，v2ctl可以照样提供
1. 根据上述结果2，甚至裁剪的意义也不那么大了，原因下述。

同样是[V2Ray 的模块化](https://steemit.com/cn/@v2ray/meemg-v2ray) 提到的: 

    路由器的 ROM 通常只有 8M 或 16M，而 V2Ray 的程序文件就达到了 7M (v3.4 ARM)，这样就很难塞进路由器了。

裁剪后大小已经超过8M，随着功能的发展，超过16M也指日可待？不一定总要盯着裁剪这一块了吧。可能V2Ray 照顾软路由场景就够了，硬路由除了空间，常常还有浮点指令缺失问题，很难适应的。

**Comment by forever8938** [comment]
@qjebbs 裁剪的意义还是有的，9.8M已经比17M小了很多，用upx可以压到3M左右。当然前提是json要能读取。

**Comment by qjebbs** [comment]
@forever8938 同意，意义还是有的。😁

**Comment by kslr** [comment]
主要的精力还是新功能与优化修复，这于缩减某种程度是背道相驰的。
也没有人开发人员熟悉路由设备，并没有使用场景。
因此不会为了大小而做功能上的阉割。
毕竟10m的设备，现在想要测试，都买不到了

**Comment by wwqgtxx** [comment]
个人意见是把v2ctl这个命令的功能全部整合到v2ray这个命令中，这样在大部分环境中即可只包含一个可执行文档
当然可以依然保留可单独编译出来的v2ctl，以及可以将该部分剪裁掉的选择供低内存设备使用（默认可不提供）

**Comment by kslr** [comment]
现在集中到一起是更好的选择，但目前没有人在这上面工作。
各位也可以尝试一下

**Comment by forever8938** [comment]
#299

**Comment by Loyalsoldier** [comment]
> #299

显然，v2ctl 的功能不仅仅只是加载 JSON 配置。

**Comment by forever8938** [comment]
上述更改，唯一的问题就是不能读取多个配置文件，因为这个需要调用v2ctl的config。如果不需要这个功能，完全可以脱离v2ctl。我在windows，mac，Linux上都使用这样编译出来的二进制。

**Comment by oemaix** [comment]
随身携带的用电池的4G路由器也有使用v2ray的需求. 这类路由器内存都挺小, 浮点性能也很差.

**Comment by qjebbs** [comment]
综合上述大家的讨论，我想解决这个issue的PR最好是这样的：
1. 默认切换到 `jsonem`，使 core 可以独立加载 json
1. 把v2ctl这个命令的功能全部整合到v2ray这个命令中，这样更进一步地，其它命令也不依赖v2ctl，且不会显著增加发布体积
1. 在整合命令过程中，要延续可裁剪的传统美德。即，用户可以注释掉`jsonem`、`jsonem`、命令相关包的方式，移除json和额外命令支持，得到较小的体积

**Comment by forever8938** [comment]
重新测试了一遍，#299 应该是可以的。
v2ray在运行时唯一调用v2ctl的地方就是读取json文件的时候。
使用jsonem可以正常读取json文件，包括多文件的情况。

**Comment by forever8938** [comment]
@qjebbs 不能裁剪的问题解决了，亲测。#351

**Comment by garypang13** [comment]
为啥加载jsonem的情况下,在all.go中做的所有包裁剪就全部不起作用了.在需要json解析配置文件的情况下,该怎么精简v2ray的大小
