### ISSUE TITLE
Suggestions on container tags

### ISSUE THREAD

**Issue by Qusic** [v2fly/v2ray-core#2477]
Current container tags are hard to use and don't follow the convention of common images.
https://github.com/v2fly/v2ray-core/pkgs/container/v2ray/versions?filters%5Bversion_type%5D=tagged

A few suggestions on container tags:
1. please remove arch from the tag and build multi-arch images
2. add some non-fixed tags such as `latest`, `v5`, `v4` to track the latest version or a range of versions

Thanks!

**Comment by AkinoKaede** [comment]
c.c. @xiaokangwang

**Comment by xiaokangwang** [comment]
Currently the container building pipeline don't support multi-arch images, and a separate step would be necessary to get it working.  Pull request on this is welcomed, so long as it don't modify exist building steps.

Tags such as latest will be considered once multi-arch tags are available.

**Comment by Qusic** [comment]
https://github.com/redhat-actions/buildah-build/issues/121#issuecomment-1683691170
seems quite tedious. to keep most of current pipeline implementation intact, another job outside of the strategy matrix is required to merge manifests and push them all together.
or do you mind that we simply remove the strategy matrix and use one single script step to build all archs in one shot. this way the pipeline can be simpler but we will have to invoke podman commands manually instead of using existing actions
