### ISSUE TITLE
Failed at step CAPABILITIES spawning /usr/local/bin/v2ray: Invalid argument

### ISSUE THREAD

**Issue by GH3a** [v2fly/v2ray-core#248]
Oct 02 04:09:28 server systemd[503]: Failed at step CAPABILITIES spawning /usr/local/bin/v2ray: Invalid argument
Oct 02 04:09:28 server systemd[1]: v2ray.service: main process exited, code=exited, status=218/CAPABILITIES
Oct 02 04:09:28 server systemd[1]: Unit v2ray.service entered failed state.
Oct 02 04:09:28 server systemd[1]: v2ray.service failed.
Oct 02 04:09:28 server systemd[1]: v2ray.service holdoff time over, scheduling restart.
Oct 02 04:09:28 server systemd[1]: Stopped V2Ray Service.
Oct 02 04:09:28 server systemd[1]: start request repeated too quickly for v2ray.service
Oct 02 04:09:28 server systemd[1]: Failed to start V2Ray Service.
Oct 02 04:09:28 server systemd[1]: Unit v2ray.service entered failed state.
Oct 02 04:09:28 server systemd[1]: v2ray.service failed.
Oct 02 04:11:46 server systemd[1]: Started V2Ray Service.
Oct 02 04:11:46 server systemd[545]: Failed at step CAPABILITIES spawning /usr/local/bin/v2ray: Invalid argument
Oct 02 04:11:46 server systemd[1]: v2ray.service: main process exited, code=exited, status=218/CAPABILITIES
Oct 02 04:11:46 server systemd[1]: Unit v2ray.service entered failed state.
Oct 02 04:11:46 server systemd[1]: v2ray.service failed.
Oct 02 04:11:46 server systemd[1]: v2ray.service holdoff time over, scheduling restart.
Oct 02 04:11:46 server systemd[1]: Stopped V2Ray Service.
Oct 02 04:11:46 server systemd[1]: Started V2Ray Service.
Oct 02 04:11:46 server systemd[547]: Failed at step CAPABILITIES spawning /usr/local/bin/v2ray: Invalid argument
Oct 02 04:11:46 server systemd[1]: v2ray.service: main process exited, code=exited, status=218/CAPABILITIES
Oct 02 04:11:46 server systemd[1]: Unit v2ray.service entered failed state.
Oct 02 04:11:46 server systemd[1]: v2ray.service failed.
Oct 02 04:11:47 server systemd[1]: v2ray.service holdoff time over, scheduling restart.
Oct 02 04:11:47 server systemd[1]: Stopped V2Ray Service.
Oct 02 04:11:47 server systemd[1]: Started V2Ray Service.
------

1、编辑v2ray的服务配置文件

vi /etc/systemd/system/v2ray.service
2、对文件内容做如下修改：

将：

CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE

改为：

CapabilityBoundingSet=~
AmbientCapabilities=
3、检查v2ray的端口号，必须设定为大于 1024的端口号才行。

做好以上修改后，执行：service v2ray restart 即可启动成功。

-----
按照上面进行修改，的确是可以正常运行了，问题来了
请问，这样修改有没有风险？

**Comment by kslr** [comment]
你不能用透明代理了

**Comment by GH3a** [comment]
> 你不能用透明代理了

但是如果不改，就启动不了，怎么改

**Comment by GH3a** [comment]
/usr/local/bin/v2ray -test -config /usr/local/etc/v2ray/config.json
V2Ray 4.29.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
A unified platform for anti-censorship.
2020/10/02 04:49:38 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Configuration OK.
-----
如果直接运行/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
也是可以正常运行的，唯独
systemctl start v2ray
显示正常运行了，但是看status里面是没有运行的。

**Comment by kslr** [comment]
你这是不是古老的发行版

**Comment by GH3a** [comment]
> 你这是不是古老的发行版

反正是OVZ
2.6.32-042stab136.1

**Comment by kslr** [comment]
太旧了，就地火化吧

**Comment by GH3a** [comment]
> 太旧了，就地火化吧

没办法呀，主机的内核，无能为力
