### ISSUE TITLE
xtls and sidh related bugs

### ISSUE THREAD

**Issue by advancedwebdeveloper** [v2fly/v2ray-core#249]
Hi.
I caught such bugs, related to two dependency packages:

> ~/go_projects/v2ray-core$ go test ./...
> # github.com/xtls/go/cpu
> vendor/github.com/xtls/go/cpu/cpu_x86.s: Assembler messages:
> vendor/github.com/xtls/go/cpu/cpu_x86.s:10: Error: no such instruction: `text ·cpuid(SB),NOSPLIT,$0-24'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:11: Error: junk `(FP)' after expression
> vendor/github.com/xtls/go/cpu/cpu_x86.s:11: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:12: Error: junk `(FP)' after expression
> vendor/github.com/xtls/go/cpu/cpu_x86.s:12: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:14: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:15: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:16: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:17: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:21: Error: no such instruction: `text ·xgetbv(SB),NOSPLIT,$0-8'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:24: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:25: Error: too many memory references for `mov'
> # v2ray.com/core/external/github.com/cloudflare/sidh/internal/utils
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s: Assembler messages:
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:5: Error: no such instruction: `text ·cpuid(SB),NOSPLIT,$0-4'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:6: Error: junk `(FP)' after expression
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:6: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:7: Error: junk `(FP)' after expression
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:7: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:9: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:10: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:11: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:12: Error: too many memory references for `mov'

My compiler and environment is as follows:
> $go env && go version
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfis81/.cache/go-build"
> GOENV="/home/oceanfis81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfis81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfis81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build835009193=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64
> 

CC @thanm @cherrymui

**Comment by rprx** [comment]
Go 1.15.2 的 internal/cpu 存在此问题吗？XTLS 的 go/cpu 是复制它的。

**Comment by advancedwebdeveloper** [comment]
> Go 1.15.2 的 internal/cpu 存在此问题吗？XTLS 的 go/cpu 是复制它的。

I am not understanding your language.
Please explain in English. Tnx

**Comment by rprx** [comment]
Is there the same problem with intenal/cpu of Go 1.15.2? Cause go/cpu of XTLS was copied from it.

**Comment by rprx** [comment]
Is there the same problem with intenal/cpu of Go 1.15.2? Cause go/cpu of XTLS was copied from it.

**Comment by advancedwebdeveloper** [comment]
CC @mengwei-intel @finomeng @mdtoguchi @binghanintel @SunJianIntel @s1061123 @bergwolf @wuxyintel @teawater 

I am using Intel Core2 Quad CPU Q9400

**Comment by rprx** [comment]
https://github.com/XTLS/Go now imports "golang.org/x/sys/cpu" in place of "github.com/xtls/go/cpu".

**Comment by rprx** [comment]
> 
> 
> https://github.com/XTLS/Go now imports "golang.org/x/sys/cpu" in place of "github.com/xtls/go/cpu".

Might have solved this problem in passing, but if not, there's nothing more I can do... Besides, sidh's problem is out of my control.
