### ISSUE TITLE
修改bind ip

### ISSUE THREAD

**Issue by kevinwu-0103** [v2fly/v2ray-core#2507]
有个需求，windows机器用vmware创建ubuntu虚机，网络模式用NAT，宿主机启动v2rayn，bind ip是127.0.0.1，
![企业微信截图_16838796369661](https://github.com/v2fly/v2ray-core/assets/31909047/7c8aa96e-cf1b-4337-81a6-a174f2a3ecb0)
尝试过修改config.json的bind ip，但是启动之后会被重置，怎么破~~~

**Comment by xiaoyang8169** [comment]
windows11用vmware创建centos虚拟机，网络模式为仅主机，windows能ping通虚拟机centos,但开启v2rayN关闭后，宿主机ping不通虚拟机了，老哥知道怎么解决吗
