### ISSUE TITLE
出栈是socks，访问失败

### ISSUE THREAD

**Issue by dragon100a** [v2fly/v2ray-core#2521]
## 你正在使用哪个版本的 V2Ray？

4.45.2

## 你的使用场景是什么？

链式代理

## 你看到的异常现象是什么？

出栈是  socks 的情况下，打不开网页

----------------------------------------------------
我的疑问在于，出栈如果 是 vless或vmess，能用，只是 socks不行
同样的配置文件，用隔壁1.75版本，socks就可以。
因此这边 是不是不支持 socks 出栈？

**服务端配置：**
{
    "log": {
        "loglevel": "none",
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log"
    },
    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query",
            "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "AsIs",
		"domainMatcher": "mph",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private",
					"geoip:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all",
					"geosite:cn"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {			
			"listen": "0.0.0.0",
			"port": 443,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "uuid",
						"level": 0,
						"alterId": 0,
						"email": "u0@email.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
				"wsSettings": {
					"acceptProxyProtocol": false,
					"path": "/path"
				},
                "security": "tls",
                "tlsSettings": {
					"allowInsecure": false,
                    "alpn": [
						"h2",
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/etc/v2ray/fullchain.cer",
                            "keyFile": "/usr/local/etc/v2ray/domain.key"
                        }
                    ]
                }
            }
        }
    ],	
    "outbounds": [
		{		
			"tag": "gotoremote",
			"protocol": "socks",
			"settings": {
				"servers": [
					{
						"address": "1.2.3.4",
						"port": 12345,
						"users": [
							{
								"user": "user",
								"pass": "path"
							}
						]
					}
				]
			}        
		},
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        {
            "tag": "block",
            "protocol": "blackhole",
			"settings": {
				"response": {
					"type": "none"
				}
			}
        }
    ],
	"transport": {
	}
}

**Comment by nursery01** [comment]
V2ray 4和5都支援鏈式代理，我在5.x版本上測試成功

你的設定檔肯定是哪裡寫得不對，你直接升級成5.x，按照5編寫

**Comment by dragon100a** [comment]
> 

感謝幫忙測試，能提供一下你在5.x測試成功的設定檔嗎？

**Comment by xzycn** [comment]
Same issue here with the same version (4.45.2), the captured traffic indicate that no "User authentication request" after client send ACK to packet "Connect to server response".Otherwise, curl works well.
