### ISSUE TITLE
the balancerTag won't take effect unless a observatory probe is probed

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [v2fly/v2ray-core#2525]
此 Issue 

have several [balancerTags ](https://www.v2fly.org/v5/config/router.html#BalancingRuleObject)in routing rule, the [balancerTag ](https://www.v2fly.org/v5/config/router.html#BalancingRuleObject)won't [take effect balancing rule and forward everything to fallbacktag until and unless observatory probe is probed.](https://github.com/v2fly/v2ray-core/pull/1480#issuecomment-1000059447)

possible existing Solution:

- #1480
- Fork: https://github.com/SagerNet/v2ray-core#other (observatory enableConcurrency)

**Comment by AkinoKaede** [comment]
I think `Burst Observatory`  can meet your needed.

<https://www.v2fly.org/en_US/v5/config/service/burstObservatory.html>

**Comment by k79e** [comment]
Is it only for v5 format?

**Comment by AkinoKaede** [comment]
> Is it only for v5 format?

Yes
