### ISSUE TITLE
在meek transportSettings.url 存在BUG 

### ISSUE THREAD

**Issue by yumusb** [v2fly/v2ray-core#2557]
## What version of V2Ray are you using?

V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 windows/amd64)
A unified platform for anti-censorship.

## What's your scenario of using V2Ray?

test meek 

## What problems have you encountered?

"outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "address": "ip",
        "port": 8080,
        "uuid": "_"
      },
      "tag":"outvmess",
      "streamSettings": {
        "transport": "meek",
        "transportSettings": {
          "url": "http://_" // or "https://"
        },
        "security": "none",
        "securitySettings": {}
      }
    }
  ]

当客户端设置中 transportSettings.url 以 http:// 开头且security设置为 none 时，会出现 [Info] transport/internet/request/assembler/simple: failed to send data > transport/internet/request/roundtripper/httprt: unimplemented
看起来是直接获取了  transportSettings.url 直接进行请求
https://github.com/v2fly/v2ray-core/blob/2ac0188d6f3072bb02de4432217b0e0077705b3d/transport/internet/request/roundtripper/httprt/httprt.go#L50
但是我没有找到具体是哪里的hook修改掉了 这个字段 或者是解析配置文件的过程中已经被修改掉了，导致这里出现这个BUG

如果想要兼容之前的设置，感觉这样会更好些。
在transportSettings中指定 host  与 path ，而 UrlPrefix 则根据 outbound item 中 security 的值 来选择是 http:// 还是 https:// 

这样配置文件就可以这样写
"outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "address": "ip",
        "port": 8080,
        "uuid": "_"
      },
      "tag":"outvmess",
      "streamSettings": {
        "transport": "meek",
        "transportSettings": {
        //  "url": "http://_" // or "https://"
          "host":"www.baidu.com"
          "path":"/index.html"
        },
        "security": "none",
        "securitySettings": {}
      }
    }
  ]
甚至像 websocket 一样 支持 自定义的 headers

**Comment by AkinoKaede** [comment]
cc. @xiaokangwang

**Comment by AkinoKaede** [comment]
`security` muse be `tls` or `utls` for Meek outbound.
