### ISSUE TITLE
官方能否维护一个一键安装脚本？

### ISSUE THREAD

**Issue by Frozen1084** [v2fly/v2ray-core#2577]
你好，我是小白用户，一直用网上找到的一键安装脚本来安装v2ray。但这个脚本已经很久不更新了，而且其实我也不是百分百信任这个第三方脚本，但没办法，只有这个脚本安装成功了。
官方能否维护一个一键安装脚本？
如果官方能够维护一个这样的脚本，对小白用户来说太救命了。

虽然我买了VPS好几年了，但对它的操作一直都是，在搬瓦重置系统，打开Xshell，复制脚本URL，复制域名，然后得到配置数据。
当然v2ray也有文档，但老实说，完全看不懂。。。

**Comment by 3vi1d0g** [comment]
# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
 官方的安装脚本

**Comment by Frozen1084** [comment]
> # bash <(curl -L [ https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh ](https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) )
> 官方的安装脚本

谢谢回复，我使用了这个命令，但安装后没有提示我输入域名，也没有输出配置，这只是安装，不是一键安装？

**Comment by 3vi1d0g** [comment]
事实上  配置需要自己写

https://www.v2fly.org

很详细介绍 如何编写json 格式的配置文件

**Comment by Frozen1084** [comment]
所以我请求的功能是"一键安装"。

这应该不是无法实现的吧，第三方都能实现。为什么不能给小白用户行个方便呢。。。
本地的配置文件我是能写，但vps的json怎么写，文档没有说。我估计要在vps创建修改文件，要从vps是什么说起，小白用户才会。

**Comment by YSXX1013** [comment]
> 所以我请求的功能是"一键安装"。
> 
> 这应该不是无法实现的吧，第三方都能实现。为什么不能给小白用户行个方便呢。。。 本地的配置文件我是能写，但vps的json怎么写，文档没有说。我估计要在vps创建修改文件，要从vps是什么说起，小白用户才会。

只能说个人认为这并不应该是官方所应当做的工作，v2ray每个人都有不同的使用方式，同时配置项多而繁杂。如果官方要维护一个可用的一键安装脚本的话必然要为此所分出不少人力。但现在明显v2ray这边的人手不是很多，制作一件安装脚本的事情还是留给第三方做比较好。

**Comment by geektcp** [comment]
事实上官方提供的脚本不能用sh或者bash执行。必须授权成可执行文件，然后直接执行，跟脚本内部用到某些特别命令有关。
错误做法，例如
```bash
sh install-release.sh
bash install-release.sh
```

正确的做法是：
```bash
wget https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
chmod u+x install-release.sh
./install-release.sh
```

**Comment by iKira** [comment]
说白了就是不想自己投入精力，想别人都做好了喂到你嘴里。

**Comment by Frozen1084** [comment]
一个简化使用门槛的请求而已。所以你是吃某些东西吃多了，看什么都是喂的吗？

**Comment by iKira** [comment]
> 一个简化使用门槛的请求而已。所以你是吃某些东西吃多了，看什么都是喂的吗？

就你这种人，你看看有没有人理你，求人喂饭还求出优越感来了，搞笑。

**Comment by Frozen1084** [comment]
就说你吃多了某些东西，不要拿"这种人/优越感"之类的话乱扣。没人理我是我的事，我搞笑也和你没毛关系，你就不能滚出吗？


----

一个普通用户，不想了解什么视频解压编码的，只想播放一个视频。不想了解什么网络协议，只想打开一个网页。不想了解什么编程编码，只想用个界面化的操作系统。所以有了播放器，有了浏览器，有了Window系统，这不是很普通的事吗？我想不到我的这个请求和这些有什么区别。当然我也想不到我的小白请求会有什么原因冒犯到谁，当然更想不到我哪里有搞笑天赋，哈哈。

**Comment by iKira** [comment]
> 就说你吃多了某些东西，不要拿"这种人/优越感"之类的话乱扣。没人理我是我的事，我搞笑也和你没毛关系，你就不能滚出吗？
> 
> 一个普通用户，不想了解什么视频解压编码的，只想播放一个视频。不想了解什么网络协议，只想打开一个网页。不想了解什么编程编码，只想用个界面化的操作系统。所以有了播放器，有了浏览器，有了Window系统，这不是很普通的事吗？我想不到我的这个请求和这些有什么区别。当然我也想不到我的小白请求会有什么原因冒犯到谁，当然更想不到我哪里有搞笑天赋，哈哈。

你滚出Github吧，想白嫖还扯一堆废话，你也不用回复我了，懒得看你。

**Comment by Frozen1084** [comment]
请你滚出我的帖子，谢谢。

**Comment by PandaRyshan** [comment]
你好，

1. 讨论的帖子建议发到 [Discussions](https://github.com/v2fly/v2ray-core/discussions) 版块
2. 我有一个自己用的脚本，愿意的话可以试试看: [链接](https://github.com/PandaRyshan/ladder)
3. 关于提问/讨论，请学习一下这篇文章：[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by YSXX1013** [comment]
> 就说你吃多了某些东西，不要拿"这种人/优越感"之类的话乱扣。没人理我是我的事，我搞笑也和你没毛关系，你就不能滚出吗？
> 
> 一个普通用户，不想了解什么视频解压编码的，只想播放一个视频。不想了解什么网络协议，只想打开一个网页。不想了解什么编程编码，只想用个界面化的操作系统。所以有了播放器，有了浏览器，有了Window系统，这不是很普通的事吗？我想不到我的这个请求和这些有什么区别。当然我也想不到我的小白请求会有什么原因冒犯到谁，当然更想不到我哪里有搞笑天赋，哈哈。

正如你这段话所说，一个普通用户是不想了解这些实现细节的，因此你更应该去使用一些将v2ray当作核心的第三方一键安装脚本/第三方gui之类的工具，而不是在官方这里要求提供安装脚本。正如你想要播放器的时候不会去找ffmpeg这个命令行工具的开发者问“我要一个GUI播放器！ffmpeg就不能官方做一个么？”，或者你想要浏览器的时候也不会去找curl/openssl/asio之类网络相关的命令行工具/库的作者说“你都写网络库了，不能写个浏览器么？”。v2ray/xray/clash在这里扮演的也是相同的角色，如果你正有此方面的需求，建议去第三方寻找帮助，很多安装脚本本身是开源的/实际上是开源的，如果你实在不信任可以先自行审计后再使用。

**Comment by Frozen1084** [comment]
> 正如你这段话所说，一个普通用户是不想了解这些实现细节的，因此你更应该去使用一些将v2ray当作核心的第三方一键安装脚本/第三方gui之类的工具，而不是在官方这里要求提供安装脚本。正如你想要播放器的时候不会去找ffmpeg这个命令行工具的开发者问“我要一个GUI播放器！ffmpeg就不能官方做一个么？”，或者你想要浏览器的时候也不会去找curl/openssl/asio之类网络相关的命令行工具/库的作者说“你都写网络库了，不能写个浏览器么？”。v2ray/xray/clash在这里扮演的也是相同的角色，如果你正有此方面的需求，建议去第三方寻找帮助，很多安装脚本本身是开源的/实际上是开源的，如果你实在不信任可以先自行审计后再使用。

不敢苟同。按照你的说法，install-release.sh 这样的脚本都是外道。
对 curl 说，"你不能写个浏览器吗"，和对 firefox 说，"你就不能优化默认配置吗？我用够了 一键优化firefox.exe了"，是两个完全不同的事。

**Comment by lmkyl** [comment]
一键安装

bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --1.8.3

一键配置


curl -Lo /usr/local/etc/xray/config.json https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/config_server.json

【估计你不会这一步】
手动生成/修改一下UUID、
手动生成/修改一下公钥、私钥

重启
systemctl restart xray

**Comment by AkinoKaede** [comment]
As it stands, we don't have enough time to develop new projects.

**Comment by Coolingsex** [comment]
> > 一个简化使用门槛的请求而已。所以你是吃某些东西吃多了，看什么都是喂的吗？
> 
> 就你这种人，你看看有没有人理你，求人喂饭还求出优越感来了，搞笑。

翻墙用户很多不是程序员，我就是。一个小白，只能按别人的操作指南一步一步操作，如果官方的确实安全性能更放心。

**Comment by UnrealCherry** [comment]
> 说白了就是不想自己投入精力，想别人都做好了喂到你嘴里。

人家小白  想要一个不夹带私货的官方脚本不是很正常？ 连我程序员都懒得看文档只想赶紧安装完事。 你这么苛刻干什么 真是纯屌丝 不能理解别人的需求是什么 。

**Comment by vxtls** [comment]
shell脚本其实都是开源的，代码可查，所以不必担心夹带私货
