### ISSUE TITLE
attrs Method Not Work 

### ISSUE THREAD

**Issue by Hifi-Games-Pro** [v2fly/v2ray-core#2579]
Hello,
I put 
domain: youtube.com
attrs: attrs[':method'] == 'GET'
Outbound: Bypass

but it's not bypassing Get request for the domain youtube.com

can I apply a proxy on the POST request and Bypass the Get request data? it is possible for a particular domain or whole traffic? I want to bypass incoming traffic and proxying outgoing traffic.

**Comment by nursery01** [comment]
> I want to bypass incoming traffic and proxying outgoing traffic.

I don't think this can be achieve

**Comment by AkinoKaede** [comment]
Because TLS encrypts HTTP requests, this feature is not available for `youtube.com`.

**Comment by nursery01** [comment]
阿秋，v2未來還有什麼好玩的東西可以整上麽
