### ISSUE TITLE
Loadbalancer should work in parallel mode and using long alive connection

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#2602]
## What version of V2Ray are you using?
5.7.0

## What's your scenario of using V2Ray?
Using it with v2raya

## What problems have you encountered?
Loadbalancer is not work in parallel mode

LB test should be parallel send. Not one by one. 
e.g. It now behaves like this. There are 2 servers, LB wait 10s to connect serverA, then wait 10s to connect serverB

There latency detect period should be made into random. Or it's may not safe. At least add an option to let user choose.

The lb's behavior seems wrong. I see it connect then close connect very fast, It look like tcping.
Well about this fast close of a connection. it seems an another bug.

## What's your expectation?
LB should work in parallel mode, with keep alive connection.
And it may be configured with random mode, and this random delay may let user choose the ceil/floor time.

## Please attach your configuration here
"balancers":[{"tag":"ext","selector":["『srv2』","『srv』","『srv3』"],"strategy":{"type":"leastping","settings":{"observerTag":"ext"}}},{"tag":"proxy","selector":["『srvw-2』","『srvw-1』"],"strategy":{"type":"leastping","settings":{"observerTag":"proxy"}}}]

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
See 

- https://github.com/v2fly/v2ray-core/issues/2525#issuecomment-1554427262
