### ISSUE TITLE
regexp not work in router rule [duplicated domain in 2 different rule, one is not LB another is LB's]

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#2604]
## What version of V2Ray are you using?
5.7.0 with v2raya (the rule it uses is v4 format)

**See the end for updated infomation**

## What's your scenario of using V2Ray?
Use it with route rule 

## What problems have you encountered?
Rule not work

## Please attach your configuration here
{"type":"field","balancerTag":"ext123","inboundTag":["rule-http_ipv4","rule-socks"],"domain":["regexp:superhenhentai.org$"]}

But the route don't change.

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

## If V2Ray service is abnormal, please attach journal log here

20230719

I find this is caused by the domain I want to use with LB have a duplicated routing rule.
e.g. google.com have rule near the head of rule, But later there is an rule to let it to use LB.
It won't use LB anymore.

**Comment by kingwilliam** [comment]
[on v2fly v5 config file structure](https://www.v2fly.org/v5/config/router.html#ruleobject)

```
=====[ orginal ]=====
{
    "type":"field",
    "balancerTag":"ext123",
    "inboundTag":["rule-http_ipv4","rule-socks"],
    "domain":["regexp:superhenhentai.org$"]
}

=====[ modify ]=====
{
    // "type":"field",                  <--- remark
    "balancingTag":"ext123",    <--- change  "balancerTag" to "balancingTag"
    "inboundTag":["rule-http_ipv4","rule-socks"],
    "domain":["regexp:superhenhentai.org$"]
}
```

**Comment by k79e** [comment]
Thanks for replying, I'll forward it to v2raya developer

**Comment by k79e** [comment]
This might work as intented. But the rule should have a weight, Then it would be better.
