### ISSUE TITLE
使用链式代理socks失败

### ISSUE THREAD

**Issue by mttbx** [v2fly/v2ray-core#2619]
使用链式代理socks失败，以下是错误：

`failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72`

我使用anxray的链式代理功能是可以实现的，已经成功。另外同样的配置，复制过去，xray也可以链接成功。

以下是主要的outbound配置，如果使用mess作为proxy则可以使用，可见是socks的问题。
```
{
      "tag": "proxy",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "xxx",
            "port": 2222,
            "users": [
              {
                "pass": "sss",
                "user": "zzz"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": ""
      },
      "proxySettings": {
        "tag": "chain"
      }
    },
    {
      "tag": "chain",
      "protocol": "shadowsocks", // 代理服务器
      "settings": {
        "servers": [
          {
            "address": "111.111.111.111",
            "port": 16001,
            "method": "aes-256-gcm",
            "password": "asdf",
            "ota": false
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": ""
      }
    }
}
```

**Comment by mttbx** [comment]
我使用anxray的链式代理功能是可以实现的，已经成功。

**Comment by AkinoKaede** [comment]
Could you try to set `transportLayer` to `true`? 
<https://www.v2fly.org/config/outbounds.html#proxysettingsobject>

**Comment by mttbx** [comment]
No, the error is the same.

**Comment by jschen1** [comment]
请问后面怎么解决的，现在我碰到了 同样的问题

**Comment by mttbx** [comment]
用xray

**Comment by mttbx** [comment]
The SOCKS5 server is not mine. And I just download the release of this project. I did't compile it myself.

**Comment by linuxkungfu** [comment]
your socks server is enable tls, if enable,please use follow in outbounds block:
`"streamSettings": {
        "network": "tcp",
        "security": "tls",
         "tlsSettings":{
            "allowInsecure": true
         }
      },`

**Comment by mttbx** [comment]
I don't use this config anymore, maybe another people will meet the same problem, and test if the solution is ok.

**Comment by jingyuLin1999** [comment]
anyone solved this issue？
