### ISSUE TITLE
jsonv5 is nearly unusable for homebrew installed v2ray

### ISSUE THREAD

**Issue by frankli0324** [v2fly/v2ray-core#2620]
> https://github.com/v2fly/discussion/issues 已无法使用

### What version of V2Ray are you using?

V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.6 darwin/amd64)
A unified platform for anti-censorship.

### What's your scenario of using V2Ray?

irrelevant

### What did you see?

homebrew services still locked to old configuration format (v2ray run -c /usr/local/etc/v2ray/config.json)

also `-d` option doesn't pick up v5.json files.

![image](https://github.com/v2fly/v2ray-core/assets/20221896/176b6968-766e-4295-aafd-023cdd30a681)

### What's your expectation?

1. fix configdir option so v2ray could pick up `config.v5.json` etc. and parse them correctly.

2. modify https://github.com/Homebrew/homebrew-core/blob/master/Formula/v2ray.rb#L65 to `run -d /usr/local/etc/v2ray` so brew v2ray keeps jsonv4 backward compatibility while jsonv5 users could also live.

modifying the plist file would be overridden when updated, so that's not an option

**Comment by frankli0324** [comment]
I'm thankful for the lack of documentation and the fact that it wasted me an entire night on this. I would love to write a detailed bug report but I need sleep.

**Comment by frankli0324** [comment]
the reason to the `confdir` issue is that `filepath.Ext` only returns the last part of a file (see https://pkg.go.dev/path/filepath#example-Ext)

https://github.com/v2fly/v2ray-core/blob/master/main/commands/run.go#L122

and someone somehow decided to use `.xx.json` as the "extension" of the config file. absolute genius.

**Comment by AkinoKaede** [comment]
V2Ray will try to use all config loaders, but v4 loaders may not throw any expectation when loading v5 format config.
I think we can add a priority for config loaders. @xiaokangwang

**Comment by AkinoKaede** [comment]
I think the first issue is fixed.
