### ISSUE TITLE
Can it be compiled with go1.21 version supported?

### ISSUE THREAD

**Issue by jan-bar** [v2fly/v2ray-core#2644]
## What version of V2Ray are you using?
I compile my code using the version：`github.com/v2fly/v2ray-core/v5 v5.7.0`

## What's your scenario of using V2Ray?
use v2ray code in my project

## What problems have you encountered?
The go1.21 version is released, I want to use this version to compile my project, but the following error is prompted

```sh
# github.com/quic-go/quic-go/internal/qtls
pkg\mod\github.com\quic-go\quic-go@v0.33.0\internal\qtls\go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/
quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

## What's your expectation?
The v2ray project can be compiled using go1.21 version

Description of related libraries：https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions

I found that the latest version of the library already supports go1.21, and I hope v2ray can follow up
  https://github.com/quic-go/quic-go/blob/v0.37.3/internal/qtls/go121.go

**Comment by AkinoKaede** [comment]
We are waiting the Go 1.21 support of quic-go .

**Comment by AkinoKaede** [comment]
Please wait for the next release.

**Comment by jan-bar** [comment]
> Please wait for the next release.

looking forward to the new version, thank you very much

**Comment by stefanb** [comment]
`quic-go` 0.37.x already support Go 1.20 and 1.21. See https://github.com/quic-go/quic-go/releases

Judging by the diff https://github.com/v2fly/v2ray-core/compare/v5.7.0...master it just needs a new release.

**Comment by jan-bar** [comment]
@stefanb Thank you very much, my own project also tested like this without any problem. Still looking forward to the release of the latest version of v2ray-core

**Comment by seyedmmousavi** [comment]
the home-brew can't install v2ray because of this error and someone like me is stopped.

**Comment by AkinoKaede** [comment]
v5.9.0 had been released.

**Comment by chenrui333** [comment]
homebrew side is good with the new release, https://github.com/Homebrew/homebrew-core/pull/152400
