### ISSUE TITLE
内置时区不准确

### ISSUE THREAD

**Issue by wode2016501** [v2fly/v2ray-core#2655]
## 你正在使用哪个版本的 V2Ray？
5.x

## 你的使用场景是什么？
google

## 你看到的异常现象是什么？
日志时间不对导致访问不了https

/sdcard/v2ray $ ls
bak          geosite.dat  v2ctl.sig  v2ray.sig
config.json  systemd      v2ray      vpoint_socks_vmess.json
geoip.dat    v2ctl        v2ray.log  vpoint_vmess_freedom.json
/sdcard/v2ray $ date
Sat Aug 19 10:53:32 CST 2023
/sdcard/v2ray $ v2ray
A unified platform for anti-censorship.

Usage:

	v2ray <command> [arguments]

The commands are:

	run           run V2Ray with config
	api           call V2Ray API
	convert       convert config files
	test          test config files
	tls           TLS tools
	uuid          generate new UUID
	verify        verify if a binary is officially signed
	version       print V2Ray version

Use "v2ray help <command>" for more information about a command.

Additional help topics:

	config-merge  config merge logic
	format-loader config formats and loading

Use "v2ray help <topic>" for more information about that topic.

/sdcard/v2ray $ v2ray run
V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.5 android/arm64)
A unified platform for anti-censorship.
2023/08/19 02:53:39 Using default config:  /sdcard/v2ray/config.json
^C
/sdcard/v2ray $ v2ray run
V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.5 android/arm64)
A unified platform for anti-censorship.
2023/08/19 02:53:43 Using default config:  /sdcard/v2ray/config.json
2023/08/19 02:53:48 [Info] features: You are using a deprecated feature: root fakedns settings. Please update your config file with latest configuration format, or update your client software.
2023/08/19 02:53:48 [Warning] V2Ray 5.7.0 started
2023/08/19 02:54:00 127.0.0.1:47794 accepted http://www.baidu.com/ [DIRECT]

^C/sdcard/v2ray export TZ=Asia/Shanghaiai

/sdcard/v2ray $ date
Sat Aug 19 10:54:38 CST 2023

/sdcard/v2ray $ v2ray run
V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.5 android/arm64)
A unified platform for anti-censorship.
2023/08/19 02:54:42 Using default config:  /sdcard/v2ray/config.json
2023/08/19 02:54:43 [Info] features: You are using a deprecated feature: root fakedns settings. Please update your config file with latest configuration format, or update your client software.

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by AkinoKaede** [comment]
V2Ray uses the time zone set by the system.
Time zone error does not affect the normal work of V2Ray.
