### ISSUE TITLE
V2rayN 无法连接

### ISSUE THREAD

**Issue by SunYang99999** [v2fly/v2ray-core#2658]
我是电脑小白，不懂编程。在youtube自学了搬瓦工搭建VPS，成功了一天，电脑和手机都可以使用。第二天电脑收都无法使用。重新操作一天后仍无法使用。在CMD 里PING 过，网站可以是可以连接的，请问问题出现在哪里？哪位大神给解答以下，万分感谢！

2023/08/21 23:36:40 [Warning] [3676089287] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://asyhly2022.top/a7f48c79-b69e-4068-cbcb-4a48f4670c9b):  > dial tcp 104.194.77.192:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://asyhly2022.top/a7f48c79-b69e-4068-cbcb-4a48f4670c9b):  > dial tcp 104.194.77.192:443: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://asyhly2022.top/a7f48c79-b69e-4068-cbcb-4a48f4670c9b):  > dial tcp: lookup asyhly2022.top: operation was canceled] > common/retry: all retry attempts failed

**Comment by ShaderFallback** [comment]
建议买现成机场省时省力
