### ISSUE TITLE
能不能限定v2ray不要使用某些端口啊

### ISSUE THREAD

**Issue by harvey-git** [v2fly/v2ray-core#2663]
## 你正在使用哪个版本的 V2Ray？

5.7

## 你的使用场景是什么？

正常使用
## 你看到的异常现象是什么？

v2ray启动后会占用不少端口，问题是，我最近在用android studio，其虚拟机通过 adb连接时总会被 v2ray 占用5037端口，导致adb没法连接，临时关闭 v2ray后adb连上后，再启动 v2ray就没有影响，问题是期间 adb
不能退出，一旦退出 v2ray 就会再次占用 5037

## 你期待看到的正常表现是怎样的？
在配置文件里设定部份保留端口， v2ray始终不会使用这些保留端口建立通讯。

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by nursery01** [comment]
這個可能不是v2ray的問題，它默認應該是會佔用40000以上的埠，你有沒有改作業系統的默認動態埠？

**Comment by harvey-git** [comment]
> 可能不是v2ray的问题，它默认应该是会占用40000以上的端口，你有没有改作业系统的默认动态端口？

已经解决了，朋友给了我一个命令。
`net.ipv4.ip_local_reserved_ports= 1024-4096`
