### ISSUE TITLE
v2ray  5.7 版本如何配置server  client 使用  

### ISSUE THREAD

**Issue by Seriels** [v2fly/v2ray-core#2668]
我花了一整天寻找 但是网上都是过期版本的 配置 文件    我需要一份最新的config.json  配置

**Comment by computerscot** [comment]
https://cscot.pages.dev/2023/05/31/v2ray-meek/

**Comment by Seriels** [comment]
@computerscot   。。。。这个比较简单 我是想通过nginx 代理链接的 。。。

**Comment by rootkiter** [comment]
什么叫 nginx 代理链接... v2ray 和 nginx 没啥关系吧

**Comment by ecrasy** [comment]
> @computerscot 。。。。这个比较简单 我是想通过nginx 代理链接的 。。。

[v2ray over nginx](https://github.com/ecrasy/BuildOpenWrt/wiki)

**Comment by maike2019** [comment]
到现在我都不清楚V5 的DNS该如何配置？ 还是否兼容V4的 DNS呢？
