### ISSUE TITLE
How to specify config in repo so it uses that

### ISSUE THREAD

**Issue by killerlearner** [v2fly/v2ray-core#2676]
Hello I am trying to deploy it but facing server not responding to port. And I can't edit config in that place so is there any way that I can place config in repo and it uses that while deploying like specify port, ip, vmess I'd 

 And someone specify demo config in reply also.
Thanx

**Comment by Comradin** [comment]
> Hello I am trying to deploy it but facing server not responding to port. And I can't edit config in that place so is there any way that I can place config in repo and it uses that while deploying like specify port, ip, vmess I'd
> 
> And someone specify demo config in reply also. Thanx

I am new to this project like you, but you should have a look into the Readme as there is a link to the documentation and especially to the guide for novices like you and me.

Please have a look [here](https://www.v2fly.org/en_US/guide/start.html).

**Comment by Comradin** [comment]
@killerlearner I would suggest, that you should take minute and reflect on your issue.

You are asking for help but you do not provide any form of information on what you did but instead you demand a demo config.

Ask yourself, how could a person help you as your issue lacks all necessary informations on how to reproduce your setup.

Are you running on Windows, macOS, Linux, a server, a desktop, some Raspberry Pi setup.

Self compiled (as the config-in-repository suggest) but then you write, that you cannot change the config on your target system?

Are you running the software in a Docker container? Maybe you are missing the option to mount a local config into the container on startup?

**Comment by killerlearner** [comment]
@Comradin yeah I am deploying in docker so can you tell me where should I put this server config file in repo to make it automatically detect and take this config be default.
