### ISSUE TITLE
Reverse proxy not documented or supported in V5 config

### ISSUE THREAD

**Issue by OurebiKitsu** [v2fly/v2ray-core#2688]
## What version of V2Ray are you using?

V2Ray 5.7.0

## What's your scenario of using V2Ray?

Set up reverse proxy from server to client

## What problems have you encountered?

The reverse proxy functionality is not documented or supported in json v5 config. The config format is shown below:

```json
{
    "log": {},
    "dns": {},
    "router": {},
    "inbounds": [],
    "outbounds": [],
    "services": {}
}
```

While in json v4, we can set up the "reverse" config:

```json
{
    "log": {},
    "api": {},
    "dns": {},
    "routing": {},
    "policy": {},
    "inbounds": [],
    "outbounds": [],
    "transport": {},
    "stats": {},
    "reverse": {},
    "fakedns": [],
    "browserForwarder": {},
    "observatory": {}
}
```

Is it because the reverse proxy support has been removed from v5 config or it's just not documented yet?
I tried looking at source code for v5 config, but couldn't find any relevant to reverse proxy.

Thanks

**Comment by AkinoKaede** [comment]
```json
{
    "services": {
      "reverse": {
          "bridgeConfig": {
             "tag": "example",
             "domain": "example.v2fly.org"
          },
          "portalConfig": {
             "tag": "example",
             "domain": "example.v2fly.org"
          }
       }
   }
}
```

**Comment by OurebiKitsu** [comment]
Thanks. It works without problem.
