### ISSUE TITLE
无法代理 SMTP 协议

### ISSUE THREAD

**Issue by hanyujie2002** [v2fly/v2ray-core#2689]
## 你正在使用哪个版本的 V2Ray？
V 5.1.0

## 你的使用场景是什么？

用 thunderbird 通过 SMTP 协议（通过 proxifier 强制代理 SMTP 流量）发电子邮件

## 你看到的异常现象是什么？

无法代理 SMTP 协议，邮件无法发送

## 你期待看到的正常表现是怎样的？
正常代理 SMTP 协议，邮件正常发送

## 请附上你的配置
```

<!-- 提交 issue 前，请隐去服务器域名或 IP 地址 -->

**服务端配置：**


```javascript
// 在这里附上服务器端配置文件
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"port": 10086,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "b831381d-6324-4d53-ad4f-8cda48b30811",
						"level": 1,
						"alterId": 0
					}
				]
			},
			"streamSettings": {
				"network": "ws"
			},
			"sniffing": {
				"enabled": false, // 已禁用流量探测
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIP"
			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
        }
		//include_out_config
		//
	],
	"dns": {
		"servers": [
			"https+local://dns.google/dns-query",
			"8.8.8.8",
			"1.1.1.1",
			"localhost"
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            }
			,
			{
				"type": "field",
				"domain": [
				],
				"outboundTag": "blocked"
			}			,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
			//include_ban_ad
			//include_rules
			//
		]
	},
	"transport": {
		"kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        }
	}
}
```

**客户端配置：**

```javascript
// 在这里附上客户端配置
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": false, // 已关闭流量探测
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "*.*.*.*",
            "port": 10086,
            "users": [
              {
                "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {}
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "dns": {
    "servers": [
      "1.0.0.1",
      "8.8.8.8"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "domain": [
          "domain:example-example.com",
          "domain:example-example2.com"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}
```
## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by hanyujie2002** [comment]
> Try `metadataOnly: true`, vanilla SMTP as a server-speaks-first protocol should only work under this condition.

No, this still don't work

current client config:
```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "metadataOnly": true
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "metadataOnly": true
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "*.*.*.*",
            "port": 10086,
            "users": [
              {
                "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {}
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "dns": {
    "servers": [
      "1.0.0.1",
      "8.8.8.8"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "domain": [
          "domain:example-example.com",
          "domain:example-example2.com"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}
```
current server config:

```javascript
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"port": 10086,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "b831381d-6324-4d53-ad4f-8cda48b30811",
						"level": 1,
						"alterId": 0
					}
				]
			},
			"streamSettings": {
				"network": "ws"
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				],
				"metadataOnly": true
			}
		}
		//include_ss
		//include_socks
		//include_mtproto
		//include_in_config
		//
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIP"
			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
        }
		//include_out_config
		//
	],
	"dns": {
		"servers": [
			"https+local://dns.google/dns-query",
			"8.8.8.8",
			"1.1.1.1",
			"localhost"
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            }
			,
			{
				"type": "field",
				"domain": [
				],
				"outboundTag": "blocked"
			}			,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
			//include_ban_ad
			//include_rules
			//
		]
	},
	"transport": {
		"kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        }
	}
}

```
## How to reproduce the bug:

1. copy the configs respectively in client side and server side
2. use proxifier to force proxy the traffic to local port 10808
3. try to send email using thunderbird

**Comment by AkinoKaede** [comment]
Can you try to set Socks proxy in Thunderbird?

**Comment by hanyujie2002** [comment]
No, the Socks proxy setting in Thunderbird don't work for SMTP protocol @AkinoKaede 
Now, I have to make Thunderbird in the whitelist of proxifier to make it work.

**Comment by hanyujie2002** [comment]
No, still don't work.

P.S. the log in the server side, is it the problem of my network setting of my server? @AkinoKaede 

```
2023/09/22 23:07:10 [Warning] [4071812026] app/dispatcher: default route for tcp:smtp.office365.com:587
2023/09/22 23:10:56 [Debug] app/log: Logger started
2023/09/22 23:10:56 [Info] app/dns: DNS: created Local DOH client for https://dns.google/dns-query
2023/09/22 23:10:56 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
2023/09/22 23:10:56 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
2023/09/22 23:10:56 [Info] app/dns: DNS: created localhost client
2023/09/22 23:10:56 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:8899
2023/09/22 23:10:56 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:8899
2023/09/22 23:10:56 [Warning] V2Ray 5.1.0 started
2023/09/22 23:11:11 [Info] [727457235] proxy/vmess/inbound: received request for tcp:smtp.office365.com:587
2023/09/22 23:11:11 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:11 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
2023/09/22 23:11:11 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:4020::2] [2603:1036:307:48da::2] [2603:1036:307:48e4::2] [2603:1036:307:4869::2]] 63.35687ms
2023/09/22 23:11:11 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [40.97.223.114 52.96.64.194 52.96.188.146 52.96.166.146] 63.688184ms
2023/09/22 23:11:11 [Warning] [727457235] app/dispatcher: default route for tcp:smtp.office365.com:587
2023/09/22 23:11:11 [Info] [727457235] proxy/freedom: opening connection to tcp:smtp.office365.com:587
2023/09/22 23:11:11 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:11 [Debug] app/dns: DOHL//dns.google cache HIT smtp.office365.com -> [40.97.223.114 52.96.64.194 52.96.188.146 52.96.166.146 2603:1036:307:4020::2 2603:1036:307:48da::2 2603:1036:307:48e4::2 2603:1036:307:4869::2]
2023/09/22 23:11:11 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:307:48e4::2]:587
2023/09/22 23:11:11 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:48e4::2]:587
2023/09/22 23:11:27 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:27 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
2023/09/22 23:11:27 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:48dd::2] [2603:1036:307:4054::2] [2603:1036:307:4000::2] [2603:1036:307:2840::2]] 21.691479ms
2023/09/22 23:11:27 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [52.96.10.82 52.96.166.242 52.96.166.194 52.96.55.194] 33.146386ms
2023/09/22 23:11:27 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:307:4000::2]:587
2023/09/22 23:11:27 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:4000::2]:587
2023/09/22 23:11:38 [Info] [4046423811] proxy/vmess/inbound: received request for tcp:outlook.office365.com:993
2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google querying: outlook.office365.com.
2023/09/22 23:11:38 [Info] [2013699662] proxy/vmess/inbound: received request for tcp:outlook.office365.com:993
2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google querying: outlook.office365.com.
2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google got answer: outlook.office365.com. TypeAAAA -> [[2603:1036:a03:6e::2] [2603:1036:307:2860::2] [2603:1036:a03:28::2] [2603:1036:307:48e7::2]] 4.510162ms
2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google got answer: outlook.office365.com. TypeA -> [52.96.166.18 52.96.110.66 52.96.31.2 52.96.188.162] 4.610644ms
2023/09/22 23:11:38 [Warning] [2013699662] app/dispatcher: default route for tcp:outlook.office365.com:993
2023/09/22 23:11:38 [Info] [2013699662] proxy/freedom: opening connection to tcp:outlook.office365.com:993
2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:38 [Debug] app/dns: DOHL//dns.google cache HIT outlook.office365.com -> [52.96.166.18 52.96.110.66 52.96.31.2 52.96.188.162 2603:1036:a03:6e::2 2603:1036:307:2860::2 2603:1036:a03:28::2 2603:1036:307:48e7::2]
2023/09/22 23:11:38 [Info] [2013699662] proxy/freedom: dialing to tcp:[2603:1036:307:48e7::2]:993
2023/09/22 23:11:38 [Info] [2013699662] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:48e7::2]:993
2023/09/22 23:11:38 [Warning] [4046423811] app/dispatcher: default route for tcp:outlook.office365.com:993
2023/09/22 23:11:38 [Info] [4046423811] proxy/freedom: opening connection to tcp:outlook.office365.com:993
2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:38 [Debug] app/dns: DOHL//dns.google cache HIT outlook.office365.com -> [52.96.166.18 52.96.110.66 52.96.31.2 52.96.188.162 2603:1036:a03:6e::2 2603:1036:307:2860::2 2603:1036:a03:28::2 2603:1036:307:48e7::2]
2023/09/22 23:11:38 [Info] [4046423811] proxy/freedom: dialing to tcp:52.96.166.18:993
2023/09/22 23:11:38 [Info] [4046423811] transport/internet/tcp: dialing TCP to tcp:52.96.166.18:993
2023/09/22 23:11:38 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
2023/09/22 23:11:38 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
2023/09/22 23:11:43 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:43 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
2023/09/22 23:11:43 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:28e0::2] [2603:1036:307:1001::2] [2603:1036:307:28f4::2] [2603:1036:a03::2]] 13.236653ms
2023/09/22 23:11:43 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [52.96.59.162 52.96.166.242 52.96.110.66 52.96.42.66] 13.329554ms
2023/09/22 23:11:43 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:307:1001::2]:587
2023/09/22 23:11:43 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:1001::2]:587
2023/09/22 23:11:59 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:11:59 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
2023/09/22 23:11:59 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [40.99.229.162 40.99.229.210 40.99.140.226 40.99.230.2] 22.832694ms
2023/09/22 23:11:59 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:30c:c74::2] [2603:1036:30c:c82::2] [2603:1036:30c:901::2] [2603:1036:30c:d3::2]] 22.988396ms
2023/09/22 23:11:59 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:30c:c82::2]:587
2023/09/22 23:11:59 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:30c:c82::2]:587
2023/09/22 23:12:11 [Debug] app/dns: DOHL//dns.google cleanup smtp.office365.com.
2023/09/22 23:12:11 [Debug] app/dns: DOHL//dns.google cleanup outlook.office365.com.
2023/09/22 23:12:15 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
2023/09/22 23:12:15 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
2023/09/22 23:12:15 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [52.96.110.2 52.96.188.178 40.97.222.194 40.97.221.114] 23.790077ms
2023/09/22 23:12:15 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:48e4::2] [2603:1036:307:48de::2] [2603:1036:307:4868::2] [2603:1036:307:294b::2] [2603:1036:307:4920::2] [2603:1036:307:28d4::2] [2603:1036:307:4070::2] [2603:1036:307:100d::2]] 31.293399ms
2023/09/22 23:12:15 [Info] [727457235] proxy/freedom: dialing to tcp:40.97.222.194:587
2023/09/22 23:12:15 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:40.97.222.194:587
2023/09/22 23:12:32 [Info] [727457235] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:smtp.office365.com:587 > common/retry: [dial tcp [2603:1036:307:48e4::2]:587: i/o timeout dial tcp [2603:1036:307:4000::2]:587: i/o timeout dial tcp [2603:1036:307:1001::2]:587: i/o timeout dial tcp [2603:1036:30c:c82::2]:587: i/o timeout dial tcp 40.97.222.194:587: i/o timeout] > common/retry: all retry attempts failed
2023/09/22 23:12:32 [Info] [727457235] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2023/09/22 23:13:11 [Debug] app/dns: DOHL//dns.google cleanup smtp.office365.com.
```

**Comment by AkinoKaede** [comment]
> No, still don't work.
> 
> P.S. the log in the server side, is it the problem of my network setting of my server? @AkinoKaede
> 
> ```
> 2023/09/22 23:07:10 [Warning] [4071812026] app/dispatcher: default route for tcp:smtp.office365.com:587
> 2023/09/22 23:10:56 [Debug] app/log: Logger started
> 2023/09/22 23:10:56 [Info] app/dns: DNS: created Local DOH client for https://dns.google/dns-query
> 2023/09/22 23:10:56 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
> 2023/09/22 23:10:56 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
> 2023/09/22 23:10:56 [Info] app/dns: DNS: created localhost client
> 2023/09/22 23:10:56 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:10086
> 2023/09/22 23:10:56 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:10086
> 2023/09/22 23:10:56 [Warning] V2Ray 5.1.0 started
> 2023/09/22 23:11:11 [Info] [727457235] proxy/vmess/inbound: received request for tcp:smtp.office365.com:587
> 2023/09/22 23:11:11 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:11 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
> 2023/09/22 23:11:11 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:4020::2] [2603:1036:307:48da::2] [2603:1036:307:48e4::2] [2603:1036:307:4869::2]] 63.35687ms
> 2023/09/22 23:11:11 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [40.97.223.114 52.96.64.194 52.96.188.146 52.96.166.146] 63.688184ms
> 2023/09/22 23:11:11 [Warning] [727457235] app/dispatcher: default route for tcp:smtp.office365.com:587
> 2023/09/22 23:11:11 [Info] [727457235] proxy/freedom: opening connection to tcp:smtp.office365.com:587
> 2023/09/22 23:11:11 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:11 [Debug] app/dns: DOHL//dns.google cache HIT smtp.office365.com -> [40.97.223.114 52.96.64.194 52.96.188.146 52.96.166.146 2603:1036:307:4020::2 2603:1036:307:48da::2 2603:1036:307:48e4::2 2603:1036:307:4869::2]
> 2023/09/22 23:11:11 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:307:48e4::2]:587
> 2023/09/22 23:11:11 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:48e4::2]:587
> 2023/09/22 23:11:27 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:27 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
> 2023/09/22 23:11:27 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:48dd::2] [2603:1036:307:4054::2] [2603:1036:307:4000::2] [2603:1036:307:2840::2]] 21.691479ms
> 2023/09/22 23:11:27 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [52.96.10.82 52.96.166.242 52.96.166.194 52.96.55.194] 33.146386ms
> 2023/09/22 23:11:27 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:307:4000::2]:587
> 2023/09/22 23:11:27 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:4000::2]:587
> 2023/09/22 23:11:38 [Info] [4046423811] proxy/vmess/inbound: received request for tcp:outlook.office365.com:993
> 2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google querying: outlook.office365.com.
> 2023/09/22 23:11:38 [Info] [2013699662] proxy/vmess/inbound: received request for tcp:outlook.office365.com:993
> 2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google querying: outlook.office365.com.
> 2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google got answer: outlook.office365.com. TypeAAAA -> [[2603:1036:a03:6e::2] [2603:1036:307:2860::2] [2603:1036:a03:28::2] [2603:1036:307:48e7::2]] 4.510162ms
> 2023/09/22 23:11:38 [Info] app/dns: DOHL//dns.google got answer: outlook.office365.com. TypeA -> [52.96.166.18 52.96.110.66 52.96.31.2 52.96.188.162] 4.610644ms
> 2023/09/22 23:11:38 [Warning] [2013699662] app/dispatcher: default route for tcp:outlook.office365.com:993
> 2023/09/22 23:11:38 [Info] [2013699662] proxy/freedom: opening connection to tcp:outlook.office365.com:993
> 2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:38 [Debug] app/dns: DOHL//dns.google cache HIT outlook.office365.com -> [52.96.166.18 52.96.110.66 52.96.31.2 52.96.188.162 2603:1036:a03:6e::2 2603:1036:307:2860::2 2603:1036:a03:28::2 2603:1036:307:48e7::2]
> 2023/09/22 23:11:38 [Info] [2013699662] proxy/freedom: dialing to tcp:[2603:1036:307:48e7::2]:993
> 2023/09/22 23:11:38 [Info] [2013699662] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:48e7::2]:993
> 2023/09/22 23:11:38 [Warning] [4046423811] app/dispatcher: default route for tcp:outlook.office365.com:993
> 2023/09/22 23:11:38 [Info] [4046423811] proxy/freedom: opening connection to tcp:outlook.office365.com:993
> 2023/09/22 23:11:38 [Debug] app/dns: domain outlook.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:38 [Debug] app/dns: DOHL//dns.google cache HIT outlook.office365.com -> [52.96.166.18 52.96.110.66 52.96.31.2 52.96.188.162 2603:1036:a03:6e::2 2603:1036:307:2860::2 2603:1036:a03:28::2 2603:1036:307:48e7::2]
> 2023/09/22 23:11:38 [Info] [4046423811] proxy/freedom: dialing to tcp:52.96.166.18:993
> 2023/09/22 23:11:38 [Info] [4046423811] transport/internet/tcp: dialing TCP to tcp:52.96.166.18:993
> 2023/09/22 23:11:38 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
> 2023/09/22 23:11:38 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
> 2023/09/22 23:11:43 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:43 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
> 2023/09/22 23:11:43 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:28e0::2] [2603:1036:307:1001::2] [2603:1036:307:28f4::2] [2603:1036:a03::2]] 13.236653ms
> 2023/09/22 23:11:43 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [52.96.59.162 52.96.166.242 52.96.110.66 52.96.42.66] 13.329554ms
> 2023/09/22 23:11:43 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:307:1001::2]:587
> 2023/09/22 23:11:43 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:307:1001::2]:587
> 2023/09/22 23:11:59 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:11:59 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
> 2023/09/22 23:11:59 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [40.99.229.162 40.99.229.210 40.99.140.226 40.99.230.2] 22.832694ms
> 2023/09/22 23:11:59 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:30c:c74::2] [2603:1036:30c:c82::2] [2603:1036:30c:901::2] [2603:1036:30c:d3::2]] 22.988396ms
> 2023/09/22 23:11:59 [Info] [727457235] proxy/freedom: dialing to tcp:[2603:1036:30c:c82::2]:587
> 2023/09/22 23:11:59 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:[2603:1036:30c:c82::2]:587
> 2023/09/22 23:12:11 [Debug] app/dns: DOHL//dns.google cleanup smtp.office365.com.
> 2023/09/22 23:12:11 [Debug] app/dns: DOHL//dns.google cleanup outlook.office365.com.
> 2023/09/22 23:12:15 [Debug] app/dns: domain smtp.office365.com will use DNS in order: [DOHL//dns.google UDP:8.8.8.8:53 UDP:1.1.1.1:53 localhost]
> 2023/09/22 23:12:15 [Info] app/dns: DOHL//dns.google querying: smtp.office365.com.
> 2023/09/22 23:12:15 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeA -> [52.96.110.2 52.96.188.178 40.97.222.194 40.97.221.114] 23.790077ms
> 2023/09/22 23:12:15 [Info] app/dns: DOHL//dns.google got answer: smtp.office365.com. TypeAAAA -> [[2603:1036:307:48e4::2] [2603:1036:307:48de::2] [2603:1036:307:4868::2] [2603:1036:307:294b::2] [2603:1036:307:4920::2] [2603:1036:307:28d4::2] [2603:1036:307:4070::2] [2603:1036:307:100d::2]] 31.293399ms
> 2023/09/22 23:12:15 [Info] [727457235] proxy/freedom: dialing to tcp:40.97.222.194:587
> 2023/09/22 23:12:15 [Info] [727457235] transport/internet/tcp: dialing TCP to tcp:40.97.222.194:587
> 2023/09/22 23:12:32 [Info] [727457235] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:smtp.office365.com:587 > common/retry: [dial tcp [2603:1036:307:48e4::2]:587: i/o timeout dial tcp [2603:1036:307:4000::2]:587: i/o timeout dial tcp [2603:1036:307:1001::2]:587: i/o timeout dial tcp [2603:1036:30c:c82::2]:587: i/o timeout dial tcp 40.97.222.194:587: i/o timeout] > common/retry: all retry attempts failed
> 2023/09/22 23:12:32 [Info] [727457235] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > io: read/write on closed pipe
> 2023/09/22 23:13:11 [Debug] app/dns: DOHL//dns.google cleanup smtp.office365.com.
> ```

Probably, the connection between SMTP server and Proxy server wasn't opened successfully.

**Comment by hanyujie2002** [comment]
I look up the document and find that to fight spam, that VPS service provider restricts outbound connections on ports 25, 465, and 587. Problem solved. Thank you @AkinoKaede
