### ISSUE TITLE
V2Ray 5.7.0 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [v2fly/v2ray-core#2695]
## What version of V2Ray are you using?

V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)

## What's your scenario of using V2Ray?

fakedns+tproxy

## What problems have you encountered?

panic: runtime error: invalid memory address or nil pointer dereference

segmentation violation

## What's your expectation?
if the client tries connect an unknown fakedns IP from pool before restart v2ray, don't panic

## Please attach your configuration here

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

## If V2Ray service is abnormal, please attach journal log here

```
sudo systemctl restart v2ray && sudo journalctl -f -t v2ray
v2ray[3520417]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)
v2ray[3520417]: A unified platform for anti-censorship.
v2ray[3520417]: Configuration OK.
v2ray[3520433]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)
v2ray[3520433]: A unified platform for anti-censorship.
v2ray[3520433]: panic: runtime error: invalid memory address or nil pointer dereference
v2ray[3520433]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa92261]
v2ray[3520433]: goroutine 74 [running]:
v2ray[3520433]: github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*Holder).GetFakeIPForDomain3(0xc000919770?, {0xc000912000?, 0x7f21657bf0a8?}, 0xc0?, 0x8c?)
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:37 +0x21
v2ray[3520433]: github.com/v2fly/v2ray-core/v5/app/dns/fakedns.(*HolderMulti).GetFakeIPForDomain3(0xc0007e8cd0?, {0xc000912000, 0x12}, 0x0?, 0x0?)
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/app/dns/fakedns/fake.go:167 +0xed
v2ray[3520433]: github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSServer).QueryIP(0xc000334d20, {0x1361648?, 0xc0007e8cc0?}, {0xc000912000, 0x12}, {0x0?, 0xc000912018?, 0xc0006e84c0?}, {0x0, 0x1, ...}, ...)
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/app/dns/nameserver_fakedns.go:39 +0x133
v2ray[3520433]: github.com/v2fly/v2ray-core/v5/app/dns.(*Client).QueryIP(0xc000810090, {0x1361680, 0xc00050d3b0}, {0xc000912000, 0x12}, {0x1b?, 0x0?, 0x0?})
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/app/dns/nameserver.go:196 +0x1c7
v2ray[3520433]: github.com/v2fly/v2ray-core/v5/app/dns.(*DNS).lookupIPInternal(0xc0001fc540, {0xc000912000, 0x13}, {0x90?, 0x7b?, 0x9f?})
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/app/dns/dns.go:297 +0x666
v2ray[3520433]: github.com/v2fly/v2ray-core/v5/app/dns.(*FakeDNSClient).LookupIPv6(0x0?, {0xc000912000?, 0x0?})
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/app/dns/fakedns.go:29 +0x2b
v2ray[3520433]: github.com/v2fly/v2ray-core/v5/proxy/dns.(*Handler).handleIPQuery(0xc0008625a0?, 0x5966, 0x1c, {0xc000912000, 0x13}, {0x1354900, 0xc0007ea110})
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/proxy/dns/dns.go:247 +0x86
v2ray[3520433]: created by github.com/v2fly/v2ray-core/v5/proxy/dns.(*Handler).Process.func2
v2ray[3520433]:         github.com/v2fly/v2ray-core/v5/proxy/dns/dns.go:199 +0x2ab
v2ray[3520445]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)
v2ray[3520445]: A unified platform for anti-censorship.
v2ray[3520445]: Configuration OK.
v2ray[3520455]: V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.8 linux/amd64)
v2ray[3520455]: A unified platform for anti-censorship.
```

**Comment by AkinoKaede** [comment]
Do you mean there will be panic when a user connects to a Fake DNS IP that doesn't exist?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Do you mean there will be panic when a user connects to a Fake DNS IP that doesn't exist?

I had clients running with cached previously assigned IP from FakeDNS pool which were trying to reconnect to those IPs between restarting V2 fly.

**Comment by AkinoKaede** [comment]
> > Do you mean there will be panic when a user connects to a Fake DNS IP that doesn't exist?
> 
> I had clients running with cached previously assigned IP from FakeDNS pool which were trying to reconnect to those IPs between restarting V2 fly.

But the error log shows that an error occurred when querying FakeDNS.

**Comment by AkinoKaede** [comment]
> > > Do you mean there will be panic when a user connects to a Fake DNS IP that doesn't exist?
> > 
> > 
> > I had clients running with cached previously assigned IP from FakeDNS pool which were trying to reconnect to those IPs between restarting V2 fly.
> 
> But the error log shows that an error occurred when querying FakeDNS.

This appears to be because V2Ray receives the query before it has completed initialization.

**Comment by AkinoKaede** [comment]
I infer that this is because the FakeDNS app has not completed initialization after V2Ray's DNS app has been started. There is usually only a millisecond interval between this. Can you reproduce this issue?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, I had seen it crashing with those log messages again after restarting v2ray for reloading (DNS unrelated) configuration change.
