### ISSUE TITLE
Reply package rerouting

### ISSUE THREAD

**Issue by Vik098St** [v2fly/v2ray-core#2698]
Hi everyone!!! Many thanks to the developers of V2Ray for a great platform that has been helping me with my studies for months. Recently I had an unusual task: there are 3 VPS (A, B, C) with V2Ray servers running at and I need to send a request to A, then from A send it to B, get answer from target site, and send the response coming back to B to the client not through A, but through C. Like this:

[ Client ] ->[ Proxy A ] ->[ Proxy B ] -> [ Internet ] ->[ Proxy B ] ->[ Proxy C ] ->[ Client ]
            

Can you please tell me if it is possible to solve the problem using V2Ray router capabilities?

**Comment by AkinoKaede** [comment]
This cannot be done using V2Ray.
