### ISSUE TITLE
[Bug]: iPad局域网无法使用youtube应用播放视频

### ISSUE THREAD

**Issue by padixa** [v2fly/v2ray-core#2700]
## What version of V2Ray are you using?

Clash for windows V0.20.34

## What's your scenario of using V2Ray?

Ipad打开Youtube应用, 设置中使用代理, 通过局域网连接电脑上的Clash for Windows

## What problems have you encountered?

在Clash打开局域网模式, 无论有无使用Tun模式, iPad中的Youtube应用播放视频时一直现在加载中.
但是如果使用iPad中的Chrome播放视频就没有任何问题, 只是Youtubey应用不能播放.
难道youtube应用直接忽略ios设置里的系统代理, 直接本地网络访问导致失败？还是说有什么检测机制Clash没跟上？ 即便把Clash改成全局模式也没用 而用Chrome浏览器打开youtube看视频就正常…youtube应用就无法播放视频
奇怪的是日志也并没有显示来自局域网的ipad的youtube应用请求*.googlevideo.com，不知道为什么
已在Clash for Windows提过问题, 但并无回应:  [[Bug]: iPad局域网无法使用youtube应用播放视频](https://github.com/Fndroid/clash_for_windows_pkg/issues/4832)

## What's your expectation?

无论是否使用Youtube应用或者Chrome打开youtube网页都能正常播放视频.

复现步骤:

1.Clash打开允许局域网访问.
2.iPad设置wifi中的代理为局域网地址
3.iPad打开Youtube应用并尝试播放视频(页面加载没问题, Chrome播放视频没问题, 只是在Youtube应用播放视频一直加载中...)

**Comment by AkinoKaede** [comment]
The repo of clash is <https://github.com/Dreamacro/clash>

**Comment by ChangAnB** [comment]
看来不是个例 我使用v2rayng安卓端也复现了这个bug

**Comment by HyperSimon** [comment]
+1 用 Clash X android 也复现了

**Comment by SuperRorange** [comment]
ios youtube视频走了udp，而clash默认不代理udp，需要改下clash的yaml文件绕一下，并在ios网络里手动设置dns

在yaml文件里添加，并把wifi dns改为你的电脑ip（clash在跑的设备）
udp: true
dns:
  enable: true
  enhanced-mode: fake-ip  # 推荐使用 fake-ip，对 UDP 转发最友好
  listen: 0.0.0.0:53
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
