### ISSUE TITLE
quic-go@v0.33.0 can not be built on go 1.21

### ISSUE THREAD

**Issue by bi4tms** [v2fly/v2ray-core#2701]
The version of Go in Lean's openwrt has been updated to 1.21. As a result, v2ray can not been built correctly. 
The log is shown below：
Building targets
github.com/quic-go/quic-go/internal/qtls
# github.com/quic-go/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration

make[3]: *** [Makefile:44: /workdir/openwrt/build_dir/target-aarch64_generic_musl/v2ray-plugin-5.7.0/.built] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/passwall_packages/v2ray-plugin'
time: package/feeds/passwall_packages/v2ray-plugin/compile#0.54#0.21#0.57
    ERROR: package/feeds/passwall_packages/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall_packages/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2

Please make quic-go compatible for go 1.21.
Thank you very much.

**Comment by swxk521** [comment]
+1

**Comment by ecrasy** [comment]
很多openwrt的最新源碼都切換到Go 1.21了，
開發組是否考慮Release一個適配Go 1.21的版本？

**Comment by JimmyHuang454** [comment]
我做了一些实验性的 [修改](https://github.com/JimmyHuang454/v2ray-core/tree/dev)，给 QUIC 加上了Hysteria的拥塞算法（包括 BBR 和 Brutal），Hysteria 的 QUIC 是支持 Go 1.21 的，很方便就可以移植过来。
