### ISSUE TITLE
无法使用https远程配置文件

### ISSUE THREAD

**Issue by bonjour-py** [v2fly/v2ray-core#2710]
## 你正在使用哪个版本的 V2Ray？

V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)

V2Ray 5.4.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.2 linux/amd64)   in v2fly docker image

## 你的使用场景是什么？

无

## 你看到的异常现象是什么？

无法启动服务器
无法使用https远程配置文件

## 你期待看到的正常表现是怎样的？

![image](https://github.com/v2fly/v2ray-core/assets/33248848/421ec386-54a2-4688-ba95-acfbd13759ee)

## 请附上你的配置

**服务端配置：**

```bash
v2ray run -config https://**********/v2ray.json
```

**客户端配置：**

```javascript

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
Failed to start: main/commands: failed to load config: [https://************/v2ray.json] > fail to load https://*****/v2ray.json: open https://*************/v2ray.json: no such file or directory
```

**客户端错误日志：**

```javascript

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by bonjour-py** [comment]
找到了替代方案
`sh -c 'wget -O - https://************/v2ray.json | v2ray run'`
但是建议更新一下文档，有些并不一致

**Comment by AkinoKaede** [comment]
This feature had been removed
