### ISSUE TITLE
HTTPUpgrade transport still requires support from the CDN provider to pass WebSocket

### ISSUE THREAD

**Issue by zirconpl** [v2fly/v2ray-core#2734]
v2ray v5.10.1 of has introduced a new `HTTPUpgrade transport` protocol, described as:

> It is a reduced version of WebSocket Transport that can pass many reverse proxies and CDNs without running a WebSocket protocol stack.

After testing, when the CDN provider's WebSocket feature is turned off, it's not possible to pass data normally because the first action of HTTPUpgrade is to request an upgrade to WebSocket. It seems that HTTPUpgrade transport cannot be used with CDN providers that do not support WebSocket, so compared to the previous WebSocket transport, HTTPUpgrade transport does not seem to have a clear advantage.

**Comment by xiaokangwang** [comment]
HTTPUpgrade does not require either client to server to support websocket protocol stack, thus allow them to decrease resource usage, simplify implementation, improve speed and make it possible to control packet length precisely.

It still use the same underlying mechanic of WebSocket to create a bidirectional channel, so it would works only on the platforms WebSocket works, and this is expected. Meek can pass CDN that does not support websocket, although it is kind of slow so it is not designed as a daily driver protocol.

**Comment by ytai-chn** [comment]
Very interesting, I used HTTPUpgrade to send traffic through Azure CDN and it worked, but I had no success using websocket before. According to Azure documentation, Azure CDN does not support websocket. Maybe I need to continue to investigate on it

**Comment by zhu327** [comment]
@xiaokangwang Can HTTP Upgrade be used in a 0-RTT manner, similar to WebSocket, to reduce the latency of the first packet?

**Comment by xiaokangwang** [comment]
> @xiaokangwang Can HTTP Upgrade be used in a 0-RTT manner, similar to WebSocket, to reduce the latency of the first packet?

This is possible but currently unimplemented.
