### ISSUE TITLE
基于serverless+nginx+tls+ws+v2ray部署的问题

### ISSUE THREAD

**Issue by luneice** [v2fly/v2ray-core#2748]

**Comment by ziqizh** [comment]
> 在v2ray没有记录到对应的错误日志。很明显，是因为v2ray拒绝了连接。
我印象中v2ray拒绝连接也会有日志？有没有可能是nginx的问题？

我最近也在弄serverless部署，你用的是哪个云服务啊？

**Comment by luneice** [comment]
> > 在v2ray没有记录到对应的错误日志。很明显，是因为v2ray拒绝了连接。
> 
> 我印象中v2ray拒绝连接也会有日志？有没有可能是nginx的问题？
> 
> 我最近也在弄serverless部署，你用的是哪个云服务啊？

阿里云的函数计算，基于这个仓库构建docker镜像，加入nginx做反向代理，文件日志放oss然后挂载在container中。我怀疑是函数计算的问题，按照nginx+tls+ws的做法，ssl证书在nginx端，有了serverless后证书放在了serverless端。

**Comment by ziqizh** [comment]
所以用serverless的时候证书是由阿里云解密的，然后明文转发给docker container？相当于镜像里只用了nginx转发明文ws？

我能想到几个问题：
1. 函数计算是事件驱动，所以是stateless对吧？每次有请求进来的时候它都会开一个新的实例，会有什么问题么
2. 阿里云理论上能看到解密后的流量
3. 函数计算会不会keep connection？我知道很多CDN回源的时候用的是HTTP/1.1，所以connection直接关掉了。

我猜你用函数计算是为了降低成本，你有没有考虑过Google Cloud的Cloud Run？类似于阿里的应用引擎SAE，但支持scale to zero。我打算拿这个搭个试试。现在头疼的是SSL证书放哪儿、config存哪儿之类的。

**Comment by luneice** [comment]
> 所以用serverless的时候证书是由阿里云解密的，然后明文转发给docker container？相当于镜像里只用了nginx转发明文ws？
> 
> 我能想到几个问题：
> 
> 1. 函数计算是事件驱动，所以是stateless对吧？每次有请求进来的时候它都会开一个新的实例，会有什么问题么
> 2. 阿里云理论上能看到解密后的流量
> 3. 函数计算会不会keep connection？我知道很多CDN回源的时候用的是HTTP/1.1，所以connection直接关掉了。
> 
> 我猜你用函数计算是为了降低成本，你有没有考虑过Google Cloud的Cloud Run？类似于阿里的应用引擎SAE，但支持scale to zero。我打算拿这个搭个试试。现在头疼的是SSL证书放哪儿、config存哪儿之类的。

不完全是出于成本的考虑，主要是部署的问题，云原生部署会方便很多。
