### ISSUE TITLE
'attr' does not work with HTTP sniffed of Socks inbound

### ISSUE THREAD

**Issue by r3a1d3a1** [v2fly/v2ray-core#2774]
Currently, 'attrs' (e.g. `"attrs[':path'].find('keyword')!=-1",`) only works with HTTP inbound.
It'd be great if it was supported with Socks mode as well.

I tried to get around the issue by firing up a second v2ray instance to have an inbound Socks and an outbound HTTP and then use 'attrs' routing on the other instance with an inbound HTTP, but for unknown reasons, it did not work. (Sniffing was enabled.)

P.S. I'm well aware that it does not work with TLS-wrapped HTTP.

**Comment by medunea** [comment]
I was wondering if I could create an HTTP proxy server using Golang myself, decrypt TLS, and provide more advanced configurations
