### ISSUE TITLE
是否可以增加一个下载arm32-v7l

### ISSUE THREAD

**Issue by nigelink** [v2fly/v2ray-core#280]
bcm4709无法使用arm32-v7a,只能使用arm32-v5a

**Comment by kslr** [comment]
我查了一些资料，是因为这个阉割了FPU，所以没有支持计划

**Comment by barlowhaydnb** [comment]
预计arm32-v7l和现有的arm32-v5a有什么区别呢？前者性能会更好吗

**Comment by rprx** [comment]
Go 似乎只能编译 v7a

**Comment by rprx** [comment]
以及，那个是 v5，不是 v5a。a 代表 Cortex-A 系列，v5 和 v6 没有。

**Comment by rampageX** [comment]
@nigelink https://github.com/rampageX/arm-static-bins/tree/master/v2ray

**Comment by rprx** [comment]
> 
> 
> @nigelink https://github.com/rampageX/arm-static-bins/tree/master/v2ray

看起来这个也是 v2ray-linux-arm32-v5

**Comment by rprx** [comment]
事实上，由于 v7l 阉割掉了 FPU，的确只能用 arm32-v5，因为 `GOARM` 就是用于设置运行时 CPU 浮点协处理器的版本。

> GOARM=5: use software floating point; when CPU doesn't have VFP co-processor
> GOARM=6: use VFPv1 only; default if cross compiling; usually ARM11 or better cores (VFPv2 or better is also supported)
> GOARM=7: use VFPv3; usually Cortex-A cores

https://golang.org/doc/install/source#environment

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/fhs-install-v2ray/issues/181#issuecomment-733665622
