### ISSUE TITLE
文档不完善 FakeDNS 自定义地址池启动失败 报错invalid CIDR address

### ISSUE THREAD

**Issue by Victor2333** [v2fly/v2ray-core#2805]
## 你正在使用哪个版本的 V2Ray？
v5.12.1

## 你的使用场景是什么？
tproxy with fakedns
linux64

## 你看到的异常现象是什么？
fakedns无法自定义地址池

Failed to start: main/commands: failed to create server > app/dns: fail to create fake dns > invalid CIDR address:

## 请附上你的配置
```json
{
"dns": {
 "fakeDns": {
        "pools": [
            {
                "ipPool": "198.18.0.0/15",
                "lruSize": 65535
            },
                        {
                "ipPool": "fc00::/18",
                "lruSize": 65535
            }
        ]
    }}
}
```

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
Failed to start: main/commands: failed to create server > app/dns: fail to create fake dns > invalid CIDR address:

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by Victor2333** [comment]
应该是因为v5的文档还不对
https://www.v2fly.org/v5/config/dns.html#dnsobject
目前看起来正确的配置应该是：
```json
"dns": {
  "fakedns": [....]
}
```

**Comment by AkinoKaede** [comment]
> 应该是因为v5的文档还不对 https://www.v2fly.org/v5/config/dns.html#dnsobject 目前看起来正确的配置应该是：
> 
> ```json
> "dns": {
>   "fakedns": [....]
> }
> ```

Yes, FakeDNS has been refactored but the documentation has not been modified.
