### ISSUE TITLE
Tun配置解析

### ISSUE THREAD

**Issue by hann-wang** [v2fly/v2ray-core#2815]
## What version of V2Ray are you using?

5.13.0

## What problems have you encountered?

无法正确解析Tun sniffing config中的`destOverride`。根本原因是services部分的配置使用了raw json，没有经过类似`InboundConfig`中的检查和转换，因此`destOverride`字段实际应为`destinationOverride`，这与文档记载不符。（See also https://github.com/v2fly/v2ray-core/discussions/2749 ）

另外直接使用Ip byte[]配置接口ip非常不自然，建议利用IpAddr string（maybe https://github.com/v2fly/v2ray-core/commit/e05823a9e68d7ec5794ec6e92ebd551ebacda9f1 ），可以利用`ConvertTimeParseIp`进行转换。

## Please attach your configuration here

```
{
    "services": {
        "tun": {
            "name": "tun0",
            "mtu": 1500,
            "tag": "tun",
            "ips": [
                {
                    "ipAddr": "192.168.18.1",
                    "prefix": 24
                }
            ],
            "routes": [
                {
                    "ipAddr": "0.0.0.0",
                    "prefix": 0
                }
            ],
            "enablePromiscuousMode": true,
            "enableSpoofing": true,
            "sniffingSettings": {
                "enabled": true,
                "destinationOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    }
}
```

**Comment by AkinoKaede** [comment]
I think the dispatcher can get sniffing settings from the context.

https://github.com/v2fly/v2ray-core/blob/458db3954f76bbf7ce621a24151d9d5469d8b6fb/app/tun/handler_tcp.go#L100-L106

**Comment by AkinoKaede** [comment]
Hmm, about `destinationOverride` and `destOverride`, I found other similar configuration items using different ways of deserializing. I think I should rewrite this part of the code.

https://github.com/v2fly/v2ray-core/blob/a96d34384dd9aadd4fbc3099d1d7fc5df77a4999/infra/conf/cfgcommon/sniffer/sniffer.go#L12-L16
