### ISSUE TITLE
关于多配置文件载入的BUG

### ISSUE THREAD

**Issue by aybru** [v2fly/v2ray-core#284]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.30.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 windows/amd64)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Socks5

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
示例：
 v2ray -confdir 基础配置 -confdir 专用配置目录 -c 专用配置
结果BUG：
1.-confdir 多次指定 只有最后一个confdir生效载入
2.-confdir 与 -config 并存使用 config显示被载入但未生效
3.如果 -confdir 指定的目录下有 .json后缀的目录 程序直接出错

4) 你期待看到的正确表现是怎样的？
-confdir -c -config 能并存使用
-confdir 只能载入指定目录下json后缀的文件 能不能递归载入子目录下面的文件呢？
在outbounds 最好能加上default标识作为默认路由使用 附加排序/优先级 id值 0为默认以此类推

多配置文件载入 只有第一项数组0的对象是默认的 多配置文件不就很难配置默认项吗？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
00_log.json
```javascript
{"log":{"access":null,"error":null,"loglevel":"warning"}}
```
01_api.json
```javascript
{}
```
02_dns.json
```javascript
{
    "dns": {
        "hosts": {},
        "servers": []
    },
    "clientIp": null,
    "tag": "dns_inbound"
}
```
03_routing.json
```javascript
{
    "routing": {
        "rules": [{
                "type": "field",
                "ip": ["geoip:private"],
                "outboundTag": "blocked"
            }
        ]
    }
}
```
04_policy.json
```javascript
{
    "policy": {
        "levels": {
            "0": {
                "handshake": 4,
                "connIdle": 300,
                "uplinkOnly": 2,
                "downlinkOnly": 5,
                "statsUserUplink": false,
                "statsUserDownlink": false,
                "bufferSize": null
            }
        },
        "system": {
            "statsInboundUplink": false,
            "statsInboundDownlink": false,
            "statsOutboundUplink": false,
            "statsOutboundDownlink": false
        }
    }
}
```
05_inbounds_vmess_ws_10000.json
```javascript
{
    "inbounds": [{
            "port": 10000,
            "listen": "0.0.0.0",
            "protocol": "vmess",
            "settings": {
                "clients": [{
                        "id": "",
                        "level": 0,
                        "alterId": 0
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/"
                }
            }
        }
    ]
}
```
06_outbounds.json
```javascript
{
    "outbounds": [{
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }, {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "none"
                }
            },
            "tag": "blocked"
        }
    ]
}
```

**Comment by kslr** [comment]
1 不是bug
2 默认只会影响灵活性

aybru <notifications@github.com> 于 2020年10月8日周四 上午10:44写道：

**Comment by aybru** [comment]
-confdir 目录下有.json后缀的目录程序直接出错
-confdir -config 同时指定 -config显示加载 实际未载入

**Comment by AkinoKaede** [comment]
> -confdir 目录下有.json后缀的目录程序直接出错
> -confdir -config 同时指定 -config显示加载 实际未载入

简单测试了下，-confdir -config 同时使用，inbound 和 outbound 会被 update，v5 中似乎只有 -confdir 会被读取。
递归载入子路径文件这个我去问了下，似乎大家都没有这个需求。
.json 后缀目录这个好解决，加个判断的事情，不过有必要吗…
