### ISSUE TITLE
vmess加grpc是不是比vless稳

### ISSUE THREAD

**Issue by ghost** [v2fly/v2ray-core#2858]
好像墙把tls都破解了，不少网友都传出了tls被封端口的案例，所以tls这种有指纹的方式是不敢再套了。
问题来了，不带tls之后，vmess+grpc是不是比vless还有ws稳？用vmess+ws的人太多了，墙是不是对grpc还是不敏感？
目前用节点跑vmess+grpc已经一周了，还很稳。有没有大神能分析下？

**Comment by kingwilliam** [comment]
独立思考一下 如真的破解了tls(这个破解是指已看到tls内是什麽) 所有政府和金融机构都已首当其冲 但明显不是. 
如说墙可以识别 tls over tls, 这就可以说不是十足也九成九.


如只问: grpc是不是比ws稳定?
短答: grpc比ws丝滑(你可看成grpc自带mux), 但ws会比grpc穏定(因grpc对网络质素要求比较高).


建议: 之前已有很多师兄都已重点解说过, 先做好自身安全
- 自建vps不要回路返国
- 自建vps要做好防范主动探测
- 自建vps如用443, 如不好彩给封闭, 千万不要转端口, 否则 即是说给墙知443可除时不用(有什麽网站是可除是来443)
- 国产品牌手机就已经不安全
- 最後是我个人建议, 千万千万不要直接ssh vps. 这又是说给墙知 这个vps是你自建

**Comment by ChenZiDie** [comment]
“不要直接ssh vps”这个是什么意思，我不懂求知。我有会直接SSH链接到服务器

**Comment by ChenZiDie** [comment]
> 独立思考一下如真的破解了tls（这个破解是指已看到tls内是什么）所有政府和金融机构都已首当其冲但明显不是。 如说墙可以识别tls over tls，那么可以说不是也九成九。
> 
> 如只问：grpc是不是比ws稳定？ 短答：grpc比ws丝滑（你可以看成grpc自带mux），但ws会比grpc穏定（因grpc对网络质素要求比较高）。
> 
> 建议：在很多师兄都强调之前说过，船舶本身就是安全的
> 
> * 自建vps不要回路返国
> * 自建vps要积极主动探测
> * 自建vps如用443，如不好彩端口给封闭，千万不要转端口，否则就是说给墙知443可除时不用（有什么网站是可除时不用443）
> * 国产品牌手机就已经不安全
> * 最后是我个人的建议，千万不要直接ssh vps。这又是说给墙知这个vps是你自建的

“不要直接ssh vps” 这句话怎么理解，是不是我不能直接SSH远程到我的服务器？

**Comment by xinbaobaojinshui** [comment]
“千万千万不要直接ssh vps” 这个我没有理解，我经常直接ssh远程到服务器上，这样会不会有问题。请赐教。 @kingwilliam

**Comment by kingwilliam** [comment]
简单问 有什麽人可用ssh连接linux server? 答案 就只有管理人. 在墙看 有什麽国外伺服器是由国内ip管理？ 这就会给墙一个要多多留意的提示， 墙会再看 这个vps会是什麽用途之类。所以 我会强烈不建议直接用ssh连接vps.

补充：ssh是指protocol(协定), 不是port(端口)23。 因端口可变 但协定不能变

**Comment by 3198137738** [comment]
> 简单问任何人都可以ssh连接linux服务器吗？答案就只有管理人员。在墙看有什么国外服务器是由国内ip管理吗？ 这就会给墙一个要多多留意的提示， 墙会再看这个vps会是什麽用途之类。 所以我会强烈不建议直接用ssh连接vps 。
> 
> 补充：ssh是指protocol(协定), 不是port(端口)。 因端口可变 但协定不能变
> 
> 所以不要以为由22转了45678就可避开监察就算一般的防火墙要过滤ssh协议也不需要什么困难事。

支持

**Comment by Deepseaon** [comment]
> 简单问 有什麽人可用ssh连接linux server? 答案 就只有管理人. 在墙看 有什麽国外伺服器是由国内ip管理？ 这就会给墙一个要多多留意的提示， 墙会再看 这个vps会是什麽用途之类。所以 我会强烈不建议直接用ssh连接vps.
> 
> 补充：ssh是指protocol(协定), 不是port(端口)22。 因端口可变 但协定不能变
> 
> 所以 不要意为由22转了45678就可避过监察 就算一般的防火墙 要过滤出ssh protocol也不是什麽难事。

这个我不是很同意啊，我自己建站也有使用一台海外服务器，这不是很正常的吗，没有规定不能使用海外服务器吧，你正常ssh流量根本不会出现什么问题吧

**Comment by kingwilliam** [comment]
> > 简单问 有什麽人可用ssh连接linux server? 答案 就只有管理人. 在墙看 有什麽国外伺服器是由国内ip管理？ 这就会给墙一个要多多留意的提示， 墙会再看 这个vps会是什麽用途之类。所以 我会强烈不建议直接用ssh连接vps.
> > 补充：ssh是指protocol(协定), 不是port(端口)22。 因端口可变 但协定不能变
> > 所以 不要意为由22转了45678就可避过监察 就算一般的防火墙 要过滤出ssh protocol也不是什麽难事。
> 
> 这个我不是很同意啊，我自己建站也有使用一台海外服务器，这不是很正常的吗，没有规定不能使用海外服务器吧，你正常ssh流量根本不会出现什么问题吧

所以我也说 由国内ssh一个国外vps 只是提供一个留意讯息给网路管理者

如 我是一个网路管理者, 我会再留意这个vps(或者是ip) 有什麽连接端口(如 443)
我就会主动探测这个443网站 看看会否有特别之处

所以 纯个人意见 可以不用ssh就不要用 只是尽量减少给网路管理者留意的讯息
当然 如这个vps是一个正常网站 没其他用途 当然不会有什麽影响

**Comment by kingwilliam** [comment]
題外話 如你的vps ip是 13.14.15.16 有沒有嘗試去試探您的隣居 如 13.14.15.(51-99) 

我就曾經試過 我是用一知名vps供應商 不知是我幸運還是不幸 左隣右里 沒70%都有60%是科學上網的 如何得知? 就是經常說要做好主動探測防護. 我不是用高人 我連tcp header是什麼也不知. 但真的用非常簡單方式就知這是否真正網站(留意 不是 真正網站 不等同 科學上網) 我有時真的想通知那個vps用家 做好防護好嗎?

如問我 如何試? 最簡單 http:// 或 https:// 那個ip 如 https://13.14.15.16 如正常網站 是不會出網頁的, 當然想知是否用來科學上網  还有很多 蛛絲馬跡 可測試

最後都係那句 做好 主動探測防護
