### ISSUE TITLE
Request add API: Dynamically add delete routing rules

### ISSUE THREAD

**Issue by ifworldok** [v2fly/v2ray-core#286]
Whether to consider adding an API for "AddRoute" and "DelRoute" to "RoutingService"? Just like adding or deleting users, the following three blocked tags are added to the routing rules in real time and take effect.

`[tag:"blocked" protocol:"bittorrent" tag:"blocked" user_email:"1@emali.com" tag:"blocked" source_geoip:{cidr:{ip:":\xf1\xd6\x23" prefix:32}}]`

In the sample test file, only the following "common.must" command, as @Vigilans says, does not find an elegant way to add a routing rule that will make the path pass effective in real time.

`{
    Protocol:  []string{"bittorrent"},
    TargetTag: &router.RoutingRule_Tag{Tag: "blocked"},
},
{
    Domain:    []*router.Domain{{Type: router.Domain_Domain, Value: "com"}},
    TargetTag: &router.RoutingRule_Tag{Tag: "out"},
},
{
    UserEmail: []string{"example@v2fly.org"},
    TargetTag: &router.RoutingRule_Tag{Tag: "out"},
}`

Find the following two references for adding routing rules:
https://github.com/ximliu/my-v2ray-core/blob/c7751b892873957a4468dc41fe25f1d9ea3e3302/app/router/router.go#L72
https://github.com/ProxyPanel/VNet-V2ray/blob/a587436377cac1985f23305016f5fbbb3b370e84/app/rule/rule.go#L82

Similar issues before:
https://github.com/v2ray/v2ray-core/issues/2024
https://github.com/v2ray/v2ray-core/issues/2068#issuecomment-559808802
https://github.com/v2fly/v2ray-core/pull/208#issuecomment-697296821

**Comment by acc557** [comment]
This can be very helpful for dynamically selecting the fastest outbound. Users can design complex strategies with this API to route every individual website to the fastest outbound. 

Similar issues before:
https://github.com/v2ray/v2ray-core/issues/1390
https://github.com/v2ray/v2ray-core/issues/1825
https://github.com/v2ray/v2ray-core/issues/1380
https://github.com/v2ray/v2ray-core/issues/1378
https://github.com/v2ray/discussion/issues/122

**Comment by acc557** [comment]
Also see
https://github.com/v2ray/v2ray-core/pull/1924
