### ISSUE TITLE
特殊使用环境下VLESS over TCP with XTLS + 回落问题咨询

### ISSUE THREAD

**Issue by zqs125** [v2fly/v2ray-core#295]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    v2ray-core v4.30.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    使用fallback回落nginx web服务
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    因我的环境比较特殊，现只能使用80端口，nginx的web是http的，使用vless+tcp+tls时，fallback没有办法回落到nginx的web上，浏览器访问web时显示连接被重置
4) 你期待看到的正确表现是怎样的？
    想要实现的结果就是浏览器访问http时能回落到nginx的web服务上
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
    {
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 80,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "", // UUID
                        "flow": "xtls-rprx-origin",
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8080 // nginx的web服务
                    },
                    {
                        "path": "/websocket", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/path/to/fullchain.crt", // 证书
                            "keyFile": "/path/to/private.key" // 私钥
                        }
                    ]
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "", // UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true,
                    "path": "/websocket"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
2020/10/10 01:58:17 [Info] [1384348709] v2ray.com/core/proxy/vless/inbound: firstLen = 0
2020/10/10 01:58:17 [Info] [1384348709] v2ray.com/core/proxy/vless/inbound: fallback starts > v2ray.com/core/proxy/vless/inbound: fallback directly
2020/10/10 01:58:17 [Info] [1384348709] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: fallback ends > v2ray.com/core/proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake
```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by xianren78** [comment]
80端口跑了https啊，没跑http。这需求也太小众了。

**Comment by zqs125** [comment]
没有办法，只能使用80端口，为了安全用VLESS over TCP with XTLS，可没办法回落http了，web不能访问了，现在就想着有什么办法可以即能用VLESS over TCP with XTLS，又可以正常回落到http的web上

**Comment by dna1982** [comment]
为什么不能回落？
按照你的配置，只要在 Nginx 里 Listen 8080 就可以了。

**Comment by zqs125** [comment]
nginx已经配置了8080端口监听是没问题的，可是用浏览器访问web时，显示连接被重置，v2ray的日志显示为tls: first record does not look like a TLS handshake，web默认是http的，不是https，所以回落不了

**Comment by dna1982** [comment]
> nginx已经配置了8080端口监听是没问题的，可是用浏览器访问web时，显示连接被重置，v2ray的日志显示为tls: first record does not look like a TLS handshake，web默认是http的，不是https，所以回落不了

用浏览器访问https://xxx.xxx。
因为你的VLESS已经加了TLS，所以你的web服务已经不是http了。

**Comment by zqs125** [comment]
嗯，现在的问题就在这，用户访问web时不可能主动输入https，即使nginx已经开了HSTS，可也要首次http后才能转成https，所以现在的问题就是有什么办法可以回落到http上

**Comment by dna1982** [comment]
> 嗯，现在的问题就在这，用户访问web时不可能主动输入https，即使nginx已经开了HSTS，可也要首次http后才能转成https，所以现在的问题就是有什么办法可以回落到http上

没有办法回落到http上。
但是有办法让http自动rewrite到https上。

**Comment by zqs125** [comment]
现在是v2是tls，浏览器http访问web时，v2都不回落，要是能回落的话就不需要什么rewrite了，因为v2的客户端肯定是加tls连接的，现在就是http的事了

**Comment by dna1982** [comment]
> 现在是v2是tls，浏览器http访问web时，v2都不回落，要是能回落的话就不需要什么rewrite了，因为v2的客户端肯定是加tls连接的，现在就是http的事了

按照我的理解，目前VLESS的 fallback 机制，似乎是在 TLS 解密之后的。
因为不解密的话，不读取不了 Request 的前面几个字节的吧。

如果一开始VLESS TLS 握手就不成功的话，似乎就到不了 fallback 那一步。
你这个问题只能找VLESS作者了。

**Comment by zqs125** [comment]
> > 现在是v2是tls,浏览器http访问web时,v2都不回落,要是能回落的话就不需要什么rewrite了,因为v2的客户端肯定是加tls连接的,现在就是http的事了
> 
> [，无回退]，[TLS]
> [request]，[请求]
> 
> [无无 Tls] [回退]
> [无用]

是的，现在就是这个问题，没有tls的就没办法回落了

**Comment by zqs125** [comment]
是的，现在就是这个问题，没有tls的就没办法回落了

**Comment by rprx** [comment]
目前不支持这样的功能，隔壁 trojan 系列也没有。从另一个角度来讲，一个端口同时处理 https 和 http，主流 web 服务器都不是这样，可以成为特征之一。

**Comment by zqs125** [comment]
> 目前不支持这样的功能，隔壁 trojan 系列也没有。从另一个角度来讲，一个端口同时处理 https 和 http，主流 web 服务器都不是这样，可以成为特征之一。

好的，明白了，我的情况比较特殊，只能这样用，v2不支持的话只能通过别的方式来解决了，有个新问题咨询一下，vless+tcp+tls时，只要配置了tcpSettings里的"header": {"type": "http"}，fallback回落web就失效了，官方文档也没找到相关的配置说明，vless下就不能在配置这个http了吗？不知道程序就是这样设计的还是这个地方是个bug？

**Comment by rprx** [comment]
@zqs125 

没有故意这样设计，但现在的逻辑是正确的（fallbacks 只能拿到最内层的数据流，所以总不能是 http 伪装内的回落，那样就无意义了）。
