### ISSUE TITLE
v2ray-core v5.14.1 bug

### ISSUE THREAD

**Issue by donghj2000** [v2fly/v2ray-core#2953]
## 你正在使用哪个版本的 V2Ray？
客户端 v2rayN 6.18, v2ray-core 5.14.1

## 你的使用场景是什么？
chrome看网页。

## 你看到的异常现象是什么？
升级到v2ray-core 5.14.1后就不能上网了。

## 你期待看到的正常表现是怎样的？
能正常上网。

## 请附上你的配置

**服务端配置：**
无
```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置
无。
```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
下载Core成功
正在解压......
https://github.com/v2fly/v2ray-core/releases/download/v5.14.1/v2ray-windows-64.zip
2024/3/31 星期日 下午 3:16:57 系统代理设置改变
更新Core成功！正在重启服务...
更新Core成功
配置成功

[VLESS] xxxxx(xxxxxxx:443)
启动服务(2024/3/31 星期日 下午 3:16:58)...
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
	runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a4da
rax     0x0
rbx     0x22a6638
rcx     0x285b528
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x2bfa2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x22a5120
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by donghj2000** [comment]
v5.13.0 及以前的版本是好的。

**Comment by donghj2000** [comment]
找到原因了，v5.15.0 使用了go 1.21版本来编译，该版本需要windows 10, 有些API在windows 7下没有。所以使用windows 7 会异常 。
https://github.com/golang/go/issues/64622

**Comment by i486** [comment]
I'm not a developer, but from what I can gather from this [discussion](https://rb.gy/sfjbpi), it seems like there's only one API change that broke Go on Windows 7. After reading the entire conversation, it looks like many of the main Go developers are open to make Go compatible with Windows 7 again. They're just waiting for a volunteer to handle it through proper channels. Anyone?

**Comment by AkinoKaede** [comment]
> I'm not a developer, but from what I can gather from this [discussion](https://rb.gy/sfjbpi), it seems like there's only one API change that broke Go on Windows 7. After reading the entire conversation, it looks like many of the main Go developers are open to make Go compatible with Windows 7 again. They're just waiting for a volunteer to handle it through proper channels. Anyone?

V2Ray will continue to be built using the latest mainline version of Go, and continued support for Windows 7 will depend on Go.
