### ISSUE TITLE
节点连接成功了为什么还登不上Tik Tok

### ISSUE THREAD

**Issue by xshk123** [v2fly/v2ray-core#3009]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

This issue will be closed immediately.

**Comment by Bryan2333** [comment]
检查路由规则，看看是不是这个问题：https://github.com/v2fly/domain-list-community/issues/926

**Comment by chinavpns** [comment]
如果你成功连接了，但依然用不了TikTok，那么可能是以下两个原因造成的：
1，你选择了中国香港的服务器节点！你可以尝试选择非中国大陆和中国香港的节点试试看！
2，你的真实IP地址可能暴露了！你可以尝试开启全局模式！
