### ISSUE TITLE
failed to read response from cachefly.cachefly.net > io: read/write on closed pipe and no access via v2rayn

### ISSUE THREAD

**Issue by nickelpower** [v2fly/v2ray-core#3030]
Greetings. I have been using v2rayn for a long time and never ever had this issue before. Until these 2 days. 
![image_2024-05-29_132247997](https://github.com/v2fly/v2ray-core/assets/149795359/2f903d7d-f084-4152-9cb4-e2e73e40e0b8)

Now i cant use this program at all, even on newest version. Same error occurs when you try to test servers speed " io: read/write on closed pipe", the test for delay works as usual meanwhile, and servers themselves are workable. But i cant establish a connection via v2rayn after its happened

Searching for this kind of issue didnt help. How do i fix it?

**Comment by bb33bb** [comment]
修复了？这个一般出现在全局端口复用上貌似
