### ISSUE TITLE
v2ray.exe闪退

### ISSUE THREAD

**Issue by daviming** [v2fly/v2ray-core#3033]
## 你期待看到的正常表现是怎样的？

v2ray.exe正常运行

## 请附上你的配置![IMG_20240603_222342.jpg](https://github.com/v2fly/v2ray-core/assets/156303637/56af61a0-71d4-4b8d-b50a-918eb3be27ca)

**服务端配置：**
![IMG_20240603_222632.jpg](https://github.com/v2fly/v2ray-core/assets/156303637/642262e4-e468-4940-b830-9597c4cf8645)

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by ioctltty** [comment]
请尝试使用终端运行v2ray.exe 这样即使出错也能看到错误信息。终端建议用 [Windows Terminal](https://apps.microsoft.com/detail/9n0dx20hk701) 配合PowerShell.
