### ISSUE TITLE
入站链接明明绑定IPV4端口,而系统查看却是绑定IPV6端口.

### ISSUE THREAD

**Issue by Y-A-K-E** [v2fly/v2ray-core#308]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

> 
> 
> ```
> V2Ray 4.29.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/mips)
> A unified platform for anti-censorship.
> ```
> 
> 或者
> 
> ```
> V2Ray 4.28.2 (OpenWrt) R1 (go1.14.7 linux/mips)
> A unified platform for anti-censorship.
> ```
> 
> 或者
> 
> ```
> V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/mips)
> A unified platform for anti-censorship.
> ```
> 

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

> 路由器开启v2ray服务器.

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

> 明明我
> 设置的是"listen":"0.0.0.0"
> 正常应该是绑定0.0.0.0:35000
> 
> 而查看路由器端口状态绑定的却是:::35000
> 
> ```
> root@OpenWrt:~# netstat -anp | grep v2
> tcp        0      0 :::35000                :::*                    LISTEN      32596/v2ray
> ```
> 
> 

4) 你期待看到的正确表现是怎样的？

> 0.0.0.0绑定IPV4端口而不是IPV6端口

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

> 
> 
> 
> 服务器端配置:
> 
> ```javascript
> {
> 	"routing":{
> 		"rules":[
> 			{
> 				"inboundTag":[
> 					"api"
> 				],
> 				"type":"field",
> 				"outboundTag":"api"
> 			},
> 			{
> 				"ip":[
> 					"geoip:private"
> 				],
> 				"type":"field",
> 				"outboundTag":"blocked"
> 			}
> 		]
> 	},
> 	"outbounds":[
> 		{
> 			"settings":{},
> 			"protocol":"freedom"
> 		},
> 		{
> 			"settings":{},
> 			"protocol":"blackhole",
> 			"tag":"blocked"
> 		}
> 	],
> 	"stats":{},
> 	"api":{
> 		"tag":"api",
> 		"services":[
> 			"HandlerService",
> 			"LoggerService",
> 			"StatsService"
> 		]
> 	},
> 	"inbounds":[
> 		{
> 			"settings":{
> 				"clients":[
> 					{
> 						"id":"5e3b1015-e222-4a72-90d5-5da9c0a0562d",
> 						"alterId":64
> 					}
> 				]
> 			},
> 			"protocol":"vmess",
> 			"port":35000,
> 			"enable":true,
> 			"streamSettings":{
> 				"wsSettings":{
> 					"path":"/",
> 					"headers":{
> 					}
> 				},
> 				"security":"none",
> 				"network":"ws"
> 			},
> 			"remark":"test",
> 			"tag":"inbound-11270",
> 			"listen":"0.0.0.0"
> 		}
> 	],
> 	"policy":{
> 		"system":{
> 			"statsInboundUplink":true,
> 			"statsInboundDownlink":true
> 		}
> 	}
> }
> 
> ```
>

**Comment by aybru** [comment]
有同样的问题 我在防火墙里屏蔽了IPv6
