### ISSUE TITLE
proxySettings conflict with VLESS XTLS 

### ISSUE THREAD

**Issue by ghost** [v2fly/v2ray-core#311]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v4.31.0

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
using VLESS XTLS with proxySettings on the client side.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

Does not work.

proxySettings seems to override streamSettings settings completely, which is required by XTLS.

4) What's your expectation?

proxySettings should be able to work with streamSettings, or at least streamSettingswith `"network": "tcp"`.

"http" or "ws" can also be treated as tcp traffic, and "kcp" or "quic" should be treated as udp traffic when sending to another outbound.

**Comment by acc557** [comment]
@rprx

**Comment by rprx** [comment]
目前 proxySettings 是有这样的限制，原因是 v2ray 底层传输方式的实现是直接与系统交互，导致无法内部直接嵌套。

**Comment by acc557** [comment]
Could XTLS bypass that and allow proxySettings to be configured as a underlying layer of TLS? Then people can chain multiple XTLS servers easily and use them as a faster tor alternative. 
Not sure if that would be easy, though.

**Comment by rprx** [comment]
目前应该可以通过 dokodemo-door 做到，但这里还有两个问题：

1. v2ray 出来的 TLS data record 都是 2k+ 的，测试表明 xtls-rprx-origin 入站处理 16k+ 时性能最佳（不确定 direct mode 的表现）

2. 对于链式代理，若旁观者同时掌握着流量出口和最终入口且有意记录 TLS 数据包，则理论上可以做到追踪（因为目前是纯转发）

当然，对于第二点，简单的数据包重组 + XOR 就可以解决。

**Comment by acc557** [comment]
Will be easily solved when https://github.com/v2fly/v2ray-core/issues/383 is implemented.

**Comment by rprx** [comment]
经过更多研究后，上面我说的两个问题中，第一个不再是问题，第二个仍需要解决。

**Comment by acc557** [comment]
> 
> 
> 经过更多研究后，上面我说的两个问题中，第一个不再是问题，第二个仍需要解决。

I thought people can simply wrap it with a shadowsocks with xor or whatever they like
ss in v2ray doesn't support xor it seems

**Comment by kery** [comment]
目前我遇到同样的问题，即在协议为VLESS的出站协议里使用proxySettings配置前置代理后streamSettings无效。我看到文档上也有提到。
> 当出站代理生效时，此出站协议的 streamSettings 将不起作用。

@rprx 你提到dokodemo-door可以解决这个问题，请问具体是如何配置呢？能否稍微解释一下，谢谢！
