### ISSUE TITLE
配置文件在4.44版能正常啟動使用但在之後的版本都是一閃而過沒法啟動

### ISSUE THREAD

**Issue by RickyWong19922005** [v2fly/v2ray-core#3117]
這到底是配置文件問題還是5打後的版本要有什麼要求才能啟動?

**Comment by unknowndevQwQ** [comment]
没拿出来配置文件，难道是要大伙用水晶球给你算算？

**Comment by RickyWong19922005** [comment]
> 没拿出来配置文件，难道是要大伙用水晶球给你算算？

{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 999,
      "protocol": "vmess",
      "settings": {
        "udp": false,
        "clients": [
          {
            "id": "hide",
            "alterId": 0,
            "email": "t@t.tt"
          }
        ],
        "allowTransparent": false
      },
      "streamSettings": {
        "network": "tcp"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}

4.45版還能用
但再新一版就已經不能用了

**Comment by unknowndevQwQ** [comment]
> > 没拿出来配置文件，难道是要大伙用水晶球给你算算？
> 
> { "log": { "access": "", "error": "", "loglevel": "warning" }, "inbounds": [ { "port": 999, "protocol": "vmess", "settings": { "udp": false, "clients": [ { "id": "hide", "alterId": 0, "email": "[t@t.tt](mailto:t@t.tt)" } ], "allowTransparent": false }, "streamSettings": { "network": "tcp" } } ], "outbounds": [ { "protocol": "freedom" }, { "tag": "block", "protocol": "blackhole", "settings": {} } ], "routing": { "domainStrategy": "IPIfNonMatch", "rules": [] } }
> 
> 4.45版還能用 但再新一版就已經不能用了

这是服务端还是客户端？
如果双击一闪而过，为啥不在终端里输入一下看看呢

**Comment by vxtls** [comment]
> > 没拿出来配置文件，难道是要大伙用水晶球给你算算？
> 
> { "log": { "access": "", "error": "", "loglevel": "warning" }, "inbounds": [ { "port": 999, "protocol": "vmess", "settings": { "udp": false, "clients": [ { "id": "hide", "alterId": 0, "email": "[t@t.tt](mailto:t@t.tt)" } ], "allowTransparent": false }, "streamSettings": { "network": "tcp" } } ], "outbounds": [ { "protocol": "freedom" }, { "tag": "block", "protocol": "blackhole", "settings": {} } ], "routing": { "domainStrategy": "IPIfNonMatch", "rules": [] } }
> 
> 4.45版還能用 但再新一版就已經不能用了

升级V5后根据文档重新写一个，或者交给ChatGPT更新配置文件吧

**Comment by RickyWong19922005** [comment]
服務端的
有試過用copliot但好像沒解決到
我再試試

**Comment by AkinoKaede** [comment]
The command for running is changed in V2Ray V5, try to run `v2ray run -c path/to/config.json -format jsonv4` in terminal.

**Comment by RickyWong19922005** [comment]
> The command for running is changed in V2Ray V5, try to run `v2ray run -c path/to/config.json -format jsonv4` in terminal.

Thanks, will try

**Comment by RickyWong19922005** [comment]
> The command for running is changed in V2Ray V5, try to run `v2ray run -c path/to/config.json -format jsonv4` in terminal.

I tried, but no different.

**Comment by AkinoKaede** [comment]
> > The command for running is changed in V2Ray V5, try to run `v2ray run -c path/to/config.json -format jsonv4` in terminal.
> 
> I tried, but no different.

Please upload the standard output of V2Ray.

**Comment by RickyWong19922005** [comment]
> > > The command for running is changed in V2Ray V5, try to run `v2ray run -c path/to/config.json -format jsonv4` in terminal.
> > 
> > 
> > I tried, but no different.
> 
> Please upload the standard output content of V2Ray, just like:
> <img alt="image" width="728" src="https://private-user-images.githubusercontent.com/26006258/392411503-0adc7055-8018-47dd-95f1-707ce3752332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjAxODIsIm5iZiI6MTczMzMxOTg4MiwicGF0aCI6Ii8yNjAwNjI1OC8zOTI0MTE1MDMtMGFkYzcwNTUtODAxOC00N2RkLTk1ZjEtNzA3Y2UzNzUyMzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEzNDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MWUyZTk1NjVjNWE0NmFiMjE4NGI1Y2MxNGRkYWJhYWQ4NGY2NTkzZjdmMzAyOGQ0NTM0YjllMzkxZTdhMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F-wBT0HcPCHOyKM_DKacCrGNYTtUVrvZLr1kIxz4ms8">

![圖片](https://github.com/user-attachments/assets/485e5f99-b800-4025-bf4c-f226fd6dc001)

**Comment by RickyWong19922005** [comment]
> > > The command for running is changed in V2Ray V5, try to run `v2ray run -c path/to/config.json -format jsonv4` in terminal.
> > 
> > 
> > I tried, but no different.
> 
> Please upload the standard output content of V2Ray, just like:
> <img alt="image" width="728" src="https://private-user-images.githubusercontent.com/26006258/392411503-0adc7055-8018-47dd-95f1-707ce3752332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjAxODIsIm5iZiI6MTczMzMxOTg4MiwicGF0aCI6Ii8yNjAwNjI1OC8zOTI0MTE1MDMtMGFkYzcwNTUtODAxOC00N2RkLTk1ZjEtNzA3Y2UzNzUyMzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEzNDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MWUyZTk1NjVjNWE0NmFiMjE4NGI1Y2MxNGRkYWJhYWQ4NGY2NTkzZjdmMzAyOGQ0NTM0YjllMzkxZTdhMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F-wBT0HcPCHOyKM_DKacCrGNYTtUVrvZLr1kIxz4ms8">

It work now, after copliot edited
thanks
