### ISSUE TITLE
v2ray-core 更新地址变化，无法更新v4.31.0

### ISSUE THREAD

**Issue by crazyshitass** [v2fly/v2ray-core#312]
这是v2ray for openwrt - 2.3.7的更新日志
【2020年10月13日 16:06:12】: 开始检查 v2ray 最新版本。。。
【2020年10月13日 16:06:14】: 当前版本：v4.28.2
【2020年10月13日 16:06:14】: 最新版本：v4.31.0
【2020年10月13日 16:06:14】: 准备升级到最新版本，开始下载
--2020-10-13 16:06:14--  https://github.com/v2ray/v2ray-core/releases/download/v4.31.0/v2ray-linux-64.zip
Resolving github.com... 192.30.255.112
Connecting to github.com|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-13 16:06:14 ERROR 404: Not Found.

【2020年10月13日 16:06:14】: 最新版本下载失败，请检查网络到github的连通后再试！

**Comment by Loyalsoldier** [comment]
请联系脚本开发者或自行把安装源从 `v2ray/v2ray-core` 改为 `v2fly/v2ray-core`

**Comment by iKira** [comment]
将 /koolshare/script/v2ray_config.sh 这个脚本里的 v2ray/v2ray-core 全部替换为 v2fly/v2ray-core，然后再进入插件更新页面更新v2ray-core。

**Comment by crazyshitass** [comment]
> 将 /koolshare/script/v2ray_config.sh 这个脚本里的 v2ray/v2ray-core 全部替换为 v2fly/v2ray-core，然后再进入插件更新页面更新v2ray-core。

非常感谢，问题解决了
