### ISSUE TITLE
failed to start v2ray-core: unexpected exiting: check the log for more information

### ISSUE THREAD

**Issue by hcws** [v2fly/v2ray-core#3174]
## 你正在使用哪个版本的 V2Ray？
[v5.18.0](https://github.com/v2fly/v2ray-core/releases/tag/v5.18.0)

## 你的使用场景是什么？

Ubuntu20.04 Google 

## 你看到的异常现象是什么？

failed to start v2ray-core: unexpected exiting: check the log for more information

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

# 将V2rayA和v2ray-core关联起来
# 添加配置两行配置
V2RAYA_V2RAY_BIN=/usr/local/v2ray-core/v2ray
V2RAYA_V2RAY_CONFDIR=/usr/local/v2ray-core


```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

## 如果 V2Ray 服务运行异常，请附上 journal 日志

-- Reboot --
10月 01 16:02:46 ly-pc systemd[1]: Started V2Ray Service.
10月 01 16:02:46 ly-pc v2ray[1153]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
10月 01 16:02:46 ly-pc v2ray[1153]: A unified platform for anti-censorship.
10月 01 16:02:46 ly-pc v2ray[1153]: 2024/10/01 16:02:46 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
10月 01 16:02:46 ly-pc v2ray[1153]: v2ctl> Read config:  /etc/v2ray/config.json
10月 01 16:02:46 ly-pc v2ray[1153]: 2024/10/01 16:02:46 [Warning] v2ray.com/core: V2Ray 4.28.2 started
10月 01 16:21:06 ly-pc systemd[1]: Stopping V2Ray Service...
10月 01 16:21:06 ly-pc systemd[1]: v2ray.service: Succeeded.
10月 01 16:21:06 ly-pc systemd[1]: Stopped V2Ray Service.
-- Reboot --
10月 01 16:25:36 ly-pc systemd[1]: Started V2Ray Service.
10月 01 16:25:36 ly-pc v2ray[1157]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
10月 01 16:25:36 ly-pc v2ray[1157]: A unified platform for anti-censorship.
10月 01 16:25:36 ly-pc v2ray[1157]: 2024/10/01 16:25:36 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
10月 01 16:25:36 ly-pc v2ray[1157]: v2ctl> Read config:  /etc/v2ray/config.json
10月 01 16:25:36 ly-pc v2ray[1157]: 2024/10/01 16:25:36 [Warning] v2ray.com/core: V2Ray 4.28.2 started
10月 01 16:29:35 ly-pc systemd[1]: Stopping V2Ray Service...
10月 01 16:29:35 ly-pc systemd[1]: v2ray.service: Succeeded.
10月 01 16:29:35 ly-pc systemd[1]: Stopped V2Ray Service.
-- Reboot --
10月 01 16:31:31 ly-pc systemd[1]: Started V2Ray Service.
10月 01 16:31:31 ly-pc v2ray[1158]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
10月 01 16:31:31 ly-pc v2ray[1158]: A unified platform for anti-censorship.

**Comment by Dancergh** [comment]
root@iZ2vceq5jzrsrp7qabt486Z:~# v2ray -test -config /etc/v2ray/config.json
V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
2026/03/26 17:30:28 [Info] v2ray.com/core/main/jsonem: Reading config: /etc/v2ray/config.json
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc0001af5f0, {0xc0000a0030, 0x16, 0x18})
        crypto/hmac/hmac.go:143 +0x292
v2ray.com/core/proxy/vmess/aead.KDF({0xc00019fc80, 0x10, 0x10}, {0xc0001af640, 0x1, 0x10})
        v2ray.com/core/proxy/vmess/aead/kdf.go:13 +0x127
v2ray.com/core/proxy/vmess/aead.KDF16(...)
        v2ray.com/core/proxy/vmess/aead/kdf.go:22
v2ray.com/core/proxy/vmess/aead.NewCipherFromKey({0xc00019fc80, 0x0, 0x0})
        v2ray.com/core/proxy/vmess/aead/authid.go:41 +0x4a
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoder(...)
        v2ray.com/core/proxy/vmess/aead/authid.go:53
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoderItem(...)
        v2ray.com/core/proxy/vmess/aead/authid.go:84
v2ray.com/core/proxy/vmess/aead.(*AuthIDDecoderHolder).AddUser(0xc0002126e0, {0x3c, 0x9, 0xe6, 0x15, 0x68, 0xbb, 0xbb, 0xe9, 0xf3, ...}, ...)
        v2ray.com/core/proxy/vmess/aead/authid.go:90 +0x50
v2ray.com/core/proxy/vmess.(*TimedUserValidator).Add(0xc00021ae00, 0xc000209b00)
        v2ray.com/core/proxy/vmess/validator.go:152 +0x365
v2ray.com/core/proxy/vmess/inbound.(*Handler).AddUser(0xc000216380, {0xb05240, 0x0}, 0x2)
        v2ray.com/core/proxy/vmess/inbound/inbound.go:166 +0x52
v2ray.com/core/proxy/vmess/inbound.New({0xd67aa0, 0xc000209770}, 0xc0000b7860)
        v2ray.com/core/proxy/vmess/inbound/inbound.go:133 +0x3b0
v2ray.com/core/proxy/vmess/inbound.init.2.func1({0xd67aa0, 0xc000209770}, {0xc1cce0, 0xc0000b7860})
        v2ray.com/core/proxy/vmess/inbound/inbound.go:355 +0x3c
v2ray.com/core/common.CreateObject({0xd67aa0, 0xc000209770}, {0xc1cce0, 0xc0000b7860})
        v2ray.com/core/common/type.go:32 +0x1a5
v2ray.com/core/app/proxyman/inbound.NewAlwaysOnInboundHandler({0xd67aa0, 0xc000209770}, {0x0, 0x62780}, 0xc00021ad90, {0xc1cce0, 0xc0000b7860})
        v2ray.com/core/app/proxyman/inbound/always.go:52 +0x71
v2ray.com/core/app/proxyman/inbound.NewHandler({0xd67aa0, 0xc000209770}, 0xc000216100)
        v2ray.com/core/app/proxyman/inbound/inbound.go:162 +0x2c5
v2ray.com/core/app/proxyman/inbound.init.0.func2({0xd67aa0, 0xc000209770}, {0xc0f4c0, 0xc000216100})
        v2ray.com/core/app/proxyman/inbound/inbound.go:176 +0x3c
v2ray.com/core/common.CreateObject({0xd67aa0, 0xc000209770}, {0xc0f4c0, 0xc000216100})
        v2ray.com/core/common/type.go:32 +0x1a5
v2ray.com/core.CreateObject(0x6, {0xc0f4c0, 0xc000216100})
        v2ray.com/core/functions.go:21 +0x78
v2ray.com/core.AddInboundHandler(0xc0000b7360, 0x4)
        v2ray.com/core/v2ray.go:101 +0x65
v2ray.com/core.addInboundHandlers(0xc0000b7360, {0xc0000a2fb8, 0x1, 0xc0000b7360})
        v2ray.com/core/v2ray.go:117 +0x56
v2ray.com/core.initInstanceWithConfig(0xc00020b050, 0xc0000b7360)
        v2ray.com/core/v2ray.go:229 +0x42b
v2ray.com/core.New(0xc4f77c)
        v2ray.com/core/v2ray.go:164 +0x77
main.startV2Ray()
        v2ray.com/core/main/main.go:115 +0x230
main.main()
        v2ray.com/core/main/main.go:139 +0x9f
root@iZ2vceq5jzrsrp7qabt486Z:~#
