### ISSUE TITLE
v2ray V5 subscription 解析节点导致的疯狂吃内存

### ISSUE THREAD

**Issue by 328902301** [v2fly/v2ray-core#3206]
## 你正在使用哪个版本的 V2Ray？

Windows v5.20.0 以及 v5.20.1

## 你的使用场景是什么？
v2ray V5 subscription 节点在线订阅服务

## 你看到的异常现象是什么？
v2ray V5 subscription 中如果订阅链接包含 vmess 节点，内核启动之后疯狂吃内存，直至被杀死。

从 v5.20.0 开始引入的 parsing some shadowsocks links 起，两个版本以及后修订上传的子版本都有相同的问题。

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by xiaokangwang** [comment]
在 https://github.com/v2fly/v2ray-core/pull/3208 修了， 请更新后再试一次。

**Comment by 328902301** [comment]
感谢佬，测试没问题。

**Comment by xiaokangwang** [comment]
This issue is closed as the problem was fixed.

**Comment by parsa2000200** [comment]
- - [ ] # **@VentoValery **
