### ISSUE TITLE
v2ray listen udp(quic protocol) port, but not recv data

### ISSUE THREAD

**Issue by liaoyangyang** [v2fly/v2ray-core#323]
my v2ray version is `V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)`。

my v2ray server use the following config，It will listen 40001 port, but can not recv any data, when change transport protocol to other like tcp or mkcp，It works

 server config

```json

{
  "log": {
    "loglevel": "debug"
  },
  "dns": {},
  "stats": {},
  "inbounds": [
    {
      "protocol": "vmess",
      "port": 40001,
      "settings": {
        "clients": [
          {
            "id": "ed78d7e5-8448-0afe-5763-668c9ff44b49",
            "alterId": 32
          }
        ]
      },
      "tag": "in-vmess-quic",
      "streamSettings": {
        "network": "quic",
        "security": "none",
        "quicSettings": {
            "security": "none",
            "key": "",
            "header": {
                "type": "none"
            }
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "policy": {},
  "reverse": {},
  "transport": {}
}

```

![image](https://user-images.githubusercontent.com/10610029/96129978-e1205380-0f29-11eb-9444-39907b873a22.png)

**Comment by ha-ku** [comment]
I encountered the same problem before.
It seems that QUIC is entirely blocked by the GFW?

**Comment by liaoyangyang** [comment]
I run nc to test quic port, v2ray has noting to feedback. But when i use nc to test other port(like tcp, shadowsocks runs by v2ray) , it works. So i think the problem may be in the v2ray logic .

**Comment by lxhao61** [comment]
> 我运行nc来测试v2ray服务器上的quic端口，v2ray注意到反馈。但是，当我使用nc测试其他端口（例如tcp，shadowsocks由v2ray运行）时，它可以工作。所以我认为问题可能出在v2ray逻辑上。

如你客户端配置域名连接，试试客户端配置"serverName"为域名。

**Comment by Lightmani** [comment]
当我本地使用4.31版本及以上的Core时，同样出现了QUIC无返回数据的问题。
但是，当我将本地客户端内核换回4.27后，能够正常使用。

**Comment by rprx** [comment]
v4.31.0 升级到了 IETF QUIC draft-29，服务端和客户端请同时使用新版。
