### ISSUE TITLE
v2rayN無法用小視窗显示

### ISSUE THREAD

**Issue by chankwokwai** [v2fly/v2ray-core#3239]
## Please attach your configuration here

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

**Comment by AkinoKaede** [comment]
You should send this issue to https://github.com/2dust/v2rayN
