### ISSUE TITLE
保存在guiLogs文件夹中的日志不会自动清除

### ISSUE THREAD

**Issue by xfish33** [v2fly/v2ray-core#326]
没有设置记录日志，但是软件运行时会自动生成日志并存储在guiLogs文件内，今天一看，累积的txt文件都已经超过5个G了，手动删除后不影响正常使用，最新生成的日志文件如附件所示
[20201016.txt](https://github.com/v2fly/v2ray-core/files/5392024/20201016.txt)

**Comment by kslr** [comment]
这跟core无关

**Comment by xfish33** [comment]
感谢回复，这应该和GUI的程序相关，可能是v2rayN？
