### ISSUE TITLE
关于移除 Hysteria2 协议

### ISSUE THREAD

**Issue by JimmyHuang454** [v2fly/v2ray-core#3268]
```
The hysteria2 fork used "github.com/JimmyHuang454/hysteria" removed the original license of hysteria2 (which is not allowed) and replaced it with GPL which conflicts with v2ray's license.
```
—— 我已将 [仓库](https://github.com/JimmyHuang454/hysteria)  修改回 MIT，很抱歉没有注释清楚。原始的 hysteria2 代码将保留原 MIT 协议。但由我新增的代码，从 [commit](https://github.com/apernet/hysteria/commit/cf6dc03156f4544f48f70ac7c70148208ebd6732) 开始为 GPL 协议，**并且特别授权 v2ray 在使用时所用协议为 MIT**。

一切都是可以协商的，按照我的理解，由我新增的代码，可以修改为 GPL 或 MIT 协议，如有不当之处请斧正；这样做的目的是不希望将我的劳动转移到我不想参与的项目。

```
Given that the quality of the related code is very poor and it is not synchronized with the upstream, I deleted it.
```
—— 关于 hysteria2 的代码我会持续地维护，并承诺有 bug 必修。我一直在定期查看 issue，但很可惜，并没有人反馈有关  hysteria2 的问题。

在添加 PR 时，已和 @xiaokangwang 讨论过 [合并条件](https://github.com/v2fly/v2ray-core/pull/2721#issuecomment-1817683097)：
> "... So long as this requirement is satisfied, I am happy to merge it so long as there is someone ready to maintain Hysteria stack in the future."

**Comment by Losalado** [comment]
请问一下，移除Hysteria协议是指开源协议？

**Comment by JimmyHuang454** [comment]
> 请问一下，移除Hysteria协议是指开源协议？

这个 issue 是关于 @nekohasekai 提交的 [commit](https://github.com/v2fly/v2ray-core/commit/1d21d7a07761af3b40ecfbf418b0849eb1c3918b) 。

**Comment by AkinoKaede** [comment]
> It is imperative that specific terms and conditions pertaining to V2Ray applications be clearly outlined within the license.

Of course, it is best to use MIT license.

**Comment by JimmyHuang454** [comment]
> It is imperative that specific terms and conditions pertaining to V2Ray applications be clearly outlined within the license.

Yes, [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria), which is used by v2ray, is licensed under the MIT License.

**Comment by AkinoKaede** [comment]
> > It is imperative that specific terms and conditions pertaining to V2Ray applications be clearly outlined within the license.
> 
> Yes, [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria), which is used by v2ray, is licensed under the MIT License.

It is crucial that V2Ray refrain from using any code licensed under the GPL. While modifying the GPL could theoretically accomplish your objective, determining whether the resulting custom license adheres to the definitions of free software and open-source software necessitates the expertise of professionals.

**Comment by JimmyHuang454** [comment]
**No. I am not modifying the GPL.** 

When v2ray use [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria), it is under MIT. When [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria) use by others project such as [Xray](https://github.com/XTLS/Xray-core), it is not under MIT!

**Comment by AkinoKaede** [comment]
> **No. I am not modifying the GPL.**
> 
> When v2ray use [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria), it is under MIT. When [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria) use by others project such as [Xray](https://github.com/XTLS/Xray-core), it is not under MIT!

Dual licensing seems to be the way to go, and you need to add content under both licenses to your repository, and you need another license to state when that applies.

**Comment by JimmyHuang454** [comment]
> > **No. I am not modifying the GPL.**
> > When v2ray use [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria), it is under MIT. When [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria) use by others project such as [Xray](https://github.com/XTLS/Xray-core), it is not under MIT!
> 
> Dual licensing seems to be the way to go, and you need to add content under both licenses to your repository, and you need another license to state when that applies.

Of course. I call it “在中国是中国籍,在美国是美国籍” license.

**Comment by AkinoKaede** [comment]
This is my personal take on the matter from a professional standpoint. However, it’s still up to @xiaokangwang  to finalize it.

**Comment by JimmyHuang454** [comment]
> This is my personal take on the matter from a professional standpoint. However, it’s still up to @xiaokangwang to finalize it.

I am willing to change to just MIT. As I said, everything can be negotiated, but I would be happy if @xiaokangwang accepts a dual license.

**Comment by nekohasekai** [comment]
限制代码被其他人使用的想法是非自由的，OSI/DFSG 也规定开源许可证不得歧视任何人、团体或用途，也不允许特定于产品。也就是说，从技术上来说，由于 V2Ray 被各大发行版所打包，不应该允许修改授权为非开源的。

从技术上来说，V2Ray 也没有依赖非成员创建的库来实现整个协议的先例，这意味着相关代码不被 V2Ray 维护：无论如何依赖都需要更新，而不是没有 bug 就可以不管，用户不需要一个不被项目维护的功能。

**Comment by xiaokangwang** [comment]
@JimmyHuang454 I would like to apology for not checking license before merging your code. My decision has not been changed, and I am happy to merge it back to V2Ray once your fork of hysteria2 is aligned with its original license.

As for per project license, the 8th article of [open source definition](https://opensource.org/osd) explicitly prohibit license be specific to certain project, so it would not possible to license it under MIT just for V2Ray.

BTW: if you would like to make something specific to V2Ray, you could make sure it have better integration with V2Ray's features and functionalities, so that there will be unique benefit that is not portable to other projects.

As for dependency on third party repositories, my policy is that so long as it is pluggable (via feature registration) I does not object its usage, so long as the respective library is well maintained.

**Comment by JimmyHuang454** [comment]
> As for per project license, the 8th article of [open source definition](https://opensource.org/osd) explicitly prohibit license be specific to certain project, so it would not possible to license it under MIT just for V2Ray.

Thank you, @xiaokangwang. I will switch to just MIT.  

I came up with the dual license because of [this](https://github.com/apernet/hysteria/pull/996#issuecomment-2016544070), although I think it is still debatable. But never mind.  

BTW @nekohasekai : I am a totally open-source guy. You can check my other code—it’s all under WTFPL!

**Comment by nekohasekai** [comment]
Hysteria 保持 MIT 是基于不同的原因 —— 它只是想被更多的闭源产品使用，并且不在乎所有这些价值，虽然你看起来也这么想，但**我相信**V2Ray 不是，因为 @xiaokangwang 用我所说的理由了拒绝我通过 GPL 授权的库实现一些功能的想法。

他乐于接受除此之外所有东西，只要它 “看起来没有影响到其他功能”，这是可笑的。你的代码不仅质量较差、疏于维护，还至使用了 replace 使 V2Ray 难以被其他项目依赖。

现在他不能这么做了，除非你将分支更改提交到上游，否则我不会接受同样的东西。

**Comment by RPRX** [comment]
> **No. I am not modifying the GPL.**
> 
> When v2ray use [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria), it is under MIT. When [JimmyHuang454/hysteria](https://github.com/JimmyHuang454/hysteria) use by other project such as [Xray](https://github.com/XTLS/Xray-core), it is not under MIT!

大可不必有这样的担心，我已多次明确表示 Xray 不会加 Hysteria；此外若你不修改 MIT 协议条款，则无法实现该目标
