### ISSUE TITLE
[Feature Request]VLESS指定TLS协议和加密组件

### ISSUE THREAD

**Issue by SteamSnake** [v2fly/v2ray-core#329]
VLESS协议的回落功能使得v2ray可以工作在服务器加密流量进入的第一站，但这导致了外部流量可以以TLS 1.0 ~TLS1.3，使用任意Cipher Suites和服务器通信，这可能为v2ray以外的其它网络服务带来安全隐患。

未来VLESS协议会考虑加入 *指定TLS握手协议/加密组件* 的设置项吗？

**Comment by kslr** [comment]
不会

**Comment by Fhokud** [comment]
也许可以取消TLS1.0和TLS1.1的支持？
如果将v2ray作为网站入站流量的第一站，这会是一个安全问题。
