### ISSUE TITLE
升级V2RAY后无法正常上网

### ISSUE THREAD

**Issue by ggmo** [v2fly/v2ray-core#33]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray: 4.25.1

v2ray_util: 3.7.7.9

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
 Chrome 通过 Socks/VMess 代理观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
[v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://wedail.com/09f9645b53c/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

4) 你期待看到的正确表现是怎样的？
正常访问youtube

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

{
  "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
  "inbounds": [
    {
    "port":18453,
      "listen": "127.0.0.1", 
      "tag": "vmess-in", 
      "protocol": "vmess", 
      "settings": {
        "clients": [
          {
          "id":"8f7fb55d-c7be-452f-ac74-8ab49e2055ad",
          "alterId":6688
          }
        ]
      }, 
      "streamSettings": {
        "network": "ws", 
        "wsSettings": {
          "path":"/09f9645b53c/"
        }
      }
    }
  ], 
  "outbounds": [
    {
      "protocol": "freedom", 
      "settings": { }, 
      "tag": "direct"
    }, 
    {
      "protocol": "blackhole", 
      "settings": { }, 
      "tag": "blocked"
    }
  ], 
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
          "1.1.1.1",
          "1.0.0.1",
          "8.8.8.8",
          "8.8.4.4",
          "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "vmess-in"
        ],
        "outboundTag": "direct"
      }
    ]
  
服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:
{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "bbcc.com",
            "port": 443,
            "users": [
              {
                "id": "8f7fb55d-c7be-452f-ac74-8ab49e2055ad",
                "alterId": 6688,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "bbcc.com"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/09f9645b53c/",
          "headers": {
            "Host": "bbcc.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "proxy",
        "ip": null,
        "domain": [
          "geosite:google",
          "geosite:github",
          "geosite:netflix",
          "geosite:steam",
          "geosite:telegram",
          "geosite:tumblr",
          "geosite:speedtest",
          "geosite:bbc",
          "domain:gvt1.com",
          "domain:textnow.com",
          "domain:twitch.tv",
          "domain:wikileaks.org",
          "domain:naver.com"
        ]
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "proxy",
        "ip": [
          "91.108.4.0/22",
          "91.108.8.0/22",
          "91.108.12.0/22",
          "91.108.20.0/22",
          "91.108.36.0/23",
          "91.108.38.0/23",
          "91.108.56.0/22",
          "149.154.160.0/20",
          "149.154.164.0/22",
          "149.154.172.0/22",
          "74.125.0.0/16",
          "173.194.0.0/16",
          "172.217.0.0/16",
          "216.58.200.0/24",
          "216.58.220.0/24",
          "91.108.56.116",
          "91.108.56.0/24",
          "109.239.140.0/24",
          "149.154.167.0/24",
          "149.154.175.0/24"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "domain:12306.com",
          "domain:51ym.me",
          "domain:52pojie.cn",
          "domain:8686c.com",
          "domain:abercrombie.com",
          "domain:adobesc.com",
          "domain:air-matters.com",
          "domain:air-matters.io",
          "domain:airtable.com",
          "domain:akadns.net",
          "domain:apache.org",
          "domain:api.crisp.chat",
          "domain:api.termius.com",
          "domain:appshike.com",
          "domain:appstore.com",
          "domain:aweme.snssdk.com",
          "domain:bababian.com",
          "domain:battle.net",
          "domain:beatsbydre.com",
          "domain:bet365.com",
          "domain:bilibili.cn",
          "domain:ccgslb.com",
          "domain:ccgslb.net",
          "domain:chunbo.com",
          "domain:chunboimg.com",
          "domain:clashroyaleapp.com",
          "domain:cloudsigma.com",
          "domain:cloudxns.net",
          "domain:cmfu.com",
          "domain:culturedcode.com",
          "domain:dct-cloud.com",
          "domain:didialift.com",
          "domain:douyutv.com",
          "domain:duokan.com",
          "domain:dytt8.net",
          "domain:easou.com",
          "domain:ecitic.net",
          "domain:eclipse.org",
          "domain:eudic.net",
          "domain:ewqcxz.com",
          "domain:fir.im",
          "domain:frdic.com",
          "domain:fresh-ideas.cc",
          "domain:godic.net",
          "domain:goodread.com",
          "domain:haibian.com",
          "domain:hdslb.net",
          "domain:hollisterco.com",
          "domain:hongxiu.com",
          "domain:hxcdn.net",
          "domain:images.unsplash.com",
          "domain:img4me.com",
          "domain:ipify.org",
          "domain:ixdzs.com",
          "domain:jd.hk",
          "domain:jianshuapi.com",
          "domain:jomodns.com",
          "domain:jsboxbbs.com",
          "domain:knewone.com",
          "domain:kuaidi100.com",
          "domain:lemicp.com",
          "domain:letvcloud.com",
          "domain:lizhi.io",
          "domain:localizecdn.com",
          "domain:lucifr.com",
          "domain:luoo.net",
          "domain:mai.tn",
          "domain:maven.org",
          "domain:miwifi.com",
          "domain:moji.com",
          "domain:moke.com",
          "domain:mtalk.google.com",
          "domain:mxhichina.com",
          "domain:myqcloud.com",
          "domain:myunlu.com",
          "domain:netease.com",
          "domain:nfoservers.com",
          "domain:nssurge.com",
          "domain:nuomi.com",
          "domain:ourdvs.com",
          "domain:overcast.fm",
          "domain:paypal.com",
          "domain:paypalobjects.com",
          "domain:pgyer.com",
          "domain:qdaily.com",
          "domain:qdmm.com",
          "domain:qin.io",
          "domain:qingmang.me",
          "domain:qingmang.mobi",
          "domain:qqurl.com",
          "domain:rarbg.to",
          "domain:rrmj.tv",
          "domain:ruguoapp.com",
          "domain:sm.ms",
          "domain:snwx.com",
          "domain:soku.com",
          "domain:startssl.com",
          "domain:store.steampowered.com",
          "domain:symcd.com",
          "domain:teamviewer.com",
          "domain:tmzvps.com",
          "domain:trello.com",
          "domain:trellocdn.com",
          "domain:ttmeiju.com",
          "domain:udache.com",
          "domain:uxengine.net",
          "domain:weather.bjango.com",
          "domain:weather.com",
          "domain:webqxs.com",
          "domain:weico.cc",
          "domain:wenku8.net",
          "domain:werewolf.53site.com",
          "domain:windowsupdate.com",
          "domain:wkcdn.com",
          "domain:workflowy.com",
          "domain:xdrig.com",
          "domain:xiaojukeji.com",
          "domain:xiaomi.net",
          "domain:xiaomicp.com",
          "domain:ximalaya.com",
          "domain:xitek.com",
          "domain:xmcdn.com",
          "domain:xslb.net",
          "domain:xteko.com",
          "domain:yach.me",
          "domain:yixia.com",
          "domain:yunjiasu-cdn.net",
          "domain:zealer.com",
          "domain:zgslb.net",
          "domain:zimuzu.tv",
          "domain:zmz002.com",
          "domain:samsungdm.com"
        ]
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "block",
        "ip": null,
        "domain": [
          "geosite:category-ads"
        ]
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }
    ]
  }
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
2020/03/14 12:03:46 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/03/14 12:06:13 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/04/06 10:23:32 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/06/06 17:24:12 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/06/16 19:15:05 [Warning] v2ray.com/core: V2Ray 4.23.1 started

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

2020/06/07 09:16:47 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:cdn.mrfdev.com:443 [direct] 
2020/06/07 09:16:47 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:cdn.mrfdev.com:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:lh3.googleusercontent.com:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:lh3.googleusercontent.com:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:stats.g.doubleclick.net:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:adservice.google.com:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:cdn.mrfdev.com:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:cdn.mrfdev.com:443 [direct] 
2020/06/07 09:16:48 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:dl.google.com:443 [direct] 
2020/06/07 09:16:49 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:16:49 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:pagead2.googlesyndication.com:443 [direct] 
2020/06/07 09:16:49 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:www.google-analytics.com:443 [direct] 
2020/06/07 09:16:51 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:stats.g.doubleclick.net:443 [direct] 
2020/06/07 09:16:51 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:adservice.google.com.hk:443 [direct] 
2020/06/07 09:16:51 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:adservice.google.com:443 [direct] 
2020/06/07 09:16:51 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:partner.googleadservices.com:443 [direct] 
2020/06/07 09:16:51 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:16:51 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:googleads.g.doubleclick.net:443 [direct] 
2020/06/07 09:16:53 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:16:53 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:googleads.g.doubleclick.net:443 [direct] 
2020/06/07 09:16:53 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:16:53 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:googleads.g.doubleclick.net:443 [direct] 
2020/06/07 09:16:53 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:www.google.com:443 [direct] 
2020/06/07 09:16:53 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:www.google.com.hk:443 [direct] 
2020/06/07 09:16:53 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:16:54 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:www.google.com:443 [direct] 
2020/06/07 09:16:54 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:tpc.googlesyndication.com:443 [direct] 
2020/06/07 09:17:01 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:17:10 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:mrfdev.disqus.com:443 [direct] 
2020/06/07 09:17:17 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59188 accepted tcp:checkappexec.microsoft.com:443 [direct] 
2020/06/07 09:17:28 tcp:112.97.50.185:59068 accepted tcp:update.googleapis.com:443 [direct] 
2020/06/07 09:17:28 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:update.googleapis.com:443 [direct] 
2020/06/07 09:17:38 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:redirector.gvt1.com:80 [direct] 
2020/06/07 09:17:38 tcp:112.97.50.185:59068 accepted tcp:r6---sn-a5meknll.gvt1.com:80 [direct] 
2020/06/07 09:17:39 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:r6---sn-a5meknll.gvt1.com:80 [direct] 
2020/06/07 09:17:55 tcp:112.97.50.185:59068 accepted tcp:raw.githubusercontent.com:443 [direct] 
2020/06/07 09:18:04 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:github.com:443 [direct] 
2020/06/07 09:18:10 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:github.com:443 [direct] 
2020/06/07 09:18:11 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59156 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:18:11 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:ocsp.digicert.com:80 [direct] 
2020/06/07 09:18:16 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:16 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:16 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:16 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:16 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:16 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:avatars1.githubusercontent.com:443 [direct] 
2020/06/07 09:18:16 tcp:112.97.50.185:59068 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:16 tcp:112.97.50.185:59068 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:16 tcp:112.97.50.185:59068 accepted tcp:github.githubassets.com:443 [direct] 
2020/06/07 09:18:20 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:www.google-analytics.com:443 [direct] 
2020/06/07 09:18:22 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:api.github.com:443 [direct] 
2020/06/07 09:18:22 tcp:112.97.50.185:59068 accepted tcp:collector.githubapp.com:443 [direct] 
2020/06/07 09:18:22 tcp:112.97.50.185:59068 accepted tcp:ocsp.digicert.com:80 [direct] 
2020/06/07 09:18:24 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:ocsp.digicert.com:80 [direct] 
2020/06/07 09:18:25 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59218 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:18:26 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:nav.smartscreen.microsoft.com:443 [direct] 
2020/06/07 09:18:26 tcp:112.97.50.185:59068 accepted tcp:github-production-release-asset-2e65be.s3.amazonaws.com:443 [direct] 
2020/06/07 09:18:26 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:x.urs.microsoft.com:443 [direct] 
2020/06/07 09:18:27 tcp:112.97.50.185:59068 accepted tcp:ocsp.digicert.com:80 [direct] 
2020/06/07 09:18:27 tcp:[2408:84f3:2c80:7c95:91:1d0a:9eab:570a]:59138 accepted tcp:ocsp.digicert.com:80 [direct] 
2020/06/07 09:18:30 tcp:112.97.50.185:59068 accepted tcp:chrome.google.com:443 [direct] 

8) 其它相关的配置文件（如 Nginx）和相关日志。
    server {
        listen 443 ssl http2;
        listen [::]:443 http2;
        ssl_certificate       /data/v2ray.crt;
        ssl_certificate_key   /data/v2ray.key;
        ssl_protocols         TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers           TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+ECDSA+AES128:EECDH+aRSA+AES128:RSA+AES128:EECDH+ECDSA+AES256:EECDH+aRSA+AES256:RSA+AES256:EECDH+ECDSA+3DES:EECDH+aRSA+3DES:RSA+3DES:!MD5;
        server_name bbcc.com;
        index index.html index.htm;
        root  /home/wwwroot/3DCEList;
        error_page 400 = /400.html;

        # Config for 0-RTT in TLSv1.3
        ssl_early_data on;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security "max-age=31536000";

        location /09f9645b53c/
        {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:18453;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        # Config for 0-RTT in TLSv1.3
        proxy_set_header Early-Data $ssl_early_data;
        }
}
    server {
        listen 80;
        listen [::]:80;
        server_name bbcc.com;
        return 301 https://bbcc.com$request_uri;
    }
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by ggmo** [comment]
V2NG一直提示
 [Warning] bbcc to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: bbcc to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: bbcc to dial WebSocket > v2ray.com/core/transport/internet/websocket: bbcc to dial to (wss://bbcc.com/09f9645b53c/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts bbcc

**Comment by ggmo** [comment]
v2ray: 4.25.1

v2ray_util: 3.7.7.9
[root@careline ~]# telnet youtube.com 443
Trying 2607:f8b0:4007:813::200e...
Connected to youtube.com.
Escape character is '^]'.

**Comment by kslr** [comment]
233 脚本升级的么

**Comment by ggmo** [comment]
> 233 脚本升级的么
不是，用的这个 https://github.com/wulabing/V2Ray_ws-tls_bash_onekey
@wulabing 不知道作者有没有注意到

**Comment by kslr** [comment]
检查V2有没有在工作

**Comment by ggmo** [comment]
V2进程正常，看不到请求日志刷新，客户端提示502错误

**Comment by fptzdh1989** [comment]
经我测试，软件冲突，手机端口问题，停止或者暂停其他VPN，SSR只开V2rayNG就可以，针对ping通，真实连接不通-1的可以试一试！

**Comment by FrankShang0706** [comment]
怎么买这个节点啊，找不到地方

**Comment by fptzdh1989** [comment]
你要买什幺机场的


Kslr <notifications@github.com> 于 2020年7月14日周二 16:43写道：
