### ISSUE TITLE
发现一处bug，希望可以修复

### ISSUE THREAD

**Issue by zqs125** [v2fly/v2ray-core#337]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray-core版本：4.31.2
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
目前已经测试过多个客户端，v2ray-core内核也试过多个，从4.2x.x到4.31.2都有此问题

手机上使用v2，有时需要ml，所以使用的是tcp+tls+http伪装，已开启“允许不安全证书”，然后客户端设置如下：
"request": {
	"headers": {
		"Host": [
			"www.aaa.com"
		]
	}
}
当host只填一个时，ml正常，查询流量详情请求host是www.aaa.com，没有问题
"request": {
	"headers": {
		"Host": [
			"www.aaa.com",
                        "www.bbb.com",
                        "www.ccc.com"
		]
	}
}
当host填两个或以上时，就出问题了，ml失败，查询流量详情后请求host是www.aaa.com,www.bbb.com,www.ccc.com这样的，
按v2fly.org配置文档里的说明“HTTP 头，一个键值对，每个键表示一个 HTTP 头的名称，对应的值是一个数组。每次请求会附上所有的键，并随机选择一个对应的值”，每次请求是随机选择一个值的，现在的情况是当填多个时把多个值拼接成了一个字符串，然后当host了
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
正常应该是多个值时随机选择，流量详情的host应该是www.aaa.com或www.bbb.com或www.ccc.com
4) 你期待看到的正确表现是怎样的？
期待看到的是修复这个bug，随机从数组中取值当host，而不是把全部的值拼成一个字符串当host
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

客户端配置:
{
    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "tag": "direct"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": "1080",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
            }
        },
        {
            "listen": "127.0.0.1",
            "port": "1081",
            "protocol": "http"
        }
    ],
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "",
                        "port": 1234,
                        "user": [
                            {
                                "id": "",
                                "alterId": 4,
                                "security": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "tcpSettings": {
                    {
                          "type": "http",
                          "request": {
                                "headers": {
                                     "Host": [
                                           "www.aaa.com",
                                            "www.bbb.com"
                                            "www.ccc.com"
                                     ]
                                }
                          }
                    }
                },
                "security": "tls",
                "tlsSettings": {
                    "serverName": "example.domain",
                    "allowInsecure": true
                }
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        }
    ]
}
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by lyx32** [comment]
这个貌似不是bug吧。
大多数head默认都是一个键对应一个值。
如果对应多个值就拼接起来当成一个值，就像cookie那样。

**Comment by rprx** [comment]
是 BUG，但我看了下现在的代码，从配置加载到运行时的 pick，没发现明显的逻辑问题。

麻烦测试一下从哪个版本开始出现此问题的。

**Comment by rprx** [comment]
以及需要纠正，TLS 是在 HTTP 伪装外面的，TLS 里面的内容无法被看到。

**Comment by zqs125** [comment]
> 这个貌似不是bug吧。
> 大多数head默认都是一个键对应一个值。
> 如果对应多个值就拼接起来当成一个值，就像cookie那样。

这个host是个数组，是可以做到随机取一个值的，而不是全拼接起来

**Comment by zqs125** [comment]
> 是 BUG，但我看了下现在的代码，从配置加载到运行时的 pick，没发现明显的逻辑问题。
> 
> 麻烦测试一下从哪个版本开始出现此问题的。

我是从4.28.1一直试到4.31.2，这个问题都存在，4.28.1之前的版本没有试，你看从哪个版本开始试，我来测试

**Comment by rprx** [comment]
已确定非 v2ray-core 的 BUG，而是 GUI 软件的配置问题。拿 v2rayN&G 来举例，当你在 HTTP 伪装外套一层 TLS 时，**“伪装域名(host)”** 填的值不仅会应用于 HTTP 伪装的 Host，还会被原封不动填到 TLS 的 serverName。需要指出，根据你的目的，此时内层的 HTTP 伪装是完全没有作用的，观察者只能看到 SNI，即 `"serverName": "www.aaa.com,www.bbb.com"`。

这告诉我们，只通过请求的 SNI 来判断访问什么网站是不靠谱的，最好读取证书，并验证有效性。
