### ISSUE TITLE
无法用tcping命令工具，获得代理网站的响应时间（如youtube等）

### ISSUE THREAD

**Issue by wikihua** [v2fly/v2ray-core#338]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
**4.31.2**

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
**tcping**

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**tcping 代理的网站未通（直接返回本地时间），并且客户端报错 insufficient header > EOF**

4) 你期待看到的正确表现是怎样的？
**能够返回通过代理的tcping响应时间**

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

> 2020/10/20 00:47:30 [Info] [3671633917] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > EOF
> 2020/10/20 00:47:30 tcp:127.0.0.1:54182 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
> 2020/10/20 00:47:32 tcp:127.0.0.1:54183 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
> 2020/10/20 00:47:32 [Info] [3196213466] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > EOF
> 2020/10/20 00:47:33 tcp:127.0.0.1:54184 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
> 2020/10/20 00:47:33 [Info] [844604380] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > EOF
> 2020/10/20 00:47:35 tcp:127.0.0.1:54188 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
> 2020/10/20 00:47:35 [Info] [3767046006] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > EOF

**tcping结果如下：**

![A3BA9EAD-1EFB-4F6C-A95B-4176490B4F83](https://user-images.githubusercontent.com/45312187/96488211-36cd6680-1270-11eb-8e70-016d809bf22a.jpeg)

**Comment by LGA1150** [comment]
所有的四层（或以上）代理都会这样，因为需要先与代理建立TCP连接

**Comment by k79e** [comment]
tcping -h 即可

**Comment by wikihua** [comment]
> 所有的四层（或以上）代理都会这样，因为需要先与代理建立TCP连接

谢谢，原来是这个原因...  所以tcping把和本地客户端代理建立的tcp连接，当成已经建立完返回的时间了是吧...

好可惜，本来还想用tcping来做一些vps访问墙外网站的ip优选

**Comment by qjebbs** [comment]
@wikihua 可以用 vmessping
