### ISSUE TITLE
dns返回不应当包含aa flag

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#340]
版本 当前最新版4.31.2

dig t.cn
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38278
;; flags: qr **aa** rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

https://www.bind9.net/dns-header-flags
bit 5   AA  Authoritative Answer [RFC 1035]

缓存自称是权威记录是很荒谬的.

配置用的是本地暴露一个任意门然后出站dns让他走指定dns. 多个dns分流那样.

目测是dns记录的开头2个字节 是id
后面好像也是2个字节 但是是比特位 第五bit的确是被设定成1的. 所以hex是0x8580 (qr rd ra aa)
其他一般都是0x8180(qr rd ra)

**Comment by k79e** [comment]
我是向里面的上游dns都查询过了的 不存在他们就是错的结果所以缓存了过来这种事情.

发现doh请求也是那样. (本地任意门 配置出站dns 配置dns:{}用doh)

**Comment by k79e** [comment]
有点事情想请教

为啥我用了doh本地模式 我也看见本地建立了doh连接 怎么还会被服务器的dns透明代理影响!??
我不太确定 这可能是dns并行发送了 本地doh走一份 同时也走代理远程请求一下. 远程一定不是doh 是普通的53请求 具体咋回事我也不清楚 我好像记得过去我也提到过类似的情况.

**Comment by k79e** [comment]
https://github.com/v2ray/v2ray-core/issues/2332
https://github.com/v2ray/v2ray-core/issues/2331

**Comment by k79e** [comment]
我用的老版本的v2rayn但是配置看起来没问题吧
  "dns": {
    "servers": [
      "https+local://dns9.quad9.net/dns-query"
    ]

就算他走了远程查询 local作废失效 那也应该客户端看不见9999的连接啊? 不是么!??
所以还是走了本地. 所以9.9.9.9 是否被路由 不用管. //而且就算被路由 也会是远程发起doh啊 不可能被透明代理劫持的
所以跟路由没关系

**Comment by k79e** [comment]
4.34.0依然有问题

**Comment by Loyalsoldier** [comment]
Fixed in https://github.com/v2fly/v2ray-core/pull/817

You can try the pre-built binary in here: https://github.com/v2fly/v2ray-core/actions/runs/678733446
