### ISSUE TITLE
fallback转发的http请求未使用正确的host头部

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#345]
#341 被关掉了我不知道什么意思. 我说的是使用正确头部之后 才正常返回.

可是正常访问不应该用户去配置头部吧 
而且我也提到了 fallback填域名也是那样. 填了域名就已经有host了才对不是么!??

> TCP，格式为 "addr:port"，其中 addr 支持域名、IPv4、IPv6，若填写域名，将直接发起连接（而不走内置的 DNS）。
你说明书自己不是写的支持域名么. 而且就算不支持 addr也应当是个ip地址才对.
可是发送出去的ip/域名都是错的 这样很不对劲!!!
我填个域名 然后他发出去 **域名没了**

那样在单host上面 你转发过去看似没问题 

ip上有多个host的时候决定有问题!!
不信你自己fallback填个t.cn 看看是不是非302.
302才是正常返回.
host写ip是403. 写地址是410. 什么都不写或者写正确的是302.

难道我需要附上配置文件么
    "fallbacks": [
        {	"xver": 0,
            "dest": "127.0.0.1:80"
        }
    ]

改成其他地址 比如
    "fallbacks": [
        {	"xver": 0,
            "dest": "t.cn:80"
        }
    ]

![image](https://user-images.githubusercontent.com/6483602/96831920-78c4fb00-1470-11eb-81b9-ac244fb40bcc.png)
图上就是发送给t.cn的host 很明显是错的

**Comment by rprx** [comment]
这里需要把 TLS 内的流量原样转发，请详细阅读文档，并理解此设计的安全意义。

**Comment by k79e** [comment]
什么叫做tls内流量!??
不是配置fallback的 addr:port之后
vless就自己去访问 addr:port资源啊. 这时候无域名的时候 host应该就是addr才对. 实际上却不是.

做这个应当翻译下地址不是么
如果v2的地址是127.0.0.1:1234 我访问https://127.0.0.1:1234/addr
这时候发出的请求头应该是 t.cn/addr 难道不是这样么? 因为fallback里面写了域名t.cn:80

**Comment by rprx** [comment]
VLESS 不以 HTTP 的方式访问 dest，只是把 TLS 内的流量转发过去，无论字节有多少，无论内容是什么。

**Comment by k79e** [comment]
原来是这样. 在说明书最下面.....

**Comment by rprx** [comment]
其实 fallbacks 文档各处都体现出了只是流量转发，而不是传统反代，为了更加清晰，等下会更新文档。另外，昨天已清空文档旧目录。
