### ISSUE TITLE
客户端用内置dns之后 服务器端dns重复解析

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#346]
此问题会造成doh泄露 因为服务器用默认dns再请求一遍.

一句话版本 即: 无论客户端dns是否走代理. 服务器都会用系统dns再请求一下
2句话版本: vmess头部不是可以放ip之类的信息么 那服务器为啥还多此一举再重复查询?
------------------------------------------------------------
也就是 客户端对要上网的域名解析的结果 没有被用于网络连接上.

我发现服务器要是指定dns查询的话 别提多坑了, 他用指定的查一次 然后用系统自带的再查一次

疑问: hosts只对direct管用么?

https://github.com/v2fly/v2ray-core/issues/346#issuecomment-715819933 记录了些连接信息(协议头) 用于诊断

**Comment by Loyalsoldier** [comment]
建议把服务端也升级到最新版。

另外，如果不希望服务端使用系统 DNS，请在服务端配置 DOHL，并为该 DOHL 域名配置 host

**Comment by k79e** [comment]
服务端配置内置dns好像没用啊
我测试的服务端内置dns写了个别的 结果他根本不理 新版本有改变?
服务端如果管用 那太好了 还需要折腾什么啊 内置写个ipaddr不就行了.... 

然而内置dns对服务端好像没作用吧 我还想问问呢?

**Comment by k79e** [comment]
我看见vmess他说有端口和地址 这个选项 地址可以是ip和domain

端口 Port：Big Endian 格式的整型端口号；
地址类型 T：
0x01：IPv4
0x02：域名
0x03：IPv6

既然头部有这个选项 而get是另一回事 是下层协议了.
上层应该包含如地址=直连dns 或者远程dns回显的ipaddr
然后下层包括的请求 即http请求 发送过去

服务器不是直接解析地址头部 然后给http get用不就行了.
服务器端无需请求dns才是. 你看他自己写的头部有那个选项 比s5还更好 s5还要费好多个rtt 这个的就不用.

**Comment by k79e** [comment]
都更新了
本机已缓存dns 再次重复请求 服务器还是会发送dns一遍
//服务器没缓存 本机无限发送重复请求 服务器无限请求dns
//服务器有内置dns 但是无效. 所以内置dns只对客户端管用 如说明书所说. 他涉及到**请求**

**Comment by k79e** [comment]
奇怪了 咋好像从来没人问问内置dns为啥在服务器端无效呢
是不是这个用法不正确呢

**Comment by zry98** [comment]
> 奇怪了 咋好像从来没人问问内置 dns 为啥在服务器端无效呢
> 是不是这个用法不正确呢

同样无法使用，即使按照文档对 freedom 设置了 domainStrategy 为 UseIP，DNS 请求仍不从设置的 servers 走

**Comment by k79e** [comment]
果然是那样的
说明书提到服务端使用!!! 但是从来都不可以用 所以应当有问题!!

`当值是 "https+local://host:port/dns-query" 的形式，如 "https+local://dns.google/dns-query"，V2Ray 会使用 DOH本地模式 进行查询，即 DOH 请求不会经过 Routing/Outbound 等组件，直接对外请求，以降低耗时。一般适合**在服务端使用**。也可使用非标端口和路径。(4.22.0+)`

**Comment by k79e** [comment]
我看到别处提到local比服务器模式更慢 我今天发现了结果

2020/10/23 14:36:14 [Info] v2ray.com/core/app/dispatcher: taking detour [direct]
 for [udp:1.2.4.8:53]
2020/10/23 14:36:14 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:1.2.4.8:53
2020/10/23 **14:36:14** [Info] v2ray.com/core/app/dns: UDP:1.2.4.8:53 got answer: t.
cn. TypeAAAA -> [] **90.0052ms**
2020/10/23 **14:36:14** [Debug] v2ray.com/core/app/dns: UDP:1.2.4.8:53 updating IP r
ecords for domain:t.cn.
2020/10/23 **14:36:18** [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n t.cn at server UDP:1.2.4.8:53 > context deadline exceeded
2020/10/23 **14:36:18** tcp:127.0.0.1:12469 accepted tcp:t.cn:80
现象是 我发现本地直连dns接到记录 他会卡在服务器也成功查询之后才发起连接. 我就眼睁睁的看着这个测试卡住 但是dns根本就是瞬间收到.
又是4秒超时出现

**Comment by k79e** [comment]
发现配置了freedom没你说的问题 反而服务器是按照指定dns查询了.
我看看doh去... 坑人啊 那客户端本机使用dohL 为啥服务器也要配置dohL 这还要双向改么

**Comment by k79e** [comment]
关于这个地方的逻辑我感觉是不是得讨论下?

就关于本机使用dns:{}查询 配置直连 
使用代理的时候 就是本机已经得了ip. 这时候服务器再用dns查询 多此一举(无论服务器是否按指定还是系统内置dns)
这时候 本机是走s5远程解析的 这个请求是发给v2本机客户端的. 他是不是该多做下处理
然后把发出去的vmess包括个ip 这样服务器就不需要查询了. 难道vmess连s5都不如!?? 

s5也没仔细研究过 但是他默认就是本地查询的 是推送ip然后紧接着发送GET请求.(所以这个东西很费rtt) 这样发对端应该不需要查询才是.
结果测试我感觉是不需要服务器解析 因为s5的效果之一就是指定ip连接啊 你把他给ip换走了 哪怕接到错误机器上 也可以连接.
证明服务器不需要解析.

**Comment by k79e** [comment]
坑死人了 有解决方法 但是这不代表这程序没问题

我想了又想 想出了老bug #353 
我还就用了这个连接流程的bug 把本机dns的问题绕过去了.
也就是配置hosts为所有域名返回随意一个地址(空地址没试过)
然后info日志会显示 dns: returning 2 IPs for domain
不会是dns .... for 这种查询日志 这样就是生效了.

然后立刻就会走远程解析 本机就bypass了 也不会泄露了. 缺点就是用户没法指定使用远程解析.

我认为正确流程应该是这样.

不需要解析的就只有普通s5 好像s4也是? 那个直接就是以ip访问的. 普通人fq应该不那样用把... 

v2ray应当有办法判断是否是远程解析的流量
远程解析分为
1. 默认远程解析 即 客户机没有配置dns:{} 只使用远程服务器的dns
2. 客户端指定dns

哎呀我不想了 浪费时间
放个vmess 明文请求 我怎么看他跟协议描述对不上啊 谁知道咋回事么
文档过期了?
0000  fc 20 03 49 9a 40 7e c8  9b 15 c4 33 1f d4 0b 9e   . .I.@~. ...3....
0010  83 e2 f6 3d 1c 0f 65 41  59 e4 58 bd ae bc c7 60   ...=..eA Y.X....`
0020  e1 00 d4 5c 5f 54 8c fe  cd 6d d8 3c 68 b8 c5 e7   ...\_T.. .m.<h...
0030  48 be ec 1b 59 04 6e a7  16 af 94 82 eb d5 03 89   H...Y.n. ........
0040  26 c2 ed d2 ef f2 34 cb  1e 06 47 45 54 20 2f 20   &.....4. ..GET / 
0050  48 54 54 50 2f 31 2e 31  0d 0a 48 6f 73 74 3a 20   HTTP/1.1 ..Host: 
0060  74 2e 63 6e 0d 0a 55 73  65 72 2d 41 67 65 6e 74   t.cn..Us er-Agent
0070  3a 20 63 75 72 6c 2f 37  2e 36 35 2e 31 0d 0a 41   : curl/7 .65.1..A
0080  63 63 65 70 74 3a 20 2a  2f 2a 0d 0a 0d 0a         ccept: * /*....

**Comment by k79e** [comment]
第17个不是指令么 前16是验证信息
17字节文档说始终是1 10是0x83啊 不是1啊

懂行的快来解释下!!

**Comment by k79e** [comment]
目前暂时避开这个问题用keyword: 后面什么都不写 或者写个点 然后随便填个ip

**Comment by kslr** [comment]
![sticker](https://user-images.githubusercontent.com/5516323/97070537-aabe9480-160b-11eb-9336-601a1f8da725.png)

**Comment by k79e** [comment]
这是什么猫~~~~~~~~~~~

**Comment by k79e** [comment]
虽然有些啰嗦 不过还是有了暂时凑合的解决办法 :D
