### ISSUE TITLE
VLESS 配置好之后访问一直报错

### ISSUE THREAD

**Issue by fengcharles** [v2fly/v2ray-core#347]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.31.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.3 linux/amd64)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
访问推特，IOS使用小火箭代理。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
访问不了,超时

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
        {
            "port": 9000,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxxx",
                        "flow": "xtls-rprx-origin",
                        "level": 0
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/letsencrypt/archive/xxx/fullchain1.pem",
                            "keyFile": "/etc/letsencrypt/archive/xxx/privkey1.pem"
                        }
                    ]
                }
            }
        },

```

客户端配置:

```javascript
    {
  "created" : 1603353343.4075851,
  "weight" : 1603353343,
  "alterId" : "",
  "title" : "",
  "host" : "xxx.cc",
  "file" : "",
  "filter" : "",
  "uuid" : "121322EA-6FF0-439C-BC97-A82B6A46B9F1",
  "method" : "auto",
  "flag" : "HK",
  "obfs" : "none",
  "chain" : "",
  "updated" : 1603353343.456692,
  "type" : "VLESS",
  "cert" : "",
  "plugin" : "none",
  "user" : "",
  "protoParam" : "",
  "tls" : true,
  "port" : 9000,
  "proto" : "",
  "peer" : "",
  "password" : "5d1da051-25d5-48b6-a420-7f3fdcf4d183",
  "data" : "",
  "ping" : 69,
  "obfsParam" : ""
}
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript

2020/10/22 15:48:10 [Info] [1527988839] v2ray.com/core/proxy/vless/inbound: firstLen = 0
2020/10/22 15:48:10 [Info] [1527988839] v2ray.com/core/proxy/vless/inbound: fallback starts > v2ray.com/core/proxy/vless/inbound: fallback directly
2020/10/22 15:48:10 [Info] [1527988839] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: fallback ends > v2ray.com/core/proxy/vless/inbound: failed to fallback request payload > read tcp 10.170.0.3:9000->180.166.206.18:58295: i/o timeout
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by fengcharles** [comment]
补充一下，有时候是这种报错
`
2020/10/22 15:59:55 [Info] [2139611813] v2ray.com/core/proxy/vless/inbound: firstLen = 0
2020/10/22 15:59:55 [Info] [2139611813] v2ray.com/core/proxy/vless/inbound: fallback starts > v2ray.com/core/proxy/vless/inbound: fallback directly
2020/10/22 15:59:55 [Info] [2139611813] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: fallback ends > v2ray.com/core/proxy/vless/inbound: failed to fallback request payload > local error: tls: bad record MAC
、

**Comment by rprx** [comment]
多半是证书问题，先在其它系统上试试能否访问。

**Comment by fengcharles** [comment]
> 多半是证书问题，先在其它系统上试试能否访问。

非常 非常感谢，确实是证书的问题
原因是  我指定的证书目录 不是live 目录的。因为有多个的原因，用的不是最新的。

**Comment by fengcharles** [comment]
证书问题导致的，感谢大神的帮助
