### ISSUE TITLE
Proposal for a new multi-json config loader

### ISSUE THREAD

**Issue by qjebbs** [v2fly/v2ray-core#348]
## What it is?

This loader merges json files with `map[string]interface{}`, not struct-specified, like `Config`, works for all fields, even all kind of specifications of json files.

You can try it with [my fork](https://github.com/qjebbs/v2ray-core):

```sh
# start with new loader
v2ray -format jsons -c c.json -c [json_dir]
```

or 

```sh
# merge json files into one
v2ray jsons c.json [json_dir]
```

## Why do we need a new loader?

There are many restrictions with current loader:

- Limited capacity. It supports only outbounds and inbounds (rest of the logic are just overrides), no support for routing rules.
- Hard to maintain, if the struct `Config` updates, we had to update the func: [func (c *Config) Override(o *Config, fn string)](https://github.com/v2fly/v2ray-core/blob/3e87b187c4ff8d4abefd89b8d7c0e4e91cb54d59/infra/conf/v2ray.go#L354-L432)

## Benefits

The new loader:

- It always works, mergeing all fields and arrays for now and future, no matter how much change is made for `Config`
- Easy to explain, understand, and of course to use: Only simple values (String, Number, Boolean) are overrode, all others are merged. By doing these, we can call it a real merge loader.
- With the potential of merging everything, user can write freely for what they want, like, to put inbound->routing->outbound together in one file
- It can provides extra capabilities without changing the config codes, like sorting outbounds and routing rules by priority

## Breaking Change?

No.

To stay compatibale, the loader register no file extension, user has to specify format clearly to call it, this is the only way:

```
v2ray -format jsons -c c.json -c [dir_with_jsons]
```

## How it works?

Suppose we have 2 json below:

The 1st one:

```jsonc
{
  "log": {"access": "some_value", "loglevel": "debug"},
  "inbounds": [{"tag": "in-1"}],
  "outbounds": [{"priority": 100, "tag": "out-1"}],
  "routing": {"rules": [{"inboundTag":["in-1"],"outboundTag":"out-1"}]}
}
```

The 2nd one:

```jsonc
{
  "log": {"loglevel": "error"},
  "inbounds": [{"tag": "in-2"}],
  "outbounds": [{"priority": -100, "tag": "out-2"}],
  "routing": {"rules": [{"inboundTag":["in-2"],"outboundTag":"out-2"}]}
}
```

Output:

```jsonc
{
  // note: with new loader, access field is kept, loglevel is overrode 
  // But use the current loader, we lose access field
  "log": {"access": "some_value", "loglevel": "error"}, 
  "inbounds": [
	{"tag": "in-1"},
	{"tag": "in-2"}
  ],
  "outbounds": [
	{"tag": "out-2"}, // note the order is affected by priority
	{"tag": "out-1"}
  ],
  "routing": {"rules": [
	{"inboundTag":["in-1"],"outboundTag":"out-1"}
	{"inboundTag":["in-2"],"outboundTag":"out-2"}
  ]}
}
```
## V2ctl version of the new loader?

As discussed, we are removing the dependency from v2ray to v2ctl, v2ctl could have the merge command, but v2ray will never read from v2ctl for the new loader

**Comment by xiaokangwang** [comment]
Personally, I agree with your proposal, but the current implementation requires more consideration. You might wants to make sure that v2 can read multiple json contents from Stdin to make it works intuitively.  

As for "removing the dependency from v2ray to v2ctl", I believe this will be changing the default way for V2Ray to load content, not completely removing the possibility of depending on v2ctl. you shouldn't expect that when writing a PR.

**Comment by qjebbs** [comment]
Sorry i didn't make it clear.

No, I'm not talking about merging functionalities. I mean, new loader will be implemented for `jsonem` (internal loader) only, not `json` (external loader)

As for `read multiple json contents from Stdin`,  do you suggest that we should load content from stdin, like:

```json
{
  "log": {"access": "some_value", "loglevel": "debug"},
  "inbounds": [{"tag": "in-1"}],
  "outbounds": [{"priority": 100, "tag": "out-1"}],
  "routing": {"rules": [{"inboundTag":["in-1"],"outboundTag":"out-1"}]}
}
{
  "log": {"loglevel": "error"},
  "inbounds": [{"tag": "in-2"}],
  "outbounds": [{"priority": -100, "tag": "out-2"}],
  "routing": {"rules": [{"inboundTag":["in-2"],"outboundTag":"out-2"}]}
}
```

then, to use stdin like below?

```
(cat c1.json; cat c2.json) | v2ray
```

It's unusual use case, `v2ray -format jsons -c c1.json -c c2.json` is more intuitive.

Multi-json content above is not respect to JOSN specifications, we cannot use standard library, and frankly speaking I can't find an easy way to parse them.

**Comment by qjebbs** [comment]
@xiaokangwang  Or, you were just talking about "Call v2ctl > read v2ctl's output from **STDIN**", the external loader way?😂
