### ISSUE TITLE
V2ray Inbound 协议选择vless时，streamSettings 设为kcp时，设定的端口不监听。但其他协议端口正常监听，v2ray正常运行，无报错。

### ISSUE THREAD

**Issue by BlackOfMing** [v2fly/v2ray-core#349]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

V2Ray 4.31.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.3 linux/amd64)

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

查找技术文档，浏览网站等。目前我v2ray配置都是使用vless协议

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

设定的端口没有监听。

4) What's your expectation?

vless kcp设置端口应该监听

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [{
    "port": 10800,
    "listen": "0.0.0.0",
    "tag": "vless-inbound",
    "protocol": "vless",
    "settings": {
      "clients": [
        {
            "id": "xxxxxxxxxxxx",
            "flow": "",
            "level": 0,
            "email": "admin@example.com"
        }
      ],
      "decryption": "none"
    },

    "streamSettings": {
      "network": "kcp",
      "security": "none",
      "kcpSettings": {
        "mtu": 1350,
        "tti": 100,
        "uplinkCapacity": 100,
        "downlinkCapacity": 100,
        "congestion": true,
        "readBufferSize": 1,
        "writeBufferSize": 1,
        "header": {
          "type": "none"
        },
        "seed": "xxxxxx"
      }
    }

    //"allocate": {
      //  "strategy": "always",
        //"refresh": 10,
        //"concurrency": 3
    //}
  },
  {
    "port": 10000,

    "listen": "0.0.0.0",

    "tag": "wss-inbound",

    "protocol": "vless",

    "settings": {
        "clients": [
        {
          "id": "xxxxxxxxx",
          "flow": "",
          "level": 0,
          "email": "admin@example.com"
        }
        ],
        "decryption": "none"
    },

    "streamSettings": {
      "network": "ws",
      "security": "none",
      "wsSettings": {
        "acceptProxyProtocol": false,
        "path": "/xxxx",
        "headers": {
          "Host": "example.com"
        }
      }
    }
  },

  {
    "port": 10001,

    "listen": "0.0.0.0",

    "tag": "vless-inbound",

    "protocol": "vless",

    "settings": {
        "clients": [
        {
          "id": "xxxxxxxx",
          "flow": "",
          "level": 0,
          "email": "example.com"
        }
        ],
        "decryption": "none"
    },

    "streamSettings": {
      "network": "tcp",
      "security": "none",
      "tcpSettings": {
        "acceptProxyProtocol": false,
        "headers": {
           "type": "none"
        }
      }
    }
  }

  ],

  "outbounds": [{
    "protocol": "freedom",
    "settings": {},
    "tag": "direct"
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],

  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "domain": ["geosite:category-ads"],
        "outboundTag": "blocked"
      }
    ]
  },

  "dns": {
    "hosts": {
    },
    "servers": [
      {
        "address": "114.114.114.114",
        "port": 53,
        "domains": [
          "geosite:cn"
        ]
      },
      "x.x.x.x"
    ]
  },

  "policy": {
    "levels": {
      "0": {
        "handshake": 4,
        "connIdle": 30,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundUplink": false,
      "statsInboundDownlink": false,
      "statsOutboundUplink": false,
      "statsOutboundDownlink": false
    }
  },
  "other": {}
}

Server configuration:
Centos 7 linux x86_64
```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

无日志输出和日志文件，其他端口正常使用

Client error log:

无日志输出和日志文件，其他端口正常使用

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
无

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

test输出是 Configuration OK

10) If V2Ray service doesn't run, please attach journal log.

正常运行，仅仅少了一个监听的端口。

**Comment by rprx** [comment]
KCP 是 UDP

**Comment by BlackOfMing** [comment]
> KCP 是 UDP

没错，KCP是UDP，我检查的端口监听状态中包括了udp，udp端口也没监听。但是我这个设置是参考之前vmess的设置，在vmess使用KCP的案例中 Inbound 里的protocol  设置未vmess，现在我设置为了vless。请问这里有问题吗？另外官网文档 protocol 协议列表里面也没有UDP。

**Comment by rprx** [comment]
可以正常使用 KCP 吗（如果可以的话，则肯定监听了）

**Comment by BlackOfMing** [comment]
不能，我可以肯定的是没有监听kcp设置的端口。下图是根据上面粘贴的配置文件运行的截图。
![v2ray运行正常](https://user-images.githubusercontent.com/28438359/96964448-0bcb6700-153d-11eb-870c-86091ae42545.png)
![监听的端口](https://user-images.githubusercontent.com/28438359/96964480-17b72900-153d-11eb-8021-37960b23e57e.jpg)

**Comment by rprx** [comment]
试试监听其它端口？

**Comment by BlackOfMing** [comment]
更改端口无用，我怀疑新版的v2ray-core kcp可能有些问题，参考我其他两个配置，基本设置都差不多，区别只有"streamSettings" 这一部分不一样。 当选择tcp和ws时，可以提供正常服务，但设为kcp就不能监听端口了。

**Comment by rprx** [comment]
目前没有其它报告，有可能是配置问题

**Comment by BlackOfMing** [comment]
没错，你说的对，我找到问题答案了。感谢帮助。 原因是 有两个 inbound 使用了相同的Tag，所以最前面的inbound 就无效了。

**Comment by BlackOfMing** [comment]
可以关闭问题了，感谢。

**Comment by BlackOfMing** [comment]
不好意思，再次打扰了。目前使用vless 我有一个疑惑。vless 中kcp 动态端口是怎么使用的？

 在vmess 中 设置kcp 动态端口，需要两个inbound。

1.  kcp 动态端口inbound。 
2.  固定端口入口vmess inbound。 

固定端口入口 vmess inbound 通过     "detour":  配置指令将流量重定向到动态端口的kcp inbound。解决了kcp因端口变化的连接问题。

但是在vless中，我看官方文档并没有 detour 这个指令。 那么 动态kcp端口的inbound 配置后，客户端怎么知道连接哪个端口？ 
这个可以问题可以解答下吗？

还是说目前vless 并不支持之前vmess 的动态端口连接方式，无法使用动态端口？

**Comment by rprx** [comment]
目前 VLESS 不支持动态端口

**Comment by tt-nb** [comment]
@BlackOfMing 想咨询你一下，kcp现在的实际体验如何，稳定不？记得去年的时候，vps线路差，想开mkcp提速，然后被秒封端口和ip

**Comment by BlackOfMing** [comment]
@tt-nb 差不多，去年我也是用了一两天mkcp动态端口，IP就没了，就换了个IP。我目前用kcp有两种方法。
1. 使用v2ray mkcp 和 udp2ra,。udp2raw 可以将udp伪装为tcp流量，绕过运营商udp流量限速。整体流程如下。
    本机windows 浏览器 -> 本机v2ray mkcp客户端 -> 本机udp2raw客户端 -> vps udp2raw服务端 -> vps v2ray kcp服务端 -> 网站。
2. 不使用v2ray的kcp，使用 kcptun的kcp。 流程如下。
     本机windows 浏览器 -> 本机v2ray vless客户端 -> 本机kcptun客户端 -> vps kcptun服务端 -> vps v2ray vless服务端 -> 网站。

我的是移动网络，晚上会卡一点，不过正常使用看视频720p也没啥问题。联通和电信会好很多。

以前我经常用第一种方式，速度快，很快，非常快，不过好像不能持久快速度，用一段时间速度就会慢，过几天速度还会回来。现在基本我都是用第二种方式，基本需求都能满足，网速大概 几百K到1MB 左右。

我也搜过一些分享经验和自己体会，确实kcptun比v2ray的kcp好一点，基本不会被封。

这两个 插件 github都有，直接搜索，选择人最多的就行，kcptun有图形化界面，udp2raw只能命令行。

**Comment by kslr** [comment]
kcp 要用 seed
