### ISSUE TITLE
hosts配置127.0.0.1时 不应当返回2个地址

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#354]
他返回了::1 和127.0.0.1
如果我这个地址没监听怎么办!??
    "hosts": {
        "regexp:": "127.0.0.1"
    }
给所有域名启用hosts 然后联网日志是返回2个地址 改其他的127.0.0.2没这个情况

**Comment by chinsyo** [comment]
请按照issue模板提供必要的信息进行讨论。可能相关的代码片段：

[](https://github.com/v2fly/v2ray-core/blob/9c1f251173be1945c34c0d081786cea6437eeb02/app/dns/hosts.go#L86-L89)

**Comment by Loyalsoldier** [comment]
不建议这样使用 hosts
