### ISSUE TITLE
无关 json，v2ray 应当吃掉 v2ctl

### ISSUE THREAD

**Issue by rprx** [v2fly/v2ray-core#360]
写这个纯粹心血来潮，说几点理由：

1. v2ray 可以成为一个瑞士军刀，不再单薄，作为一个更规范、更强大的命令行工具，利于长远发展
2. 几乎不会增加运行时开销，对程序运行效率无影响，因为那取决于热点代码
3. release 的体积反而更小，如果需要继续减小体积，可以按 tag 编译出仅含需要功能的二进制（这是一整个机制）

兼容性问题？不存在的。有些人的顾虑可能在第二点，我明确说，不会影响运行时性能，建议多深究原理。

有的程序是有守护进程，但也是通过 ctl 来控制 daemon 的。现在的模式是直接运行 daemon，导致 ctl 没存在感，这其实很异类。

**Comment by rprx** [comment]
补充：最后一句是吐槽，毕竟 v2ray 现在不支持整个配置的热重载，普通用户改配置就是重启 v2ray。

**Comment by rprx** [comment]
关于体积我需要说一下，整体体积肯定是更小的，仅看 v2ray 则会增加一点点（真的只是一点点），绝大多数设备都能轻松装下，装不下的地方自有人操心，UPX 也不是不能用。另外，“功能多”和“运行时用到的功能”是两个概念，想一想瑞士军刀是怎么用的吧。

**Comment by rprx** [comment]
我再说得明白一点，现在的 v2ray 二进制都装不下的也就老旧路由器，已经有人操心了，至少得 UPX。我的意思是，不管 v2ray 是否 merge v2ctl，这个局面并不会被改变，所以别拿这一点来反驳。

**Comment by rprx** [comment]
所以 release 的整体体积更小，而仅 v2ray 的一小点体积增加也不会带来新的问题，这与运行时性能更是无关。

所以还有什么理由不能让 v2ray 更加强大？

**Comment by rprx** [comment]
另外关于 v2ray 的属性，它本身就该是个多能的 ctl 工具，我们的版本迭代等也没把它当 daemon 来对待。

**Comment by rprx** [comment]
https://github.com/v2fly/v2ray-core/pull/335

**Comment by wwqgtxx** [comment]
同意，而且我也希望 #335 能尽快merge
不过个人倾向于对目前已有的v2ctl命令不再修改其使用方法了（针对的是如下评论）
>比如原本关于 tls 的 command cert、tlsping 可以合并为 tls cert、ping

对后续增加的命令倒是可以重新梳理，这样可以尽量保证兼容性，在一键安装脚本或者zip文件中直接软连接到v2ray就避免修改现有第三方脚本了

**Comment by U-v-U** [comment]
1. 用户关心的不是 Release 的大小（至少路由器用户实际关心的是跑在机器上的 executable 文件大小）
2. 我认为 v2ctl 作为 v2ray 的功能补充即可，尽量减少低频代码在核心二进制上出现（比如 `v2ctl lovevictoria` 指令，你说合并还是不合并呢？）
  - 路由器用户不会在路由器上跑 `v2ray uuidgen` 吧
3. 瑞士军刀上并没有 「主体功能」 和 「额外功能」 之分，但是 V2Ray 主体功能是用来连接节点的，其他的 uuidgen 属于 「额外功能」
4. 项目整体的强大与否，不应单纯依靠一个文件大小进行评判

**Comment by rprx** [comment]
@U-v-U 仔细看完我说的话

**Comment by rprx** [comment]
@U-v-U 你的观点有一个误区，就是太在意“路由器”和“体积”了，关于路由器的我不必再重复，而关于体积的

> 项目整体的强大与否，不应单纯依靠一个文件大小进行评判

？？？

**Comment by wwqgtxx** [comment]
@U-v-U 你这里的`尽量减少低频代码在核心二进制上出现`的话并没有什么理论和使用依据，首先在程序执行过程中这些代码并不会影响运行效率，其次这些代码本来就在`v2ray-core`仓库中，也不会导致仓库源码膨胀等事情发生
至于路由器用户会不会在路由器上跑`v2ray uuidgen`这个问题，你要是觉得你自己不需要的话可以在编译时将其裁剪掉，又不是说作为一个必选模块就不能去掉了

**Comment by wwqgtxx** [comment]
>Up： 我认为要真正缩小二进制大小，就应该拆包，这样的运行时可插拔比编译时可插拔更加便携
这个评论对golang程序简直就是个灾难，因为对于golang程序，由于静态编译的影响，意味着所有拆分出来的包都会反复携带大量的依赖（golang运行时、其他core内部必须依赖的代码），并做不到像大型c/c++程序使用动态链接库（.dll/.so）那样复用来减小可执行文件的效果

**Comment by qjebbs** [comment]
在意路由上单个v2ray体积的，可能10个里面只有1个，但即使 #335 合并进来:

- 这1个人，他仍然可以用裁剪的方式得到他想要的小体积，其他包他也得裁剪，不是么
- 另外9个人，即使要用v2ctl，也不用再占一份体积

之前因为json问题强制需要v2ctl，那是脱离基本面了，为了1个人的好处，另外9个人都得浪费大量空间，不环保😄

现在这问题算是缓解，但如果要用v2ctl的人也能省空间，不是更好么？关键是，至少没啥坏处

**Comment by qjebbs** [comment]
> > Up： 我认为要真正缩小二进制大小，就应该拆包，这样的运行时可插拔比编译时可插拔更加便携
> 
> 这个评论对golang程序简直就是个灾难，因为对于golang程序，由于静态编译的影响，意味着所有拆分出来的包都会反复携带大量的依赖（golang运行时、其他core内部必须依赖的代码），并做不到像大型c/c++程序使用动态链接库（.dll/.so）那样复用来减小可执行文件的效果，所以就算是golang官方都倾向于把所有命令都放在一个可执行文件中(比如`go get`、`go mod`等等)

对，golang 不支持动态库，就是鼓励单文件发布 ，被社区逼得没办法，搞个plugin包，还不实用。

**Comment by rprx** [comment]
此 issue 即将关闭，昨晚内部讨论已决定合并，并去掉一些无用的功能，以增强整体生命力。

（@U-v-U 这位一开始是误解了，以为核心目的是减小体积。无需继续评论）
