### ISSUE TITLE
dns hosts中引用较大geosite项导致dns空解析

### ISSUE THREAD

**Issue by zenyanbo** [v2fly/v2ray-core#361]
dns hosts中引用较大geosite项导致dns空解析。很好验证，当开放dns时，自带的geosie还不够明显。最好调用[加强版geosite](https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202010250054/geosite.dat) bug会很明显
dns配置：
  "dns": {
    "hosts": {
      "geosite:category-ads-all": "127.0.0.1",
      "geosite:qihoo360": "127.0.0.1"
    },
    "servers": [
      "https+local://223.5.5.5/dns-query",
      "https+local://223.6.6.6/dns-query",
      {
        "address": "1.1.1.1",
        "domains": [
          "geosite:tld-!cn",
          "geosite:geolocation-!cn"
        ],
        "port": 53
      },
      "1.0.0.1"
    ]
  },

解决办法：把广告过滤规则放到路由中

**Comment by kslr** [comment]
听不懂，你的日志呢
