### ISSUE TITLE
加载jsonem的情况下,如何精简v2ray体积.

### ISSUE THREAD

**Issue by garypang13** [v2fly/v2ray-core#364]
加载jsonem的情况下,在all.go中做的所有包裁剪就全部不起作用了.v2ray去掉jsonem的话又得手动转换json配置文件.

在需要解析json配置文件的情况下,该怎么精简v2ray的体积. k2p容量不够,我只想保留自己需要的模块.

谢谢.

**Comment by forever8938** [comment]
使用jsonem就不能精简。如果只需要透明代理和ss，建议用clash，压缩后才2MB。

**Comment by garypang13** [comment]
不使用jsonem那就得加上v2ctl, 要是装的下v2ctl,那还精简v2ray干嘛, 真是让人头疼.

**Comment by felix-fly** [comment]
@garypang13 v2ray用upx后不到4mb，完全放得下k2p啊，我一直就这么用的 https://github.com/felix-fly/v2ray-openwrt

**Comment by rprx** [comment]
楼上正解，UPX

v5 版本应该会有 tag 编译，不用改代码了

**Comment by garypang13** [comment]
> @garypang13 v2ray用upx后不到4mb，完全放得下k2p啊，我一直就这么用的 https://github.com/felix-fly/v2ray-openwrt

是放得下,但是k2p就剩不下多少空间了,在不引入jsonem的情况下,v2ray可以压缩到只有2M多一点,可惜无法读取json配置文件导致无法启动.

**Comment by felix-fly** [comment]
@garypang13 如果你的v2是用tls+ws的话，可以试试trojan，这个体积小一些
