### ISSUE TITLE
v2ray 测速完毕会继续跑流量，可能是软件本身的 BUG

### ISSUE THREAD

**Issue by RPRX** [v2fly/v2ray-core#374]
Speedtest 测速完毕后，即使关了浏览器，v2ray 仍在上传流量，很早就存在的问题。

**Comment by badO1a5A90** [comment]
是用www.speedtest.net网站测试吗,一般会后续上传多久?没能重现,可能和一些配置有关?我用的VLESS+TCP+XTLS,想知道重现的方式然后抓包看看...

**Comment by rprx** [comment]
> 是用www.speedtest.net网站测试吗,一般会后续上传多久?没能重现,可能和一些配置有关?我用的VLESS+TCP+XTLS,想知道重现的方式然后抓包看看...

Y

Chrome SwitchyOmega Socks5

**Comment by badO1a5A90** [comment]
> > 是用www.speedtest.net网站测试吗,一般会后续上传多久?没能重现,可能和一些配置有关?我用的VLESS+TCP+XTLS,想知道重现的方式然后抓包看看...
> 
> Y
> 
> Chrome SwitchyOmega Socks5

我平时使用也是这个模式,并没有重现,你也不用mux吧.

**Comment by MeguminKato** [comment]
4.32.1 xtls 没有发现这个问题

**Comment by z826540272** [comment]
确实有这个问题,而且这个问题和服务端有关
我两家机场,一家有这个问题,一家没有,但是没有的那家mux连接到无法访问的ip会导致挂起
