### ISSUE TITLE
v2ray 需要支持更多 TLS/XTLS 细节配置

### ISSUE THREAD

**Issue by rprx** [v2fly/v2ray-core#375]
重要的

0. Protocols（？）
1. Ciphers
2. Prefer_server_ciphers
3. Curves
4. OCSP Stapling
5. CertificateObject / password of key or keyFile
6. disable_session_resumption（补充文档）
7. https://github.com/v2fly/v2fly-github-io/issues/39

可选的

1. 服务端收到非 TLS 数据的 fallback `"fail": { "dest":8443, "xver":0 }`
2. 服务端支持自动申请、更新证书
3. TLS 双向认证
4. 客户端可选 uTLS 等指纹伪造
5. 支持 TLSv1.3 自带的 padding（？）

* 服务端 TLS/XTLS 不同的配置也有不同的指纹，与 Caddy 能配置出的效果一致最佳
* 但这不成问题，因为服务端 TLS 的不同配置、前置分流等非常常见（包括 是/否 处理 TLS）
* 举个例子，SNI 预分流的场景下也不会响应非 TLS 数据，`可选 1` 就不是必要的

**Comment by Fhokud** [comment]
对于ESNI的支持？

**Comment by rprx** [comment]
> 
> 
> 对于ESNI的支持？

目前 Go 不支持（且对于 v2ray 这样的软件来说，现在也没必要了

**Comment by zhfish** [comment]
感觉是否可以借2的机会，设计一套插件机制？
其他倒是无感..

**Comment by ClarkeCheng** [comment]
服务端支持自动申请、更新证书这个功能很有必要，因为出了 XTLS 后，443 端口已经给 v2ray 了，以前用 443 端口给 caddy 的时候自动更新证书还好解决，现在不知道该怎么做了

如果让 caddy 自动更新证书后，v2ray 重载证书也好

**Comment by rurirei** [comment]
R.I.P vless & xtls inside v2fly/v2ray-core

just kidding.

**Comment by rprx** [comment]
@rurirei 

我开了 Xray：https://github.com/XTLS

**Comment by rurirei** [comment]
@rprx 

vless remains as MIT right? though did you consider not-MIT vless as well?

**Comment by Alex-coffen** [comment]
> 服务端支持自动申请、更新证书这个功能很有必要，因为出了 XTLS 后，443 端口已经给 v2ray 了，以前用 443 端口给 caddy 的时候自动更新证书还好解决，现在不知道该怎么做了
> 
> 如果让 caddy 自动更新证书后，v2ray 重载证书也好

我是做了个caddy的docker来更新证书和处理回落（容器打开443，宿主机可以用-p端口转发）。V2ray在宿主机启动直接用caddy更新出来的证书。这方案实测可用，都用了好几个月了。

**Comment by rprx** [comment]
@rurirei 

你的语气，很让人讨厌。

**Comment by ClarkeCheng** [comment]
> > 服务端支持自动申请、更新证书这个功能很有必要，因为出了 XTLS 后，443 端口已经给 v2ray 了，以前用 443 端口给 caddy 的时候自动更新证书还好解决，现在不知道该怎么做了
> > 如果让 caddy 自动更新证书后，v2ray 重载证书也好
> 
> 我是做了个caddy的docker来更新证书和处理回落（容器打开443，宿主机可以用-p端口转发）。V2ray在宿主机启动直接用caddy更新出来的证书。这方案实测可用，都用了好几个月了。

你好，我的是 caddy 和 v2ray 全在 docker 容器里，想问问你的这个方案，在 caddy 更新证书后，需不需要重启一下 v2ray 来重新加载证书？我有点顾虑，虽然 caddy 已经把证书文件更新了，但是 v2ray 还是用的旧证书（可能它把证书加载在内存里），等把 v2ray 重启后，v2ray 才会用上新的证书

**Comment by Alex-coffen** [comment]
> 你好，我的是 caddy 和 v2ray 全在 docker 容器里，想问问你的这个方案，在 caddy 更新证书后，需不需要重启一下 v2ray 来重新加载证书？我有点顾虑，虽然 caddy 已经把证书文件更新了，但是 v2ray 还是用的旧证书（可能它把证书加载在内存里），等把 v2ray 重启后，v2ray 才会用上新的证书

我是宿主机，所以自己写了个crontab按一定规则重启v2ray. 需不需要重启, 这要看每次使用证书都是从硬盘上读取呢还是v2ray启动时读取一次到内存来用，下次重启前不再读取。这个要专家解答:) @rprx

**Comment by Alex-coffen** [comment]
对了， 你如果了解caddy的话， 它是有一种dns的获取证书的方式，这种方式不需要开放任何端口的。只有Lets encrypt才需要开放端口。所以v2ray 443不会被冲突的。

**Comment by hibobmaster** [comment]
> R.I.P vless & xtls inside v2fly/v2ray-core
> 
> just kidding.

首先你这个答复和这个issue没关系，请不要阴阳怪气。
闹出了这么一出，大家都不太舒服，如果只是部分了解问题的历程，最好不要随便发言
作者们开发出一个个工具是让大家受益的，当出现一些问题我们更多的应该是抛开主观因素提出解决方案，而不是只说些没有建设性的话语，希望大家都能心平气和下来
最后感谢v2ray的作者们的辛苦付出，让我们得以跨过网络长城

**Comment by jdnt** [comment]
> 服务端支持自动申请、更新证书这个功能很有必要，因为出了 XTLS 后，443 端口已经给 v2ray 了，以前用 443 端口给 caddy 的时候自动更新证书还好解决，现在不知道该怎么做了
> 
> 如果让 caddy 自动更新证书后，v2ray 重载证书也好

我发现用acme可以用80端口更新。我把回落到nginx的80改成其他的释放出来给acme，域名配置里加入重启v2ray，一切都完美了（vps只运行v2ray）。

**Comment by 905250363** [comment]
> @rurirei
> 
> 我开了 XXXXXXXXX

您这种行为，也是比较让人讨厌的吧

**Comment by 905250363** [comment]
> @rurirei
> 
> 我开了 XXXXXXXX

您的行为，是不是也有点让人不舒服 ？

**Comment by 905250363** [comment]
@rprx
> 
> 你的语气，很让人讨厌。

您的行为，是不是也不太舒服呢？

**Comment by rprx** [comment]
@905250363 

恰好我刚发了 https://github.com/XTLS/Go/issues/9#issuecomment-731588021

**Comment by rurirei** [comment]
author owns his rights to declare any license of his project, as there is no any problem first.

i just throw a question of license of `vless`, code great by @rprx

**Comment by vongoethe** [comment]
> > > 服务端支持自动申请、更新证书这个功能很有必要，因为出了 XTLS 后，443 端口已经给 v2ray 了，以前用 443 端口给 caddy 的时候自动更新证书还好解决，现在不知道该怎么做了
> > > 如果让 caddy 自动更新证书后，v2ray 重载证书也好
> > 
> > 
> > 我是做了个caddy的docker来更新证书和处理回落（容器打开443，宿主机可以用-p端口转发）。V2ray在宿主机启动直接用caddy更新出来的证书。这方案实测可用，都用了好几个月了。
> 
> 你好，我的是 caddy 和 v2ray 全在 docker 容器里，想问问你的这个方案，在 caddy 更新证书后，需不需要重启一下 v2ray 来重新加载证书？我有点顾虑，虽然 caddy 已经把证书文件更新了，但是 v2ray 还是用的旧证书（可能它把证书加载在内存里），等把 v2ray 重启后，v2ray 才会用上新的证书

no need to restart v2ray if you do soft-link the certs.

**Comment by 1265578519** [comment]
刚刚看到4.33.0的XTLS已经删除了
