### ISSUE TITLE
v2ray 的 UDP 行为需修复

### ISSUE THREAD

**Issue by rprx** [v2fly/v2ray-core#376]
Socks5 入站和 Freedom 出站返回 UDP 包时都扔掉了真实的源地址，需要改。

其它出入站和中间传输行为也需要同步修复。

我发现 v2ray 中一个 UDP 包基于 2048 的 buffer，简单给它加点料应该就能修复了。

修复后 v2ray 的 Shadowsocks 和 Trojan 可以实现 FullCone。

**Comment by rprx** [comment]
除此之外，出入站绑定 UDP 端口的行为、相关路由的行为可能也需要改。

**Comment by rprx** [comment]
出入站绑定 UDP 端口的行为、相关路由的行为可能也需要改。

**Comment by rprx** [comment]
需要指出，重点在于修复 v2ray 四不像的 UDP 行为 —— 现在包是能收到，但来源认错了，就会导致一些应用出奇怪的问题。

**Comment by ClarkeCheng** [comment]
请问VLESS和Vmess在websocket下有望支持Fullcone吗？我记得Shadowsocks是公网下直接传UDP的，个人不太看好裸传UDP的方式

**Comment by rprx** [comment]
@ClarkeCheng 

目前 VLESS 测试版、VMess 不支持 FullCone，Trojan、SS 支持 FullCone，但 v2ray 的不支持，需修复

VLESS 正式版默认是 UDP 聚合隧道，有最低延迟，且可以自定义 NAT 行为，可以实现 FullCone

https://github.com/v2fly/v2ray-core/issues/112#issuecomment-688271288

**Comment by JimhHan** [comment]
能否考虑修改 Mux 使之能够支持 FullCone ？
这样可以到达 FullCone 的同时避免对 VMess/Mux 用户造成影响。

**Comment by rprx** [comment]
@JimhHan 

似乎无法在不引入 breaking change 的情况下修复 Mux 的 UDP 行为

**Comment by 1265578519** [comment]
Socks5提过，使用udp，，ip地址变成0.0.0.0

**Comment by Greeed-islanl** [comment]
4.33的版本NAT很容易跳UDP block
