### ISSUE TITLE
v2ray 应加入 Fake IP、代理组等实用性功能

### ISSUE THREAD

**Issue by rprx** [v2fly/v2ray-core#377]
### ~加个 map 很难吗~

https://github.com/v2ray/v2ray-core/pull/2237

代理组（高级负载均衡、fallback）功能貌似在计划中

**Comment by rprx** [comment]
这个功能主要是利好各种“类透明代理”，比如 TUN/TAP、路由器、Android

**Comment by lucifer9** [comment]
有些app啥的必须启用 always_real_ip
比如 iOS 上的 BOSS直聘
如果要用fake ip的话一定记得提醒用户遇到连不上的域名试试 always_real_ip
我被坑过超过3天，还学会了debug rust才知道这么做

**Comment by yuhan6665** [comment]
I can try simplify commits from https://github.com/v2ray/v2ray-core/pull/2237 and rebase on master. Though it might take me quite a while to understand all related code.
@rprx let me know if there is any suggestions

**Comment by rprx** [comment]
@yuhan6665 

我觉得可以开始这项工作了

**Comment by rprx** [comment]
@yuhan6665 

用 sync.Map

**Comment by acc557** [comment]
@rprx 

https://github.com/v2ray/v2ray-core/pull/2254
May also be interesting since you mentioned proxy fallback.

**Comment by rprx** [comment]
@acc557 

关于代理组，其他开发者似乎有另外的规划

**Comment by badO1a5A90** [comment]
> [v2ray/v2ray-core#2254](https://github.com/v2ray/v2ray-core/pull/2254)
> May also be interesting since you mentioned proxy fallback.

https://github.com/v2ray/v2ray-core/pull/1924
我觉得这个更好用,动态切换最佳性能的线路.

**Comment by acc557** [comment]
@badO1a5A90 Even better. Have you tried this on the current master branch of the v2fly repo?

**Comment by lucifer9** [comment]
测速来决定出口有个坑就是类似网银这种会判断你来连接的IP是不是一段时间内变化，如果变化了就需要重新登陆。一般会选择设置一个阈值，两个出口速度差超过阈值才切换。然后就会遇到阈值设置多少合适的问题...当然还可以再加条件判断，比如限制去某个IP的链接绑定某个出口，这次会遇到银行有好多IP的问题...再添加条件？那就太复杂了吧。
这个就跟之前fakeip会遇到某些域名必须被加到always_real_ip里面才行一样。这种会影响实际用途，但是确实是很小概率，一旦遇到用户很难首先定位到真正的原因，会花大量的时间来从其他方向排除，甚至可能最终也不会意识到真正的原因在哪里。

**Comment by badO1a5A90** [comment]
> 测速来决定出口有个坑就是类似网银这种会判断你来连接的IP是不是一段时间内变化，如果变化了就需要重新登陆。一般会选择设置一个阈值，两个出口速度差超过阈值才切换。然后就会遇到阈值设置多少合适的问题...当然还可以再加条件判断，比如限制去某个IP的链接绑定某个出口，这次会遇到银行有好多IP的问题...再添加条件？那就太复杂了吧。
> 这个就跟之前fakeip会遇到某些域名必须被加到always_real_ip里面才行一样。这种会影响实际用途，但是确实是很小概率，一旦遇到用户很难首先定位到真正的原因，会花大量的时间来从其他方向排除，甚至可能最终也不会意识到真正的原因在哪里。

确实如此。不光网银，YouTube其实也会有类似问题。
可以通过路由规则根本上解决，也可以加切换速度差的阈值。
更好一点是通过增加加出口权重，避免性能差不多线路频繁切换。(性能高的线路权重高，如果切换到权重低的线路说明此时肯定进入不稳定状态了，稳定后也会自动切回来；也可以适合类似稳定但流量小的备用线路权重低，常用低延迟线路权重高等用法)

**Comment by kslr** [comment]
通过在相同域下保证使用同一个路线

**Comment by badO1a5A90** [comment]
> @badO1a5A90 Even better. Have you tried this on the current master branch of the v2fly repo?

是的,事实上我自己一直在用这个PR.

我有多条线路,常用线路基础延迟低带宽高流量大,但是偶然会丢包不稳定.备用线路流量小带宽低且延迟高一些,但确保稳定.所以我有在用这个RP,(并且我略微修改了一下,就是在它的算分基础上*权重更确保在线路状态确实很差的情况下才进行切换)
部分切换出口IP不能用的网站,则路由规则中强制指定出口.

**Comment by acc557** [comment]
@badO1a5A90 Nice! I will have a try.

Maybe fallback strategy can also be implemented as a special case inside this speedtest strategy. 
Like, when  setting `timeout: 0`,  only trigger the testOutboud when the current outbound fails. That would usually be enough for keep the line working. 

leaf has this failover mode 
https://github.com/eycorsican/leaf/blob/master/README.zh.md#failover

**Comment by acc557** [comment]
> 
> 
> 通过在相同域下保证使用同一个路线

Maybe this should be the default for all kinds of strategies.

**Comment by badO1a5A90** [comment]
> @badO1a5A90 Nice! I will have a try. Do you know which one is the last working version?

https://github.com/v2fly/v2ray-core/commit/09b81b78c3a0c4afbc523fc371ea6b1bdde9d679
这个commit的app/router/config.pb.go和之前的有冲突,是因为我自己不太懂这部分的代码,所以app/router/config.pb.go一直用的是旧的而已,同时也一直用着那个RP,其余的代码都可以同步最新的代码,并没有其他问题.
按这个RP的算法,如果某一台代理服务器down了或者下线了,得分会是0,也是可以知道的.

**Comment by acc557** [comment]
@badO1a5A90 
I tired using app/router/config.pb.go on 1a574c17bdc1a04c14374cc8cc4f866b11ca94d3 with current master of v2fly but it fails with
```
app/router/config.pb.go:13:2: imported and not used: "reflect"
app/router/config.pb.go:14:2: imported and not used: "sync"
app/router/config.pb.go:479:12: undefined: isRoutingRule_TargetTag
app/router/config.pb.go:552:38: undefined: isRoutingRule_TargetTag
app/router/config.pb.go:760:8: undefined: RoutingRule_Tag
app/router/config.pb.go:764:6: BalancingRule redeclared in this block
	previous declaration at app/router/config.pb.go:738:6
app/router/config.pb.go:773:25: (*BalancingRule).Reset redeclared in this block
	previous declaration at app/router/config.pb.go:748:6
app/router/config.pb.go:782:25: (*BalancingRule).String redeclared in this block
	previous declaration at app/router/config.pb.go:749:6
app/router/config.pb.go:786:23: (*BalancingRule).ProtoMessage redeclared in this block
	previous declaration at app/router/config.pb.go:750:6
app/router/config.pb.go:898:13: undefined: isDomain_Attribute_TypedValue
app/router/config.pb.go:786:23: too many errors
```

Have you seen this before?
 Could you share you patch if you have fixed this, thanks!

**Comment by acc557** [comment]
@badO1a5A90
Thanks! I tried v2ray/v2ray-core#1924, and it works nicely on current master of v2fly. 

For anyone who want to use this or PR this into the current v2fly master, the `app/router/config.pb.go` can be solved by running `go generate` again. 

```
git remote add speedtest https://github.com/jonas-burn/v2ray-core.git \
    && git fetch speedtest  \
    && git cherry-pick -X ours 1a574c17bdc1a04c14374cc8cc4f866b11ca94d3 \
    && go mod download \
    && git checkout 1a574c17bdc1a04c14374cc8cc4f866b11ca94d3 .dev/protoc/linux/protoc \
    && PATH=$PATH:$(pwd)/.dev/protoc/linux/  \
    && go generate 
# build release
```

**Comment by acc557** [comment]
The only problem of v2ray/v2ray-core#1924 is that it only test speed periodically.  Even if the current outbound fails,  it will not realize it until the next testing cycle.

I can be improved by integrating with v2ray/v2ray-core#2254, which schedules a speed test right after an amount of failure is observed on the current outbound. 

I'd really appreciate if someone could make an improved version of 1a574c17bdc1a04c14374cc8cc4f866b11ca94d3, as I am not familiar with golang :)

**Comment by beanslel** [comment]
I disagree that https://github.com/v2ray/v2ray-core/pull/2254 on its own is not useful. The use-case of https://github.com/v2ray/v2ray-core/pull/2254 is different from https://github.com/v2ray/v2ray-core/pull/1924. The first is to prevent downtime, the second is to maximize performance. The speedtest feature is nice, but should be optional. Personally I think preventing downtime is more important than maximizing performance. Users should be able to choose which one best fits their use-case.

Let's say you have a high performance server, but the bandwidth is very expensive. So you want to use a medium performance server with cheap bandwidth as the primary server and the high performance server as backup. With the speedtest function that's not possible because the high performance server will always be first.

What about the following approach:

1. The user can set the priority order of the servers in the fallback balancer. 

2. The balancer will always choose the highest order server if it's available. If the higher order server goes down (based on maxAttempts), switch to a lower order server. Then periodically try the higher order server and as soon as it comes back online, switch back to that one. 

3. Speedtest can be enabled as an optional feature. If enabled, a periodic check is made with speedtest that automatically orders the servers from high to low priority. Then the same approach as 2. is used.

My golang skills are not so great too, hopefully someone can help work on this.

**Comment by rurirei** [comment]
the issue is shifting away from its theme..

**Comment by rprx** [comment]
> 
> 
> the issue is shifting away from its theme..

没关系，内容也提到了代理组，这就改标题

**Comment by acc557** [comment]
@beanslel 
Have you tried https://github.com/v2ray/v2ray-core/pull/2254 on the current v2fly repo?
I tired to cherry-pick and get it compiled, but it fails with 
```
app/proxyman/outbound/handler.go:27:25: undefined: policy
app/proxyman/outbound/handler.go:29:32: undefined: "v2ray.com/core/app/stats".ManagerType
app/proxyman/outbound/handler.go:29:52: impossible type assertion:
	"v2ray.com/core/app/stats".Manager does not implement features.Feature (Close method has pointer receiver)
app/proxyman/outbound/handler.go:31:11: undefined: "v2ray.com/core/app/stats".GetOrRegisterCounter
app/proxyman/outbound/handler.go:37:32: undefined: "v2ray.com/core/app/stats".ManagerType
app/proxyman/outbound/handler.go:37:52: impossible type assertion:
	"v2ray.com/core/app/stats".Manager does not implement features.Feature (Close method has pointer receiver)
app/proxyman/outbound/handler.go:39:11: undefined: "v2ray.com/core/app/stats".GetOrRegisterCounter
app/proxyman/outbound/handler.go:66:3: unknown field 'uplinkCounter' in struct literal of type Handler
app/proxyman/outbound/handler.go:67:3: unknown field 'downlinkCounter' in struct literal of type Handler
app/proxyman/outbound/handler.go:67:3: too many errors
```

**Comment by rurirei** [comment]
> @beanslel
> Have you tried [v2ray/v2ray-core#2254](https://github.com/v2ray/v2ray-core/pull/2254) on the current v2fly repo?
> I tired to cherry-pick and get it compiled, but it fails with
> 
> ```
> app/proxyman/outbound/handler.go:27:25: undefined: policy
> app/proxyman/outbound/handler.go:29:32: undefined: "v2ray.com/core/app/stats".ManagerType
> app/proxyman/outbound/handler.go:29:52: impossible type assertion:
> 	"v2ray.com/core/app/stats".Manager does not implement features.Feature (Close method has pointer receiver)
> app/proxyman/outbound/handler.go:31:11: undefined: "v2ray.com/core/app/stats".GetOrRegisterCounter
> app/proxyman/outbound/handler.go:37:32: undefined: "v2ray.com/core/app/stats".ManagerType
> app/proxyman/outbound/handler.go:37:52: impossible type assertion:
> 	"v2ray.com/core/app/stats".Manager does not implement features.Feature (Close method has pointer receiver)
> app/proxyman/outbound/handler.go:39:11: undefined: "v2ray.com/core/app/stats".GetOrRegisterCounter
> app/proxyman/outbound/handler.go:66:3: unknown field 'uplinkCounter' in struct literal of type Handler
> app/proxyman/outbound/handler.go:67:3: unknown field 'downlinkCounter' in struct literal of type Handler
> app/proxyman/outbound/handler.go:67:3: too many errors
> ```

2254 needs update.

**Comment by rurirei** [comment]
> Personally I think preventing downtime is more important than maximizing performance. 

i'll do and only do some work on #2254 .

**Comment by beanslel** [comment]
I was also thinking to try porting [v2ray/v2ray-core#2254](https://github.com/v2ray/v2ray-core/pull/2254) to v2fly and then go from there. The original author seems inactive. Maybe it's better to start over from scratch?

**Comment by rurirei** [comment]
> > Personally I think preventing downtime is more important than maximizing performance.
> 
> i'll do and only do some work on #2254 .

https://github.com/rurirei/v2ray-core/tree/balancer-master preview and test welcome. no configuration as default to:
 - maxFailedAttempts = 10
 - replace `random` to `failover (#2254)`

**Comment by rurirei** [comment]
did one met this? @acc557 
```
// go generate


failed 5 minutes ago in 2m 59s
Search logs
3s
1s
2s
3s
2s
2m 48s
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/pires/go-proxyproto v0.3.1
go: downloading golang.org/x/sys v0.0.0-20201107080550-4d91cf3a1aaf
go: downloading github.com/golang/mock v1.4.4
go: downloading golang.org/x/tools v0.0.0-20191216052735-49a3e744a425
google.golang.org/protobuf/types/descriptorpb
google.golang.org/protobuf/types/pluginpb
google.golang.org/protobuf/reflect/protodesc
google.golang.org/protobuf/compiler/protogen
google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo
google.golang.org/protobuf/cmd/protoc-gen-go
go: downloading google.golang.org/grpc v1.33.2
go: finding module for package google.golang.org/grpc/cmd/protoc-gen-go-grpc
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.0.1
go: found google.golang.org/grpc/cmd/protoc-gen-go-grpc in google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.0.1
google.golang.org/grpc/cmd/protoc-gen-go-grpc
go: downloading github.com/gogo/protobuf v1.1.1
github.com/gogo/protobuf/protoc-gen-gogo/generator/internal/remap
github.com/gogo/protobuf/proto
github.com/gogo/protobuf/protoc-gen-gogo/descriptor
github.com/gogo/protobuf/protoc-gen-gogo/plugin
github.com/gogo/protobuf/gogoproto
github.com/gogo/protobuf/vanity
github.com/gogo/protobuf/protoc-gen-gogo/generator
github.com/gogo/protobuf/plugin/testgen
github.com/gogo/protobuf/plugin/defaultcheck
github.com/gogo/protobuf/plugin/embedcheck
github.com/gogo/protobuf/plugin/enumstringer
github.com/gogo/protobuf/plugin/compare
github.com/gogo/protobuf/plugin/description
github.com/gogo/protobuf/plugin/equal
github.com/gogo/protobuf/plugin/face
github.com/gogo/protobuf/plugin/gostring
github.com/gogo/protobuf/plugin/marshalto
github.com/gogo/protobuf/plugin/oneofcheck
github.com/gogo/protobuf/plugin/populate
github.com/gogo/protobuf/plugin/size
github.com/gogo/protobuf/plugin/stringer
github.com/gogo/protobuf/plugin/union
github.com/gogo/protobuf/plugin/unmarshal
github.com/gogo/protobuf/protoc-gen-gogo/grpc
github.com/gogo/protobuf/vanity/command
github.com/gogo/protobuf/protoc-gen-gofast
Make sure that you have `protoc` in your system path or current path. To download it, please visit https://github.com/protocolbuffers/protobuf/releases
exit status 1
proto.go:8: running "go": exit status 1
make: *** [build] Error 1
Makefile:2: recipe for target 'build' failed
```

**Comment by Loyalsoldier** [comment]
@rurirei 

```
Make sure that you have `protoc` in your system path or current path. To download it, please visit https://github.com/protocolbuffers/protobuf/releases
exit status 1
```

Download `protoc` binary executable and place it in your PATH.

**Comment by rurirei** [comment]
> @rurirei
> 
> ```
> Make sure that you have `protoc` in your system path or current path. To download it, please visit https://github.com/protocolbuffers/protobuf/releases
> exit status 1
> ```
> 
> Download `protoc` binary executable and place it in your PATH.

thanks as solved.

**Comment by acc557** [comment]
@rurirei 
Great job! Would you consider PR this to v2fly when you finish the configuration part?

I would also suggest to do a speed test for outbound selection, instead of simply going to the next outbound  in the list.
https://github.com/rurirei/v2ray-core/commit/936f75f0cecbc8c2f61375040be77a4a4d57f037#diff-6567ec16ed6866364dd8b9f0e0dc6a3950be497fc9c3aac1c6d3c782558229e3R85

**Comment by rurirei** [comment]
@acc557 

1. no as it's not code in good
2. i won't do it as it's much compilcated to do

**Comment by beanslel** [comment]
I will take a look and see if I can get get it ready for a PR with basic functionality, but I need to familiarize myself more with the v2ray codebase so it might take a while.

**Comment by acc557** [comment]
It seems that  https://github.com/rurirei/v2ray-core/tree/balancer-master is not as stable as  v2ray/v2ray-core#1924.
It sometimes switch to a bad outbound out of non reason. 
 @rurirei Can you expose maxFailedAttempts and I try a higher number on my side?

**Comment by rurirei** [comment]
> It seems that https://github.com/rurirei/v2ray-core/tree/balancer-master is not as stable as [v2ray/v2ray-core#1924](https://github.com/v2ray/v2ray-core/pull/1924).
> It sometimes switch to a bad outbound out of non reason.
> @rurirei Can you expose maxFailedAttempts and I try a higher number on my side?

expected of errorgen of v2ray, there are much parts to makes errors to makes fallback, as i do not apply log level check #2254 did.

check branch `balancer-dev`.

**Comment by acc557** [comment]
@rurirei  Just get it compiled. 

30 seems to be too large for me, and it stucks at the bad outbound forever. 

I think using a smaller value of maxFailedAttempts to trigger a test before routing the actual user traffic to a new outbound would be a better solution. Currently it uses users' traffic to perform testing, which may break a lot of downstream program.

**Comment by rurirei** [comment]
> @rurirei Just get it compiled.
> 
> 30 seems to be too large for me, and it stucks at the bad outbound forever.
> 
> I think using a smaller value of maxFailedAttempts to trigger a test before routing the actual user traffic to a new outbound would be a better solution. Currently it uses users' traffic to perform testing, which may break a lot of downstream program.

find desired value your way.

buuld your test server your local machine.

**Comment by acc557** [comment]
Maybe exposing an external balancer API, that allows a third-party to pull outbound tags, and configure the balacner, would be the ultimate solution. Users can design whatever rule or strategy themselves using vmessping, traffic stats, or maybe some AI, to pick the best outbound. 

And it should be easier than dynamically changing rules (#286).

**Comment by kslr** [comment]
> Maybe exposing an external balancer API, that allows a third-party to pull outbound tags, and configure the balacner, would be the ultimate solution. Users can design whatever rule or strategy themselves using vmessping, traffic stats, or maybe some AI, to pick the best outbound.
> 
> And it should be easier than dynamically changing rules (#286).

https://github.com/v2fly/v2ray-core/pull/229

**Comment by rurirei** [comment]
configuration released at branch balancer-dev @acc557 
```jsonc
    {
       "tag": "balancer",
       "selector": [
          "a",
          "b",
          "c"
       ],
       "settings": {
          "strategy": "fallback",  // fallback or random. default to random
       },
       "strategySettings": {
          "maxAttempts": 10
       }
    }
```

**Comment by acc557** [comment]
> 
> 
> > Maybe exposing an external balancer API, that allows a third-party to pull outbound tags, and configure the balacner, would be the ultimate solution. Users can design whatever rule or strategy themselves using vmessping, traffic stats, or maybe some AI, to pick the best outbound.
> > And it should be easier than dynamically changing rules (#286).
> 
> #229

 I think #229 is for getting the current users' browsing behavior, and it will be great when being used together with a balancer update API.

But I think some basic strategy like fallback, speedtest ,speedtest-when-fail should be built-in of v2ray.

**Comment by acc557** [comment]
> 
> 
> configuration released at branch balancer-dev @acc557
> 
> ```js
>     {
>        "tag": "balancer",
>        "selector": [
>           "a",
>           "b",
>           "c"
>        ],
>        "settings": {
>           "strategy": "fallback",  // fallback or random. default to random
>        },
>        "strategySettings": {
>           "maxAttempts": 10
>        }
>     }
> ```

It doesn't seem to compile after merging to the latest master.

```
app/router/config.go:155:15: undefined: NewFallbackStrategy
app/router/config.go:161:15: undefined: NewRandomStrategy
```

**Comment by rurirei** [comment]
> > configuration released at branch balancer-dev @acc557
> > ```js
> >     {
> >        "tag": "balancer",
> >        "selector": [
> >           "a",
> >           "b",
> >           "c"
> >        ],
> >        "settings": {
> >           "strategy": "fallback",  // fallback or random. default to random
> >        },
> >        "strategySettings": {
> >           "maxAttempts": 10
> >        }
> >     }
> > ```
> 
> It doesn't seem to compile after merging to the latest master.
> 
> ```
> app/router/config.go:155:15: undefined: NewFallbackStrategy
> app/router/config.go:161:15: undefined: NewRandomStrategy
> ```

fixed, and remember to regenerate .pb.go first.

**Comment by acc557** [comment]
> 
> 
> > > configuration released at branch balancer-dev @acc557
> > > ```js
> > >     {
> > >        "tag": "balancer",
> > >        "selector": [
> > >           "a",
> > >           "b",
> > >           "c"
> > >        ],
> > >        "settings": {
> > >           "strategy": "fallback",  // fallback or random. default to random
> > >        },
> > >        "strategySettings": {
> > >           "maxAttempts": 10
> > >        }
> > >     }
> > > ```
> > 
> > 
> > It doesn't seem to compile after merging to the latest master.
> > ```
> > app/router/config.go:155:15: undefined: NewFallbackStrategy
> > app/router/config.go:161:15: undefined: NewRandomStrategy
> > ```
> 
> fixed, and remember to regenerate .pb.go first.

after regenerating .pb it fails again with

```
app/router/config.go:155:15: undefined: newBalancingManager
app/router/config.go:161:15: undefined: newBalancingManager
```

**Comment by acc557** [comment]
Share my patch of fallback + speed test 
It will only perform speed test after 10 fails.


```
git remote add new1 https://github.com/jonas-burn/v2ray-core.git
git fetch new1
git cherry-pick -X ours  1a574c17bdc1a04c14374cc8cc4f866b11ca94d3
git am -3 fallback.patch
```

```
---
 app/proxyman/outbound/handler.go         |  5 ++
 app/router/balancing_optimal_strategy.go | 60 +++++++++++++++++++++++-
 2 files changed, 63 insertions(+), 2 deletions(-)

diff --git a/app/proxyman/outbound/handler.go b/app/proxyman/outbound/handler.go
index f899e6b8..75146c57 100644
--- a/app/proxyman/outbound/handler.go
+++ b/app/proxyman/outbound/handler.go
@@ -5,6 +5,7 @@ import (
 
 	"v2ray.com/core"
 	"v2ray.com/core/app/proxyman"
+	"v2ray.com/core/app/router"
 	"v2ray.com/core/common"
 	"v2ray.com/core/common/mux"
 	"v2ray.com/core/common/net"
@@ -51,6 +52,7 @@ type Handler struct {
 	streamSettings  *internet.MemoryStreamConfig
 	proxy           proxy.Outbound
 	outboundManager outbound.Manager
+	balancerManager router.BalancerManager
 	mux             *mux.ClientManager
 	uplinkCounter   stats.Counter
 	downlinkCounter stats.Counter
@@ -63,6 +65,7 @@ func NewHandler(ctx context.Context, config *core.OutboundHandlerConfig) (outbou
 	h := &Handler{
 		tag:             config.Tag,
 		outboundManager: v.GetFeature(outbound.ManagerType()).(outbound.Manager),
+		balancerManager: router.NewBalancerManager(),
 		uplinkCounter:   uplinkCounter,
 		downlinkCounter: downlinkCounter,
 	}
@@ -135,12 +138,14 @@ func (h *Handler) Dispatch(ctx context.Context, link *transport.Link) {
 		if err := h.mux.Dispatch(ctx, link); err != nil {
 			newError("failed to process mux outbound traffic").Base(err).WriteToLog(session.ExportIDToError(ctx))
 			common.Interrupt(link.Writer)
+			h.balancerManager.AddFailedAttempts()
 		}
 	} else {
 		if err := h.proxy.Process(ctx, link, h); err != nil {
 			// Ensure outbound ray is properly closed.
 			newError("failed to process outbound traffic").Base(err).WriteToLog(session.ExportIDToError(ctx))
 			common.Interrupt(link.Writer)
+			h.balancerManager.AddFailedAttempts()
 		} else {
 			common.Must(common.Close(link.Writer))
 		}
diff --git a/app/router/balancing_optimal_strategy.go b/app/router/balancing_optimal_strategy.go
index 8906a8eb..a3822119 100644
--- a/app/router/balancing_optimal_strategy.go
+++ b/app/router/balancing_optimal_strategy.go
@@ -11,7 +11,9 @@ import (
 	"net/url"
 	"sort"
 	"sync"
+	"sync/atomic"
 	"time"
+
 	"v2ray.com/core/common/net"
 	"v2ray.com/core/common/session"
 	"v2ray.com/core/transport"
@@ -21,6 +23,54 @@ import (
 	"v2ray.com/core/features/outbound"
 )
 
+type BalancerManager struct {
+	maxAttempts    int64
+	failedAttempts int64
+}
+
+// temp and will removed
+var balancerManager BalancerManager
+
+func newBalancerManager() {
+	const defaultMaxAttempts = 20
+	balancerManager = BalancerManager{
+		failedAttempts: int64(0),
+		maxAttempts:    int64(defaultMaxAttempts),
+	}
+}
+
+func NewBalancerManager() BalancerManager {
+	return balancerManager
+}
+
+// GetFailedAttempts implements outbound.FailedAttemptsRecorder
+func (m *BalancerManager) getFailedAttempts() int64 {
+	return atomic.LoadInt64(&m.failedAttempts)
+}
+func (m *BalancerManager) GetFailedAttempts() int64 {
+	return balancerManager.getFailedAttempts()
+}
+
+// ResetFailedAttempts implements outbound.FailedAttemptsRecorder
+func (m *BalancerManager) resetFailedAttempts() int64 {
+	return atomic.SwapInt64(&m.failedAttempts, int64(0))
+}
+func (m *BalancerManager) ResetFailedAttempts() int64 {
+	return balancerManager.resetFailedAttempts()
+}
+
+// AddFailedAttempts implements outbound.FailedAttemptsRecorder
+func (m *BalancerManager) addFailedAttempts() int64 {
+	return atomic.AddInt64(&m.failedAttempts, int64(1))
+}
+func (m *BalancerManager) AddFailedAttempts() int64 {
+	return balancerManager.addFailedAttempts()
+}
+
+func init() {
+	newBalancerManager()
+}
+
 // OptimalStrategy pick outbound by net speed
 type OptimalStrategy struct {
 	timeout       time.Duration
@@ -102,6 +152,12 @@ type optimalStrategyTestResult struct {
 
 // periodic execute function
 func (s *OptimalStrategy) run() error {
+
+	if balancerManager.GetFailedAttempts() < balancerManager.maxAttempts {
+		newError(fmt.Sprintf("skip a test for not enough fails %d", balancerManager.GetFailedAttempts())).AtInfo().WriteToLog()
+		return nil
+	}
+
 	tags := s.tags
 	count := s.count
 
@@ -122,8 +178,8 @@ func (s *OptimalStrategy) run() error {
 	})
 
 	s.tag = results[0].tag
-	newError(fmt.Sprintf("Balance OptimalStrategy now pick detour [%s](score: %.2f) from %s", results[0].tag, results[0].score, tags)).AtInfo().WriteToLog()
-
+	newError(fmt.Sprintf("Balance OptimalStrategy now pick detour [%s](score: %.2f) from %s", results[0].tag, results[0].score, tags)).AtWarning().WriteToLog()
+	balancerManager.ResetFailedAttempts()
 	return nil
 }
 
-- 


```
