### ISSUE TITLE
[需求]v2ray DNS 缓存，超时策略可自定义配置

### ISSUE THREAD

**Issue by ifooth** [v2fly/v2ray-core#379]
## 背景
- DNS是一个重要而且复杂的功能，目前v2ray的策略是4秒超时，默认缓存结果，但是有如下2个场景：
- 大家一般都有多个远程服务器，想测试下哪个服务器DNS请求快，因为有缓存，这个就不好测试了。正式使用时，一般前面会加个dnsmasq，缓存可有可无。只有只使用内置dns时，缓存才是有必要的（`总结一句，缓存需求其实是比较多样化的`）
- DNS超时时间，默认4秒，用着是没什么问题，我想设置为2秒，超时就尽快请求下一个，而不是阻塞在那里。目前也不好配置

## 需求
- 超时时间可配置
- 缓存策略可配置

默认策略可以和以前保持一致，只是用户有了更多的选择，貌似只有好处，没有坏处 :)

**Comment by Loyalsoldier** [comment]
DNS 关闭缓存已实现：https://github.com/v2fly/v2ray-core/pull/705
