### ISSUE TITLE
dokodemo-door支持转发到Unix domain socket文件吗？

### ISSUE THREAD

**Issue by fivetime** [v2fly/v2ray-core#383]
dokodemo-door如何支持转发tcp/udp到Unix domain socket文件？

**Comment by kslr** [comment]
no

**Comment by rprx** [comment]
目前不支持。

https://github.com/v2fly/v2ray-core/pull/367#issuecomment-720054681

任意门作为特殊的入站协议，以后也会支持转发到 DS

**Comment by lucifer9** [comment]
实际用途是什么呢？
v2ray往本地写这个实在想不到有什么需求啊

**Comment by maskedeken** [comment]
可以转发，但是要经过路由
