### ISSUE TITLE
V2Ray的TLS库性能可能不如openssl

### ISSUE THREAD

**Issue by kirin10000** [v2fly/v2ray-core#387]
之前知道V2Ray使用的是GO TLS库，后来听说V2Ray要导入Openssl库，现在我并不清楚V2Ray使用的是什么TLS库。
这里对V2Ray和使用openssl 3.0.0-alpha7的nginx的TLS性能进行比较。
V2Ray版本: 4.32.0
nginx版本: 1.19.4
nginx编译选项：
``
./configure --prefix=/etc/nginx --with-openssl=../openssl-3.0.0-alpha7 --with-openssl-opt="enable-ec_nistp_64_gcc_128 shared threads zlib-dynamic sctp" --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --with-stream_realip_module --with-stream_geoip_module=dynamic --with-stream_ssl_preread_module --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-pcre --with-libatomic --with-compat --with-cpp_test_module --with-google_perftools_module --with-file-aio --with-threads --with-poll_module --with-select_module --with-cc-opt="-Wno-error -g0 -O3"
``
V2Ray配置:
```
{
    "log": {
        "loglevel": "none"
    },
    "inbounds": [
        {
            "port": 444,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8000,
                        "xver": 0
                    }
                ]
            }
        },
        {
            "port": 445,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8001,
                        "xver": 0
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "cer",
                            "keyFile": "key"
                        }
                    ]
                }
            }
        }
    ]
}
```
nginx配置：
```
server {
    listen 127.0.0.1:8000 ssl;
    ssl_certificate      cer;
    ssl_certificate_key     key;
    ssl_protocols           TLSv1.3;
    root /dev/shm/nginx;
}
server {
    listen 127.0.0.1:8001;
    root /dev/shm/nginx;
}
```
/dev/shm/nginx下放置着一个大小为400mb的文件file
配置hosts，使测试域名指向127.0.0.1
测试命令
```
wget https://域名:444/file -O /dev/null
wget https://域名:445/file -O /dev/null
```
第一条命令，平均速度 190mb/s
第二条，平均速度 140mb/s
第一条比第二条快了35%
ps:
此测试不严谨，不能确定v2ray和wget的tls连接版本，本来想用curl指定tls握手版本进行测试，无奈有这个bug: https://github.com/v2fly/v2ray-core/issues/386 
欢迎各位进行更严谨的测试或者提出更好的测试方案

**Comment by rprx** [comment]
v2ray 是 Go 的 TLS 库，支持 AES-NI

**Comment by rprx** [comment]
由于都是 AES-NI，差距可能在其它地方上：Nginx 或许有针对 TLS 的特殊优化，或者就的确是 Go 的 TLS 库性能不如 OpenSSL，但这也很正常，不是 v2 能直接解决的问题。引入 OpenSSL 是比较麻烦的，性价也比不高（追求性能则有 XTLS，直接不加密了，性能等于 VLESS 裸奔）

**Comment by kirin10000** [comment]
> 引入 OpenSSL 是比较麻烦的，性价也比不高（追求性能则有 XTLS，直接不加密了，性能等于 VLESS 裸奔）

明白，理解

> Nginx 或许有针对 TLS 的特殊优化，或者就的确是 Go 的 TLS 库性能不如 OpenSSL

个人认为 Go 的 TLS 库性能不如 OpenSSL 的可能性比较大，因为nginx的ssl模块就是从openssl源码编译而来的

**Comment by rprx** [comment]
对了，还有可能是 v2 发送数据的区别，即直接发送数据可能有特殊的性能优化（类似 ReadV 的情况，但印象中没有，待查证
