### ISSUE TITLE
trojan协议缺少类似V2RAY_VLESS_XTLS_SHOW = true的设置

### ISSUE THREAD

**Issue by badO1a5A90** [v2fly/v2ray-core#389]
trojan协议缺少类似V2RAY_VLESS_XTLS_SHOW = true的设置,来控制xtlsConn.SHOW ,用以显示信息从而确认是否XTLS正确开启

**Comment by rprx** [comment]
欢迎 PR

**Comment by badO1a5A90** [comment]
https://github.com/v2fly/v2ray-core/pull/391
