### ISSUE TITLE
Redirecting connections to external ip address using TPROXY --on-ip failed

### ISSUE THREAD

**Issue by Provissy** [v2fly/v2ray-core#399]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
```V4.27.0 on Ubuntu 20.04.1 LTS```
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
```Do transparent proxy```
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
```No incomming connections from TPROXY```
4) What's your expectation?
```Receive incomming connections from TPROXY```
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).
```Qv2ray GUI is being used, here is a screenshot.```
![Screenshot 2020-11-09](https://user-images.githubusercontent.com/9506924/98600881-94aa1700-2321-11eb-863f-12dc3053fc69.png)

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.
```N/A```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```N/A```

8) Other configurations (such as Nginx) and logs.

The TPROXY related configurations are set according to this guide https://toutyrater.github.io/app/tproxy.html 

All the information I found about TPROXY is redirecting connections to localhost, but iptables clearly provided an --on-ip option seems to allow you to choose destination whilst v2ray also allows you to listen on 0.0.0.0 when using tproxy inbound.

In my case I want to separate the router and the gateway - which has better performance processing V2ray connections. But if the --on-ip options is set to something other than 0.0.0.0 or 127.0.0.1, V2ray clearly is not receiving any incoming connections. For example, altering this command in the tutorial metioned above:
```
iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 12345 --tproxy-mark 1 # 给 UDP 打标记 1，转发至 12345 端口
```
to
```
iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 12345 --on-ip 192.168.1.20 --tproxy-mark 1 # 给 UDP 打标记 1，转发至 12345 端口
```

I am not sure whether is TPROXY won't redirect connections to an external ip address or my configuration was wrong, or it is a bug for V2ray. If this is a limitation for TPROXY, is there a better solution?

By the way, V2ray is properly listening.
```
$ ss -natp | grep 60080
LISTEN        0         4096                                         *:60080                                                    *:*                              users:(("v2ray",pid=98789,fd=11))
```

Finally, thank you all for your efforts developing V2ray!

**Comment by lucifer9** [comment]
If you followed the common guide, you may check your routing table.
Most guides use:
```
/sbin/ip rule add fwmark 1 table 100
/sbin/ip route add local 0.0.0.0/0 dev lo table 100
```
Notice the second line says **dev lo**, so you know why only 127.0.0.1 (and 0.0.0.0) gets traffic.

**Comment by Provissy** [comment]
> If you followed the common guide, you may check your routing table.
> Most guides use:
> 
> ```
> /sbin/ip rule add fwmark 1 table 100
> /sbin/ip route add local 0.0.0.0/0 dev lo table 100
> ```
> 
> Notice the second line says **dev lo**, so you know why only 127.0.0.1 (and 0.0.0.0) gets traffic.

Thank you for your advice! 

But I still can't get connection redirected to V2ray another machine.

Here is my plan
```
            TPROXY
[GATEWAY] ----------> [SERVER RUNNING V2RAY]
```

I tried setting `ip route` to 

```
route add local default dev eth0 table 100
```

But nerver work.

The iptables chain looks like this:
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
TPROXY     tcp  --  anywhere             anywhere             mark match 0x2333 TPROXY redirect 192.168.10.10:60080 mark 0x0/0x0
TPROXY     udp  --  anywhere             anywhere             mark match 0x2333 TPROXY redirect 192.168.10.10:60080 mark 0x0/0x0
```

Please tell me which part is wrong... Thank you!

**Comment by Provissy** [comment]
It seems that redirecting TPROXY to an external ip is not possible.

Closing issue.
