### ISSUE TITLE
v4.32.1 在任务管理器中网络使用统计有诡异问题

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#400]
看起来不需要有可用代理 也不需要联网 用默认的配置 或者什么配置都不用 启动即可
然后他的网络使用可能是已经接受了几百m 发送0.
或者收发是随机大小. 
或者都是0. 都是随机出现的.

![a3](https://user-images.githubusercontent.com/6483602/98669253-1a62ac80-238c-11eb-9471-222752cf5025.gif)

**Comment by kslr** [comment]
把你的网线拔掉再试试

**Comment by k79e** [comment]
测试开的程序复制到其他文件夹了 是没用配置文件启动的. 他自然不会联网的

**Comment by kslr** [comment]
那和 core 有什么关系

**Comment by k79e** [comment]
果然有点道理 难不成管理器出bug了....
