### ISSUE TITLE
建议给Dokodemo-door增加一个允许连接的IP地址

### ISSUE THREAD

**Issue by fivetime** [v2fly/v2ray-core#404]
建议给Dokodemo-door增加一个允许连接的IP地址
我这边的需求用到了Dokodemo-door做流量转发
```
{
    "allow": "1.1.1.1",  #例如只允许1.1.1.1连接
    "address": "8.8.8.8",
    "port": 8080,
    "network": "tcp",
    "timeout": 0,
    "userLevel": 0
}
```

**Comment by Losalado** [comment]
也许你可以通过路由将其转至blackhole

**Comment by fivetime** [comment]
通过路由将其转至blackhole是可以实现，但是那样配置复杂了吧

**Comment by xqzr** [comment]
`{
	"inbounds": [
        {
            "tag": "dd",
            "protocol": "dokodemo-door",
            "settings": {
            "address": "8.8.8.8",
            "port": 53,
            "network": "tcp",
            "timeout": 0,
            "followRedirect": false,
            "userLevel": 0
            }
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "ip": [
                    "1.1.1.1"
                ],
                "inboundTag": [
                    "dd"
                ],
                "outboundTag": "fd"
            }
        ]
    },
    "outbounds": [
        {
            "protocol": "blackhole"
        },
        {
            "tag": "fd",
            "protocol": "freedom"
        }
    ]
}`

**Comment by rurirei** [comment]
> It is recommended to add an IP address that allows connection to Dokodemo-door

agreed.

**Comment by kslr** [comment]
对于和外部的网络通讯控制使用防火墙是不是更合适
