### ISSUE TITLE
vless+tcp与CDN

### ISSUE THREAD

**Issue by dalton-chiou** [v2fly/v2ray-core#410]
我的v2ray开两个端口，一个是vmess, ws+tls，8443端口, 需要走CDN；一个是新的vless, tcp+xtls ，443端口。问题是，服务器的域名如果走cloudflare代理，vless这个就连不上了。我以为cloudflare不接受tcp，会没影响，看来不是这样。
请教有什么解决办法，能让两种方式在同一个域名上经过cloudflare而共存？

**Comment by xianren78** [comment]
服务器的域名如果走cloudflare代理，vless设置的时候要设置服务器为你的服务器IP，另外设置serverName为你的域名。
PS：这种问题一般要发在discussion里面，而不是在这儿发issue

**Comment by dalton-chiou** [comment]
> 服务器的域名如果走cloudflare代理，vless设置的时候要设置服务器为你的服务器IP，另外设置serverName为你的域名。
> PS：这种问题一般要发在discussion里面，而不是在这儿发issue

谢谢。关闭这个话题。
