### ISSUE TITLE
[feature request] DNS Fallback (DNS transport over TCP)

### ISSUE THREAD

**Issue by rurirei** [v2fly/v2ray-core#415]
request: DNS Transport over TCP [rfc5966](https://tools.ietf.org/html/rfc5966)

reference: DNS Fallback [article by eycorsican](https://medium.com/@TachyonDevel/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0)
> DNS Fallback
 Next, let’s talk about a technology called DNS fallback (this name may not be right). When the proxy server does not support UDP, a simple global TCP/UDP traffic proxy will have a problem, because UDP is needed to resolve DNS.  , The server cannot handle DNS if it does not support UDP, so it cannot handle all domain name requests. DNS fallback is a technology that can force applications to send DNS requests as TCP traffic.

requirement: remote dns for udp-unsupported server https://github.com/2dust/v2rayNG/issues/709

one implementation: https://github.com/eycorsican/go-tun2socks/tree/master/proxy/dnsfallback

this is also an dns alternative to fakedns #377

**Comment by testermania** [comment]
vmess websocket + CDN（cloudflare）udp被阻止。

我尝试开/关多路复用器和其他电击服务器没有任何变化。

没有CDN, 黄色的udp标志出现

netch ntt.log

Other address is 
Binding test: Fail
Local address: 
Mapped address: 
Nat mapping behavior: Unknown
Nat filtering behavior: Unknown
result: Unknown
