### ISSUE TITLE
VLESS over TCP with XTLS下能否加入按访问的域名回落到不同的端口的功能？

### ISSUE THREAD

**Issue by ClarkeCheng** [v2fly/v2ray-core#419]
## 场景

一台VPS下有 Caddy（原本绑定了80，443端口），部署了2个网站"a.com"和"b.com"，现在把 443 端口让给 v2ray 运行 VLESS over TCP with XTLS 模式，但是回落时，回落给 Caddy 的 80 端口的话，2个网站都不能访问。希望回落的配置里能加入按照访问的域名回落到不同的端口的功能，这样建站和高性能的代理都没有冲突了。
```
"inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "",
            "flow": "xtls-rprx-direct",
            "level": 0
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "caddy:80",
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": ["http/1.1"],
            "certificates": [
              {
                "certificateFile": "/root/a.com.crt",
                "keyFile": "/root/a.com.key"
              },
              {
                "certificateFile": "/root/b.com.crt",
                "keyFile": "/root/b.com.key"
              }
            ]
        }
      }
    }
  ]
```
我知道可以用 nginx 或者 haproxy 来绑定 443 端口来做 sni 分流，但是我采用 VLESS over TCP with XTLS 是为了高性能，如果又加入别的软件势必会造成性能损耗，这样就失去了用 VLESS over TCP with XTLS 的意义。所以还是希望 v2ray 能原生支持这一功能。

**Comment by mdlenoir** [comment]
别问我，我可能比你还不懂，只是碰到同样的问题找到的解决办法，自己还没有尝试，你先试试吧，看上去很美的解决方案了（他还给了其它各种套路）。。。
https://github.com/lxhao61/integrated-examples/tree/master/v2ray(vless%2Btcp%26ws%2Btls)%2Bcaddy2

**Comment by ClarkeCheng** [comment]
@mdlenoir 你确定这个是根据域名分流的吗？

**Comment by zhfish** [comment]
mark，正好开始有这个需求，我也测试一下

**Comment by lxhao61** [comment]
很简单事情，caddy2直接就可以解决这个问题。修改我的模板中caddy2回落部分参数即可，见如下：
            "handle": [{
              "handler": "file_server",
              "root": "/var/www/html" //修改成自己存放的web文件路径
            }],
            "terminal": true
改成如下：
            "match": [{
              "host": ["a.com"] //判断/分流域名a.com
            }],
            "handle": [{
              "handler": "file_server",
              "root": "/var/www/html" //修改成上边域名对应存放的web文件路径
            }],
            "terminal": true
          },
          {
            "match": [{
              "host": ["b.com"] //判断/分流域名b.com
            }],
            "handle": [{
              "handler": "file_server",
              "root": "/var/www/html" //修改成上边域名对应存放的web文件路径
            }],
            "terminal": true

**Comment by 1unns** [comment]
> 很简单事情，caddy2直接就可以解决这个问题。修改我的模板中caddy2回落部分参数即可，见链接：
> https://github.com/lxhao61/integrated-examples/tree/master/caddy2(other%20configuration)

有caddyfile的版本吗,php配置麻烦

**Comment by ClarkeCheng** [comment]
> 很简单事情，caddy2直接就可以解决这个问题。修改我的模板中caddy2回落部分参数即可，见链接：
> https://github.com/lxhao61/integrated-examples/tree/master/caddy2(other%20configuration)

你好，你的方法我已经测试过了。确认有效，谢谢。之前我用 caddyfile 的时候，没指定端口为80，所以没有发现这个方法。现在分享我的设置方法。宿主机的 443 端口给 v2ray，80 端口给 caddy

v2ray 的 config.json
```
{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "", //填写自己的id
            "flow": "xtls-rprx-direct",
            "level": 0,
            "email": "vless"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "caddy:80",
            "xver": 0
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": [
            "http/1.1"
          ],
          "certificates": [ // 所有域名的证书都要放到这里
            {
              "certificateFile": "/root/a.com.crt", // 填写自己的证书路径
              "keyFile": "/root/a.com.key" // 填写自己的证书key路径
            },
            {
              "certificateFile": "/root/b.com.crt",
              "keyFile": "/root/b.com.crt"
            },
            {
              "certificateFile": "/root/c.com.crt",
              "keyFile": "/root/c.com.crt"
            }
          ]
        }
      }
    }
  ]
}
```
caddy.json
```
{
  "apps": {
    "http": {
      "http_port": 80,
      "servers": {
        "srv0": {
          "listen": [
            ":80"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "a.com" // 匹配域名，这里替换成自己的域名
                  ]
                }
              ],
              "handle": [],// 这里写自己想要的 handler
              "terminal": true
            },
            {
              "match": [
                {
                  "host": [
                    "b.com"
                  ]
                }
              ],
              "handle": [],
              "terminal": true
            },
            {
              "match": [
                {
                  "host": [
                    "c.com"
                  ]
                }
              ],
              "handle": [],
              "terminal": true
            }
          ]
        }
      }
    }
  }
}
```
caddyfile
```
{
  http_port 80
}
a.com:80 {
  # 注意，80端口下不要配置tls，自动获取证书这些
}
b.com:80 {

}
c.com:80 {
  
}
```
问题已经解决，此 issue 可以关闭了

**Comment by choicky** [comment]
@ClarkeCheng 请问这种情况下如何让 caddy 自动获取tls证书呢？
