### ISSUE TITLE
[feature request] balancerTag for ProxySettingsObject

### ISSUE THREAD

**Issue by rurirei** [v2fly/v2ray-core#420]
request: balancerTag (balancing in routing) support for ProxySettingsObject (for Outbound to use frontend proxy)

requirement: balancerTag is available only on Routing but not ProxySettings of Outbound

**Comment by kslr** [comment]
What can this bring

**Comment by rurirei** [comment]
balancing, of course..

frontend proxy server could be balancing as well, as it provides same balancing as balancing routing.

**Comment by acc557** [comment]
Maybe the entire ProxySettings should be deprecated and replaced with dokodemo-door + domain socket.

see https://github.com/v2fly/v2ray-core/issues/311

**Comment by kslr** [comment]
See https://www.v2fly.org/config/protocols/loopback.html
