### ISSUE TITLE
v2ray.com/core/proxy/vmess/outbound: failed to find an available destination

### ISSUE THREAD

**Issue by pennkao** [v2fly/v2ray-core#426]
2020/11/16 23:35:28 [Warning] [3942895406] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://x'x'x'x'x): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/11/16 23:35:28 [Warning] [3634160708] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/11/16 23:35:28 [Info] [3942895406] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2020/11/16 23:35:28 [Info] [3634160708] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2020/11/16 23:35:28 [Info] [2271413108] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [github.com:443] with URL [//github.com:443]
2020/11/16 23:35:28 [Info] [2271413108] v2ray.com/core/app/dispatcher: default route for tcp:github.com:443
2020/11/16 23:35:28 [Info] [2271413108] v2ray.com/core/transport/internet/websocket: creating connection to tcp:us1102.tomnode.com:443
2020/11/16 23:35:28 127.0.0.1:53284 accepted //github.com:443 [proxy]

**Comment by kslr** [comment]
> wss://us1102.tomnode.com/cat/34281): 404 Not Found > websocket: bad handshake

**Comment by pennkao** [comment]
同样配置手机可以用，只是最近这几天用不了，配置应该没有问题

**Comment by kslr** [comment]
你的配置是错误的，不可能工作

**Comment by pennkao** [comment]
我是扫码的，而且这个配置一直再用，手机都可以用

**Comment by pennkao** [comment]
刚试了下同样都配置 我用其他软件就可以 了

**Comment by xianren78** [comment]
> 刚试了下同样都配置 我用其他软件就可以 了

截图上来看看你所说的其他软件同样配置可用。

**Comment by pennkao** [comment]
> > 刚试了下同样都配置 我用其他软件就可以 了
> 
> 截图上来看看你所说的其他软件同样配置可用。

都是扫码或者复制 手机上都能用

**Comment by pennkao** [comment]
有可能是v2rayU的问题
