### ISSUE TITLE
feature request: apple silicon supported

### ISSUE THREAD

**Issue by sheljoy** [v2fly/v2ray-core#432]
苹果的m1 arm架构有计划支持么?

**Comment by CalmLong** [comment]
这个要看 Go 语言

**Comment by Loyalsoldier** [comment]
just wait for Golang support.

**Comment by chromer030** [comment]
https://github.com/golang/go/issues/39782

**Comment by 0xKira** [comment]
https://golang.org/dl/#go1.16beta1
有beta版支持了
