### ISSUE TITLE
Why remove XTLS？

### ISSUE THREAD

**Issue by Fhokud** [v2fly/v2ray-core#442]

**Comment by rprx** [comment]
原因很复杂，关了，不希望这里也变成吵架的地方。

**Comment by asiaon123** [comment]
> 原因很复杂，关了，不希望这里也变成吵架的地方。

方便说下原因么，是本身问题还是其他非技术问题？asiaon123@gmail.com

**Comment by fivetime** [comment]
残念ですね。

**Comment by 1265578519** [comment]
其实我一直没搞懂这个东西有什么用。。。还没体验到就没了

**Comment by jamesszg** [comment]
确实残念（

**Comment by Fhokud** [comment]
![Uploading xray20201202 (1).png…]()

**Comment by Fhokud** [comment]
![xray20201202](https://user-images.githubusercontent.com/62986412/101179409-1ec96f00-3685-11eb-9ce1-698dd4279c0e.png)

**Comment by hugetiny** [comment]
理论上少了一层tls加密是可以加速的，希望两方求同存异，相互磨合下了

**Comment by Fhokud** [comment]
![Uploading IMG_20220725_173852.jpg…]()

**Comment by Fhokud** [comment]
![IMG_20220725_173852](https://user-images.githubusercontent.com/62986412/180748083-e8b6dab4-f73a-498c-95b0-10841f14b08b.jpg)

**Comment by Fhokud** [comment]
> 理论上少了一层tls加密是可以加速的，希望两方求同存异，相互磨合下了

https://github.com/XTLS/Go/issues/12

https://github.com/XTLS/Go/issues/16

https://github.com/e1732a364fed/xtls-/blob/main/README.md

处理高性能以外一无是处
