### ISSUE TITLE
how dokodemo-door public dns

### ISSUE THREAD

**Issue by rurirei** [v2fly/v2ray-core#445]
platform: Android + gomobile
requirement: build dokodemo-door inbound to a public dns server
```json
{
      "tag": "dns-inbound",
      "listen": "127.0.0.1",
      "port": 10088,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "port": 53,
        "network": "udp"
      }
}
```
issue:
(1) [rurirei/go-libv2ray@9f1e33e](https://github.com/rurirei/go-libv2ray/commit/9f1e33e) (localDns string) to 127.0.0.1:10088
```
PrepareDomain err: lookup server.address.domain on [::1]:53:
 read udp 127.0.0.1:48822->127.0.0.1:10088:
  read: connection refused
```
(2) dig on termux
```
dig @127.0.0.1 -p 10088 github.com

; <<>> DiG 9.16.7 <<>> @127.0.0.1 -p 10088 github.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by kslr** [comment]
```
{
            "listen": "127.0.0.1",
            "port": 10088,
            "protocol": "dokodemo-door",
            "settings": {
              "address": "8.8.8.8",
              "port": 53,
              "network": "tcp,udp" // not space
            }
        }
```

**Comment by rurirei** [comment]
现在解决。 非常抱歉和感谢。
(it is of param "network" does not split space i inserted. solved for now. much sorry and thanks.)

though i had failed with "udp" only as my first post of the thread, hope i will never meet this.

**Comment by kslr** [comment]
First 

lookup server.address.domain on [::1]:53:

Ipv4 vs ipv6 lol

**Comment by rurirei** [comment]
> First
> 
> > lookup server.address.domain on [::1]:53:
> 
> Ipv4 vs ipv6 lol
> 
> ( Your listen ipv4, dig use ipv6

thanks for advanced reply. that's not about dig, but for a golang library (you can see that commit if interested).
