### ISSUE TITLE
Docker Hub上的latest版本对应的还是上一个版本

### ISSUE THREAD

**Issue by gy6221** [v2fly/v2ray-core#45]
如题，armhf的latest镜像内的实际版本是v4.25.0，但实际上最新的版本是v4.25.1，麻烦更新一下

**Comment by yezige** [comment]
哈哈，抱歉来催更，4.26.0了

因为发现4.25.0的docker，搭配4.26.0的客户端无法正常使用

**Comment by yezige** [comment]
看了看脚本，表示我会了，自己搞去拉

**Comment by kslr** [comment]
最近计划迁移到CI里自动更新，但是一直没有时间来处理

**Comment by yezige** [comment]
> 最近计划迁移到CI里自动更新，但是一直没有时间来处理

搞起来吧，我没准能帮上点忙

**Comment by kslr** [comment]
> > 最近计划迁移到CI里自动更新，但是一直没有时间来处理
> 
> 搞起来吧，我没准能帮上点忙

你可以试试来做这一部分，使用github ations

**Comment by yezige** [comment]
> > > 最近计划迁移到CI里自动更新，但是一直没有时间来处理
> > 
> > 
> > 搞起来吧，我没准能帮上点忙
> 
> 你可以试试来做这一部分，使用github ations

还准备参考下v2ray-core的action写法呢，研究完发现，有现成的轮子

**Comment by RouRouX** [comment]
> > > > 最近计划迁移到CI里自动更新，但是一直没有时间来处理
> > > 
> > > 
> > > 搞起来吧，我没准能帮上点忙
> > 
> > 
> > 你可以试试来做这一部分，使用github ations
> 
> 还准备参考下v2ray-core的action写法呢，研究完发现，有现成的轮子
> https://docs.github.com/en/actions/language-and-framework-guides/publishing-docker-images

可以看一下这个轮子，直接就构建多平台镜像，感觉可以全自动基本不用管了
https://github.com/marketplace/actions/docker-buildx#build-and-push-to-dockerhub

**Comment by yezige** [comment]
@kslr
