### ISSUE TITLE
Limit number of connected users 

### ISSUE THREAD

**Issue by psk007** [v2fly/v2ray-core#457]
Hi, 
Thanks for your great program . 
I have Socks 5 proxy server with required Auth in my in bound configurations that mapped to multiple out bound conf . 
My user counts is about 100 person but in my traffic statistics i have data usage for 500 member . so in found that my users share their connection username and password ans used the proxy in shared method . 
so i want limit them max 2 concurrent connections at time but i don't how to do it . 
Is it possible ?

**Comment by NutterChen** [comment]
https://doxtex.com/cart.php?a=add&pid=5

**Comment by psk007** [comment]
thanks for your response but i want to use this in aside of my AAA server and my server currently is based on python language .
