### ISSUE TITLE
多核服务端单核心负载问题，一核有难N核围观

### ISSUE THREAD

**Issue by ZhiShengYuan** [v2fly/v2ray-core#466]
我在***Linux 5.8.0-29-generic #31~20.04.1-Ubuntu SMP Fri Nov 6 16:10:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux***上使用 
 ***v2ray(V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64))*** 作为服务端时，当客户端负载较大的时候，通过HTOP观察到服务端出现单核心负载极高，其他核心几乎无负载的问题，HTOP输出如下

>   1  [&nbsp;4.0%]   4  [&nbsp;4.7%]
>   2  [&nbsp;4.1%]   5  [&nbsp;4.7%]
>   3  [&nbsp;7.3%]   6  [&nbsp;96.6%]
>   Mem[&nbsp;1.34G/7.59G]   Tasks: 123, 320 thr; 1 running
>   Swp[                                          0K/2.00G]   Load average: 0.11 0.07 0.09
>                                                             Uptime: 1 day, 05:04:22
>
>     PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
>
>   82266 root       20   0 4869M 86936 14104 S 105.  1.1  4:12.27 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   82270 root       20   0 4869M 86936 14104 S 28.8  1.1  0:26.89 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   82272 root       20   0 4869M 86936 14104 S 13.4  1.1  0:27.04 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   82277 root       20   0 4869M 86936 14104 S 13.4  1.1  0:28.91 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   82276 root       20   0 4869M 86936 14104 S 12.0  1.1  0:28.81 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   85945 root       20   0 4869M 86936 14104 S 12.0  1.1  0:05.49 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   85944 root       20   0 4869M 86936 14104 S 12.0  1.1  0:06.68 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   82271 root       20   0 4869M 86936 14104 S 11.4  1.1  0:31.52 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
>   82267 root       20   0 4869M 86936 14104 S  4.0  1.1  0:31.78 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

我服务端入站配置如下：

> {
>       "listen": "0.0.0.0",
>       "port": port,
>       "protocol": "socks",
>       "settings": {
>         "auth": "noauth",
>         "udp": true
>       },
>       "sniffing": {
>         "enabled": true,
>         "destOverride": [
>           "http",
>           "tls"
>         ]
>       }
>     }

似乎使用了多线程但是负载几乎集中于一个核心，此现象是否是我配置问题？

**Comment by 1265578519** [comment]
v2祖传毛病了，，不支持多线程，只能单线程跑
和你的配置无关，等未来有开发者优化

**Comment by ZhiShengYuan** [comment]
> v2祖传毛病了，，不支持多线程，只能单线程跑
> 和你的配置无关，等未来有开发者优化
> 不过单线程吞吐量已经很大了啊，你是跑机场吗，单核心吞吐量有200Mbps多，吞吐量根据CPU主频单核心性能而定，正常个人家庭使用很足够了，机场的话，，人多了的话确实不够分的样子

内网代理，实际上哪怕是socks5 noauth(ip limit)的方式也仅有不到800M(I5-8400)

**Comment by kslr** [comment]
个人使用已经足够了，机场可以请人优化

**Comment by 1265578519** [comment]
> > v2祖传毛病了，，不支持多线程，只能单线程跑
> > 和你的配置无关，等未来有开发者优化
> > 不过单线程吞吐量已经很大了啊，你是跑机场吗，单核心吞吐量有200Mbps多，吞吐量根据CPU主频单核心性能而定，正常个人家庭使用很足够了，机场的话，，人多了的话确实不够分的样子
> 
> 内网代理，实际上哪怕是socks5 noauth(ip limit)的方式也仅有不到800M(I5-8400)

I5-8400 内网测试有800M很猛了，公网上高延迟环境基本200M左右。

**Comment by ZhiShengYuan** [comment]
> > > v2祖传毛病了，，不支持多线程，只能单线程跑
> > > 和你的配置无关，等未来有开发者优化
> > > 不过单线程吞吐量已经很大了啊，你是跑机场吗，单核心吞吐量有200Mbps多，吞吐量根据CPU主频单核心性能而定，正常个人家庭使用很足够了，机场的话，，人多了的话确实不够分的样子
> > 
> > 
> > 内网代理，实际上哪怕是socks5 noauth(ip limit)的方式也仅有不到800M(I5-8400)
> 
> I5-8400 内网测试有800M很猛了，公网上高延迟环境基本200M左右。

主要是不走proxy的话限速10M......
似乎gost也是这样
排查以后似乎是网卡亲和性问题，主要负载并非V2RAY而是网卡
