### ISSUE TITLE
安卓arm平台使用v2ray脚本时耗电异常

### ISSUE THREAD

**Issue by fei3988** [v2fly/v2ray-core#471]
安卓arm平台v2ray脚本后台唤醒严重，耗电量大测试多个版本的脚本和v2ray核心都存在这个问题，手机锁屏后，程序依然后台唤醒，抓包发现程序不停的在传输数据，后台程序并没有大流量下载之类的，猜测是不是程序没有休眠策略，反观ssr的ss-redir使用过程中并不像v2ray耗电

**Comment by kslr** [comment]
什么是v2ray脚本

**Comment by fei3988** [comment]
类似于sussr的东西，就是一些.sh文件用来免流的，包含防跳，nat策略https://www.lanzous.com/b008i70mb

**Comment by fei3988** [comment]
v2ray核心一直在后台唤醒，待机耗电异常

**Comment by fei3988** [comment]
![Uploading Screenshot_2020-12-08-09-37-27-420_com.miui.securitycenter.png…]()

**Comment by fei3988** [comment]
![Screenshot_2020-12-08-09-37-27-420_com miui securitycenter](https://user-images.githubusercontent.com/65103566/101476263-641bc400-3945-11eb-8fd5-d5a877f6b797.png)

**Comment by kslr** [comment]
你需要寻找脚本的作者

**Comment by kslr** [comment]
我不清楚你这个原因，但我们正在改善tcp的连接时间，你有兴趣也可以参与
