### ISSUE TITLE
TODO: 移除日志中的 v2ray.com/core 部分

### ISSUE THREAD

**Issue by CalmLong** [v2fly/v2ray-core#474]
https://github.com/v2fly/v2ray-core/projects/1#card-50295188

以 `/` 为索引，始终移除第二个 `/` 前的内容怎么样？反射中的 `PkgPath` 返回的始终是包的路径
![image](https://user-images.githubusercontent.com/37164399/100708758-d8a3af80-33e7-11eb-84f2-7f5ce3ba8422.png)

**Comment by kslr** [comment]
前面的长度是固定的，移除有很多办法
