### ISSUE TITLE
是否可以统一配置中 routing和 dns 关于域名的键名

### ISSUE THREAD

**Issue by ToutyRater** [v2fly/v2ray-core#476]
在 routing 中，域名的键为 domain，在 dns 却是 domains，感觉很分裂

**Comment by kslr** [comment]
可以把路由里的也改成复数，但需要保持两个名称兼容

**Comment by ToutyRater** [comment]
是的，我也认为这是比较好的方式

**Comment by Loyalsoldier** [comment]
Fixed by https://github.com/v2fly/v2ray-core/pull/502
