### ISSUE TITLE
Caddy TLS+Websocket，迁移配置文件并使用此脚本移除原4.25版安装4.60之后客户端不停报错502 Bad Gateway > websocket: bad handshake

### ISSUE THREAD

**Issue by zsbstephen** [v2fly/v2ray-core#49]
RT，服务器端原来是使用官方的脚本安装的，之前从3.X一直覆盖升级到4.25均正常使用。看到v2fly更新了脚本就按网页提示迁移config.json配置文件到/usr/local/etc/v2ray/目录，移除了原4.25版本之后并用新脚本安装4.26之后，客户端就不停报错显示：

2020/07/10 11:55:00 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://domian/ray): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

服务器端配置文件：
{
  "log": {
    "loglevel": "info",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [
    {
      "port": 1024,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "7eeb2ff8-0e79-4095-8010-83336e864f28",
            "alterId": 64,
            "level": 1
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/ray"
        }
      }
    }
  ],
  "inboundDetour": [
    {
      "listen": "127.0.0.1",
      "port": 2048,
      "protocol": "shadowsocks",
      "settings": {
        "method": "aes-256-gcm",
        "password": "e7f82vb4n7w8anr12vaw87n",
       "udp": true,
        "network": "tcp,udp"
      },
      "tag": "shadowsocks"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}

**Comment by zsbstephen** [comment]
Update
2台VPS，一样的Debian9 x64，用v2fly脚本卸载原来4.25重新安装4.26之后，都是一模一样的情况。查看/var/log/v2ray/下面的error.log和access.log日志，发现日志居然是空的，然后查看v2ray服务状态

root@:~# service v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled)
   Active: failed (Result: start-limit) since Fri 2020-07-10 22:50:22 HKT; 1min 29s ago
  Process: 25742 ExecStart=/usr/local/bin/v2ray -confdir /usr/local/etc/v2ray/ (code=exited, status=255)
 Main PID: 25742 (code=exited, status=255)

Jul 10 22:50:22 systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Jul 10 22:50:22 systemd[1]: Unit v2ray.service entered failed state.
Jul 10 22:50:22 systemd[1]: v2ray.service holdoff time over, scheduling restart.
Jul 10 22:50:22 systemd[1]: Stopping V2Ray Service...
Jul 10 22:50:22 systemd[1]: Starting V2Ray Service...
Jul 10 22:50:22 systemd[1]: v2ray.service start request repeated too quickly, refusing to start.
Jul 10 22:50:22 systemd[1]: Failed to start V2Ray Service.
Jul 10 22:50:22 systemd[1]: Unit v2ray.service entered failed state.

原来v2ray居然运行没有成功。
然后发现无论是通过service v2ray start，还是systemctl start v2ray来启动v2ray，很快就会闪退。status跟上面一样。

然后尝试用卸载脚本卸载v2ray，并且将v2ray所有相关目录、文件夹删除，并用脚本重新安装，但安装完重新应用之前的config.json配置之后，依然是会秒退。

**Comment by kslr** [comment]
这种自行处理吧

**Comment by zsbstephen** [comment]
Update：
打开 /usr/local/etc/v2ray/路径，发现除了config.json以外，多了这一堆东西：
00_log.json
01_api.json
02_dns.json
03_routing.json
04_policy.json
05_inbounds.json
06_outbounds.json
07_transport.json
08_stats.json
09_reverse.json

删除这10个json文件，重新systemctl daemon-reload，依然闪退。然后直接命令运行：
root@debian:/usr/local/bin# /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/local/bin/geoip.dat: no such file or directory > exit status 255

然后跑journalctl -u v2ray命令，发现：
root@debian:~# journalctl -u v2ray
-- Logs begin at Fri 2020-07-10 17:32:02 HKT, end at Fri 2020-07-10 23:52:42 HKT. --
Jul 10 20:55:49 debian systemd[1]: Starting V2Ray Service...
Jul 10 20:55:49 debian systemd[1]: Started V2Ray Service.
Jul 10 20:55:49 debian v2ray[22989]: V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
Jul 10 20:55:49 debian v2ray[22989]: A unified platform for anti-censorship.
Jul 10 20:55:49 debian v2ray[22989]: 2020/07/10 20:55:49 Using confdir from arg: /usr/local/etc/v2ray/
Jul 10 20:55:50 debian v2ray[22989]: 2020/07/10 20:55:50 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Jul 10 20:55:50 debian v2ray[22989]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Jul 10 20:55:50 debian v2ray[22989]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 55 > v2ray.com/core/transport/internet: failed to list
Jul 10 20:55:50 debian systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Jul 10 20:55:50 debian systemd[1]: Unit v2ray.service entered failed state.
Jul 10 20:55:50 debian systemd[1]: v2ray.service holdoff time over, scheduling restart.
Jul 10 20:55:50 debian systemd[1]: Stopping V2Ray Service...
Jul 10 20:55:50 debian systemd[1]: Starting V2Ray Service...
Jul 10 20:55:50 debian systemd[1]: Started V2Ray Service.
Jul 10 20:55:50 debian v2ray[22999]: V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
Jul 10 20:55:50 debian v2ray[22999]: A unified platform for anti-censorship.
Jul 10 20:55:50 debian v2ray[22999]: 2020/07/10 20:55:50 Using confdir from arg: /usr/local/etc/v2ray/
Jul 10 20:55:50 debian v2ray[22999]: 2020/07/10 20:55:50 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Jul 10 20:55:50 debian v2ray[22999]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Jul 10 20:55:50 debian v2ray[22999]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 55 > v2ray.com/core/transport/internet: failed to list
Jul 10 20:55:50 debian systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Jul 10 20:55:50 debian systemd[1]: Unit v2ray.service entered failed state.
Jul 10 20:55:51 debian systemd[1]: v2ray.service holdoff time over, scheduling restart.
Jul 10 20:55:51 debian systemd[1]: Stopping V2Ray Service...
Jul 10 20:55:51 debian systemd[1]: Starting V2Ray Service...
Jul 10 20:55:51 debian systemd[1]: Started V2Ray Service.
Jul 10 20:55:51 debian v2ray[23010]: V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
Jul 10 20:55:51 debian v2ray[23010]: A unified platform for anti-censorship.
Jul 10 20:55:51 debian v2ray[23010]: 2020/07/10 20:55:51 Using confdir from arg: /usr/local/etc/v2ray/
Jul 10 20:55:51 debian v2ray[23010]: 2020/07/10 20:55:51 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Jul 10 20:55:51 debian v2ray[23010]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Jul 10 20:55:51 debian v2ray[23010]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 55 > v2ray.com/core/transport/internet: failed to list
Jul 10 20:55:51 debian systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
lines 1-34...skipping...
-- Logs begin at Fri 2020-07-10 17:32:02 HKT, end at Fri 2020-07-10 23:52:42 HKT. --
Jul 10 20:55:49 debian systemd[1]: Starting V2Ray Service...
Jul 10 20:55:49 debian systemd[1]: Started V2Ray Service.
Jul 10 20:55:49 debian v2ray[22989]: V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
Jul 10 20:55:49 debian v2ray[22989]: A unified platform for anti-censorship.
Jul 10 20:55:49 debian v2ray[22989]: 2020/07/10 20:55:49 Using confdir from arg: /usr/local/etc/v2ray/
Jul 10 20:55:50 debian v2ray[22989]: 2020/07/10 20:55:50 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Jul 10 20:55:50 debian v2ray[22989]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Jul 10 20:55:50 debian v2ray[22989]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 55 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:55 > listen tcp 127.0.0.1:55: bind: permission denied
Jul 10 20:55:50 debian systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Jul 10 20:55:50 debian systemd[1]: Unit v2ray.service entered failed state.
Jul 10 20:55:50 debian systemd[1]: v2ray.service holdoff time over, scheduling restart.
Jul 10 20:55:50 debian systemd[1]: Stopping V2Ray Service...
Jul 10 20:55:50 debian systemd[1]: Starting V2Ray Service...
Jul 10 20:55:50 debian systemd[1]: Started V2Ray Service.

这就想起来原来开了个shadowsocks在55这个低位端口，于是跑这条命令给权限
setcap cap_net_bind_service=+ep /usr/local/bin/v2ray
发现还是没用……

**Comment by zsbstephen** [comment]
看了介绍，原来新的脚本用了nobody用户来启动，不再是用root来启动，而原先配置文件里面开Shadowsocks的55端口因为属于1024以下的低位端口，linux禁止非root启动的程序占用，所以导致v2ray启动失败。将配置文件里面的55端口改成1024以上的高位端口才解决。

还好shadowsocks并不是直接对外而只是给simple obfs监听，影响不大。issue就先close吧。

**Comment by zsbstephen** [comment]
> 这种自行处理吧

建议介绍页面增加提示，提醒in/out bound等等的端口都大于1024~
