### ISSUE TITLE
V4.33.0 的 arm64-v8a的v2ray無法啓動，v2ctl正常

### ISSUE THREAD

**Issue by soundghost** [v2fly/v2ray-core#491]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V4.33.0 的 arm64-v8a

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Magisk Android client

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

服務端配置文件正常，PC端可以連接。
Android端無法啓動。

4)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

客户端错误日志:

```javascript
SIGILL: illegal instruction
PC=0x64b4c0 m=0 sigcode=1
instruction bytes: 0x0 0x6 0x38 0xd5 0xe0 0x7 0x0 0xf9 0xc0 0x3 0x5f 0xd6 0x0 0x0 0x0 0x0

goroutine 1 [running, locked to thread]:
golang.org/x/sys/cpu.getisar0(0x400021a930)
        golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/cpu/cpu_arm64.s:13 fp=0x40001dfc70 sp=0x40001dfc70 pc=0x64b4c0
golang.org/x/sys/cpu.readARM64Registers()
        golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/cpu/cpu_arm64.go:65 +0x30 fp=0x40001dfcb0 sp=0x40001dfc70 pc=0x64acc0
golang.org/x/sys/cpu.doinit()
        golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/cpu/cpu_linux_arm64.go:38 +0x2c fp=0x40001dfcd0 sp=0x40001dfcb0 pc=0x64afbc
golang.org/x/sys/cpu.archInit()
        golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/cpu/cpu_arm64.go:45 +0x20 fp=0x40001dfce0 sp=0x40001dfcd0 pc=0x64ac70
golang.org/x/sys/cpu.init.0()
        golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/cpu/cpu.go:199 +0x20 fp=0x40001dfcf0 sp=0x40001dfce0 pc=0x64a210
runtime.doInit(0xf15660)
        runtime/proc.go:5646 +0x9c fp=0x40001dfd30 sp=0x40001dfcf0 pc=0x50c9c
runtime.doInit(0xf231a0)
        runtime/proc.go:5641 +0x58 fp=0x40001dfd70 sp=0x40001dfd30 pc=0x50c58
runtime.doInit(0xf15560)
        runtime/proc.go:5641 +0x58 fp=0x40001dfdb0 sp=0x40001dfd70 pc=0x50c58
runtime.doInit(0xf136e0)
        runtime/proc.go:5641 +0x58 fp=0x40001dfdf0 sp=0x40001dfdb0 pc=0x50c58
runtime.doInit(0xf1b860)
        runtime/proc.go:5641 +0x58 fp=0x40001dfe30 sp=0x40001dfdf0 pc=0x50c58
runtime.doInit(0xf16700)
        runtime/proc.go:5641 +0x58 fp=0x40001dfe70 sp=0x40001dfe30 pc=0x50c58
runtime.doInit(0xf21020)
        runtime/proc.go:5641 +0x58 fp=0x40001dfeb0 sp=0x40001dfe70 pc=0x50c58
runtime.doInit(0xf215c0)
        runtime/proc.go:5641 +0x58 fp=0x40001dfef0 sp=0x40001dfeb0 pc=0x50c58
runtime.doInit(0xf23a20)
        runtime/proc.go:5641 +0x58 fp=0x40001dff30 sp=0x40001dfef0 pc=0x50c58
runtime.doInit(0xf1b460)
        runtime/proc.go:5641 +0x58 fp=0x40001dff70 sp=0x40001dff30 pc=0x50c58
runtime.main()
        runtime/proc.go:191 +0x1b8 fp=0x40001dffd0 sp=0x40001dff70 pc=0x43b08
runtime.goexit()
        runtime/asm_arm64.s:1136 +0x4 fp=0x40001dffd0 sp=0x40001dffd0 pc=0x730c4

r0      0x1
r1      0x40001dc3a0
r2      0x40001dfcb0
r3      0x400021a930
r4      0xa4c6e0
r5      0x277f0
r6      0x1000
r7      0x6
r8      0xf9
r9      0x400021a95f
r10     0x1000
r11     0x1
r12     0xa2ca34
r13     0x0
r14     0xf9
r15     0x0
r16     0x0
r17     0x6
r18     0x0
r19     0xd0
r20     0x40001dfb90
r21     0x40001dfca8
r22     0x4000002000
r23     0x0
r24     0x0
r25     0x0
r26     0xf15698
r27     0xfb8816
r28     0x4000000180
r29     0x40001dfc68
lr      0x64acc0
sp      0x40001dfc70
pc      0x64b4c0
fault   0x0
```

**Comment by kslr** [comment]
你在手机终端下直接运行呢

**Comment by soundghost** [comment]
謝謝回復。
root后pc端進入adb shell，執行/bin/v2ray -test -config /data/v2ray/config.json出現一樣的錯誤。

**Comment by soundghost** [comment]
這個錯誤在magisk的v2ray的討論頁也有人反饋。
[issues 80](https://github.com/Magisk-Modules-Repo/v2ray/issues/80)

**Comment by kslr** [comment]
我的意思是指单独下载跑，不要用magisk安装的

**Comment by kslr** [comment]
在 31 上的调查最后认为是 xtls 导致，但目前已经删掉了，所以不太清楚现在的又是什么原因

**Comment by zsxwz** [comment]
4.33.0移除xtls之后，用termux自己编译一份就可以用了。之前的版本自己编译的好像也用不了。或者直接使用4.30.0以前的版本。

**Comment by soundghost** [comment]
不知道這個信息是否有用，我分別下載了v4.32.1 v4.32.0 v4.30.0，拷入手機裏相應的目錄替換掉原始v2ray，發現只有v4.30.0啓動不報錯，其餘幾個版本都出現同樣的問題

**Comment by dyhkwong** [comment]
那么跟 x/sys 有关了 https://github.com/golang/sys/commit/59e60aa80a0c64fa4b088976ee16ad7f04252c25 [cpu/cpu_arm64.go#L47](https://github.com/golang/sys/blob/ed752295db8857b3a7f36c3f57e38509cadff471/cpu/cpu_arm64.go#L47) 
可以通过添加 Android ARM64 的 release 解决 https://github.com/dyhkwong/v2ray-core/commit/4f8ea3f1bdb9544ef539564e073b421f3a33b9fb ，未测试是否会有其它问题（sockopt, domainsocket, dokodemo 等）

**Comment by kslr** [comment]
> 那么跟 x/sys 有关了 [golang/sys@59e60aa](https://github.com/golang/sys/commit/59e60aa80a0c64fa4b088976ee16ad7f04252c25) [cpu/cpu_arm64.go#L47](https://github.com/golang/sys/blob/ed752295db8857b3a7f36c3f57e38509cadff471/cpu/cpu_arm64.go#L47)
> 可以通过添加 Android ARM64 的 release 解决 [dyhkwong@4f8ea3f](https://github.com/dyhkwong/v2ray-core/commit/4f8ea3f1bdb9544ef539564e073b421f3a33b9fb) ，未测试是否会有其它问题（sockopt, domainsocket, dokodemo 等）

你们要不要尝试用 go 1.4 什么的编译下试试呢？

**Comment by dyhkwong** [comment]
> 
> 你们要不要尝试用 go 1.4 什么的编译下试试呢？

是指 go 1.14 吗？虽然并不认为这跟 Go 版本有关，但我还是[试了](https://github.com/dyhkwong/v2ray-core/commits/dev-go114)，不工作，go 1.14.9/1.14.13 的 linux arm64 构建可以在 Android 上复现同样的 crash

（既然是 reproducible build，那 Actions 编译和本地编译就没区别了吧？）

**Comment by kslr** [comment]
可以添加Android平台的arm来解决，你有兴趣发一个pr吗
