### ISSUE TITLE
Limit connections per client

### ISSUE THREAD

**Issue by legobyte** [v2fly/v2ray-core#503]
Hi,
Is there any way so we can limit connections per client
I mean the client A only accepts maximum 2 simultaneous connections

Thanks!

**Comment by NutterChen** [comment]
Currently, u can use traffic restrictions

v2ray's protocol almost impossible to limit each client's connection device (in my ability)

**Comment by legobyte** [comment]
> Currently, u can use traffic restrictions
> 
> v2ray's protocol almost impossible to limit each client's connection device (in my ability)

Can you please explain how to do so
Can we do it with config file?

**Comment by NutterChen** [comment]
> > Currently, u can use traffic restrictions
> > v2ray's protocol almost impossible to limit each client's connection device (in my ability)
> 
> Can you please explain how to do so
> Can we do it with config file?

through v2ray's api interface, periodically get the traffic usage of a clients(user), and when it reaches a certain value, remove the clients

write the relevant code urself, of course there are some ready-made solutions

**Comment by famdude** [comment]
No solution has been found?!

**Comment by attacking6** [comment]
i'm looking for a way too, :(

**Comment by se8820726** [comment]
> 

please introduce us those ready made solutions

**Comment by se8820726** [comment]
> > > Currently, u can use traffic restrictions
> > > v2ray's protocol almost impossible to limit each client's connection device (in my ability)
> > 
> > 
> > Can you please explain how to do so
> > Can we do it with config file?
> 
> through v2ray's api interface, periodically get the traffic usage of a clients(user), and when it reaches a certain value, remove the clients
> 
> write the relevant code urself, of course there are some ready-made solutions


please introduce us those ready made solutions

**Comment by mahansalimi** [comment]
> i'm looking for a way too, :(

you can check this page

https://github.com/vaxilu/x-ui/pull/179
