### ISSUE TITLE
FriendlyElec NanoPi R2S V2ray  节点订阅报错

### ISSUE THREAD

**Issue by Jesn** [v2fly/v2ray-core#514]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.33.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
https://github.com/openwrt/luci i  FriendlyElec NanoPi R2S  ,通过节点订阅 进行订阅

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
节点订阅错误

4) 你期待看到的正确表现是怎样的？
通过订阅链接能正常订阅该链接下的所有节点

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
```
2020-12-14 09:28:54: 正在订阅: 
2020-12-14 09:28:56: /usr/share/passwall/subscribe.lua:347: attempt to index local 'info' (a nil value)
2020-12-14 09:28:56: stack traceback:
	/usr/share/passwall/subscribe.lua:901: in function </usr/share/passwall/subscribe.lua:899>
	/usr/share/passwall/subscribe.lua:347: in function 'processData'
	/usr/share/passwall/subscribe.lua:846: in function 'parse_link'
	/usr/share/passwall/subscribe.lua:886: in function 'callback'
	/usr/lib/lua/luci/model/uci.lua:269: in function 'foreach'
	/usr/share/passwall/subscribe.lua:879: in function </usr/share/passwall/subscribe.lua:876>
	[C]: in function 'xpcall'
	/usr/share/passwall/subscribe.lua:899: in main chunk
	[C]: ?
2020-12-14 09:28:56: 发生错误, 正在恢复服务
2020-12-14 09:28:56: 订阅完毕...
```

**Comment by 2f8ca48d** [comment]
你一个 OpenWrt 的passwall 插件的问题你来 V2Ray 内核 这里发什么 issues？
用不了就用更新插件或者更新固件！
有问题就找固件链接发出来的那个人！
你去 https://github.com/xiaorouji/openwrt-passwall

**Comment by Loyalsoldier** [comment]
Not related to V2Ray.

**Comment by Fhokud** [comment]
#540
