### ISSUE TITLE
安装脚本无法成功安装v2ray

### ISSUE THREAD

**Issue by onlyJinx** [v2fly/v2ray-core#52]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v4.26.0 

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Github
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
Failed to stop v2ray.service: Unit v2ray.service not loaded
4) What's your expectation?
install v2ray
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

旧版本已经使用脚本移除
bash <(curl -L https://install.direct/go.sh) --remove
然后使用新的安装
bash <(curl https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

提示截图报错, 如果使用旧的脚本安装是可以正常安装的, 系统CentOS7 X64, 这是要手动安装v2ray才可以吗

![image](https://user-images.githubusercontent.com/21324835/87369144-59394f00-c5b2-11ea-9c71-c2aa1aff98ff.png)

![image](https://user-images.githubusercontent.com/21324835/87368953-d912e980-c5b1-11ea-80c1-c928c0a77d0d.png)

**Comment by kslr** [comment]
Centos7的生命周期已经要结束了吧

**Comment by onlyJinx** [comment]
> Centos7的生命周期已经要结束了吧

如果是因为新脚本不再支持CentOS7的话那我就懂了，我手动装…

**Comment by dctxmei** [comment]
@onlyJinx 我特意用 CentOS 7 試了一下，是可以安裝上的。

你是否在使用該腳本時，仍通過其它方式運行著 V2Ray 呢？

**Comment by onlyJinx** [comment]
@dctxmei 以前使用過舊版的v2ray脚本, 就是
bash <(curl -L https://install.direct/go.sh)
然後我已經使用指令卸載了
bash <(curl -L https://install.direct/go.sh) --remove
在重新裝就裝不上了
bash <(curl https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
現在下載二進制文件然後手動複製到指定路徑搞定了, 謝謝

**Comment by dctxmei** [comment]
@onlyJinx 經過測試，如果不是通過 `systemctl` 來管理 V2Ray 服務的話，在執行舊腳本的移除指令後，V2Ray 仍會保持原有進程（可執行 `pgrep v2ray` 查看），若在沒有殺死該進程的情況下去執行新腳本，則會因此而導致安裝失敗。
