### ISSUE TITLE
如果 Firefox 开启 http3 支持，如果使用 V2ray, 频繁遇到页面访问结果 400 问题。

### ISSUE THREAD

**Issue by zw963** [v2fly/v2ray-core#541]
之前以为是某个插件，或者是我在用 nightly 版本的 Firefox 的问题，最近切换到 stable, 发现问题依旧。

然后我尝试关闭 http3 之后，用了一段时间，再没出现过这个错误。

所以，我觉得可以肯定是 Firefox http3 support 和 V2ray 一起工作的问题。

详细的描述，请看这个帖子，谢谢。

https://github.com/v2fly/discussion/issues/56

**Comment by devinstever** [comment]
在firefox里打开这个选项相当于强制让所有网站尽量使用http3连接了。如果对应网站仅支持quic但是不支持http3的话，那肯定是400啊。不是v2ray这个软件的问题，和软件无关。
这个跟v2ray没有关系，v2ray只是在这件事中充当了一个按原样转发内容的代理的用途。数据包在出口（也就是服务器）原来是什么样，还是什么样。
现在你知道为什么这么长时间没有人回复你的问题了吗。

**Comment by zw963** [comment]
> 现在你知道为什么这么长时间没有人回复你的问题了吗。

@devinstever 

哦，谢谢， 我基本明白你的解释，不过还有一些疑问：

1. 类似的问题，基本上发生在 Google 自家的网站上，例如： google.com, youtube.com，自家不支持自家开发的 Quic 协议，说不过去吧？

2. 为啥重新刷一下就好了呢？

3.  如果我不用 V2ray, 而是用 shadowsocks + http3, 却没有此问题？


BTW: 我想起来了，应该与 Quic 无关，我记得我曾经试过直接 http 协议，问题依旧, 但是关闭 http3 之后，问题解决。

**Comment by devinstever** [comment]
> > 现在你知道为什么这么长时间没有人回复你的问题了吗。
> 
> @devinstever
> 
> 哦，谢谢， 我基本明白你的解释，不过还有一些疑问：
> 
> 1. 类似的问题，基本上发生在 Google 自家的网站上，例如： google.com, youtube.com，自家不支持自家开发的 Quic 协议，说不过去吧？
> 2. 为啥重新刷一下就好了呢？
> 3. 如果我不用 V2ray, 而是用 shadowsocks + http3, 却没有此问题？
> 
> BTW: 我想起来了，应该与 Quic 无关，我记得我曾经试过直接 http 协议，问题依旧, 但是关闭 http3 之后，问题解决。

1.quic跟http3虽然同样是通过udp443端口传输数据，但是从协议上来讲是两个不同的标准的，也是基于不同的草案开发的，Google自己的服务仅支持quic，不支持http3。也没有消息说Google一定会支持http3。
2.当http3或者quic连接不通畅的时候，浏览器会降级为普通的tcp tls，这就是为什么刷新就好的原因。
3.shadowsocks默认是不转发udp的，udp根本不通，浏览器用的根本不是http3。http3也不会协商成功。

**Comment by zw963** [comment]
完全清楚了，多谢！
