### ISSUE TITLE
微信联系人被封，怎么用以前的账户续约

### ISSUE THREAD

**Issue by BinZheng51** [v2fly/v2ray-core#554]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

This issue will be closed immediately.

**Comment by BinZheng51** [comment]
以前的微信联系人被封，怎么联系你们

**Comment by biubiussr** [comment]
你这个问题不属于v2ray,请不要继续跟进。

Kslr <notifications@github.com> 于 2020年12月28日周一 10:20写道：
