### ISSUE TITLE
服务端不变，客户端在4.30.0之前Quic都是可用的，升级到4.31.0及以后后不可用

### ISSUE THREAD

**Issue by ohiyangss** [v2fly/v2ray-core#559]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务端：
客户端：V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 darwin/amd64)
服务端：V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 通过 http/VMess 代理 google搜索

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
两个现象：
wireshark抓包：发现服务端回复  [Malformed Packet: QUIC]，然后出现retry
[Dissector bug, protocol QUIC: ../epan/dissectors/packet-quic.c:3347: failed assertion "quic_packet"]
客户端日志：
2020/12/30 18:54:11 [Warning] [2895670186] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [NO_ERROR: Handshake did not complete in time] > v2ray.com/core/common/retry: all retry attempts failed
应该握手失败。

4) 你期待看到的正确表现是怎样的？
在4.30.0之前都是可用的。问题出现后，我回退了版本。发现在4.30.0之前都是可用的。
最终确定的commit id a44e1ede 它以后便不能够正常使用了。
希望能够正常使用，完成 握手。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
inbounds
   {
      "port": 33333,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "email": "quic0",
            "id": "19a962de-4d46-4759-94b2-uuuuuuuuu",
            "alterId": 32,
            "level": 0
          }
        ]
      },
      "tag": "in-quic",
      "streamSettings": {
        "network": "quic",
        "security": "tls",
        "quicSettings": {
          "security": "aes-128-gcm",
          "key": "keykeyekykey",
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "server.crt",
              "keyFile": "server.key.unsecure"
            }
          ]
        }
      }
    },
```

客户端配置:

```javascript
    {
    "protocol":"vmess",
    "settings":{
      "vnext":[
        {
          "address":"lalalalllalala",
          "port":33333,
          "users":[
            {
              "id":"19a962de-4d46-4759-94b2-uuuuuuuuuu",
              "alterId":32
            }
          ]
        }
      ]
    },
    "tag":"out-quic-direct",
    "streamSettings":{
      "network":"quic",
      "security":"tls",
      "quicSettings":{
        "security":"aes-128-gcm",
        "key":"keykeykeyke",
        "header":{
          "type":"none"
        }
      },
      "tlsSettings":{
        "serverName":"lalalalllalala"
      }
    }
  },
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
   2020/12/30 06:22:14 [Debug] v2ray.com/core/transport/internet/kcp: #8332 entering state 3 at 872427
2020/12/30 06:22:14 [Info] v2ray.com/core/transport/internet/kcp: #8332 closing connection to 211.157.146.18:54677
2020/12/30 06:22:14 [Info] [1610367598] v2ray.com/core/app/proxyman/inbound: failed to close connection > io: read/write on closed pipe
2020/12/30 06:22:16 [Debug] v2ray.com/core/transport/internet/kcp: #8338 sending terminating cmd.
2020/12/30 06:22:16 [Debug] v2ray.com/core/transport/internet/kcp: #8338 entering state 5 at 310042
2020/12/30 06:22:16 [Info] v2ray.com/core/transport/internet/kcp: #8338 terminating connection to 211.157.146.18:55406
2020/12/30 06:22:17 [Debug] v2ray.com/core/transport/internet/kcp: #8332 sending terminating cmd.
2020/12/30 06:22:22 [Debug] v2ray.com/core/transport/internet/kcp: #8332 sending terminating cmd.
2020/12/30 06:22:22 [Debug] v2ray.com/core/transport/internet/kcp: #8332 entering state 5 at 880086
2020/12/30 06:22:22 [Info] v2ray.com/core/transport/internet/kcp: #8332 terminating connection to 211.157.146.18:54677
```

客户端错误日志:

```javascript
2020/12/30 18:54:11 [Warning] [2895670186] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [NO_ERROR: Handshake did not complete in time] > v2ray.com/core/common/retry: all retry attempts failed
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
2020/12/30 06:22:09 [Debug] v2ray.com/core/transport/internet/kcp: #8339 entering state 2 at 291074
2020/12/30 06:22:09 [Info] [2021293668] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > context canceled
2020/12/30 06:22:09 [Debug] v2ray.com/core/transport/internet/kcp: #8339 entering state 3 at 291198
2020/12/30 06:22:09 [Info] v2ray.com/core/transport/internet/kcp: #8339 closing connection to 211.157.146.18:60966
2020/12/30 06:22:09 [Info] [2021293668] v2ray.com/core/app/proxyman/inbound: failed to close connection > io: read/write on closed pipe
2020/12/30 06:22:09 [Info] [2021293668] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/12/30 06:22:10 [Debug] v2ray.com/core/transport/internet/kcp: #8338 entering state 2 at 304220
2020/12/30 06:22:10 [Info] [1582051599] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/12/30 06:22:10 [Info] [1582051599] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2020/12/30 06:22:10 [Debug] v2ray.com/core/transport/internet/kcp: #8338 entering state 3 at 304264
2020/12/30 06:22:10 [Info] v2ray.com/core/transport/internet/kcp: #8338 closing connection to 211.157.146.18:55406
2020/12/30 06:22:10 [Info] [1582051599] v2ray.com/core/app/proxyman/inbound: failed to close connection > io: read/write on closed pipe
2020/12/30 06:22:11 [Debug] v2ray.com/core/transport/internet/kcp: #8338 sending terminating cmd.
2020/12/30 06:22:13 [Debug] v2ray.com/core/transport/internet/kcp: #8339 sending terminating cmd.
2020/12/30 06:22:13 [Debug] v2ray.com/core/transport/internet/kcp: #8339 entering state 5 at 295045
2020/12/30 06:22:13 [Info] v2ray.com/core/transport/internet/kcp: #8339 terminating connection to 211.157.146.18:60966
2020/12/30 06:22:14 [Debug] v2ray.com/core/transport/internet/kcp: #8332 entering state 2 at 872387
2020/12/30 06:22:14 [Info] [1610367598] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/12/30 06:22:14 [Info] [1610367598] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2020/12/30 06:22:14 [Debug] v2ray.com/core/transport/internet/kcp: #8332 entering state 3 at 872427
2020/12/30 06:22:14 [Info] v2ray.com/core/transport/internet/kcp: #8332 closing connection to 211.157.146.18:54677
2020/12/30 06:22:14 [Info] [1610367598] v2ray.com/core/app/proxyman/inbound: failed to close connection > io: read/write on closed pipe
2020/12/30 06:22:16 [Debug] v2ray.com/core/transport/internet/kcp: #8338 sending terminating cmd.
2020/12/30 06:22:16 [Debug] v2ray.com/core/transport/internet/kcp: #8338 entering state 5 at 310042
2020/12/30 06:22:16 [Info] v2ray.com/core/transport/internet/kcp: #8338 terminating connection to 211.157.146.18:55406
2020/12/30 06:22:17 [Debug] v2ray.com/core/transport/internet/kcp: #8332 sending terminating cmd.
2020/12/30 06:22:22 [Debug] v2ray.com/core/transport/internet/kcp: #8332 sending terminating cmd.
2020/12/30 06:22:22 [Debug] v2ray.com/core/transport/internet/kcp: #8332 entering state 5 at 880086
2020/12/30 06:22:22 [Info] v2ray.com/core/transport/internet/kcp: #8332 terminating connection to 211.157.146.18:54677

8) 其它相关的配置文件（如 Nginx）和相关日志。
 没有使用Nginx
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
你只能升级到新的qui, 29是目前使用最广泛的草案

**Comment by ohiyangss** [comment]
请问如何升级到新的quic？v2ray 客户端 服务端都是 4.33版本

**Comment by kslr** [comment]
你提供的日志和配置对不上

**Comment by onlineyh** [comment]
你检查下配置文件 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json 新版本更改了配置文件路径 我也踩了一次坑 我的版本是4.34

**Comment by ohiyangss** [comment]
@onlineyh 谢谢提醒，因为你的提醒我发现，我一直以来运行的都是旧版本v2ray，在脚本中写了绝对路径。新版本虽然更新了，但是一直没有能够运行。现在一切良好。
@kslr 谢谢支持

**Comment by ohiyangss** [comment]
我一直以来运行的都是旧版本v2ray，在脚本中写了绝对路径。新版本虽然更新了，但是一直没有能够运行。现在一切良好。
