### ISSUE TITLE
VLESS + unix socket 对 acceptProxyProtocol 的处理不当

### ISSUE THREAD

**Issue by zhangyoufu** [v2fly/v2ray-core#579]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
   4.33.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
   使用 haproxy 进行 TLS 卸载，PROXY Protocol + 明文流量转发到 v2ray

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
   `streamSettings.sockopt.acceptProxyProtocol` 配置为 `true` 时，v2ray 依然只接受不包含 PROXY Protocol 的流量
   看上去因为一些内部逻辑，`streamSettings.tcpSettings.acceptProxyProtocol`（零值 `false`）盖掉了 `streamSettings.sockopt.acceptProxyProtocol`，尽管我并没有使用 tcp

4) 你期待看到的正确表现是怎样的？
   `streamSettings.sockopt.acceptProxyProtocol` 配置为 `true` 时，v2ray 正确处理 PROXY Protocol

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
   服务器端配置:
   ```javascript
   {
     "inbounds": [
       {
         "listen": "/mnt/v2ray/vless.sock",
         "protocol": "vless",
         "settings": {
           "decryption": "none",
           "clients": [
             {
               "id": "12345678-1234-1234-1234-123456789abc",
               "description": "dummy"
             }
           ]
         },
         "streamSettings": {
           "sockopt": {
             "acceptProxyProtocol": true
           }
         }
       }
     ],
     "outbounds": [
       {
         "protocol": "freedom"
       }
     ]
   }
   ```

   客户端配置: N/A

6) 请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

   服务器端错误日志: N/A

   客户端错误日志: N/A

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

   N/A

8) 其它相关的配置文件（如 Nginx）和相关日志。

   ```
   backend v2ray_vless
       mode tcp
       server v2ray_vless unix@/mnt/v2ray/vless.sock send-proxy-v2
   ```

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

   N/A

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

    N/A

**Comment by zhangyoufu** [comment]
@lucifer9, FYI

**Comment by lucifer9** [comment]
本来预期的是取消每个传输协议配置里面acceptProxyProtocol，统一放sockopt的
后来由于要兼容以前的配置写法，只能改成单独协议的设置优先级更高一些
然后其实你还是搞混了...按照你写的配置，应该是用新的方式来解析，这样的话，ds就不是跟tcp，ws等等平级，而是更低（或者更高，看怎么理解了）一级。于是传输方式由于你没写就默认是TCP，所以sockopt的配置由于之前说的原因，就被tcp里面的设置（空的话就默认false啦）覆盖了...
总的来说还是新旧配置交织起来造成误解了。还有就是传输配置tcp这个名字的锅，改叫raw的话就清晰一些。

**Comment by zhangyoufu** [comment]
@lucifer9
文档上写了 `未来这里的 DomainSocket 可能会被弃用`，所以我想避免旧的这套配置方式。
总不能按新的配置方式来就只能改 `streamSettings.tcpSettings.acceptProxyProtocol` 来达成 unix socket + proxy protocol 吧？

**Comment by zhangyoufu** [comment]
感觉更合适的逻辑是 sockopt. acceptProxyProtocol 覆盖 transport 中的配置，或者把配置项定义成指针，判断用户的意图，在两边冲突的时候拒绝。现在的配置看起来比较 weird

**Comment by lucifer9** [comment]
> @lucifer9
> 文档上写了 `未来这里的 DomainSocket 可能会被弃用`，所以我想避免旧的这套配置方式。
> 总不能按新的配置方式来就只能改 `streamSettings.tcpSettings.acceptProxyProtocol` 来达成 unix socket + proxy protocol 吧？

新的配置对应新的实现。而新的实现里面，传输方式里面**没有**ds，只有tcp，ws...这些。
那你不写传输方式的话，肯定是按照默认的tcp了啊
其实按你写的配置确实思路是对的，不过是受以前习惯影响罢了。
