### ISSUE TITLE
安卓版的v2ray不能使用upx压缩

### ISSUE THREAD

**Issue by zhj9709** [v2fly/v2ray-core#581]
![image](https://user-images.githubusercontent.com/13991774/103557280-e5875780-4eed-11eb-966c-9741ee07a088.png)
是upx的问题还是v2ray的问题，arm64没问题

**Comment by rampageX** [comment]
UPX 3.96 很多问题的，建议退回 3.94

**Comment by zhj9709** [comment]
> UPX 3.96 很多问题的，建议退回 3.94

3.94, 3.95都试了，都不行

**Comment by kslr** [comment]
这个问题你得去找 upx 吧

**Comment by zhj9709** [comment]
> 这个问题你得去找 upx 吧

好的

**Comment by kslr** [comment]
你可以依旧用 arm 版的使用 upx
