### ISSUE TITLE
Android 5.1无法使用v2ray-android-arm64-v8a

### ISSUE THREAD

**Issue by zhj9709** [v2fly/v2ray-core#582]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v4.34.0

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
执行时报错
![image](https://user-images.githubusercontent.com/13991774/103560958-a1975100-4ef3-11eb-8ad6-cc4b9b12fe40.png)

4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by kslr** [comment]
your phone is arm64 ?

**Comment by zhj9709** [comment]
> your phone is arm64 ?

是的

**Comment by CalmLong** [comment]
什么处理器

**Comment by CalmLong** [comment]
https://golang.org/doc/go1.13#android

仅支持 Android 10

**Comment by zhj9709** [comment]
> 什么处理器

MTK Helio X10 Turbo

**Comment by zhj9709** [comment]
> https://golang.org/doc/go1.13#android
> 
> 仅支持 Android 10 ，~或许 11 也可行~

安卓9可以。这个是不是以前最高只支持到安卓9，然后1.13开始支持安卓10了？

**Comment by nL6DHZc3RhMnC** [comment]
> > https://golang.org/doc/go1.13#android
> > 仅支持 Android 10 ，~或许 11 也可行~
> 
> 安卓9可以。这个是不是以前最高只支持到安卓9，然后1.13开始支持安卓10了？

支持安卓10应该是指安卓10以下能不能用得看缘分

**Comment by SekiBetu** [comment]
> [golang.org/doc/go1.13#android](https://golang.org/doc/go1.13#android)
> 
> 仅支持 Android 10 ，~或许 11 也可行~

This means, Go binaries now avoid system calls blocked by Android 10
