### ISSUE TITLE
关于腾讯云之类内网ip做服务器的提供商UDP NAT的一些测试

### ISSUE THREAD

**Issue by 1265578519** [v2fly/v2ray-core#592]
可以观察到，内网IP的服务器，，，NAT永远是严格，只有公网IP的情况下填入网卡的那种服务器，才能变成NAT中等

在没有解决NAT完全开放的情况下。

有没有什么办法改善下代码让内网IP的服务器也变成中等呢？

今天测了下发现的问题！
https://github.com/v2fly/v2ray-core/discussions/591

**Comment by 1265578519** [comment]
望来个大佬修一下！不求和SS一样能做到开放，好歹让其变成中等！
既然知道是网卡内网IP引起导致严格，，那么应该好修复这个问题才对

**Comment by xhqpp** [comment]
https://github.com/XTLS/Xray-core/discussions/252

**Comment by 1265578519** [comment]
2022年了，，居然还没解决这个问题，依旧是nat4，由于v2ray官方核心开摆，没去解决这个问题。测试采用包括所谓的第三方xray-core等等，都是假的nat1快乐灯
特别点名批评下netch，都说了这玩意新版垃圾的很，自从1.6.9以后的后续版本，都烂的不行，特别自从改了第三方xray核心后就bug满天了
1.6.9旧版的还能加速cod，netch新版由于用的xray核心直接加速不了提示网络中断。因为xray虚假的nat1快乐灯，导致游戏检测nat开放是假的引起进不去游戏
猜测估计就是这玩意的BUG，但是把它关掉后，虽然netch界面显示变成了nat3的快乐灯，但是一样也进不去游戏。
以上测试环境，采用xray核心服务端得出的结论
![image](https://user-images.githubusercontent.com/6442439/162582937-1edd05bb-e4ed-46cc-b263-fbebb58bb99d.png)
![1](https://user-images.githubusercontent.com/6442439/162583213-edf2abc5-6e55-459e-8574-2a3d32e432dd.png)
![2](https://user-images.githubusercontent.com/6442439/162583217-ec742e87-980f-4427-ace0-c7893d4df8e8.png)
![3](https://user-images.githubusercontent.com/6442439/162583220-deca1708-34e5-4b57-a306-75198ada1a12.png)
![4](https://user-images.githubusercontent.com/6442439/162583223-a731f6d9-b53e-4112-a586-13335770075b.png)
