### ISSUE TITLE
跨年后出现failed to read response header > websocket: close 1000 (normal)，已检查时间与id

### ISSUE THREAD

**Issue by hotpotgirl** [v2fly/v2ray-core#593]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器 4.20.0；客户端 4.21.3
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
浏览youtube网页
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法打开网页
4) 你期待看到的正确表现是怎样的？
可以正常访问youtube
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
"log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [{
    "port": 10620,
    "protocol": "vmess",
    "settings": {
"clients": [
                        {
                                "id": "***",
                                "level": 1,
                                "alterId": 64
                        }]
                },
                "streamSettings":
                 {
                         "network": "ws",
                         "wsSettings":
                         {
                                "path": "/awesomepath"
                         }
                 },
                 "listen": "127.0.0.1"

        }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
 // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "****",
            "port": 443,
            "users": [
              {
                "id": "****",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "域名"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/awesomepath",
          "headers": {
            "Host": "域名"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    无
// 在这里附上服务器端日志
```

客户端错误日志:

```javascript
2021/01/09 15:34:03 tcp:127.0.0.1:50391 accepted tcp:d.docs.live.net:443 [proxy] 
2021/01/09 15:34:05 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/01/09 15:34:06 tcp:127.0.0.1:50393 accepted tcp:activity.windows.com:443 [proxy] 
2021/01/09 15:34:06 tcp:127.0.0.1:50396 accepted tcp:android.clients.google.com:443 [proxy] 
2021/01/09 15:34:07 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/01/09 15:34:08 tcp:127.0.0.1:50398 accepted tcp:activity.windows.com:443 [proxy] 
2021/01/09 15:34:09 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/01/09 15:34:10 tcp:127.0.0.1:50401 accepted tcp:activity.windows.com:443 [proxy] 
2021/01/09 15:34:13 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)// 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
 2021/01/09 15:32:18 *****:49805 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2021/01/09 15:32:20  *****:49806 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2021/01/09 15:32:21  *****:49807 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2021/01/09 15:32:25  *****:49808 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2021/01/09 15:32:28  *****:49809 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2021/01/09 15:32:31  *****:49810 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2021/01/09 15:32:34  *****:49811 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
  // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
配置文件：
server {
    listen 80;
    server_name 域名;
    rewrite ^(.*) https://$server_name$1 permanent;
}

server {
    listen 443 ssl;
    server_name 域名;
    charset utf-8;

    ssl_certificate /etc/letsencrypt/live/***/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/***/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_ecdh_curve secp384r1;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    keepalive_timeout 70;
    root /usr/share/nginx/html;
    location / { index index.html;}
location /awesomepath {
proxy_redirect off;
proxy_pass http://127.0.0.1:10620;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}
日志：
access日志：
 - - [09/Jan/2021:15:37:48 -0500] "GET /awesomepath HTTP/1.1" 101 4 "-" "Go-http-client/1.1" "-"
**** - - [09/Jan/2021:15:38:01 -0500] "GET / HTTP/1.1" 301 170 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36" "-"
 - - [09/Jan/2021:15:38:23 -0500] "GET /awesomepath HTTP/1.1" 101 4 "-" "Go-http-client/1.1" "-"
 - - [09/Jan/2021:15:38:26 -0500] "GET /awesomepath HTTP/1.1" 101 4 "-" "Go-http-client/1.1" "-"
 - - [09/Jan/2021:15:38:28 -0500] "GET /awesomepath HTTP/1.1" 101 4 "-" "Go-http-client/1.1" "-"

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
> invalid user

**Comment by stryio** [comment]
我也出现了这个问题
2021/03/03 13:36:02 *****:19148 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate
2021/03/03 13:36:02 *****:57136 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate
2021/03/03 13:36:02 *****:46694 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate
2021/03/03 13:36:02 *****:46700 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate
2021/03/03 13:36:02 *****:46698 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate
2021/03/03 13:36:02 *****:46702 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate
用的tcp+tls出现这个报错
用ws+tls则出现
failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
怀疑是防火墙针对tls拦截的新手段，一般新申请的域名，不会出现这个报错，运行大概一天后就开始有大量报错，ip和端口都正常连通，证书正常，网站用梯子可以正常打开，不用梯子则打不开。
