### ISSUE TITLE
研发请求:自适应服务器故障分流[解决代理服务器不稳定]

### ISSUE THREAD

**Issue by z826540272** [v2fly/v2ray-core#594]
希望增加自适应服务器分流,
发起连接后,当前线路不通时,自动切换至备用节点重新发起连接
整个过程在5秒之内完成.
非主动式连接检测,主动式联通检测有弊端.
这样的话就不会遇到服务器不稳定影响上网体验了

**Comment by kslr** [comment]
no request, only pr :d
