### ISSUE TITLE
希望添加Shadowsockets的xchacha20-ietf-poly1305加密方法

### ISSUE THREAD

**Issue by scriptkitz** [v2fly/v2ray-core#605]
希望添加Shadowsockets的xchacha20-ietf-poly1305加密方法

**Comment by kslr** [comment]
Welcome PR

**Comment by database64128** [comment]
XC20P1305 is not part of the Shadowsocks AEAD specifications.

Related: shadowsocks/go-shadowsocks2#124, shadowsocks/shadowsocks-android#2653, shadowsocks/shadowsocks-android#2644, shadowsocks/shadowsocks-android#2642
