### ISSUE TITLE
长时间工作几天后会无法访问外网

### ISSUE THREAD

**Issue by Lather0519** [v2fly/v2ray-core#616]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

1) 你正在使用哪个版本的 V2Ray？ 【双端都是 Ver4.34.0】 

2) 你的使用场景是什么？【通过路由器V2ray插件使用Chrome 等信息载体浏览墙外信息】

3) 你看到的不正常的现象是什么？【V2ray工作2天左右，就会出现外网访问不正常，有时国内外都会无法访问，需要重启V2ray服务，严重时需要重启路由器】

4) 你期待看到的正确表现是怎样的？【未更新到v4.34.0时的正常使用】

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```{
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "*.*.*.*",
                        "port": 37193,
                        "users": [
                            {
                                "id": "971014c5-0d8a-4912-b91f-77927007cc2f",
                                "alterId": 233,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "mux": {
                "enabled": true
            }
        },
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        },
        {
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
        },
        {
            "protocol": "dns",
            "tag": "dns-out"
        }
    ],
    "inbounds": [
        {
            "port": "1099",
            "protocol": "dokodemo-door",
            "settings": {
              "network": "tcp,udp",
              "timeout": 0,
              "followRedirect": true
            },
            "sniffing": {
              "enabled": true,
              "destOverride": ["http", "tls"]
            }
        },
        {
            "port": 2133,
            "tag": "dns-in",
            "protocol": "dokodemo-door",
            "settings": {
                "address": "119.29.29.29",
                "port": 53,
                "timeout": 0,
                "network": "tcp,udp"
            }
        },
        {
            "port": 2333,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            }
        },
        {
            "port": 6666,
            "protocol": "http",
            "settings": {
                "auth": "noauth",
                "udp": true
            }
        }
    ],
    "dns": {
        "servers": [
            {
                "address": "119.29.29.29",
                "port": 53,
                "domains": [
                  "geosite:cn"
                ],
                "expectIPs": [
                  "geoip:cn"
                ]
              },
              {
                "address": "1.1.1.1",
                "port": 53,
                "domains": [
                  "geosite:geolocation-!cn"
                ]
            },
            "8.8.8.8",
            "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "IPOnDemand",	
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "dns-in"
                ],
                "outboundTag": "dns-out"
            },
            {
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "blocked"
			},
            {
                "type": "field",
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}
    // 在这里附上服务器端配置文件
```

客户端配置:

```{
	"log": {
		"access": "/dev/null",
		"error": "/tmp/v2ray_log.log",
		"loglevel": "error"
	},
	"inbounds": [
		{
			"port": 23456,
			"listen": "0.0.0.0",
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true,
				"ip": "127.0.0.1",
				"clients": null
			},
			"streamSettings": null
		},
		{
			"listen": "0.0.0.0",
			"port": 3333,
			"protocol": "dokodemo-door",
			"settings": {
				"network": "tcp,udp",
				"followRedirect": true
			}
		}
	],
	"outbounds": [
		{
			"tag": "agentout",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "*.*.*.*",
						"port": 37193,
						"users": [
							{
								"id": "971014c5-0d8a-4912-b91f-77927007cc2f",
								"alterId": 233,
								"security": "auto"
							}
						]
					}
				],
				"servers": null
			},
			"streamSettings": {
				"network": "tcp",
				"security": "",
				"tlsSettings": null,
				"tcpSettings": null,
				"kcpSettings": null,
				"wsSettings": null,
				"httpSettings": null
			},
			"mux": {
				"enabled": true,
				"concurrency": 8
			}
		}
	]
}


```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

``` 
https://www.dropbox.com/s/s7ao44h1t5eoxv2/error.log?dl=0

```

客户端错误日志:

```
【抱歉，没有收集】

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```
【792MB太大了】
  
```

**Comment by kslr** [comment]
内存有没有观察

**Comment by Lather0519** [comment]
> 内存有没有观察

有的，AC86U，512MB内存，开机占用312MB几天后持续走高止至342MB，稳定不波动

**Comment by kslr** [comment]
你可以把服务器的 doh 关闭试试

**Comment by Lather0519** [comment]
> 你可以把服务器的 doh 关闭试试

我百度了一下你说的是dns-over-https吗，看完介绍(https://github.com/felix-fly/v2ray-dnsmasq-dnscrypt#%E5%85%B3%E4%BA%8E-v2ray-dnsmasq-doh)只是简单知道是一种DNS服务，但我不清楚我是否有使用，也不知道如何关掉。
这是路由器插件启动日志，希望有你想要的信息：
========================
【2021年01月19日 18:31:12】:
【2021年01月19日 18:31:12】: ------------------------- 启动【科学上网】 -----------------------------
【2021年01月19日 18:31:12】: 关闭V2Ray进程...
【2021年01月19日 18:31:13】: 关闭chinadns1进程...
【2021年01月19日 18:31:13】: 关闭dns2socks进程...
【2021年01月19日 18:31:13】: 关闭haveged进程...
【2021年01月19日 18:31:13】: 插件触发重启定时任务已经删除...
【2021年01月19日 18:31:13】: 删除ss相关的名单配置文件.
【2021年01月19日 18:31:13】: 【dnsmasq替换】：从dnsmasq-fastlookup切换为原版dnsmasq
【2021年01月19日 18:31:13】: 重启dnsmasq服务...
【2021年01月19日 18:31:13】: 清除iptables规则和ipset...
【2021年01月19日 18:31:13】: 删除ss规则定时更新任务...
【2021年01月19日 18:31:13】: 启动haveged，为系统提供更多的可用熵！
【2021年01月19日 18:31:13】: 检测到你的v2ray服务器已经是IP格式：*.*.*.*, 跳过解析... 
【2021年01月19日 18:31:13】: 创建ipset名单
【2021年01月19日 18:31:14】: 应用域名白名单
【2021年01月19日 18:31:14】: 自动判断dns解析使用国外优先模式...
【2021年01月19日 18:31:14】: 国外解析方案【chinadns1】自带国内cdn，无需加载cdn.conf，路由器开销小...
【2021年01月19日 18:31:14】: 检测到网络拨号/开机触发启动，不创建v2ray配置文件，使用上次的配置文件！
【2021年01月19日 18:31:14】: 开启tcp fast open支持.
【2021年01月19日 18:31:14】: v2ray启动成功，pid：22320
【2021年01月19日 18:31:14】: 开启dns2socks，用于chinadns1上游...
【2021年01月19日 18:31:14】: 开启chinadns1，用于【国内cdn网站 + 国外所有网站】的DNS解析...
【2021年01月19日 18:31:14】: 加载nat规则!
【2021年01月19日 18:31:14】: 写入iptables规则到nat表中...
【2021年01月19日 18:31:15】: 加载ACL规则：【全部主机】【全部端口】模式为：大陆白名单模式
【2021年01月19日 18:31:15】: 开启DNS劫持功能功能，防止DNS污染...
【2021年01月19日 18:31:15】: 【dnsmasq替换】：用dnsmasq-fastlookup替换原版dnsmasq！
【2021年01月19日 18:31:15】: 重启dnsmasq服务...
【2021年01月19日 18:31:15】: 添加ss规则定时更新任务，每天5自动检测更新规则.
【2021年01月19日 18:31:15】: 插件触发重启定时任务已经删除...
【2021年01月19日 18:31:15】: ------------------------ 【科学上网】 启动完毕 ------------------------

**Comment by DolorHunter** [comment]
在浏览器设置里面关闭doh试试, src: [Disable DNS over HTTPS on enterprise browsers](https://learn.akamai.com/en-us/webhelp/enterprise-threat-protector/etp-client-configuration-guide/GUID-04D2A852-CB51-4210-9CE3-7F6ABB3B84E2.html)

- On Google Chrome

DNS over HTTPS (DoH) is enabled by default on Google Chrome version 83 or later. Complete this procedure to disable DoH.

1. In the Chrome address bar, enter chrome://flags/#dns-over-https.
2. Go to the Secure DNS lookups setting.
3. In the provided menu, select Disabled.
4. Click Relaunch to relaunch the browser window with this change. 

- On Mozilla Firefox

DNS over HTTPS (DoH) is enabled by default on Mozilla Firefox. Complete this procedure to disable DoH.

1. On Mozilla Firefox, click the menu button.
2. Click Options.
3. Go to the Network Settings section and click Settings.
4. Scroll down to the Enable DNS over HTTPS option, and deselect it.
5. Click OK to save your settings. 

- On Microsoft Edge

While DNS over HTTPS (DoH) is not enabled by default on Microsoft Edge browsers, you can perform this procedure in case it’s enabled.

1. In the Microsoft Edge address bar, enter edge://flags#dns-over-https.
2. Go to the Secure DNS Lookup setting.
3. In the provided menu, select Disabled.
4. Click Restart to restart the browser with this change.

**Comment by Lather0519** [comment]
> 1. chrome://flags/#dns-over-https.

不是浏览器哦，是路由器插件，不过目前暂时没事了
