### ISSUE TITLE
Security enhancement: Allow server to deny VMess clients without AEAD

### ISSUE THREAD

**Issue by U925** [v2fly/v2ray-core#617]
## Versions

Server: official binary v4.34.0
Client: official binaries v4.34.0 and v4.23.4

## Observed behaviour

First experiment:

1. Launch server with `v2ray -c server.json`
2. Launch client (v4.34.0) with VMessAEAD forcedly disabled with `V2RAY_VMESS_AEAD_DISABLED=true v2ray -c client.json`
3. The server accepts connections from the client

Second experiment:

1. Launch server with `v2ray -c server.json`
2. Launch client (v4.23.4) with `v2ray -c client.json` (this version doesn't support VMessAEAD)
3. The server accepts connections from the client

In either case, the server is accepting connections without AEAD. In other words, it is not enjoying the benefits of AEAD against active probing.

## Suggested enhancement

Allow server to optionally deny VMess clients without AEAD.

In the future (for example in a major version increase), set denying VMess clients without AEAD as default and accepting them optional.

## Configurations

Server configuration:

```javascript
{
  "log": {
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1081,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
            "alterId": 0
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

Client configuration:

```javascript
{
  "log": {
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "127.0.0.1",
            "port": 1081,
            "users": [
              {
                "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
                "alterID": 0
              }
            ]
          }
        ]
      }
    }
  ],
  "routing": {}
}
```

**Comment by z826540272** [comment]
不支持，开AES/CHACHA20加密后我的路由器只能跑30-50M了，None模式可以接近100M

**Comment by Loyalsoldier** [comment]
> 不支持默认开启，开AES/CHACHA20加密后我的路由器只能跑30-50M了，None模式可以接近100M

https://github.com/v2fly/v2ray-core/pull/720
