### ISSUE TITLE
连接加密方式为aes-256-cfb的节点显示加密方式不支持（旧版core没有此问题）

### ISSUE THREAD

**Issue by takedownccp** [v2fly/v2ray-core#620]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

Core: 4.34.0, v2rayN: 3.29

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

使用firefox通过shadowsocks代理浏览网页

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

[Info] v2ray.com/core/main/jsonem: Reading config: F:\v2rayN-Core\config.json
main: failed to read config files: [F:\v2rayN-Core\config.json] > v2ray.com/core/infra/conf: unknown cipher method: aes-256-cfb

无法连接节点

4) 你期待看到的正确表现是怎样的？

能正常连接节点

e.g. 其他AEAD加密方式正常；旧版本core（4.33.x, 4.32.x）能正常连接

**Comment by database64128** [comment]
Support for the legacy Shadowsocks protocol with stream ciphers has been removed. Use Shadowsocks AEAD instead.

**Comment by jeffery9** [comment]
回退到 3.0 依然不支持

2023/04/03 15:04:31 tcp:127.0.0.1:53874 accepted tcp:alive.github.com:443 [proxy]
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 darwin/amd64)
A unified platform for anti-censorship.
2023/04/03 15:16:42 [Info] infra/conf/serial: Reading config: config.json
2023/04/03 15:16:42 [Warning] core: Xray 1.5.5 started
V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 darwin/amd64)
A unified platform for anti-censorship.
2023/04/03 15:17:30 [Info] v2ray.com/core/main/jsonem: Reading config: config.json
main: failed to read config files: [config.json] > v2ray.com/core/infra/conf: unknown cipher method: aes-256-cfb

貌似 v2ray core 版本太高， 不再支持。
