### ISSUE TITLE
pc端可以正常运行，使用移动端连不上服务器

### ISSUE THREAD

**Issue by fy59644** [v2fly/v2ray-core#629]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
最新版本

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
已经使用三个月，之前都是正常的，现在用只能pc端。移动端连不上服务器。但是我去别的城市pc和移动端都正常，是不是dns的问题？还是别的问题可能会出现这样的情况，
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by 18263873187** [comment]
目前我将dns改成了8.8.8.8，wif的情况下是可以用的，但是移动流量依然不可以。有大神知道这是为啥吗？

**Comment by ququ0755** [comment]
@18263873187 你是用哪家运营商的流量

**Comment by ququ0755** [comment]
> 目前我将dns改成了8.8.8.8，wif的情况下是可以用的，但是移动流量依然不可以。有大神知道这是为啥吗？

@18263873187 你用哪家运营商

**Comment by 18263873187** [comment]
手机我是用的移动还有联通，服务器是vultr的日本服务器




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v2fly/v2ray-core"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 上午10:34
收件人:&nbsp;"v2fly/v2ray-core"<v2ray-core@noreply.github.com&gt;;
抄送:&nbsp;"风缘"<596441799@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [v2fly/v2ray-core] pc端可以正常运行，使用移动端连不上服务器 (#629)





  
目前我将dns改成了8.8.8.8，wif的情况下是可以用的，但是移动流量依然不可以。有大神知道这是为啥吗？
  
@18263873187 你用哪家运营商

**Comment by ququ0755** [comment]
移动是墙中墙，可以上Google搜一下
