### ISSUE TITLE
已经支付钱了，显示支付失败，提交工单反映问题无人处理，QQ联系客服人员无人回应，联系方式qq:675505899

### ISSUE THREAD

**Issue by monkeyshichi** [v2fly/v2ray-core#631]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

This issue will be closed immediately.

**Comment by xhqpp** [comment]
电信诈骗的话去公安局咨询
