### ISSUE TITLE
go1.15.7 编译Android版本 无法使用  go1.15.6 编译正常

### ISSUE THREAD

**Issue by fvlw** [v2fly/v2ray-core#636]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.34.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Android上使用 V2Ray

使用官方编译的v2ray-android-arm64-v8a.zip 可以正常运行 (官方go版本go1.15.6 )

![图片](https://user-images.githubusercontent.com/71577616/105823609-52c36f80-5ff8-11eb-922a-8af8ecae3857.png)
![图片](https://user-images.githubusercontent.com/71577616/105824257-12b0bc80-5ff9-11eb-9925-34d82df9cd02.png)

go1.15.6 会显示  v2ray.com/core: V2Ray 4.34.0 started
go1.15.7 没有显示启动状态输出

**Comment by kslr** [comment]
无法重现该问题

**Comment by fvlw** [comment]
找到原因了
用新版本go编译的版本启动比较慢，不像go1.15.6 编译的版本 很快就输出启动成功
等待了2分钟 才输出启动成功的结果
![图片](https://user-images.githubusercontent.com/71577616/107723216-a1bd1480-6d1b-11eb-81e7-9a731f78624b.png)
