### ISSUE TITLE
Carbon Black 和微软一直报毒

### ISSUE THREAD

**Issue by gtang8** [v2fly/v2ray-core#664]
## 你正在使用哪个版本的 V2Ray？

4.xx

## 你的使用场景是什么？

Windows 10 Pro

## 你看到的异常现象是什么？

Carbon Black 和微软一直报毒

## 你期待看到的正常表现是怎样的？

应该是误杀，但是能否避免？否则公司电脑不能使用。

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件

```

**客户端配置：**

```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by kslr** [comment]
消除只能通过手动发邮件给微软，如果你真的想用可以来发，也不是很复杂。

**Comment by leungyauming** [comment]
不可以單獨選擇跳過檢查某個執行檔嗎？

**Comment by gtang8** [comment]
> 不可以單獨選擇跳過檢查某個執行檔嗎？

公司电脑是不能修改的

**Comment by gtang8** [comment]
> 消除只能通过手动发邮件给微软，如果你真的想用可以来发，也不是很复杂。

与其挑战微软和Carbon Black，有没有可能避开他们的报读机制？

**Comment by kslr** [comment]
不值得花费精力

**Comment by forever8938** [comment]
我的win10没有报毒

**Comment by xiaokangwang** [comment]
是这样的，现在V2没有数字签名，然后微软的杀毒软件是根据引用的包来判断是不是病毒的所以基本上每次都会被检测出是病毒。
简单的方法的话就是每次生成出来二进制文件就手工上传到杀毒软件的开发商那里请求白名单。或者想办法写个脚本也好。
如果想一劳永逸的解决这个问题就需要给杀毒软件公司交钱来交涉，成本会比较高。

**Comment by hzhr** [comment]
WSL 1下跑Linux版。
