### ISSUE TITLE
开启全局代理，重启电脑无法连接到网络。

### ISSUE THREAD

**Issue by yuesong-feng** [v2fly/v2ray-core#665]
## 你正在使用哪个版本的 V2Ray？

V3.29

## 你的使用场景是什么？

开启http全局代理后，在不关闭代理或者退出软件的情况下，直接关机重启电脑。

## 你看到的异常现象是什么？

重启电脑后，如果没有运行V2Ray，则无法进行部分网络连接。必须打开V2Ray软件，才能正常连接到网络。

## 你期待看到的正常表现是怎样的？
重启电脑后正常连接到网络。

**Comment by kslr** [comment]
这得看你用的是哪个客户端
