### ISSUE TITLE
(配合cloudflare下)大家有成功使用假host的没？ 能否分享下配置。

### ISSUE THREAD

**Issue by insoxin** [v2fly/v2ray-core#673]
目的免流host伪装

WebSocket+TLS+nginx与Cloudflare CDN梯子，伪装域名(host)的功能无法使用

将客户端中的伪装域名(host)设置成自己的域名www.myhostxxxx.top或者不设置，能够联网。
将其设置成伪装的，比如www.ted.com或者www.youku.com之类的，无法联网

**Comment by database64128** [comment]
You don't use a fake hostname with CDNs.
