### ISSUE TITLE
32位程序无法在windows server2003上运行！

### ISSUE THREAD

**Issue by simonchan6688** [v2fly/v2ray-core#706]
## 你正在使用哪个版本的 V2Ray？
4.19.1 windows-32

## 你看到的异常现象是什么？

自4.20以后版本，32位程序无法在windows server2003上运行！4.19.1或之前版本无问题！
![25](https://user-images.githubusercontent.com/34909952/108969033-7f80aa80-76bc-11eb-913f-3fbca0d03bfa.png)

**Comment by okudayukiko** [comment]
Windows Server 2003即使用IE8 也不支援各網站的HTTPS。
