### ISSUE TITLE
config "domainMatcher" move to RoutingObject?

### ISSUE THREAD

**Issue by rurirei** [v2fly/v2ray-core#731]
https://www.v2fly.org/config/routing.html#ruleobject

what about move config `domainMatcher` to RoutingObject instead? @xiaokangwang 

```jsonc
// now
"rules": [ { "domainMatcher": "ac" } ]

// new
{ "domainStrategy": "AsIs", "domainMatcher": "ac", "rules": [ ... ] }
```

**Comment by database64128** [comment]
Let's also take the chance to change `ac` to `hybrid`. 😁

**Comment by xiaokangwang** [comment]
I agree with you. I will incorporate  this two changes into next minor version update, which should be a Release version.
