### ISSUE TITLE
在windows下fakedns默认设置报解析失败

### ISSUE THREAD

**Issue by wyx2685** [v2fly/v2ray-core#734]
新版本路由器用默认的fakedns设置，ip段使用240.0.0.0/8时
在win10上用nslookup可以成功返回解析，但使用ping或者chrome浏览器会报错DNS解析失败
安卓下可以正常使用

修改"ipPool": "10.0.0.0/8" 后问题解决

**Comment by yuhan6665** [comment]
I suspect there is no one address block fit all cases. Please configure custom address for each device.

**Comment by kingwilliam** [comment]
因windows 也不支援 240.0.0.0/8 段, 所以执行 tracert 会 error 1231.

```
Microsoft Windows [Version 10.0.19042.804]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\>tracert 240.0.0.3

Tracing route to 240.0.0.3 over a maximum of 30 hops

  1  Transmit error: code 1231.

Trace complete.
```

所以解决方法可用 10.0.0.0/8或172.16.0.0/12段, 但是也要留意对您的设定会否有冲突

**Comment by wyx2685** [comment]
这个问题可否在文档里面加个注明？
没遇到过的可能排查半天

**Comment by Loyalsoldier** [comment]
Fixed by #779

Thanks for feedback.  Now fakedns uses `198.18.0.0/15` as the default IP pool.
