### ISSUE TITLE
4.34版本v2ray启动失败

### ISSUE THREAD

**Issue by wuren1222** [v2fly/v2ray-core#739]
手机发的，格式编辑不好，抱歉。问题：

编辑 config.json  文件后，v2ray启动失败，日志提示：

-- Logs begin at Fri 2021-03-05 20:34:07 EST, end at Fri 2021-03-05 21:04:51 EST. --
Mar 05 20:42:35 proud-frogs-3.localdomain systemd[1]: *[/etc/systemd/system/v2ray.service:9] Unknown lvalue 'AmbientCapabilities' in section 'Service'*
Mar 05 20:42:35 proud-frogs-3.localdomain systemd[1]: *[/etc/systemd/system/v2ray.service:9] Unknown lvalue 'AmbientCapabilities' in section 'Service'*
Mar 05 20:42:44 proud-frogs-3.localdomain systemd[1]: *[/etc/systemd/system/v2ray.service:9] Unknown lvalue 'AmbientCapabilities' in section 'Service'*
Mar 05 20:42:59 proud-frogs-3.localdomain systemd[1]: Started V2Ray Service.
Mar 05 20:42:59 proud-frogs-3.localdomain systemd[1]: Starting V2Ray Service...
Mar 05 20:42:59 proud-frogs-3.localdomain v2ray[11344]: V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 linux/amd64)
Mar 05 20:42:59 proud-frogs-3.localdomain v2ray[11344]: A unified platform for anti-censorship.
Mar 05 20:42:59 proud-frogs-3.localdomain v2ray[11344]: 2021/03/05 20:42:59 [Info] v2ray.com/core/main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Mar 05 20:42:59 proud-frogs-3.localdomain v2ray[11344]: 2021/03/05 20:42:59 [Warning] v2ray.com/core: V2Ray 4.34.0 started
Mar 05 20:50:35 proud-frogs-3.localdomain systemd[1]: Stopping V2Ray Service...
Mar 05 20:50:35 proud-frogs-3.localdomain systemd[1]: Started V2Ray Service.
Mar 05 20:50:35 proud-frogs-3.localdomain systemd[1]: Starting V2Ray Service…
Mar 05 20:50:35 proud-frogs-3.localdomain v2ray[11426]: V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 linux/amd64)
Mar 05 20:50:35 proud-frogs-3.localdomain v2ray[11426]: A unified platform for anti-censorship.
Mar 05 20:50:35 proud-frogs-3.localdomain systemd[1]: *v2ray.service: main process exited, code=exited, status=2/INVALIDARGUMENT*
Mar 05 20:50:35 proud-frogs-3.localdomain systemd[1]: *Unit v2ray.service entered failed state.*
Mar 05 20:50:35 proud-frogs-3.localdomain systemd[1]: *v2ray.service failed.*

针对 Unknown lvalue 'AmbientCapabilities' in section 'Service' 的提示，找了一些相关问题帖，删了 etc/systemd/system/v2ray.service 文件中的：

CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true

但还是不行，无法启动，实在不懂要怎么解决，只懂一点自学的 v2ray相关的代码。

有说法是 Cent OS 7 不支持 AmbientCapabilities ，然后尝试 Debian 10 也不行，日志提示  Failed with result ’exit-code’. 有人说是有V2ray重复的文件路径，但也没懂怎么查看怎么改。

求助。

**Comment by database64128** [comment]
Fix your JSON config.
