### ISSUE TITLE
开mux时打开一个无法打开的地址会造成代理暂时无法使用

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#747]
## 你正在使用哪个版本的 V2Ray？

4.34.0

## 你的使用场景是什么？

打开一个无法打开的地址 如8.7.6.5 或者http://oca.microsoft.com

## 你看到的异常现象是什么？

在这个打开过程中浏览器会白页面 因为他打不开 然而其他所有页面也同时打不开了!!!

## 你期待看到的正常表现是怎样的？
其他页面应当能被打开

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件
https://github.com/v2fly/v2ray-core/issues/482#issuecomment-740743465
```

**客户端配置：**
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 9053,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": false,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "addr1",
            "port": 443,
            "users": [
              {
                "id": "",
                "alterId": 4,
				"flow":"",
				"encryption": "none",
                "security": "none"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "addr"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "path": "/ppp",
          "headers": {
            "Host": "addr"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 80
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null
    }
  ],
  "dns": {
    "servers": [
      "9.9.9.9"
    ]
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "111.123123.com"
        ]
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }
    ]
  }
}
```javascript
// 在这里附上客户端配置

```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志

```

**客户端错误日志：**
2021/03/07 20:15:00 [Info] [235627161] v2ray.com/core/proxy/http: request to Met
hod [GET] Host [8.7.6.5] with URL [http://8.7.6.5/]
2021/03/07 20:15:00 [Info] [235627161] v2ray.com/core/app/dispatcher: default ro
ute for tcp:8.7.6.5:80
2021/03/07 20:15:00 [Info] [235627161] v2ray.com/core/common/mux: dispatching re
quest to tcp:8.7.6.5:80
2021/03/07 20:15:04 [Info] [595020008] v2ray.com/core/proxy/http: request to Met
hod [GET] Host [portableappz.blogspot.com] with URL [http://portableappz.blogspo
t.com/]
2021/03/07 20:15:04 [Info] [595020008] v2ray.com/core/app/dispatcher: default ro
ute for tcp:portableappz.blogspot.com:80
2021/03/07 20:15:04 [Info] [595020008] v2ray.com/core/common/mux: dispatching re
quest to tcp:portableappz.blogspot.com:80
2021/03/07 20:15:11 [Info] [3092939601] v2ray.com/core/app/proxyman/inbound: con
nection ends > v2ray.com/core/proxy/http: connection ends > context canceled
2021/03/07 20:15:11 [Info] [3092939601] v2ray.com/core/common/mux: failed to fet
ch all input > io: read/write on closed pipe
2021/03/07 20:15:11 [Info] [1277318162] v2ray.com/core/app/proxyman/inbound: con
nection ends > v2ray.com/core/proxy/http: connection ends > context canceled
2021/03/07 20:15:11 [Info] [1277318162] v2ray.com/core/common/mux: failed to fet
ch all input > io: read/write on closed pipe
2021/03/07 20:15:11 [Info] [1152731113] v2ray.com/core/app/proxyman/inbound: con
nection ends > v2ray.com/core/proxy/http: connection ends > context canceled
2021/03/07 20:15:11 [Info] [1152731113] v2ray.com/core/common/mux: failed to fet
ch all input > io: read/write on closed pipe
2021/03/07 20:15:43 [Info] [2028838220] v2ray.com/core/proxy/http: request to Me
thod [CONNECT] Host [imgur.com:443] with URL [//imgur.com:443]
2021/03/07 20:15:43 [Info] [2028838220] v2ray.com/core/app/dispatcher: default r
oute for tcp:imgur.com:443
2021/03/07 20:15:43 [Info] [2028838220] v2ray.com/core/common/mux: dispatching r
equest to tcp:imgur.com:443
```javascript
// 在这里附上客户端日志

```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

**Comment by z826540272** [comment]
你用的机场把.
