### ISSUE TITLE
`sockopt` of Dokodemo TProxy Inbound has no affect on returning socket

### ISSUE THREAD

**Issue by Vigilans** [v2fly/v2ray-core#75]
#### 你正在使用哪个版本的 V2Ray？
4.26.0

#### 你的使用场景是什么？
透明代理。

#### 你看到的不正常的现象是什么？

用作透明代理的Dokodemo Inbound，其JSON配置中sockopt的设置（e.g. mark）对返回至Client的Socket没有效果。

可以通过如下步骤得到验证：
1. 配置好透明代理，令所有流量通过Dokodemo Tproxy Inbound，该Inbound设置Sockopt.Mark为255。
2. 另配置一个Socks Inbound，同样设置Sockopt.Mark为255。
3. 以DNS查询为例，在透明代理中配置如下日志规则（部分内容）以追踪V2Ray截获后发出的DNS响应：
   ```bash
    ip route add local default dev lo table 100 # 策略路由
    ip rule add fwmark 1 table 100

    iptables -t mangle -N V2RAY_INPUT
    iptables -t mangle -A V2RAY_INPUT -p udp --sport 53 -j LOG --log-level info # 记录DNS流量是否被重路由回INPUT链
    iptables -t mangle -A INPUT -j V2RAY_INPUT

    iptables -t mangle -N V2RAY_MARK
    iptables -t mangle -A V2RAY_MARK -p udp --sport 53 -j LOG --log-level debug # 记录TProxy的DNS响应（源地址为外网DNS IP:53端口）
    iptables -t mangle -A V2RAY_MARK -p udp -m mark --mark 0xff -j RETURN # 放行V2Ray发出的流量
    iptables -t mangle -A V2RAY_MARK -p udp -j MARK --set-mark 0x1 # 打上标记重路由
    iptables -t mangle -A V2RAY_MARK -p udp --sport 53 -j LOG --log-level debug # 查看是否没有被成功放行
    iptables -t mangle -A OUTPUT -j V2RAY_MARK # 应用至OUTPUT链
   ```
4. 配置好`rsyslog`服务，执行`nslookup baidu.com 114.114.114.114`，在`/var/log/debug`中观察捕获到的DNS流量：
   ```log
   [2047421.414478] IN= OUT=eth0 SRC=114.114.114.114 DST=127.0.0.1 LEN=80 TOS=0x00 PREC=0x00 TTL=64 ID=32853 DF PROTO=UDP SPT=53 DPT=60862 LEN=60 
   [2047421.414505] IN= OUT=eth0 SRC=114.114.114.114 DST=127.0.0.1 LEN=80 TOS=0x00 PREC=0x00 TTL=64 ID=32853 DF PROTO=UDP SPT=53 DPT=60862 LEN=60 MARK=0x1
   ```
   在Access日志中可以看到V2Ray成功从外部DNS服务器取得了回复。但上文日志表明Dokodemo Inbound响应的Socket并没有打上255 Mark，也没有成功放行。在`/var/log/message`中，能看到打上了1 Mark的DNS流量，说明其进入了INPUT链。此时，**由于目的地址就是本机，因此`nslookup`能正常获取到响应**。

5. 在另一台设备上，配置`114.114.114.114`的路由以透明代理设备为网关：
   ```bash
   ip route add 114.114.114.114 via 192.168.200.8 table main # 192.168.200.8是树莓派IP
   ```
6. 在上述设备上以114为服务器查询DNS流量：`nslookup baidu.com 114.114.114.114`，结果是查询无响应。在透明代理设备的`/var/log/debug`中能看到与上面相似的两行消息，同时`/var/log/messages`中显示：
   ```log
   [1983152.609196] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=114.114.114.114 DST=192.168.200.7 LEN=254 TOS=0x00 PREC=0x00 TTL=64 ID=19453 DF PROTO=UDP SPT=53 DPT=42598 LEN=234 MARK=0x1
   ```
   本应直接送回原设备（192.168.200.7）的流量，被重路由后回到了INPUT链（到不了FORWARD链，因为路由表中只配置了送给lo网卡的路由），**而透明代理设备并没有能处理该流量的应用，因此包被废弃掉，致使原设备代理失败**。

7. 在上述设备上对透明代理设备的Socks Inbound发送任意请求，在`/var/log/debug`中观察：
   ```log
   [2116590.850537] IN= OUT=eth0 SRC=192.168.200.8 DST=192.168.200.7 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=1080 DPT=37666 WINDOW=65160 RES=0x00 ACK SYN URGP=0 MARK=0xff
   ```
    可以看到Socks Inbound的回复能正常为Socket绑定MARK，同时Client设备能收到回复，说明成功放行。

上述现象的产生，是因为Dokodemo TProxy Inbound并未用监听的Socket回复客户端，而是另外新建了一个源地址绑定为原目标IP的连接(tConn），同时这个连接的Sockopt完全由自己构造，并没有复用StreamSettings里的SocketConfig：

https://github.com/v2fly/v2ray-core/blob/45bf57826d8006f2b2b4e2e44f047064cfa05293/proxy/dokodemo/dokodemo.go#L161-L168

因此尽管监听Socket成功绑定了Mark 255，回复的Socket与该Mark是无缘的。

#### 你期待看到的正确表现是怎样的？

透明代理的教程里，一个重要的关注点是V2Ray发出的流量应该被直连，而非重路由。同时不仅是V2Ray发给外网的请求，V2Ray回复给内网的响应也是从OUTPUT链上发出流量，从而应当被直连。因此这种对Inbound设置Sockopt的方法同理应像Outbound一样可以生效。

> 不过，由于在配置透明代理时往往会添加本地IP（如192.168.0.0/16）直连，而Dokodemo TProxy Inbound回复的IP基本在此之列，因此一般情况下不需要设置Sockopt也能达到效果，从而规避了这个问题。
> 不过×2，由于Socks Inbound的Sockopt设置能够在回复Socket上成功设置MARK，因此Dokodemo的这个行为应当属于BUG，仍然应该被修复。

#### 服务器端配置

```javascript
"inbounds": [
  {
    "tag":"transparent",
    "protocol": "dokodemo-door",
    "listen": "127.0.0.1",
    "port": 821,
    "sniffing": { "enabled": true, "destOverride": ["http", "tls"] },
    "settings": {
      "network": "tcp,udp",
      "followRedirect": true
    },
    "streamSettings": {
      "sockopt": {
        "tproxy": "tproxy", 
        "mark": 255
      }
    }
  }, { 
    "tag": "socks5",
    "protocol": "socks",
    "listen": "192.168.200.8",
    "port": 1080,
    "sniffing": { "enabled": true, "destOverride": ["http", "tls"] },
    "settings": {
      "ip": "127.0.0.1",
      "auth": "noauth",
      "udp": true
    },
    "streamSettings": {
      "sockopt": { "mark": 255 }
    }
  }
]
```

**Comment by ToutyRater** [comment]
我只是一个使用者，对于网络、代码的细节不甚了解，不理解你的描述。因此我想从一个使用者的角度提一个问题：理论上，dokodemo是不是也应该设置Sockopt.Mark，然后iptables对该Sockopt.Mark的流量执行RETURN动作？

**Comment by Vigilans** [comment]
@ToutyRater 一句话总结应该是：一般不需要。

iptables对`Sockopt.Mark: 255`的重路由发生在OUTPUT链上，这是本地进程发出的流量所要经过的路线。

V2Ray进程发出一份流量时，有两种可能：
* 目标地址是外网IP。这一般是v2ray作为client对某个outbound发出request，如VPS地址；
* 目标地址是内网IP。这一般是v2ray作为server从某个inbound发出response，如透明代理下某个终端设备。

对于前者，现有教程里均会要求每个Outbound都设置Sockopt，因此在RETURN上没有出现过什么问题；

对于后者，由于以下原因，一般也不会遇到问题：
* 现有教程绝大多数会在OUTPUT链上设置直连内网目标IP。透明代理的环境被代理的设备基本都是使用内网IP，因此尽管Dokodemo返回的流量没有打标记，在`Mark 255`规则上直连失败了，但在内网IP（如192.168.0.0/16）规则上直连成功了，从而规避了问题。
* 本Issue提及的问题只出现在UDP转发上。只有UDP使用TProxy时，V2Ray会新建一个连接，但没有复用JSON Inbound配置里的Sockopt。流量的大头TCP则复用了监听的连接，Sockopt一直是正确的。
* 多数教程对于UDP只透明代理DNS流量。参考[这篇教程](https://xdays.me/V2RAY%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86/)，其在OUTPUT链中只为目标端口为53的流量打标记，因此只有DNS查询的去程流量被重路由了（透明代理给客户端回复时，变成源端口为53了）。所以尽管这篇教程对UDP流量没有设置内网IP直连，但由于UDP代理的作用范围小，同样规避了问题。

而我此前的代理设置是：1）代理所有UDP流量（有游戏需求）；2）OUTPUT链上未设置内网IP直连。于是悲剧就产生了。

总结上面的描述，个人觉得需要给Inbound打上Mark 255直连的情况：
* 不想在iptables里管理大量地址，想将所有路由交给V2Ray处理（似乎路由器上会有性能问题……）。此时只有Mark 255能保证TProxy Inbound的回复不被重路由。
* 设备在对内提供透明代理的同时，还需要为外网提供一般代理服务的。以使用Socks Inbound（如朋友间联机时改善联机状况）为例，其回复时的IP是一个外网IP（当然也可能是ZeroTier等Virtual LAN里的内网IP……），此时无法触发内网IP直连规则，若没有通过Sockopt.Mark来RETURN，则会触发重路由而导致回复失败。

**Comment by Vigilans** [comment]
@ToutyRater 补充另一个配置相关的问题（刚遇到的）：

https://guide.v2fly.org/app/tproxy.html 一节中，iptables规则里TPROXY指令只使用了`--on-port`参数：
```
iptables -t mangle -A V2RAY_MASK -p udp -j TPROXY --on-port 12345 --tproxy-mark 1
```

由于教程里Dokodemo默认监听了`0.0.0.0`，这样写没有什么问题；但如果手动配置Dokodemo只监听`127.0.0.1`，这样会导致内网里的其他设备（如`192.168.200.7`）送给透明代理设备的请求无法送至Dokodemo Inbound。这大概是因为iptables默认转发到了`192.168.200.8`（透明代理设备IP）上，而这个IP并没有被Dokodemo监听。设置`--on-ip 127.0.0.1`后恢复正常。

**Comment by ToutyRater** [comment]
非常感谢！我差不多明白了，有一些小问题我自己再思考一下。

白话文中透明代理的内容是我编写的，我当时的想法是流量来自内网的其他设备，监听127.0.0.1会导致无法使用，所以没特别指定监听地址；--on-ip 参数我其实也疑惑了一段时间，不清楚 127.0.0.1 还是 0.0.0.0 有什么区别，但是我反复测试都感觉不到有什么不一样的地方，并没有想到要和dokodemo监听的地址配合。所以后来写教程时就直接没写 --on-ip

**Comment by ToutyRater** [comment]
好像还存在一个问题，我这么理解你看对不对。如果 iptables 指定了 --on-ip 127.0.0.1，dokodemo也指定监听127.0.0.1，按你的描述这是可以正常使用的。我想知道的是，这会不会导致本来源地址内网其他设备的 IP `192.168.200.7`，经过 iptables 送入 dokodemo 之后，V2Ray 识别到的源地址已经不是 `192.168.200.7`

**Comment by Vigilans** [comment]
@ToutyRater V2Ray Dokodemo处理函数中有一句代码就是打印传给Dokodemo的连接的源地址的：

https://github.com/v2fly/v2ray-core/blob/2c49559c618941baf5dd2f0078ee6b10db6a3ccc/proxy/dokodemo/dokodemo.go#L112-L118

其中`conn.RemoteAddr()`获取到的就是客户端设备源地址。（Remote是相对于Dokodemo Inbound这个Server的，LocalAddr()即为Dokodemo Server监听的IP:Port）

因此可以在日志中通过筛选这一句来确认V2Ray识别到的源地址：
```
$ journalctl -u v2ray -f -n 100 | grep "received request for"
[213223273]  v2ray.com/core/proxy/dokodemo: received request for 192.168.200.7:33640
[3088536205] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.7:56681
[2362926342] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.8:123
[3474638906] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.7:56798
[2377829117] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.8:123
[1186549181] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.7:55482
[1353602185] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.8:123
[4105656159] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.7:53849
[3045925870] v2ray.com/core/proxy/dokodemo: received request for 192.168.200.8:123
[349077685]  v2ray.com/core/proxy/dokodemo: received request for 192.168.200.8:123
[39384329]   v2ray.com/core/proxy/dokodemo: received request for 192.168.200.7:49684
```
可以看到收到的是正常的`192.168.200.7`。

在https://powerdns.org/tproxydoc/tproxy.md.html 的5.2节中：
> The basic syntax is:
> iptables -t mangle -A PREROUTING -p tcp --dport 25 -j TPROXY --tproxy-mark 0x1/0x1 --on-port 10025 --on-ip 127.0.0.1
> 
> This says: take everything destined for a port 25 on TCP and deliver this for a process listening on 127.0.0.1:10025 and mark the packet with 1.
> This mark then makes sure the packet ends up in the right routing table.

--on-ip与--on-port用来定位监听的V2Ray进程，--tproxy-mark打上标记后让本应通过物理网卡转发到外网的流量（FORWARD链）被强制路由到环回网卡（进入了INPUT链），从而能够让V2Ray进程收到流量。这个过程中并没有修改过地址。

**Comment by Vigilans** [comment]
不过REDIRECT不太一样，它有利用NAT修改目标地址。看了一下文档，-j REDIRECT会按照源IP隐式选择目标IP，因此只有`--to-port`参数，因此使用REDIRECT的话Dokodemo Inbound需要监听0.0.0.0。

（另查了一些资料，试着替换了行为上似乎一致的-j DNAT，本地仍能正常代理，远程设备流量在经过DNAT规则后没有响应了。由于没有研究NAT相关机制，暂时不清楚原因。）

**Comment by ToutyRater** [comment]
多谢解答，还劳烦你特意查找相关资料，这下很清楚了。
