### ISSUE TITLE
how to tunnel the whole system (windows) like tun mode in clash

### ISSUE THREAD

**Issue by fsheidaiee** [v2fly/v2ray-core#758]
Hi
I'm wondering how I can tunnel the whole windows 10 network with v2ray?
as you know clash premium has an ability for that ([tun mode](https://lancellc.gitbook.io/clash/clash-config-file/tun))
how can I do the same with v2fly core in windows 10?
thanks

**Comment by xiaokangwang** [comment]
This is certainly on the table, but no one can predict when such a feature will be introduced.

**Comment by Loyalsoldier** [comment]
V2Ray has no TUN mode for now. You can use `Proxifier` as the front proxy of V2Ray.

**Comment by mehdifirefox** [comment]
> V2Ray has no TUN mode for now. You can use `Proxifier` as the front proxy of V2Ray.

You have complete training How to do this?

**Comment by aziziali87** [comment]
> > V2Ray has no TUN mode for now. You can use `Proxifier` as the front proxy of V2Ray.
> 
> You have complete training How to do this?

Hi Mehdi, did you find any way how to use Proxifire?
If you did, is it possible to share us?

**Comment by erfansiasi** [comment]
in version 6.23 its have "tun mode". just run it as administrator and active it and see it in blew sidbar
