### ISSUE TITLE
Access Log Shows Incomplete HTTPS Scheme but No Such Problem for HTTP

### ISSUE THREAD

**Issue by NAXX2008** [v2fly/v2ray-core#771]
## What version of V2Ray are you using?

V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 windows/amd64)

## What's your scenario of using V2Ray?

Can reproduce by visiting any HTTP and HTTPS scheme.

## What problems have you encountered?

Access log shows incomplete HTTPS scheme but no such problem for HTTP.

## What's your expectation?

Access log shows complete URL scheme.

## Please attach your configuration here

**Client configuration:**

```javascript
{
  "log": {
    "access": "D:\\Apps\\v2rayN\\Vaccess.log",
    "error": "D:\\Apps\\v2rayN\\Verror.log",
    "loglevel": "error"
  },
  ...
}
```

## Please attach access log here

```
2021/03/11 11:55:33 127.0.0.1:50306 accepted http://speedtest-sgp1.digitalocean.com/10mb.test [proxy1182] 
2021/03/11 11:55:36 127.0.0.1:50310 accepted //clientservices.googleapis.com:443 [proxy]
```

![image](https://user-images.githubusercontent.com/16894061/110741162-2fcee100-826f-11eb-9f68-65f7df40acfe.png)

**Comment by database64128** [comment]
This is expected.
