### ISSUE TITLE
Generalized V2Ray URI scheme for config sharing

### ISSUE THREAD

**Issue by henrypijames** [v2fly/v2ray-core#774]
V2Ray started with VMess and came with a well defined `vmess:` URI scheme for config sharing - particularly convenient with QR code. Now, not only has VMess itself evolved, but V2Ray supports a much wider collection of protocols - and its config sharing ability has fallen behind. We need a new `v2ray:` (or similar) URI scheme that is
as generalized, modular and future-proof as V2Ray itself.

**Comment by xiaokangwang** [comment]
Actually, there is an ongoing internal discussion about the format of the subscription format. But for url, there isn't a discussion right now since it could be much more difficult to represent the complex configure format of V2Ray using it in a idiomatic way.

**Comment by Abbode** [comment]
@henrypijames  Did you find a solution for sharing config file with URI and/or QR code ?
