### ISSUE TITLE
need help error with Critical Warning: potentially invalid user: a non VMessAEAD

### ISSUE THREAD

**Issue by malikshi** [v2fly/v2ray-core#782]
## What version of V2Ray are you using?
v4.36.0

same version

## What's your scenario of using V2Ray?
this the scenario I am usually using, trojan-gfw running at port 443 with Nginx proxy for path v2ray 127.0.0.1 10000. nothing wrong before update to the latest version. 
## What problems have you encountered?
after updated log warning 
`[Warning] github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection`

is it any changes at default for the v2ray config?
`trojan`
 >"run_type": "server",
  "local_addr": "0.0.0.0",
  "local_port": 443,
  "remote_addr": "127.0.0.1",
  "remote_port": 80,

`v2ray`
>{
  "inbounds": [
    {
      "port": 10000,
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "fb5bbbbc-ebd3-45b5-9897-08687a0f1467",
            "email": "domain,com",
            "alterId": 16
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/pathws"
        },
        "sockopt": {
          "mark": 0,
          "tcpFastOpen": true
        }
      },
      "domain": "domain,com"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "tag": "IPv4-out"
    }
  ],
  "dns": {
    "servers": [
      "https+local://cloudflare-dns.com/dns-query",
      "1.1.1.1",
      "1.0.0.1",
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  }
}

`nginx`
>location /pathws {
        access_log off;
        proxy_pass http://127.0.0.1:10000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

**Comment by Loyalsoldier** [comment]
Just update your VMess to VMessAEAD https://www.v2fly.org/config/protocols/vmess.html

**Comment by malikshi** [comment]
thank you for pointing the reference
