### ISSUE TITLE
v2ray-core listening error?

### ISSUE THREAD

**Issue by FengZhg** [v2fly/v2ray-core#804]
### PART1
while v2ray-core version is **the latest maybe 4.36.2**, and listening ip is **0.0.0.0**, 
![image](https://user-images.githubusercontent.com/53263520/111861766-b7ad9d00-898b-11eb-8b26-828ea5c90d84.png)

and now client **can't** establish a connection with the v2ray server.

### PART2
base on part1 ,when i change the listen ip to **my vps ip**,
![tempsnip](https://user-images.githubusercontent.com/53263520/111861678-23dbd100-898b-11eb-9588-b7ba8e6d5da6.png)

now client **can** establish a connection with the v2ray server.

### part3
base on part1 ,when i change the **v2ray-core version to 4.34.0**
it is still listen on tcp6.
![image](https://user-images.githubusercontent.com/53263520/111861716-5a195080-898b-11eb-934e-ea903bce8be4.png)

but it does worked , so maybe their is some thing wrong in the latest v2ray-core release?

**Comment by xieccc** [comment]
you can use telnet to test the listening port

**Comment by FengZhg** [comment]
> you can use telnet to test the listening port

i‘m sure that it was listening, i have tried to use telnet, all goes well

**Comment by e2ge** [comment]
sysctl net.ipv6 | grep bindv6only
to see if this value is 1, if yes, you need to change it to 0

**Comment by FengZhg** [comment]
> sysctl net.ipv6 | grep bindv6only
> to see if this value is 1, if yes, you need to change it to 0
![image](https://user-images.githubusercontent.com/53263520/111944993-cd4dce80-8b13-11eb-8296-db3222ae54ac.png)
it runs in docker, i think all should be the default.
it is already 0. listening on tcp6 doesn't matter on the previous release.
as long as i change the release version to a **previous** one, all goes well.
So, i came here to see anybody met the same problem with me.

**Comment by xieccc** [comment]
If the telnet is normal and the port can communicate normally, there will be no problem with the v2ray service.

**Comment by FengZhg** [comment]
> If the telnet is normal and the port can communicate normally, there will be no problem with the v2ray service.

it should like this theoretically, however client can't connect to server in fact.

**Comment by FengZhg** [comment]
maybe there is some thing wrong with v2-ui ? and only occur when using the latest version of v2ray-core

**Comment by xieccc** [comment]
Can you put the core log here?

**Comment by FengZhg** [comment]
> Can you put the core log here?
I tried to reproduce this problem, and show you the whole procedure yesterday.
On two different server, with the same config, however i can't reproduce it anymore, maybe there were some accidental problem that day.
thx for your reply. Sorry to bother you.
