### ISSUE TITLE
负载均衡提示找不到对应的balancer

### ISSUE THREAD

**Issue by yuzenan888** [v2fly/v2ray-core#827]
## 你正在使用哪个版本的 V2Ray？

```
4.36.2
```

## 你的使用场景是什么？

用内置的负载均衡器实现HA。

## 你看到的异常现象是什么？

无法启动程序，提示:
```
main: failed to create server > github.com/v2fly/v2ray-core/v4/app/router: balancer MY-HA not found
```

## 你期待看到的正常表现是怎样的？

程序正常启动。

## 请附上你的配置

**服务端配置：**

```javascript
N/A
```

**客户端配置：**
```javascript
// routing part only
"routing": {
	"strategy": "rules",
	"settings": {
		"domainStrategy": "AsIs",
		"domainMatcher": "mph",
		"balancers": [
			{
				"tag": "MY-HA",
				"selector": ["PROXY-US", "PROXY-HK", "PROXY-JP"]
			}
		],
		"rules": [
				{
				"type": "field",
				"inboundTag": "HTTP",
				"domain": [
					"full:mywebsite.com"
				],
				"balancerTag": "MY-HA"
			}
		]
	}
}
```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
N/A
```

**客户端错误日志：**

```javascript
V2Ray 4.36.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.2 darwin/amd64)
A unified platform for anti-censorship.
2021/03/26 22:44:00 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /Users/zenandidi/.config/v2ray.json
main: failed to create server > github.com/v2fly/v2ray-core/v4/app/router: balancer MY-HA not found
```

## 请附上访问日志

```javascript
N/A
```

## 其它相关的配置文件（如 Nginx）和相关日志
N/A

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出
N/A

## 如果 V2Ray 服务运行异常，请附上 journal 日志

N/A

Thanks.

**Comment by kingwilliam** [comment]
参考:
https://www.v2fly.org/config/routing.html#routingobject
正确格式
```
"routing":
{
    "domainStrategy": "",
    "domainMatcher": "",
    "rules": [],
    "balancers": []
}

```
你的格式
```
"routing": {
	"strategy": "rules",
	"settings": {
		"domainStrategy": "AsIs",
		"domainMatcher": "mph",
		"balancers": [
			{
				"tag": "MY-HA",
				"selector": ["PROXY-US", "PROXY-HK", "PROXY-JP"]
			}
		],
		"rules": [
				{
				"type": "field",
				"inboundTag": "HTTP",
				"domain": [
					"full:mywebsite.com"
				],
				"balancerTag": "MY-HA"
			}
		]
	}
}
```

尝试修改
```
"routing": {
    "domaintrategy": "AsIs",
    "domainMatcher": "mph",
    "balancers": [
        {
            "tag": "MY-HA",
            "selector": ["PROXY-US", "PROXY-HK", "PROXY-JP"]
        }
    ],
    "rules": [
        {
            "type": "field",
            "inboundTag": "HTTP",
            "domain": [
                full:mywebsite.com"
            ],
            "balancerTag": "MY-HA"
        }
    ]
}
```

**Comment by yuzenan888** [comment]
> 参考:
> https://www.v2fly.org/config/routing.html#routingobject
> 正确格式
> 
> ```
> "routing":
> {
>     "domainStrategy": "",
>     "domainMatcher": "",
>     "rules": [],
>     "balancers": []
> }
> ```
> 
> 你的格式
> 
> ```
> "routing": {
> 	"strategy": "rules",
> 	"settings": {
> 		"domainStrategy": "AsIs",
> 		"domainMatcher": "mph",
> 		"balancers": [
> 			{
> 				"tag": "MY-HA",
> 				"selector": ["PROXY-US", "PROXY-HK", "PROXY-JP"]
> 			}
> 		],
> 		"rules": [
> 				{
> 				"type": "field",
> 				"inboundTag": "HTTP",
> 				"domain": [
> 					"full:mywebsite.com"
> 				],
> 				"balancerTag": "MY-HA"
> 			}
> 		]
> 	}
> }
> ```
> 
> 尝试修改
> 
> ```
> "routing": {
>     "domaintrategy": "AsIs",
>     "domainMatcher": "mph",
>     "balancers": [
>         {
>             "tag": "MY-HA",
>             "selector": ["PROXY-US", "PROXY-HK", "PROXY-JP"]
>         }
>     ],
>     "rules": [
>         {
>             "type": "field",
>             "inboundTag": "HTTP",
>             "domain": [
>                 full:mywebsite.com"
>             ],
>             "balancerTag": "MY-HA"
>         }
>     ]
> }
> ```

多谢指点，已经正常！看了下文档，原来是routing配置的格式变了，原来一直用的是旧版配置格式。
