### ISSUE TITLE
V4.63.2客户端不发送grpc serviceName参数

### ISSUE THREAD

**Issue by gitgayhub** [v2fly/v2ray-core#828]
## 你正在使用哪个版本的 V2Ray？

服务器和客户端均为V4.36.2 Linux 64位，服务器使用caddy2反代grpc，中间经过cloudflare cdn

## 你看到的异常现象是什么？

服务器上caddy2的访问日志显示v2ray客户端并未发送grpc的serviceName，caddy2请求日志如下

` {"request": {"remote_addr": "[xxx]:31460", "proto": "HTTP/2.0", "method": "POST", "host": "host", "uri": "//Tun", "headers": {"Cdn-Loop": ["cloudflare"], "Accept-Encoding": ["gzip"], "Te": ["trailers"], "Cf-Visitor": ["{\"scheme\":\"https\"}"], "Cf-Connecting-Ip": ["ip"], "Cf-Request-Id": ["id"], "Cf-Ipcountry": ["CN"], "X-Forwarded-For": ["ip"], "Cf-Ray": ["xxx"], "X-Forwarded-Proto": ["https"], "Content-Type": ["application/grpc+proto"], "User-Agent": ["grpc-go/1.36.0"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "proto_mutual": true, "server_name": "xxx"}}, "duration": 0.000396009, "status": 502, "err_id": "id", "err_trace": "reverseproxy.statusError (reverseproxy.go:783)"}`

其中"uri": "//Tun"中的serviceName是空白的。

v2ray服务器端的日志如下

`2021/03/29 15:15:44 [Info] [1886718610] github.com/v2fly/v2ray-core/v4/app/proxyman/inbound: connection ends > github.com/v2fly/v2ray-core/v4/proxy/vmess/inbound: connection ends > github.com/v2fly/v2ray-core/v4/proxy/vmess/inbound: failed to transfer request > github.com/v2fly/v2ray-core/v4/transport/internet/grpc/encoding: unable to read from gun tunnel > rpc error: code = Canceled desc = context canceled`

v2ray客户端日志
`2021/03/29 15:15:57 [Warning] [3815883603] github.com/v2fly/v2ray-core/v4/app/proxyman/outbound: failed to process outbound traffic > github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound: connection ends > github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound: failed to read header > github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding: failed to read response header > github.com/v2fly/v2ray-core/v4/transport/internet/grpc/encoding: unable to read from gun tunnel > rpc error: code = Unknown desc = : HTTP status code 521; transport: missing content-type field`

**客户端配置：**

```javascript
"streamSettings": {
		"network": "grpc",
		"security": "tls",
		"tlsSettings": {
				"serverName": "xxx.com"
		},
		"grpcSettings": {
				"serviceName": "xxxxxxx"
		}
}

```

**Comment by k79e** [comment]
服务器也没法设定这个 填了跟没填一样

**Comment by gitgayhub** [comment]
另外客户端如果配置了mux enabled=true的话可以艰难地断断续续藕断丝连般地打开一些网页，如果没打开mux的话就完全不能连接。

相同的配置文件，如果使用xray 1.40客户端的话会发送正确的serviceName到服务器，但是不能上网。

**Comment by kslr** [comment]
这是个已知问题，等下个版本
