### ISSUE TITLE
securedload cannot load files on windows

### ISSUE THREAD

**Issue by dyhkwong** [v2fly/v2ray-core#849]
## What problems have you encountered?

browser forwarder failed to load on windows

## Please attach error logs here
```
app/browserforwarder: cannot load necessary resources > common/platform/securedload: embedded is not loading executable file > common/platform/securedload: Unrecognized file at browserforwarder\index.html can not be loaded for execution
```

need to replace `/` with `\`  in `embedded.go` or use `path/filepath.ToSlash` when comparing

**Comment by xiaokangwang** [comment]
Fixed in https://github.com/v2fly/v2ray-core/commit/93e44b72d9f13afb35e04433230ea4df5546dc21.
Please wait for release.

**Comment by dyhkwong** [comment]
working fine now, thanks!
