### ISSUE TITLE
WS 0rtt 发送url错误

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#859]
2021-04-05 13:57:42
一开始以为是域名错了. 现在我也不清楚 还没仔细测试. 我只测试了vless+ws 明文 发现是地址错了
实际发送的地址应该是 `wsaddr?0rttdata` 但是目前发送的是 `wsaddr0rttdata `导致根本没那个挂载点 
所以bug是 问号少了

## What version of V2Ray are you using?

v4.37.0

## What's your scenario of using V2Ray?

自定义tls sni时 使用ws 0rtt

## What problems have you encountered?

~在需要发送sni和server address不同的时候 需要按照tls里面的servername来发送
或者如果没配置这个 wsSettings里面如果有写host 就应当发送过去才对. 
目前如果开启0rtt 就会按照serveraddress的地址来走 结果跑出个404 not found.~
因为日志记录的地址没什么帮助 所以当时猜错了

## What's your expectation?
应当按照正确地址来发送数据

## Please attach your configuration here

**Server configuration:**

```javascript
// Please attach your server configuration here.

```

**Client configuration:**

```javascript
// Please attach your client configuration here.

```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.
[Warning] failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: Unable to proceed with delayed write > transport/internet/websocket: failed to dial to (wss://wrongdomain.cc/wsaddr) with early data: 404 Not Found > websocket: bad handshake
```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

**Comment by gitgayhub** [comment]
问题复现。caddy日志里tls server_name是有的，ws没有host，caddy回复404，我半天还没搞明白为什么会是404

**Comment by k79e** [comment]
我详细测试下去
分析出来了 是少了个问号 地址错的

**Comment by gitgayhub** [comment]
> 我详细测试下去
> 分析出来了 是少了个问号 地址错的

确实是这样，wspath后面直接跟上的early data，没有问号分割。404是v2ray服务器返回的，不是caddy自己返回的

**Comment by gitgayhub** [comment]
我又在caddy的配置中把wsaddr0rttdata自动替换为wsaddr?0rttdata，再传递给v2ray，还是不能上网。caddy返回status code是101，v2ray服务端debug模式没有任何日志输出

**Comment by Loyalsoldier** [comment]
Fixed in https://github.com/v2fly/v2ray-core/commit/3a77bbdf6522021b482556e04e2605159973976f

**Comment by k79e** [comment]
用了那个新版本没啥改变啊!??

**Comment by k79e** [comment]
换了4.37.1 最新那个commit的版本 还是老样子啊 还是wsaddr后面没问号

**Comment by gitgayhub** [comment]
> 换了4.37.1 最新那个commit的版本 还是老样子啊 还是wsaddr后面没问号

没有问号，但是能上网了。v2ray的实现应该和xray不一样，不需要加问号吧

**Comment by k79e** [comment]
不可能我还是报错 和老版本一样
你上错网了是不是 没走代理 直接直连了

**Comment by k79e** [comment]
```
 [Warning] V2Ray 4.37.1 started
[Warning] [4011855057] app/proxyman/outbound: failed to proc
ess outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbo
und: failed to write A request payload > transport/internet/websocket: Unable to
 proceed with delayed write > transport/internet/websocket: failed to dial to (w
s://xxxxx/xxx) with early data: 404 Not Found > websocket: bad handshak
e
```

**Comment by k79e** [comment]
@gitgayhub 你咋上网的 用的啥版本???

**Comment by gitgayhub** [comment]
> @gitgayhub 你咋上网的 用的啥版本???

我客户端和服务器端都是v4.37.1，vmess。肯定没有连错，我还专门看了服务器caddy的日志

**Comment by k79e** [comment]
我用的vless咋就不行!!?

**Comment by Loyalsoldier** [comment]
也许可能是 VLESS 有 bug

**Comment by k79e** [comment]
vmess也用了也不行!!! 你哪里下载的那个新版本?
我用的这个md5的96ADF5C45DFFC9DC5A8702D5B6786AEA

**Comment by k79e** [comment]
下载了预发行版的也是一样 太奇怪了吧

**Comment by gitgayhub** [comment]
> vmess也用了也不行!!! 你哪里下载的那个新版本?
> 我用的这个md5的96ADF5C45DFFC9DC5A8702D5B6786AEA

我用的pre-release里的v4.37.1

你是不是服务器端没有配置maxearlydata？客户端和服务端都同时配置才行

**Comment by k79e** [comment]
双边配置可以了 但是这个 他不是说是服务器端自动适配么??

**Comment by gitgayhub** [comment]
> 双边配置可以了 但是这个 他不是说是服务器端自动适配么?? 额可能我记错什么了

我没看到谁这么说过

**Comment by k79e** [comment]
@Loyalsoldier 对了 我想问下这个补丁修的是什么问题哇? 
他是问号的问题还是其他问题呢!?? 问号看起来现在还没有哇

**Comment by xiaokangwang** [comment]
> 双边配置可以了 但是这个 他不是说是服务器端自动适配么?? 额可能我记错什么了

文档里面是 `对于接收端，任何非0数值都代表接受前置数据。` 所以说是需要双端配置的。

默认行为是不发问号的。如果想发问号可以在客户端和服务器端的配置里面的路径的部分都在结尾加个问号。这个方案目的是保证内容尽可能的可配置。
