### ISSUE TITLE
v2ray的ip判定算法是不是也同样高效，是否存在提升空间？

### ISSUE THREAD

**Issue by redstoneleo** [v2fly/v2ray-core#871]
这个问题起源于这里
https://github.com/Qv2ray/Qv2ray/issues/1049#issuecomment-814204897
https://github.com/Qv2ray/Qv2ray/issues/1049#issuecomment-814246999
我把这个[pac](https://github.com/iBug/pac/releases)用在trojan-qt5里之后感觉比Qv2ray还流畅快速，所以就疑惑v2ray的ip判定算法是不是也同样高效，是否存在提升空间。但是我读不懂v2ray的代码，所以请开发者参考pac里的算法，核实v2ray的ip判定算法是不是也同样高效，是否存在提升空间，谢谢！

**Comment by database64128** [comment]
Apparently you know nothing about algorithms.
