### ISSUE TITLE
Proposal for resolving local domain in built-in DNS

### ISSUE THREAD

**Issue by Vigilans** [v2fly/v2ray-core#88]
#### 你正在使用哪个版本的 V2Ray？

4.27.0

#### 你的使用场景是什么？

透明代理/开放DNS服务器到53端口供局域网内使用

#### 你看到的不正常的现象是什么？

V2Ray的内置DNS拒绝解析无点的域名。无点的域名不仅不能交由DNS Server解析，也无法进入Static Host查询：
https://github.com/v2fly/v2ray-core/blob/1664b4ec9c4252209ce00fd654d18a091dd0b381/app/dns/server.go#L300-L315

这导致的问题有：
* 无法解析localhost。
* 无法解析自己的主机名 (某些版本下sudo会往DNS查询主机名，本来通过`systemd-resolved`之类服务可以正确返回，但送给V2Ray后会被拒绝且不给回复，导致sudo卡很长一段时间才有响应，见https://github.com/v2ray/v2ray-core/issues/2618 )。
* 无法解析诸如`Mijia Cloud`之类的似乎是路由器设定的域名（然后被路由器内置DNS返回IP），见https://github.com/v2ray/v2ray-core/issues/1913, https://github.com/v2ray/v2ray-core/issues/2615 。
* 在安卓端使用时，会在日志中看到大量意义不明的乱码无点域名查询，导致日志刷出大量的invalid domain name。
* 一些公司内网的管理页面就是无点域名。

#### 你期待看到的正确表现是怎样的？

内置DNS应当对无点/本地域名提供更好的支持，包括：
* 允许无点域交由Static Host与DNS Server查询，并且提供对于无点域的匹配能力。
* 由于无点域及本地域名往往只有本地DNS才能给出解析，因此对于该类域名应优先交给系统DNS处理。

以下是对支持方法的提案：
* 移除对于域名是否带点的检查。
* 提供一个新规则: `dotless:<substr>`。该规则用于匹配无点域名。当`<substr>`被设置时，无点的域名需要进一步匹配作为子串的`<substr>`。未设置时则匹配所有无点域名。
* 当DNS服务器中设置了`"localhost"`且没有为其设置`"domain"`字段时，默认为其配置三条匹配规则：无点域名、`.local`域名与`.localdomain`域名。也即以下配置：
   ```javascript
    "servers": ["localhost"]
   ```
   与以下配置等价：
   ```
   "servers": [{
      "address": "localhost",
      "domains": ["dotless:", "domain:local", "domain:localdomain"]
    }]
   ```
   这样只在本地有意义的域名将优先送给`"localhost"`查询，而非经过外部DNS然后返回大量的SERVFAIL。

#### 参考资料

* [dotless domains的命名](https://tools.ietf.org/html/rfc7085)
* [.local与.localdomain域名的使用](https://www.reddit.com/r/PFSENSE/comments/9yw969/using_local_or_localdomain_versus_real)
* [家庭网络中的home.arpa.?](https://tools.ietf.org/html/rfc8375)

**Comment by Loyalsoldier** [comment]
容我厚颜无耻地提一个请求：方便的话，麻烦把 DNS 模块的这个 bug 也修一下 https://github.com/v2fly/domain-list-community/issues/91#issuecomment-665583837

路由模块对于规则都是优先匹配，而 DNS 模块对于规则是最后匹配，希望 DNS 模块跟路由模块保持一致：优先匹配域名。

**Comment by Vigilans** [comment]
@Loyalsoldier hhh这个我也注意到了，当时看了代码，这是因为用于域名匹配的Trie树实现造成的问题，导致后插入的优先匹配。

当初想一起提的，不过后来觉得跟问题不是很相关，还是个breaking change（虽然利用这个feature的估计很少……），并且调教出了合适的配置，就先放着了。。
