### ISSUE TITLE
TLS Fingerprint

### ISSUE THREAD

**Issue by eroxs** [v2fly/v2ray-core#883]
How can we change the fingerprint? I am going to use uTLSand use Firefox or Chrome browser.

**Comment by AkinoKaede** [comment]
You can use browser forwarder

**Comment by eroxs** [comment]
what do you mean ?
Xray core add Add uTLS fingerprints in project but v2flay doesnt have this

**Comment by AkinoKaede** [comment]
> what do you mean ?
> Xray core add Add uTLS fingerprints in project but v2flay doesnt have this

https://www.v2fly.org/config/browserforwarder.html

You can add uTLS to V2Ray by yourself...

**Comment by eroxs** [comment]
Can we go private?
I need guidance
I am from Iran and I need your help 
if have Telegram id or mail ...

**Comment by AkinoKaede** [comment]
If you don't know how to develop this project, and don't require some features of V2Ray, such as WebSocket early data, you can use Xray-core to use uTLS, it's compatible with most features of V2Ray.

**Comment by AkinoKaede** [comment]
Because of the license, we need rewirte the code of uTLS support in Xray-core or get rprx's permission to add uTLS to V2Ray.

**Comment by eroxs** [comment]
I think rprx allows. It is better to maneuver on this issue and consult with each other. 
Does not xray core support websocket?
I have ws + tls + cdn configuration
