### ISSUE TITLE
路由设置中的反向匹配"geoip:!cn"不可用,///"geosite:!cn",不可用

### ISSUE THREAD

**Issue by wutongskype** [v2fly/v2ray-core#885]
![Snipaste_2021-04-10_23-14-38](https://user-images.githubusercontent.com/40192806/114274757-8d16a780-9a52-11eb-977e-ff479baef1d1.jpg)

日志提示无效规则说明里却又反向匹配这么一说

**Comment by Loyalsoldier** [comment]
这周刚新增的功能，请使用 [**v4.37.2**](https://github.com/v2fly/v2ray-core/releases/tag/v4.37.2)

**Comment by Loyalsoldier** [comment]
另外，geosite 不支持反向匹配。
