### ISSUE TITLE
[Feature request] Manual set the buffer of mux

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#899]
It usually happens that a connection of mux is slow while other is very fast.
The slower one don't even have packet loss.

Maybe the buffer is not enough when rtt is high?

**Comment by database64128** [comment]
Just your ISP's typical everyday QoS.

**Comment by database64128** [comment]
#898

**Comment by k79e** [comment]
Will your qos give your old connections more speed?!!
It stucks when mux created a new connection.
if speed of the new conn is limited what about created a new one immediately and it's back to normal?

**Comment by k79e** [comment]
Can you explain why on this flow there are many fragment segments? The packet sliced to hundreds kb rather 1.x kb
![2021-04-13_202536](https://user-images.githubusercontent.com/6483602/114551892-8d06e980-9c96-11eb-9984-0c9a28131b5b.png)

Make packet smaller will do addition calculation. Why v2ray did this!??

**Comment by k79e** [comment]
![2021-04-13_204828](https://user-images.githubusercontent.com/6483602/114554731-9f365700-9c99-11eb-99df-51af5e33111e.png)
Another one flow that have medium speed.
Srcport filtered. Notice that there don't exist many packet which their length is around 40-50k

The length of psh,ack **don't act same as slower one**
![2021-04-13_204943](https://user-images.githubusercontent.com/6483602/114554953-d442a980-9c99-11eb-8642-9714312260b7.png)

**Comment by k79e** [comment]
Reproduced in lan environment with 0% pktloss

**Comment by k79e** [comment]
Notice that port 13325 have sky high speed but port 13564 is very slow.
Within 1s vs around 3s load time (download a same file)
