### ISSUE TITLE
你们arm64包改名了,要更新

### ISSUE THREAD

**Issue by mbcc2006** [v2fly/v2ray-core#90]
https://github.com/v2fly/v2ray-core/releases/download/v4.27.0/v2ray-linux-arm64.zip这个包被你们改名了,导致更新失败.
root@pizero5:~# ./go.sh -p http://192.168.193.76:2080
Installing V2Ray v4.27.0 on aarch64
Downloading V2Ray: https://github.com/v2fly/v2ray-core/releases/download/v4.27.0/v2ray-linux-arm64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0      1      0  0:00:09  0:00:05  0:00:04     2
awk: not an option: -e
[/tmp/v2ray/v2ray.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Shutting down V2Ray service.
Archive:  /tmp/v2ray/v2ray.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Failed to copy V2Ray binary and resources.

**Comment by IceCodeNew** [comment]
请换用新版的安装脚本来更新（请注意遵照官方文档中给出的迁移建议

Refer: https://www.v2fly.org/guide/install.html#linux-%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC
