### ISSUE TITLE
疑似路由有bug IP和域名连个一起写的时候 2个都不生效

### ISSUE THREAD

**Issue by k79e** [v2fly/v2ray-core#902]
是不能这样用么? 我看说明书好像也没写不能这样啊

"routing": {
    "domainStrategy": "asis",
    "rules": [
      {
        "type": "field",
        "port": null,
        "outboundTag": "block",
		"#protocol": [  "http","tls"	],
		"ip":"1.1.1.1",
		"domain":"t.cn"
      }
...
我是在server里面写的

像这个他不是把4个1的封了 然后t.cn也封锁么? 难道他们的关系是 ip and domain!??
就关于ip和域名一切写的 开不开嗅探都一样 这样用的话始终都是2个都不生效

**Comment by U-v-U** [comment]
没错，就是 and 的关系

**Comment by k79e** [comment]
建议说明书注明下比较好

**Comment by database64128** [comment]
The documentation specifically mentioned this: https://www.v2fly.org/config/routing.html#ruleobject
