### ISSUE TITLE
v2ray反向代理模式存在明显BUG

### ISSUE THREAD

**Issue by xingzhuanxing** [v2fly/v2ray-core#91]
我简单阐述一下吧，因为我的问题不表现在日志中。（日志无法反映出实际的问题）

v2ray工作模式：反向代理2 （内网A主动连接公网B，C通过A代理访问内网）
v2ray-core版本：刚下载的最新版
运行环境：A ubuntu20.04，B ubuntu20.04，C windows
具体问题：
C多线程下载大文件（100MB以上），中途取消下载并断开C与B的连接，此时内网A依然持续给公网B传输数据（未下载完的那部分数据）。

因此在客户端C断开后， A和B之间持续连接并传输数据，造成大量带宽的占用。导致后续客户端C继续使用连接时，可用带宽不足

我怀疑应该是工作模式上没协调好，B的left跟right的数据接收和转发没有进行有效的关联。当C断开后，没有通知A将C的数据交换队列作废

**Comment by Asgore0** [comment]
把mux关了试试？

**Comment by xingzhuanxing** [comment]
> 把mux关了试试？

默认是开启的。能关闭吗？

你试过效果？

**Comment by Asgore0** [comment]
> > 把mux关了试试？
> 
> 默认是开启的。能关闭吗？
> 
> 你试过效果？
客户端关闭就可以。

**Comment by xingzhuanxing** [comment]
> > > 把mux关了试试？
> > 
> > 
> > 默认是开启的。能关闭吗？
> > 你试过效果？
> > 客户端关闭就可以。

客户端没有开Mux

**Comment by chinalichen** [comment]
老哥最后怎么解决的？我这边用的最新版，依旧有这个问题。
