### ISSUE TITLE
Bittorrent Sniffing does not support uTP

### ISSUE THREAD

**Issue by Vigilans** [v2fly/v2ray-core#93]
#### 你正在使用哪个版本的 V2Ray？

4.27.0

#### 你的使用场景是什么？

BT流量直连/抛弃。

#### 你看到的不正常的现象是什么？

Sniffing功能似乎只支持基于TCP的Bittorrent 1.0协议，而不支持基于UDP的uTP协议。

理论基于以下两点：
* 只在TCP流量中才有Sniffing处理代码：
https://github.com/v2fly/v2ray-core/blob/65c16cd44c1576bb5e3a9cd29f5cc3795d5e61fa/app/dispatcher/default.go#L205-L225

* Bittorrent Sniffer里只对1.0版本基于TCP的协议的握手包有嗅探（即检测"Bittorrent Protocol"的存在）：
https://github.com/v2fly/v2ray-core/blob/65c16cd44c1576bb5e3a9cd29f5cc3795d5e61fa/common/protocol/bittorrent/bittorrent.go#L22-L32

以及现象基于以下两点：
* 客户端设置了BT直连，服务端设置了BT堵塞，但在过去半年间吃了三次DMCA Request（。）
* 传输了BT流量的设备使用了Mellow，通过TUN模式其能接收UDP流量，并对非CN IP选择了代理，因此服务端是有可能收到uTP流量并因没有嗅探到BT协议而放行的。

#### 你期待看到的正确表现是怎样的？

~~不再吃DMCA Requests了~~对于一般情况下的两种BT协议（TCP，uTP）能准确嗅探以在路由中匹配。

#### Access / Error 日志

由于对BT原理了解不足，暂没有准备好环境提供测试复现。这个Issue是在看了Sniffing相关代码有一些原理上的疑惑后发出来的，希望得到社区的解惑。条件合适时会仔细测试并提供日志。

**Comment by Loyalsoldier** [comment]
用 Proxifier 也会遇到这个问题，即使设置了 BT 直连，也会触发服务商对 BT 流量审查。

**Comment by kslr** [comment]
因为目前 UDP over TCP

**Comment by escape0707** [comment]
此问题仍未解决，希望能够打上`actions/stale`中的`exempt-issue-labels`中的标签？

**Comment by Vigilans** [comment]
@escape0707 如果使用场景是透明代理的话，可以参考下这个基于iptables的解决方案：
* 使用更加成熟的DPI来嗅探BT流量: https://github.com/betolj/ndpi-netfilter, https://github.com/vel21ripn/nDPI/tree/flow_info-3.2/ndpi-netfilter （V2Ray要实现uTP Sniffing可能也得根据这个的实现走……）
* v2ray只使用TPROXY代理TCP流量(+DNS流量）（大流量如访问网站，看视频，及下载走V2Ray）
* 其余所有流量（UDP, ICMP）走自组网的VPN，如OpenVPN（小流量如游戏流量走OpenVPN，FullCone支持程度好）

iptables的设置部分大概如下：
```
-A proxy -m ndpi --bittorrent -j RETURN # Do not mark Bittorrent connections
-A proxy   -p tcp -g mark_v2ray
-A proxy ! -p tcp -g mark_openvpn
```

**Comment by escape0707** [comment]
@Vigilans 您这个相当高级了。也有其他依赖软件需要学习哈哈😄

我现在对路由这边的理解非常初级，而且只是客户端过滤一下，服务端用的是机场。目前的打算是因为没有用独立nas的条件所以想试试网关机上用docker跑bt客户端，防火墙里对这个docker不代理的方法。

之后再研究一下docker的网络（
