### ISSUE TITLE
VMess / AEAD 加密方式设计/实现存在的四个漏洞，附带修复建议

### ISSUE THREAD

**Issue by rprx** [v2fly/v2ray-core#942]
## 零：针对 0-RTT 未知流量代理协议的 EMP 攻击

影响范围：所有版本的 VMess 协议，无论是否 AEAD，且不止 VMess 协议，Shadowsocks 等也受影响。

这个大家已经很熟悉了，一旦部署将会使所有符合条件的协议失效，详见 https://github.com/shadowsocks/shadowsocks-org/issues/184

修复建议：把它放到零是因为无解，只能从头设计新的有握手的协议，顺便实现普遍欠缺的前向安全。

## 一：VMess / AEAD 设计缺陷，Packet Length 仍未认证，可被任意修改

影响范围：此前所有版本的 VMess 协议，无论是否 AEAD（因为此前 VMess AEAD 也没有考虑该问题）

简单来说，Shadowsocks AEAD 的 length 和 payload 均有认证，**而 VMess AEAD 只认证了 payload，没有认证 length，存在隐患。**

我在几个月前已将该问题告知 @xiaokangwang ，也是我在 https://github.com/shadowsocks/shadowsocks-org/issues/183 提到的 VMess AEAD 的“其它问题”，鉴于目前已有初步修复的 PR https://github.com/v2fly/v2ray-core/pull/940 ，才发布出来说明，顺便把目前我发现的所有问题一次性说完。

**该问题修复很简单，但若默认启用会造成 VMess AEAD 的又一次 breaking change**

> 之前我提议 alterId 0 代表 AEAD，这样以后可以直接弃用 alterId，但也说了这个方法只能用一次，之后 @cute 发现 VMess AEAD 存在 responseBodyKey 和 responseBodyIV 相同的问题，修复后就出现了一次比较严重的 breaking，这里不建议再来一次。

可以考虑使用一套新的命名：

```
aead-aes-128-gcm
aead-chacha20-poly1305
aead-auto
zero
```

## 二：VMess / AEAD 发送非必要数据包，可被用于 on-path 分析、识别

影响范围：此前所有版本的 VMess 协议，无论是否 AEAD，无论套不套 TLS

摘自文档：

> 当传输结束时，客户端必须发送一个空的数据包，即 L = 0（不加密） 或认证数据长度（有加密），来表示传输结束。

实际上不止客户端 outbound 有，服务端 inbound 也有，摘自代码：

https://github.com/v2fly/v2ray-core/blob/dbfc2138e40ecaa5b594191ffb85899dc2fe99c3/proxy/vmess/outbound/outbound.go#L154-L158

https://github.com/v2fly/v2ray-core/blob/dbfc2138e40ecaa5b594191ffb85899dc2fe99c3/proxy/vmess/inbound/inbound.go#L206-L210

这...？一言难尽。关键是这个机制完全没有必要，只会带来强特征。

修复建议：删掉这种机制。

## 三：VMess AEAD 客户端 18 字节解密失败断连，in-path 即可精准识别

影响范围：此前所有版本的 VMess AEAD 协议，**这个漏洞是 0-day 级别的，非常严重。**

**利用方式：in-path 攻击者只需抓一条连接改一个字节，使客户端在 18 字节处解密失败断连，即可 100% 确定是 VMess AEAD，100%**

摘自代码：

https://github.com/v2fly/v2ray-core/blob/dbfc2138e40ecaa5b594191ffb85899dc2fe99c3/proxy/vmess/encoding/client.go#L201-L213

为什么说这是个 0-day 级别的严重漏洞？因为它非常隐蔽，我才刚发现不久，而如果发现者不发布出来，这个漏洞是一直可以被利用的，细思恐极。还是那句话，对客户端的攻击往往被忽视（好像只有我会看一下），其它协议多少也有这种情况，建议检查一下。

修复建议：drain？**但由于是客户端，难点在于所有实现的修复。**

顺便一提，对于逐字节探测，我设计 VLESS 时首创了首包长度判断分流，但这只适用于不可拆分的 packet 之上，比如 TLS 包结构。

对于 VMess AEAD 等协议的设计，如果发现新的问题，我还会提出，包括实现上的问题（比如 Go 1.16 那个差点 breaking...

**Comment by kslr** [comment]
Please follow the reporting process
