### ISSUE TITLE
How can I check the version of v2ray ?

### ISSUE THREAD

**Issue by VolinHe** [v2fly/v2ray-core#943]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/v2ray-core/discussions)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/v2ray-core/discussions) first.

This issue will be closed immediately.

**Comment by chromer030** [comment]
$ v2ray -version 
`V2Ray 4.38.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
A unified platform for anti-censorship.`
