### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MateorChan** [v2fly/v2ray-core#961]
## What version of V2Ray are you using?
V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)

## What problems have you encountered?
V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
A unified platform for anti-censorship.
2021/05/02 13:52:31 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]

goroutine 56 [running]:
github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc000a67900, 0xc0007bc090, 0x3, 0x3, 0xc0007bc090, 0x3)
	github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc003228080, 0x104bb58, 0xc0032286c0, 0xc000388660, 0x104bb58)
	github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
	github.com/v2fly/v2ray-core/v4/app/router/config.go:58
github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc0004edf40, 0x104bbc8, 0xc000116408, 0xc000116408, 0x0, 0xc00005b760, 0x8c1ab6)
	github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0004edcc0, 0x1041c20, 0xc000389e90, 0xc00007c4c0, 0x1042f28, 0xc000150090, 0x300000035)
	github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
	github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]

goroutine 65 [running]:
github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc000a67900, 0xc000844000, 0x3, 0x3, 0xc000844000, 0x3)
	github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc003228080, 0x104bb58, 0xc000842000, 0xc000388660, 0x104bb58)
	github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
	github.com/v2fly/v2ray-core/v4/app/router/config.go:58
github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc0004edf40, 0x104bbc8, 0xc000838000, 0xc000838000, 0x0, 0xc00005af60, 0x8c1ab6)
	github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0004edcc0, 0x1041c20, 0xc0001fd200, 0xc000f78060, 0x1042f28, 0xc000150084, 0x300000035)
	github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
	github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b

## Please attach your configuration here

**Server configuration:**

```javascript
// Please attach your server configuration here.
{
  "inbounds": [
    {
      "port": 0,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxx"
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "normal",
      "protocol": "freedom",
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8"
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "normal"
      }
    ]
  }
}
```

**Client configuration:**

```javascript
// Please attach your client configuration here.
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [
    {
      "tag": "transparent",
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255,
          "tcpFastOpen": true
        }
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    },
    {
      "tag": "proxyClear1",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxx",
            "port": 0,
            "users": [
              {
                "id": "xxx"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    },
    {
      "tag": "proxyClear2",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxx",
            "port": 0,
            "users": [
              {
                "id": "xxx"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    },
    {
      "tag": "proxyClear3",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxx",
            "port": 0,
            "users": [
              {
                "id": "xxx"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    }
  ],
  "subjectSelector": [
    "proxyClear"
  ],
  "dns": {
    "servers": [
      "192.168.0.10"
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "transparent"
        ],
        "port": 123,
        "network": "udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "ip": [
          "114.114.114.114",
          "119.29.29.29",
          "223.5.5.5"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "network": "tcp,udp",
        "balancerTag": "proxyClear"
      }
    ],
    "balancers": [
      {
        "tag": "proxyClear",
        "selector": [
          "proxyClear1",
          "proxyClear2",
          "proxyClear3"
        ],
        "strategy": {
          "type": "leastPing"
        }
      }
    ]
  }
}
```

## Please attach error logs here

**Server error log:**

```javascript
// Please attach your server error log here.

```

**Client error log:**

```javascript
// Please attach your client error log here.

```

## Please attach access log here

```javascript
// Please attach your server access log here.

```

## If V2Ray cannot start up, please attach output from `--test` command
V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
A unified platform for anti-censorship.
2021/05/02 13:58:16 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Configuration OK.

## If V2Ray service is abnormal, please attach journal log here

May 02 13:58:58 yl-server systemd[1]: Started V2Ray Service.
May 02 13:58:58 yl-server v2ray[1891]: V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
May 02 13:58:58 yl-server v2ray[1891]: A unified platform for anti-censorship.
May 02 13:58:58 yl-server v2ray[1891]: 2021/05/02 13:58:58 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
May 02 13:58:59 yl-server v2ray[1891]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 13:58:59 yl-server v2ray[1891]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]
May 02 13:58:59 yl-server v2ray[1891]: goroutine 86 [running]:
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc00231d7c0, 0xc0007ba5d0, 0x3, 0x3, 0xc0007ba5d0, 0x3)
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc0004e2400, 0x104bb58, 0xc0007c0240, 0xc00047c660, 0x104bb58)
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/config.go:58
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc0004e2300, 0x104bbc8, 0xc0007b0468, 0xc0007b0468, 0x0, 0xc0022adf60, 0x8c1ab6
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00235de00, 0x1041c20, 0xc0022be960, 0xc0022bc480, 0x1042f
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
May 02 13:58:59 yl-server v2ray[1891]: created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
May 02 13:58:59 yl-server v2ray[1891]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 13:58:59 yl-server v2ray[1891]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]
May 02 13:58:59 yl-server v2ray[1891]: goroutine 134 [running]:
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc00231d7c0, 0xc0006c6180, 0x3, 0x3, 0xc0006c6180, 0x3)
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc0004e2400, 0x104bb58, 0xc0006c2100, 0xc00047c660, 0x104bb58)
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/config.go:58
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc0004e2300, 0x104bbc8, 0xc0006c0138, 0xc0006c0138, 0x0, 0xc003247f60, 0x8c1ab6
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
May 02 13:58:59 yl-server v2ray[1891]: github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00235de00, 0x1041c20, 0xc0032b2c30, 0xc00231c720, 0x1042f
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
May 02 13:58:59 yl-server v2ray[1891]: created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
May 02 13:58:59 yl-server v2ray[1891]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
May 02 13:58:59 yl-server systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 13:58:59 yl-server systemd[1]: v2ray.service: Failed with result 'exit-code'.
May 02 13:58:59 yl-server systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
May 02 13:58:59 yl-server systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
May 02 13:58:59 yl-server systemd[1]: Stopped V2Ray Service.
May 02 13:58:59 yl-server systemd[1]: Started V2Ray Service.
May 02 13:58:59 yl-server v2ray[1922]: V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
May 02 13:58:59 yl-server v2ray[1922]: A unified platform for anti-censorship.
May 02 13:58:59 yl-server v2ray[1922]: 2021/05/02 13:58:59 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
May 02 13:58:59 yl-server v2ray[1922]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 13:58:59 yl-server v2ray[1922]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]
May 02 13:58:59 yl-server v2ray[1922]: goroutine 30 [running]:
May 02 13:58:59 yl-server v2ray[1922]: github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc0009596a0, 0xc000744000, 0x3, 0x3, 0xc000744000, 0x3)
May 02 13:58:59 yl-server v2ray[1922]:         github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
May 02 13:58:59 yl-server v2ray[1922]: github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc0001d1680, 0x104bb58, 0xc000742000, 0xc000464660, 0x104bb58)
May 02 13:58:59 yl-server v2ray[1922]:         github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
May 02 13:58:59 yl-server v2ray[1922]: github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
May 02 13:58:59 yl-server v2ray[1922]:         github.com/v2fly/v2ray-core/v4/app/router/config.go:58
May 02 13:58:59 yl-server v2ray[1922]: github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc0004c7fc0, 0x104bbc8, 0xc000740000, 0xc000740000, 0x0, 0xc000054760, 0x8c1ab6
May 02 13:58:59 yl-server v2ray[1922]:         github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
May 02 13:58:59 yl-server v2ray[1922]: github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0004c7d40, 0x1041c20, 0xc000465fb0, 0xc0009e6200, 0x1042f
May 02 13:58:59 yl-server v2ray[1922]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
May 02 13:58:59 yl-server v2ray[1922]: created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
May 02 13:58:59 yl-server v2ray[1922]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
May 02 13:58:59 yl-server systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 13:58:59 yl-server systemd[1]: v2ray.service: Failed with result 'exit-code'.
May 02 13:59:00 yl-server systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
May 02 13:59:00 yl-server systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
May 02 13:59:00 yl-server systemd[1]: Stopped V2Ray Service.
May 02 13:59:00 yl-server systemd[1]: Started V2Ray Service.
May 02 13:59:00 yl-server v2ray[1952]: V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
May 02 13:59:00 yl-server v2ray[1952]: A unified platform for anti-censorship.
May 02 13:59:00 yl-server v2ray[1952]: 2021/05/02 13:59:00 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
May 02 13:59:00 yl-server v2ray[1952]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 13:59:00 yl-server v2ray[1952]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]
May 02 13:59:00 yl-server v2ray[1952]: goroutine 42 [running]:
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc0008fd900, 0xc003b78510, 0x3, 0x3, 0xc003b78510, 0x3)
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc00003c600, 0x104bb58, 0xc003b7a100, 0xc0003c3320, 0x104bb58)
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/config.go:58
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc00003c500, 0x104bbc8, 0xc0000a07b0, 0xc0000a07b0, 0x0, 0xc000e77f60, 0x8c1ab6
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00003c280, 0x1041c20, 0xc003b78390, 0xc003b68460, 0x1042f
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
May 02 13:59:00 yl-server v2ray[1952]: created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
May 02 13:59:00 yl-server v2ray[1952]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 13:59:00 yl-server v2ray[1952]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]
May 02 13:59:00 yl-server v2ray[1952]: goroutine 116 [running]:
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc0008fd900, 0xc000ee6300, 0x3, 0x3, 0xc000ee6300, 0x3)
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc00003c600, 0x104bb58, 0xc000ee0140, 0xc0003c3320, 0x104bb58)
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/config.go:58
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc00003c500, 0x104bbc8, 0xc000ede1c8, 0xc000ede1c8, 0x0, 0xc0000c2760, 0x8c1ab6
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
May 02 13:59:00 yl-server v2ray[1952]: github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00003c280, 0x1041c20, 0xc000031c20, 0xc000e68300, 0x1042f
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
May 02 13:59:00 yl-server v2ray[1952]: created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
May 02 13:59:00 yl-server v2ray[1952]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
May 02 13:59:00 yl-server systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 13:59:00 yl-server systemd[1]: v2ray.service: Failed with result 'exit-code'.
May 02 13:59:01 yl-server systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
May 02 13:59:01 yl-server systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
May 02 13:59:01 yl-server systemd[1]: Stopped V2Ray Service.
May 02 13:59:01 yl-server systemd[1]: Started V2Ray Service.
May 02 13:59:01 yl-server v2ray[1982]: V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
May 02 13:59:01 yl-server v2ray[1982]: A unified platform for anti-censorship.
May 02 13:59:01 yl-server v2ray[1982]: 2021/05/02 13:59:01 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
May 02 13:59:02 yl-server v2ray[1982]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 13:59:02 yl-server v2ray[1982]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]
May 02 13:59:02 yl-server v2ray[1982]: goroutine 11 [running]:
May 02 13:59:02 yl-server v2ray[1982]: github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc0009758a0, 0xc0000a70b0, 0x3, 0x3, 0xc0000a70b0, 0x3)
May 02 13:59:02 yl-server v2ray[1982]:         github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
May 02 13:59:02 yl-server v2ray[1982]: github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc00003c800, 0x104bb58, 0xc00003c440, 0xc00043d230, 0x104bb58)
May 02 13:59:02 yl-server v2ray[1982]:         github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
May 02 13:59:02 yl-server v2ray[1982]: github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
May 02 13:59:02 yl-server v2ray[1982]:         github.com/v2fly/v2ray-core/v4/app/router/config.go:58
May 02 13:59:02 yl-server v2ray[1982]: github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc00003c700, 0x104bbc8, 0xc000416240, 0xc000416240, 0x0, 0xc003201f60, 0x8c1ab6
May 02 13:59:02 yl-server v2ray[1982]:         github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
May 02 13:59:02 yl-server v2ray[1982]: github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00003c480, 0x1041c20, 0xc000030810, 0xc003222100, 0x1042f
May 02 13:59:02 yl-server v2ray[1982]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
May 02 13:59:02 yl-server v2ray[1982]: created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
May 02 13:59:02 yl-server v2ray[1982]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Failed with result 'exit-code'.
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
May 02 13:59:02 yl-server systemd[1]: Stopped V2Ray Service.
May 02 13:59:02 yl-server systemd[1]: Started V2Ray Service.
May 02 13:59:02 yl-server v2ray[2022]: V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
May 02 13:59:02 yl-server v2ray[2022]: A unified platform for anti-censorship.
May 02 13:59:02 yl-server v2ray[2022]: 2021/05/02 13:59:02 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
May 02 13:59:02 yl-server v2ray[2022]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 13:59:02 yl-server v2ray[2022]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa466ae]
May 02 13:59:02 yl-server v2ray[2022]: goroutine 51 [running]:
May 02 13:59:02 yl-server v2ray[2022]: github.com/v2fly/v2ray-core/v4/app/router.(*LeastPingStrategy).PickOutbound(0xc0009be300, 0xc0001a09f0, 0x3, 0x3, 0xc0001a09f0, 0x3)
May 02 13:59:02 yl-server v2ray[2022]:         github.com/v2fly/v2ray-core/v4/app/router/strategy_leastping.go:32 +0x4e
May 02 13:59:02 yl-server v2ray[2022]: github.com/v2fly/v2ray-core/v4/app/router.(*Balancer).PickOutbound(0xc0031ce080, 0x104bb58, 0xc0031ce100, 0xc00047e660, 0x104bb58)
May 02 13:59:02 yl-server v2ray[2022]:         github.com/v2fly/v2ray-core/v4/app/router/balancing.go:44 +0x17e
May 02 13:59:02 yl-server v2ray[2022]: github.com/v2fly/v2ray-core/v4/app/router.(*Rule).GetTag(...)
May 02 13:59:02 yl-server v2ray[2022]:         github.com/v2fly/v2ray-core/v4/app/router/config.go:58
May 02 13:59:02 yl-server v2ray[2022]: github.com/v2fly/v2ray-core/v4/app/router.(*Router).PickRoute(0xc0004e5f40, 0x104bbc8, 0xc00009e108, 0xc00009e108, 0x0, 0xc000605760, 0x8c1ab6
May 02 13:59:02 yl-server v2ray[2022]:         github.com/v2fly/v2ray-core/v4/app/router/router.go:78 +0x16b
May 02 13:59:02 yl-server v2ray[2022]: github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0004e5cc0, 0x1041c20, 0xc0001f1da0, 0xc0019680c0, 0x1042f
May 02 13:59:02 yl-server v2ray[2022]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:314 +0x3f3
May 02 13:59:02 yl-server v2ray[2022]: created by github.com/v2fly/v2ray-core/v4/app/dispatcher.(*DefaultDispatcher).Dispatch
May 02 13:59:02 yl-server v2ray[2022]:         github.com/v2fly/v2ray-core/v4/app/dispatcher/default.go:230 +0x31b
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Failed with result 'exit-code'.
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
May 02 13:59:02 yl-server systemd[1]: Stopped V2Ray Service.
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Start request repeated too quickly.
May 02 13:59:02 yl-server systemd[1]: v2ray.service: Failed with result 'exit-code'.
May 02 13:59:02 yl-server systemd[1]: Failed to start V2Ray Service.

**Comment by AkinoKaede** [comment]
It might be fixed by #954

**Comment by MateorChan** [comment]
update config.json

**Comment by AkinoKaede** [comment]
```json
"observatory":{
  "subjectSelector": [
    "proxyClear"
   ]
}
```

**Comment by MateorChan** [comment]
> ```json
> observatory
> ```

It works!
My bad.
