### ISSUE TITLE
[feature request] Bypassing Deep Packet Inspection (based on SNI) by HTTPS fragmentation

### ISSUE THREAD

**Issue by molink36** [v2fly/v2ray-core#976]
I can bypass deep packet inspection based on Server Name Indication (SNI) for websites and services which use HTTPS in case their IP range is not completely blocked by internet service provider's firewall. I use `GoodbyeDPI` program combined with `DNS over HTTPS` to accomplish this.

This program can be downloaded from the following link:

https://github.com/ValdikSS/GoodbyeDPI

And the parameter that I use for HTTPS fragmentation mode is:
`GoodbyeDPI.exe -e 60`

It would be great if there was an option in v2ray to fragment TLS connections for certain domains.

**Comment by ValdikSS** [comment]
@molink36, just FYI, I'm planning to implement single-application mode in GoodbyeDPI, which would allow to use it only for v2ray.
