### ISSUE TITLE
[feature request] 配置文件支持使用HOCON

### ISSUE THREAD

**Issue by timnick-snow** [v2fly/v2ray-core#978]
建议使用JSON 格式的超集HOCON来编写合法的配置文件
更加人性化

https://github.com/ustc-zzzz/HOCON-CN-Translation

**Comment by xiaokangwang** [comment]
我查看了一下现在的Go语言的HOCON的库没看见自动转换为json的功能，也就是说这个玩意并不是和json等价的。
如果想支持的话，需要有人实现一个将它和json之间互相转换的工具。
如果你有发现Go语言的将HOCON向json转换的库的话，请分享一下以便进一步讨论。
